### ISSUE TITLE
pipenv install error 

### ISSUE THREAD

**Issue by mmyydd** [pypa/pipenv#1134]
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

##### Describe your environment

1. OS Type win10 x64
1. Python version: Python 2.7.13
1. Pipenv version: version 8.3.2

##### Expected result

install this sucess
https://github.com/honeynet/droidbot

##### Actual result

pipenv install -e .
Installing -e .…
Traceback (most recent call last):
  File "C:\Python27\Scripts\pipenv-script.py", line 11, in <module>
    load_entry_point('pipenv==8.3.2', 'console_scripts', 'pipenv')()
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\pipenv\cli.py", line 1880, in install
    converted = convert_deps_from_pip(package_name)
  File "c:\python27\lib\site-packages\pipenv\utils.py", line 547, in convert_deps_from_pip
    os.path.isfile(req.name)) and not req.vcs:
  File "c:\python27\lib\genericpath.py", line 37, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

**Comment by techalchemy** [comment]
@mmyydd sorry you ran into this bug, it was resolved in #958 and #1095 and has been released today in pipenv 9.0, so you can go ahead and upgrade your pipenv and that should help.  Let me know if you have any other issues, but I'm going to go ahead and close this out for now!
