### ISSUE TITLE
.env dir breaks usage

### ISSUE THREAD

**Issue by hobofan** [pypa/pipenv#1136]
The project of a client I am working on contains top level `.env` dirs. Currently when using `pipenv shell`, this 

##### Describe your environment

1. macOs 10.12.4
1. Python version: `Python 3.6.1`
1. Pipenv version: `pipenv, version 8.3.2`

##### Expected result

Default `pipenv shell` behaviour.

##### Actual result

```
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 2085, in shell
    load_dot_env()
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 130, in load_dot_env
    dotenv.load_dotenv(denv, override=True)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/dotenv/main.py", line 27, in load_dotenv
    for k, v in dotenv_values(dotenv_path).items():
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/dotenv/main.py", line 93, in dotenv_values
    values = OrderedDict(parse_dotenv(dotenv_path))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/dotenv/main.py", line 99, in parse_dotenv
    with open(dotenv_path) as f:
IsADirectoryError: [Errno 21] Is a directory: '/Users/hobofan/XXX/postgres/.env'
```

##### Steps to replicate

1. Create new pipenv project
2. `mkdir .env` in that project directory
3. Run `pipenv shell`

**Comment by uranusjr** [comment]
As a workaround, set `PIPENV_DONT_LOAD_ENV` environment variable to a non-empty value to circumvent this code path.

**Comment by kennethreitz** [comment]
Yeah, don't do that.
