### ISSUE TITLE
python_version range specifier

### ISSUE THREAD

**Issue by crizCraig** [pypa/pipenv#1149]
Trying to get something to the effect of

```
[requires]

python_version = ">=3.5"
```

Tried

```
[requires]

python_version = {version = ">=3.5"}
```
and get
```
> pipenv install
Traceback (most recent call last):
  File "c:\users\a\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\a\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\a\Miniconda3\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "c:\users\a\miniconda3\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\a\miniconda3\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\a\miniconda3\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\a\miniconda3\lib\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\a\miniconda3\lib\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\a\miniconda3\lib\site-packages\pipenv\cli.py", line 1775, in install
    ensure_project(three=three, python=python, system=system, warn=True, deploy=deploy)
  File "c:\users\a\miniconda3\lib\site-packages\pipenv\cli.py", line 600, in ensure_project
    ensure_virtualenv(three=three, python=python, site_packages=site_packages)
  File "c:\users\a\miniconda3\lib\site-packages\pipenv\cli.py", line 555, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "c:\users\a\miniconda3\lib\site-packages\pipenv\cli.py", line 440, in ensure_python
    path_to_python = find_a_system_python(python)
  File "c:\users\a\miniconda3\lib\site-packages\pipenv\cli.py", line 350, in find_a_system_python
    if python.startswith('py'):
AttributeError: 'InlineTableElement' object has no attribute 'startswith'
```

**Comment by kennethreitz** [comment]
no supported

**Comment by oca159** [comment]
How can I manage different versions of python in my environments?

I am using python 3.6 in my mac and python 3.5 in a tinkerboard but there are some problems with Pipfile because I can't install python 3.6 in the tinkerboard by repositories, should I install python 3.6 manually from sources?

**Comment by uranusjr** [comment]
@oca159 Or maybe you can use 3.5 on your Mac? It would be fairly straightforward to install under normal circumstances.

**Comment by leesdolphin** [comment]
Is there a reason behind your decision @kennethreitz? I'm running into a similar problem of trying to build a library with Python 3.5+ support. I'm running Python 3.6 but I don't want to force people to use Python 3.6 in order to run it.

**Comment by kennethreitz** [comment]
then don't specify a python in your pipfile, currently :)
