### ISSUE TITLE
pipenv under Python 2.7 cannot create Python 3 virtualenvs

### ISSUE THREAD

**Issue by halloleo** [pypa/pipenv#1152]
Because of [Issue 1151](https://github.com/kennethreitz/pipenv/issues/1151) I then tried running `pipenv` under Python 2.7:

I installed `pipenv` into Python 2.7. (Python engine  was installed via homebrew), then ran

    pipenv --three install

and get:

```
.
.
.
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 1728, in cli
    ensure_project(three=three, python=python, warn=True, site_packages=site_packages)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 630, in ensure_project
    ensure_pipfile(validate=validate)
  File "/usr/local/lib/python2.7/site-packages/pipenv/cli.py", line 334, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/usr/local/lib/python2.7/site-packages/pipenv/project.py", line 388, in create_pipfile
    data[u'requires'] = {'python_version': python_version(python)[:len('2.7')]}
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by kennethreitz** [comment]
install requires an argument. this may be a bug.

**Comment by scott-burgess** [comment]
I'm getting this error too. However before this error I also get:

`Running virtualenv with interpreter /usr/bin/python3.6m
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 8, in <module>
    import base64
  File "/usr/lib64/python3.6/base64.py", line 9, in <module>
    import re
  File "/usr/lib64/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'`

I don't know if the two errors are related.

**Comment by nateprewitt** [comment]
@scott-burgess I don't believe your error is related. This is likely cause by you having enum34 installed which isn't compatible with Python's 3.6 enum implementation because it lacks IntFlag.

**Comment by scott-burgess** [comment]
@nateprewitt yeah I thought this was something to do with enum34. 
If I remove enum34, I get stuck with flake8 requiring enum34....

My system was using virtualenv from Python 2.7 site packages, I had to re-install pip for python 3 and fetch virtualenv for python 3. All good now.

**Comment by techalchemy** [comment]
@halloleo is this resolved as a result of setting your encoding?

**Comment by halloleo** [comment]
@techalchemy Yes, seems to be fixed now - using now a newer pipenv (v9) though!
