### ISSUE TITLE
pipenv - Installed via Homebrew - errors on matplotlib installation

### ISSUE THREAD

**Issue by cmlccie** [pypa/pipenv#1169]
Pipenv (installed via Homebrew) crashes after installing `matplotlib`.  To verify that it wasn't something in my environment, I have replicated it on a clean-build VM of macOS High Sierra 10.13.1 (17B1003).  Note that matplotlib installs fine in this environment manually (using `python -m venv` and `pip install matplotlib`), and it appears that pipenv successfully installs it into the virtual environment created by pipenv.  However, pipenv errors-out after the installation and doesn't produce a lock file.

**Environment:**
* macOS High Sierra 10.13.1
* Python Interpreters:
  * `python` Python 2.7.10 (system)
  * `python2` Python 2.7.14 (installed via pyenv)
  * `python3` Python 3.6.3 (installed via pyenv)
* pipenv, version 8.3.2 (installed via homebrew)

**Steps to Reproduce:**
``` bash
$ mkdir -p ~/dev/projects/pipenv-matplotlib
$ cd ~/dev/projects/pipenv-matplotlib
$ pipenv install --three --verbose matplotlib
```

**Output:**  _(verbose output attached)_
``` bash
Chriss-Mac:pipenv-matplotlib cmlccie$ pipenv install --three --verbose matplotlib > verbose.log
Creating a virtualenv for this project…
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/Users/cmlccie/.pyenv/versions/3.6.3'
New python executable in /Users/cmlccie/.local/share/virtualenvs/pipenv-matplotlib-XtkrZ9f3/bin/python3
Also creating executable in /Users/cmlccie/.local/share/virtualenvs/pipenv-matplotlib-XtkrZ9f3/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/cmlccie/.local/share/virtualenvs/pipenv-matplotlib-XtkrZ9f3
Creating a Pipfile for this project…
Installing u'matplotlib'
$ "/Users/cmlccie/.local/share/virtualenvs/pipenv-matplotlib-XtkrZ9f3/bin/pip" install   --verbose   "matplotlib" -i https://pypi.python.org/simple --exists-action w
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.3.2', 'console_scripts', 'pipenv')()
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/cli.py", line 1935, in install
    do_lock(system=system, pre=pre)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/cli.py", line 1121, in do_lock
    pre=pre
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/utils.py", line 461, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 296, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/sh/5sddjf85009d0585hwjxd3cr0000gn/T/tmpRZW5Ttbuild/subprocess32/
Chriss-Mac:pipenv-matplotlib cmlccie$ 
```
[verbose.log](https://github.com/kennethreitz/pipenv/files/1529506/verbose.log)

**Tagging:** @vphilippon

**Comment by jnns** [comment]
I'm not sure if my issue is related but I guess it doesn't hurt to collect some infos.

**Environment**

    Ubuntu 17.10
    Python 2.7.14
    pip 9.0.1 from virtualenv (python 2.7)
    pipenv version 8.3.2 from virtualenv 


**Pipfile**
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
django-debug-toolbar = ">=1.6"

[packages]
django = "<2.0"

[requires]
python_version = "2.7"
```

**Output**
```
 $ pipenv lock --verbose

Creating a virtualenv for this project…
Using /usr/bin/python2.7 to create virtualenv…
⠋Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/jnns/.virtualenvs/testpipenv-CUs2SnP3/bin/python2.7
Also creating executable in /home/jnns/.virtualenvs/testpipenv-CUs2SnP3/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/jnns/.virtualenvs/testpipenv-CUs2SnP3
Locking [dev-packages] dependencies…
Using pip: -i https://pypi.python.org/simple

                          ROUND 1                           
Current constraints:
  django-debug-toolbar>=1.6

Finding the best candidates:
  found candidate django-debug-toolbar==1.9.1 (constraint was >=1.6)

Finding secondary dependencies:
  django-debug-toolbar==1.9.1 requires django-debug-toolbar==1.9.1, Django>=1.8, sqlparse>=0.2.0

New dependencies found in this round:
  adding [u'django', '>=1.8', '[]']
  adding [u'django-debug-toolbar', '==1.9.1', '[]']
  adding [u'sqlparse', '>=0.2.0', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  Django>=1.8
  django-debug-toolbar==1.9.1,>=1.6
  sqlparse>=0.2.0

Finding the best candidates:
  found candidate django==2.0 (constraint was >=1.8)
  found candidate django-debug-toolbar==1.9.1 (constraint was >=1.6,==1.9.1)
  found candidate sqlparse==0.2.4 (constraint was >=0.2.0)

Finding secondary dependencies:
  sqlparse==0.2.4           requires sqlparse==0.2.4
  django==2.0 not in cache, need to check index
Traceback (most recent call last):
  File "/home/jnns/.local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.3.2', 'console_scripts', 'pipenv')()
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/cli.py", line 2061, in lock
    do_lock(verbose=verbose, clear=clear, pre=pre)
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/cli.py", line 1060, in do_lock
    pre=pre
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/utils.py", line 461, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 296, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/jnns/.local/lib/python2.7/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpK64P_Ubuild/Django/
```

**Comment by vphilippon** [comment]
From what I understand (and according to Kenneth's comment (https://github.com/Homebrew/homebrew-core/pull/20902#issuecomment-345955184), the system python used in the Homebrew formula is not CPython, so the pre-compiled wheel of `matplotlib` isn't selected. As a result, the Homebrew-installed `pipenv` selects the `.tar.gz` and then setuptools attemps to build and compile `matplotlib`. I would't be surprised that the required dependencies to build `matplotlib` aren't on your machine @cmlccie.

There's a PR (https://github.com/Homebrew/homebrew-core/pull/20902) ongoing to change the python version used by the Homebrew formula.

/cc @erinxocon @kennethreitz for the follow-up here

For Django in @jnns case, it's different: It tries to install `Django==2.0`, which is Python 3 only, But I've seen that you downpinned `Django<2.0`. I think this is related to https://github.com/pypa/pipenv/issues/1172. Please try with the version in master, and if it isn't fixed, open a separate issue.

**Comment by jnns** [comment]
@vphilippon Thanks for the notification. My issue is indeed related to #1172 and therefore fixed in current master. Thank you.

**Comment by axitkhurana** [comment]
@cmlccie Saw this issue, I was facing the same with installing jupyter and reading @vphilippon 's comment, the workaround that worked for me:

1. Uninstall homebrew based pipenv
2. `brew install python3` (If you don't have already)
3. `python3 -m pip install pipenv`

Now try installing matplotlib. Should work until the PR is merged in homebrew.

**Comment by cmlccie** [comment]
@axitkhurana Yes, I had the same thought...  If it is a brew recipe issue, then installing and updating via pip might be a good workaround.


Confirmed, uninstalling the brew installed package and installing from PyPI works as a workaround to this issue (I used my global user space rather than my global "system" space).

## Workaround
```bash
$ brew uninstall pipenv
$ pip3 install --user pipenv
```

@vphilippon , you are correct.  It does seem to be an issue with the environment used by the brew installed pipenv package.  ...and I was testing on a clean-build macOS VM, so whatever the dependency issue is... The dependencies probably don't exist on most Macs (by default).  😎

**Comment by kennethreitz** [comment]
brew is broken.

**Comment by kennethreitz** [comment]
we don't document it as an installation method for a reason

**Comment by cmlccie** [comment]
@kennethreitz , Actually, you do:

https://github.com/pypa/pipenv
![pypa_pipenv__python_development_workflow_for_humans_](https://user-images.githubusercontent.com/16244946/34163514-e69dffc2-e4a4-11e7-9c6b-cbf7deef12d8.png)


https://docs.pipenv.org/install/#fancy-installation-of-pipenv
![pipenv___virtual_environments_ _pipenv_9_0_1_documentation](https://user-images.githubusercontent.com/16244946/34163550-036309cc-e4a5-11e7-9d33-7ad16b25e2a0.png)

**Comment by audiolion** [comment]
https://docs.pipenv.org/install/#homebrew-installation-of-pipenv yeah ya do

**Comment by cmlccie** [comment]
@audiolion Looks like were pulling that at the same time...  😀

**Comment by kennethreitz** [comment]
ugh, let's remove that.

**Comment by kennethreitz** [comment]
removed! ✨🍰✨

**Comment by kennethreitz** [comment]
thanks :)

**Comment by RalfHema** [comment]
Thanks 👍
