### ISSUE TITLE
pipenv --update doesn't work: NameError: global name 'FileNotFoundError' is not defined

### ISSUE THREAD

**Issue by andreagrandi** [pypa/pipenv#1180]
I was trying to update pipenv installation using `pipenv --update` but I got an error.

##### Describe your environment

1. OS: OSX
1. Python version: Python 2.7.13
1. Pipenv version: pipenv, version 8.3.2

##### Expected result

Expecting pipenv to update itself

##### Actual result

```
➜  test-pipenv pipenv --update
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.3.2', 'console_scripts', 'pipenv')()
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/cli.py", line 1634, in cli
    ensure_latest_self()
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/cli.py", line 159, in ensure_latest_self
    touch_update_stamp()
  File "/usr/local/Cellar/pipenv/8.3.2/libexec/lib/python2.7/site-packages/pipenv/utils.py", line 979, in touch_update_stamp
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

##### Steps to replicate

`pipenv --update`

**Comment by MatMoore** [comment]
Hey @andreagrandi 👋 

This was fixed in https://github.com/pypa/pipenv/issues/1085

I'm not sure what the proper workaround is to upgrade out of this version. I managed to upgrade from 8.3.2 to 9.0.0 with a combination of `pip install --update` and hacking the executable script that was actually on my path (which was still passing `==8.3.2` to pkg_resources). After that `pipenv --upgrade` works.

**Comment by andreagrandi** [comment]
Hi Mat!

Oh, my fault then :) I installed and used this versione because 9.0 wasn't available on `brew` yet. I'd better grab the latest version before doing any further testing and report any issue. Thanks for your reply!

Cheers
