### ISSUE TITLE
NameError: name 'resolver' is not defined

### ISSUE THREAD

**Issue by stephen-bunn** [pypa/pipenv#1195]
Be sure to check the existing issues, both open and closed.

I encounter a NameError on locking my Pipfile.

```
Traceback (most recent call last):
  File "/home/stephen-bunn/.local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==9.0.0', 'console_scripts', 'pipenv')()
  File "/home/stephen-bunn/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/stephen-bunn/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/stephen-bunn/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/stephen-bunn/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/stephen-bunn/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/stephen-bunn/.local/lib/python3.6/site-packages/pipenv/cli.py", line 2054, in lock
    do_lock(verbose=verbose, clear=clear, pre=pre)
  File "/home/stephen-bunn/.local/lib/python3.6/site-packages/pipenv/cli.py", line 1099, in do_lock
    pre=pre
  File "/home/stephen-bunn/.local/lib/python3.6/site-packages/pipenv/utils.py", line 593, in resolve_deps
    collected_hashes = list(list(resolver.resolve_hashes([result]).items())[0][1])
NameError: name 'resolver' is not defined
```

##### Describe your environment

1. OS Type: `Ubuntu 17.10`
1. Python version: `3.6.3`
1. Pipenv version: `9.0.0`

##### Expected result

I would prefer for there not to be a NameError 😢 

##### Actual result

This issue relates to the `ibm-db-sa-py3` package where the required version `0.3.1-1` _technically_ doesn't exist (I'm sure I'm the only person using it).
[For reference](https://pypi.org/pypi/ibm-db-sa-py3/json)

##### Steps to replicate

Here is my Pipfile contents, locking them should cause this error.

```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true


[packages]

simplejson = "*"
json-log-formatter = "*"
jsonschema = "*"
camel = "*"
pyyaml = "*"
pyexcel = "*"
pyexcel-io = "*"
pyexcel-xlsx = "*"
sqlparse = "*"
sqlalchemy = "*"
sqlalchemy-postgres-copy = "*"
"psycopg2" = "*"
pymssql = "*"
celery = "*"
kombu = "*"
redis = "*"
walrus = "*"
flower = "*"
requests = "*"
dateparser = "*"
emails = "*"
pysftp = "*"
pysmb = "*"
psutil = "*"
simple-salesforce = "*"
"ibm-db-sa-py3" = "==0.3.1-1"
pyodbc = "==3.1.1"


[dev-packages]

ptpython = "*"
"flake8" = "*"
nose = "*"
coverage = "*"
cprofilev = "*"
sphinx = "*"
sphinx-rtd-theme = "*"
pypager = "*"
prompt-toolkit = "*"
pygments = "*"
colorama = "*"
invoke = "*"
pytest = "*"
pytest-cov = "*"
"pytest-flake8" = "*"
```

**Comment by yashmehrotra** [comment]
@kennethreitz I faced the same issue but updating to a newer version didn't help, then I saw that the merged PR https://github.com/pypa/pipenv/pull/1200 is not in the master's commit history and when I saw the file https://github.com/pypa/pipenv/blob/master/pipenv/utils.py the last commit is on December 9, 2017 and changes are not reflected.

IMO, someone force pushed into master which broke the master's commit history. Kindly check

**Comment by OniOni** [comment]
Yup, I'm seeing the same error with version 9.0.3. But it looks like the fix landed in master 4 days ago, hopefully we'll get a new release with the fix soon 🤞 

Every time I find a bug, somebody has already fixed it. You peeps are amazing ^^
