### ISSUE TITLE
ImportError: cannot import name 'MappingProxyType'

### ISSUE THREAD

**Issue by Pitometsu** [pypa/pipenv#1211]
##### Describe your environment

1. OS Type – macOS High Sierra `10.13.1 (17B1003)`

```
$ python -V
Python 2.7.14
$ pipenv --version
pipenv, version 9.0.0
```

##### Expected result

Create empty project skeleton

##### Actual result

```
$ pipenv --python 2.7
Creating a virtualenv for this project…
Using /usr/local/bin/python2.7 to create virtualenv…
⠋Could not import runpy module
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 14, in <module>
    import importlib.machinery # importlib first so we can test #15386 via -m
  File "/usr/local/Cellar/pipenv/8.3.2_1/libexec/lib/python3.6/importlib/__init__.py", line 57, in <module>
    import types
  File "/Users/netsu/Projects/csr/csr/ic/types.py", line 1, in <module>
    import typing as tp
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 4, in <module>
    import contextlib
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 6, in <module>
    from functools import wraps
  File "/usr/local/Cellar/pipenv/8.3.2_1/libexec/lib/python3.6/functools.py", line 22, in <module>
    from types import MappingProxyType
ImportError: cannot import name 'MappingProxyType'
Error while trying to remove the /Users/netsu/.local/share/virtualenvs/ic-17J2RgpQ env:
No such file or directory
```

**Comment by Pitometsu** [comment]
When I added by hand `Pipfile`:

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[requires]
python_version = '2.7'


[packages]



[dev-packages]

```
It tell now:

```
$ pipenv --python 2.7
Creating a virtualenv for this project…
Using /usr/local/bin/python2.7 to create virtualenv…
⠋Could not import runpy module
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 14, in <module>
    import importlib.machinery # importlib first so we can test #15386 via -m
  File "/usr/local/Cellar/pipenv/8.3.2_1/libexec/lib/python3.6/importlib/__init__.py", line 57, in <module>
    import types
  File "/Users/netsu/Projects/csr/csr/ic/types.py", line 1, in <module>
    import typing as tp
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 4, in <module>
    import contextlib
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 6, in <module>
    from functools import wraps
  File "/usr/local/Cellar/pipenv/8.3.2_1/libexec/lib/python3.6/functools.py", line 22, in <module>
    from types import MappingProxyType
ImportError: cannot import name 'MappingProxyType'
Error while trying to remove the /Users/netsu/.local/share/virtualenvs/ic-17J2RgpQ env:
No such file or directory

Virtualenv location:
Warning: Your Pipfile requires python_version 2.7, but you are using None (/bin/python).
  $ pipenv check will surely fail.
```

**Comment by Pitometsu** [comment]
```
$ pipenv --py
/bin/python
```
Why so???

**Comment by Pitometsu** [comment]
Oh, I see: `pipenv` use `python3` from `homebrew` by default.
Reinstall from `pip` solve it.
