### ISSUE TITLE
pipenv installs a wheel over tar.gz even if tar.gz was the one used at locking

### ISSUE THREAD

**Issue by jrabbit** [pypa/pipenv#1213]
Running pipenv install with a lockfile doesn't always install the same url or archive type (whl v. tar.gz).

##### Describe your environment

1. Ubuntu 17.10
1. Python 2.7.14
1. pipenv, version 8.3.2 (on host), latest in container (i think its 9.00 offhand)

##### Expected result

pipenv install should "just work" with a lockfile in the future, i.e. install the tar.gz that has the correct hash in the lockfile.

##### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

```
Installing dependencies from Pipfile.lock (0a2fe5)…
An error occurred while installing todoist-python==7.0.17! Will try again.
     ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 70/70 — 00:00:44
Installing initially–failed dependencies…
Collecting todoist-python==7.0.17 ▉▉▉ 0/1 — 00:00:00
  Using cached todoist_python-7.0.17-py2.py3-none-any.whl

THESE PACKAGES DO NOT MATCH THE HASHES FROM Pipfile.lock!. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    todoist-python==7.0.17 from https://pypi.python.org/packages/f9/a7/7995ce502ebe70eda1eecd090c1468f22e3add1ff4e5bc230f5345fd660c/todoist_python-7.0.17-py2.py3-none-any.whl#md5=450f88e7abc6ccc8a1e6116706c1445d (from -r /tmp/pipenv-_1sXUH-requirement.txt (line 1)):
        Expected sha256 22cfac11ea33a786d8e28a4aec1ecebe2136aaa14072bdfc11e6cfba37dd443f
             Got        43edf4819372003c95095c9cfa648273ddd28e0879a3b7c4414cce6cbf5e15e2
```

from pypi metadata:
```
 
File    Type    Py Version    Uploaded on    Size
todoist-python-7.0.17.tar.gz (md5)    Source        2017-05-29    18KB
todoist_python-7.0.17-py2.py3-none-any.whl (md5)    Python Wheel    py2.py3    2017-12-13    22KB
```

##### Steps to replicate
`"todoist-python" = "==7.0.17"`
and

```
        "todoist-python": {
            "hashes": [
                "sha256:22cfac11ea33a786d8e28a4aec1ecebe2136aaa14072bdfc11e6cfba37dd443f"
            ],
            "version": "==7.0.17"
        },
```

then pip install.
```
Installing 'todoist-python==7.0.17 --hash=sha256:22cfac11ea33a786d8e28a4aec1ecebe2136aaa14072bdfc11e6cfba37dd443f'
$ "/home/travis/virtualenv/python2.7.14/bin/pip" install   --verbose --no-deps  -r /tmp/pipenv-JE84tW-requirement.txt --require-hashes -i https://pypi.python.org/simple --exists-action w
Collecting todoist-python==7.0.17 
  1 location(s) to search for versions of todoist-python:
  * https://pypi.python.org/simple/todoist-python/
  Getting page https://pypi.python.org/simple/todoist-python/
  Looking up "https://pypi.python.org/simple/todoist-python/" in the cache
  Current age based on date: 399
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 399
  Analyzing links from page https://pypi.python.org/simple/todoist-python/
    Found link https://pypi.python.org/packages/04/cc/d01837d47edf5d2fe1d0df7b4abd98328eeae9f1dfe27408a42671b6b91e/todoist-python-7.0.3.tar.gz#md5=d48d37a06b52580d34acb02a79193152 (from https://pypi.python.org/s
imple/todoist-python/), version: 7.0.3
    Found link https://pypi.python.org/packages/09/a7/4df41818e24c8b658f728b1f65ac33fd56e51b24eab15404917d7f26c06b/todoist-python-7.0.5.tar.gz#md5=1151d83caa5b5061745d66cd425046bd (from https://pypi.python.org/s
imple/todoist-python/), version: 7.0.5
    Found link https://pypi.python.org/packages/0b/ec/7a933564dec8092ed0c921303585ff2e3ab64c2e82004d8e5cbb70ee35d8/todoist-python-7.0.7.tar.gz#md5=f217175b7b0458301d951b9b8edd72eb (from https://pypi.python.org/s
imple/todoist-python/), version: 7.0.7
    Found link https://pypi.python.org/packages/12/b8/58ee96eaabffb0e548c74c111b7d7ed369878db40dc5bfce238dfb773a80/todoist-python-0.2.22.tar.gz#md5=0a8729f08285689746a149204f6c033b (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.22
    Found link https://pypi.python.org/packages/17/a0/e2167d4cae0050a19cc5911252fd025f01c1574bc2deb74ec752b541f173/todoist-python-7.0.13.tar.gz#md5=3f21a447fd5d8e3f9a658446ff8f4f79 (from https://pypi.python.org/
simple/todoist-python/), version: 7.0.13
    Found link https://pypi.python.org/packages/18/dd/32820a9a7d01e7696b57c54411176b367948cb26adfb1f4831d9617dbaa5/todoist-python-0.2.14.tar.gz#md5=a41e292e30b1cc7f8908cb80f03c26fe (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.14
    Found link https://pypi.python.org/packages/19/6e/4bacf6690327ba77dedeac92dd891bc835c9220530b9cf78abf44ab3ac10/todoist-python-0.2.10.tar.gz#md5=9a8b5e2f2761fda9410815062a9868ba (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.10
    Found link https://pypi.python.org/packages/1e/e5/16400422cd8e6b194b6b07462c94c0310f42e21b35edbdfa02768d6d62d7/todoist-python-0.2.18.tar.gz#md5=96e664ae1b3e7a13a25bc7299360ff44 (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.18
    Found link https://pypi.python.org/packages/29/f3/aaf45b5ba4c57dbb436c5b0b659dbf6557a106d97116bdfde05385df7ee2/todoist-python-0.2.9.tar.gz#md5=ae54a3aa04fbc541d27096b4abbe7052 (from https://pypi.python.org/s
imple/todoist-python/), version: 0.2.9
    Found link https://pypi.python.org/packages/39/7b/da6b0aae818ef3f387ea139926e197870c34d606851eb5bf6297a2ce42b9/todoist-python-0.2.15.tar.gz#md5=7dd8bae1f4340c94aed48284b69b319a (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.15
    Found link https://pypi.python.org/packages/39/f4/f1d613b18d97f5002626836dd141eb7096c2d73cfd1e5ef82bd72313a844/todoist-python-0.2.11.tar.gz#md5=68da293cfc2e4409f3d0eca303f3353b (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.11
    Found link https://pypi.python.org/packages/3e/7e/5cd599218c33dff9ab1b05255c0b53fe52a481571721d6078efd88283b75/todoist-python-7.0.6.tar.gz#md5=3d27f57c71075d533c2563f620d5728d (from https://pypi.python.org/s
imple/todoist-python/), version: 7.0.6
    Found link https://pypi.python.org/packages/43/6c/6132aaaa50c5321163ee25567a0d53cb1751eb3c4242af4f46f67a99aa07/todoist-python-7.0.11.tar.gz#md5=bf51ef7631865316aea9276ae5e965a7 (from https://pypi.python.org/
simple/todoist-python/), version: 7.0.11
    Found link https://pypi.python.org/packages/45/0c/a9065d7efd5f1d44ddedd93e3953d7edcd9f746d75a7ced049e286da5657/todoist-python-7.0.16.tar.gz#md5=a6f29f123c2a7387cffd55322fe4a991 (from https://pypi.python.org/
simple/todoist-python/), version: 7.0.16
    Found link https://pypi.python.org/packages/50/e9/a0f055b50112b1981d8b87830ad5c087dfbab49dc5a7949d7a550a53353e/todoist-python-0.2.20.tar.gz#md5=43e1f760a9d7981a0dbe2d1b53bbdf9b (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.20
    Found link https://pypi.python.org/packages/57/9d/c6b33affe95c66590808a40d61d99a5ff94473dc6ed84127b83119fa4ec3/todoist_python-7.0.18-py2.py3-none-any.whl#md5=ec2ed10ba509bc5488821d6931edf04d (from https://py
pi.python.org/simple/todoist-python/), version: 7.0.18
    Found link https://pypi.python.org/packages/57/ec/f35cf3febf85d8bb53f9b830147d9ed92b750412d9e036be0e61b17ca11a/todoist-python-0.2.1.tar.gz#md5=416205951725f05c14ce0aceb8673359 (from https://pypi.python.org/s
imple/todoist-python/), version: 0.2.1
    Found link https://pypi.python.org/packages/59/b4/5cc2dbe037f72942a8378784815aae0955b534e3f718f004af5d5c4c6edf/todoist-python-0.2.tar.gz#md5=6586254bea8674d3a6c7db0e3ba7841a (from https://pypi.python.org/sim
ple/todoist-python/), version: 0.2
    Found link https://pypi.python.org/packages/59/d4/a8b79e1cbf1ff4b5eb870522959d48e563b688083c002ffe7ff717c46cb9/todoist-python-0.2.25.tar.gz#md5=a31c2b34b5f2ff838589d3cb9588cef0 (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.25
    Found link https://pypi.python.org/packages/5a/52/075ee932a974310ac30b0bf1da5d1c7c07fde49296d757023ba6ebe42dff/todoist-python-0.2.24.tar.gz#md5=4868d911fb1baa950336ece295626033 (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.24
    Found link https://pypi.python.org/packages/5d/22/20f3a5fe3254c50b7d7ca552cecd0fd1b06bfa7b5b718017910f229522d9/todoist-python-0.2.6.tar.gz#md5=9c6a90062145f414e5e26f7b19a9c473 (from https://pypi.python.org/s
imple/todoist-python/), version: 0.2.6
    Found link https://pypi.python.org/packages/62/17/a5c5e86277a140cf3bfbf0685ac10f2d7750527b3b8a33dee95d5b74fee7/todoist-python-0.2.5.tar.gz#md5=baa7eb7e21f72da3b3229a1456bb2bb9 (from https://pypi.python.org/s
imple/todoist-python/), version: 0.2.5
    Found link https://pypi.python.org/packages/65/52/c37930a121ea354a1a7032e6c059fc74b8d9c82a6728af71e9a72c4ebaf7/todoist-python-7.0.4.tar.gz#md5=b446bf8080b61e4dd0af5f5d4e6ee9b0 (from https://pypi.python.org/s
imple/todoist-python/), version: 7.0.4
    Found link https://pypi.python.org/packages/6a/ce/486417ae71e1d538775209ac61f5857ce63ae59dfbf5a18bc6e94ea955e4/todoist-python-0.2.16.tar.gz#md5=e449ccedbb5f30e0bff4ca9555117d82 (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.16
    Found link https://pypi.python.org/packages/71/dc/c88f146f644e3dd27a134df808694064b95288d4e64d3368c66b85ccdbc7/todoist-python-0.2.2.tar.gz#md5=9eebd7887707afaab148eccdda436f00 (from https://pypi.python.org/s
imple/todoist-python/), version: 0.2.2
    Found link https://pypi.python.org/packages/71/ec/850f71c78a2cdc6cd7a1ad6e1ca7797d8ce9cd09e2f8494822a3210863b6/todoist-python-0.2.8.tar.gz#md5=27fc35ed4280f8d76068714b7db01edd (from https://pypi.python.org/s
imple/todoist-python/), version: 0.2.8
    Found link https://pypi.python.org/packages/76/50/e20654362449b67f406d439a953cc3e96ae414ad97300cb02aa5464259e0/todoist-python-7.0.15.tar.gz#md5=ddbede3aa86a4d26f0aeac245dfb0f14 (from https://pypi.python.org/
simple/todoist-python/), version: 7.0.15
    Found link https://pypi.python.org/packages/79/31/8f23519d7e90f173f6293f33dc71b4363eb926211a28fe8686551b0f6f3f/todoist-python-7.0.9.tar.gz#md5=ba3acb54982e08f688372f3eaa2041ee (from https://pypi.python.org/s
imple/todoist-python/), version: 7.0.9
    Found link https://pypi.python.org/packages/7d/86/40e9e8ab728a1a2559c491b84ded463b6f7c6f6fbd868ff6f376c9d9bf86/todoist-python-0.2.3.tar.gz#md5=ae5a2bef77748ecef1b7de07d4f38425 (from https://pypi.python.org/s
imple/todoist-python/), version: 0.2.3
    Found link https://pypi.python.org/packages/7e/b8/3ab736cf32e74b086e5279b33c28ded805b18d1cb7b992a4fbf46852aafb/todoist-python-7.0.12.tar.gz#md5=2ce0f495cb880c04750961c38f0f35cf (from https://pypi.python.org/
simple/todoist-python/), version: 7.0.12
    Found link https://pypi.python.org/packages/7f/f8/b47298367c3655ec654470d8e2a623848bbc2f176fc66e38676d03d4e475/todoist-python-7.0.1.tar.gz#md5=ae4d77f5d7e731477f35e74c813f8d65 (from https://pypi.python.org/s
imple/todoist-python/), version: 7.0.1
    Found link https://pypi.python.org/packages/89/a5/9d1dcc77bfe4ccc5cef7b7da23c6308d681a55203327f10a3ac8ef753ad0/todoist-python-0.2.23.tar.gz#md5=896e74309f8c4a125322fe062fb4da69 (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.23
    Found link https://pypi.python.org/packages/8e/7e/72d39801c424e5dcc4b0a0637c03e4b767d7e3b86f313f65d8e4ce5e86c7/todoist-python-7.0.2.tar.gz#md5=635e4974836ff32fb4184e9fc4cadfc5 (from https://pypi.python.org/s
imple/todoist-python/), version: 7.0.2
    Found link https://pypi.python.org/packages/95/f9/b28923581a32f5a73d12783a7130c43a48c3bfaa584b097089a6fe90f054/todoist-python-0.2.26.tar.gz#md5=b53c6dc9d66027f137c0a4edd694d35c (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.26
    Found link https://pypi.python.org/packages/aa/4a/c96f5f8dfbbd77ad37732bdac5c87be90013959c3b25bc6e7a23adeea5ac/todoist-python-0.2.21.tar.gz#md5=36d1cca4d1d26aed5d48d6f5484fc63f (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.21
    Found link https://pypi.python.org/packages/c8/4f/87c5e53eac5ba209e6d1e580b7131180c7849970640073fa5b1a6978fd11/todoist-python-0.2.7.tar.gz#md5=dc3fa4f3dd74b2007983817e5472a755 (from https://pypi.python.org/s
imple/todoist-python/), version: 0.2.7
    Found link https://pypi.python.org/packages/d0/c4/5b7f07a2a12519687f862dba0e0a73502f861c688d7db059d0f5138a28f2/todoist-python-7.0.14.tar.gz#md5=43ee6357786abe725b095d8248c2b84e (from https://pypi.python.org/
simple/todoist-python/), version: 7.0.14
    Found link https://pypi.python.org/packages/d4/26/58045100227fa951949e86b786dc5c7f4587e7bbf62be7141ca5a76b4824/todoist-python-0.2.13.tar.gz#md5=e176ec0b6541ca82078db74c764d6c9e (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.13
    Found link https://pypi.python.org/packages/d4/55/ec2260d75417163e0be58bc3e0995d19ee22df66515a13f4ac31a5efe820/todoist-python-7.0.10.tar.gz#md5=92ccb9a3d86e780761ba3fff9ec6ef9d (from https://pypi.python.org/
simple/todoist-python/), version: 7.0.10
    Found link https://pypi.python.org/packages/e3/7e/9910080e96bcaf4259eb9ca928a8e8bb4d3110ebdda7d68e4db118302ba1/todoist-python-0.2.19.tar.gz#md5=a910819a9bfd84d7bbafcfe82a6a4f8e (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.19
    Found link https://pypi.python.org/packages/e4/f7/d2109fcfc2185a2753f7add62f3e6a5e7679bdce2d3dbd0c731a6d2dfb8c/todoist_python-0.2.17-py2.py3-none-any.whl#md5=6b2cb43ad0498e54c55fcbb75f97b1ef (from https://py
pi.python.org/simple/todoist-python/), version: 0.2.17
    Found link https://pypi.python.org/packages/ec/02/39c9de305e6f97c983ad4caf8d82b9a6c1dd524c4eeb17c9666cdde1e6ef/todoist-python-0.2.4.tar.gz#md5=66b186a03017e1cfdf98c3991ccaabac (from https://pypi.python.org/s
imple/todoist-python/), version: 0.2.4
    Found link https://pypi.python.org/packages/f0/23/87995673c589ee78ce6f1c66693fc3d7b927b3f6b56dc681fa4221440e66/todoist-python-7.0.17.tar.gz#md5=3f8c10afff6d1814a6cb705742dc2158 (from https://pypi.python.org/
simple/todoist-python/), version: 7.0.17
    Found link https://pypi.python.org/packages/f5/88/792c1a0713d1cde9b43516de2c496b31f6c83d5e87b8d2505ea99001e27a/todoist-python-7.0.8.tar.gz#md5=d406eebf862dcd0bc7fbd01e98dabf96 (from https://pypi.python.org/s
imple/todoist-python/), version: 7.0.8
    Found link https://pypi.python.org/packages/f9/4b/4e5535915c9c7af8f44635a567bbd7d2eb259e9499dbe16c201f1ed41fe0/todoist-python-0.2.17.tar.gz#md5=c9cc9fede829eff801a955a6332d01c4 (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.17
    Found link https://pypi.python.org/packages/f9/61/e0eaa85fe067dd15d39a0c41a2ac6aaf9d0014112383b027af3e2b63e365/todoist-python-0.2.12.tar.gz#md5=1924eeafdf0801a8aa231cd892190fdb (from https://pypi.python.org/
simple/todoist-python/), version: 0.2.12
    Found link https://pypi.python.org/packages/f9/a7/7995ce502ebe70eda1eecd090c1468f22e3add1ff4e5bc230f5345fd660c/todoist_python-7.0.17-py2.py3-none-any.whl#md5=450f88e7abc6ccc8a1e6116706c1445d (from https://py
pi.python.org/simple/todoist-python/), version: 7.0.17
    Found link https://pypi.python.org/packages/fa/c3/c77bdec30b8d8d685cc5c5f18052f62e884f57499db1d58a630e27c9546c/todoist-python-0.1.tar.gz#md5=bbf5991e44e95bf955372d0bf37a9706 (from https://pypi.python.org/sim
ple/todoist-python/), version: 0.1
    Found link https://pypi.python.org/packages/fe/47/1be476e96186f65bf1a25275575a667e8f223cd6912ebd726af1607b78b9/todoist-python-7.0.tar.gz#md5=205998a24b8d31b2f50873e33a1e85a1 (from https://pypi.python.org/sim
ple/todoist-python/), version: 7.0
  Using version 7.0.17 (newest of versions: 7.0.17)
  Looking up "https://pypi.python.org/packages/f9/a7/7995ce502ebe70eda1eecd090c1468f22e3add1ff4e5bc230f5345fd660c/todoist_python-7.0.17-py2.py3-none-any.whl" in the cache
  Current age based on date: 399
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 399
  Using cached todoist_python-7.0.17-py2.py3-none-any.whl
  Downloading from URL https://pypi.python.org/packages/f9/a7/7995ce502ebe70eda1eecd090c1468f22e3add1ff4e5bc230f5345fd660c/todoist_python-7.0.17-py2.py3-none-any.whl#md5=450f88e7abc6ccc8a1e6116706c1445d (from ht
tps://pypi.python.org/simple/todoist-python/)
Cleaning up...
Exception information:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pip/req/req_set.py", line 386, in prepare_files
    raise hash_errors
HashErrors: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may h
ave tampered with them.
    todoist-python==7.0.17 from https://pypi.python.org/packages/f9/a7/7995ce502ebe70eda1eecd090c1468f22e3add1ff4e5bc230f5345fd660c/todoist_python-7.0.17-py2.py3-none-any.whl#md5=450f88e7abc6ccc8a1e6116706c1445d
 
        Expected sha256 22cfac11ea33a786d8e28a4aec1ecebe2136aaa14072bdfc11e6cfba37dd443f
             Got        43edf4819372003c95095c9cfa648273ddd28e0879a3b7c4414cce6cbf5e15e2


THESE PACKAGES DO NOT MATCH THE HASHES FROM Pipfile.lock!. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with th
em.
    todoist-python==7.0.17 from https://pypi.python.org/packages/f9/a7/7995ce502ebe70eda1eecd090c1468f22e3add1ff4e5bc230f5345fd660c/todoist_python-7.0.17-py2.py3-none-any.whl#md5=450f88e7abc6ccc8a1e6116706c1445d
 (from -r /tmp/pipenv-JE84tW-requirement.txt (line 1)):
        Expected sha256 22cfac11ea33a786d8e28a4aec1ecebe2136aaa14072bdfc11e6cfba37dd443f
             Got        43edf4819372003c95095c9cfa648273ddd28e0879a3b7c4414cce6cbf5e15e2


  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:00
```

**Comment by nateprewitt** [comment]
@jrabbit this is because the package maintainer didn't upload the wheel until December 13th. Since your lockfile was generated before the wheel existed, it doesn't have the hash and therefore won't resolve. This is how the feature is intended to work, and if you wish to use the new hash, you'll need to generate a new lockfile to get the current available hashes.

**Comment by jrabbit** [comment]
I don't understand how this is how it's supposed to work when pipenv has all the information to acquire the correct file which is still uploaded and happily on pypi?

**Comment by nateprewitt** [comment]
@jrabbit, if you're discussing why it's not choosing to install the tar.gz file now, this is a behavior of pip itself. Pip is designed to always choose a wheel over an archive installation unless explicitly told not to. Since we are a layer on top of pip's functionality you'd have to do something, likely modify a global pip.conf, to get pip to choose archives by default. It's unlikely that's the behaviour you want though.

**Comment by jrabbit** [comment]
Ok. So it's somewhat pre-determined (by pip convention) that package owners shouldn't do this. I'll forward that on. Would it make sense to handle this weirdness without showing the mismatch? since the file shasum didn't actually change just the set did.
