### ISSUE TITLE
Pipenv not able to lock Pipefile after import from requirements.txt

### ISSUE THREAD

**Issue by felixgao** [pypa/pipenv#1222]
I have a requirement.txt file 
```
pyobjc-core
pyobjc
pyautogui
pyyaml
click
selenium
nose
```
I used the `pipenv install -r requirement.text` command to install requirements and generate the Pipefile.  The Pipefile is generated correctly as
```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[dev-packages]



[packages]

pyobjc-core = "*"
pyobjc = "*"
PyAutoGUI = "*"
PyYAML = "*"
click = "*"
selenium = "*"
nose = "*"
```
However the Pipefile.lock file failed with the following exception
```
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==9.0.1', 'console_scripts', 'pipenv')()
  File "/Library/Python/2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pipenv/cli.py", line 2060, in lock
    do_lock(verbose=verbose, clear=clear, pre=pre)
  File "/Library/Python/2.7/site-packages/pipenv/cli.py", line 1102, in do_lock
    pre=pre
  File "/Library/Python/2.7/site-packages/pipenv/utils.py", line 545, in resolve_deps
    resolved_tree = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/Library/Python/2.7/site-packages/pipenv/utils.py", line 507, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/Library/Python/2.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Library/Python/2.7/site-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/Library/Python/2.7/site-packages/pipenv/patched/piptools/resolver.py", line 296, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Library/Python/2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/Library/Python/2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/Library/Python/2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/Library/Python/2.7/site-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Library/Python/2.7/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
```

##### Describe your environment

1. OS Type: OSX 10.12.5
1. Python version: 2.7.10
1. Pipenv version:  9.0.1

##### Expected result

Pipefile.lock should be generated without exception

##### Actual result
```
Requirements file provided! Importing into Pipfile…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==9.0.1', 'console_scripts', 'pipenv')()
  File "/Library/Python/2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pipenv/cli.py", line 1865, in install
    do_init(dev=dev, allow_global=system, ignore_pipfile=ignore_pipfile, system=system, skip_lock=skip_lock, verbose=verbose, concurrent=concurrent, deploy=deploy, pre=pre)
  File "/Library/Python/2.7/site-packages/pipenv/cli.py", line 1311, in do_init
    do_lock(system=system, pre=pre)
  File "/Library/Python/2.7/site-packages/pipenv/cli.py", line 1102, in do_lock
    pre=pre
  File "/Library/Python/2.7/site-packages/pipenv/utils.py", line 545, in resolve_deps
    resolved_tree = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/Library/Python/2.7/site-packages/pipenv/utils.py", line 507, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/Library/Python/2.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Library/Python/2.7/site-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/Library/Python/2.7/site-packages/pipenv/patched/piptools/resolver.py", line 296, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Library/Python/2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/Library/Python/2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/Library/Python/2.7/site-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/Library/Python/2.7/site-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Library/Python/2.7/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/xp/wxrjtr_d7zq0nhr6shcfh5tm0000gn/T/tmp0ysko3build/PyAutoGUI/
```
##### Steps to replicate

create a file called requirement.txt with the content above.
run `pipenv install -r requirement.ext`

**Comment by uranusjr** [comment]
The `setup.py` of PyAutoGUI [imports itself](https://github.com/asweigart/pyautogui/blob/master/setup.py#L6), which in turn triggers the following code, that eventually creates the error you see:

```python
try:
    import Quartz
except:
    assert False, "You must first install pyobjc-core and pyobjc: https://pyautogui.readthedocs.io/en/latest/install.html"
```

I think this is a flaw in PyAutoGUI’s packaging. Checking just the first two pages I found three open issues that boil down to this same problem:

* asweigart/pyautogui#184
* asweigart/pyautogui#180
* asweigart/pyautogui#151

I guess the most sensitive way is to let PyAutoGUI fix this. There’s not much Pipenv (and Pip) can do to amend this.

/cc @asweigart

----

Workaround:

* Generate the Pipfile (it will error, but that’s OK)
* Remove PyAutoGUI from Pipfile
* `pipenv install`
* `pipenv install PyAutoGUI` (this will add auto PyAutoGUI to Pipfile and Pipfile.lock)

This should guarantee to work as long as you keep Pipfile.lock, and install from it (i.e. do not run `pipenv install --ignore-lockfile`).

**Comment by techalchemy** [comment]
Yeah @uranusjr has pretty much covered it, the resolver can't resolve properly for packages where the maintainers have imported their own libraries into their `setup.py`.

As a sidenote thanks for your ongoing support @uranusjr it is incredibly helpful

I'm going to close this one out for now, sorry you are running into this and hopefully they can get this fixed up for you!
