### ISSUE TITLE
pip --three failed

### ISSUE THREAD

**Issue by Rouzip** [pypa/pipenv#1251]
##### Describe your environment
OS:Ubuntu 16.04LTS
Python version: 3.6.3
Pipenv version: pipenv, version 9.0.1
##### Expected result

Create a virtualenv for the project.

##### Actual result

        Complete output from command python setup.py egg_info:
        /usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'entry_points'
          warnings.warn(msg)
        /usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
          warnings.warn(msg)
        /usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'zip_safe'
          warnings.warn(msg)
        /usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
          warnings.warn(msg)
        /usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'extras_require'
          warnings.warn(msg)
        usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
           or: -c --help [cmd1 cmd2 ...]
           or: -c --help-commands
           or: -c cmd --help

        error: invalid command 'egg_info'

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7kvu61pe/pip/
    ----------------------------------------
    ...Installing setuptools, pip, wheel...done.
    Traceback (most recent call last):
      File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 2328, in <module>
        main()
      File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 713, in main
        symlink=options.symlink)
      File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 945, in create_environment
        download=download,
      File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 901, in install_wheel
        call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
      File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 797, in call_subprocess
        % (cmd_desc, proc.returncode))
    OSError: Command /home/rouzip/.local/...mbNjlp15/bin/python3 - setuptools pip wheel failed with error code 1

    Virtualenv location: 
    Creating a Pipfile for this project…
    Traceback (most recent call last):
      File "/home/rouzip/.local/bin/pipenv", line 11, in <module>
        load_entry_point('pipenv==9.0.1', 'console_scripts', 'pipenv')()
      File "/home/rouzip/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/home/rouzip/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/home/rouzip/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
        return Command.invoke(self, ctx)
      File "/home/rouzip/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/rouzip/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/rouzip/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/home/rouzip/.local/lib/python3.6/site-packages/pipenv/cli.py", line 1724, in cli
        ensure_project(three=three, python=python, warn=True, site_packages=site_packages)
      File "/home/rouzip/.local/lib/python3.6/site-packages/pipenv/cli.py", line 642, in ensure_project
        ensure_pipfile(validate=validate)
      File "/home/rouzip/.local/lib/python3.6/site-packages/pipenv/cli.py", line 337, in ensure_pipfile
        project.create_pipfile(python=python)
      File "/home/rouzip/.local/lib/python3.6/site-packages/pipenv/project.py", line 406, in create_pipfile
        data[u'requires'] = {'python_version': python_version(python)[:len('2.7')]}
    TypeError: 'NoneType' object is not subscriptable

##### Steps to replicate

```shell
pipenv --three
```
I have the latest setuptools,pip and pipenv.
I try to add `export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8`  like #538 ,but it doesn't work.

**Comment by knowsuchagency** [comment]
Make sure you don't have a `setup.cfg` with the following in your project's root, or it will cause this issue

    [install]
    prefix=

**Comment by Rouzip** [comment]
Thanks for your answering!I check my root carefully,there is nothing but a blank pipfile. @knowsuchagency 
    
    ls -al
    drwxrwxr-x 2 rouzip rouzip 4096 12月 28 15:12 .
    drwxrwxr-x 9 rouzip rouzip 4096 12月 28 14:56 ..
    -rw-rw-r-- 1 rouzip rouzip    0 12月 28 15:12 Pipfile

**Comment by techalchemy** [comment]
@Rouzip thanks for the report. If you have a blank Pipfile in your project it will definitely not work— Pipfiles _must_ adhere to a specific syntax and therefore shouldn’t be blank. Pipenv will generate one for you if you install something. Try to remove the blank Pipfile and simply run `pipenv install <somepackage>`

**Comment by Rouzip** [comment]
@techalchemy thanks for your advice,I had a good Pipfile now! I think my expected result is not exactly. When I try to create a virtualenv by `pipenv --three` ,it shows error and creates a blank Pipfile. And I try `pipenv install requests`,its errors like that:
> Creating a virtualenv for this project…
⠋Using base prefix '/usr/local'
Traceback (most recent call last):
  File "/home/rouzip/Python-3.6.3/Lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rouzip/Python-3.6.3/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 1132, in install_python
    copy_required_modules(home_dir, symlink)
  File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 1062, in copy_required_modules
    dst_filename = change_prefix(filename, dst_prefix)
  File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 1036, in change_prefix
    (filename, prefixes)
AssertionError: Filename /home/rouzip/Python-3.6.3/Lib/os.py does not start with any of these prefixes: ['/usr/local', '/usr/local']
Virtualenv location: 
Creating a Pipfile for this project…
Installing requests…
⠼
Error:  An error occurred while installing requests!
/bin/sh: 1: /bin/pip: not found

**Comment by Rouzip** [comment]
@techalchemy thanks for your advice,I had a good Pipfile now! I think my expected result is not exactly. When I try to create a virtualenv by pipenv --three ,it shows error and creates a blank Pipfile. And I try pipenv install requests,its errors like that:

 ```
⠋Using base prefix '/usr/local'
New python executable in /home/rouzip/.local/share/virtualenvs/pue-mbNjlp15/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /home/rouzip/.local/...-mbNjlp15/bin/python - setuptools pip wheel:
  /home/rouzip/.local/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
Collecting setuptools
  Downloading http://mirrors.aliyun.com/pypi/packages/69/56/f0f52281b5175e3d9ca8623dadbc3b684e66350ea9e0006736194b265e99/setuptools-38.2.4.zip (736kB)
Collecting pip
  Downloading http://mirrors.aliyun.com/pypi/packages/11/b6/abcb525026a4be042b486df43905d6893fb04f05aac21c32c638e939e447/pip-9.0.1.tar.gz (1.2MB)
    Complete output from command python setup.py egg_info:
    /usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'entry_points'
      warnings.warn(msg)
    /usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
      warnings.warn(msg)
    /usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'zip_safe'
      warnings.warn(msg)
    /usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    /usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'extras_require'
      warnings.warn(msg)
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: invalid command 'egg_info'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kv2a8pl8/pip/
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/home/rouzip/.local/lib/python3.6/site-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/rouzip/.local/...-mbNjlp15/bin/python - setuptools pip wheel failed with error code 1
Virtualenv location: 
Installing requests…
⠸
Error:  An error occurred while installing requests!
/bin/sh: 1: /bin/pip: not found

```

**Comment by Rouzip** [comment]
@uranusjr I check my `/bin` , it **doesn't** have __pip__.I don't know why pipenv try to use `/bin/pip` which not exists.
`which pip` returns 
`/usr/local/bin/pip`
`pip --version` returns
`pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)`
And I can use pip install packages.

**Comment by Rouzip** [comment]
I have found the reason.I set `~/.pip/pip.conf` a Chinese mirror,when I remove it,everything will work fine!

**Comment by uranusjr** [comment]
Huh, that is… unexpected. Python packaging is difficult.
