### ISSUE TITLE
Install timeout

### ISSUE THREAD

**Issue by orkenstein** [pypa/pipenv#1254]
##### Describe your environment

1. macOS 10.13.2 (17C88)
1. Python 3.6.1
1. pipenv, version 9.0.1

##### Expected result

Trying to install `google-cloud-datastore`. Or any other heavy package.

##### Actual result
`Install` timeout:
`pipenv install --verbose google-cloud-datastore`
<details> 
  <summary>output:</summary>

```Installing google-cloud-datastore…
⠋Installing 'google-cloud-datastore'
$ "/Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/bin/pip" install   --verbose   "google-cloud-datastore" -i https://pypi.python.org/simple --exists-action w
Requirement already satisfied: google-cloud-datastore in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages
Requirement already satisfied: google-api-core<0.2.0dev,>=0.1.1 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-cloud-datastore)
Requirement already satisfied: google-cloud-core<0.29dev,>=0.28.0 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-cloud-datastore)
Requirement already satisfied: gapic-google-cloud-datastore-v1<0.16dev,>=0.15.0 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-cloud-datastore)
Requirement already satisfied: google-gax<0.16dev,>=0.15.7 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-cloud-datastore)
Requirement already satisfied: protobuf>=3.0.0 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-datastore)
Requirement already satisfied: six>=1.10.0 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-datastore)
Requirement already satisfied: pytz in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-datastore)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-datastore)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.5.3 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-datastore)
Requirement already satisfied: setuptools>=34.0.0 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-datastore)
Requirement already satisfied: google-auth<2.0.0dev,>=0.4.0 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-api-core<0.2.0dev,>=0.1.1->google-cloud-datastore)
Requirement already satisfied: oauth2client<4.0dev,>=2.0.0 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from gapic-google-cloud-datastore-v1<0.16dev,>=0.15.0->google-cloud-datastore)
Requirement already satisfied: proto-google-cloud-datastore-v1[grpc]<0.91dev,>=0.90.3 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from gapic-google-cloud-datastore-v1<0.16dev,>=0.15.0->google-cloud-datastore)
  Installing extra requirements: 'grpc'
Requirement already satisfied: future<0.17dev,>=0.16.0 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-gax<0.16dev,>=0.15.7->google-cloud-datastore)
Requirement already satisfied: dill<0.3dev,>=0.2.5 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-gax<0.16dev,>=0.15.7->google-cloud-datastore)
Requirement already satisfied: ply==3.8 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-gax<0.16dev,>=0.15.7->google-cloud-datastore)
Requirement already satisfied: grpcio<2.0dev,>=1.0.2 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-gax<0.16dev,>=0.15.7->google-cloud-datastore)
Requirement already satisfied: idna<2.7,>=2.5 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<0.2.0dev,>=0.1.1->google-cloud-datastore)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<0.2.0dev,>=0.1.1->google-cloud-datastore)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<0.2.0dev,>=0.1.1->google-cloud-datastore)
Requirement already satisfied: certifi>=2017.4.17 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core<0.2.0dev,>=0.1.1->google-cloud-datastore)
Requirement already satisfied: cachetools>=2.0.0 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-auth<2.0.0dev,>=0.4.0->google-api-core<0.2.0dev,>=0.1.1->google-cloud-datastore)
Requirement already satisfied: rsa>=3.1.4 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-auth<2.0.0dev,>=0.4.0->google-api-core<0.2.0dev,>=0.1.1->google-cloud-datastore)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-auth<2.0.0dev,>=0.4.0->google-api-core<0.2.0dev,>=0.1.1->google-cloud-datastore)
Requirement already satisfied: pyasn1>=0.1.7 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from google-auth<2.0.0dev,>=0.4.0->google-api-core<0.2.0dev,>=0.1.1->google-cloud-datastore)
Requirement already satisfied: httplib2>=0.9.1 in /Users/orkenstein/.local/share/virtualenvs/hugepython9000-8Cdyqm-S/lib/python3.6/site-packages (from oauth2client<4.0dev,>=2.0.0->gapic-google-cloud-datastore-v1<0.16dev,>=0.15.0->google-cloud-datastore)
Cleaning up...

Adding google-cloud-datastore to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1002, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 865, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 625, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1934, in install
    do_lock(system=system, pre=pre)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 1102, in do_lock
    pre=pre
  File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 578, in resolve_deps
    r = requests.get('https://pypi.org/pypi/{0}/json'.format(name), timeout=10)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=10)
```
</details>

##### Steps to replicate
`pipenv install --verbose google-cloud-datastore`

There's a `timeout` parameter in pip & pip3. How to use it in pipenv?

**UPDATE**:
It was finally installed after 7-8 attempts.

**Comment by orkenstein** [comment]
@kennethreitz could you, please, take a look?

**Comment by kennethreitz** [comment]
there's a configurable timeout, via environment variables. see the documentation.

**Comment by orkenstein** [comment]
@kennethreitz could you, please, point which var to use? I've tried `pip` variables, but this doesn't look like helped.

**Comment by grv87** [comment]
@orkenstein, I believe @kennethreitz meant [PIPENV_TIMEOUT environment variable](https://docs.pipenv.org/advanced/#configuration-with-environment-variables). I had the same problem, this var solved it.
