### ISSUE TITLE
pipenv install fails on Linux when os_name is specified for package pypiwin32

### ISSUE THREAD

**Issue by DesktopMan** [pypa/pipenv#1277]
Pipfile:

```
[[source]]
name = "pypi"
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages]
pypiwin32 = {version = "*", os_name = "== 'nt'"}
requests = "*"
```

I expect _pypiwin32_ to be ignored on Linux. Something goes wrong and the install fails. I tried the same configuration with the example in the manual, _pywinusb_, and it works as expected (_pywinusb_ is skipped).

##### Describe your environment

1. OS Type: Ubuntu 16.04 x86-64
1. Python version: 3.5.2
1. Pipenv version: 9.0.1

##### Expected result

_requests_ is installed and _pypiwin32_ is ignored.

##### Actual result

Install fails with:

```
pipenv install --python 3.5 --verbose
Creating a virtualenv for this project…
Using /usr/bin/python3.5m to create virtualenv…
⠋Running virtualenv with interpreter /usr/bin/python3.5m
Using base prefix '/usr'
New python executable in /home/user/.local/share/virtualenvs/temp-doVRGgBk/bin/python3.5m
Also creating executable in /home/user/.local/share/virtualenvs/temp-doVRGgBk/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/user/.local/share/virtualenvs/temp-doVRGgBk
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…                                                                                                        Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==9.0.1', 'console_scripts', 'pipenv')()
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 1865, in install
    do_init(dev=dev, allow_global=system, ignore_pipfile=ignore_pipfile, system=system, skip_lock=skip_lock, verbose=verbose, concurrent=concurrent, deploy=deploy, pre=pre)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 1311, in do_init
    do_lock(system=system, pre=pre)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 1102, in do_lock
    pre=pre
  File "/usr/local/lib/python3.5/dist-packages/pipenv/utils.py", line 545, in resolve_deps
    resolved_tree = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/utils.py", line 507, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/piptools/resolver.py", line 278, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmphoq6fp33build/pypiwin32/
```

##### Steps to replicate

Create the _Pipfile_ as specified above and run _pipenv install_.

**Comment by techalchemy** [comment]
Hey @DesktopMan thanks for the report and sorry you're running into this.  This is a tricky one to be sure -- it has to do with how pipenv uses the pip-tools resolver.  Essentially because the goal of pipenv is to produce a portable `Pipfile` the resolver attempts to resolve dependencies for things in your lockfile even if they are not supposed to be installed.  Normally this is fine, but `pypiwin32` does a lot of fancy things in its `setup.py` that involve importing and operating on the windows API without first verifying that the caller OS is indeed windows.  I'd say the solution for now would be that you can skip locking here or perform the locking on a windows machine... not the answer you're looking for perhaps, but this is not an issue that will be easily resolved without rethinking a few things.

**Comment by kennethreitz** [comment]
nothing we can do here
