### ISSUE TITLE
Issues with python_version marker in pyenv install

### ISSUE THREAD

**Issue by Code0x58** [pypa/pipenv#1329]
Using pipenv 9.0.3 on python 3.6.4 the following failed:
```sh
$ pipenv --three install "enum==0.4.6; python_version < '3.4'"
…
Creating a Pipfile for this project…
Installing enum==0.4.6; python_version < '3.4'…
⠧
Adding enum==0.4.6; python_version < '3.4' to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 1934, in install
    do_lock(system=system, pre=pre)
  File "/venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 1093, in do_lock
    deps = convert_deps_to_pip(project.packages, project, r=False, include_index=True)
  File "/venvs/pipenv/lib/python3.6/site-packages/pipenv/utils.py", line 742, in convert_deps_to_pip
    if not deps[dep]['version'] == '*':
TypeError: string indices must be integers
```
This leads to `enum = "==0.4.6; python-version < '3.4'"` being in the `Pipfile`'s packages section although I think it should be `enum = {version = "==0.4.6", python_version = "< '3.4'"}`. There is same outcome when using `--two`.

I also tried using a requirements file instead, the attempt at [dependency resolution](https://github.com/pypa/pipenv/issues/1277#issuecomment-356153687) highlighted that the [`enum`](https://pypi.python.org/pypi/enum) isn't intended for compatibility (I should have used [`enum-compat`](https://pypi.python.org/pypi/enum-compat/0.0.2)):
```
$ pipenv --three install --requirements requirements.txt
…
Creating a Pipfile for this project…
Requirements file provided! Importing into Pipfile…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (2c7e63)!
Installing dependencies from Pipfile.lock (2c7e63)…
An error occurred while installing enum==0.4.6! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:00
Installing initially–failed dependencies…
Collecting enum==0.4.6 ▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:00
  Using cached enum-0.4.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/share/virtualenvs/test-hxkKlP5o/lib/python3.6/site-packages/setuptools/__init__.py", line 5, in <module>
        import distutils.core
      File "/share/virtualenvs/test-hxkKlP5o/lib/python3.6/distutils/__init__.py", line 4, in <module>
        import imp
      File "/share/virtualenvs/test-hxkKlP5o/lib/python3.6/imp.py", line 27, in <module>
        import tokenize
      File "/share/virtualenvs/test-hxkKlP5o/lib/python3.6/tokenize.py", line 33, in <module>
        import re
      File "/share/virtualenvs/test-hxkKlP5o/lib/python3.6/re.py", line 142, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0uqv6ezh/enum/

  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:00
```
This leads to `enum = "==0.4.6"` ending up in the `Pipfile`'s (same with `--two` but it installs).

It seems like the issues are:
 * `--requirements` isn't pick picking up marker requirements
 * requirements added as args aren't parsed correctly

**Comment by kennethreitz** [comment]
markers must be placed in the pipfile directly, currently.
