### ISSUE TITLE
pyenv + pipenv issues

### ISSUE THREAD

**Issue by ezeeyahoo** [pypa/pipenv#1333]
pipenv is throwing error, trying to find pip at /bin/. --user not provided with pip install pipenv because it is not working with shims/python resulting in "command not found" error.

##### Describe your environment

1. OS Type: macOS 10.13
1. Python version: `$ python -V` Python 3.6.4
1. Pipenv version: `$ pipenv --version` pip 9.0.1 from /Users/eshant/.pyenv/versions/3.6.4/lib/python3.6/site-packages (python 3.6)

##### Expected result

pipenv should install packages

##### Actual result
```
❯ pipenv install requests
Creating a virtualenv for this project…
⠋Traceback (most recent call last):
  File "/Users/eshant/.pyenv/versions/3.6.4/bin/pew", line 7, in <module>
    from pew.pew import pew
  File "/Users/eshant/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pew/__init__.py", line 3, in <module>
    from . import pew
  File "/Users/eshant/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pew/pew.py", line 41, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/Users/eshant/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pew/_utils.py", line 22, in <module>
    encoding = locale.getlocale()[1] or 'ascii'
  File "/Users/eshant/.pyenv/versions/3.6.4/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/Users/eshant/.pyenv/versions/3.6.4/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

Virtualenv location:
Creating a Pipfile for this project…
Installing requests…
⠴
Error:  An error occurred while installing requests!
/bin/sh: /bin/pip: No such file or directory
```

##### Steps to replicate
```
$ brew install pyenv
$ pyenv install 3.6.4
$ pyenv global 3.6.4
$ exec $SHELL
$ pyenv versions
  system
* 3.6.4 (set by /Users/eshant/.pyenv/version)
$ pip install pipenv
$ mkcd test
$ pipenv install requests

```

**Comment by uranusjr** [comment]
This is probably not related to pyenv, but a macOS bug. See #187.

**Comment by ezeeyahoo** [comment]
I will try and let you know later. Thanks

**Comment by ezeeyahoo** [comment]
Issue resolved!
