### ISSUE TITLE
Fail to install new projects

### ISSUE THREAD

**Issue by addohm** [pypa/pipenv#1352]
Be sure to check the existing issues, both open and closed.

With any (new or existing) project I get this - pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmp13ba53__build/mysqlclient/.

##### Describe your environment

1. Environment: Ubuntu Budgie 17.1
1. Python version: 3.6
1. Pipenv version: 9.0.3

##### Expected result

Duh?

##### Actual result

addohm@budgie-p50:~/django-projects/mgRest$ pipenv install --verbose
Creating a virtualenv for this project…
⠋Using base prefix '/usr'
New python executable in /home/addohm/.local/share/virtualenvs/mgRest-BFqGcu6E/bin/python3
Also creating executable in /home/addohm/.local/share/virtualenvs/mgRest-BFqGcu6E/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/addohm/.local/share/virtualenvs/mgRest-BFqGcu6E
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/cli.py", line 1865, in install
    do_init(dev=dev, allow_global=system, ignore_pipfile=ignore_pipfile, system=system, skip_lock=skip_lock, verbose=verbose, concurrent=concurrent, deploy=deploy, pre=pre)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/cli.py", line 1311, in do_init
    do_lock(system=system, pre=pre)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/cli.py", line 1102, in do_lock
    pre=pre
  File "/usr/local/lib/python3.6/dist-packages/pipenv/utils.py", line 545, in resolve_deps
    resolved_tree = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/utils.py", line 507, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/resolver.py", line 296, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmppk1h5skgbuild/mysqlclient/

##### Steps to replicate

pip install --verbose

**Comment by addohm** [comment]
As a follow up, it appears that pipenv install looks for requirements.txt in places other than where it's ran from.  Where are these locations?

**Comment by chgad** [comment]
:+1: encountered same issue  with mysqlclient.

**Comment by chgad** [comment]
Why was this closed ?

**Comment by harri00413** [comment]
I have the same issue with mysqlclient on Mac os x.

**Comment by uranusjr** [comment]
Please kindly search for `egg_info` in the issue tracker; there are various instances of this issue with many packages. This is closed because it is considered a duplicate.
