### ISSUE TITLE
pipenv install with vcs, editable, and path defined results in key error

### ISSUE THREAD

**Issue by spott** [pypa/pipenv#1401]
```
pipenv install
```
where Pipfile is:
```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

package = {git = "git@bitbucket.org:***/hoot.git", path = ".", editable = true}

[dev-packages]



[requires]

python_version = "3.6"
```

##### Describe your environment

1. OS X
1. Python version: python3.6
1. Pipenv version:  9.0.3

##### Expected result

An "bad combination" error will be thrown rather than a non-descriptive key error.

##### Actual result

```
Traceback (most recent call last):
  File "/Users/spott/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/spott/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/spott/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/spott/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/spott/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/spott/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/spott/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 1865, in install
    do_init(dev=dev, allow_global=system, ignore_pipfile=ignore_pipfile, system=system, skip_lock=skip_lock, verbose=verbose, concurrent=concurrent, deploy=deploy, pre=pre)
  File "/Users/spott/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 1311, in do_init
    do_lock(system=system, pre=pre)
  File "/Users/spott/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 1093, in do_lock
    deps = convert_deps_to_pip(project.packages, project, r=False, include_index=True)
  File "/Users/spott/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/utils.py", line 790, in convert_deps_to_pip
    extra = '{0}+{1}'.format(vcs, deps[dep][vcs])
KeyError: '-e '
```

**Comment by techalchemy** [comment]
Thanks for the report - You shouldn’t attempt to generate this kind of entry manually if you aren’t sure about the parameters. The path argument points at a local filesystem path when searching for what package to install. The vcs parameter points at a uri for the same reason.  These are mutually exclusive and shouldn’t ever appear in the same entry. We can think about improving the error message here but honestly you should let pipenv generate your pipfile.
