### ISSUE TITLE
pipenv install '-e .' --dev   raises TypeError

### ISSUE THREAD

**Issue by benjaminweb** [pypa/pipenv#1420]
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

##### Describe your environment

1. OS Type Mac OS X 10.12.6
1. Python version: `$ python -V` 3.6.3
1. Pipenv version: `$ pipenv --version` 8.3.2

##### Expected result

pipenv to install the module located in current working directory with its deps in editable mode.

##### Actual result

```python
⋊> pipenv install '-e .' --dev
Installing -e .…
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/8.3.2_1/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.3.2', 'console_scripts', 'pipenv')()
  File "/usr/local/Cellar/pipenv/8.3.2_1/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/8.3.2_1/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/8.3.2_1/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/pipenv/8.3.2_1/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/8.3.2_1/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/8.3.2_1/libexec/lib/python3.6/site-packages/pipenv/cli.py", line 1880, in install
    converted = convert_deps_from_pip(package_name)
  File "/usr/local/Cellar/pipenv/8.3.2_1/libexec/lib/python3.6/site-packages/pipenv/utils.py", line 547, in convert_deps_from_pip
    os.path.isfile(req.name)) and not req.vcs:
  File "/usr/local/Cellar/pipenv/8.3.2_1/libexec/bin/../lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType


```
##### Steps to replicate
Pipfile
```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

pytest-redis = "*"
flask-mail = "*"
dataset = "*"
pendulum = "*"
regex = "*"


[dev-packages]
pytest = "*"
```

`pipenv install '-e .' --dev` taken from https://docs.pipenv.org/basics/#editable-dependencies-e-g-e

However, `pipenv install . -e --dev` seems to work.

**Comment by techalchemy** [comment]
Thanks for the report

I believe this will be fixed in #1372 but if you are on osx please do make sure you have LC_ALL set properly.  Also please try without the quotes. Please let me know if you have any further questions

**Comment by benjaminweb** [comment]
``echo $LC_ALL``

gives me `en_US.UTF-8`

**Comment by techalchemy** [comment]
Ok you’re good there. Does it work without the quotes?

**Comment by benjaminweb** [comment]
pipenv 9.0.3 does work with the quotes.
However, `pipenv install '-e .'` does not instantiate `Pipfile` (after deleting `Pipfile` and `Pipfile.lock`).

Relates to https://github.com/pypa/pipenv/issues/1263#issuecomment-364991783

**Comment by techalchemy** [comment]
stop using quotation marks, feel free to either:

1) test out the code in #1372 and see if it works with the single quotes, or 
2) submit a PR for a documentation update removing them
