### ISSUE TITLE
Improve experience of debugging failed installs with pipenv

### ISSUE THREAD

**Issue by jtratner** [pypa/pipenv#1434]
I was trying to debug why pipenv was failing on an IPython install in OSX.  I was getting errors like this:

```
›› pipenv install --verbose
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv', 'console_scripts', 'pipenv')()
<long traceback>
  File "/Users/jtratner/pipenv/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/fm/sjgpzb856kld04jvq82bxrcw0000gp/T/tmp4cQKivbuild/ipython/
```
but with no ability to actually look at what the error was because temp file got removed.

By adding 

```
logger.setLevel(std_logging.INFO)
```

to pipenv/pipenv/patched/pip/utils/__init__.py, I was able to get to underlying error message.  But just using `--verbose` flag didn't really get anywhere.

It'd be nice to either be able to specify a loglevel to pip/pipenv so you can see build failures or have the `--verbose` flag pass through to pip itself. (and if there's a way to do this or a way you'd *like* to do this, perhaps we could add it to the documentation).

(It turned out it was the good old error like this:

```
INFO:pip.utils:Complete output from command python setup.py egg_info:
INFO:pip.utils:
IPython 6.0+ does not support Python 2.6, 2.7, 3.0, 3.1, or 3.2.
When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
Beginning with IPython 6.0, Python 3.3 and above is required.

See IPython `README.rst` file for more information:

    https://github.com/ipython/ipython/blob/master/README.rst

Python sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0) detected.
```
)

##### Describe your environment

1. OS Type OS X
1. Python version: `2.7.14`
1. Pipenv version: (latest master)

**Comment by kennethreitz** [comment]
I'm definately open to having `--verbose` set the log level.

**Comment by jtratner** [comment]
How do you feel about something like this?

1. Can specify it multiple times (and “-v” is synonym for “—verbose”)
2.Single “-v” dumps more output, like “—verbose” now
3. “-vv” sets INFO loglevel for pip (and maybe pipenv)
4. “-vvv” sets DEBUG loglevel for pip and pipenv

**Comment by kennethreitz** [comment]
no need for that, let's just add the logging info to standard verbose mode.

**Comment by ktosiek** [comment]
This is still broken for weasyprint==50. The error is:
```
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 386, in prepare_files
    raise hash_errors
pip.exceptions.HashErrors: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    setuptools>=1.0 from https://nexus.dcs.pl/repository/pypi/packages/54/28/c45d8b54c1339f9644b87663945e54a8503cfef59cf0f65b3ff5dd17cf64/setuptools-42.0.2-py2.py3-none-any.whl#sha256=c8abd0f3574bc23afd2f6fd2c415ba7d9e097c8a99b845473b0d957ba1e2dac6 (from workalendar==7.2.0->-r /tmp/pipenv-7cio9314-requirements/pipenv-5w49bdpq-requirement.txt (line 1))
```
