### ISSUE TITLE
pipenv graph json yields stacktrace, pipenv graph merely exits

### ISSUE THREAD

**Issue by mdaniel** [pypa/pipenv#1455]
- [X] Be sure to check the existing issues, [both open and closed](https://github.com/pypa/pipenv/issues?utf8=%E2%9C%93&q=graph+json)

_Describe the issue briefly here_

Running `pipenv graph --json` without a `pipenv` virtualenv yields a very ugly stacktrace; `pipenv graph` yields no such stacktrace, just empty output

##### Describe your environment

1. macOS, 10.13.3
1. `Python 2.7.14; Python 3.6.4`
1. `pipenv, version 9.0.3` (also tested with 9.1.0 as `--update` did more than I expected it to)

##### Expected result

```
$ pipenv graph --json
[]
```

##### Actual result

The ticket template requested `--verbose` output, but:
```
$ pipenv graph --json --verbose
Error: no such option: --verbose
```

```
$ pipenv graph --json
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/9.0.3/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==9.0.3', 'console_scripts', 'pipenv')()
  File "/usr/local/Cellar/pipenv/9.0.3/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/9.0.3/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/9.0.3/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/pipenv/9.0.3/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/9.0.3/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/9.0.3/libexec/lib/python3.6/site-packages/pipenv/cli.py", line 2422, in graph
    for d in simplejson.loads(c.out):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

##### Steps to replicate

```
$ cd `mktemp -d pipenv.XXXXX`
$ pipenv install six
$ pipenv --rm
$ pipenv graph --json
```

**Comment by soulomoon** [comment]
+1 same here with brew python,
while pyenv installed python is fine

**Comment by dschaller** [comment]
Working on a fix for this now
