### ISSUE TITLE
pipenv lock --requirements --dev fails if -e . is installed

### ISSUE THREAD

**Issue by hynek** [pypa/pipenv#1534]
This issue is new in 11.0.(1?)

If you have a lock file with some dependency *and* did `pipenv install --dev -e .`, a `pipenv lock --requirements --dev` will fail like this:

```
Traceback (most recent call last):
  File "/Users/hynek/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/hynek/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hynek/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/hynek/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hynek/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hynek/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/hynek/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/cli.py", line 245, in lock
    core.do_init(dev=dev, requirements=requirements)
  File "/Users/hynek/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/core.py", line 1367, in do_init
    skip_lock=skip_lock, verbose=verbose, concurrent=concurrent)
  File "/Users/hynek/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/core.py", line 833, in do_install_dependencies
    click.echo('\n'.join(d[0] for d in sorted(dev_deps_list)))
TypeError: '<' not supported between instances of 'list' and 'tuple'
```

##### Describe your environment

1. OS Type macOS
1. Python version: `$ python -V` 3.6.4
1. Pipenv version: `$ pipenv --version` 11.0.1

##### Expected result

A list of dependencies.

##### Actual result

The traceback above. Adding `--verbose` doesn’t change the output.

##### Steps to replicate

1. Create an empty directory
2. Add a setup.py into it:

```
from setuptools import setup

setup(name="t", version="1.0", py_modules=["t"])
```
3. And an empty t.py for good measure: `touch t.py`
4. Install some stuff: `pipenv install --dev pytest`
5. Install current package: `pipenv install --dev -e .` (installing both at once leads to an error, pretty sure that’s a bug too?)
6. Finally call: `pipenv lock --verbose --requirements --dev` and get the traceback from above.

I tried to pdb it and the problem is that all deps in `dev_deps_list` are tuples except for `['# -e .', True, True]`.

This shouldn’t happen on Python 2 albeit it returns a wrong results (just try `(1,) < [2,]` in a Python 2 repl).

**Comment by tekulvw** [comment]
Should be fixed with #1533

**Comment by kennethreitz** [comment]
this should be fixed in master

**Comment by kennethreitz** [comment]
11.0.2 released, which contains this fix

**Comment by hynek** [comment]
Wonderful!

**Comment by kennethreitz** [comment]
p.s. all my projects also have a `t.py` file

**Comment by hynek** [comment]
Part of every proper global .gitignore. 😂
