### ISSUE TITLE
pipenv --update blows up in Dockerfile

### ISSUE THREAD

**Issue by dknesek** [pypa/pipenv#1561]
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

"pipenv --update" fails in build of dockerfile

##### Describe your environment

1. OSX 10.13.3
1. Python version: 2.7.10
1. Pipenv version: 11.0.2

##### Expected result

A normal pipenv update

##### Actual result
...
Step 10/15 : RUN pipenv --update
 ---> Running in 3a92d44aeca0
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/requests/packages/urllib3/util/ssl_.py", line 295, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/requests/packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/requests/packages/urllib3/util/ssl_.py", line 297, in ssl_wrap_socket
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pipenv/core.py", line 168, in ensure_latest_self
    r = requests.get('https://pypi.python.org/pypi/pipenv/json', timeout=2)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.0.2', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/cli.py", line 60, in cli
    core.ensure_latest_self()
  File "/usr/lib/python3.6/site-packages/pipenv/core.py", line 170, in ensure_latest_self
    click.echo(crayons.red(e))
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/utils.py", line 221, in echo
    message = text_type(message)
TypeError: __str__ returned non-string (type SSLError)
The command '/bin/sh -c pipenv --update' returned a non-zero code: 1

##### Steps to replicate

------ Dockerfile ------
FROM google/cloud-sdk:alpine

LABEL maintainer="doug.knesek@gmail.com"
LABEL version="1.0"
LABEL description="Simple Google Cloud SDK-Based Devlopment. Python on Alpine."

RUN apk add --no-cache \
        libstdc++ && \
    apk add --no-cache --virtual .build-deps \
        binutils-gold \
        curl \
        g++ \
        gcc \
        gnupg \
        libgcc \
        linux-headers \
        zlib-dev \
        jpeg-dev \
        make \
        git \
        python3 \
        python3-dev \
        vim \
        openssh-client \
        sudo

RUN addgroup -g 1000 developer && \
    adduser -u 1000 -G developer -s /bin/sh -D developer

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN pip3 install pipenv
RUN pipenv --update

USER developer
WORKDIR /home/developer

RUN pipenv --three && \
    pipenv install mock ujson nose && \
    pipenv install google-cloud && \
    pipenv install requests socketIO-client-nexus ujson pillow && \
    pipenv install IPython pandas

ENV GOOGLE_APPLICATION_CREDENTIALS='/home/developer/XXXXXXX-9af834918ef4.json'
ENV exitPS1="\$? > "

**Comment by kennethreitz** [comment]
please check out our example dockerfile https://github.com/pypa/pipenv/blob/master/Dockerfile

**Comment by seslattery** [comment]
Fwiw you're likely missing ca-certificates.  "apk add ca-certificates" should help.
