### ISSUE TITLE
Pipenv cannot find Python

### ISSUE THREAD

**Issue by dspechnikov** [pypa/pipenv#1582]
I'm using pipenv in the following docker image:
```
FROM python:3.6.4
RUN mkdir /app
WORKDIR /app
ADD ./ /app/
RUN pip install pipenv
RUN pipenv install --system --deploy
```

`pipenv install` command fails.

##### Describe your environment

1. Docker
2. Python version: `3.6.4`
3. Pipenv version: `11.1.1`

##### Expected result

All dependencies installed successfully.

##### Actual result

`pipenv install` fails with the following error:
```
 ---> Running in fb1741a0385e
Installing dependencies from Pipfile.lock (a1fc0a)…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 197, in install
    selective_upgrade=selective_upgrade
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1835, in do_install
    pre=pre, requirements_dir=requirements_directory
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1372, in do_init
    requirements_dir=requirements_dir.name)
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 856, in do_install_dependencies
    requirements_dir=requirements_dir
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1473, in pip_install
    c = delegator.run(pip_command, block=block)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/delegator.py", line 267, in run
    c.run(block=block, binary=binary)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/delegator.py", line 156, in run
    s = PopenSpawn(self._popen_args, **pexpect_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/pexpect/popen_spawn.py", line 46, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/python -m pip': '/usr/local/bin/python -m pip'
ERROR: Service 'backend_1' failed to build: The command '/bin/sh -c /bin/bash -c "pipenv install --system --deploy"' returned a non-zero code: 1
```

##### Additional info

When I use bash for `install` command like this:
`RUN ["/bin/bash", "-c", "pipenv install --system --deploy"]`
it works fine.

The issue appeared in version `11.1.1`, `10.1.2` worked fine. 

Since changing the shell fixes the issue, I'm not really sure it's pipenv problem, but since it broke with the pipenv update, I think we need at least investigate it.

**Comment by kennethreitz** [comment]
fixed
