### ISSUE TITLE
Crash running `pipenv lock -r`

### ISSUE THREAD

**Issue by ipmb** [pypa/pipenv#1588]
This is a regression that started in 11.1.2

##### Describe your environment

1. MacOS
1. Python version: `Python 3.6.4`
1. Pipenv version: `pipenv, version 11.1.3`

##### Expected result

a list of requirements

##### Actual result

```
$ pipenv lock --verbose -r
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 245, in lock
    core.do_init(dev=dev, requirements=requirements)
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1373, in do_init
    requirements_dir=requirements_dir.name)
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 827, in do_install_dependencies
    click.echo('\n'.join(d[0] for d in sorted(deps_list)))
TypeError: '<' not supported between instances of 'tuple' and 'list'
```

##### Steps to replicate

On a local project with `install_requires` dependencies defined in `setup.cfg`:

```
pipenv install -e .
pipenv lock -r
```

**Comment by kennethreitz** [comment]
omg

**Comment by varnion** [comment]
I'm having the same issue. Reverting back to pipenv 11.0.2 solves if you need this feature desperately =/
