### ISSUE TITLE
pkg_resources.ContextualVersionConflict: psutil 5.4.3, psutil==5.3.1, sys_platform == "win32"

### ISSUE THREAD

**Issue by bityob** [pypa/pipenv#1602]
I just upgraded `pipenv` to the latest version: `11.1.4`.

After installation was done, I tried to run `pipenv --version`, but it failed.

```batch
C:\windows\system32>pipenv --version
Traceback (most recent call last):
  File "c:\python364-32\lib\site-packages\pkg_resources\__init__.py", line 681, in _build_master
    ws.require(__requires__)
  File "c:\python364-32\lib\site-packages\pkg_resources\__init__.py", line 999, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\python364-32\lib\site-packages\pkg_resources\__init__.py", line 890, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (psutil 5.4.3 (c:\python364-32\lib\site-packages), Requirement.parse('psutil==5.3.1; sys_platform == "win32"'), {'pew'})
```

##### Describe your environment

1. OS Type - **Windows**
1. Python version: `$ python -V` - **Python 3.6.4**
1. Pipenv version: `$ pipenv --version` - **11.1.4**

##### Expected result

Excepted to received nice output of `pipenv` version.

It happens, of course, no matter which command I choose to to use with `pipenv`.

The same is for just typing `pipenv`

```batch
C:\windows\system32>pipenv
Traceback (most recent call last):
  File "c:\python364-32\lib\site-packages\pkg_resources\__init__.py", line 681, in _build_master
    ws.require(__requires__)
  File "c:\python364-32\lib\site-packages\pkg_resources\__init__.py", line 999, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\python364-32\lib\site-packages\pkg_resources\__init__.py", line 890, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (psutil 5.4.3 (c:\python364-32\lib\site-packages), Requirement.parse('psutil==5.3.1; sys_platform == "win32"'), {'pew'})
```

##### Actual result

See output below.

##### Steps to replicate

`pip install pipenv --upgrade`

**Comment by bityob** [comment]
Seems the same error like this issue - https://github.com/pypa/pipenv/issues/724

But the problem there was with **urllib3** and now it is **psutil**

**Comment by bityob** [comment]
I installed `psutil==5.3.1`, and it works - 

```batch
C:\windows\system32>pip install psutil==5.3.1
Collecting psutil==5.3.1
  Downloading psutil-5.3.1-cp36-cp36m-win32.whl (212kB)
    100% |████████████████████████████████| 215kB 989kB/s
Installing collected packages: psutil
  Found existing installation: psutil 5.4.3
    Uninstalling psutil-5.4.3:
      Successfully uninstalled psutil-5.4.3
Successfully installed psutil-5.3.1

C:\windows\system32>pipenv --version
pipenv, version 11.1.4
```

So maybe `setup.py` needs to be updated

**Comment by kennethreitz** [comment]
fixed in master

**Comment by techalchemy** [comment]
see #1587 and #1600 

New release cut which does not depend on psutil
