### ISSUE TITLE
pipenv install fails when run with ansible

### ISSUE THREAD

**Issue by andreyst** [pypa/pipenv#1604]
I'm trying to do pipenv install with ansible on remote server and it fails with an error. Logging to remote server manually and performing install works good (see below).

I think the problem is with the way ansible calls remote command, not pipenv itself, but I cannot figure out what exactly the problem is from the error message.

##### Environment

1. Ubuntu 16.04.3 LTS (on remote host), macOS Sierra 10.12.6 (on local host)
1. Python version: 2.7.12 (on remote host), 2.7.10 (on local host)
1. Pipenv version: 11.1.4
1. ansible 2.3.0.0

##### Expected result

Expected ```pipenv install``` to complete successfully with ansible, same as when running it directly on remote host.

##### Actual result

Install with ansible:
```
$ ansible all -a "~/.local/bin/pipenv install" -i hosts --key-file "~/.ssh/krz-2017.pem" -u ubuntu
54.194.198.151 | FAILED | rc=1 >>
Installing dependencies from Pipfile.lock (235fde)…Creating a virtualenv for this project…
New python executable in /home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: 
Creating a virtualenv for this project…
New python executable in /home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: 
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/cli.py", line 197, in install
    selective_upgrade=selective_upgrade
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/core.py", line 1836, in do_install
    pre=pre, requirements_dir=requirements_directory
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/core.py", line 1373, in do_init
    requirements_dir=requirements_dir.name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/core.py", line 857, in do_install_dependencies
    requirements_dir=requirements_dir
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/core.py", line 1474, in pip_install
    c = delegator.run(pip_command, block=block)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/vendor/delegator.py", line 267, in run
    c.run(block=block, binary=binary)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/vendor/delegator.py", line 156, in run
    s = PopenSpawn(self._popen_args, **pexpect_kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/vendor/pexpect/popen_spawn.py", line 46, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/utils.py:1149: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-LkId6a-requirements'>
  warnings.warn(warn_message, ResourceWarning)
```

**Manual installation:**
```
$ ssh -i ~/.ssh/krz-2017.pem ubuntu@54.194.198.151
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-1047-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

80 packages can be updated.
38 updates are security updates.


*** System restart required ***
Last login: Thu Mar  8 15:22:30 2018 from 93.80.236.70
ubuntu@ip-10-0-1-247:~$ pipenv install
Installing dependencies from Pipfile.lock (235fde)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 31/31 — 00:00:41
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

Env on remote host (don't know it if matters):
```
ubuntu@ip-10-0-1-247:~$ export
declare -x HOME="/home/ubuntu"
declare -x LANG="en_US.UTF-8"
declare -x LESSCLOSE="/usr/bin/lesspipe %s %s"
declare -x LESSOPEN="| /usr/bin/lesspipe %s"
declare -x LOGNAME="ubuntu"
declare -x LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
declare -x MAIL="/var/mail/ubuntu"
declare -x OLDPWD
declare -x PATH="/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
declare -x PWD="/home/ubuntu"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SSH_CLIENT="***"
declare -x SSH_CONNECTION="***"
declare -x SSH_TTY="/dev/pts/0"
declare -x TERM="xterm-256color"
declare -x USER="ubuntu"
declare -x XDG_DATA_DIRS="/usr/local/share:/usr/share:/var/lib/snapd/desktop"
declare -x XDG_RUNTIME_DIR="/run/user/1000"
declare -x XDG_SESSION_ID="23"
```

##### Steps to replicate

1. Launch a AWS instance with AMI ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180109 (ami-4d46d534)
2. Install python, pip and pipenv with following ansible tasks:
```
  - name: install python 2
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python-minimal)
  - name: install pip
    raw: test -e /usr/bin/pip || (sudo apt -y update && sudo apt install -y python-pip)
  - pip:
      name: pipenv
```
3. Try to ```pipenv install``` with ansible:
```ansible <match> -a "~/.local/bin/pipenv install" -i <hosts file> --key-file "<key file>" -u ubuntu```

**Comment by techalchemy** [comment]
since you're running with a devops suite you probably want to disable spinners and such, and you definitely need your locale set... here are the relevant environment vars you will want:

```env
LC_ALL=C.UTF-8
PIPENV_NOSPIN=1
PIPENV_COLORBLIND=1
PIPENV_YES=1
```

As a general FYI pipenv works much more consistently when used with python 3, but I dopn't know much about ansible and your limitations... These settings are used on CI pretty often and they basically disable graphical artifacts and prompting.

**Comment by andreyst** [comment]
@techalchemy Thank you for your tips, Dan! The actual issue was not with locale, but with missing PATH env var, but your comment helped me realize that. Setting PATH explicitly remedied the issue. 

Thank you also for pointing out other useful env vars!

Reproducing the issue is actually much easier:
```$ PATH= /home/ubuntu/.local/bin/pipenv install
...
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

If pipenv would give more detailed error message in this place, it would be more user-friendly and help diagnose the issue faster.
