### ISSUE TITLE
Traceback when trying to create an environment w/ interpreter specified by its path

### ISSUE THREAD

**Issue by brettcannon** [pypa/pipenv#1619]
Can't create an environment with the Python interpreter specified on the command-line (don't know if other options work since I only have `py` on my PATH).

##### Describe your environment

1. OS Type: Windows 10
1. Python version: 3.6.4
1. Pipenv version: 1.11.5

##### Expected result

A virtual environment is created.

##### Actual result

An exception was raised.

##### Steps to replicate

```
> py -3 -m pipenv --python C:\Users\brcan\AppData\Local\Programs\Python\Python36\python.exe
Creating a virtualenv for this project…
Using C:\Users\brcan\AppData\Local\Programs\Python\Python36\python.exe to create virtualenv…
Already using interpreter C:\Users\brcan\AppData\Local\Programs\Python\Python36\python.exe
Using base prefix 'C:\\Users\\brcan\\AppData\\Local\\Programs\\Python\\Python36'
New python executable in C:\Users\brcan\.virtualenvs\bunk-M_X9FcBv\Scripts\python.exe
Installing setuptools, pip, wheel...done.

Virtualenv location:
Traceback (most recent call last):
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\__main__.py", line 4, in <module>
    cli()
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\vendor\click\core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\vendor\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\cli.py", line 154, in cli
    core.ensure_project(three=three, python=python, warn=True, site_packages=site_packages)
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\core.py", line 638, in ensure_project
    crayons.green(shorten_path(path_to_python))
  File "C:\Users\brcan\AppData\Local\Programs\Python\Python36\lib\site-packages\pipenv\core.py", line 698, in shorten_path
    short = os.sep.join([s[0] if len(s) > (len('2long4')) else s for s in location.split(os.sep)])
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by kennethreitz** [comment]
I apologize for there being so many issues with Windows — our userbase on Windows is small, so we don't get many reports.

We do test on windows, though!

**Comment by kennethreitz** [comment]
P.S. Want to write a breaking test? :)

**Comment by techalchemy** [comment]
wow I haven't ever seen that one before....

**Comment by brettcannon** [comment]
No problem about the breakage; I realize I'm trailblazing here. 😄 I'm happy to keep trying and filing issues as I come across them to help out, so no hard feelings at all on my end.

As for writing the test, I will see if I can find the time but I unfortunately can't make any promises ATM (I'm still playing catch-up with stuff that backed up from our latest release of VS Code which added pipenv support 😉 ).

**Comment by kennethreitz** [comment]
Just trying to @brettcannon into becoming a committer :)

**Comment by techalchemy** [comment]
You can make him a committer but that probably doesn't guarantee he'll ever commit anything :p

**Comment by brettcannon** [comment]
@techalchemy I can guarantee it makes not guarantees, just ask Nathaniel Smith about how much I have contributed to Trio after getting committer rights 😉

**Comment by uranusjr** [comment]
I think I’ve got it. The problem is not Windows-specific, but happens when you don’t have any `python` command available in `PATH` at all. Un\*x systems typically always have a system-wide `python`, which is likely why no-one found out until now.

**Comment by kennethreitz** [comment]
Aha! Nice catch, @uranusjr!

**Comment by uranusjr** [comment]
I’ll produce a pull request later (at work right now).

**Comment by uranusjr** [comment]
@kennethreitz Are you open to adding type-checking to some code paths (with something like mypy)? It would prevent some of these problems in the future.

**Comment by kennethreitz** [comment]
I think that would just add maintenance burden (and I’m not personally a fan of commented mypy typing, prefer hardcoded style).
