### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pyenv': 'pyenv' when trying to install anaconda

### ISSUE THREAD

**Issue by devxpy** [pypa/pipenv#1635]
##### Describe your environment

1. Kubuntu 17.10
2. Python version: `Python 3.6.3`
3. Pipenv version: `pipenv, version 11.1.7`
4. pyenv 1.2.2

##### Expected result

pipenv installs latest anaconda version for me and creates a virtualenv

##### Actual result

```
/mnt/Stuff/Projekt/testing! pipenv install --python anaconda --verbose
Warning: Python anaconda was not found on your system…
Would you like us to install CPython anaconda with pyenv? [Y/n]: 
Installing CPython anaconda with pyenv (this may take a few minutes)…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/cli.py", line 197, in install
    selective_upgrade=selective_upgrade
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 1768, in do_install
    ensure_project(three=three, python=python, system=system, warn=True, deploy=deploy, skip_requirements=skip_requirements)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 659, in ensure_project
    ensure_virtualenv(three=three, python=python, site_packages=site_packages)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 604, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 554, in ensure_python
    block=False
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/delegator.py", line 267, in run
    c.run(block=block, binary=binary)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/delegator.py", line 156, in run
    s = PopenSpawn(self._popen_args, **pexpect_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/pexpect/popen_spawn.py", line 46, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pyenv': 'pyenv'

```

##### Steps to replicate

`pipenv install --python anaconda --verbose`

**Comment by kennethreitz** [comment]
thanks for the report

**Comment by kennethreitz** [comment]
"pipenv installs latest anaconda version for me and creates a virtualenv"

we don't support that.

**Comment by devxpy** [comment]
Don't support "anaconda", or don't support "creates a virtualenv"?

**Comment by kennethreitz** [comment]
"anaconda"
