### ISSUE TITLE
Can't install the extra of urllib3

### ISSUE THREAD

**Issue by Azd325** [pypa/pipenv#1643]
On python 2.7 the extra get resolved but not taken over. Also the new `pipenv.help` fails on the half way.

```bash
❯ pipenv install "urllib3[secure]"
Creating a virtualenv for this project…
⠋New python executable in /Users/tim/.local/share/virtualenvs/test-GRNMnhLi/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/tim/.local/share/virtualenvs/test-GRNMnhLi
Creating a Pipfile for this project…
Installing urllib3[secure]…
Collecting urllib3[secure]
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna>=2.0.0; python_version <= "2.7" and extra == "secure" (from urllib3[secure])
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting pyOpenSSL>=0.14; python_version <= "2.7" and extra == "secure" (from urllib3[secure])
  Using cached pyOpenSSL-17.5.0-py2.py3-none-any.whl
Collecting cryptography>=1.3.4; python_version <= "2.7" and extra == "secure" (from urllib3[secure])
  Using cached cryptography-2.1.4-cp27-cp27m-macosx_10_6_intel.whl
Collecting certifi; extra == "secure" (from urllib3[secure])
  Using cached certifi-2018.1.18-py2.py3-none-any.whl
Collecting ipaddress; python_version <= "2.7" and extra == "secure" (from urllib3[secure])
Collecting six>=1.5.2 (from pyOpenSSL>=0.14; python_version <= "2.7" and extra == "secure"->urllib3[secure])
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure])
  Using cached asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure])
  Using cached cffi-1.11.5-cp27-cp27m-macosx_10_6_intel.whl
Collecting enum34; python_version < "3" (from cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure])
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure])
Installing collected packages: idna, asn1crypto, pycparser, cffi, enum34, six, ipaddress, cryptography, pyOpenSSL, certifi, urllib3
Successfully installed asn1crypto-0.24.0 certifi-2018.1.18 cffi-1.11.5 cryptography-2.1.4 enum34-1.1.6 idna-2.6 ipaddress-1.0.19 pyOpenSSL-17.5.0 pycparser-2.18 six-1.11.0 urllib3-1.22

Adding urllib3[secure] to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (c24a0d)!
Installing dependencies from Pipfile.lock (c24a0d)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell

```

```bash
❯ pipenv lock -r
urllib3==1.22
```

```bash
❯ python -m pipenv.help | pbcopy
Traceback (most recent call last):
  File "/Users/tim/.pyenv/versions/2.7.14/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/tim/.pyenv/versions/2.7.14/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/tim/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pipenv/help.py", line 88, in <module>
    main()
  File "/Users/tim/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pipenv/help.py", line 51, in main
    print(u'Pipenv–specific environment variables:')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-8: ordinal not in range(128)

```

```
Pipenv version: `'11.1.9'`
()
Pipenv location: `'/Users/tim/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pipenv'`
()
Python location: `'/Users/tim/.pyenv/versions/2.7.14/bin/python'`
()
Other Python installations in `PATH`:
()
  - `2.7`: `/Users/tim/.pyenv/versions/2.7.14/bin/python2.7`
  - `2.7`: `/Users/tim/.pyenv/versions/2.7.14/bin/python2.7`
  - `2.7`: `/Users/tim/.pyenv/shims/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/Users/tim/.pyenv/shims/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`
()
  - `2.7.14`: `/Users/tim/.pyenv/versions/2.7.14/bin/python`
  - `2.7.14`: `/Users/tim/.pyenv/shims/python`
  - `3.6.4`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.14`: `/Users/tim/.pyenv/versions/2.7.14/bin/python2`
  - `2.7.14`: `/Users/tim/.pyenv/shims/python2`
  - `None`: `/Users/tim/.pyenv/shims/python3`
  - `3.6.4`: `/usr/local/bin/python3`
()
PEP 508 Information:
()
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.4.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64',
 'python_full_version': '2.7.14',
 'python_version': '2.7',
 'sys_platform': 'darwin'}
()
System environment variables:
()
  - `LESS`
  - `LC_CTYPE`
  - `TERM_PROGRAM_VERSION`
  - `PYENV_DIR`
  - `LOGNAME`
  - `USER`
  - `HOME`
  - `PATH`
  - `TERM_PROGRAM`
  - `LANG`
  - `LESS_TERMCAP_se`
  - `TERM`
  - `SHELL`
  - `COLORFGBG`
  - `PYENV_SHELL`
  - `SHLVL`
  - `LESS_TERMCAP_me`
  - `LESS_TERMCAP_md`
  - `SECURITYSESSIONID`
  - `LESS_TERMCAP_mb`
  - `XPC_FLAGS`
  - `PYENV_VERSION`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `EDITOR`
  - `GREP_COLOR`
  - `ITERM_SESSION_ID`
  - `TERM_SESSION_ID`
  - `XPC_SERVICE_NAME`
  - `GREP_COLORS`
  - `SSH_AUTH_SOCK`
  - `VISUAL`
  - `Apple_PubSub_Socket_Render`
  - `ITERM_PROFILE`
  - `LC_ALL`
  - `PIP_PYTHON_PATH`
  - `TMPDIR`
  - `BROWSER`
  - `LESS_TERMCAP_ue`
  - `LSCOLORS`
  - `PROMPT_EOL_MARK`
  - `PYENV_HOOK_PATH`
  - `PYENV_ROOT`
  - `__CF_USER_TEXT_ENCODING`
  - `PWD`
  - `LESS_TERMCAP_us`
  - `COLORTERM`
  - `LESS_TERMCAP_so`
  - `LS_COLORS`
  - `PAGER`
  - `COMMAND_MODE`
()

```

```
> cat Pipfile
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[dev-packages]



[packages]

"urllib3" = {extras = ["secure"]}


[requires]

python_version = "2.7"
```

**Comment by kennethreitz** [comment]
oh thanks, i'll fix help ASAP

**Comment by kennethreitz** [comment]
11.1.10 released, which should fix the 2.7 bug. want to try again?

**Comment by kennethreitz** [comment]
Hmm, it appears to be working on my machine.

**Comment by kennethreitz** [comment]
`$ cat Pipfile.lock`

**Comment by Azd325** [comment]
The dashes still raise an issue. I swapped then to a normal `-` and after it help works
```
❯ python -m pipenv.help | pbcopy
Traceback (most recent call last):
  File "/Users/tim/.pyenv/versions/2.7.14/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/tim/.pyenv/versions/2.7.14/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/tim/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pipenv/help.py", line 89, in <module>
    main()
  File "/Users/tim/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pipenv/help.py", line 52, in main
    print(u'Pipenv–specific environment variables:')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 6: ordinal not in range(128)

~/test
❯ python -m pipenv.help | pbcopy
Traceback (most recent call last):
  File "/Users/tim/.pyenv/versions/2.7.14/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/tim/.pyenv/versions/2.7.14/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/tim/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pipenv/help.py", line 89, in <module>
    main()
  File "/Users/tim/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pipenv/help.py", line 59, in main
    print(u'Debug–specific environment variables:')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 5: ordinal not in range(128)

```

Pipenv version: `'11.1.11'`

Pipenv location: `'/Users/tim/.pyenv/versions/2.7.14/lib/python2.7/site-packages/pipenv'`

Python location: `'/Users/tim/.pyenv/versions/2.7.14/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/Users/tim/.pyenv/versions/2.7.14/bin/python2.7`
  - `2.7`: `/Users/tim/.pyenv/versions/2.7.14/bin/python2.7`
  - `2.7`: `/Users/tim/.pyenv/shims/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/Users/tim/.pyenv/shims/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `2.7.14`: `/Users/tim/.pyenv/versions/2.7.14/bin/python`
  - `2.7.14`: `/Users/tim/.pyenv/shims/python`
  - `3.6.4`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.14`: `/Users/tim/.pyenv/versions/2.7.14/bin/python2`
  - `2.7.14`: `/Users/tim/.pyenv/shims/python2`
  - `None`: `/Users/tim/.pyenv/shims/python3`
  - `3.6.4`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.4.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64',
 'python_full_version': '2.7.14',
 'python_version': '2.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `LESS`
  - `LC_CTYPE`
  - `TERM_PROGRAM_VERSION`
  - `PYENV_DIR`
  - `LOGNAME`
  - `USER`
  - `HOME`
  - `PATH`
  - `TERM_PROGRAM`
  - `LANG`
  - `LESS_TERMCAP_se`
  - `TERM`
  - `SHELL`
  - `COLORFGBG`
  - `PYENV_SHELL`
  - `SHLVL`
  - `LESS_TERMCAP_me`
  - `LESS_TERMCAP_md`
  - `SECURITYSESSIONID`
  - `LESS_TERMCAP_mb`
  - `XPC_FLAGS`
  - `PYENV_VERSION`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `EDITOR`
  - `GREP_COLOR`
  - `ITERM_SESSION_ID`
  - `TERM_SESSION_ID`
  - `XPC_SERVICE_NAME`
  - `GREP_COLORS`
  - `SSH_AUTH_SOCK`
  - `VISUAL`
  - `Apple_PubSub_Socket_Render`
  - `ITERM_PROFILE`
  - `LC_ALL`
  - `PIP_PYTHON_PATH`
  - `TMPDIR`
  - `BROWSER`
  - `LESS_TERMCAP_ue`
  - `LSCOLORS`
  - `PROMPT_EOL_MARK`
  - `PYENV_HOOK_PATH`
  - `PYENV_ROOT`
  - `__CF_USER_TEXT_ENCODING`
  - `PWD`
  - `LESS_TERMCAP_us`
  - `COLORTERM`
  - `LESS_TERMCAP_so`
  - `LS_COLORS`
  - `PAGER`
  - `COMMAND_MODE`

Pipenv-specific environment variables:


Debug-specific environment variables:

  - `PATH`: `/Users/tim/.pyenv/versions/2.7.14/bin:/usr/local/Cellar/pyenv/1.2.2/libexec:/usr/local/opt/gnu-sed/libexec/gnubin:/Users/tim/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Applications/Postgres.app/Contents/Versions/latest/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `nano`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/tim/test`


---------------------------

Contents of `Pipfile` ('/Users/tim/test/Pipfile'):

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[dev-packages]



[packages]

"urllib3" = {extras = ["secure"]}


[requires]

python_version = "2.7"

```


Contents of `Pipfile.lock` ('/Users/tim/test/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "0b0840075070eca5e70a7e28676798f0badb1d836865729e7682db68a9c24a0d"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "2.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "urllib3": {
            "hashes": [
                "sha256:06330f386d6e4b195fbfc736b297f58c5a892e4440e54d294d7004e3a9bbea1b",
                "sha256:cc44da8e1145637334317feebd728bd869a35285b93cbb4cca2577da7e62db4f"
            ],
            "version": "==1.22"
        }
    },
    "develop": {}
}

```

**Comment by kennethreitz** [comment]
this is very strange — i might have to look at urllib3's setup.py to see what's going on

**Comment by kennethreitz** [comment]
```
requires-dist = 
	pyOpenSSL>=0.14; python_version<="2.7" and extra == 'secure'
	cryptography>=1.3.4; python_version<="2.7" and extra == 'secure'
	idna>=2.0.0; python_version<="2.7" and extra == 'secure'
	certifi; extra == 'secure'
	ipaddress; python_version<="2.7" and extra == 'secure'
	PySocks>=1.5.6,<2.0,!=1.5.7; extra == 'socks'
```

**Comment by kennethreitz** [comment]
we might have a bug here

**Comment by Azd325** [comment]
If I do it on python 3 it will add append the requirements to `Pipfile.lock` file.



Pipenv version: `'11.1.11'`

Pipenv location: `'/Users/tim/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv'`

Python location: `'/Users/tim/.pyenv/versions/3.6.4/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/Users/tim/.pyenv/shims/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/Users/tim/.pyenv/versions/3.6.4/bin/python3.6m`
  - `3.6`: `/Users/tim/.pyenv/versions/3.6.4/bin/python3.6`
  - `3.6`: `/Users/tim/.pyenv/shims/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `3.6.4`: `/Users/tim/.pyenv/versions/3.6.4/bin/python`
  - `3.6.4`: `/Users/tim/.pyenv/shims/python`
  - `3.6.4`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `None`: `/Users/tim/.pyenv/shims/python2`
  - `3.6.4`: `/Users/tim/.pyenv/versions/3.6.4/bin/python3`
  - `3.6.4`: `/Users/tim/.pyenv/shims/python3`
  - `3.6.4`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.4.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST '
                     '2017; root:xnu-4570.41.2~1/RELEASE_X86_64',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `GREP_COLOR`
  - `LESS_TERMCAP_mb`
  - `TERM_PROGRAM`
  - `LESS_TERMCAP_md`
  - `PYENV_ROOT`
  - `LESS_TERMCAP_me`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `LESS_TERMCAP_ue`
  - `TERM_SESSION_ID`
  - `PYENV_VERSION`
  - `LC_ALL`
  - `USER`
  - `LS_COLORS`
  - `GREP_COLORS`
  - `COMMAND_MODE`
  - `SSH_AUTH_SOCK`
  - `PYENV_DIR`
  - `__CF_USER_TEXT_ENCODING`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `PAGER`
  - `LSCOLORS`
  - `LESS_TERMCAP_us`
  - `PATH`
  - `PWD`
  - `EDITOR`
  - `LANG`
  - `ITERM_PROFILE`
  - `PYENV_HOOK_PATH`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `PYENV_SHELL`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `VISUAL`
  - `LESS_TERMCAP_so`
  - `LC_CTYPE`
  - `BROWSER`
  - `PROMPT_EOL_MARK`
  - `SECURITYSESSIONID`
  - `LESS_TERMCAP_se`
  - `COLORTERM`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:


Debug–specific environment variables:

  - `PATH`: `/Users/tim/.pyenv/versions/3.6.4/bin:/usr/local/Cellar/pyenv/1.2.2/libexec:/usr/local/opt/gnu-sed/libexec/gnubin:/Users/tim/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Applications/Postgres.app/Contents/Versions/latest/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `nano`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/tim`


---------------------------

Contents of `Pipfile` ('/Users/tim/Pipfile'):

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

"urllib3" = {extras = ["secure"]}


[dev-packages]


```


Contents of `Pipfile.lock` ('/Users/tim/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "e51ebb8b58c7b8d7386f902832abd7034a457cc73f4858f402502de761ce448c"
        },
        "host-environment-markers": {
            "implementation_name": "cpython",
            "implementation_version": "0",
            "os_name": "posix",
            "platform_machine": "x86_64",
            "platform_python_implementation": "CPython",
            "platform_release": "17.4.0",
            "platform_system": "Darwin",
            "platform_version": "Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64",
            "python_full_version": "2.7.14",
            "python_version": "2.7",
            "sys_platform": "darwin"
        },
        "pipfile-spec": 6,
        "requires": {},
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "certifi": {
            "hashes": [
                "sha256:14131608ad2fd56836d33a71ee60fa1c82bc9d2c8d98b7bdbc631fe1b3cd1296",
                "sha256:edbc3f203427eef571f79a7692bb160a2b0f7ccaa31953e99bd17e307cf63f7d"
            ],
            "version": "==2018.1.18"
        },
        "urllib3": {
            "hashes": [
                "sha256:06330f386d6e4b195fbfc736b297f58c5a892e4440e54d294d7004e3a9bbea1b",
                "sha256:cc44da8e1145637334317feebd728bd869a35285b93cbb4cca2577da7e62db4f"
            ],
            "version": "==1.22"
        }
    },
    "develop": {}
}

```

**Comment by kennethreitz** [comment]
try again with latest :)

**Comment by Azd325** [comment]
Still the same result with pipenv, version 11.2.2, on python2

**Comment by techalchemy** [comment]
@Azd325 reinstall pipenv with python 3 btw, you will have a much nicer time

**Comment by Azd325** [comment]
python3 will be possible first in some month but I'm on a good way.

**Comment by techalchemy** [comment]
pipenv works better with python 3 even if you use python 2 primarily

**Comment by Azd325** [comment]
May but I still stay or the problem that the current requirements, what I need, don't get resolved.  ;)
