### ISSUE TITLE
Cannot install loremipsum

### ISSUE THREAD

**Issue by dbellavista** [pypa/pipenv#1654]
I cannot generate the `Pipfile.lock` with loremipsum (`pip install` works fine)

Pipenv version: `'11.2.2'`

Pipenv location: `'/usr/local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`

  - `3.6.4`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `3.6.4`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.4.0',
 'platform_system': 'Darwin',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `EDITOR`
  - `HOME`
  - `LANG`
  - `LC_ALL`
  - `LC_CTYPE`
  - `PATH`
  - `PWD`
  - `SHELL`
  - `USER`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/me`

---------------------------

Contents of `Pipfile` ('/Users/me/Pipfile'):

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

loremipsum = "*"


[dev-packages]



[requires]

python_version = "3.6"

```
------------

##### Expected result
`Pipfile.lock` to be generated

##### Actual result
```
$ pipenv install loremipsum
Creating a virtualenv for this project…
⠋Using base prefix '/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/me/.local/share/virtualenvs/me-fCiNQwGw/bin/python3.6
Also creating executable in /Users/me/.local/share/virtualenvs/me-fCiNQwGw/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/me/.local/share/virtualenvs/me-fCiNQwGw
Creating a Pipfile for this project…
Installing loremipsum…
Collecting loremipsum
Installing collected packages: loremipsum
Successfully installed loremipsum-1.0.5

Adding loremipsum to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
olve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/resolver.py", line 297, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python3.6/site-packages/pipenv/../pipenv/patched/piptools/repositories/pypi.py", line 182, in get_dependencies
    'Please run "$ pipenv-resolver {0!r} --verbose" to debug.'.format(str(ireq.req))
ValueError: Your dependencies could not be resolved.
Please run "$ pipenv-resolver 'loremipsum==1.0.5' --verbose" to debug.
```

```
$ pipenv-resolver 'loremipsum==1.0.5' --verbose
Using pip: -i https://pypi.python.org/simple

                          ROUND 1                           
Current constraints:
  loremipsum==1.0.5

Finding the best candidates:
  found candidate loremipsum==1.0.5 (constraint was ==1.0.5)

Finding secondary dependencies:
  loremipsum==1.0.5 not in cache, need to check index
Traceback (most recent call last):
  File "/usr/local/bin/pipenv-resolver", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pipenv/resolver.py", line 54, in main
    results = resolve(packages, pre=do_pre, sources=project.sources, verbose=is_verbose, clear=do_clear)
  File "/usr/local/lib/python3.6/site-packages/pipenv/resolver.py", line 52, in resolve
    return pipenv.utils.resolve_deps(packages, which, project=project, pre=pre, sources=sources, clear=clear, verbose=verbose)
  File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 395, in resolve_deps
    resolved_tree, resolver = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 328, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 297, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 182, in get_dependencies
    'Please run "$ pipenv-resolver {0!r} --verbose" to debug.'.format(str(ireq.req))
ValueError: Your dependencies could not be resolved.
Please run "$ pipenv-resolver 'loremipsum==1.0.5' --verbose" to debug.
```

##### Steps to replicate

`pipenv install loremipsum`

**Comment by kennethreitz** [comment]
```
$ pipenv-resolver 'loremipsum==1.0.5' --verbose

Using pip: -i https://pypi.python.org/simple

                          ROUND 1
Current constraints:
  loremipsum==1.0.5

Finding the best candidates:
  found candidate loremipsum==1.0.5 (constraint was ==1.0.5)

Finding secondary dependencies:
  loremipsum==1.0.5 not in cache, need to check index
INFO:pip._vendor.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): pypi.org
INFO:pip.req.req_set:Collecting loremipsum==1.0.5
INFO:pip._vendor.requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): pypi.python.org
INFO:pip.download:Downloading loremipsum-1.0.5.tar.gz
INFO:pip.download:Saved /Volumes/KR/Library/Caches/pipenv/pkgs/loremipsum-1.0.5.tar.gz
  loremipsum==1.0.5         requires -
------------------------------------------------------------
Result of round 1: stable, done
RESULTS:
[{"name": "loremipsum", "version": "1.0.5", "hashes": ["sha256:30481f59ef323fc5566efe2271f63e85ea5bc358a8f25274927232388a1557ee", "sha256:b849c69305c3f52badfe25ecc0495b991769d96cafdfd99014d17f50ee523af5", "sha256:a38672c145c0e0790cb40403d46bee695e5e9a0350f0643199a012a18f65449a"]}]
```

**Comment by kennethreitz** [comment]
What output do you get when you run that command?

**Comment by kennethreitz** [comment]
closing until more information is provided.

Also, PyPI is in maintinence mode right now, which affects resolution services for Pipenv (this will be fixed soon, on their end).

**Comment by kennethreitz** [comment]
Resolved: https://status.python.org/incidents/jcg42tnvbfmm

**Comment by dbellavista** [comment]
Ok thank you! (BTW the output `$ pipenv-resolver 'loremipsum==1.0.5' --verbose` was already present in the issue description).
