### ISSUE TITLE
ImportError: cannot import name 'appdirs' (with Debian system Python)

### ISSUE THREAD

**Issue by inducer** [pypa/pipenv#1675]
I have a Python 3.6 virtualenv based on my Debian testing/unstable system Python, and within that virtualenv I ran `pip install pipenv` to install pipenv.

Then, running `pipenv install` in an empty directory gives me:

```
Traceback (most recent call last):
  File "/home/andreas/src/env-3.6/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/andreas/src/env-3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/andreas/src/env-3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/andreas/src/env-3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/home/andreas/src/env-3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andreas/src/env-3.6/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/andreas/src/env-3.6/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/andreas/src/env-3.6/lib/python3.6/site-packages/pipenv/cli.py", line 62, in cli
    from . import core
  File "/home/andreas/src/env-3.6/lib/python3.6/site-packages/pipenv/core.py", line 33, in <module>
    from .project import Project
  File "/home/andreas/src/env-3.6/lib/python3.6/site-packages/pipenv/project.py", line 16, in <module>
    from .utils import (
  File "/home/andreas/src/env-3.6/lib/python3.6/site-packages/pipenv/utils.py", line 45, in <module>
    from pipenv.patched.piptools.resolver import Resolver
  File "/home/andreas/src/env-3.6/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 10, in <module>
    from notpip.req import InstallRequirement
  File "/home/andreas/src/env-3.6/lib/python3.6/site-packages/pipenv/patched/notpip/req/__init__.py", line 3, in <module>
    from .req_install import InstallRequirement
  File "/home/andreas/src/env-3.6/lib/python3.6/site-packages/pipenv/patched/notpip/req/req_install.py", line 17, in <module>
    from notpip._vendor import pkg_resources, six
  File "/home/andreas/src/env-3.6/lib/python3.6/site-packages/pipenv/patched/notpip/_vendor/pkg_resources/__init__.py", line 70, in <module>
    from pip._vendor import appdirs
ImportError: cannot import name 'appdirs'
```

`python -m pipenv.help` dies with the same trackeback.

**Comment by kennethreitz** [comment]
looks like you're using an incompatible pip

**Comment by inducer** [comment]
I'm on pip 9.0.1 as far as I can tell.

**Comment by iScrE4m** [comment]
Same error here, also debian-based system, but py 3.5

```
Requirement already satisfied: pip>=9.0.1 in /usr/lib/python3/dist-packages (from pipenv)
.
.
.
Successfully installed pipenv-11.5.2 setuptools-38.5.2 virtualenv-15.1.0 virtualenv-clone-0.3.0
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 62, in cli
    from . import core
  File "/usr/local/lib/python3.5/dist-packages/pipenv/core.py", line 33, in <module>
    from .project import Project
  File "/usr/local/lib/python3.5/dist-packages/pipenv/project.py", line 16, in <module>
    from .utils import (
  File "/usr/local/lib/python3.5/dist-packages/pipenv/utils.py", line 45, in <module>
    from pipenv.patched.piptools.resolver import Resolver
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/piptools/resolver.py", line 10, in <module>
    from notpip.req import InstallRequirement
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/notpip/req/__init__.py", line 3, in <module>
    from .req_install import InstallRequirement
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/notpip/req/req_install.py", line 17, in <module>
    from notpip._vendor import pkg_resources, six
  File "/usr/local/lib/python3.5/dist-packages/pipenv/patched/notpip/_vendor/pkg_resources/__init__.py", line 70, in <module>
    from pip._vendor import appdirs
ImportError: cannot import name 'appdirs'
```

**Comment by kennethreitz** [comment]
the pip you have installed (wherever pipenv is installed) appears to not be 9.0.1.

**Comment by iScrE4m** [comment]
That's why I included the requirement already satisfied line. The source is in my case debian stretch's main repository, `python3-pip=9.0.1-2`. Is that not `9.0.1` then?

**Comment by kennethreitz** [comment]
ah, they modify pip.

**Comment by kennethreitz** [comment]
they remove _vendor

**Comment by iScrE4m** [comment]
Did some digging, it appears that debian does not include ANY packages in `_vendor`.

```
/usr/lib/python3/dist-packages/pip/_vendor$ ls -la
total 20
drwxr-xr-x  3 root root 4096 Mar 12 14:08 .
drwxr-xr-x 11 root root 4096 Mar 12 14:08 ..
-rw-r--r--  1 root root 4804 Jan 11  2017 __init__.py
drwxr-xr-x  2 root root 4096 Mar 12 14:08 __pycache__
```

And after reading pip's policy about _vendor, I can see why. Since appdirs is a dependency, can it be imported directly? Even debian would be happy I think :) 

```
/usr/lib/python3/dist-packages/pip/_vendor$ apt-cache search python3-appdir
python3-appdirs - determining appropriate platform-specific directories (Python 3)
```

**Comment by kennethreitz** [comment]
We're heavily relying on pip's standard distribution. You should use that instead of system pip, imo.

**Comment by kennethreitz** [comment]
e.g. install pipenv into a virtualenv if you must

**Comment by iScrE4m** [comment]
Can you somehow check for vendor during pipenv's installation and force reinstall of pip if they're not found? It's very unintuitive.

**Comment by kennethreitz** [comment]
this is asking for a lot — please just use a standard environment. we can only do so much.

**Comment by kennethreitz** [comment]
P.S. we have a ppa we distribute, so we'll work to make that experience as smooth as possible.

**Comment by kennethreitz** [comment]
So recommended action here: Install Pipenv within a virtualenv.

**Comment by kennethreitz** [comment]
This will "go away" in the future, with some changes we have planned (for the rollout of pip10).

**Comment by kennethreitz** [comment]
@techalchemy it's already solved.

**Comment by inducer** [comment]
> e.g. install pipenv into a virtualenv if you must

That's what I did (see my report above), and I still encountered the issue.

FWIW, this still fails in the same way even if `appdirs` installed (e.g. into the same virtualenv).

> it's already solved.

Sorry if I'm being dense, but I'm not sure I understand. The problem certainly persists for me, with no workaround that I'm aware of.

**Comment by kennethreitz** [comment]
In 11.6.0?

**Comment by inducer** [comment]
Aw shoot, sorry. I was unaware that a new version of pipenv had been released in the meantime. Yes, I can confirm that I am no longer seeing this issue.

**Comment by kennethreitz** [comment]
sorry, i forgot to update this issue 😆
