### ISSUE TITLE
Windows installation on python 3.6.2 tries to use 2.x version of concurrent.futures?

### ISSUE THREAD

**Issue by kimvais** [pypa/pipenv#1686]
##### Expected result

Working pipenv installation

##### Actual result
```python_tb
Successfully installed pipenv-11.6.0
PS C:\Users\kimvais\PycharmProjects\dbv2> pipenv shell
Traceback (most recent call last):
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kimvais\AppData\Local\Programs\Python\Python36\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\site-packages\pipenv\cli.py", line 259, in shell
    from . import core
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\site-packages\pipenv\core.py", line 24, in <module>
    import pipdeptree
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\pipdeptree.py", line 16, in <module>
    import pip9
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\pip9\__init__.py", line 28, in <module>
    from pip9.vcs import git, mercurial, subversion, bazaar  # noqa
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\pip9\vcs\subversion.py", line 9, in <module>
    from pip9.index import Link
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\pip9\index.py", line 31, in <module>
    from pip9.wheel import Wheel, wheel_ext
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\pip9\wheel.py", line 6, in <module>
    import compileall
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\compileall.py", line 20, in <module>
    from concurrent.futures import ProcessPoolExecutor
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\site-packages\pipenv\..\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "c:\users\kimvais\appdata\local\programs\python\python36\lib\site-packages\pipenv\..\concurrent\futures\_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```
##### Steps to replicate
In windows 10 powershell with python 3.6.2 installed do:

pip install pipenv
pipenv shell

**Comment by kennethreitz** [comment]
try latest version :)

**Comment by zyv** [comment]
@kennethreitz still errors out for me:

```
$ pipenv --version
pipenv, version 11.7.2
```

This is (system global) pipenv installed under Python 2.7, running inside of local Python 3.6 venv.

```
$ pipenv update --dry-run
 File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/vendor/pip9/index.py", line 31, in <module>
    from pip9.wheel import Wheel, wheel_ext
  File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/vendor/pip9/wheel.py", line 6, in <module>
    import compileall
  File "/home/zaytsev/opt/ActivePython-3.6.0.3600/lib/python3.6/compileall.py", line 20, in <module>
    from concurrent.futures import ProcessPoolExecutor
  File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/../concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/../concurrent/futures/_base.py", line 414
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

**Comment by kennethreitz** [comment]
We aren't shipping concurrent.futures anymore.

**Comment by kennethreitz** [comment]
i wonder if the file somehow didn't get uninstalled when you upgraded

**Comment by zyv** [comment]
Duplicates:

* #1603
* #1589
* #1553

D'uh.

**Comment by zyv** [comment]
Okay, I will delete the package manually, reinstall and report back.

**Comment by zyv** [comment]
Hmmm, did

```
rm -r /home/zaytsev/.local/lib/python2.7/site-packages/pipenv*
pip install -U --user pipenv
```

Still same error message. However, note, that apparently it is *not* referencing pipenv-bundled `concurrent.futures` as you suggested. It is referencing global Python 2.7 backport, which was pulled in by Ansible:

`site-packages/pipenv/../pipenv/../concurrent`

I'm not quite sure why it runs under Python 3.6 though?! I checked the shebang at the top of `pipenv` script and it is set to `!/usr/bin/python`, so `pipenv` is correctly executed under Python 2.7.

**Comment by kennethreitz** [comment]
sounds like you have a messed up python installation :)

**Comment by kennethreitz** [comment]
we might have to do something about that

**Comment by zyv** [comment]
Nope, I have totally normal functioning Python installation(s).

* System default installation is Python 2.7 (Debian Jessie)
* User-installed Python 2.7 packages in `$HOME/.local/lib/python2.7/site-packages`
* Scripts / programs installed by Python 2.7 into `$HOME/.local/bin` are on `$PATH`
* Installed `pipenv` as a user program to manage Python 2.7 and Python 3.6 virtualenvs
* User-installed Python 3.6 from ActiveState in `$HOME/opt` (not on `$PATH`!)
* This installation is used to create Python 3.6 virtualenvs, including the one in question using `--python` flag of `pipenv`

If `pipenv` is executed inside Python 3.6 virtualenvs, which happens naturally, because PyCharm terminals enter corresponding virtualenvs automatically, the error I referenced appears, in spite of shebang of `pipenv` being correctly set.

Apparently, you are doing some questionable background process spawning dark magic, which leads to wrong `PYTHONPATH` being set / wrong interpreter used, this is my only theory.

However, please note that my setup is not broken, but working, and judging from other tickets / user reports, quite a common one.

**Comment by kennethreitz** [comment]
I think this is out of scope.

**Comment by kennethreitz** [comment]
Or, we need to remove `concurrent.futures` from `sys.modules` at import time, if it's found, and the python interpreter is <= 3.0.

**Comment by techalchemy** [comment]
Your setup _is_ broken if your pipenv still spawns background processes. This is quite literally not in our code anywhere. Look in the repository. 

You just described a highly convoluted python install with a large number of separate interpreters. Call each of them separately and uninstall pipenv. `/path/to/python -m pip uninstall pipenv` and then install it in one place.

**Comment by techalchemy** [comment]
Just because your setup runs python code doesn’t mean things about it aren’t broken btw

**Comment by zyv** [comment]
@techalchemy no need to be defensive, I came in peace and we don't need to be shooting at each other just because my Python environment appears bewildering to you. As you can see, it's much more common that one might think.

I explicitly mentioned that background process spawning is only my theory as to why `PYTHONPATH` is messed up. If you say you are not spawning anything, there is no reason for me to doubt your words. I can totally accept that my speculation is wrong and I apologize for it, but then I have no other ideas as to what could be the true cause of the problem.

**Comment by kennethreitz** [comment]
i know what the problem is

**Comment by kennethreitz** [comment]
try 11.7.3.

**Comment by zyv** [comment]
Hmmm, no dice :(

```
(moneymeets-deployment-N9wt4NSf) zaytsev@work:~/src/moneymeets-deployment$ pipenv --version
pipenv, version 11.7.3
(moneymeets-deployment-N9wt4NSf) zaytsev@work:~/src/moneymeets-deployment$ pipenv update --dry-run
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
 File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/vendor/pip9/index.py", line 31, in <module>
    from pip9.wheel import Wheel, wheel_ext
  File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/vendor/pip9/wheel.py", line 6, in <module>
    import compileall
  File "/home/zaytsev/opt/ActivePython-3.6.0.3600/lib/python3.6/compileall.py", line 20, in <module>
    from concurrent.futures import ProcessPoolExecutor
  File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/../concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/../concurrent/futures/_base.py", line 414
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

**Comment by kennethreitz** [comment]
there's no reason this should be happening.

**Comment by kennethreitz** [comment]
please just uninstall pipenv entirely everywhere

**Comment by kennethreitz** [comment]
you clealry have an old installation laying around somewhere

**Comment by kennethreitz** [comment]
try setting this environment variable

`PYTHONDONTWRITEBYTECODE=1`

**Comment by zyv** [comment]
Are you able to reproduce the problem, actually? If not, then maybe it will help if I make you a clean Docker image which illustrates the issue?

I have checked once again, but I have just one and only one `pipenv` on my system. It is the one installed using system default `python` interpreter (Python 2.7) in `$HOME/.local/lib/python2.7`. I have removed all files and reinstalled it again, but it doesn't help. The core of the issue seems to be working with Python 3 virtualenvs on the system with Python 2 as a default interpreter...

```
(moneymeets-deployment-N9wt4NSf) zaytsev@work:~/src/moneymeets-deployment$ PYTHONDONTWRITEBYTECODE=1 pipenv update --dry-run
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
 File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/vendor/pip9/index.py", line 31, in <module>
    from pip9.wheel import Wheel, wheel_ext
  File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/vendor/pip9/wheel.py", line 6, in <module>
    import compileall
  File "/home/zaytsev/opt/ActivePython-3.6.0.3600/lib/python3.6/compileall.py", line 20, in <module>
    from concurrent.futures import ProcessPoolExecutor
  File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/../concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/../concurrent/futures/_base.py", line 414
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

Interestingly, the error appears not only in PyCharm, when running inside virtualenv, as I originally supposed, but also when `VIRTUAL_ENV` variable is not set.

```
zaytsev@work:~/src/moneymeets-deployment$ pipenv update --dry-run
 File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/vendor/pip9/index.py", line 31, in <module>
    from pip9.wheel import Wheel, wheel_ext
  File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/vendor/pip9/wheel.py", line 6, in <module>
    import compileall
  File "/home/zaytsev/opt/ActivePython-3.6.0.3600/lib/python3.6/compileall.py", line 20, in <module>
    from concurrent.futures import ProcessPoolExecutor
  File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/../concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/zaytsev/.local/lib/python2.7/site-packages/pipenv/../pipenv/../concurrent/futures/_base.py", line 414
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

If I install pipenv inside the virtualenv, and run it from inside virtualenv, then the problem goes away.

**Comment by kennethreitz** [comment]
if you can make the problem go away, please just do that.

**Comment by SUlbrichA** [comment]
I encounter exactly the same problem on Ubuntu 16.04. 
Pipenv installed locally (--user) for 2.7, version 11.7.3 
same error message when creating a venv for 3.5 or 3.6

**Comment by SUlbrichA** [comment]
Update: I removed `$HOME/.local` entirely and now it seems to work

**Comment by zyv** [comment]
@SUlbrichA as I mentioned, there is a workaround, which doesn't require removing the `pipenv` installation:

You can install `pipenv` in your Python 3 virtualenv, and run it from inside Python 3 virtualenv, this will work. Very unsatisfying, of course, but I think much better than having to remove Python 2 version altogether.

**Comment by kennethreitz** [comment]
there should only be one version of pipenv installed!

**Comment by kennethreitz** [comment]
Locking this conversation so no more misinformation can be spread.

Please open a new issue if you continue to have this problem.
