### ISSUE TITLE
Trouble after `pipenv install` (11.6.3)

### ISSUE THREAD

**Issue by koddr** [pypa/pipenv#1710]
I have trouble after `$ pipenv install` (11.6.3):

```bash
/pipenv/vendor/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/../pipenv/vendor/requests/packages/urllib3/connectionpool.py", line 355, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/../pipenv/vendor/requests/packages/urllib3/connectionpool.py", line 315, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/resolver.py", line 66, in <module>
    main()
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/resolver.py", line 54, in main
    results = resolve(packages, pre=do_pre, sources=project.sources, verbose=is_verbose, clear=do_clear)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/resolver.py", line 52, in resolve
    return pipenv.utils.resolve_deps(packages, which, project=project, pre=pre, sources=sources, clear=clear, verbose=verbose)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/../pipenv/utils.py", line 429, in resolve_deps
    r = requests.get('https://pypi.org/pypi/{0}/json'.format(name), timeout=10)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/../pipenv/vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/../pipenv/vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/../pipenv/vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/../pipenv/vendor/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=10)
```

How to solve this?

**Comment by kennethreitz** [comment]
looks like a problem with your internet connection (or pypi). Can't do anything about that!
