### ISSUE TITLE
[11.6.3] Trouble with pipenv --update

### ISSUE THREAD

**Issue by koddr** [pypa/pipenv#1719]
When I try to update pipenv with `pipenv --update`:

```bash
$ pipenv --update

Courtesy Notice: Pipenv 11.6.8 is now available. Automatically upgrading!
Traceback (most recent call last):
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/cli.py", line 71, in cli
    core.ensure_latest_self()
  File "/Users/vikkyshostak/.local/share/virtualenvs/django_visatorus-fiOUaYzG/lib/python3.6/site-packages/pipenv/core.py", line 171, in ensure_latest_self
    sys.modules['pip'].main(args)
KeyError: 'pip'
```

**Comment by kennethreitz** [comment]
we may be removing this

**Comment by techalchemy** [comment]
@koddr / @kennethreitz the bug likely only happens when pipenv is installed inside a virtualenv, but yeah we should either remove or fix

**Comment by kennethreitz** [comment]
I don't care when or why it's happening, it's happening :)

**Comment by kennethreitz** [comment]
this has been removed from master
