### ISSUE TITLE
Cannot install whl package using pipenv install [package_name].whl

### ISSUE THREAD

**Issue by purEnergy** [pypa/pipenv#1756]
I'm attempting to install specific versions of packages in a pipenv and have different versions of those same packages on my host environment from local whl files. When I attempt to do any thing like run "pipenv shell" or "pipenv install [package_name].whl", I get an error stating that the encryption package needs to be at least version 2.1.4. The error is below. Does pipenv require this version specifically? If so, why did it not get automatically updated as a dependency?

Using the following versions:
Python 2.7.13
Pip 9.0.1
pipenv 11.8.0
cryptography 2.1.1

The error I get when executing "pipenv shell":

Traceback (most recent call last):
File "C:\Python27\Scripts\pipenv-script.py", line 6, in 
from pkg_resources import load_entry_point
File "c:\python27\lib\site-packages\pkg_resources_init_.py", line 3142, in 
@call_aside
File "c:\python27\lib\site-packages\pkg_resources_init.py", line 3126, in call_aside
f(*args, **kwargs)
File "c:\python27\lib\site-packages\pkg_resources_init.py", line 3155, in _initialize_master_working_set
working_set = WorkingSet.build_master()
File "c:\python27\lib\site-packages\pkg_resources_init.py", line 666, in _build_master
return cls.build_from_requirements(requires)
File "c:\python27\lib\site-packages\pkg_resources_init.py", line 679, in build_from_requirements
dists = ws.resolve(reqs, Environment())
File "c:\python27\lib\site-packages\pkg_resources_init.py", line 872, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 2.1.1 (c:\python27\lib\site-packages), Requirement.parse('cryptog
raphy>=2.1.4'), set(['pyOpenSSL']))

**Comment by kennethreitz** [comment]
`$ pip install --upgrade pipenv` should patch you right up.

**Comment by purEnergy** [comment]
All is well now. Thanks. Was it just a bad install? It didn't upgrade to a newer version.
