### ISSUE TITLE
Errors thrown importing requirements.txt 

### ISSUE THREAD

**Issue by pbannister** [pypa/pipenv#1799]
Attempting to create a new pipenv context for an existing project fails. Seems the syntax in **requirements.txt** is not fully handled by pipenv.

FYI (note this is MacOS with Python installed via **brew**):
```
$ python -m pipenv.help
/usr/local/opt/python@2/bin/python2.7: No module named pipenv
$ which python
/usr/local/bin/python
```
------------

##### Expected result

Either ingest the **requirements.txt** file, or report the file cannot be handled (in concise/clear form).

##### Actual result

Stack trace of thrown error(s). Fails to import **requirements.txt**.

##### Steps to replicate
```
git clone https://github.com/kliment/Printrun.git
cd Printrun
pipenv --two
```
This throws a rather noisy error:

```
$ pipenv --two
Virtualenv already exists!
Removing existing virtualenv…
Creating a virtualenv for this project…
Using /usr/local/bin/python2 (2.7.14) to create virtualenv…
⠋Running virtualenv with interpreter /usr/local/bin/python2
New python executable in /Users/preston/.local/share/virtualenvs/Printrun-uVIhZWEA/bin/python2.7
Also creating executable in /Users/preston/.local/share/virtualenvs/Printrun-uVIhZWEA/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/preston/.local/share/virtualenvs/Printrun-uVIhZWEA
requirements.txt found, instead of Pipfile! Converting…
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip9._vendor.pyparsing.ParseException: Expected stringEnd (at char 9), (line:1, col:10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip9._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'(>= 2.8,'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.8.3', 'console_scripts', 'pipenv')()
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/cli.py", line 235, in cli
    three=three, python=python, warn=True, site_packages=site_packages
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/core.py", line 635, in ensure_project
    ensure_pipfile(validate=validate, skip_requirements=skip_requirements)
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/core.py", line 268, in ensure_pipfile
    import_requirements()
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/core.py", line 204, in import_requirements
    reqs = [f for f in parse_requirements(r, session=pip9._vendor.requests)]
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/core.py", line 204, in <listcomp>
    reqs = [f for f in parse_requirements(r, session=pip9._vendor.requests)]
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/req/req_file.py", line 93, in parse_requirements
    for req in req_iter:
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/req/req_file.py", line 158, in process_line
    isolated=isolated, options=req_options, wheel_cache=wheel_cache
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/req/req_install.py", line 235, in from_line
    wheel_cache=wheel_cache, constraint=constraint)
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/req/req_install.py", line 91, in __init__
    "Invalid requirement: '%s'\n%s" % (req, add_msg))
pip9.exceptions.InstallationError: Invalid requirement: 'wxPython (>= 2.8, << 4.0)'
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip9._vendor.pyparsing.ParseException: Expected stringEnd (at char 9), (line:1, col:10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip9._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'(>= 2.8,'"
```

You might want the **requirements.txt**
```
python (>= 2.7, << 3)
pyreadline
pyserial (>= 2.6)
wxPython (>= 2.8, << 4.0)
numpy (>= 1.8.2)
pyglet (>= 1.1)
pycairo (>= 1.8.8)
cairosvg (>= 1.0.9, << 2)
psutil (>= 2.1)
dbus-python (>= 1.2.0)
pygobject (>= 3.14.0)
libxml2 (>= 2.9.1)
appdirs (>= 1.4.0)
```

The created **Pipfile** is not very interesting:
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "2.7"
```

Just for grins, tried importing **requirements.txt** again:
```
$ pipenv shell
Spawning environment shell (/bin/bash). Use 'exit' to leave.
bash-3.2$ . /Users/preston/.local/share/virtualenvs/Printrun-uVIhZWEA/bin/activate

(Printrun-uVIhZWEA) bash-3.2$ pipenv install -r requirements.txt 
Requirements file provided! Importing into Pipfile…
Unexpected syntax in /Users/preston/sources/Printrun/requirements.txt. Are you sure this is a requirements.txt style file?
Invalid requirement: 'wxPython (>= 2.8, << 4.0)'
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip9._vendor.pyparsing.ParseException: Expected stringEnd (at char 9), (line:1, col:10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/usr/local/Cellar/pipenv/11.8.3/libexec/lib/python3.6/site-packages/pipenv/vendor/pip9/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip9._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'(>= 2.8,'"
```

Seems the **requirements.txt** file has syntax not (yet?) handled by **pipenv**.

**Comment by uranusjr** [comment]
This is not a valid requirements.txt. You should create one with `pip freeze`, not `pip list`.

**Comment by uranusjr** [comment]
See https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format

**Comment by uranusjr** [comment]
@hinnerk Your error is completely different from this one, and is covered by #1791.
