### ISSUE TITLE
Pretty log messages cause UnicodeEncodeError in non-unicode locales

### ISSUE THREAD

**Issue by russss** [pypa/pipenv#1804]
Pipenv version: 11.8.3

When running Pipenv in a non-UTF8 environment, the unicode ellipses in the log messages generate a UnicodeEncodeError. Although this doesn't kill the process, it's very noisy.

<details><summary>Output</summary>

```
$ LANG=en_US pipenv update
Running $ pipenv lock then $ pipenv sync.
Locking [dev-packages] dependencies\u2026
Locking [packages] dependencies\u2026
Updated Pipfile.lock (0582a8)!
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 760, in update
    sequential=sequential,
  File "/usr/local/lib/python3.5/dist-packages/pipenv/core.py", line 2436, in do_sync
    requirements_dir=requirements_dir,
  File "/usr/local/lib/python3.5/dist-packages/pipenv/core.py", line 1368, in do_init
    requirements_dir=requirements_dir.name,
  File "/usr/local/lib/python3.5/dist-packages/pipenv/core.py", line 785, in do_install_dependencies
    bold=True,
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/utils.py", line 259, in echo
    file.write(message)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 59: ordinal not in range(256)
```

</details>

**Comment by techalchemy** [comment]
Pipenv is not supported in non-unicode environments.  Neither is python 3, nor click.  You must use a UTF8 encoding.

**Comment by egorsmkv** [comment]
Just add these lines into your ~/.bashrc

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```
