### ISSUE TITLE
`pipenv install --system PACKAGE` errors

### ISSUE THREAD

**Issue by nottrobin** [pypa/pipenv#1810]
``` bash
$ sudo pipenv install --system requests
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.1.3', 'console_scripts', 'pipenv')()
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 197, in install
    selective_upgrade=selective_upgrade
  File "/usr/local/lib/python3.5/dist-packages/pipenv/core.py", line 1731, in do_install
    ensure_project(three=three, python=python, system=system, warn=True, deploy=deploy, skip_requirements=skip_requirements)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/core.py", line 652, in ensure_project
    ensure_pipfile(validate=validate, skip_requirements=skip_requirements)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/core.py", line 342, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/project.py", line 439, in create_pipfile
    data[u'requires'] = {'python_version': python_version(self.which('python'))[:len('2.7')]}
TypeError: 'NoneType' object is not subscriptable
```

**Comment by uranusjr** [comment]
Already fixed. Please upgrade. (Also, please kindly follow the instructions in the issue template. They exist for a reason, e.g. ensure you are using the latest version.)
