### ISSUE TITLE
pipenv install fails to remove temp directory on Windows under MINGW64

### ISSUE THREAD

**Issue by saites** [pypa/pipenv#1830]
This is almost certainly low priority, but it's a bit of weirdness that I thought you might should be aware of.

I'm using Docker Toolbox on Windows, which installs MINGW for use as the Docker quickstart terminal. After install pipenv, I tried `pipenv install pytest` within the MINGW shell, but it looks like a cleanup step failed to remove a temporary directory. I am still able to use the virtualenv/pipenv after this, but it probably shouldn't break.

I removed the virtualenv via `pipenv --rm`, deleted Pipfile and Pipfile.lock, and then reran `pipenv install pytest` within the same directory, but this time from the Windows command prompt. This worked as expected.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.9.0'`

Pipenv location: `'C:\\Users\\[user]\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pipenv'`

Python location: `'C:\\Users\\[user]\\AppData\\Local\\Programs\\Python\\Python36\\python.exe'`

Other Python installations in `PATH`:

  - `3.6`: `C:\Users\[user]\AppData\Local\Programs\Python\Python36\python.exe`

  - `3.6.1`: `C:\Users\[user]\AppData\Local\Programs\Python\Python36\python.exe`
  - `3.6.1`: `C:\Windows\py.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.1',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.14393',
 'python_full_version': '3.6.1',
 'python_version': '3.6',
 'sys_platform': 'win32'}
```

System environment variables [some redacted]:

  - `DOCKER_TOOLBOX_INSTALL_PATH`
  - `GOPATH`
  - `GOROOT`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `HTTPS_PROXY`
  - `HTTP_PROXY`
  - `MOZ_PLUGIN_PATH`
  - `NO_PROXY`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCDIRLOG`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `UATDATA`
  - `USERDNSDOMAIN`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `USE_PROXY`
  - `VBOX_MSI_INSTALL_PATH`
  - `WINDIR`
  - `_JAVA_OPTIONS`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `C:\PROGRAMDATA\ORACLE\JAVA\JAVAPATH;C:\WINDOWS\SYSTEM32;C:\WINDOWS;C:\WINDOWS\SYSTEM32\WBEM;C:\WINDOWS\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;C:\PROGRAM FILES\GIT\CMD;C:\GRADLE-3.3\BIN;C:\PROGRAM FILES\NODEJS\;C:\PROGRAM FILES\PUTTY\;C:\APACHE-ANT-1.10.1\BIN;C:\APACHE-MAVEN-3.5.0\BIN;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Users\[user]\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\[user]\AppData\Local\Programs\Python\Python36\;C:\Users\[user]\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files\Docker Toolbox;C:\Users\[user]\AppData\Local\Microsoft\WindowsApps;`

---------------------------

Contents of `Pipfile` ('C:\\Users\\[user]\\Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
pytest = "*"

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('C:\\Users\\[user]\\Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "c018bb8ccec52b3be3685cb2033f3b54aaee3af3dade1807a6ae303c3f91bb67"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "attrs": {
            "hashes": [
                "sha256:1c7960ccfd6a005cd9f7ba884e6316b5e430a3f1a6c37c5f87d8b43f83b54ec9",
                "sha256:a17a9573a6f475c99b551c0e0a812707ddda1ec9653bed04c13841404ed6f450"
            ],
            "version": "==17.4.0"
        },
        "colorama": {
            "hashes": [
                "sha256:463f8483208e921368c9f306094eb6f725c6ca42b0f97e313cb5d5512459feda",
                "sha256:48eb22f4f8461b1df5734a074b57042430fb06e1d61bd1e11b078c0fe6d7a1f1"
            ],
            "markers": "sys_platform == 'win32'",
            "version": "==0.3.9"
        },
        "pluggy": {
            "hashes": [
                "sha256:7f8ae7f5bdf75671a718d2daf0a64b7885f74510bcd98b1a0bb420eb9a9d0cff"
            ],
            "version": "==0.6.0"
        },
        "py": {
            "hashes": [
                "sha256:29c9fab495d7528e80ba1e343b958684f4ace687327e6f789a94bf3d1915f881",
                "sha256:983f77f3331356039fdd792e9220b7b8ee1aa6bd2b25f567a963ff1de5a64f6a"
            ],
            "version": "==1.5.3"
        },
        "pytest": {
            "hashes": [
                "sha256:062027955bccbc04d2fcd5d79690947e018ba31abe4c90b2c6721abec734261b",
                "sha256:117bad36c1a787e1a8a659df35de53ba05f9f3398fb9e4ac17e80ad5903eb8c5"
            ],
            "index": "pypi",
            "version": "==3.4.2"
        },
        "six": {
            "hashes": [
                "sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9",
                "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"
            ],
            "version": "==1.11.0"
        }
    },
    "develop": {}
}

```
</details>

------------

##### Expected result

`pipenv install pytest` should output a success message; copied from the Windows command prompt output:

```
Creating a virtualenv for this project…
Using c:\users\[user]\appdata\local\programs\python\python36\python.exe (3.6.1) to create virtualenv…
Already using interpreter c:\users\[user]\appdata\local\programs\python\python36\python.exe
Using base prefix 'c:\\users\\[user]\\appdata\\local\\programs\\python\\python36'
New python executable in C:\Users\[user]\.virtualenvs\testing-qPom47Ab\Scripts\python.exe
Installing setuptools, pip, wheel...done.

Virtualenv location: C:\Users\[user]\.virtualenvs\testing-qPom47Ab
Creating a Pipfile for this project…
Installing pytest…
Collecting pytest
  Using cached pytest-3.4.2-py2.py3-none-any.whl
Collecting colorama; sys_platform == "win32" (from pytest)
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting attrs>=17.2.0 (from pytest)
  Using cached attrs-17.4.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in c:\users\[user]\.virtualenvs\testing-qpom47ab\lib\site-packages (from pytest)
Collecting pluggy<0.7,>=0.5 (from pytest)
Collecting py>=1.5.0 (from pytest)
  Using cached py-1.5.3-py2.py3-none-any.whl
Collecting six>=1.10.0 (from pytest)
  Using cached six-1.11.0-py2.py3-none-any.whl
Installing collected packages: colorama, attrs, pluggy, py, six, pytest
Successfully installed attrs-17.4.0 colorama-0.3.9 pluggy-0.6.0 py-1.5.3 pytest-3.4.2 six-1.11.0

Adding pytest to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (91bb67)!
Installing dependencies from Pipfile.lock (91bb67)…
  ================================ 6/6 - 00:00:01
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

##### Actual result

```
$ pipenv install pytest
Creating a virtualenv for this project…
Using c:\users\[user]\appdata\local\programs\python\python36\python.exe (3.6.1) to create virtualenv…
Already using interpreter c:\users\[user]\appdata\local\programs\python\python36\python.exe
Using base prefix 'c:\\users\\[user]\\appdata\\local\\programs\\python\\python36'
New python executable in C:\Users\[user]\.virtualenvs\testing-qPom47Ab\Scripts\python.exe
Installing setuptools, pip, wheel...done.

Virtualenv location: C:\Users\[user]\.virtualenvs\testing-qPom47Ab
Creating a Pipfile for this project…
Installing pytest…
Collecting pytest
  Using cached pytest-3.4.2-py2.py3-none-any.whl
Collecting six>=1.10.0 (from pytest)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting pluggy<0.7,>=0.5 (from pytest)
Collecting attrs>=17.2.0 (from pytest)
  Using cached attrs-17.4.0-py2.py3-none-any.whl
Collecting colorama; sys_platform == "win32" (from pytest)
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Requirement already satisfied: setuptools in c:\users\[user]\.virtualenvs\testing-qpom47ab\lib\site-packages (from pytest)
Collecting py>=1.5.0 (from pytest)
  Downloading py-1.5.3-py2.py3-none-any.whl (84kB)
Installing collected packages: six, pluggy, attrs, colorama, py, pytest
Successfully installed attrs-17.4.0 colorama-0.3.9 pluggy-0.6.0 py-1.5.3 pytest-3.4.2 six-1.11.0

Adding pytest to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (91bb67)!
Installing dependencies from Pipfile.lock (91bb67)…
  ================================ 6/6 - 00:00:01
Traceback (most recent call last):
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python36\Scripts\pipenv-script.py", line 11, in <module>
    load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')()
  File "c:\users\[user]\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\[user]\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\[user]\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\[user]\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\[user]\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\[user]\appdata\local\programs\python\python36\lib\site-packages\pipenv\cli.py", line 366, in install
    selective_upgrade=selective_upgrade,
  File "c:\users\[user]\appdata\local\programs\python\python36\lib\site-packages\pipenv\core.py", line 1996, in do_install
    requirements_dir=requirements_directory,
  File "c:\users\[user]\appdata\local\programs\python\python36\lib\site-packages\pipenv\core.py", line 1371, in do_init
    requirements_dir.cleanup()
  File "c:\users\[user]\appdata\local\programs\python\python36\lib\site-packages\pipenv\utils.py", line 1243, in cleanup
    rmtree(self.name)
  File "c:\users\[user]\appdata\local\programs\python\python36\lib\site-packages\pipenv\utils.py", line 1166, in rmtree
    directory, ignore_errors=ignore_errors, onerror=handle_remove_readonly
  File "c:\users\[user]\appdata\local\programs\python\python36\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\[user]\appdata\local\programs\python\python36\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\users\[user]\appdata\local\programs\python\python36\lib\shutil.py", line 391, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\[user]\\AppData\\Local\\Temp\\pipenv-dttvu2tx-requirements'
```

##### Steps to replicate

- Install Docker Toolbox on Windows
- Install python
- Install pipenv
- run `pipenv install pytest` within MINGW64 shell (Docker quickstart terminal)

**Comment by techalchemy** [comment]
hey @saites we don't actually support MINGW64 technically speaking, mainly due to issues with temporary file handling on windows (as you can see here).  It's basically impossible to properly clean up temporary file handles when dealing with the subprocess hierarchy there.  We have extensive code to try and handle these cases but some slip through the cracks... I don't think there is much we can do here unfortunately, sorry about that!

**Comment by saites** [comment]
OK, no worries. Thank you for the reply. MINGW64 is really quite a strange environment, but I need it for Docker. 

I will simply run pipenv from the Windows command line.

**Comment by techalchemy** [comment]
@saites FWIW I don't usually have those problems and I run pipenv pretty regularly from a hacky setup that uses fish from cmder/msys2 built from the git for windows sdk:

![image](https://user-images.githubusercontent.com/954310/37800329-d6a9342c-2df8-11e8-9462-87e8c30bfe82.png)
