### ISSUE TITLE
'python_version': python_version(required_python)[: len('2.7')] TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by adiusz** [pypa/pipenv#1858]
Hi.
I would like to report some issue. I'm running Python 3.6.4 v on macOS High Sierra 10.13.3 and everytime i create a new folder and try to 

> pipenv install django 

i got this: 

>Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project…
Using /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 (3.6.4) to create virtualenv…
blablabla....
    'python_version': python_version(required_python)[: len('2.7')]
TypeError: 'NoneType' object is not subscriptable

This issue was mentioned here but i didn't find a solution that worked for me tho. So for everyone who faced this problem. Just simply put this in your terminal
> export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

Then u can install django and use shell.
Have a nice day.

**Comment by techalchemy** [comment]
Thanks for the tip, if this is not somewhere in our documentation we need to get it there. Thanks for using pipenv :)

**Comment by shanezhiu** [comment]
Yep, I also got stuck the same problem, and I tried the way @adiusz mentioned above, but it did not  work for me, there is prompt info. I wonder know why it occurs and how to solute it.
```
Creating a virtualenv for this project…
Using /usr/bin/python3 (3.6.7) to create virtualenv…
⠋/usr/bin/python3: No module named pipenv.pew

Virtualenv location:
Creating a Pipfile for this project…                                                                                                                                                             Traceback (most recent call last):
  File "/usr/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 366, in install
    selective_upgrade=selective_upgrade,
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 1761, in do_install
    skip_requirements=skip_requirements,
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 636, in ensure_project
    ensure_pipfile(validate=validate, skip_requirements=skip_requirements)
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 289, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/usr/lib/python3/dist-packages/pipenv/project.py", line 518, in create_pipfile
    'python_version': python_version(required_python)[: len('2.7')]
TypeError: 'NoneType' object is not subscriptable
```
