### ISSUE TITLE
pipenv install --ignore-pipfile fails for official docker images

### ISSUE THREAD

**Issue by immerrr** [pypa/pipenv#1897]
I tried to start using pipenv to manage dependencies running the code on top of `python:3.6-slim` docker image, but ran into a failure that seems to reproduce just fine on `python:3.6-alpine` too.

I've boiled it down to this [gist]( https://gist.github.com/immerrr/0f760fad425a851ce45ba2de0e4af8be). It appears to fail when trying to create a `Pipfile` and is possibly related to python being in `/usr/local` rather than in `/usr`, but I'm not quite sure. Here's what I see when when running `pipenv` inside a directory that only contains `Pipfile.lock`:
```
+ pipenv install --system --ignore-pipfile
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 366, in install
    selective_upgrade=selective_upgrade,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1761, in do_install
    skip_requirements=skip_requirements,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 636, in ensure_project
    ensure_pipfile(validate=validate, skip_requirements=skip_requirements)
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 289, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/usr/local/lib/python3.6/site-packages/pipenv/project.py", line 518, in create_pipfile
    'python_version': python_version(required_python)[: len('2.7')]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by techalchemy** [comment]
Pipenv can _ignore_ the pipfile, however you msut still _include_ the pipfile in your directory or it will not work.
