### ISSUE TITLE
"pipenv run {alias}" fails (regression)

### ISSUE THREAD

**Issue by Moritz90** [pypa/pipenv#1904]
After upgrading from pipenv 11.1.0 to 11.9.0, running the command defined in the `[scripts]` section of my Pipfile no longer works.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.9.0'`

Pipenv location: `'/home/moritz/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.14`: `/usr/bin/python`
  - `2.7.14`: `/usr/bin/python2`
  - `3.6.3`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.13.0-37-generic',
 'platform_system': 'Linux',
 'platform_version': '#42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018',
 'python_full_version': '3.6.3',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SESSION_MANAGER`
  - `XDG_SESSION_ID`
  - `LC_IDENTIFICATION`
  - `WINDOWPATH`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `DISPLAY`
  - `XDG_SEAT`
  - `GNOME_DESKTOP_SESSION_ID`
  - `DEFAULTS_PATH`
  - `LOGNAME`
  - `TEXTDOMAIN`
  - `LC_TIME`
  - `SHELL`
  - `JAVA_HOME`
  - `PATH`
  - `LC_NUMERIC`
  - `ftp_proxy`
  - `LC_PAPER`
  - `IM_CONFIG_PHASE`
  - `QT4_IM_MODULE`
  - `CLUTTER_IM_MODULE`
  - `TEXTDOMAINDIR`
  - `XMODIFIERS`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `J2REDIR`
  - `XDG_MENU_PREFIX`
  - `XAUTHORITY`
  - `XDG_SESSION_DESKTOP`
  - `GDMSESSION`
  - `QT_IM_MODULE`
  - `SSH_AUTH_SOCK`
  - `LC_MEASUREMENT`
  - `LC_ADDRESS`
  - `GNOME_SHELL_SESSION_MODE`
  - `MANDATORY_PATH`
  - `XDG_CONFIG_DIRS`
  - `USERNAME`
  - `DESKTOP_SESSION`
  - `no_proxy`
  - `https_proxy`
  - `GTK_IM_MODULE`
  - `XDG_RUNTIME_DIR`
  - `GTK_MODULES`
  - `USER`
  - `PWD`
  - `DERBY_HOME`
  - `LC_MONETARY`
  - `HOME`
  - `QT_ACCESSIBILITY`
  - `DESKTOP_AUTOSTART_ID`
  - `SSH_AGENT_PID`
  - `XDG_DATA_DIRS`
  - `GUAKE_TAB_UUID`
  - `LANG`
  - `LC_NAME`
  - `SHLVL`
  - `JOURNAL_STREAM`
  - `J2SDKDIR`
  - `XDG_VTNR`
  - `XDG_SESSION_TYPE`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_CURRENT_DESKTOP`
  - `http_proxy`
  - `S_COLORS`
  - `LC_TELEPHONE`
  - `TERM`
  - `OLDPWD`
  - `LD_LIBRARY_PATH`
  - `LS_COLORS`
  - `LESSOPEN`
  - `LESSCLOSE`
  - `GCC_COLORS`
  - `WORKON_HOME`
  - `PROJECT_HOME`
  - `VIRTUALENVWRAPPER_PROJECT_FILENAME`
  - `VIRTUALENVWRAPPER_SCRIPT`
  - `VIRTUALENVWRAPPER_HOOK_DIR`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/moritz/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/moritz/Projects/flask-todo`

---------------------------

Contents of `Pipfile` ('/home/moritz/Projects/flask-todo/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = "~=0.12.2"
flask-migrate = "~=2.1.1"

[dev-packages]
pytest = "~=3.5.0"

[requires]
python_version = "3.6"

[scripts]
tests = "python -m pytest"

```

Contents of `Pipfile.lock` ('/home/moritz/Projects/flask-todo/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "685d2d34db1446e89ad6a0cf549d6850e9572beba36e025d3ee20558a055476f"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "alembic": {
            "hashes": [
                "sha256:85bd3ea7633024e4930900bc64fb58f9742dedbc6ebb6ecf25be2ea9a3c1b32e"
            ],
            "version": "==0.9.9"
        },
        "click": {
            "hashes": [
                "sha256:29f99fc6125fbc931b758dc053b3114e55c77a6e4c6c3a2674a2dc986016381d",
                "sha256:f15516df478d5a56180fbf80e68f206010e6d160fc39fa508b65e035fd75130b"
            ],
            "version": "==6.7"
        },
        "flask": {
            "hashes": [
                "sha256:0749df235e3ff61ac108f69ac178c9770caeaccad2509cb762ce1f65570a8856",
                "sha256:49f44461237b69ecd901cc7ce66feea0319b9158743dd27a2899962ab214dac1"
            ],
            "index": "pypi",
            "version": "==0.12.2"
        },
        "flask-migrate": {
            "hashes": [
                "sha256:493f9b3795985b9b4915bf3b7d16946697f027b73545384e7d9e3a79f989d2fe",
                "sha256:b709ca8642559c3c5a81a33ab10839fa052177accd5ba821047a99db635255ed"
            ],
            "index": "pypi",
            "version": "==2.1.1"
        },
        "flask-sqlalchemy": {
            "hashes": [
                "sha256:3bc0fac969dd8c0ace01b32060f0c729565293302f0c4269beed154b46bec50b",
                "sha256:5971b9852b5888655f11db634e87725a9031e170f37c0ce7851cf83497f56e53"
            ],
            "version": "==2.3.2"
        },
        "itsdangerous": {
            "hashes": [
                "sha256:cbb3fcf8d3e33df861709ecaf89d9e6629cff0a217bc2848f1b41cd30d360519"
            ],
            "version": "==0.24"
        },
        "jinja2": {
            "hashes": [
                "sha256:74c935a1b8bb9a3947c50a54766a969d4846290e1e788ea44c1392163723c3bd",
                "sha256:f84be1bb0040caca4cea721fcbbbbd61f9be9464ca236387158b0feea01914a4"
            ],
            "version": "==2.10"
        },
        "mako": {
            "hashes": [
                "sha256:4e02fde57bd4abb5ec400181e4c314f56ac3e49ba4fb8b0d50bba18cb27d25ae"
            ],
            "version": "==1.0.7"
        },
        "markupsafe": {
            "hashes": [
                "sha256:a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665"
            ],
            "version": "==1.0"
        },
        "python-dateutil": {
            "hashes": [
                "sha256:3220490fb9741e2342e1cf29a503394fdac874bc39568288717ee67047ff29df",
                "sha256:9d8074be4c993fbe4947878ce593052f71dac82932a677d49194d8ce9778002e"
            ],
            "version": "==2.7.2"
        },
        "python-editor": {
            "hashes": [
                "sha256:a3c066acee22a1c94f63938341d4fb374e3fdd69366ed6603d7b24bed1efc565"
            ],
            "version": "==1.0.3"
        },
        "six": {
            "hashes": [
                "sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9",
                "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"
            ],
            "version": "==1.11.0"
        },
        "sqlalchemy": {
            "hashes": [
                "sha256:7cb00cc9b9f92ef8b4391c8a2051f81eeafefe32d63c6b395fd51401e9a39edb"
            ],
            "version": "==1.2.6"
        },
        "werkzeug": {
            "hashes": [
                "sha256:c3fd7a7d41976d9f44db327260e263132466836cef6f91512889ed60ad26557c",
                "sha256:d5da73735293558eb1651ee2fddc4d0dedcfa06538b8813a2e20011583c9e49b"
            ],
            "version": "==0.14.1"
        }
    },
    "develop": {
        "attrs": {
            "hashes": [
                "sha256:1c7960ccfd6a005cd9f7ba884e6316b5e430a3f1a6c37c5f87d8b43f83b54ec9",
                "sha256:a17a9573a6f475c99b551c0e0a812707ddda1ec9653bed04c13841404ed6f450"
            ],
            "version": "==17.4.0"
        },
        "more-itertools": {
            "hashes": [
                "sha256:0dd8f72eeab0d2c3bd489025bb2f6a1b8342f9b198f6fc37b52d15cfa4531fea",
                "sha256:11a625025954c20145b37ff6309cd54e39ca94f72f6bb9576d1195db6fa2442e",
                "sha256:c9ce7eccdcb901a2c75d326ea134e0886abfbea5f93e91cc95de9507c0816c44"
            ],
            "version": "==4.1.0"
        },
        "pluggy": {
            "hashes": [
                "sha256:7f8ae7f5bdf75671a718d2daf0a64b7885f74510bcd98b1a0bb420eb9a9d0cff"
            ],
            "version": "==0.6.0"
        },
        "py": {
            "hashes": [
                "sha256:29c9fab495d7528e80ba1e343b958684f4ace687327e6f789a94bf3d1915f881",
                "sha256:983f77f3331356039fdd792e9220b7b8ee1aa6bd2b25f567a963ff1de5a64f6a"
            ],
            "version": "==1.5.3"
        },
        "pytest": {
            "hashes": [
                "sha256:6266f87ab64692112e5477eba395cfedda53b1933ccd29478e671e73b420c19c",
                "sha256:fae491d1874f199537fd5872b5e1f0e74a009b979df9d53d1553fd03da1703e1"
            ],
            "index": "pypi",
            "version": "==3.5.0"
        },
        "six": {
            "hashes": [
                "sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9",
                "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"
            ],
            "version": "==1.11.0"
        }
    }
}

```
</details>

------------

##### Expected result

pytest is executed

##### Actual result

```
Traceback (most recent call last):
  File "/home/moritz/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/moritz/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/moritz/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/moritz/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/moritz/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/moritz/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/moritz/.local/lib/python3.6/site-packages/pipenv/cli.py", line 602, in run
    core.do_run(command=command, args=args, three=three, python=python)
  File "/home/moritz/.local/lib/python3.6/site-packages/pipenv/core.py", line 2200, in do_run
    command = ' '.join(project.scripts[command])
  File "/home/moritz/.local/lib/python3.6/site-packages/pipenv/project.py", line 374, in scripts
    scripts[k] = shlex.split(v, posix=True)
  File "/usr/lib/python3.6/shlex.py", line 305, in split
    return list(lex)
  File "/usr/lib/python3.6/shlex.py", line 295, in __next__
    token = self.get_token()
  File "/usr/lib/python3.6/shlex.py", line 105, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.6/shlex.py", line 136, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'ArrayElement' object has no attribute 'read'
```

##### Steps to replicate

Add the following to your Pipfile:

```
[scripts]
tests = "python -m pytest"
```

Then try to run `pipenv run tests`.

**Comment by tsiq-oliverc** [comment]
Out of curiosity, how do you folks track issues to resolution?  (Naively, I'd assume that you'd want to keep the issue open until a corresponding PR is merged.)

**Comment by uranusjr** [comment]
@tsiq-oliverc The fix is already in master, I just don’t bother to dig out the exact PR (or commit)…

**Comment by techalchemy** [comment]
Technically only half fixed in master until we split the other branch up for the test fixes

**Comment by Moritz90** [comment]
@tsiq-oliverc As long as the fix will be in the very next release, I'm fine with my bug being closed immediately. Since the Github bug tracker is not the best bug tracker on the planet, I guess that's the best way to do it.

**Comment by techalchemy** [comment]
@Moritz90 if the code is merged in master it will be in the next release.  For the record, we do this for _our_ workflow, not yours. The bug is fixed. The fact that  fix is not available on pypi yet has nothing to do with our issue tracker. You're free to install from master. Our workflow isn't changing.

**Comment by Moritz90** [comment]
@techalchemy That's perfectly fine by me; in fact, that's exactly what I was trying to say. Sorry if the phrasing of my earlier comment didn't convey that. I'm hoping you didn't misread my earlier comment as a demand of any kind. I just tried to explain my understanding of the expected user workflow.
