### ISSUE TITLE
Pipenv sees `sys_platform == "win32"` marker but doesn't respect it

### ISSUE THREAD

**Issue by altendky** [pypa/pipenv#1954]
I would expect `pypiwin32 = {markers = "sys_platform == 'win32'"}` to not try to be installed in Linux and therefore not result in an error.  While `pipenv` does say it is `Ignoring pypiwin32` it subsequently also fails with `No matching distribution found for pywin32==223`.

Tested against d2b0580427bbaeda3b8efea4b884c5d857360508.

```bash
altendky@lt:/home/epc/t/pipenv/t$ rm Pipfile.lock
rm: cannot remove 'Pipfile.lock': No such file or directory
altendky@lt:/home/epc/t/pipenv/t$ git -C ../pipenv rev-parse HEAD
d2b0580427bbaeda3b8efea4b884c5d857360508
altendky@lt:/home/epc/t/pipenv/t$ ../pipenv/venv/bin/pipenv install
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (1eacc8)!
Installing dependencies from Pipfile.lock (1eacc8)…
Ignoring pypiwin32: markers 'sys_platform == "win32"' don't match your environment
An error occurred while installing pywin32==223! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:01
Installing initially–failed dependencies…
Collecting pywin32==223 ▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:00

  Could not find a version that satisfies the requirement pywin32==223 (from -r /tmp/pipenv-csqv2dmw-requirements/pipenv-6oz3mv06-requirement.txt (line 1)) (from versions: )
No matching distribution found for pywin32==223 (from -r /tmp/pipenv-csqv2dmw-requirements/pipenv-6oz3mv06-requirement.txt (line 1))

  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:01
altendky@lt:/home/epc/t/pipenv/t$ ../pipenv/venv/bin/python -m pipenv.help
```
<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.9.1'`

Pipenv location: `'/home/epc/t/pipenv/pipenv/pipenv'`

Python location: `'/home/epc/t/pipenv/t/../pipenv/venv/bin/python'`

Other Python installations in `PATH`:

  - `2.6`: `/home/altendky/.pyenv/shims/python2.6`
  - `2.6`: `/home/altendky/.pyenv/shims/python2.6`
  - `2.7`: `/home/altendky/.pyenv/shims/python2.7`
  - `2.7`: `/home/altendky/.pyenv/shims/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.4`: `/home/altendky/.pyenv/shims/python3.4m`
  - `3.4`: `/home/altendky/.pyenv/shims/python3.4`
  - `3.5`: `/home/altendky/.pyenv/shims/python3.5m`
  - `3.5`: `/home/altendky/.pyenv/shims/python3.5`
  - `3.5`: `/usr/bin/python3.5`
  - `3.6`: `/home/altendky/.pyenv/shims/python3.6m`
  - `3.6`: `/home/altendky/.pyenv/shims/python3.6`
  - `3.7`: `/home/altendky/.pyenv/shims/python3.7m`
  - `3.7`: `/home/altendky/.pyenv/shims/python3.7`

  - `3.6.3`: `/home/altendky/.pyenv/shims/python`
  - `2.7.13`: `/usr/bin/python`
  - `2.7.14`: `/home/altendky/.pyenv/shims/python2`
  - `2.7.13`: `/usr/bin/python2`
  - `3.6.3`: `/home/altendky/.pyenv/shims/python3`
  - `3.5.3`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.9.0-6-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02)',
 'python_full_version': '3.6.3',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `GS_LIB`
  - `KDE_FULL_SESSION`
  - `LS_COLORS`
  - `LANG`
  - `PROFILEHOME`
  - `DISPLAY`
  - `PYENV_ROOT`
  - `SHELL_SESSION_ID`
  - `EDITOR`
  - `COLORTERM`
  - `XDG_VTNR`
  - `PAM_KWALLET5_LOGIN`
  - `SSH_AUTH_SOCK`
  - `XDG_SESSION_ID`
  - `USER`
  - `DESKTOP_SESSION`
  - `PWD`
  - `HOME`
  - `SSH_AGENT_PID`
  - `QT_ACCESSIBILITY`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `KONSOLE_DBUS_SESSION`
  - `XDG_SESSION_DESKTOP`
  - `KONSOLE_DBUS_WINDOW`
  - `GTK_MODULES`
  - `TERM`
  - `SHELL`
  - `KONSOLE_DBUS_SERVICE`
  - `XDG_SESSION_CLASS`
  - `XDG_SEAT_PATH`
  - `XCURSOR_THEME`
  - `XDG_CURRENT_DESKTOP`
  - `GPG_AGENT_INFO`
  - `QT_LINUX_ACCESSIBILITY_ALWAYS_ON`
  - `KONSOLE_PROFILE_NAME`
  - `XDG_SEAT`
  - `SHLVL`
  - `COLORFGBG`
  - `LANGUAGE`
  - `WINDOWID`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `XDG_SESSION_PATH`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `PATH`
  - `KDE_SESSION_UID`
  - `KDE_SESSION_VERSION`
  - `KDED_STARTED_BY_KDEINIT`
  - `SESSION_MANAGER`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/altendky/.pyenv/bin:/home/altendky/venvs/bin:/home/altendky/.pyenv/bin:/home/altendky/.pyenv/shims:/epc/bin:/home/altendky/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/epc/bin`
  - `SHELL`: `/usr/bin/fish`
  - `EDITOR`: `vi`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/epc/t/pipenv/t`

---------------------------

Contents of `Pipfile` ('/home/epc/t/pipenv/t/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
pypiwin32 = {markers = "sys_platform == 'win32'"}

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/home/epc/t/pipenv/t/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "9fa04988206025352c69a12c7fc93425680db8e7ea405fe879a6c118a61eacc8"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "pypiwin32": {
            "hashes": [
                "sha256:67adf399debc1d5d14dffc1ab5acacb800da569754fafdc576b2a039485aa775",
                "sha256:71be40c1fbd28594214ecaecb58e7aa8b708eabfa0125c8a109ebd51edbd776a"
            ],
            "index": "pypi",
            "markers": "sys_platform == 'win32'",
            "version": "==223"
        },
        "pywin32": {
            "hashes": [
                "sha256:0df9b008caef10af0d674c483316c28dcf78391332d9d5d380fab667ebf2d7d1",
                "sha256:249391eb924b8376826e6f84d143d1dcc0e400b238b511d5fbd3811f6ed9ad50",
                "sha256:42f48567e36b787901ff3da20de5a134cd9880cc90832e2aad60951f058699f0",
                "sha256:9eff897796c9d76a213134257a01b6f8a122c55e0772847fba313a8091f3ec44",
                "sha256:c7ea0deabcc324e5b74084b5452003109c592d1aedbe9e9289ed55b26d9b0c7f",
                "sha256:da422d4067d98b49fbb19d851900a5fc38c61eab0ee803574c27c42309173ebe",
                "sha256:f0f0e7c82ee334dd6e888b9b5beb05fd8947355fa7a15644c810bb4ea0079ca6",
                "sha256:fb3c85907918fd01a72ee146d323d220771dee151c0cfa5630c2f35797ffb116"
            ],
            "version": "==223"
        }
    },
    "develop": {}
}

```
</details>

<details><summary>$ ../pipenv/venv/bin/pipenv install --verbose</summary>

```bash
altendky@lt:/home/epc/t/pipenv/t$ ../pipenv/venv/bin/pipenv install --verbose
Installing dependencies from Pipfile.lock (1eacc8)…
Installing "pypiwin32==223; sys_platform == 'win32' --hash=sha256:67adf399debc1d5d14dffc1ab5acacb800da569754fafdc576b2a039485aa775  --hash=sha256:71be40c1fbd28594214ecaecb58e7aa8b708eabfa0125c8a109ebd51edbd776a"
$ "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/bin/pip" install   --verbose  --no-deps  -r /tmp/pipenv-k0s30nht-requirements/pipenv-9ctplt_g-requirement.txt --require-hashes -i https://pypi.python.org/simple --exists-action w
Installing 'pywin32==223 --hash=sha256:0df9b008caef10af0d674c483316c28dcf78391332d9d5d380fab667ebf2d7d1  --hash=sha256:249391eb924b8376826e6f84d143d1dcc0e400b238b511d5fbd3811f6ed9ad50  --hash=sha256:42f48567e36b787901ff3da20de5a134cd9880cc90832e2aad60951f058699f0  --hash=sha256:9eff897796c9d76a213134257a01b6f8a122c55e0772847fba313a8091f3ec44  --hash=sha256:c7ea0deabcc324e5b74084b5452003109c592d1aedbe9e9289ed55b26d9b0c7f  --hash=sha256:da422d4067d98b49fbb19d851900a5fc38c61eab0ee803574c27c42309173ebe  --hash=sha256:f0f0e7c82ee334dd6e888b9b5beb05fd8947355fa7a15644c810bb4ea0079ca6  --hash=sha256:fb3c85907918fd01a72ee146d323d220771dee151c0cfa5630c2f35797ffb116'
$ "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/bin/pip" install   --verbose  --no-deps  -r /tmp/pipenv-k0s30nht-requirements/pipenv-i4gg_i_f-requirement.txt --require-hashes -i https://pypi.python.org/simple --exists-action w
Ignoring pypiwin32: markers 'sys_platform == "win32"' don't match your environment
Ignoring pypiwin32: markers 'sys_platform == "win32"' don't match your environment

Collecting pywin32==223 (from -r /tmp/pipenv-k0s30nht-requirements/pipenv-i4gg_i_f-requirement.txt (line 1))
  1 location(s) to search for versions of pywin32:
  * https://pypi.python.org/simple/pywin32/
  Getting page https://pypi.python.org/simple/pywin32/
  Looking up "https://pypi.python.org/simple/pywin32/" in the cache
  Current age based on date: 114
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 114
  Analyzing links from page https://pypi.python.org/simple/pywin32/
    Skipping link https://pypi.python.org/packages/36/98/581719389bef3491e982b0550ab539c25e8b2d1e9fd0695f4a05c696f061/pywin32-222-cp27-cp27m-win32.whl#md5=51917d8ed94c02bf88d84b88818905ea (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/96/4b/b52fb6f3b1648a52a3dfc422dace461a237d23ac55dfc0375b6263e86bd9/pywin32-222-cp27-cp27m-win_amd64.whl#md5=ea0cba650d37cd2869adeef3f3bb803c (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/ed/7b/2b4ed81d83cb98721a7d1bd01a1899351a99260fe97cc51d5118ac9998f7/pywin32-222-cp35-cp35m-win32.whl#md5=3a0dbb14218636bb8621f744b1214f52 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/20/6d/ba9413b676959e49ffa990abb0f3dc4db57d2d23271859f3f76e59796e3e/pywin32-222-cp35-cp35m-win_amd64.whl#md5=4a3bf2aae41cb1d87067c5e3d63a4e46 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/23/e3/e65b4d14c89f68bb85c24d733bcdb0b684af34970bdbb1b0892985965ce9/pywin32-222-cp36-cp36m-win32.whl#md5=ef168bf2acbdced419d27467ed793c95 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/be/25/0e0c568456b77ce144dd2b8799f915b046ffa1cd922771d214e4be05bca2/pywin32-222-cp36-cp36m-win_amd64.whl#md5=94a9a3782081e14973c5ae448957d530 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/91/67/59bb7d0d7623b879ce871ff82fb05da9efa63e907e1ba2e253c4cea6dcfc/pywin32-222-cp37-cp37m-win32.whl#md5=eba4296557e1fd50b68cf8e93fd8ee83 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/a0/76/89b836562a36929bb913f9c17fca54fdd2c68b5e97ec0d626a389c087150/pywin32-223-cp27-cp27m-win32.whl#md5=f25f866c8d76a1854affc34ab214cd7e (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/65/83/0b14690d70bcd193a67c8b0a640129717e37a11d8e6a3e28a01e47910737/pywin32-223-cp27-cp27m-win_amd64.whl#md5=c9d2d260ef87592bb04cbc59f1ffe2d2 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/32/0f/16419ffd63c60b0c197614c430eab35360a94154ac1b846b3ee69f8c8061/pywin32-223-cp35-cp35m-win32.whl#md5=b68b53a5fdbbb1c2d67c1308aac34a02 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/73/48/42e18ab94651c28d21f626ce1b5feaf60e5fb2aae3d264138aa768532a5f/pywin32-223-cp35-cp35m-win_amd64.whl#md5=0cff676367cdbb803f98fd163e0b61ba (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/d4/2d/b927e61c4a2b0aaaab72c8cb97cf748c319c399d804293164b0c43380d5f/pywin32-223-cp36-cp36m-win32.whl#md5=f30f6f3979f77f79bed4d871b508c41c (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/9f/9d/f4b2170e8ff5d825cd4398856fee88f6c70c60bce0aa8411ed17c1e1b21f/pywin32-223-cp36-cp36m-win_amd64.whl#md5=2d211288ee000b6ec5d37436bcbe8a43 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/d6/39/5c318e0b61d892861fe65a6a3150d42be4d87ae9137be2ef3e35632341c2/pywin32-223-cp37-cp37m-win32.whl#md5=9c0387c16d3335f02093fc7b148d9b13 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/f4/fb/ba9e519d90b63090005bcdee900d318d895d475c627dc1bc0f77b27abad0/pywin32-223-cp37-cp37m-win_amd64.whl#md5=c6e4dcf5042226bd94fb06556572fa57 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
  Could not find a version that satisfies the requirement pywin32==223 (from -r /tmp/pipenv-k0s30nht-requirements/pipenv-i4gg_i_f-requirement.txt (line 1)) (from versions: )
Cleaning up...
No matching distribution found for pywin32==223 (from -r /tmp/pipenv-k0s30nht-requirements/pipenv-i4gg_i_f-requirement.txt (line 1))
Exception information:
Traceback (most recent call last):
  File "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/lib/python3.6/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for pywin32==223 (from -r /tmp/pipenv-k0s30nht-requirements/pipenv-i4gg_i_f-requirement.txt (line 1))

An error occurred while installing pywin32==223! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:01
Installing initially–failed dependencies…
Installing 'pywin32==223 --hash=sha256:0df9b008caef10af0d674c483316c28dcf78391332d9d5d380fab667ebf2d7d1  --hash=sha256:249391eb924b8376826e6f84d143d1dcc0e400b238b511d5fbd3811f6ed9ad50  --hash=sha256:42f48567e36b787901ff3da20de5a134cd9880cc90832e2aad60951f058699f0  --hash=sha256:9eff897796c9d76a213134257a01b6f8a122c55e0772847fba313a8091f3ec44  --hash=sha256:c7ea0deabcc324e5b74084b5452003109c592d1aedbe9e9289ed55b26d9b0c7f  --hash=sha256:da422d4067d98b49fbb19d851900a5fc38c61eab0ee803574c27c42309173ebe  --hash=sha256:f0f0e7c82ee334dd6e888b9b5beb05fd8947355fa7a15644c810bb4ea0079ca6  --hash=sha256:fb3c85907918fd01a72ee146d323d220771dee151c0cfa5630c2f35797ffb116'
$ "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/bin/pip" install   --verbose  --no-deps  -r /tmp/pipenv-k0s30nht-requirements/pipenv-6vr_ku9x-requirement.txt --require-hashes -i https://pypi.python.org/simple --exists-action w
Collecting pywin32==223 
  1 location(s) to search for versions of pywin32:
  * https://pypi.python.org/simple/pywin32/
  Getting page https://pypi.python.org/simple/pywin32/
  Looking up "https://pypi.python.org/simple/pywin32/" in the cache
  Current age based on date: 115
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 115
  Analyzing links from page https://pypi.python.org/simple/pywin32/
    Skipping link https://pypi.python.org/packages/36/98/581719389bef3491e982b0550ab539c25e8b2d1e9fd0695f4a05c696f061/pywin32-222-cp27-cp27m-win32.whl#md5=51917d8ed94c02bf88d84b88818905ea (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/96/4b/b52fb6f3b1648a52a3dfc422dace461a237d23ac55dfc0375b6263e86bd9/pywin32-222-cp27-cp27m-win_amd64.whl#md5=ea0cba650d37cd2869adeef3f3bb803c (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/ed/7b/2b4ed81d83cb98721a7d1bd01a1899351a99260fe97cc51d5118ac9998f7/pywin32-222-cp35-cp35m-win32.whl#md5=3a0dbb14218636bb8621f744b1214f52 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/20/6d/ba9413b676959e49ffa990abb0f3dc4db57d2d23271859f3f76e59796e3e/pywin32-222-cp35-cp35m-win_amd64.whl#md5=4a3bf2aae41cb1d87067c5e3d63a4e46 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/23/e3/e65b4d14c89f68bb85c24d733bcdb0b684af34970bdbb1b0892985965ce9/pywin32-222-cp36-cp36m-win32.whl#md5=ef168bf2acbdced419d27467ed793c95 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/be/25/0e0c568456b77ce144dd2b8799f915b046ffa1cd922771d214e4be05bca2/pywin32-222-cp36-cp36m-win_amd64.whl#md5=94a9a3782081e14973c5ae448957d530 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/91/67/59bb7d0d7623b879ce871ff82fb05da9efa63e907e1ba2e253c4cea6dcfc/pywin32-222-cp37-cp37m-win32.whl#md5=eba4296557e1fd50b68cf8e93fd8ee83 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/a0/76/89b836562a36929bb913f9c17fca54fdd2c68b5e97ec0d626a389c087150/pywin32-223-cp27-cp27m-win32.whl#md5=f25f866c8d76a1854affc34ab214cd7e (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/65/83/0b14690d70bcd193a67c8b0a640129717e37a11d8e6a3e28a01e47910737/pywin32-223-cp27-cp27m-win_amd64.whl#md5=c9d2d260ef87592bb04cbc59f1ffe2d2 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/32/0f/16419ffd63c60b0c197614c430eab35360a94154ac1b846b3ee69f8c8061/pywin32-223-cp35-cp35m-win32.whl#md5=b68b53a5fdbbb1c2d67c1308aac34a02 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/73/48/42e18ab94651c28d21f626ce1b5feaf60e5fb2aae3d264138aa768532a5f/pywin32-223-cp35-cp35m-win_amd64.whl#md5=0cff676367cdbb803f98fd163e0b61ba (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/d4/2d/b927e61c4a2b0aaaab72c8cb97cf748c319c399d804293164b0c43380d5f/pywin32-223-cp36-cp36m-win32.whl#md5=f30f6f3979f77f79bed4d871b508c41c (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/9f/9d/f4b2170e8ff5d825cd4398856fee88f6c70c60bce0aa8411ed17c1e1b21f/pywin32-223-cp36-cp36m-win_amd64.whl#md5=2d211288ee000b6ec5d37436bcbe8a43 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/d6/39/5c318e0b61d892861fe65a6a3150d42be4d87ae9137be2ef3e35632341c2/pywin32-223-cp37-cp37m-win32.whl#md5=9c0387c16d3335f02093fc7b148d9b13 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/f4/fb/ba9e519d90b63090005bcdee900d318d895d475c627dc1bc0f77b27abad0/pywin32-223-cp37-cp37m-win_amd64.whl#md5=c6e4dcf5042226bd94fb06556572fa57 (from https://pypi.python.org/simple/pywin32/); it is not compatible with this Python
Cleaning up...
Exception information:
Traceback (most recent call last):
  File "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/altendky/.local/share/virtualenvs/t-QpgK7uUH/lib/python3.6/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for pywin32==223 

  Could not find a version that satisfies the requirement pywin32==223 (from -r /tmp/pipenv-k0s30nht-requirements/pipenv-6vr_ku9x-requirement.txt (line 1)) (from versions: )
No matching distribution found for pywin32==223 (from -r /tmp/pipenv-k0s30nht-requirements/pipenv-6vr_ku9x-requirement.txt (line 1))

  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 —
```
</details>

**Comment by techalchemy** [comment]
This is a problem with pywin32 specifically, see previous issues on this topic

**Comment by gsemet** [comment]
Previous threads does not give the solution, sadly.

**Comment by altendky** [comment]
@gsemet, this isn't a solution but if I understood correctly it's the discussion of finding a solution.  What is your particular scenario?

**Comment by gsemet** [comment]
I did not understood this issue has been resolved on master but not yet released. My use case:
- typing should not be installed on python >=3.5
- pynsist and pywin32 should not be installed on windows

**Comment by altendky** [comment]
@gsemet, this issue report is at it's heart about the pywin32 `setup.py` that imports windows only stuff, as I recall.  It shouldn't have anything to do with `typing` or `pynsist`.  Perhaps you should file a full report including a real or sample project and a terminal log of the issue?  Not that I'm significantly involved in pipenv but you can copy me on a new issue if you make one and I'll see if I can offer any help.  I've dealt with some other conditional dependency issues with pipenv as well, but they should be fixed as I recall.

**Comment by aselma** [comment]
This Pipfile fail in a linux, it tries to install appnode

`[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
ipython = "*"
flake8 = "*"
requests = "*"
pytest = "*"
pytest-cov = "*"
ipdb = "*"

[packages]
starlette = "*"
uvicorn = "*"
databases = {extras = ["sqlite"],version = "*"}
sqlalchemy-utils = "*"
fastjsonschema = "*"

httptools = { markers = "sys_platform != 'win32'"}
uvloop = 	{ markers = "sys_platform != 'win32'"}
pexpect = 	{ markers = "sys_platform != 'win32'"}

appnode = 	{ markers = "sys_platform == 'darwin'"}

[requires]
python_version = "3.7"
`
`
$ pipenv install -d
Pipfile.lock (a37e94) out of date, updating to (ea8020)…
Locking [dev-packages] dependencies…
✔ Success! 
Locking [packages] dependencies…
✘ Locking Failed! 
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.7/site-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches appnode
[pipenv.exceptions.ResolutionFailure]:       No versions found
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches appnode
No versions found
Was https://pypi.org/simple reachable?
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/usr/local/lib/python3.7/site-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches appnode
[pipenv.exceptions.ResolutionFailure]:       No versions found
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches appnode
No versions found
Was https://pypi.org/simple reachable?

`
