### ISSUE TITLE
pipenv check fails when pip 10 is installed

### ISSUE THREAD

**Issue by rodxavier** [pypa/pipenv#2007]
`pipenv check` fails with an error when pip 10.0.0 is installed.

    An error occurred:
    Traceback (most recent call last):
      File "/var/go/.pyenv/versions/3.6.3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
      File "/var/go/.pyenv/versions/3.6.3/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
      File "/var/go/.pyenv/versions/3.6.3/lib/python3.6/site-•
      packages/pipenv/patched/safety.zip/__main__.py", line 8, in <module>
      File "/var/go/.pyenv/versions/3.6.3/lib/python3.6/site-•
      packages/pipenv/patched/safety.zip/click/core.py", line 722, in __call__
      File "/var/go/.pyenv/versions/3.6.3/lib/python3.6/site-•
      packages/pipenv/patched/safety.zip/click/core.py", line 697, in main
      File "/var/go/.pyenv/versions/3.6.3/lib/python3.6/site-•
      packages/pipenv/patched/safety.zip/click/core.py", line 1066, in invoke
      File "/var/go/.pyenv/versions/3.6.3/lib/python3.6/site-•
      packages/pipenv/patched/safety.zip/click/core.py", line 895, in invoke
      File "/var/go/.pyenv/versions/3.6.3/lib/python3.6/site-•
      packages/pipenv/patched/safety.zip/click/core.py", line 535, in invoke
      File "/var/go/.pyenv/versions/3.6.3/lib/python3.6/site-•
      packages/pipenv/patched/safety.zip/safety/cli.py", line 52, in check
      AttributeError: module 'pip' has no attribute 'get_installed_distributions'

**Comment by uranusjr** [comment]
#1996. Please read the issue template and fill it. Specifically, please look for existing issues before hitting that submit button.
