### ISSUE TITLE
Can't install ldap or python-ldap: AssertionError: No source dir

### ISSUE THREAD

**Issue by mtdeguzis** [pypa/pipenv#2012]
Cannot seem to get ldap installed now. I have been using the same pipfile for a while now on the same system.  python-devel and openldap-devel are installed already.
------------

##### Expected result

Installs ldap / python-ldap.

##### Actual result

```
$ pipenv install git+https://github.com/python-ldap/python-ldap.git#egg=python-ldap
Creating a virtualenv for this project…
Using /usr/bin/python2.7 to create virtualenv…
⠋Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/mtdeguzis/.local/share/virtualenvs/pipenv-testing-HrGvjtr7/bin/python2.7
Also creating executable in /home/mtdeguzis/.local/share/virtualenvs/pipenv-testing-HrGvjtr7/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /home/mtdeguzis/.local/share/virtualenvs/pipenv-testing-HrGvjtr7
Installing git+https://github.com/python-ldap/python-ldap.git#egg=python-ldap…
⠇Warning: You installed a VCS dependency in non–editable mode. This will work fine, but sub-dependencies will not be resolved by $ pipenv lock.
  To enable this sub–dependency functionality, specify that this dependency is editable.
Collecting python-ldap from git+https://github.com/python-ldap/python-ldap.git#egg=python-ldap
  Cloning https://github.com/python-ldap/python-ldap.git to /tmp/pip-install-ACKPlp/python-ldap
Collecting pyasn1>=0.3.7 (from python-ldap)
  Using cached https://files.pythonhosted.org/packages/ba/fe/02e3e2ee243966b143657fb8bd6bc97595841163b6d8c26820944acaec4d/pyasn1-0.4.2-py2.py3-none-any.whl
Collecting pyasn1_modules>=0.1.5 (from python-ldap)
  Using cached https://files.pythonhosted.org/packages/e9/51/bcd96bf6231d4b2cc5e023c511bee86637ba375c44a6f9d1b4b7ad1ce4b9/pyasn1_modules-0.2.1-py2.py3-none-any.whl
Building wheels for collected packages: python-ldap
  Running setup.py bdist_wheel for python-ldap: started
  Running setup.py bdist_wheel for python-ldap: finished with status 'done'
  Stored in directory: /tmp/pip-ephem-wheel-cache-5Wrd3A/wheels/6f/5c/c6/a0219e062798e7ff50a21e2b694f90375f2e6b526f9f79cbd5
Successfully built python-ldap
Installing collected packages: pyasn1, pyasn1-modules, python-ldap
Successfully installed pyasn1-0.4.2 pyasn1-modules-0.2.1 python-ldap-3.0.0

Adding git+https://github.com/python-ldap/python-ldap.git#egg=python-ldap to Pipfile's [packages]…
Pipfile.lock (54367d) out of date, updating to (f5d00e)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (f5d00e)!
Installing dependencies from Pipfile.lock (f5d00e)…
An error occurred while installing git+https://github.com/python-ldap/python-ldap.git#egg=python-ldap! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:03
Installing initially–failed dependencies…
Requirement already satisfied: python-ldap from git+https://github.com/python-ldap/python-ldap.git#egg=python-ldap in /home/mtdeguzis/.local/share/virtualenvs/pipenv-testing-HrGvjtr7/lib/python2.7/site-packages (3.0.0)
Requirement already satisfied: pyasn1>=0.3.7 in /home/mtdeguzis/.local/share/virtualenvs/pipenv-testing-HrGvjtr7/lib/python2.7/site-packages (from python-ldap) (0.4.2)
Requirement already satisfied: pyasn1-modules>=0.1.5 in /home/mtdeguzis/.local/share/virtualenvs/pipenv-testing-HrGvjtr7/lib/python2.7/site-packages (from python-ldap) (0.2.1)
Building wheels for collected packages: python-ldap

Exception:
Traceback (most recent call last):
  File "/home/mtdeguzis/.local/share/virtualenvs/pipenv-testing-HrGvjtr7/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/home/mtdeguzis/.local/share/virtualenvs/pipenv-testing-HrGvjtr7/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 305, in run
    session=session, autobuilding=True
  File "/home/mtdeguzis/.local/share/virtualenvs/pipenv-testing-HrGvjtr7/lib/python2.7/site-packages/pip/_internal/wheel.py", line 773, in build
    python_tag=python_tag,
  File "/home/mtdeguzis/.local/share/virtualenvs/pipenv-testing-HrGvjtr7/lib/python2.7/site-packages/pip/_internal/wheel.py", line 633, in _build_one
    python_tag=python_tag)
  File "/home/mtdeguzis/.local/share/virtualenvs/pipenv-testing-HrGvjtr7/lib/python2.7/site-packages/pip/_internal/wheel.py", line 637, in _build_one_inside_env
    if self.__build_one(req, temp_dir.path, python_tag=python_tag):
  File "/home/mtdeguzis/.local/share/virtualenvs/pipenv-testing-HrGvjtr7/lib/python2.7/site-packages/pip/_internal/wheel.py", line 663, in __build_one
    base_args = self._base_setup_args(req)
  File "/home/mtdeguzis/.local/share/virtualenvs/pipenv-testing-HrGvjtr7/lib/python2.7/site-packages/pip/_internal/wheel.py", line 659, in _base_setup_args
    SETUPTOOLS_SHIM % req.setup_py
  File "/home/mtdeguzis/.local/share/virtualenvs/pipenv-testing-HrGvjtr7/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 415, in setup_py
    assert self.source_dir, "No source dir for %s" % self
AssertionError: No source dir for python-ldap from git+https://github.com/python-ldap/python-ldap.git#egg=python-ldap in /home/mtdeguzis/.local/share/virtualenvs/pipenv-testing-HrGvjtr7/lib/python2.7/site-packages

  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:00
```

##### Steps to replicate

Pipfile:

```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]

python-ldap = {git = "https://github.com/python-ldap/python-ldap.git"}

[requires]

python_version = "2.7"
```

**Comment by mtdeguzis** [comment]
Do you know what version this will be on https://pypi.org/project/pipenv/#history ?

**Comment by uranusjr** [comment]
@mtdeguzis This is a pip issue, not Pipenv. There won’t be an entry in Pipenv’s history.
