### ISSUE TITLE
`pipenv check` fails on 11.10.1.dev1 version

### ISSUE THREAD

**Issue by Gr1N** [pypa/pipenv#2037]
`pipenv check` fails on `11.10.1.dev1` version

------------

##### Expected result

No exceptions in output.

##### Actual result

```
$ pipenv check
Checking PEP 508 requirements…
Passed!
Checking installed package safety…
An error occurred:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/safety.zip/__main__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/safety.zip/safety/cli.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/safety.zip/safety/util.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/safety.zip/dparse/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/safety.zip/dparse/parser.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/safety.zip/yaml/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/safety.zip/yaml/yaml3/__init__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/safety.zip/yaml/yaml3/cyaml.py", line 5, in <module>
  File "ext/_yaml.pyx", line 18, in init _yaml (ext/_yaml.c:23185)
AttributeError: module 'yaml' has no attribute 'error'
```

##### Steps to replicate

Install latest dev version `11.10.1.dev1` and run `pipenv check` on project.

**Comment by techalchemy** [comment]
Awesome. Thanks for testing!

**Comment by techalchemy** [comment]
(Not awesome that there’s a bug but awesome that you caught it!)

**Comment by techalchemy** [comment]
@Gr1N I probably didn't solve the problem but the error message may be more helpful if you `pip install --upgrade --pre pipenv` now

**Comment by Gr1N** [comment]
@techalchemy problem looks solved:
```
$ pipenv --version
pipenv, version 11.10.1.dev2
$ pipenv check
Checking PEP 508 requirements…
Passed!
Checking installed package safety…
All good!
```
