### ISSUE TITLE
`pipenv install` fails on v11.10.1.dev[1-4] in docker

### ISSUE THREAD

**Issue by michael-k** [pypa/pipenv#2044]
If there's no or an outdated Pipfile.lock  `pipenv install --system` fails during docker build with a TypeError.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.1.dev4'`

Pipenv location: `'/usr/local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/usr/bin/python3.5`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `3.6.5`: `/usr/local/bin/python`
  - `3.6.5`: `/usr/local/bin/python`
  - `2.7.13`: `/usr/bin/python`
  - `2.7.13`: `/usr/bin/python2`
  - `3.6.5`: `/usr/local/bin/python3`
  - `3.6.5`: `/usr/local/bin/python3`
  - `3.5.3`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-2-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Debian 4.15.11-1 (2018-03-20)',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `HOSTNAME`
  - `PYTHON_PIP_VERSION`
  - `HOME`
  - `GPG_KEY`
  - `PIPENV_VERSION`
  - `PATH`
  - `LANG`
  - `PYTHON_VERSION`
  - `PWD`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

 - `PIPENV_VERSION`: `v11.10.1.dev4`

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/code`

---------------------------

Contents of `Pipfile` ('/code/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
requests = "*"

[dev-packages]

[requires]
python_version = "3.6"

```

</details>

------------

##### Expected result

`pipenv install --system` installs packages.

##### Actual result

`pipenv install --system` fails with a TypeError:

```
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 402, in install
    selective_upgrade=selective_upgrade,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1902, in do_install
    requirements_dir=requirements_directory,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1340, in do_init
    verbose=verbose,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1038, in do_lock
    allow_global=system,
  File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 408, in venv_resolve_deps
    escape_grouped_arguments(which('python')),
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 126, in which
    p = os.sep.join([location] + ['bin/{0}'.format(command)])
TypeError: sequence item 0: expected str instance, NoneType found
```

Same happens if a `Pipfile.lock` exists:

```
Pipfile.lock (b6f97a) out of date, updating to (8e0064)…
Locking [dev-packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 402, in install
    selective_upgrade=selective_upgrade,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1902, in do_install
    requirements_dir=requirements_directory,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1329, in do_init
    do_lock(system=system, pre=pre, keep_outdated=keep_outdated)
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1038, in do_lock
    allow_global=system,
  File "/usr/local/lib/python3.6/site-packages/pipenv/utils.py", line 408, in venv_resolve_deps
    escape_grouped_arguments(which('python')),
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 126, in which
    p = os.sep.join([location] + ['bin/{0}'.format(command)])
TypeError: sequence item 0: expected str instance, NoneType found
```

##### Steps to replicate

Create a Dockerfile and a Pipfile in a new directory with the following content:

```Dockerfile
FROM python:3.6-stretch
ARG PIPENV_VERSION
RUN mkdir -p /code

RUN pip install "pipenv==${PIPENV_VERSION}"
# RUN pip install "git+https://github.com/pypa/pipenv.git@master#egg=pipenv"

WORKDIR /code
COPY Pipfile* /code/
RUN python -m pipenv.help && ls -l && pipenv install --system --verbose
```

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]
requests = "*"


[dev-packages]
pytest = "*"


[requires]
python_version = "3.6"
```

Run `docker build --build-arg PIPENV_VERSION="v11.10.1.dev4" .`  (Same for dev1, dev2, and dev3).
To try it with the latest commit in pypa/pipenv@master, use the commented out line in the Dockerfile instead.

To try it with a `Pipfile.lock` you can use the one from the [documentation](https://docs.pipenv.org/basics/#example-pipfile-lock).

**Comment by uranusjr** [comment]
This looks like a variant to the old `/bin/python` not found thing, just a tiny bit more explicit. The root cause is the failure to locate `python`.

**Comment by michael-k** [comment]
FYI: WIth `v11.10.0`:

```
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…

/bin/sh: 1: /bin/python: not found
```

If I add `RUN ln -s /usr/local/bin/python /bin/python` after `COPY`, it works with `v11.10.0`, but not with `v11.10.1.dev4`.

**Comment by michael-k** [comment]
It works. (Although it would be nice to skip the virtualenv in docker containers.)

## for anyone else running into this

Here's a working example (with the Pipfile from above).  Maybe it helps someone else.

```Dockerfile
FROM python:3.6-stretch

ARG PIPENV_VERSION

RUN mkdir -p /code

RUN pip install "pipenv==${PIPENV_VERSION}"

WORKDIR /code

COPY Pipfile* /code/

RUN ls -l \
	&& if test ! -f Pipfile.lock; then \
		pipenv lock; \
	fi \
	&& pipenv install --system
```

`docker build --tag my-project:latest --build-arg PIPENV_VERSION="v11.10.1.dev5" .`

- If Pipfile.lock existed and was up to date: ✔
- If Pipfile.lock existed, but was out of date: pipenv did not update Pipfile.lock.¹  Use the following code to catch up on that:
    ```bash
    # The --volume option makes sure the Pipfile.lock in the local filesystem is updated.
    docker run --rm --volume $(pwd)/Pipfile.lock:/code/Pipfile.lock --entrypoint pipenv my-project:latest lock
    ```
- If Pipfile.lock was missing:  The Pipfile.lock exists now, but only in the image.  Use the following code to copy it to the local filesystem.
    ```bash
    # Start a container; it will exit immediately with the Dockerfile from above,
    # but we do not care.
    docker run --name myproj my-project:latest

    # Copy the Pipfile.lock from the container to the local filesystem.
    docker cp myproj:/code/Pipfile.lock .

    # Get rid of the container.  We only needed it to get the Pipfile.lock.
    docker rm myproj
    ```

Note that the last `RUN` command in the Dockerfile is not what you should use in production.  (Eg. the virtualenv in part of your docker image.)
- Use it to get started with an initial Pipfile.lock (if you don't want to run pipenv on your local machine).  The consider checking PIpfile.lock into git/hg/… and change the `RUN` command as follows: `RUN pipenv install --system --deploy`.
- If you want to update the Pipfile, make sure that an image of your Dockerfile is available (if not, run `docker build` first), then change the Pipfile and run something like `docker run --rm --volume $(pwd)/Pipfile.lock:/code/Pipfile.lock --entrypoint pipenv my-project:latest lock`


¹  Pipfile.lock (b6f97a) out of date, but installation uses --system... re-building lockfile must happen in isolation. Please rebuild lockfile in a virtualenv. Continuing anyway...
