### ISSUE TITLE
TOML parsing can't handle [packages."discord.py"]

### ISSUE THREAD

**Issue by greysteil** [pypa/pipenv#2062]
Pipenv cannot install the following (valid) Pipfile:
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages."discord.py"]
git = "https://github.com/Rapptz/discord.py.git"
```

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.0'`

Pipenv location: `'/usr/local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.6`: `/usr/bin/python2.6`
  - `2.6`: `/usr/bin/python2.6`
  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `3.6.5`: `/usr/local/bin/python`
  - `3.6.5`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `3.6.5`: `/usr/local/bin/python3`
  - `3.6.5`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '16.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT '
                     '2017; root:xnu-3789.71.6~1/RELEASE_X86_64',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_PROGRAM`
  - `TERM`
  - `SHELL`
  - `CLICOLOR`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `LSCOLORS`
  - `PATH`
  - `PWD`
  - `EDITOR`
  - `LANG`
  - `XPC_FLAGS`
  - `RBENV_SHELL`
  - `XPC_SERVICE_NAME`
  - `HOME`
  - `SHLVL`
  - `LOGNAME`
  - `OLDPWD`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONUNBUFFERED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/greysteil/.cargo/bin:/usr/local/heroku/bin:/Users/greysteil/.rbenv/shims:/usr/local/bin:./node_modules/.bin:.bundle/binstubs:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Library/TeX/texbin:/usr/local/sbin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `subl -w`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/Users/greysteil/code/python-test`

---------------------------

Contents of `Pipfile` ('/Users/greysteil/code/python-test/Pipfile'):

```toml

[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[packages."discord.py"]
git = "https://github.com/Rapptz/discord.py.git"

```

</details>

------------

##### Expected result

Successful install

##### Actual result

```
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/11.10.0/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.10.0', 'console_scripts', 'pipenv')()
  File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/cli.py", line 366, in install
    selective_upgrade=selective_upgrade,
  File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/core.py", line 1730, in do_install
    skip_requirements=skip_requirements,
  File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/core.py", line 608, in ensure_project
    if project.required_python_version:
  File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/project.py", line 180, in required_python_version
    required = self.parsed_pipfile.get('requires', {}).get(
  File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/project.py", line 378, in parsed_pipfile
    parsed = self._parse_pipfile(contents)
  File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/project.py", line 409, in _parse_pipfile
    return contoml.loads(toml.dumps(data, preserve=True))
  File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/patched/contoml/__init__.py", line 15, in loads
    elements = parse_tokens(tokens)
  File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/patched/prettytoml/parser/__init__.py", line 17, in parse_tokens
    return _parse_token_stream(TokenStream(tokens))
  File "/usr/local/Cellar/pipenv/11.10.0/libexec/lib/python3.6/site-packages/pipenv/patched/prettytoml/parser/__init__.py", line 32, in _parse_token_stream
    raise ParsingError('Failed to parse line {}'.format(pending.head.row))
prettytoml.parser.errors.ParsingError: Failed to parse line 6
```

##### Steps to replicate

`pipenv install` on the above Pipfile

**Comment by greysteil** [comment]
Ah, I can see this is a dupe of https://github.com/pypa/pipenv/issues/1519. I'll close, as it's already been marked as low priority.

**Comment by techalchemy** [comment]
@greysteil we use a modified toml format (I wasn’t involved in the decision making behind this but we are too far down the road to undo it anyway— best we could hope for is supporting regular toml too someday)

Basically you should conform to our format which looks like this:

```
[packages]
“discord.py” = {git = “https://github.com/Rapptz/discord.py.git”}
```

**Comment by uranusjr** [comment]
Python really needs a TOML library that *actually works*.

**Comment by techalchemy** [comment]
I believe @frostming is the resident toml expert, he has a full python implementation I'm willing to bet works pretty well ;)

**Comment by techalchemy** [comment]
Do note we have made changes to contoml and prettytoml (see `tasks/vendoring/patches`)

**Comment by greysteil** [comment]
👍 - dug into this and created https://github.com/pypa/pipenv/pull/2067, which is an improvement but not a fix.

**Comment by uranusjr** [comment]
Hmm, wait a minute, this actually works with ConTOML vendored in master. Many it’s fixed during the vendor update?

**Comment by greysteil** [comment]
That's entirely possible - I couldn't get master running locally so tested my changes off of 11.10.0. If so, 🎉.

**Comment by techalchemy** [comment]
@greysteil why couldn’t you get master running

**Comment by greysteil** [comment]
Some kind of install issue / me being stupid. I get the following when I try to `pipenv install` anything with it:

```
from .pypi import PyPIRepository
  File "/Users/greysteil/code/pipenv/pipenv/patched/piptools/repositories/pypi.py", line 11, in <module>
    from notpip.index import PackageFinder
  File "/Users/greysteil/code/pipenv/pipenv/patched/notpip/index.py", line 33, in <module>
    from notpip._vendor import html5lib, requests, six
  File "/Users/greysteil/code/pipenv/pipenv/patched/notpip/_vendor/requests/__init__.py", line 98, in <module>
    from . import packages
  File "/Users/greysteil/code/pipenv/pipenv/patched/notpip/_vendor/requests/packages.py", line 8, in <module>
    locals()[package] = __import__(vendored_package)
ModuleNotFoundError: No module named 'pip._vendor.urllib3'
```

**Comment by techalchemy** [comment]
Oh. If that’s current master that’s a problem — did you `pip install -e`?

**Comment by greysteil** [comment]
I did - I went through each of the install steps in the `.travis.yml`.

**Comment by frostming** [comment]
I saw the exactly same error this morning but it was gone after I upgraded my pip. You can have a try.

**Comment by greysteil** [comment]
No joy I'm afraid - I'm already on `10.0.1`.

**Comment by techalchemy** [comment]
@greysteil latest version should fix this. Good catch. Meant to respond but got caught up in a few other things

**Comment by greysteil** [comment]
Yep, works perfectly - thanks for the release!
