### ISSUE TITLE
ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-byK6xR-requirements'>

### ISSUE THREAD

**Issue by oucb** [pypa/pipenv#2066]
create a virtualenv with `pipenv install`
pipenv version: 11.10.0
system: ubuntu16.04
python version: 2.7.12

solved it by uninstall pipenv and install pipenv==10.0.1 
------------

##### Expected result

Creating a virtualenv for this project…

##### Actual result

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/cli.py", line 366, in install
    selective_upgrade=selective_upgrade,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/core.py", line 1730, in do_install
    skip_requirements=skip_requirements,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/core.py", line 604, in ensure_project
    three=three, python=python, site_packages=site_packages
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/core.py", line 537, in ensure_virtualenv
    if not project.virtualenv_exists:
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/project.py", line 207, in virtualenv_exists
    if self.pipfile_exists and os.path.exists(self.virtualenv_location):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/project.py", line 299, in virtualenv_location
    loc = self._get_virtualenv_location(self.virtualenv_name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/project.py", line 220, in _get_virtualenv_location
    from pipenv.patched.pew.pew import get_workon_home
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/patched/pew/__init__.py", line 1, in <module>
    from . import pew
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/patched/pew/pew.py", line 44, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/patched/pew/__init__.py", line 1, in <module>
    from . import pew
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/patched/pew/pew.py", line 44, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/patched/pew/_utils.py", line 23, in <module>
    locale.setlocale(locale.LC_CTYPE, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
/home/ubuntu/.local/lib/python2.7/site-packages/pipenv/utils.py:1258: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-byK6xR-requirements'>
  warnings.warn(warn_message, ResourceWarning)
```

**Comment by uranusjr** [comment]
Do you have `LC_ALL` and related locale environment variables set? It seems that Pipenv wants to print a warning (the `ResourceWarning` part), but an exception prevented it from doing so.

**Comment by techalchemy** [comment]
3 things:

1. Your locale is not set, you need to set it to something unicode compatible, this is a bare minimum for using python on linux
2. Using the system python on ubuntu 16.04 when choosing python 2.7 is problematic, the virtualenv implementation it installs is broken, you should install pyenv or use python 3.
3. This is not an error message that needs to be solved, it's a warning. Like it says.

Also note that there is an issue template, please follow the instructions in the future.

**Comment by techalchemy** [comment]
P.S. Sorry you ran into this, I know it's annoying. Seriously. But the issue template is there for a reason. It helps us help you.

**Comment by oucb** [comment]
@uranusjr  I just set `LANG`, after set `LC_ALL` and `LC_CTYPE`, it works well, thank you!

**Comment by oucb** [comment]
@techalchemy I just forget to set `LC_ALL` and `LC_CTYPE`, after set them, reinstall pipenv11.10.0, it works. thanks!
