### ISSUE TITLE
Actively warn users about misconfigured locale

### ISSUE THREAD

**Issue by uranusjr** [pypa/pipenv#2092]
Things I’d like to do:

* [ ] Make `python_version` fail much more loudly (with an explicit exception) so we don’t end up with obscure errors like #538.
* [ ] Find out what is producing the incorrect `/bin/python` path (probably because the prefix is an empty string), and make that fail more loudly.
* [ ] Catch those loud exceptions produced above (probably incrementally) to print a better error message so users know how to resolve it themselves.
* [ ] Catch the `ValueError: unknown locale` exception from `locale.getlocale()` (probably by patching Pew) to fallback to ASCII.

**Comment by fluffy-critter** [comment]
I recently ran into this problem with an application deployed to Dreamhost using Passenger WSGI.

As their wrapper is not configured to work with Pipenv, I use the following `passenger_wsgi.py` (based on [Dreamhost's instructions](https://help.dreamhost.com/hc/en-us/articles/215769548-Passenger-and-Python-WSGI)) to shunt my interpreter over to my pipenv's Python 3.6 and then import my `app` object from `main.py`:

```
import sys
import os
import subprocess

INTERP = subprocess.check_output(
    ['pipenv', 'run', 'which', 'python3']).strip().decode('utf-8')
if sys.executable != INTERP:
    os.execl(INTERP, INTERP, *sys.argv)

sys.path.append(os.getcwd())
from main import app as application
```

This was working for quite some time, but recently either Dreamhost or Pipenv made a change which broke startup:

```
Traceback (most recent call last):
File "/home/plaidfluff/opt/python-3.6.5/bin/pipenv", line 11, in <module>
sys.exit(cli())
File "/home/plaidfluff/opt/python-3.6.5/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/home/plaidfluff/opt/python-3.6.5/lib/python3.6/site-packages/pipenv/vendor/cl ck/core.py", line 676, in main
_verify_python3_env()
File "/home/plaidfluff/opt/python-3.6.5/lib/python3.6/site-packages/pipenv/vendor/click/_unicodefun.py", line 118, in _verify_python3_env
'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult http://click.pocoo.org/python3/for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

export LC_ALL=C.UTF-8
export LANG=C.UTF-8

Traceback (most recent call last):
File "/home/plaidfluff/opt/python-3.6.5/bin/pipenv", line 11, in <module>
sys.exit(cli())
File "/home/plaidfluff/opt/python-3.6.5/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/home/plaidfluff/opt/python-3.6.5/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 676, in main
_verify_python3_env()
File "/home/plaidfluff/opt/python-3.6.5/lib/python3.6/site-packages/pipenv/vendor/click/_unicodefun.py", line 118, in _verify_python3_env
'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult http://click.pocoo.org/python3/for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

export LC_ALL=C.UTF-8
export LANG=C.UTF-8
Traceback (most recent call last):
File "/dh/passenger/helper-scripts/wsgi-loader.py", line 320, in <module>
app_module = load_app()
File "/dh/passenger/helper-scripts/wsgi-loader.py", line 61, in load_app
return imp.load_source('passenger_wsgi', startup_file)
File "passenger_wsgi.py", line 33, in <module>
['pipenv', 'run', 'which', 'python3']).strip().decode('utf-8')
File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['pipenv', 'run', 'which', 'python3']' returned non-zero exit status 1
```

My fix turned out to be adding the following to the top of `passenger_wsgi.py`, as I don't have any control over Passenger's own environment:

```
os.environ['LANG'] = 'C.UTF-8'
os.environ['LC_ALL'] = 'C.UTF-8'
```

I'm not entirely sure this is a *correct* fix but it at least got me up and running again.

**Comment by uranusjr** [comment]
The fix is correct as long as it follows the `<locale>.<encoding>` format. The encoding part should almost always be UTF-8, but the locale can be set to any locale you this is correct (en_US for Americans, ja_JP for Japanese, de_DE for Germans, etc.). The check I’m thinking would simply be detection this and output a helpful message if it finds it is not set correctly.

**Comment by matteius** [comment]
I think this may have been fixed, but totally willing to re-open if still an issue.
