### ISSUE TITLE
pipenv install -e failure

### ISSUE THREAD

**Issue by yrro** [pypa/pipenv#2107]
`pipenv install -e .` fails with the following output:

```
Installing -e .…
⠋Installing '-e .'
⠙$ "/home/sam/.local/share/virtualenvs/nexsan-exporter-Eq5p1XVG/bin/pip" install   --verbose    -e "." -i https://pypi.org/simple --exists-action w
Created temporary directory: /tmp/pip-ephem-wheel-cache-fk4_pry3
Created temporary directory: /tmp/pip-install-ey7tcytz
Cleaning up...
Exception information:
Traceback (most recent call last):
  File "/home/sam/.local/share/virtualenvs/nexsan-exporter-Eq5p1XVG/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/home/sam/.local/share/virtualenvs/nexsan-exporter-Eq5p1XVG/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 267, in run
    self.name, wheel_cache
  File "/home/sam/.local/share/virtualenvs/nexsan-exporter-Eq5p1XVG/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 305, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/home/sam/.local/share/virtualenvs/nexsan-exporter-Eq5p1XVG/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 137, in from_editable
    name, url, extras_override = parse_editable(editable_req)
  File "/home/sam/.local/share/virtualenvs/nexsan-exporter-Eq5p1XVG/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 1046, in parse_editable
    url_no_extras
pip._internal.exceptions.InstallationError: Directory '.' is not installable. File 'setup.py' not found.

Error:  An error occurred while installing -e .!
Directory '.' is not installable. File 'setup.py' not found.
```

I'm trying this with https://github.com/yrro/nexsan-exporter and definitely appreciative of the fact that there is a problem with my project rather than pipenv, nonetheless the error message needs some work; `setup.py` certainly exists!

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.1'`

Pipenv location: `'/home/sam/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`

  - `2.7.15`: `/usr/bin/python`
  - `2.7.15`: `/usr/bin/python2`
  - `3.6.5`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5c1',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-3-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Debian 4.15.17-1 (2018-04-19)',
 'python_full_version': '3.6.5rc1',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LS_COLORS`
  - `LESSCLOSE`
  - `XDG_MENU_PREFIX`
  - `LANG`
  - `GDM_LANG`
  - `MALLOC_PERTURB_`
  - `DISPLAY`
  - `EDITOR`
  - `COLORTERM`
  - `DESKTOP_AUTOSTART_ID`
  - `USERNAME`
  - `XDG_VTNR`
  - `SSH_AUTH_SOCK`
  - `S_COLORS`
  - `LESS_TERMCAP_so`
  - `LESS_TERMCAP_se`
  - `XDG_SESSION_ID`
  - `USER`
  - `DESKTOP_SESSION`
  - `GNOME_TERMINAL_SCREEN`
  - `PWD`
  - `HOME`
  - `SSH_AGENT_PID`
  - `QT_ACCESSIBILITY`
  - `XDG_SESSION_TYPE`
  - `https_proxy`
  - `XDG_DATA_DIRS`
  - `http_proxy`
  - `XDG_SESSION_DESKTOP`
  - `LESS_TERMCAP_mb`
  - `LESS_TERMCAP_md`
  - `LESS_TERMCAP_me`
  - `ENV_TEST_SAM`
  - `no_proxy`
  - `ANSIBLE_NOCOWS`
  - `GTK_MODULES`
  - `NO_PROXY`
  - `VISUAL`
  - `WINDOWPATH`
  - `TERM`
  - `SHELL`
  - `VTE_VERSION`
  - `DEBNAME`
  - `XDG_CURRENT_DESKTOP`
  - `GPG_AGENT_INFO`
  - `GNOME_TERMINAL_SERVICE`
  - `PYTHONSTARTUP`
  - `COLORFGBG`
  - `SHLVL`
  - `XDG_SEAT`
  - `DEBEMAIL`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `LESS_TERMCAP_ue`
  - `LESS_TERMCAP_us`
  - `ANSIBLE_COW_SELECTION`
  - `PATH`
  - `SESSION_MANAGER`
  - `LESSOPEN`
  - `_`
  - `OLDPWD`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/sam/bin:/home/sam/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `vim`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/home/sam/src/nexsan-exporter/nexsan-exporter`

---------------------------

Contents of `Pipfile` ('/home/sam/src/nexsan-exporter/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/home/sam/src/nexsan-exporter/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "415dfdcb118dd9bdfef17671cb7dcd78dbd69b6ae7d4f39e8b44e71d60ca72e7"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>

------------

##### Expected result

Project to be installed into the venv in editable mode.

##### Actual result

Error as above

##### Steps to replicate

Clone https://github.com/yrro/nexsan-exporter and run pipenv install -e .

**Comment by yrro** [comment]
Just noticed that `pipenv.help` refers to `/home/sam/src/nexsan-exporter` which is the parent directory of the direcotry that contains my project. Maybe that's helpful...

**Comment by yrro** [comment]
You're quite right, I don't know how that got created!
