### ISSUE TITLE
pipenv install with existing requirements.txt fails with stack trace

### ISSUE THREAD

**Issue by dangunter** [pypa/pipenv#2125]
Be sure to check the existing issues (both open and closed!).

`pipenv install` with an existing requirements.txt fails with a stack trace.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.1'`

Pipenv location: `'/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/pipenv'`

Python location: `'/home/dang/anaconda3/envs/idaes-dev3/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/opt/anaconda/bin/python3.5m`
  - `3.5`: `/opt/anaconda/bin/python3.5`
  - `3.6`: `/home/dang/anaconda3/envs/idaes-dev3/bin/python3.6m`
  - `3.6`: `/home/dang/anaconda3/envs/idaes-dev3/bin/python3.6`
  - `3.6`: `/home/dang/anaconda3/bin/python3.6`
  - `3.6`: `/usr/bin/python3.6`

  - `3.6.2`: `/home/dang/anaconda3/envs/idaes-dev3/bin/python`
  - `3.6.1`: `/home/dang/anaconda3/bin/python`
  - `3.6.5`: `/usr/bin/python`
  - `3.5.2`: `/opt/anaconda/bin/python`
  - `2.7.14`: `/usr/bin/python2`
  - `3.6.2`: `/home/dang/anaconda3/envs/idaes-dev3/bin/python3`
  - `3.6.1`: `/home/dang/anaconda3/bin/python3`
  - `3.6.5`: `/usr/bin/python3`
  - `3.5.2`: `/opt/anaconda/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.16.3-1-ARCH',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Thu Apr 19 09:17:56 UTC 2018',
 'python_full_version': '3.6.2',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `CONDA_SHLVL`
  - `GS_LIB`
  - `KDE_FULL_SESSION`
  - `CONDA_EXE`
  - `CLOUDSDK_PYTHON`
  - `LANG`
  - `GOOGLE_CLOUD_SDK_HOME`
  - `DISPLAY`
  - `OLDPWD`
  - `QT_SCREEN_SCALE_FACTORS`
  - `MOZ_PLUGIN_PATH`
  - `CONDA_PREFIX`
  - `CADENCE_AUTO_STARTED`
  - `XDG_VTNR`
  - `PAM_KWALLET5_LOGIN`
  - `SSH_AUTH_SOCK`
  - `DSSI_PATH`
  - `HG`
  - `XDG_SESSION_ID`
  - `USER`
  - `DESKTOP_SESSION`
  - `PWD`
  - `HOME`
  - `GITHUB_USER`
  - `CONDA_PYTHON_EXE`
  - `LC_CTYPE`
  - `SSH_AGENT_PID`
  - `XCURSOR_SIZE`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `XDG_SESSION_DESKTOP`
  - `CLOUDSDK_ROOT_DIR`
  - `LADSPA_PATH`
  - `CONDA_PROMPT_MODIFIER`
  - `GTK_MODULES`
  - `MAIL`
  - `LV2_PATH`
  - `VISUAL`
  - `TERM`
  - `SHELL`
  - `XDG_SESSION_CLASS`
  - `XDG_SEAT_PATH`
  - `XCURSOR_THEME`
  - `GITHUB_PASSWORD`
  - `VST_PATH`
  - `XDG_CURRENT_DESKTOP`
  - `ROXTERM_NUM`
  - `SHLVL`
  - `XDG_SEAT`
  - `WINDOWID`
  - `ROXTERM_ID`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `ROXTERM_PID`
  - `ANT_HOME`
  - `XDG_SESSION_PATH`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `PATH`
  - `KDE_SESSION_UID`
  - `PS1`
  - `KDE_SESSION_VERSION`
  - `KDED_STARTED_BY_KDEINIT`
  - `CONDA_DEFAULT_ENV`
  - `CLOUDSDK_PYTHON_ARGS`
  - `SESSION_MANAGER`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/dang/anaconda3/envs/idaes-dev3/bin:/home/dang/.yarn/bin:/home/dang/.config/yarn/global/node_modules/.bin:/home/dang/anaconda3/bin:/home/dang/local/pycharm/bin:/opt/google-cloud-sdk/bin:/opt/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/anaconda/bin:/home/dang/bin:/home/dang/bin/imagemagick`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/dang/src/idaes/dangunter/idaes`

---------------------------

Contents of `Pipfile` ('/home/dang/src/idaes/dangunter/idaes/Pipfile'):

```toml

```

</details>

##### Expected result

Installation of the Python package in the current directory.

##### Actual result

Stack trace.

````
Creating a virtualenv for this project…
Using /home/dang/anaconda3/envs/idaes-dev3/bin/python (3.6.2) to create virtualenv…
⠋Already using interpreter /home/dang/anaconda3/envs/idaes-dev3/bin/python
Using base prefix '/home/dang/anaconda3/envs/idaes-dev3'
New python executable in /home/dang/.local/share/virtualenvs/idaes-Kqcjy-GI/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /home/dang/.local/sh...-Kqcjy-GI/bin/python - setuptools pip wheel:
  Exception:
Traceback (most recent call last):
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/commands/install.py", line 272, in run
    with self._build_session(options) as session:
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 69, in user_agent
    "python": platform.python_version(),
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/platform.py", line 1244, in python_version
    return _sys_version()[1]
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/platform.py", line 1192, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.6.5 (default, Apr 14 2018, 13:17:30) \n[GCC 7.3.1 20180406]'
Traceback (most recent call last):
  File "<stdin>", line 23, in <module>
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/__init__.py", line 233, in main
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/basecommand.py", line 251, in main
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/basecommand.py", line 72, in _build_session
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 329, in __init__
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 69, in user_agent
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/platform.py", line 1244, in python_version
    return _sys_version()[1]
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/platform.py", line 1192, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.6.5 (default, Apr 14 2018, 13:17:30) \n[GCC 7.3.1 20180406]'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/dang/.local/sh...-Kqcjy-GI/bin/python - setuptools pip wheel failed with error code 1

Virtualenv location: 
requirements.txt found, instead of Pipfile! Converting…
Traceback (most recent call last):
  File "/home/dang/anaconda3/envs/idaes-dev3/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/pipenv/cli.py", line 402, in install
    selective_upgrade=selective_upgrade,
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/pipenv/core.py", line 1787, in do_install
    skip_requirements=skip_requirements,
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/pipenv/core.py", line 648, in ensure_project
    ensure_pipfile(validate=validate, skip_requirements=skip_requirements, system=system)
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/pipenv/core.py", line 279, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/pipenv/project.py", line 588, in create_pipfile
    required_python = self.which('python')
  File "/home/dang/anaconda3/envs/idaes-dev3/lib/python3.6/site-packages/pipenv/core.py", line 126, in which
    p = os.sep.join([location] + ['bin/{0}'.format(command)])
TypeError: sequence item 0: expected str instance, NoneType found
```
##### Steps to replicate

Command run was `pipenv install`. Was working in a Python 3.6 Conda environment.

The requirements.txt file follows.

```
# general
alabaster>=0.7.7
bunch
codecov
jupyter
networkx
#pyomo
pytest
pytest-cov
snowballstemmer==1.2.1
# Need Sphinx >=1.74 due to bug #4897
# See: https://github.com/sphinx-doc/sphinx/issues/4897
Sphinx>=1.7.4
sphinx-rtd-theme>=0.1.9
sphinxcontrib-napoleon>=0.5.0
tox
# DMF
backports.tempfile
flake8
flask>=1.0
flask-bower
flask-restful
lxml
mock
pandas==0.19.2
pendulum
psutil
pyyaml
# For ALAMO examples
numpy
scipy
tinydb
traitlets

# ****** NEED TO ADD THIS SOMEWHERE
# Used for testing: geckodriver
# https://github.com/mozilla/geckodriver/releases
# Used for testing: pytest-selenium

# dev version of pyomo
# https://software.sandia.gov/svn/public/pyomo/pyomo/trunk
git+https://github.com/pyomo/pyomo.git@IDAES
git+https://github.com/PyUtilib/pyutilib
bokeh==0.12.9
```

**Comment by techalchemy** [comment]
This will be fixed in the next release

as a sidenote you should use `-e` in front of VCS repositories from github if you want them to have hteir dependencies resolved

**Comment by mcintyre94** [comment]
@techalchemy sorry to poke a closed issue, but do you have an ETA for that next release? :)

**Comment by techalchemy** [comment]
yep, we are wrapping things up now -- just finalizing tests / changelog / closing out some encoding issues but most changes have been merged that are going to be merged so this should be finished today or tomorrow.  I feel like I've said that before but the code is actually done being worked on
