### ISSUE TITLE
Show error when installing dependency fails?

### ISSUE THREAD

**Issue by sid-kap** [pypa/pipenv#2149]
A package that I included in my `Pipfile` failed to install when I ran `pipenv install`, so pipenv failed with the message
```
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in <source directory>
```
Would it be a good idea for pipenv to show more information when the install fails (possibly behind the `--verbose` flag)?

(By the way, I'm getting this error with a local dependency—not sure if that makes a difference.)

**Comment by techalchemy** [comment]
Please include the full output including the command you ran and the content of your Pipfile. Including the output of `python -m pipenv.help`. Basically please fill out the issue template.

**Comment by sid-kap** [comment]
Command and output:
```
$ pipenv install                                                                                                                                                                                                                                                                                                                                        
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/bin/.pipenv-wrapped", line 12, in <module>
    sys.exit(cli())
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/cli.py", line 1865, in install
    do_init(dev=dev, allow_global=system, ignore_pipfile=ignore_pipfile, system=system, skip_lock=skip_lock, verbose=verbose, concurrent=concurrent, deploy=deploy, pre=pre)
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/cli.py", line 1311, in do_init
    do_lock(system=system, pre=pre)
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/cli.py", line 1102, in do_lock
    pre=pre
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/utils.py", line 545, in resolve_deps
    resolved_tree = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/utils.py", line 507, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 274, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 523, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/nix/store/g1xwr6fl9b60qdk89hnkfmaswrnp3gxn-pipenv-9.0.1/lib/python3.6/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /home/sidharth/clones/Fiona/
```

Pipfile:
```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]

Fiona = {path = "../Fiona/", editable = true}

[dev-packages]
```

**Comment by sid-kap** [comment]
@techalchemy I'm on version 9.0.1. which doesn't seem to have a `help.py` submodule.

**Comment by uranusjr** [comment]
@sid-kap Do you consider upgrading

**Comment by sid-kap** [comment]
No, because I'm not in control of the version on pipenv that my OS provides.

This seems really irrelevant—I pointed out a general problem with the pipenv output that I'm pretty sure affects all versions. Why does this pipenv.help matter so much?

**Comment by uranusjr** [comment]
I’m not thinking about help specifically, but more confused that how we implementing something would help your usage if you are stuck on an older version and not upgrading…

**Comment by techalchemy** [comment]
Seems like the directory in question doesn’t have a `setup.py` — not sure why you expect support if you won’t upgrade though. Also not sure how you can generalize about it’s impact across all versions...

**Comment by sid-kap** [comment]
@techalchemy I was just asking a question! Not asking for support! If someone pointed out that this changed in a newer version, I would be happy to upgrade. Still no one has made a single comment that's relevant to my question—would it be a good idea for pipenv to show detailed error information from pip during installation.

The directory in question (`/home/sidharth/clones/Fiona`) does have a `setup.py`.

**Comment by techalchemy** [comment]
We don't support versions that are not being supported.

We do rolling releases.  We don't go back and update old things.  Considering you haven't updated even to the latest patch release in the 9.0 series, i'm not even sure what support you would want...

**Comment by sid-kap** [comment]
@techalchemy which versions are supported? I don't see this written in the readme or the doc website.

Anyway, once again this is not a support request! This is a feature suggestion! I'm not asking anyone to go back and update old things. I made no indication that I'm unwilling to update my to new patches. I simply referred to an older version because that's what I have installed on my computer. Again, if someone was kind enough to point out that this is fixed in a newer version, I would consider updating.

If you know anything about my question (i.e. is this behavior the same in all versions) I would appreciate if you told me that. If not, just kindly say "I don't know, maybe it's fixed on a new version, please go ahead and try yourself". Why are all you guys' responses so cryptic?

**Comment by techalchemy** [comment]
None of us use old versions of our own tools and we don’t plan to provide support for them so installing them to tell you if we can reproduce your problem just to tell you to upgrade is pointless. The only version we support is the latest one. This is a volunteer project and we are not too full of free time. If you need help, step 1 is install the latest release.

**Comment by sid-kap** [comment]
Let me re-ask my question once again: does the current version of pipenv have a try-catch block around the pip subcommands it invokes, in order to tell the user if (and why) building a dependency failed? If not, would it be helpful to add such an error message to help users?
Notice that the words "support" and "old version" appear nowhere in my question.

**Comment by uranusjr** [comment]
Okay since you said so I’ll just say I don’t know. The code it there for me to trace, but I’m too lazy to look it up.

**Comment by techalchemy** [comment]
Yup, I have no clue what precise things were present in whatever old version you're using, if you want support, install the new version and describe the problem if you encounter it. Thanks for filing this issue and sorry for the frustration.
