### ISSUE TITLE
Clearer errors for Pyupio connection issues 

### ISSUE THREAD

**Issue by djpugh** [pypa/pipenv#2189]
Connection issues to pyup.io could have a clearer error rather than a traceback of what is going on

------------

##### Expected result

Clear error message that there is a connection issue to pyup.io and fail on checking installed package safety

##### Actual result
```
Checking PEP 508 requirements…
Passed!
Checking installed package safety…
An error occurred:
Traceback (most recent call last):
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\packages\urllib3\connection.py", line 142, in _new_conn
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\packages\urllib3\util\connection.py", line 98, in create_connection
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\packages\urllib3\util\connection.py", line 88, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\packages\urllib3\connection.py", line 254, in connect
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\packages\urllib3\connection.py", line 147, in _new_conn
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000023C636F16A0>, 'Connection to pyup.io timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\adapters.py", line 423, in send
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\packages\urllib3\util\retry.py", line 287, in increment
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pyup.io', port=443): Max retries exceeded with url: /api/v1/safety/insecure.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000023C636F16A0>, 'Connection to pyup.io timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\__main__.py", line 8, in <module>
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\click\core.py", line 722, in __call__
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\click\core.py", line 697, in main
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\click\core.py", line 1066, in invoke
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\click\core.py", line 895, in invoke
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\click\core.py", line 535, in invoke
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\safety\cli.py", line 55, in check
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\safety\safety.py", line 127, in check
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\safety\safety.py", line 108, in fetch_database
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\safety\safety.py", line 79, in fetch_database_url
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\api.py", line 70, in get
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\api.py", line 56, in request
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\sessions.py", line 475, in request
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\sessions.py", line 596, in send
  File "c:\\python36\\lib\\site-packages\\pipenv\\patched\\safety.zip\requests\adapters.py", line 479, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='pyup.io', port=443): Max retries exceeded with url: /api/v1/safety/insecure.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000023C636F16A0>, 'Connection to pyup.io timed out. (connect timeout=5)'))
```
##### Steps to replicate
pipenv check when offline/disconnected to the internet (or if pyup.io is down)

**Comment by kennethreitz** [comment]
This is a proper exception for this exceptional case. Thank you for your feedback.
