### ISSUE TITLE
ValueError: On `pipenv lock -r`

### ISSUE THREAD

**Issue by gordio** [pypa/pipenv#2203]
<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.05.18'`
Pipenv location: `'/usr/local/lib/python3.6/site-packages/pipenv'`
Python location: `'/usr/local/opt/python/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`

  - `2.7.10`: `/usr/bin/python`
  - `3.6.5`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT '
                     '2018; root:xnu-4570.51.2~1/RELEASE_X86_64',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `Apple_PubSub_Socket_Render`
  - `HOME`
  - `LC_CTYPE`
  - `LOGNAME`
  - `PATH`
  - `PWD`
  - `SECURITYSESSIONID`
  - `SHELL`
  - `SSH_AUTH_SOCK`
  - `TERM`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `TMPDIR`
  - `TMUX`
  - `TMUX_PANE`
  - `USER`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `SHLVL`
  - `OLDPWD`
  - `PYTHONSTARTUP`
  - `PYTHONDONTWRITEBYTECODE`
  - `BETTER_EXCEPTIONS`
  - `EDITOR`
  - `LESS`
  - `HOMEBREW_AUTO_UPDATE`
  - `HOMEBREW_NO_AUTO_UPDATE`
  - `HOMEBREW_GITHUB_API_TOKEN`
  - `ZSH_MULTILINE`
  - `NMAPDIR`
  - `GOPATH`
  - `STUDIO_JDK`
  - `ANDROID_HOME`
  - `ANDROID_NDK`
  - `ONO_GAC_PREFIX`
  - `JAVA_HOME`
  - `JDK_HOME`
  - `JRE_HOME`
  - `CLASSPATH`
  - `MPLBACKEND`
  - `ITERMPLOT`
  - `ITERMPLOT_LINES`
  - `PS1`
  - `RPS1`
  - `_`
  - `__CF_USER_TEXT_ENCODING`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/opt/llvm/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/sqlite/bin:/Users/gordio/Library/Python/3.6/bin:/usr/local/opt/go/libexec/bin:/Users/gordio/Development/Deps/jdk1.8.0_101.jdk/Contents/Home/bin:/Users/gordio/Development/Deps/android-sdk-macosx/platform-tools:/usr/local/opt/fzf/bin`
  - `SHELL`: `/usr/local/bin/zsh`
  - `EDITOR`: `/usr/local/bin/nvim`
  - `PWD`: `/Users/gordio/Development/myproj `

---------------------------

Contents of `Pipfile` ('/Users/gordio/Development/myproj/Pipfile'):

```toml

```

</details>

------------

##### Expected result

Creating env and install `requirements.txt`…

##### Actual result

```
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli.py", line 543, in lock
    ensure_project(three=three, python=python)
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 620, in ensure_project
    three=three, python=python, site_packages=site_packages
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 553, in ensure_virtualenv
    if not project.virtualenv_exists:
  File "/usr/local/lib/python3.6/site-packages/pipenv/project.py", line 225, in virtualenv_exists
    if self.pipfile_exists and os.path.exists(self.virtualenv_location):
  File "/usr/local/lib/python3.6/site-packages/pipenv/project.py", line 315, in virtualenv_location
    loc = self._get_virtualenv_location(self.virtualenv_name)
  File "/usr/local/lib/python3.6/site-packages/pipenv/project.py", line 238, in _get_virtualenv_location
    from .patched.pew.pew import get_workon_home
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pew/__init__.py", line 3, in <module>
    from . import pew
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pew/pew.py", line 44, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pew/__init__.py", line 3, in <module>
    from . import pew
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pew/pew.py", line 44, in <module>
    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,
  File "/usr/local/lib/python3.6/site-packages/pipenv/patched/pew/_utils.py", line 25, in <module>
    encoding = locale.getlocale()[1] or 'ascii'
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
```

##### Steps to replicate

```
❯pipenv --version
pipenv, version 2018.05.18
```
Run `pipenv lock -r`

**Comment by uranusjr** [comment]
This happens because of an encoding issue in CPython. Python thinks it’s a bug in macOS, but Apple just doesn’t give a f**c about it. [So you need to work around it yourself.](https://docs.pipenv.org/diagnose/#valueerror-unknown-locale-utf-8)
