### ISSUE TITLE
Pipenv lock SSLError

### ISSUE THREAD

**Issue by danieldaeschle** [pypa/pipenv#2216]
In company behind an only HTTP Proxy i get this:
```
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
ython36-32\lib\site-packages\pipenv\vendor\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\users\i01002704\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/certifi/json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\\users\\i01002704\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\pipenv\\resolver.py", line 85, in <module>
    main()
  File "c:\\users\\i01002704\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\pipenv\\resolver.py", line 74, in main
    system=system,
  File "c:\\users\\i01002704\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\pipenv\\resolver.py", line 65, in resolve
    allow_global=system,
  File "c:\users\i01002704\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\utils.py", line 526, in resolve_deps
    timeout=10,
  File "c:\users\i01002704\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\i01002704\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\i01002704\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\i01002704\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/certifi/json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

On this command:
```
pipenv lock
```

I have on my pip.ini
```
[global]
trusted-host = 
	pypi.python.org
	pypi.org
	files.pythonhosted.org
cert = C:/Users/i01002704/Documents/chain.pem
```

And i set the environment variable:
```
REQUESTS_CA_BUNDLE = C:/Users/i01002704/Documents/chain.pem
```

What should i do to fix this?

**Comment by danieldaeschle** [comment]
Now it works, lol. I did nothing.... nvm
