### ISSUE TITLE
Creating virtualenv is failed on mac

### ISSUE THREAD

**Issue by ukisoft** [pypa/pipenv#2297]
Hi there,

I think there is owner problem in my mac using pipenv.
After installing pipenv through brew, I tried to use it, but there is an error;

```
$ pipenv --python 3.6.5
Creating a virtualenv for this project…
Using /usr/local/bin/python3.6m (3.6.5) to create virtualenv…
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 109, in expect_loop
    return self.timeout()
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x10d2fe7b8>
searcher: searcher_re:
    0: EOF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==2018.5.18', 'console_scripts', 'pipenv')()
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/cli.py", line 270, in cli
    three=three, python=python, warn=True, site_packages=site_packages
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/core.py", line 620, in ensure_project
    three=three, python=python, site_packages=site_packages
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/core.py", line 569, in ensure_virtualenv
    do_create_virtualenv(python=python, site_packages=site_packages)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/core.py", line 936, in do_create_virtualenv
    click.echo(crayons.blue(c.out), err=True)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/delegator.py", line 99, in out
    self.__out = self._pexpect_out
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/delegator.py", line 87, in _pexpect_out
    result += self.subprocess.read()
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 441, in read
    self.expect(self.delimiter)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 119, in expect_loop
    return self.timeout(e)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x10d2fe7b8>
searcher: searcher_re:
    0: EOF
<pexpect.popen_spawn.PopenSpawn object at 0x10d2fe7b8>
searcher: searcher_re:
    0: EOF
```

But, using sudo, I can create virtualenv;

```
$ sudo pipenv --python 3.6.5
Password:
Creating a virtualenv for this project…
Using /usr/local/bin/python3.6m (3.6.5) to create virtualenv…
⠋Running virtualenv with interpreter /usr/local/bin/python3.6m
Using base prefix '/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/me/.local/share/virtualenvs/prj-itnUncie/bin/python3.6
Not overwriting existing python script /Users/me/.local/share/virtualenvs/prj-itnUncie/bin/python (you must use /Users/me/.local/share/virtualenvs/prj-itnUncie/bin/python3.6)
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/me/.local/share/virtualenvs/prj-itnUncie
```

I think that making pip-selfcheck.json is not good because it's owner is root.

```
$ ls -l /Users/me/.local/share/virtualenvs/prj-itnUncie/
total 8
drwxr-xr-x  16 me  staff  512  6  3 14:57 bin
drwxr-xr-x   3 me  staff   96  6  3 14:54 include
drwxr-xr-x   3 me  staff   96  6  3 14:54 lib
-rw-r--r--   1 root  staff   61  6  3 14:57 pip-selfcheck.json
```

Or, making activate shell scripts.

```
# after pipenv --python 3.6.5
$ tree /Users/me/.local/share/virtualenvs/prj-itnUncie
/Users/me/.local/share/virtualenvs/prj-itnUncie
├── bin
│   ├── easy_install
│   ├── easy_install-3.6

# after sudo pipenv --python 3.6.5
$ tree /Users/me/.local/share/virtualenvs/prj-itnUncie
/Users/me/.local/share/virtualenvs/prj-itnUncie
├── bin
│   ├── activate
│   ├── activate.csh
│   ├── activate.fish
│   ├── activate_this.py
│   ├── easy_install
│   ├── easy_install-3.6

$ ls -l /Users/me/.local/share/virtualenvs/prj-itnUncie/bin/activate*
-rw-r--r--  1 root  staff  2116  6  3 15:07 /Users/me/.local/share/virtualenvs/prj-itnUncie/bin/activate
-rw-r--r--  1 root  staff  1058  6  3 15:07 /Users/me/.local/share/virtualenvs/prj-itnUncie/bin/activate.csh
-rw-r--r--  1 root  staff  2212  6  3 15:07 /Users/me/.local/share/virtualenvs/prj-itnUncie/bin/activate.fish
-rw-r--r--  1 root  staff  1137  6  3 15:07 /Users/me/.local/share/virtualenvs/prj-itnUncie/bin/activate_this.py
```

Additionally, I changed venv directory to use PIPENV_VENV_IN_PROJECT or WORKON_HOME, this problem is not resolved.

Environments are below;
- Pyenv: 1.2.4
- Pipenv: 2018.5.18
- Homebrew: 1.6.4
- mac os: high sierra 10.13.4

Thank you.

**Comment by techalchemy** [comment]
Hi, sorry you ran into this issue

For context, you are having this problem because you ran pipenv with `sudo` privileges. You should never do this, this is not supported or recommended and it should never be necessary.  Doing something as `sudo` will _always_ use root permission and therefore mess with whatever files are created. If you want to fix this problem you will have to remove these thigns using `sudo` again

Pipenv does not create `pip-selfcheck` or any other pip related files, but it does make pipenv related files and other files in your virtualenv -- this is how virtualenvs work.  When you run them with root permissions they get created as root.  Therefore you need to be root to remove them.

For more support please see stackoverflow
