### ISSUE TITLE
windows 10 pipenv.vendor.pexpect has no attribute 'spawn'

### ISSUE THREAD

**Issue by tiarno** [pypa/pipenv#2308]
On Windows10, Python3.6.5, pipenv 11.10.3, I get this error when I try to start a shell.
It worked fine for a while. I shared the volume to a linux instance (I know) and worked with it there. I think that's when the problems started with my Windows box.

So yeah, I probably shot myself in the foot there, but I don't see a way to start fresh again.
Can I just wipe it out and start fresh somehow?

In any case, here's the traceback:

    $ pipenv shell
    Traceback (most recent call last):
      File "c:\program files\python36\lib\site-packages\pipenv\core.py", line 2192, in do_shell
        c = pexpect.spawn(
    AttributeError: module 'pipenv.vendor.pexpect' has no attribute 'spawn'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\Program Files\Python36\Scripts\pipenv.exe\__main__.py", line 9, in <module>
      File "c:\program files\python36\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "c:\program files\python36\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
        rv = self.invoke(ctx)
      File "c:\program files\python36\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "c:\program files\python36\lib\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "c:\program files\python36\lib\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "c:\program files\python36\lib\site-packages\pipenv\cli.py", line 607, in shell
        three=three, python=python, fancy=fancy, shell_args=shell_args
      File "c:\program files\python36\lib\site-packages\pipenv\core.py", line 2206, in do_shell
        pew.workon_cmd([workon_name])
      File "c:\program files\python36\lib\site-packages\pipenv\patched\pew\pew.py", line 381, in     workon_cmd
        shell(env, cwd=project_dir)
      File "c:\program files\python36\lib\site-packages\pipenv\patched\pew\pew.py", line 208, in shell
        shell_name = Path(shell).stem
      File "c:\program files\python36\lib\pathlib.py", line 999, in __new__
        self = cls._from_parts(args, init=False)
      File "c:\program files\python36\lib\pathlib.py", line 656, in _from_parts
        drv, root, parts = self._parse_args(args)
      File "c:\program files\python36\lib\pathlib.py", line 640, in _parse_args
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not NoneType

Here's the result of pipenv.help minus the pipfile.lock contents because there's a lot.

    $ python -m pipenv.help
    <details><summary>$ python -m pipenv.help output</summary>
    
    Pipenv version: `'11.10.3'`
    
    Pipenv location: `'C:\\Program Files\\Python36\\lib\\site-packages\\pipenv'`
    
    Python location: `'C:\\Program Files\\Python36\\python.exe'`
    
    Other Python installations in `PATH`:
    
      - `2.7`: `C:\Python27\python.exe`
      - `3.6`: `C:\Program Files\Python36\python.exe`
    
      - `3.6.5`: `C:\Program Files\Python36\python.exe`
      - `2.7.13`: `C:\Python27\python.exe`
      - `3.6.5`: `C:\Windows\py.exe`
    
    PEP 508 Information:
    
    ```
    {'implementation_name': 'cpython',
     'implementation_version': '3.6.5',
     'os_name': 'nt',
     'platform_machine': 'AMD64',
     'platform_python_implementation': 'CPython',
     'platform_release': '10',
     'platform_system': 'Windows',
     'platform_version': '10.0.16299',
     'python_full_version': '3.6.5',
     'python_version': '3.6',
     'sys_platform': 'win32'}
    ```
    
    System environment variables:
    
      - `ALLUSERSPROFILE`
      - `APPDATA`
      - `COMMONPROGRAMFILES`
      - `COMPUTERNAME`
      - `COMSPEC`
      - `COMMONPROGRAMFILES(X86)`
      - `COMMONPROGRAMW6432`
      - `EDITOR`
      - `EXEPATH`
      - `HOME`
      - `HOMEDRIVE`
      - `HOMEPATH`
      - `LANG`
      - `LOCALAPPDATA`
      - `LOCALDFS`
      - `LOGONSERVER`
      - `MSYSTEM`
      - `NUMBER_OF_PROCESSORS`
      - `OS`
      - `PATH`
      - `PATHEXT`
      - `PLINK_PROTOCOL`
      - `PROCESSOR_ARCHITECTURE`
      - `PROCESSOR_IDENTIFIER`
      - `PROCESSOR_LEVEL`
      - `PROCESSOR_REVISION`
      - `PROGRAMFILES`
      - `PS1`
      - `PSMODULEPATH`
      - `PUBLIC`
      - `PWD`
      - `PROGRAMDATA`
      - `PROGRAMFILES(X86)`
      - `PROGRAMW6432`
      - `SESSIONNAME`
      - `SHLVL`
      - `SYSTEMDRIVE`
      - `SYSTEMROOT`
      - `TEMP`
      - `TERM`
      - `TERM_PROGRAM`
      - `TERM_PROGRAM_VERSION`
      - `TMP`
      - `UATDATA`
      - `USERDNSDOMAIN`
      - `USERDOMAIN`
      - `USERDOMAIN_ROAMINGPROFILE`
      - `USERNAME`
      - `USERPROFILE`
      - `VBOX_MSI_INSTALL_PATH`
      - `VSCODE_CWD`
      - `VSCODE_IPC_HOOK`
      - `VSCODE_NLS_CONFIG`
      - `VSCODE_NODE_CACHED_DATA_DIR_8980`
      - `VSCODE_PID`
      - `WINDIR`
      - `_`
      - `PYTHONDONTWRITEBYTECODE`
      - `PIP_PYTHON_PATH`
    
 

##### Expected result

Expected the pipenv shell to start.

##### Actual result

Traceback above.

##### Steps to replicate

Not sure.

**Comment by techalchemy** [comment]
Step 1) uninstall pipenv
Step 2) reinstall it

This _should_ fix the problem, we will have a new release out shortly as well, but let us know if this doesn't help

**Comment by tiarno** [comment]
That worked, thanks. Now I'll try to remember to not use multiple OS's in the same repo!
