### ISSUE TITLE
Install dev dependency results key error

### ISSUE THREAD

**Issue by JiDai** [pypa/pipenv#2373]
I have a problem with installing dev dependency. In my project I have this Pipfile : 

```
url = "https://pypi.org/simple"
[[source]]
verify_ssl = true
name = "pypi"

[packages]
argparse = "*"
argcomplete = "*"
prettytable = "*"

[dev-packages]
pyinstaller = "*"

[scripts]
build = "pyinstaller main.spec"

[requires]
python_version = "3.6"
```

When I install dev dependency I got an KeyError (see below). 
I tried to create a new folder with same dev dependency and it worked.
I tried to remove Virtualenv, remove pipenv cache folder but I got same error.

```
Python 3.6.3
pipenv, version 2018.05.18
```

------------

##### Expected result

Dev dependency install without error

##### Actual result

`$ pipenv install --dev`
```
Installing pyinstaller…
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==2018.5.18', 'console_scripts', 'pipenv')()
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/cli.py", line 402, in install
    selective_upgrade=selective_upgrade,
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/core.py", line 1978, in do_install
    extra_indexes=extra_indexes,
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/core.py", line 1494, in pip_install
    ' '.join(prepare_pip_source_args(sources)),
  File "/usr/local/Cellar/pipenv/2018.5.18/libexec/lib/python3.6/site-packages/pipenv/utils.py", line 285, in prepare_pip_source_args
    pip_args.extend(['-i', sources[0]['url']])
KeyError: 'url'
```
##### Steps to replicate

`pipenv install --dev`

**Comment by uranusjr** [comment]
Um, because you put the `url` lin in the wrong place? It should be under `[[source]]`, not above. We can probably emit better error messages for this, but you need to fix your Pipfile.

**Comment by JiDai** [comment]
So simple. Thanks, it works

**Comment by Marto32** [comment]
Is anyone working on this? If not, mind if I give it a try?
