### ISSUE TITLE
Unable to install dependencies from Github

### ISSUE THREAD

**Issue by realslimshanky** [pypa/pipenv#2409]
Be sure to check the existing issues (both open and closed!).

Describe the issue briefly here.

While installing dependency from the Pipfile which in turn is using `.git` from Github, error occurs. But the same can be successfully installed by calling pipenv install explicitly.

In my case, I'm trying to install Kivy's 1.10.1 version using `git+http://github.com/kivy/kivy.git#egg=kivy-1.10.1`

Please run `$ python -m pipenv.help`, and paste the results here.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'2018.05.18'`

Pipenv location: `'/home/realslimshanky/.local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/usr/bin/python3.5`

  - `2.7.13`: `/usr/bin/python`
  - `2.7.13`: `/usr/bin/python2`
  - `3.5.3`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.9.0-6-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07)',
 'python_full_version': '2.7.13',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `KDE_SESSION_VERSION`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_SESSION_TYPE`
  - `LOGNAME`
  - `USER`
  - `N_PREFIX`
  - `XDG_VTNR`
  - `HOME`
  - `DISPLAY`
  - `SSH_AGENT_PID`
  - `LANG`
  - `PROFILEHOME`
  - `TERM`
  - `SHELL`
  - `COLORFGBG`
  - `XAUTHORITY`
  - `LANGUAGE`
  - `SESSION_MANAGER`
  - `XDG_DATA_DIRS`
  - `GS_LIB`
  - `KONSOLE_PROFILE_NAME`
  - `XCURSOR_THEME`
  - `KONSOLE_DBUS_WINDOW`
  - `QT_ACCESSIBILITY`
  - `WINDOWID`
  - `XDG_RUNTIME_DIR`
  - `KDE_FULL_SESSION`
  - `KONSOLE_DBUS_SESSION`
  - `XDG_SESSION_CLASS`
  - `PATH`
  - `XDG_SESSION_DESKTOP`
  - `KDE_SESSION_UID`
  - `GTK_RC_FILES`
  - `ANDROID_EMULATOR_USE_SYSTEM_LIBS`
  - `SSH_AUTH_SOCK`
  - `KONSOLE_DBUS_SERVICE`
  - `PAM_KWALLET5_LOGIN`
  - `PIP_PYTHON_PATH`
  - `GTK2_RC_FILES`
  - `XDG_SEAT_PATH`
  - `XDG_SESSION_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_SESSION_ID`
  - `SHELL_SESSION_ID`
  - `_`
  - `DESKTOP_SESSION`
  - `GPG_AGENT_INFO`
  - `GTK_MODULES`
  - `XDG_SEAT`
  - `SHLVL`
  - `PWD`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `COLORTERM`
  - `QT_LINUX_ACCESSIBILITY_ALWAYS_ON`
  - `LS_COLORS`
  - `KDE_MULTIHEAD`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/realslimshanky/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/realslimshanky/.npm-packages/bin:/home/realslimshanky/.local/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_IN`
  - `PWD`: `/home/realslimshanky/Downloads/Telegram Desktop/EduModWiz/EduModWiz/edumodwiz`

---------------------------

Contents of `Pipfile` ('/home/realslimshanky/Downloads/Telegram Desktop/EduModWiz/EduModWiz/edumodwiz/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
pylint = "==1.9.1"
pytest = "==3.6.0"
pytest-cov = "==2.5.1"

[packages]
cython = "==0.28"
"kivy-1.10.1" = {path = "git+http://github.com/kivy/kivy.git#egg=kivy-1.10.1"}

[requires]
python_version = "3.5"


```

Contents of `Pipfile.lock` ('/home/realslimshanky/Downloads/Telegram Desktop/EduModWiz/EduModWiz/edumodwiz/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "e2091669144f62c9bf8da171d836db2f98d0eb13f9b8f7d9fe4f859c50c78817"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.5"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "cython": {
            "hashes": [
                "sha256:02414e1cae1882d48e8fa9cdefb6e7bd3dd200a5dc5120a3905df164d23e7894",
                "sha256:02540b24230fa8111ac5b2602ee61d4341adbe25d8b5a4ba8becf675c2253a36",
                "sha256:047acc6712ee6fd97d661e9a804befe1307156d7595501bd1aeaaa882c01e8a9",
                "sha256:086c082b77565382e1c67e864c0c4832d49dc38bdf551f69c789cbcec9b1d190",
                "sha256:20c73f0af4df69948aff13183163613855a12973c66ddbeed83b079b73d83ea1",
                "sha256:24078813387ce0613f8e1cb9f44e07a2abacb0ca2ec697886cb020c7628f6107",
                "sha256:35696be120cf3c8505a461cf9ac7792fc92c938f9e92526a8b1bb581f802c920",
                "sha256:44b94943552074b1644b9727395c06b6efbaf562083a9e2bd89c6a41d0df8159",
                "sha256:518f7e22da54109661e483a91a63045203caf9fd78da4a69185a7622f759965f",
                "sha256:5b9f283ca14b4d572d87f741b3c67a2d922d28e03d8bc692d700cfe4c7b94270",
                "sha256:5c0bdd626e3e30656059383a0c2ee4150985ffe888c5951f2381f1120e281cd6",
                "sha256:667f7f6da9951d3ab2ac5c50ee686bec42307f0d004483a981efc813caf76481",
                "sha256:678f18c41248510e0ea924bc467b9586ec19726c01dd44f69086ab61c3406191",
                "sha256:732f04055108a70571a2f5336dc2d07cd7ee8c63cc18777200604e7a0a9bb223",
                "sha256:7abe6b8c7435f26ce022419d4a5bd5e81a9a31cc32d984939bb808709ecad528",
                "sha256:96392fb9c6d69efd689fc62df5eb06a7efe8ef6c432b316d2cec4054710c13b5",
                "sha256:995409aa518e87fd63098a6c2f437fa8483bd1be1485bb76446622663b071a3b",
                "sha256:a1370f5c245980c61e815a073d5117ae56b1f56a83c473e2d49cdafec569581f",
                "sha256:ac0b06430117241e59d07a3b965cbbdc62ac7315f5f6c3b9826740f80cf6ecd6",
                "sha256:b654751d6e87de3dcea998a2afb438402a8e1bf4d60df91f163e2c086096b388",
                "sha256:bb3f13351f13ee0fd920319589c14e3e1b8a8188c1ceeec780f9b77f6f627e7b",
                "sha256:bbce622d2d0cacd810ee275db149950b7c4530eec0c4acfa8cf211079138b92d",
                "sha256:c0fa07a0e1b33eb0d7ad4df5e9658367a40a4af0915ad652a7c7774368fbcca1",
                "sha256:cad1cef5ea2bcd43d0391af921715150e84fb6122f322dde2f5faea68f6fdb13",
                "sha256:d622bade45e1807f6149fee559e65a24b2ae54ab9d8ebfba2b546eec78a771de",
                "sha256:d8de4ccc93a660adbeaacaa10a544072bc840a48a16680ece472c3d9c70989ce",
                "sha256:dd889b21a275a516383c3bc4d65c7ba2bacee592a5478bd1b20421f2ec9702eb",
                "sha256:ee7ccfcb3f46d6f8cea1eb6819c7d82c34e0f5bd8dda7c4413ccbbbb575565bb",
                "sha256:fb0ea686f6e39bac3b070e43b2fda4cd47b08e6539390f3953b2c40117c40766",
                "sha256:fee8d2fefbccd2029812a344e03fdd028bdf9147e4a0cb117ad2d1db14e46e11"
            ],
            "index": "pypi",
            "version": "==0.28"
        },
        "kivy-1.10.1": {
            "path": "git+http://github.com/kivy/kivy.git#egg=kivy-1.10.1"
        }
    },
    "develop": {
        "astroid": {
            "hashes": [
                "sha256:0ef2bf9f07c3150929b25e8e61b5198c27b0dca195e156f0e4d5bdd89185ca1a",
                "sha256:fc9b582dba0366e63540982c3944a9230cbc6f303641c51483fa547dcc22393a"
            ],
            "version": "==1.6.5"
        },
        "atomicwrites": {
            "hashes": [
                "sha256:240831ea22da9ab882b551b31d4225591e5e447a68c5e188db5b89ca1d487585",
                "sha256:a24da68318b08ac9c9c45029f4a10371ab5b20e4226738e150e6e7c571630ae6"
            ],
            "version": "==1.1.5"
        },
        "attrs": {
            "hashes": [
                "sha256:4b90b09eeeb9b88c35bc642cbac057e45a5fd85367b985bd2809c62b7b939265",
                "sha256:e0d0eb91441a3b53dab4d9b743eafc1ac44476296a2053b6ca3af0b139faf87b"
            ],
            "version": "==18.1.0"
        },
        "coverage": {
            "hashes": [
                "sha256:03481e81d558d30d230bc12999e3edffe392d244349a90f4ef9b88425fac74ba",
                "sha256:0b136648de27201056c1869a6c0d4e23f464750fd9a9ba9750b8336a244429ed",
                "sha256:104ab3934abaf5be871a583541e8829d6c19ce7bde2923b2751e0d3ca44db60a",
                "sha256:15b111b6a0f46ee1a485414a52a7ad1d703bdf984e9ed3c288a4414d3871dcbd",
                "sha256:198626739a79b09fa0a2f06e083ffd12eb55449b5f8bfdbeed1df4910b2ca640",
                "sha256:1c383d2ef13ade2acc636556fd544dba6e14fa30755f26812f54300e401f98f2",
                "sha256:28b2191e7283f4f3568962e373b47ef7f0392993bb6660d079c62bd50fe9d162",
                "sha256:2eb564bbf7816a9d68dd3369a510be3327f1c618d2357fa6b1216994c2e3d508",
                "sha256:337ded681dd2ef9ca04ef5d93cfc87e52e09db2594c296b4a0a3662cb1b41249",
                "sha256:3a2184c6d797a125dca8367878d3b9a178b6fdd05fdc2d35d758c3006a1cd694",
                "sha256:3c79a6f7b95751cdebcd9037e4d06f8d5a9b60e4ed0cd231342aa8ad7124882a",
                "sha256:3d72c20bd105022d29b14a7d628462ebdc61de2f303322c0212a054352f3b287",
                "sha256:3eb42bf89a6be7deb64116dd1cc4b08171734d721e7a7e57ad64cc4ef29ed2f1",
                "sha256:4635a184d0bbe537aa185a34193898eee409332a8ccb27eea36f262566585000",
                "sha256:56e448f051a201c5ebbaa86a5efd0ca90d327204d8b059ab25ad0f35fbfd79f1",
                "sha256:5a13ea7911ff5e1796b6d5e4fbbf6952381a611209b736d48e675c2756f3f74e",
                "sha256:69bf008a06b76619d3c3f3b1983f5145c75a305a0fea513aca094cae5c40a8f5",
                "sha256:6bc583dc18d5979dc0f6cec26a8603129de0304d5ae1f17e57a12834e7235062",
                "sha256:701cd6093d63e6b8ad7009d8a92425428bc4d6e7ab8d75efbb665c806c1d79ba",
                "sha256:7608a3dd5d73cb06c531b8925e0ef8d3de31fed2544a7de6c63960a1e73ea4bc",
                "sha256:76ecd006d1d8f739430ec50cc872889af1f9c1b6b8f48e29941814b09b0fd3cc",
                "sha256:7aa36d2b844a3e4a4b356708d79fd2c260281a7390d678a10b91ca595ddc9e99",
                "sha256:7d3f553904b0c5c016d1dad058a7554c7ac4c91a789fca496e7d8347ad040653",
                "sha256:7e1fe19bd6dce69d9fd159d8e4a80a8f52101380d5d3a4d374b6d3eae0e5de9c",
                "sha256:8c3cb8c35ec4d9506979b4cf90ee9918bc2e49f84189d9bf5c36c0c1119c6558",
                "sha256:9d6dd10d49e01571bf6e147d3b505141ffc093a06756c60b053a859cb2128b1f",
                "sha256:9e112fcbe0148a6fa4f0a02e8d58e94470fc6cb82a5481618fea901699bf34c4",
                "sha256:ac4fef68da01116a5c117eba4dd46f2e06847a497de5ed1d64bb99a5fda1ef91",
                "sha256:b8815995e050764c8610dbc82641807d196927c3dbed207f0a079833ffcf588d",
                "sha256:be6cfcd8053d13f5f5eeb284aa8a814220c3da1b0078fa859011c7fffd86dab9",
                "sha256:c1bb572fab8208c400adaf06a8133ac0712179a334c09224fb11393e920abcdd",
                "sha256:de4418dadaa1c01d497e539210cb6baa015965526ff5afc078c57ca69160108d",
                "sha256:e05cb4d9aad6233d67e0541caa7e511fa4047ed7750ec2510d466e806e0255d6",
                "sha256:e4d96c07229f58cb686120f168276e434660e4358cc9cf3b0464210b04913e77",
                "sha256:f3f501f345f24383c0000395b26b726e46758b71393267aeae0bd36f8b3ade80",
                "sha256:f8a923a85cb099422ad5a2e345fe877bbc89a8a8b23235824a93488150e45f6e"
            ],
            "version": "==4.5.1"
        },
        "isort": {
            "hashes": [
                "sha256:1153601da39a25b14ddc54955dbbacbb6b2d19135386699e2ad58517953b34af",
                "sha256:b9c40e9750f3d77e6e4d441d8b0266cf555e7cdabdcff33c4fd06366ca761ef8",
                "sha256:ec9ef8f4a9bc6f71eec99e1806bfa2de401650d996c59330782b89a5555c1497"
            ],
            "version": "==4.3.4"
        },
        "lazy-object-proxy": {
            "hashes": [
                "sha256:0ce34342b419bd8f018e6666bfef729aec3edf62345a53b537a4dcc115746a33",
                "sha256:1b668120716eb7ee21d8a38815e5eb3bb8211117d9a90b0f8e21722c0758cc39",
                "sha256:209615b0fe4624d79e50220ce3310ca1a9445fd8e6d3572a896e7f9146bbf019",
                "sha256:27bf62cb2b1a2068d443ff7097ee33393f8483b570b475db8ebf7e1cba64f088",
                "sha256:27ea6fd1c02dcc78172a82fc37fcc0992a94e4cecf53cb6d73f11749825bd98b",
                "sha256:2c1b21b44ac9beb0fc848d3993924147ba45c4ebc24be19825e57aabbe74a99e",
                "sha256:2df72ab12046a3496a92476020a1a0abf78b2a7db9ff4dc2036b8dd980203ae6",
                "sha256:320ffd3de9699d3892048baee45ebfbbf9388a7d65d832d7e580243ade426d2b",
                "sha256:50e3b9a464d5d08cc5227413db0d1c4707b6172e4d4d915c1c70e4de0bbff1f5",
                "sha256:5276db7ff62bb7b52f77f1f51ed58850e315154249aceb42e7f4c611f0f847ff",
                "sha256:61a6cf00dcb1a7f0c773ed4acc509cb636af2d6337a08f362413c76b2b47a8dd",
                "sha256:6ae6c4cb59f199d8827c5a07546b2ab7e85d262acaccaacd49b62f53f7c456f7",
                "sha256:7661d401d60d8bf15bb5da39e4dd72f5d764c5aff5a86ef52a042506e3e970ff",
                "sha256:7bd527f36a605c914efca5d3d014170b2cb184723e423d26b1fb2fd9108e264d",
                "sha256:7cb54db3535c8686ea12e9535eb087d32421184eacc6939ef15ef50f83a5e7e2",
                "sha256:7f3a2d740291f7f2c111d86a1c4851b70fb000a6c8883a59660d95ad57b9df35",
                "sha256:81304b7d8e9c824d058087dcb89144842c8e0dea6d281c031f59f0acf66963d4",
                "sha256:933947e8b4fbe617a51528b09851685138b49d511af0b6c0da2539115d6d4514",
                "sha256:94223d7f060301b3a8c09c9b3bc3294b56b2188e7d8179c762a1cda72c979252",
                "sha256:ab3ca49afcb47058393b0122428358d2fbe0408cf99f1b58b295cfeb4ed39109",
                "sha256:bd6292f565ca46dee4e737ebcc20742e3b5be2b01556dafe169f6c65d088875f",
                "sha256:cb924aa3e4a3fb644d0c463cad5bc2572649a6a3f68a7f8e4fbe44aaa6d77e4c",
                "sha256:d0fc7a286feac9077ec52a927fc9fe8fe2fabab95426722be4c953c9a8bede92",
                "sha256:ddc34786490a6e4ec0a855d401034cbd1242ef186c20d79d2166d6a4bd449577",
                "sha256:e34b155e36fa9da7e1b7c738ed7767fc9491a62ec6af70fe9da4a057759edc2d",
                "sha256:e5b9e8f6bda48460b7b143c3821b21b452cb3a835e6bbd5dd33aa0c8d3f5137d",
                "sha256:e81ebf6c5ee9684be8f2c87563880f93eedd56dd2b6146d8a725b50b7e5adb0f",
                "sha256:eb91be369f945f10d3a49f5f9be8b3d0b93a4c2be8f8a5b83b0571b8123e0a7a",
                "sha256:f460d1ceb0e4a5dcb2a652db0904224f367c9b3c1470d5a7683c0480e582468b"
            ],
            "version": "==1.3.1"
        },
        "mccabe": {
            "hashes": [
                "sha256:ab8a6258860da4b6677da4bd2fe5dc2c659cff31b3ee4f7f5d64e79735b80d42",
                "sha256:dd8d182285a0fe56bace7f45b5e7d1a6ebcbf524e8f3bd87eb0f125271b8831f"
            ],
            "version": "==0.6.1"
        },
        "more-itertools": {
            "hashes": [
                "sha256:2b6b9893337bfd9166bee6a62c2b0c9fe7735dcf85948b387ec8cba30e85d8e8",
                "sha256:6703844a52d3588f951883005efcf555e49566a48afd4db4e965d69b883980d3",
                "sha256:a18d870ef2ffca2b8463c0070ad17b5978056f403fb64e3f15fe62a52db21cc0"
            ],
            "version": "==4.2.0"
        },
        "pluggy": {
            "hashes": [
                "sha256:7f8ae7f5bdf75671a718d2daf0a64b7885f74510bcd98b1a0bb420eb9a9d0cff",
                "sha256:d345c8fe681115900d6da8d048ba67c25df42973bda370783cd58826442dcd7c",
                "sha256:e160a7fcf25762bb60efc7e171d4497ff1d8d2d75a3d0df7a21b76821ecbf5c5"
            ],
            "version": "==0.6.0"
        },
        "py": {
            "hashes": [
                "sha256:29c9fab495d7528e80ba1e343b958684f4ace687327e6f789a94bf3d1915f881",
                "sha256:983f77f3331356039fdd792e9220b7b8ee1aa6bd2b25f567a963ff1de5a64f6a"
            ],
            "version": "==1.5.3"
        },
        "pylint": {
            "hashes": [
                "sha256:aa519865f8890a5905fa34924fed0f3bfc7d84fc9f9142c16dac52ffecd25a39",
                "sha256:c353d8225195b37cc3aef18248b8f3fe94c5a6a95affaf885ae21a24ca31d8eb"
            ],
            "index": "pypi",
            "version": "==1.9.1"
        },
        "pytest": {
            "hashes": [
                "sha256:39555d023af3200d004d09e51b4dd9fdd828baa863cded3fd6ba2f29f757ae2d",
                "sha256:c76e93f3145a44812955e8d46cdd302d8a45fbfc7bf22be24fe231f9d8d8853a"
            ],
            "index": "pypi",
            "version": "==3.6.0"
        },
        "pytest-cov": {
            "hashes": [
                "sha256:03aa752cf11db41d281ea1d807d954c4eda35cfa1b21d6971966cc041bbf6e2d",
                "sha256:890fe5565400902b0c78b5357004aab1c814115894f4f21370e2433256a3eeec"
            ],
            "index": "pypi",
            "version": "==2.5.1"
        },
        "six": {
            "hashes": [
                "sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9",
                "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"
            ],
            "version": "==1.11.0"
        },
        "wrapt": {
            "hashes": [
                "sha256:d4d560d479f2c21e1b5443bbd15fe7ec4b37fe7e53d335d3b9b0a7b1226fe3c6"
            ],
            "version": "==1.10.11"
        }
    }
}

```
</details>

If you're on MacOS, just run the following:

    $ python -m pipenv.help | pbcopy

------------

##### Expected result

Dependency should be installed by mentioning `"kivy-1.10.1" = {path = "git+http://github.com/kivy/kivy.git#egg=kivy-1.10.1"}` in the Pipfile.

##### Actual result

When we run `pipenv install git+http://github.com/kivy/kivy.git`, dependency can be successfully installed. But the same is not the case with Pipfile.
While installing `Kivy` from Pipfile the following error occurs

```
Installing 'git+http://github.com/kivy/kivy.git#egg=kivy-1.10.1'
$ "/home/realslimshanky/.local/share/virtualenvs/edumodwiz-WZ8dLI63/bin/pip" install   --verbose  --no-deps  -r "/tmp/pipenv-EIOrx4-requirements/pipenv-aT1X8_-requirement.txt" -i https://pypi.org/simple --exists-action w
Created temporary directory: /tmp/pip-ephem-wheel-cache-0mfs6b4u
Created temporary directory: /tmp/pip-install-br8l_eq6                                                                       
Requirement already satisfied: cython==0.28 in /home/realslimshanky/.local/share/virtualenvs/edumodwiz-WZ8dLI63/lib/python3.5/site-packages (from -r /tmp/pipenv-EIOrx4-requirements/pipenv-Itn28s-requirement.txt (line 1)) (0.28)                       
  Since it is already installed, we are trusting this package without checking its hash. To ensure a completely repeatable environment, install into an empty virtualenv.                                                                                 
Cleaning up...                                                                                                               

Created temporary directory: /tmp/pip-ephem-wheel-cache-y1wbxykw
Created temporary directory: /tmp/pip-install-yyv5puvx                                                                       
Collecting kivy-1.10.1 from git+http://github.com/kivy/kivy.git#egg=kivy-1.10.1 (from -r /tmp/pipenv-EIOrx4-requirements/pipenv-aT1X8_-requirement.txt (line 1))                                                                                          
  Cloning http://github.com/kivy/kivy.git to /tmp/pip-install-yyv5puvx/kivy-1.10.1                                           
  Running command git clone -q http://github.com/kivy/kivy.git /tmp/pip-install-yyv5puvx/kivy-1.10.1                         
fatal: unable to access 'https://github.com/kivy/kivy.git/': GnuTLS recv error (-9): A TLS packet with unexpected length was received.                                                                                                                    
Cleaning up...                                                                                                               
Command "git clone -q http://github.com/kivy/kivy.git /tmp/pip-install-yyv5puvx/kivy-1.10.1" failed with error code 128 in None                                                                                                                           
Exception information:                                                                                                       
Traceback (most recent call last):                                                                                           
  File "/home/realslimshanky/.local/share/virtualenvs/edumodwiz-WZ8dLI63/lib/python3.5/site-packages/pip/_internal/basecommand.py", line 228, in main                                                                                                     
    status = self.run(options, args)                                                                                         
  File "/home/realslimshanky/.local/share/virtualenvs/edumodwiz-WZ8dLI63/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 291, in run                                                                                                 
    resolver.resolve(requirement_set)                                                                                        
  File "/home/realslimshanky/.local/share/virtualenvs/edumodwiz-WZ8dLI63/lib/python3.5/site-packages/pip/_internal/resolve.py", line 103, in resolve                                                                                                      
    self._resolve_one(requirement_set, req)                                                                                  
  File "/home/realslimshanky/.local/share/virtualenvs/edumodwiz-WZ8dLI63/lib/python3.5/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one                                                                                                 
    abstract_dist = self._get_abstract_dist_for(req_to_install)                                                              
  File "/home/realslimshanky/.local/share/virtualenvs/edumodwiz-WZ8dLI63/lib/python3.5/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for                                                                                       
    self.require_hashes                                                                                                      
  File "/home/realslimshanky/.local/share/virtualenvs/edumodwiz-WZ8dLI63/lib/python3.5/site-packages/pip/_internal/operations/prepare.py", line 310, in prepare_linked_requirement                                                                        
    progress_bar=self.progress_bar                                                                                           
  File "/home/realslimshanky/.local/share/virtualenvs/edumodwiz-WZ8dLI63/lib/python3.5/site-packages/pip/_internal/download.py", line 820, in unpack_url                                                                                                  
    unpack_vcs_link(link, location)                                                                                          
  File "/home/realslimshanky/.local/share/virtualenvs/edumodwiz-WZ8dLI63/lib/python3.5/site-packages/pip/_internal/download.py", line 495, in unpack_vcs_link                                                                                             
    vcs_backend.unpack(location)                                                                                             
  File "/home/realslimshanky/.local/share/virtualenvs/edumodwiz-WZ8dLI63/lib/python3.5/site-packages/pip/_internal/vcs/__init__.py", line 388, in unpack                                                                                                  
    self.obtain(location)                                                                                                    
  File "/home/realslimshanky/.local/share/virtualenvs/edumodwiz-WZ8dLI63/lib/python3.5/site-packages/pip/_internal/vcs/git.py", line 187, in obtain                                                                                                       
    self.run_command(['clone', '-q', url, dest])                                                                             
  File "/home/realslimshanky/.local/share/virtualenvs/edumodwiz-WZ8dLI63/lib/python3.5/site-packages/pip/_internal/vcs/__init__.py", line 427, in run_command                                                                                             
    spinner=spinner)                                                                                                         
  File "/home/realslimshanky/.local/share/virtualenvs/edumodwiz-WZ8dLI63/lib/python3.5/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess                                                                                           
    % (command_desc, proc.returncode, cwd))                                                                                  
pip._internal.exceptions.InstallationError: Command "git clone -q http://github.com/kivy/kivy.git /tmp/pip-install-yyv5puvx/kivy-1.10.1" failed with error code 128 in None 
```

##### Steps to replicate

My Pipfile contains the following
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]
pylint = "==1.9.1"
pytest = "==3.6.0"
pytest-cov = "==2.5.1"

[packages]
cython = "==0.28"
"kivy-1.10.1" = {path = "git+http://github.com/kivy/kivy.git#egg=kivy-1.10.1"}

[requires]
python_version = "3.5"
```

Running `pipenv install` prompts the error.

**Comment by uranusjr** [comment]
I think the canonical way is to use `{git = "http://github.com/kivy/kivy.git#egg=kivy-1.10.1"}`. I’m honestly curious why you would think you should use `path`—it is not even a path. This would help us provide better documentation on how the Pipfile should be written manually.

**Comment by techalchemy** [comment]
Just replace `pip` with `pipenv` and don’t edit your pipfile by hand. If you want to do that please see the documentation and if you have more questions please visit the help forum on stackoverflow. Thanks and good luck!
