### ISSUE TITLE
pipenv 2018.6.25 for python 2 fails when running "pipenv update --dev" or similar commands -- pathlib.Path.mkdir does NOT have exist_ok argument

### ISSUE THREAD

**Issue by mrstewar** [pypa/pipenv#2438]
Running Python 2.7.12 with pipenv installed in user site (pip install --user pipenv) fails because 
pathlib.Path.mkdir function doesn't have a exist_ok argument specified.

Actual error (from bottom of full output):
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'

Seems like it's confied to python2 as python2 doesn't have pathlib natively in the standard library and must use a backport.

Full output:
project_dir>pipenv update --dev
Running $ pipenv lock then $ pipenv sync.
Locking [dev-packages] dependencies...
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "<user_base>\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "<user_base>\Python\Python27\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "<user_base>\Python27\site-packages\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "<user_base>\Python27\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "<user_base>\Python27\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<user_base>\Python27\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "<user_base>\Python27\site-packages\pipenv\vendor\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "<user_base>\Python27\site-packages\pipenv\cli.py", line 850, in update
    verbose=verbose, clear=clear, pre=pre, keep_outdated=keep_outdated, pypi_mirror=pypi_mirror
  File "<user_base>\Python27\site-packages\pipenv\core.py", line 1098, in do_lock
    dev=settings['dev']
  File "<user_base>\Python27\site-packages\pipenv\utils.py", line 1177, in get_vcs_deps
    src_dir.mkdir(mode=0o775, exist_ok=True)
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'

[pipenv_help.txt](https://github.com/pypa/pipenv/files/2139816/pipenv_help.txt)

##### Expected result
Expected the update to run without error

##### Actual result
Failed as shown at the beginning

##### Steps to replicate

In pristine project directory (no Pipfile) using python 2.7.12 or greater run:
pipenv install future

You should actually see the problem there as well.

If not, then run "pipenv update"

**Comment by techalchemy** [comment]
We fall back to pathlib2 which we vendor. I guess you have manually installed the old, deprecated `pathlib` in your global environment. I guess we can use python conditional version checks but the real solution is to stop installing pathlib in your environment.

**Comment by uranusjr** [comment]
We do list 3.4 as supported, and the built-in pathlib on 3.4 does not have `exist_ok` IIRC. I need to fix that.

**Comment by uranusjr** [comment]
Or maybe we should use the vendored pathlib2 on 3.4.

**Comment by mrstewar** [comment]
@techalchemy you were indeed correct about having pathlib installed in my environment.  I removed it on both my windows and linux systems and can confirm that this fixed my specific issue.  Many thanks for the tip.

**Comment by daa** [comment]
@uranusjr You may also use  ``ruamel.std.pathlib`` which uses standard ``pathlib`` or ``pathlib2`` when appropriate, for example now ``pathlib2`` is used for python < 3.5.

**Comment by techalchemy** [comment]
We already handled this.
