### ISSUE TITLE
pipenv --completion fails

### ISSUE THREAD

**Issue by iboyperson** [pypa/pipenv#2439]
Running `pipenv --completion` results in the following error:

    Traceback (most recent call last):
      File "/usr/bin/pipenv", line 11, in <module>
        load_entry_point('pipenv==2018.6.25', 'console_scripts', 'pipenv')()
      File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
        return Command.invoke(self, ctx)
      File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "/usr/lib/python3.6/site-packages/pipenv/cli.py", line 178, in cli
        print(click_completion.get_code(shell=shell, prog_name='pipenv'))
      File "/usr/lib/python3.6/site-packages/pipenv/vendor/click_completion/__init__.py", line 353, in get_code
        template = env.get_template('%s.j2' % shell)
      File "/usr/lib/python3.6/site-packages/pipenv/vendor/jinja2/environment.py", line 830, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/usr/lib/python3.6/site-packages/pipenv/vendor/jinja2/environment.py", line 804, in _load_template
        template = self.loader.load(self, name, globals)
      File "/usr/lib/python3.6/site-packages/pipenv/vendor/jinja2/loaders.py", line 113, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "/usr/lib/python3.6/site-packages/pipenv/vendor/jinja2/loaders.py", line 187, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: zsh.j2
 

Please run `$ python -m pipenv.help`, and paste the results here.

https://pastebin.com/m4t3YgxM

##### Expected result

Normal completion output

##### Actual result

The above error is thrown

##### Steps to replicate

run `pipenv --completion`

**Comment by techalchemy** [comment]
Thanks for the report. Fix is already merged. Release will be out tomorrow. See #2422
