### ISSUE TITLE
Wheel file not used when installing mysql-python on MacOs

### ISSUE THREAD

**Issue by dresnick-sf** [pypa/pipenv#2442]
Installing mysql-python with `pip` succeeds, but with `pipenv` it fails.

I see that `pip` is installing from `MySQL_python-1.2.5-cp27-cp27m-macosx_10_13_x86_64.whl`.
When installing via `pipenv` the wheel file is not used and it fails with:
```
  Using version 1.2.5 (newest of versions: 1.2.5)
  Created temporary directory: /private/var/folders/_t/4fb22psj4079hxxtjj3bqt31b8jsc8/T/pip-unpack-vXegtZ
  Looking up "https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip" in the cache
  Ignoring unknown cache-control directive:
  Current age based on date: 89524
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 89524
  Using cached https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip
  Downloading from URL https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip#sha256=811040b647e5d5686f84db415efd697e6250008b112b6909ba77ac059e140c74 (from https://pypi.org/simple/mysql-python/)
  Running setup.py (path:/private/var/folders/_t/4fb22psj4079hxxtjj3bqt31b8jsc8/T/pip-install-785taV/mysql-python/setup.py) egg_info for package mysql-python
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_t/4fb22psj4079hxxtjj3bqt31b8jsc8/T/pip-install-785taV/mysql-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 53, in get_config
        libraries = [ dequote(i[2:]) for i in libs if i.startswith(compiler_flag("l")) ]
      File "setup_posix.py", line 8, in dequote
        if s[0] in "\"'" and s[0] == s[-1]:
    IndexError: string index out of range
```

With pip (in an empty `virtualenv` with the same python):
```
$ pip install -v mysql-python
...
Using version 1.2.5 (newest of versions: 1.2.3, 1.2.4, 1.2.5)
Using cached wheel link: file:///Users/user/Library/Caches/pip/wheels/07/d2/5f/314860e4cb53a44bf0ee0d051d4b34465e4b4fbe9de6d42f42/MySQL_python-1.2.5-cp27-cp27m-macosx_10_13_x86_64.whl
Installing collected packages: mysql-python

Successfully installed mysql-python-1.2.5
Cleaning up...

```
Versions:
```
pipenv, version 2018.05.18
Python 2.7.15 (Homebrew python@2)
pip 10.0.1 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)
MacOs: 10.13.5
```

**Comment by techalchemy** [comment]
I think we have fixed this in master, can you try that out and let us know?

**Comment by dresnick-sf** [comment]
Same result:
```
/Users/user/src/proj ❯❯❯ ./temp/bin/pipenv --version
pipenv, version 2018.6.26.dev0
/Users/user/src/proj ❯❯❯ ./temp/bin/pipenv install -v mysql-python
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead.
Creating a Pipfile for this project...
Installing mysql-python...
⠋Installing u'mysql-python'
$ "/Users/user/src/proj/temp/bin/pip" install   --verbose    "mysql-python" -i https://pypi.org/simple --exists-action w
Created temporary directory: /private/var/folders/_t/4fb22psj4079hxxtjj3bqt31b8jsc8/T/pip-ephem-wheel-cache-jY6Ueb
Created temporary directory: /private/var/folders/_t/4fb22psj4079hxxtjj3bqt31b8jsc8/T/pip-install-m6iEmd
Collecting mysql-python
  1 location(s) to search for versions of mysql-python:
  * https://pypi.org/simple/mysql-python/
  Getting page https://pypi.org/simple/mysql-python/
  Looking up "https://pypi.org/simple/mysql-python/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.org
  https://pypi.org:443 "GET /simple/mysql-python/ HTTP/1.1" 200 3030
  Updating cache with response from "https://pypi.org/simple/mysql-python/"
  Caching due to etag
  Analyzing links from page https://pypi.org/simple/mysql-python/
    Skipping link https://files.pythonhosted.org/packages/66/8f/d22ffc75b2e9b1d9c264c0cd715359e589f1f1f7edfb48e0923401ac3f8f/MySQL_python-1.2.2-py2.4-win32.egg#sha256=35e098febdfc2e97f417a8c37131c47cc88bc65ec1ee7bf01f55ff8d1bf23830 (from https://pypi.org/simple/mysql-python/); unsupported archive format: .egg
    Skipping link https://files.pythonhosted.org/packages/f9/5a/ad2d05dbf38fff9e184f9c386506f92e4d6f2cd572bcebd289d2a7c6dce6/MySQL_python-1.2.2-py2.5-win32.egg#sha256=8258a8e287e3b7cca9e645b0da6de132d5a3b25e79e8c8ce4f555173033b2807 (from https://pypi.org/simple/mysql-python/); unsupported archive format: .egg
    Found link https://files.pythonhosted.org/packages/55/b8/f1f811f29a3b290b9e0fedeab8ea38b0c57cfb5e78f3c1eccc2d4de321e7/MySQL-python-1.2.3b1.tar.gz#sha256=8bdae9ef1e6341585a5f8e4b1decfd8720a171dc13da61d8bc72b2d1f62ac3c2 (from https://pypi.org/simple/mysql-python/), version: 1.2.3b1
    Skipping link https://files.pythonhosted.org/packages/d6/2e/14aab64b706ac291e2aa66b32911b64696361108289722fb804e1ad8a67c/MySQL_python-1.2.3b1-py2.5-linux-i686.egg#sha256=441cc30059a601dfa9146c74e55f3298f4b1360225b5693a0adcb60c643d067a (from https://pypi.org/simple/mysql-python/); unsupported archive format: .egg
    Skipping link https://files.pythonhosted.org/packages/b9/7a/ad14337bcc08f60550f178acb3ce715fba1a827494b8f47b1022619d5eb1/MySQL_python-1.2.3b1-py2.6-linux-i686.egg#sha256=ec2811d0869b7fa8e8a80e8c205bbb954b964c8720acfb83a32d459635f96d63 (from https://pypi.org/simple/mysql-python/); unsupported archive format: .egg
    Found link https://files.pythonhosted.org/packages/9b/f0/2b71c8f3be0319dc9eb1aab8eac1dcbe5f981cc1b42f630cb7a49ae9ab54/MySQL-python-1.2.3b2.tar.gz#sha256=bb2ba94602ceb536d59127efe0f4b550b916b9b1fe1e6f4bc2f5099c436175dd (from https://pypi.org/simple/mysql-python/), version: 1.2.3b2
    Skipping link https://files.pythonhosted.org/packages/94/c2/96ca7914b69fe1eda92b401a8e314e8321cd4d6119c7f85921ce6982eb49/MySQL_python-1.2.3b2-py2.5-linux-i686.egg#sha256=a740cba0b2dc4d628ce106b5ddeefa7fb82c62f99dcd66ab40f1d7d3637a7b63 (from https://pypi.org/simple/mysql-python/); unsupported archive format: .egg
    Skipping link https://files.pythonhosted.org/packages/b0/12/68620c27126815217264c89c74b22171b366bf48230a6a99622d0414baa5/MySQL_python-1.2.3b2-py2.6-linux-i686.egg#sha256=90228ec7abbf144565c3b164fe1c6aa132d63421bf49f3f2512da8da2a3557bd (from https://pypi.org/simple/mysql-python/); unsupported archive format: .egg
    Found link https://files.pythonhosted.org/packages/c8/8f/aedf47a2e973a2d2f225ac98537472fc928ad61b9647fb370870404c594b/MySQL-python-1.2.3c1.tar.gz#sha256=1faa4977e9850731e8b7f8a1d58b8627393a3744543788ec437fb45e06cfe401 (from https://pypi.org/simple/mysql-python/), version: 1.2.3c1
    Skipping link https://files.pythonhosted.org/packages/62/75/70c766d07004c28c400e9336705369ad6a2e7ad90d7e99ec3d31b50f4316/MySQL_python-1.2.3c1-py2.5-linux-i686.egg#sha256=74491697bed98f8ca91401827c49822e1eb2ba0273759a4d0b382172fd367a38 (from https://pypi.org/simple/mysql-python/); unsupported archive format: .egg
    Skipping link https://files.pythonhosted.org/packages/c3/a3/e4e654d205d264c548235fa230eaee2ed404678835f7a2f937860d66b418/MySQL_python-1.2.3c1-py2.6-linux-i686.egg#sha256=f998823b7a6f00e5f8421eb062355c4d50ac7e4ab85d65382a7e56895f42052d (from https://pypi.org/simple/mysql-python/); unsupported archive format: .egg
    Found link https://files.pythonhosted.org/packages/9a/81/924d6799494cf7fb24370335c2f782088d6ac4f79e4137d4df94cea3582c/MySQL-python-1.2.3.tar.gz#sha256=7de66fbbf923634e7c965aeaefa74642ba75ae20ee1cefcefc3009595b7a7e6e (from https://pypi.org/simple/mysql-python/), version: 1.2.3
    Found link https://files.pythonhosted.org/packages/bc/5f/915c647f6b4aabb65b36296643f2e90fcb7986be35f602d0caa4b7a57cc7/MySQL-python-1.2.4b1.tar.gz#sha256=3ff7260b58b00e78155d8670ad2c9d46871d532bcb825b5a5cd33e3668fd38c5 (from https://pypi.org/simple/mysql-python/), version: 1.2.4b1
    Skipping link https://files.pythonhosted.org/packages/ea/68/7f718d209aed8b117f6d4c8e27194fc63cb900d612799301aceb93204be6/MySQL-python-1.2.4b1.win32-py2.7.exe#sha256=f82ea398625a605b2d0952f7166eef6f9bd393e94d1c3a958a2e35c38678c0dd (from https://pypi.org/simple/mysql-python/); unsupported archive format: .exe
    Found link https://files.pythonhosted.org/packages/c6/0b/a213f0abd7a4d2038af5565f2e83aa8f72d16e122eb0a1e98fed469b0361/MySQL-python-1.2.4b2.tar.gz#sha256=003c79a3db6a249b70ebb0c4cb9b604d0c67216d9fc192f12c64270bfbe20ff3 (from https://pypi.org/simple/mysql-python/), version: 1.2.4b2
    Skipping link https://files.pythonhosted.org/packages/36/f4/044085299e6772dae18714e511251f8a815b51cc60c21d5287ae22f2b3e0/MySQL-python-1.2.4b2.win32-py2.7.exe#sha256=b182b635eda9b412af7955682b974e09762e7bb9411384a4c1fbeb9e1e59fa44 (from https://pypi.org/simple/mysql-python/); unsupported archive format: .exe
    Found link https://files.pythonhosted.org/packages/dd/9a/c69feb14eb5c6b3e17ffc7d24e515fef2add87322bbc4e5a02eeea175dec/MySQL-python-1.2.4b3.tar.gz#sha256=d95bafdfa2ddca75bc0a412d14a0907e0fe0b0e3afba7be516a90589376b7408 (from https://pypi.org/simple/mysql-python/), version: 1.2.4b3
    Skipping link https://files.pythonhosted.org/packages/3c/c4/0a4facd4af2537cce63aceb8049e67a5c9b376eb094593dc1d7f443e78be/MySQL-python-1.2.4b3.win32-py2.7.exe#sha256=3a4c7ba9c5b1b2d909569e1ab5dc40d5de6be906bddac7b47898694502c46a5e (from https://pypi.org/simple/mysql-python/); unsupported archive format: .exe
    Found link https://files.pythonhosted.org/packages/57/11/9215987060b0c3981b9d7a0b16dc4f2588522e7819f484086e0c46bb7fb3/MySQL-python-1.2.4b3.zip#sha256=9ca465a0cedc3acee9af6c659d68740850600b3f5ba0be60f1e6286549257082 (from https://pypi.org/simple/mysql-python/), version: 1.2.4b3
    Found link https://files.pythonhosted.org/packages/ee/be/203071bba1a90bd428c2f466dad1426bad5f27844de0016ffdce3b28921c/MySQL-python-1.2.4b4.tar.gz#sha256=512844e11a0e788db2177deb32196099e3a7d749713a4e28d01186a9df0dc68f (from https://pypi.org/simple/mysql-python/), version: 1.2.4b4
    Skipping link https://files.pythonhosted.org/packages/94/ea/b3bbfb326d754dcf1ceaa558d634af87f3f6aa6dfa54a771a8b8a01ff892/MySQL-python-1.2.4b4.win32-py2.7.exe#sha256=fbf53615ed884e887946d98f3fa5a852f48faafec24e11f7e6bf9e3bba1580fc (from https://pypi.org/simple/mysql-python/); unsupported archive format: .exe
    Found link https://files.pythonhosted.org/packages/b2/be/8847f0522fb66832885a19010de54e232408a6654af79bad5980e0a4bb41/MySQL-python-1.2.4b4.zip#sha256=46a6d87884fe25d4ec3f814d71e8d46562ac201563d72b581ffce1f8e094b010 (from https://pypi.org/simple/mysql-python/), version: 1.2.4b4
    Found link https://files.pythonhosted.org/packages/5a/f4/71d7ce0ca43833a55d4a5c39b011bbf4c89f060be719ff0d8e2cb688be84/MySQL-python-1.2.4b5.tar.gz#sha256=0a7441cf24aec5b9c792d69561444b009702eeb48f3f6bafa6730120290cc190 (from https://pypi.org/simple/mysql-python/), version: 1.2.4b5
    Skipping link https://files.pythonhosted.org/packages/26/c4/990b2bf5572f79c0929312b7fc199d5339a7860df2fc0debb19048c07837/MySQL-python-1.2.4b5.win32-py2.7.exe#sha256=69ef6a62d6f622314c7328d3dc86024a05a408015d3fda6cf25b4143738aa381 (from https://pypi.org/simple/mysql-python/); unsupported archive format: .exe
    Found link https://files.pythonhosted.org/packages/03/c5/9f67c61bf6de708410305f172580f8d123b149fc9f24d25d063a2c393576/MySQL-python-1.2.4b5.zip#sha256=f15dba5aa9b1db8832ed4c85002c84b782e8288e255b48bec46612a08edd0583 (from https://pypi.org/simple/mysql-python/), version: 1.2.4b5
    Skipping link https://files.pythonhosted.org/packages/49/56/97ce5ee8003106a1c0aa9f58191d822a5c14a317bed15d3fa73a86722537/MySQL-python-1.2.4c1.win32-py2.7.exe#sha256=a99e0a77d2ce505275e8d615b4979dadca56d018dfcb673fe17200f85ef295a6 (from https://pypi.org/simple/mysql-python/); unsupported archive format: .exe
    Found link https://files.pythonhosted.org/packages/9a/d4/4d7ceed182e5930335ec8c94a5d786f0d9f5dd4326f397877ede2c511d9e/MySQL-python-1.2.4c1.zip#sha256=f5e01643eb597e71bdf3313c185f0ced94363b1e0854b6e492bf6207e791c6ed (from https://pypi.org/simple/mysql-python/), version: 1.2.4c1
    Skipping link https://files.pythonhosted.org/packages/2f/75/35dad3542f4dc1e679c6c044dc6fffa73c49f1c9e49fb6c8126aacf67b46/MySQL-python-1.2.4.win32-py2.7.exe#sha256=ba0d23ea57fa507d6b0fffe778b7fdc2c122f31539feffbc52fc690083295f31 (from https://pypi.org/simple/mysql-python/); unsupported archive format: .exe
    Found link https://files.pythonhosted.org/packages/90/5a/ce7bef80825c2188cf507baf57b37516e18dffdb198a6766a597f703059a/MySQL-python-1.2.4.zip#sha256=e405f9d6be33923d428acaa4db4f4470427f1d15ea0d2d82a933449ace26bbd9 (from https://pypi.org/simple/mysql-python/), version: 1.2.4
    Skipping link https://files.pythonhosted.org/packages/27/06/596ae3afeefc0cda5840036c42920222cb8136c101ec0f453f2e36df12a0/MySQL-python-1.2.5.win32-py2.7.exe#sha256=ab22d1322099098730a57fd59d610f60738f95a1cb68dacca2d1c47cb0cbe8ee (from https://pypi.org/simple/mysql-python/); unsupported archive format: .exe
    Found link https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip#sha256=811040b647e5d5686f84db415efd697e6250008b112b6909ba77ac059e140c74 (from https://pypi.org/simple/mysql-python/), version: 1.2.5
  Using version 1.2.5 (newest of versions: 1.2.3, 1.2.4, 1.2.5)
  Created temporary directory: /private/var/folders/_t/4fb22psj4079hxxtjj3bqt31b8jsc8/T/pip-unpack-l99ual
  Looking up "https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip" in the cache
  Ignoring unknown cache-control directive:
  No cache entry available
  Starting new HTTPS connection (1): files.pythonhosted.org
  https://files.pythonhosted.org:443 "GET /packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip HTTP/1.1" 200 108935
  Downloading https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip (108kB)
  Downloading from URL https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip#sha256=811040b647e5d5686f84db415efd697e6250008b112b6909ba77ac059e140c74 (from https://pypi.org/simple/mysql-python/)
  Ignoring unknown cache-control directive:
  Ignoring unknown cache-control directive: immutable
  Updating cache with response from "https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip"
  Caching due to etag
  Running setup.py (path:/private/var/folders/_t/4fb22psj4079hxxtjj3bqt31b8jsc8/T/pip-install-m6iEmd/mysql-python/setup.py) egg_info for package mysql-python
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_t/4fb22psj4079hxxtjj3bqt31b8jsc8/T/pip-install-m6iEmd/mysql-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 53, in get_config
        libraries = [ dequote(i[2:]) for i in libs if i.startswith(compiler_flag("l")) ]
      File "setup_posix.py", line 8, in dequote
        if s[0] in "\"'" and s[0] == s[-1]:
    IndexError: string index out of range
Cleaning up...
  Removing source in /private/var/folders/_t/4fb22psj4079hxxtjj3bqt31b8jsc8/T/pip-install-m6iEmd/mysql-python
Exception information:
Traceback (most recent call last):
  File "/Users/user/src/proj/temp/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/Users/user/src/proj/temp/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/Users/user/src/proj/temp/lib/python2.7/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/Users/user/src/proj/temp/lib/python2.7/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/user/src/proj/temp/lib/python2.7/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/Users/user/src/proj/temp/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 324, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/Users/user/src/proj/temp/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 154, in prep_for_dist
    self.req.run_egg_info()
  File "/Users/user/src/proj/temp/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 486, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Users/user/src/proj/temp/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_t/4fb22psj4079hxxtjj3bqt31b8jsc8/T/pip-install-m6iEmd/mysql-python/

Error:  An error occurred while installing mysql-python!
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_t/4fb22psj4079hxxtjj3bqt31b8jsc8/T/pip-install-m6iEmd/mysql-python/

This is likely caused by a bug in mysql-python. Report this to its maintainers.

```

**Comment by uranusjr** [comment]
Wait, how did you get that wheel? I don’t see any wheels provided by MySQL-Python on PyPI.

**Comment by techalchemy** [comment]
Yeah there is no wheel on PyPI. If you have a local wheel you want to install you will need to expose the folder with `PIP_FIND_LINKS` or just install the path directly. Sorry for the frustration and thanks for the report!

**Comment by dresnick-sf** [comment]
Sorry about that. Was it previously automatically built on my mac and cached? I'm still learning python packaging. Thanks for explaining why it wasn't working.

**Comment by uranusjr** [comment]
based on the log, your environment likely cannot build the wheel though… otherwise egg_info would have failed 🤔

I suggest trying out if `pipenv install mysqlclient` works, and file any problems against it. It is a fork of MySQL-Python, but much better maintained and modern. The usage is completely identical.

https://github.com/PyMySQL/mysqlclient-python
