### ISSUE TITLE
pipenv --completion crashes with jinja2.exceptions.TemplateNotFound: bash.j2 (pipenv==2018.6.25)

### ISSUE THREAD

**Issue by agandrabur** [pypa/pipenv#2447]
Exception when using `pipenv --completion`
------------

Host: ArchLinux

##### Expected result

No Exception

##### Actual result
`
Traceback (most recent call last):
  File "/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==2018.6.25', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/cli.py", line 178, in cli
    print(click_completion.get_code(shell=shell, prog_name='pipenv'))
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click_completion/__init__.py", line 353, in get_code
    template = env.get_template('%s.j2' % shell)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash.j2
`

##### Steps to replicate
`pipenv --completion`

**Comment by techalchemy** [comment]
Thanks for the report. We already merged a fix, see #2422 -- will have a release shortly
