### ISSUE TITLE
Pipevnv 2018.6.5 Breaks Python-openstackclient

### ISSUE THREAD

**Issue by iammcgaber** [pypa/pipenv#2452]
With the recent upgrade to Pipenv 2018.6.5 we are getting the following errors from the Python-openstackclient.

    Failed in branch Ansible Role: Jenkins Instance Provisioner
Traceback (most recent call last):
    File "/home/docker/.local/share/virtualenvs/docker--dI8ArJd/bin/openstack", line 7, in <module>
    from openstackclient.shell import main
    File "/home/docker/.local/share/virtualenvs/docker--dI8ArJd/local/lib/python2.7/site-packages/openstackclient/shell.py", line 23, in <module>
    from osc_lib import shell
    File "/home/docker/.local/share/virtualenvs/docker--dI8ArJd/local/lib/python2.7/site-packages/osc_lib/shell.py", line 33, in <module>
    from osc_lib.cli import client_config as cloud_config
    File "/home/docker/.local/share/virtualenvs/docker--dI8ArJd/local/lib/python2.7/site-packages/osc_lib/cli/client_config.py", line 21, in <module>
    from os_client_config import exceptions as occ_exceptions
    File "/home/docker/.local/share/virtualenvs/docker--dI8ArJd/local/lib/python2.7/site-packages/os_client_config/__init__.py", line 19, in <module>
    from os_client_config import cloud_config
    File "/home/docker/.local/share/virtualenvs/docker--dI8ArJd/local/lib/python2.7/site-packages/os_client_config/cloud_config.py", line 17, in <module>
    from openstack import _log
    File "/home/docker/.local/share/virtualenvs/docker--dI8ArJd/local/lib/python2.7/site-packages/openstack/__init__.py", line 17, in <module>
    import openstack.connection
    File "/home/docker/.local/share/virtualenvs/docker--dI8ArJd/local/lib/python2.7/site-packages/openstack/connection.py", line 164, in <module>
    from openstack import _log
    ImportError: cannot import name _log

I can confidently say that rolling back to the previous version of Pipenv solved this issue.
------------

**Comment by techalchemy** [comment]
Please fill out the full issue template with a detailed report and a reproducible test case so that we can better track down this issue.  The boilerplate is there to help us triage the several hundred issues we have coming in, without it it is quite difficult to determine what exactly is going wrong.

Closing this issue, please file a new one with the above information.
