### ISSUE TITLE
Do a bugfix release

### ISSUE THREAD

**Issue by jakul** [pypa/pipenv#2471]
@techalchemy Can you cut a bugfix release which includes https://github.com/pypa/pipenv/pull/2422? Everytime I open a shell I get an error message and it's driving me crazy:

```
Last login: Thu Jun 28 14:44:32 on ttys001
wotkon serTraceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.6.25/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==2018.6.25', 'console_scripts', 'pipenv')()
  File "/usr/local/Cellar/pipenv/2018.6.25/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.6.25/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/2018.6.25/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/Cellar/pipenv/2018.6.25/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/2018.6.25/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.6.25/libexec/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.6.25/libexec/lib/python3.6/site-packages/pipenv/cli.py", line 178, in cli
    print(click_completion.get_code(shell=shell, prog_name='pipenv'))
  File "/usr/local/Cellar/pipenv/2018.6.25/libexec/lib/python3.6/site-packages/pipenv/vendor/click_completion/__init__.py", line 353, in get_code
    template = env.get_template('%s.j2' % shell)
  File "/usr/local/Cellar/pipenv/2018.6.25/libexec/lib/python3.6/site-packages/pipenv/vendor/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/Cellar/pipenv/2018.6.25/libexec/lib/python3.6/site-packages/pipenv/vendor/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/Cellar/pipenv/2018.6.25/libexec/lib/python3.6/site-packages/pipenv/vendor/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/Cellar/pipenv/2018.6.25/libexec/lib/python3.6/site-packages/pipenv/vendor/jinja2/loaders.py", line 187, in get_source
settings/local_settings.py
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash.j2
```

**Comment by uranusjr** [comment]
We want to. Thanks for the reminder.

**Comment by techalchemy** [comment]
Oh god yeah this is still happening. I’ll get it out today. CI is super slow and really holds us back.
