### ISSUE TITLE
pipenv can not instanciate virtualenv if directory it is running in starts with "-"

### ISSUE THREAD

**Issue by derphilipp** [pypa/pipenv#2486]
------------

##### Issue description

- It is possible to create directories starting with a dash ("-")
- Though highly unpractical this can occur when using CI systems etc.
- Pipenv fails setting up anything inside a directory of that nature, because parameters are parsed wrong (The directory name is considered a parameter because it starts with a dash)

##### Expected result

Pipenv working normally

##### Actual result

Example run on a machine:

```
~/BUILDPATH/-6SOMEDIRECTORYWITHADASH$ pipenv install --verbose
Creating a virtualenv for this project…
Using /usr/bin/python3 (3.6.5) to create virtualenv…
⠋usage: __main__.py [-h] [-p PYTHON] [-i PACKAGES] [-r REQUIREMENTS] [-d]
                   [-a PROJECT]
                   envname
__main__.py: error: the following arguments are required: envname

Virtualenv location:
Creating a virtualenv for this project…
Using /usr/bin/python3 (3.6.5) to create virtualenv…
⠙usage: __main__.py [-h] [-p PYTHON] [-i PACKAGES] [-r REQUIREMENTS] [-d]
                   [-a PROJECT]
                   envname
__main__.py: error: the following arguments are required: envname

Virtualenv location:
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/cli.py", line 402, in install
    selective_upgrade=selective_upgrade,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 1932, in do_install
    requirements_dir=requirements_directory,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 1369, in do_init
    verbose=verbose,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 1043, in do_lock
    allow_global=system,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/utils.py", line 420, in venv_resolve_deps
    escape_grouped_arguments(which('python', allow_global=allow_global)),
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 128, in which
    p = os.sep.join([location] + ['bin/{0}'.format(command)])
TypeError: sequence item 0: expected str instance, NoneType found
USER@SERVER:~/BUILDPATH/-6SOMEDIRECTORYWITHADASH$
```

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

1. create directory starting with a dash
`mkdir -- -foo`
2. enter said directory
`cd -- -foo`
3. start pipenv:
`pipenv install .`

-------------
This is probably not a very high priority for most people but it can lead to broken builds when directories are created automatically;

**Comment by uranusjr** [comment]
Not reproducible. Please follow the issue template so we can understand whether you are running an old version, or if this is caused by an environmental issue.

**Comment by derphilipp** [comment]
I tried it using Ubuntu 18.04, Python 3.6.5:

```
phw@douglas:~$ mkdir -p temp/-invalid
phw@douglas:~$ cd temp/-invalid/
phw@douglas:~/temp/-invalid$ pipenv --version
pipenv, version 2018.7.1

phw@douglas:~/temp/-invalid$ uname -a
Linux douglas 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

phw@douglas:~/temp/-invalid$ python3 --version
Python 3.6.5

phw@douglas:~/temp/-invalid$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"


phw@douglas:~/temp/-invalid$ pipenv install . --three --verbose                                                                                                                                            [23/23]
Creating a virtualenv for this project...
Pipfile: /home/phw/temp/-invalid/Pipfile
Using /usr/bin/python3 (3.6.5) to create virtualenv...
⠋Already using interpreter /usr/bin/python3
Using base prefix '/usr'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/virtualenv.py", line 2343, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/usr/local/lib/python3.6/dist-packages/virtualenv.py", line 927, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python3.6/dist-packages/virtualenv.py", line 1112, in install_python
    mkdir(lib_dir)
  File "/usr/local/lib/python3.6/dist-packages/virtualenv.py", line 324, in mkdir
    os.makedirs(path)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/phw/.local/share/virtualenvs/-invalid-UW4L-zdK'
Error while trying to remove the /home/phw/.local/share/virtualenvs/-invalid-UW4L-zdK env:
No such file or directory

Virtualenv location:
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/cli.py", line 435, in install
    selective_upgrade=selective_upgrade,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 1759, in do_install
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 639, in ensure_project
    ensure_pipfile(validate=validate, skip_requirements=skip_requirements, system=system)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 244, in ensure_pipfile
    python = which('python') if not (USING_DEFAULT_PYTHON or system) else None
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 115, in which
    p = os.path.join(location, 'bin', command)
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by derphilipp** [comment]
Trying it to reproduce via Docker and/or other computers it fails; Closing it for now

**Comment by techalchemy** [comment]
This was specifically addressed in the latest release
