### ISSUE TITLE
Not informative exception message for incorrect line in Pipfile

### ISSUE THREAD

**Issue by lorien** [pypa/pipenv#2525]
##### Issue description

If I use invalid dependency description `tgram = {path = "/web/lib_tgram", editable = True}` (should be `true`, not `True`), then I got IndexError exception that does not help much.
 
##### Expected result

Something like `Hey! Your Pipfile is broken at line #XXX`

##### Actual result

```
$ pipenv install -ve /web/lib_tgram
Installing -e /web/lib_tgram…

... few lines skipped ...

Successfully installed tgram
Cleaning up...

Adding -e /web/lib_tgram to Pipfile's [packages]…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/lorien/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/lorien/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/lorien/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lorien/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lorien/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/lorien/.local/lib/python2.7/site-packages/pipenv/cli.py", line 366, in install
    selective_upgrade=selective_upgrade,
  File "/home/lorien/.local/lib/python2.7/site-packages/pipenv/core.py", line 1996, in do_install
    requirements_dir=requirements_directory,
  File "/home/lorien/.local/lib/python2.7/site-packages/pipenv/core.py", line 1321, in do_init
    p = pipfile.load(project.pipfile_location)
  File "/home/lorien/.local/lib/python2.7/site-packages/pipenv/patched/pipfile/api.py", line 223, in load
    return Pipfile.load(filename=pipfile_path, inject_env=inject_env)
  File "/home/lorien/.local/lib/python2.7/site-packages/pipenv/patched/pipfile/api.py", line 154, in load
    pipfile.data = p.parse(inject_env=inject_env)
  File "/home/lorien/.local/lib/python2.7/site-packages/pipenv/patched/pipfile/api.py", line 102, in parse
    parsed = toml.loads(content)
  File "/home/lorien/.local/lib/python2.7/site-packages/pipenv/vendor/toml.py", line 373, in loads
    multibackslash)
  File "/home/lorien/.local/lib/python2.7/site-packages/pipenv/vendor/toml.py", line 478, in _load_line
    value, vtype = _load_value(pair[1], _dict, strictly_valid)
  File "/home/lorien/.local/lib/python2.7/site-packages/pipenv/vendor/toml.py", line 640, in _load_value
    _load_inline_object(v, inline_object, _dict)
  File "/home/lorien/.local/lib/python2.7/site-packages/pipenv/vendor/toml.py", line 398, in _load_inline_object
    candidate_groups[0] = candidate_group + "," + candidate_groups[0]
IndexError: list index out of range
/home/lorien/.local/lib/python2.7/site-packages/pipenv/utils.py:1230: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-MZT2mQ-requirements'>
  warnings.warn(warn_message, ResourceWarning)
```
##### Steps to replicate

Use some local dependency with invalid option `editable = True`, for example: `tgram = {path = "/web/lib_tgram", editable = True}`

-------------

> Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

```
$ pipenv --support
Error: no such option: --support
```

**Comment by uranusjr** [comment]
Similar to #2362, but different. This one should be much easier to implement (just wrap the parser call and emit a new message).

**Comment by Kacppian** [comment]
Can I work on this?

**Comment by uranusjr** [comment]
please do!

**Comment by pfctdayelise** [comment]
@Kacppian do you still intend to work on this?

**Comment by aidin36** [comment]
There's a better error in `master` now.

```
Traceback (most recent call last):
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/vendor/toml/decoder.py", line 456, in loads
    multibackslash)
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/vendor/toml/decoder.py", line 725, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/vendor/toml/decoder.py", line 805, in load_value
    self.load_inline_object(v, inline_object)
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/vendor/toml/decoder.py", line 621, in load_inline_object
    raise ValueError("Invalid inline table value encountered")
ValueError: Invalid inline table value encountered

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/__main__.py", line 4, in <module>
    cli()
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/cli/command.py", line 249, in install
    editable_packages=state.installstate.editables,
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/core.py", line 1976, in do_install
    skip_lock=skip_lock,
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/core.py", line 1274, in do_init
    pypi_mirror=pypi_mirror,
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/core.py", line 983, in do_lock
    lockfile = project._lockfile
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/project.py", line 550, in _lockfile
    pfile = pipfile.load(self.pipfile_location, inject_env=False)
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/patched/pipfile/api.py", line 230, in load
    return Pipfile.load(filename=pipfile_path, inject_env=inject_env)
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/patched/pipfile/api.py", line 161, in load
    pipfile.data = p.parse(inject_env=inject_env)
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/patched/pipfile/api.py", line 109, in parse
    parsed = toml.loads(content)
  File "/home/aidin/workspace/aidin36/pipenv/pipenv/vendor/toml/decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Invalid inline table value encountered (line 7 column 1 char 87)
```

**Comment by uranusjr** [comment]
I think it can still improve by printing the actual offending line (or even mark the character; I don’t ever want to count to char 87 by hand, for example).

**Comment by frostming** [comment]
Reviewed, this issue has already fixed by the `tomlkit` parser. Close it now.
