### ISSUE TITLE
Redirecting stdout to NUL (Windows) raises exception

### ISSUE THREAD

**Issue by uranusjr** [pypa/pipenv#2555]
I’m not sure if this is a bug in Pipenv. Crayon, Click, or even Python, but I need to log it somewhere.

Discovered https://github.com/pypa/pipenv/issues/2527#issuecomment-403836587.

To reproduce:

```
λ pipenv >NUL
Traceback (most recent call last):
  File "C:\Users\uranusjr\Documents\programming\pipenv\.venv\Scripts\pipenv-script.py", line 11, in <module>
    load_entry_point('pipenv', 'console_scripts', 'pipenv')()
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\vendor\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\vendor\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\cli.py", line 1017, in sync
    pypi_mirror=pypi_mirror,
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\core.py", line 2545, in do_sync
    system=system,
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\core.py", line 1330, in do_init
    pypi_mirror=pypi_mirror,
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\core.py", line 767, in do_install_dependencies
    bold=True,
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\vendor\click\utils.py", line 259, in echo
    file.write(message)
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\vendor\click\_compat.py", line 577, in _safe_write
    return _write(s)
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\vendor\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\vendor\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\vendor\colorama\ansitowin32.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\vendor\colorama\ansitowin32.py", line 175, in write_plain_text
    self.wrapped.flush()
  File "c:\users\uranusjr\documents\programming\pipenv\pipenv\vendor\click\_winconsole.py", line 164, in write
    raise OSError(self._get_error_message(GetLastError()))
OSError: Windows error 1
```

I believe any command that outputs to stdout (i.e. all of them) has this problem. Stderr works fine. I do not know whether Linux and macOS has this problem.

**Comment by uranusjr** [comment]
Seems to work on WSL, I assume it is a Windows-only problem, and is from an upstream library (likely Click).

**Comment by uranusjr** [comment]
Tracked in pallets/click#1065 instead.
