### ISSUE TITLE
Locking does not take pinned prerelease version of a dependency, but reverts to latest stable version

### ISSUE THREAD

**Issue by zupo** [pypa/pipenv#2598]
##### Issue description

Installation of `repoze.workflow==1.0b1 repoze.zcml==1.0b1` on Python 3.7 fails because when doing locking, pipenv incorrectly takes the latest stable `repoze.zcml==0.4`, runs `python setup.py egg_info` on it and fails due to a syntax error in `setup.py`/`ez_setup.py`. 

How do I know it takes `repoze.zcml==0.4`? Well in the traceback below you see this:

```
  Running setup.py (path:/private/var/folders/ck/dlscb24n4lzdlzpt3w0pdcgh0000gn/T/pip-install-nmd9li96/repoze.zcml/setup.py) egg_info for package repoze.zcml
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ck/dlscb24n4lzdlzpt3w0pdcgh0000gn/T/pip-install-nmd9li96/repoze.zcml/setup.py", line 19, in <module>
        from ez_setup import use_setuptools
      File "/private/var/folders/ck/dlscb24n4lzdlzpt3w0pdcgh0000gn/T/pip-install-nmd9li96/repoze.zcml/ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
```

The 0.4 repoze.zcml contains the [ez_setup.py file](https://github.com/repoze/repoze.zcml/blob/1d77f50121a8e0c4e42cbad5c6ecbfe98ad05f0d/ez_setup.py).

The 1.0b1 repoze.zcml's [does not](https://github.com/repoze/repoze.zcml/tree/3d8005f6f842f6c0d70cdb5614fba58ab6a70726).

Same error happens on Python 3.6.

##### Expected result

Installation & locking is successful:

```
repoze$ pipenv install repoze.zcml==1.0b1 repoze.workflow==1.0b1 --three
...
tmp$ mkdir repoze
tmp$ cd repoze/
repoze$ pipenv install --three --verbose repoze.workflow==1.0b1 repoze.zcml==1.0b1
Creating a virtualenv for this project...
Pipfile: /private/tmp/repoze/Pipfile
Using /usr/local/bin/python3 (3.7.0) to create virtualenv...
[... snip ...]
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Updated Pipfile.lock (42ab63)!
Installing dependencies from Pipfile.lock (42ab63)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 8/8 — 00:00:02
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

##### Actual result

```
tmp$ mkdir repoze
tmp$ pipenv install --three --verbose repoze.workflow==1.0b1 repoze.zcml==1.0b1
Creating a virtualenv for this project...
Pipfile: /private/tmp/Pipfile
Using /usr/local/bin/python3 (3.7.0) to create virtualenv...
⠋Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7'
/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /private/tmp/.venv/bin/python3.7
Also creating executable in /private/tmp/.venv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /private/tmp/.venv
Creating a Pipfile for this project...
Installing repoze.workflow==1.0b1...
⠙Installing 'repoze.workflow==1.0b1'
$ "/private/tmp/.venv/bin/pip" install   --verbose    "repoze.workflow==1.0b1" -i https://pypi.org/simple --exists-action w
Created temporary directory: /private/var/folders/ck/dlscb24n4lzdlzpt3w0pdcgh0000gn/T/pip-ephem-wheel-cache-vyoi5tm2
Created temporary directory: /private/var/folders/ck/dlscb24n4lzdlzpt3w0pdcgh0000gn/T/pip-install-nmd9li96
Collecting repoze.workflow==1.0b1
  1 location(s) to search for versions of repoze.workflow:
  * https://pypi.org/simple/repoze-workflow/
  Getting page https://pypi.org/simple/repoze-workflow/
  Looking up "https://pypi.org/simple/repoze-workflow/" in the cache
  Current age based on date: 366
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 366
  Analyzing links from page https://pypi.org/simple/repoze-workflow/
    Found link https://files.pythonhosted.org/packages/39/7d/43c883e0414f0e989c19b199fc40c6a427820696f58bff02e0f3870c2889/repoze.workflow-0.2.tar.gz#sha256=c73a13f0266eee7d92d22ccaf88330be2d7c24811e5a8f7984c6ffafa430db50 (from https://pypi.org/simple/repoze-workflow/), version: 0.2
    Found link https://files.pythonhosted.org/packages/76/da/4898ffc54b7237c4d4c1192e06bae1a5a13ffd82d6fad5dbd04f015834cd/repoze.workflow-0.3.tar.gz#sha256=a77161301120bd442e936df9a797aa6bd20289c180473eea396f016b2a11dcd7 (from https://pypi.org/simple/repoze-workflow/), version: 0.3
    Found link https://files.pythonhosted.org/packages/9d/c2/30b4e59d673af2b51257ac74f5442e1772f9419938dcb2401f3ba0567012/repoze.workflow-0.4.tar.gz#sha256=2131dfc31413eba5547ab03bf671381dc507477ff2515e534eb7d457ebaf998e (from https://pypi.org/simple/repoze-workflow/), version: 0.4
    Found link https://files.pythonhosted.org/packages/fe/08/5520ad8d6e82acaa3bbde4b72f9c88714ff06b0e0e3414494005cfe0342c/repoze.workflow-0.5.tar.gz#sha256=b80e69a81d6922f459b147eb42f3d8a5a2144a0959bae94aab6ef3900571d709 (from https://pypi.org/simple/repoze-workflow/), version: 0.5
    Found link https://files.pythonhosted.org/packages/bc/0e/8cf20a12b9082154baeb1a33062fc10ebf0357745922dd73e2739c4babcd/repoze.workflow-0.6.1.tar.gz#sha256=0251ace0a68696abef24ecf1cb4c9dfbf29ecaaa60fd30500f60eaf3c79bbf47 (from https://pypi.org/simple/repoze-workflow/), version: 0.6.1
    Found link https://files.pythonhosted.org/packages/86/20/5970a894393ca4ae95c949703af4d45db96134bfe70f7a9a068fb4b3fcac/repoze.workflow-1.0b1.tar.gz#sha256=06b49de7b7d256a1b393a80a5336048312c21e7d0386b7529b7509dfb3b6e2e2 (from https://pypi.org/simple/repoze-workflow/), version: 1.0b1
  Using version 1.0b1 (newest of versions: 1.0b1)
  Using cached wheel link: file:///Users/zupo/Library/Caches/pipenv/wheels/32/ba/38/9a87c6b396b8117ff1162b4eb3783e0f0f5d972e8a7db9a99e/repoze.workflow-1.0b1-cp37-none-any.whl
Collecting zope.configuration>=3.8.0 (from repoze.workflow==1.0b1)
  1 location(s) to search for versions of zope.configuration:
  * https://pypi.org/simple/zope-configuration/
  Getting page https://pypi.org/simple/zope-configuration/
  Looking up "https://pypi.org/simple/zope-configuration/" in the cache
  Current age based on date: 366
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 366
  Analyzing links from page https://pypi.org/simple/zope-configuration/
    Skipping link https://files.pythonhosted.org/packages/0a/5c/0f1ca5ad1671d613072141f03e2b23cd27a037fa48ec3248805432c4eb02/zope.configuration-3.4dev_r72952-py2.4.egg#sha256=dc9de9d250696c517fe1b211324d845e0e3ebd44a8a4ca85c9b619e0899410cf (from https://pypi.org/simple/zope-configuration/); unsupported archive format: .egg
    Found link https://files.pythonhosted.org/packages/a6/6f/f76c4b438899c8544a959878196045b739a9e3ec61e8b6222d3499a8a8ee/zope.configuration-3.4.0.tar.gz#sha256=f043f10495bc02d3c8051890ee39be8c1a2a4e9914fd9b25cae3c255798c97e6 (from https://pypi.org/simple/zope-configuration/), version: 3.4.0
    Found link https://files.pythonhosted.org/packages/32/09/fe6e43b62adf1f308b4d39dfc77fbb02b1e55ad116bdd62e84b3895a77db/zope.configuration-3.4.1.tar.gz#sha256=acec760d1519438dd575b02b086130459e67ea8707569f6457de84fd5a19044f (from https://pypi.org/simple/zope-configuration/), version: 3.4.1
    Found link https://files.pythonhosted.org/packages/e3/68/a1194c4eaac6078e172fe7643a25a8614730b928a4d84070f5afccd4499f/zope.configuration-3.5.0.tar.gz#sha256=2b45574328d5ce1a6729d9d92121c95bbeb2267c50c394ec54712302eef19011 (from https://pypi.org/simple/zope-configuration/), version: 3.5.0
    Found link https://files.pythonhosted.org/packages/21/43/53e7cb6d13337a9289b2f508a99a2e8ce0a7e24246134552b5a0fbffe784/zope.configuration-3.6.0.tar.gz#sha256=a18e57267562da177825a23f3ab6304b7aafc904b9c3799761f07c0925a079f5 (from https://pypi.org/simple/zope-configuration/), version: 3.6.0
    Found link https://files.pythonhosted.org/packages/4c/f1/2a2ba44fadd8a5fa279826d58209ade9d9f4d522e613d4d27c8fc124db73/zope.configuration-3.7.0.zip#sha256=9fe3e14a7557bdbdf8b8465013e017fbcfd1b3f67ca05fb93a4fa665b061811d (from https://pypi.org/simple/zope-configuration/), version: 3.7.0
    Found link https://files.pythonhosted.org/packages/4f/99/9786963b062534ec21edac80ea4c60393ee4337bbd63fff763e2621765d3/zope.configuration-3.7.1.tar.gz#sha256=8841fe8b8b13b85452df9c43d4d4c2c99b61c8778d5f32a7390550e16ba90a0e (from https://pypi.org/simple/zope-configuration/), version: 3.7.1
    Found link https://files.pythonhosted.org/packages/bd/d4/211a29aeed88e9c79ccb8594bfc5374d12ed44aadc54054189a266ab860c/zope.configuration-3.7.2.zip#sha256=e6469e84472411333c98520f60b5223abf28ae62e617635af88c09ec0cbc1520 (from https://pypi.org/simple/zope-configuration/), version: 3.7.2
    Found link https://files.pythonhosted.org/packages/13/c8/520efd81f1d7fad4232c1e209b35d194b7fb2b4c7c76c24dd3a4b6fad5b2/zope.configuration-3.7.3.zip#sha256=d0fd3e8089b2bbf56927e5633417dcd778637de08733e72d0b93db7bb61d77fd (from https://pypi.org/simple/zope-configuration/), version: 3.7.3
    Found link https://files.pythonhosted.org/packages/a7/16/32f278e57310fd167926f0297ec0e24fd66cc7e6b04fd1c853e282a07a5e/zope.configuration-3.7.4.zip#sha256=1cb7e757ee282fe25eecaf9bf6a5e8715025bc7c6c4374a996879cd5a24c9249 (from https://pypi.org/simple/zope-configuration/), version: 3.7.4
    Found link https://files.pythonhosted.org/packages/fe/14/0d7a28ffae8b1b655ab639064d718a744cd14636826d481dcbbf0b78377d/zope.configuration-3.8.0.tar.gz#sha256=715b1a669a49d1968165ad6ce4dd7ae206df9289ffa0376bf71466c88a0ff4c1 (from https://pypi.org/simple/zope-configuration/), version: 3.8.0
    Found link https://files.pythonhosted.org/packages/8e/b1/1bc85c58a046ea3955299d8ccc375cc9650e17ffe4a0cd9648f256eaceb3/zope.configuration-3.8.1.tar.gz#sha256=4f436195f4cc8054b867d20ddb07346a3181d866556407f84da704a227b85ae5 (from https://pypi.org/simple/zope-configuration/), version: 3.8.1
    Found link https://files.pythonhosted.org/packages/92/ef/015422281097226df0ab3b8728b5755defdd92fe952e4554b39a2e173432/zope.configuration-4.0.0.tar.gz#sha256=2bd4567ccdee416230121d6f30c4afca999e99b93c4e6a51f9dd034e34beb23f (from https://pypi.org/simple/zope-configuration/), version: 4.0.0
    Found link https://files.pythonhosted.org/packages/e8/bd/3abedab93bec44866c79f2716eb586250a2d30e0eca09e4b9461da1320f3/zope.configuration-4.0.1.tar.gz#sha256=2c1a936e16388124aafa34e650f02c216542f720d4f2e117455a0f3000ffec56 (from https://pypi.org/simple/zope-configuration/), version: 4.0.1
    Found link https://files.pythonhosted.org/packages/5b/33/ed60a66537694e668de4c33b2d52c464280450890ff04a0b45f89b6a64e5/zope.configuration-4.0.2.tar.gz#sha256=c8a496fa9fad6d39ec1a46fe2b59cf47a6d159e4bc3293f3850e725a1b83fc6d (from https://pypi.org/simple/zope-configuration/), version: 4.0.2
    Found link https://files.pythonhosted.org/packages/37/d7/653c2a05d876e787a1532b51ef7f89917ff17885daaac41af9da5e2f140b/zope.configuration-4.0.3.tar.gz#sha256=b6f0f718597945fc6fda7aee72dab9636302fb2035dd222ab5b7fa773d762df5 (from https://pypi.org/simple/zope-configuration/), version: 4.0.3
    Found link https://files.pythonhosted.org/packages/57/d5/c1944d487626698418aca0c5f08541e0f96bbaae358e09a8da8f9325759a/zope.configuration-4.1.0-py2.py3-none-any.whl#sha256=623295cf552035940a4605b06f3a5b2f63495e078a914b3272153de350baa1bc (from https://pypi.org/simple/zope-configuration/), version: 4.1.0
    Found link https://files.pythonhosted.org/packages/be/1b/84b54ec99c92ab4db6185c1b334329d717ab6e42eb8f59c63ea3f5d6591b/zope.configuration-4.1.0.tar.gz#sha256=eebea03062b9d7ddd512a31412bcdf3549aa2dff481503487067dbbd06774050 (from https://pypi.org/simple/zope-configuration/), version: 4.1.0
  Using version 4.1.0 (newest of versions: 3.8.0, 3.8.1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0)
  Created temporary directory: /private/var/folders/ck/dlscb24n4lzdlzpt3w0pdcgh0000gn/T/pip-unpack-v3udrvej
  Looking up "https://files.pythonhosted.org/packages/57/d5/c1944d487626698418aca0c5f08541e0f96bbaae358e09a8da8f9325759a/zope.configuration-4.1.0-py2.py3-none-any.whl" in the cache
  Ignoring unknown cache-control directive: 
  Current age based on date: 5131
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 5131
  Using cached https://files.pythonhosted.org/packages/57/d5/c1944d487626698418aca0c5f08541e0f96bbaae358e09a8da8f9325759a/zope.configuration-4.1.0-py2.py3-none-any.whl
  Downloading from URL https://files.pythonhosted.org/packages/57/d5/c1944d487626698418aca0c5f08541e0f96bbaae358e09a8da8f9325759a/zope.configuration-4.1.0-py2.py3-none-any.whl#sha256=623295cf552035940a4605b06f3a5b2f63495e078a914b3272153de350baa1bc (from https://pypi.org/simple/zope-configuration/)
Collecting repoze.zcml (from repoze.workflow==1.0b1)
  1 location(s) to search for versions of repoze.zcml:
  * https://pypi.org/simple/repoze-zcml/
  Getting page https://pypi.org/simple/repoze-zcml/
  Looking up "https://pypi.org/simple/repoze-zcml/" in the cache
  Current age based on date: 366
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 366
  Analyzing links from page https://pypi.org/simple/repoze-zcml/
    Found link https://files.pythonhosted.org/packages/26/f7/b4e4a4096e8380457febb5a1e3e47c90977aa39e3c1db8b5cc96e19eb52c/repoze.zcml-0.1.tar.gz#sha256=9372f63a6d870c09628073659875fb38127aa8fd81f166cf567cf51a05438f29 (from https://pypi.org/simple/repoze-zcml/), version: 0.1
    Found link https://files.pythonhosted.org/packages/2d/02/e915725b4e50c926477c7fdf642e0fa556ba5c3495fb4a8bfd5705655f85/repoze.zcml-0.2.tar.gz#sha256=b2c972a884532b14816114f866fa4453ef8be0c4b52dcd68e3baa6c880424d72 (from https://pypi.org/simple/repoze-zcml/), version: 0.2
    Found link https://files.pythonhosted.org/packages/95/a4/6372d02255c7dbc46b4697e956469542a34292152a91c1a4c5d606d4117e/repoze.zcml-0.3.tar.gz#sha256=5f7d558e843537b04a9cbfe430b4d4dfff4752e317c2c31da19578279e23ddbe (from https://pypi.org/simple/repoze-zcml/), version: 0.3
    Found link https://files.pythonhosted.org/packages/5c/17/8b78c892a07ed6af213ac192d9b9dde19e24eab2719376751f69c3c0d8c3/repoze.zcml-0.4.tar.gz#sha256=f59feb7303111f5ccc2a862ba35266768189b0f6e3f33c20cc24878800b247a7 (from https://pypi.org/simple/repoze-zcml/), version: 0.4
    Found link https://files.pythonhosted.org/packages/60/4a/665caf16c988c68f701ae40d992eb447452ee3de61910fc7f3ceb7093ea3/repoze.zcml-1.0b1.tar.gz#sha256=856b4836149731de0e6946988d055d124de45fc960a5309f70e12ef224631637 (from https://pypi.org/simple/repoze-zcml/), version: 1.0b1
  Using version 0.4 (newest of versions: 0.1, 0.2, 0.3, 0.4)
  Created temporary directory: /private/var/folders/ck/dlscb24n4lzdlzpt3w0pdcgh0000gn/T/pip-unpack-ewna226y
  Looking up "https://files.pythonhosted.org/packages/5c/17/8b78c892a07ed6af213ac192d9b9dde19e24eab2719376751f69c3c0d8c3/repoze.zcml-0.4.tar.gz" in the cache
  Ignoring unknown cache-control directive: 
  Current age based on date: 5118
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 5118
  Using cached https://files.pythonhosted.org/packages/5c/17/8b78c892a07ed6af213ac192d9b9dde19e24eab2719376751f69c3c0d8c3/repoze.zcml-0.4.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/5c/17/8b78c892a07ed6af213ac192d9b9dde19e24eab2719376751f69c3c0d8c3/repoze.zcml-0.4.tar.gz#sha256=f59feb7303111f5ccc2a862ba35266768189b0f6e3f33c20cc24878800b247a7 (from https://pypi.org/simple/repoze-zcml/)
  Running setup.py (path:/private/var/folders/ck/dlscb24n4lzdlzpt3w0pdcgh0000gn/T/pip-install-nmd9li96/repoze.zcml/setup.py) egg_info for package repoze.zcml
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ck/dlscb24n4lzdlzpt3w0pdcgh0000gn/T/pip-install-nmd9li96/repoze.zcml/setup.py", line 19, in <module>
        from ez_setup import use_setuptools
      File "/private/var/folders/ck/dlscb24n4lzdlzpt3w0pdcgh0000gn/T/pip-install-nmd9li96/repoze.zcml/ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
Cleaning up...
  Removing source in /private/var/folders/ck/dlscb24n4lzdlzpt3w0pdcgh0000gn/T/pip-install-nmd9li96/repoze.zcml
Exception information:
Traceback (most recent call last):
  File "/private/tmp/.venv/lib/python3.7/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/private/tmp/.venv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 291, in run
    resolver.resolve(requirement_set)
  File "/private/tmp/.venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 103, in resolve
    self._resolve_one(requirement_set, req)
  File "/private/tmp/.venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 257, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/private/tmp/.venv/lib/python3.7/site-packages/pip/_internal/resolve.py", line 210, in _get_abstract_dist_for
    self.require_hashes
  File "/private/tmp/.venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 324, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/private/tmp/.venv/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 154, in prep_for_dist
    self.req.run_egg_info()
  File "/private/tmp/.venv/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 486, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/private/tmp/.venv/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 698, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ck/dlscb24n4lzdlzpt3w0pdcgh0000gn/T/pip-install-nmd9li96/repoze.zcml/

Error:  An error occurred while installing repoze.workflow==1.0b1!
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ck/dlscb24n4lzdlzpt3w0pdcgh0000gn/T/pip-install-nmd9li96/repoze.zcml/

This is likely caused by a bug in repoze.workflow==1.0b1. Report this to its maintainers.
tmp$ 

```

##### Steps to replicate

```
tmp$ mkdir repoze
tmp$ cd repoze/
repoze$ pipenv install --three --verbose repoze.workflow==1.0b1 repoze.zcml==1.0b1

```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.7.1/libexec/bin/python3.7'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.7`: `/usr/local/bin/python3.7m`
  - `3.7`: `/usr/local/bin/python3.7`
  - `3.7`: `/usr/local/bin/python3.7`

  - `2.7.10`: `/usr/bin/python`
  - `3.7.0`: `/usr/local/bin/python3`
  - `3.7.0`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST '
                     '2018; root:xnu-4570.51.1~1/RELEASE_X86_64',
 'python_full_version': '3.7.0',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `GREP_COLOR`
  - `LDFLAGS`
  - `TERM_PROGRAM`
  - `PYPICLOUD_PASSWORD`
  - `NVM_CD_FLAGS`
  - `TERM`
  - `SHELL`
  - `CLICOLOR`
  - `TMPDIR`
  - `PIPENV_VENV_IN_PROJECT`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `LC_ALL`
  - `USER`
  - `NVM_DIR`
  - `LS_COLORS`
  - `SSH_AUTH_SOCK`
  - `XERO_CONSUMER_KEY`
  - `_`
  - `DASH_APITOKEN`
  - `PWD`
  - `EDITOR`
  - `LANG`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `HOME`
  - `SHLVL`
  - `GREP_OPTIONS`
  - `CFLAGS`
  - `PYPICLOUD_USERNAME`
  - `LOGNAME`
  - `LC_CTYPE`
  - `NVM_BIN`
  - `DISPLAY`
  - `SECURITYSESSIONID`
  - `__CF_USER_TEXT_ENCODING`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2018.7.1/libexec/tools:/Users/zupo/.nvm/versions/node/v10.3.0/bin:/Users/zupo/bin:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `subl -w`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/zupo`

---------------------------

</details>

**Comment by techalchemy** [comment]
So pipenv never actually reached the installation step on `repoze.zcml`.  That's why it tells you it encountered an error while installing `repoze.workflow` -- it tried to lock and install that first, failed, and then told you about it. During the resolution step, it happened to resolve a different version of the second package which it hasn't even attempted to deal with yet.

By the way, you are using prerelease versions, which may depend on other prerelease versions, which means you probably want to pass `--pre` with your install.  Considering that package hasn't been maintained for 4 or 5 years, it's not that surprising that we can't properly resolve it in python3.7.  I followed this up the stack a bunch and I actually have no clue why this is happening though.  /cc @uranusjr

**Comment by techalchemy** [comment]
Ah ok yeah I see what you're saying. sorry about that.  Yeah, see my above comment -- it's trying to do resolution on the first package without ever encountering the second one -- we have an open issue on merging these dependency sets somewhere... I'll leave this open until we can triage it properly

**Comment by zupo** [comment]
The order of the packages does not really matter. Consider the following scenario:

First install just `repoze.zcml==1.0b1`

```
tmp$ rm -rf repoze/
tmp$ mkdir repoze
tmp$ cd repoze/
repoze$ pipenv install --three repoze.zcml==1.0b1
Creating a virtualenv for this project...
Pipfile: /private/tmp/repoze/Pipfile
Using /usr/local/bin/python3 (3.7.0) to create virtualenv...
[ ... snip ... ]
Adding repoze.zcml==1.0b1 to Pipfile's [packages]...
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Updated Pipfile.lock (5597db)!
Installing dependencies from Pipfile.lock (5597db)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 7/7 — 00:00:02
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

SUCCESS! Now, let's install repoze.workflow==1.0b1

```
repoze$ cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"repoze.zcml" = "==1.0b1"

[dev-packages]

[requires]
python_version = "3.7"

repoze$ pipenv install repoze.workflow==1.0b1
Installing repoze.workflow==1.0b1...
Collecting repoze.workflow==1.0b1
Requirement already satisfied: zope.component in ./.venv/lib/python3.7/site-packages (from repoze.workflow==1.0b1) (4.4.1)
Requirement already satisfied: zope.configuration>=3.8.0 in ./.venv/lib/python3.7/site-packages (from repoze.workflow==1.0b1) (4.1.0)
Requirement already satisfied: setuptools in ./.venv/lib/python3.7/site-packages (from repoze.workflow==1.0b1) (40.0.0)
Requirement already satisfied: zope.interface in ./.venv/lib/python3.7/site-packages (from repoze.workflow==1.0b1) (4.5.0)
Requirement already satisfied: repoze.zcml in ./.venv/lib/python3.7/site-packages (from repoze.workflow==1.0b1) (1.0b1)
Requirement already satisfied: zope.event in ./.venv/lib/python3.7/site-packages (from zope.component->repoze.workflow==1.0b1) (4.3.0)
Requirement already satisfied: zope.i18nmessageid in ./.venv/lib/python3.7/site-packages (from zope.configuration>=3.8.0->repoze.workflow==1.0b1) (4.1.0)
Requirement already satisfied: zope.schema in ./.venv/lib/python3.7/site-packages (from zope.configuration>=3.8.0->repoze.workflow==1.0b1) (4.5.0)
Installing collected packages: repoze.workflow
Successfully installed repoze.workflow-1.0b1

Adding repoze.workflow==1.0b1 to Pipfile's [packages]...
Pipfile.lock (5597db) out of date, updating to (441907)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
3, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 335, in get_legacy_dependencies
    self.resolver.resolve(reqset)
  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 107, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 264, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 214, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 328, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 155, in prep_for_dist
    self.req.run_egg_info()
  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 486, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 752, in call_subprocess
    % (command_desc, proc.returncode, cwd)
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/ck/dlscb24n4lzdlzpt3w0pdcgh0000gn/T/tmp_vzsch1pbuild/repoze.zcml/
```

Same error. Even with `repoze.zcml==1.0b1` already installed in the environment.

Notice how the installation is successful, because `repoze.zcml==1.0b1` is available in virtualenv. It's the locking that fails as it apparently downloads `repoze.zcml==0.4` and runs `setup.py egg_info` off of the downloaded package, instead of the one already in virtualenv. At least that is how I understand it.

**Comment by karantan** [comment]
poetry doesn't have this problem because it uses pip-tools for resolving packages. Maybe we can check how they do it?

**Comment by uranusjr** [comment]
@karantan It’s the other way around, this problem riots in pip-tools, and poetry does not have it because it does not use pip-tools. We have already looked into their solution, and are already developing our own solution.

See: https://github.com/sarugaku/passa

**Comment by matteius** [comment]
Closing this issue as it is quite dated at this point.  If you think this is error please recheck with the latest version `pipenv==2021.1.8`   Noting also that there is perhaps a similar issue (but different) reported more recently against newer version:  https://github.com/pypa/pipenv/issues/4594
