### ISSUE TITLE
Error parsing commented setup.cfg file

### ISSUE THREAD

**Issue by pecigonzalo** [pypa/pipenv#2633]
##### Issue description

When installing `botocore==1.10.62` some comments on the setup.cfg make the parser fail.
https://github.com/boto/botocore/blob/2565d7912c05eadeae9f9f8ff77c18846c8cae34/setup.cfg 

This seems to have been introduced after: `2018.6.25`

##### Expected result

Installing correctly ignoring the comment

##### Actual result

```
❯ pipenv lock -v             
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
using sources: [{'url': 'https://pypi.org/simple', 'verify_ssl': True, 'name': 'pypi'}]
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  botocore==1.10.62 (from -r /tmp/pipenv-txc6yae0-requirements/pipenv-e3op5ly4-constraints.txt (line 2))

Finding the best candidates:
  found candidate botocore==1.10.62 (constraint was ==1.10.62)

Finding secondary dependencies:
  botocore==1.10.62         requires docutils>=0.10, jmespath<1.0.0,>=0.7.1, python-dateutil<3.0.0,>=2.1; python_version >= "2.7"; python_version >= "2.7"

Traceback (most recent call last):
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/notpip/_vendor/packaging/markers.py", line 276, in __init__
    self._markers = _coerce_parse_result(MARKER.parseString(marker))
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/notpip/_vendor/pyparsing.py", line 1632, in parseString
    raise exc
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/notpip/_vendor/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/notpip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/notpip/_vendor/pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/notpip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/notpip/_vendor/pyparsing.py", line 3183, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pipenv.patched.notpip._vendor.pyparsing.ParseException: Expected stringEnd (at char 23), (line:1, col:24)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/resolver.py", line 87, in <module>
    main()
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/resolver.py", line 76, in main
    system=system,
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/resolver.py", line 63, in resolve
    allow_global=system,
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/utils.py", line 402, in resolve_deps
    req_dir=req_dir
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/utils.py", line 293, in actually_resolve_deps
    results = resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS)
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 104, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 209, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 311, in _iter_dependencies
    yield InstallRequirement.from_line(dependency_string, constraint=ireq.constraint)
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 193, in from_line
    markers = Marker(markers)
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/notpip/_vendor/packaging/markers.py", line 280, in __init__
    raise InvalidMarker(err_str)
pipenv.patched.notpip._vendor.packaging.markers.InvalidMarker: Invalid marker: 'python_version >= "2.7"; python_version >= "2.7"', parse error at '; python'
```

##### Steps to replicate

```
❯ cd $(mktemp -d)
[...]
❯ pipenv install --three
[...]
❯ pipenv install botocore==1.10.62
Installing botocore==1.10.62...
Requirement already satisfied: botocore==1.10.62 in ./.venv/lib/python3.6/site-packages (1.10.62)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in ./.venv/lib/python3.6/site-packages (from botocore==1.10.62) (0.9.3)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in ./.venv/lib/python3.6/site-packages (from botocore==1.10.62) (2.7.3)
Requirement already satisfied: docutils>=0.10 in ./.venv/lib/python3.6/site-packages (from botocore==1.10.62) (0.14)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.6/site-packages (from python-dateutil<3.0.0,>=2.1; python_version >= "2.7"->botocore==1.10.62) (1.11.0)

Adding botocore==1.10.62 to Pipfile's [packages]...
Pipfile.lock (ca72e7) out of date, updating to (a22c5c)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
ule>
    main()
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/resolver.py", line 76, in main
    system=system,
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/resolver.py", line 63, in resolve
    allow_global=system,
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/utils.py", line 402, in resolve_deps
    req_dir=req_dir
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/utils.py", line 293, in actually_resolve_deps
    results = resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS)
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 104, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 209, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 311, in _iter_dependencies
    yield InstallRequirement.from_line(dependency_string, constraint=ireq.constraint)
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 193, in from_line
    markers = Marker(markers)
  File "/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv/patched/notpip/_vendor/packaging/markers.py", line 280, in __init__
    raise InvalidMarker(err_str)
pipenv.patched.notpip._vendor.packaging.markers.InvalidMarker: Invalid marker: 'python_version >= "2.7"; python_version >= "2.7"', parse error at '; python'
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/home/gonzalo.peci/.local/venvs/pipenv/lib/python3.6/site-packages/pipenv'`

Python location: `'/home/gonzalo.peci/.local/venvs/pipenv/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/home/gonzalo.peci/.pyenv/shims/python2.7`
  - `2.7`: `/home/gonzalo.peci/.pyenv/shims/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/home/gonzalo.peci/.pyenv/shims/python3.6m`
  - `3.6`: `/home/gonzalo.peci/.pyenv/shims/python3.6`
  - `3.6`: `/usr/bin/python3.6`

  - `3.6.6`: `/home/gonzalo.peci/.pyenv/shims/python`
  - `3.6.6`: `/usr/bin/python`
  - `2.7.15`: `/home/gonzalo.peci/.pyenv/shims/python2`
  - `2.7.15`: `/usr/bin/python2`
  - `3.6.6`: `/home/gonzalo.peci/.pyenv/shims/python3`
  - `3.6.6`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.17.8-1-zen',
 'platform_system': 'Linux',
 'platform_version': '#1 ZEN SMP PREEMPT Wed Jul 18 09:56:17 UTC 2018',
 'python_full_version': '3.6.6',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `AWS_VAULT_BACKEND`
  - `COLORFGBG`
  - `COLORTERM`
  - `CORRECT_IGNORE`
  - `CORRECT_IGNORE_FILE`
  - `CVSEDITOR`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DESKTOP_SESSION`
  - `DISABLE_UNTRACKED_FILES_DIRTY`
  - `DISPLAY`
  - `EDITOR`
  - `GIT_EDITOR`
  - `GS_LIB`
  - `GTK_MODULES`
  - `HG`
  - `HISTFILE`
  - `HISTSIZE`
  - `HOME`
  - `KDE_FULL_SESSION`
  - `KDE_SESSION_UID`
  - `KDE_SESSION_VERSION`
  - `KONSOLE_DBUS_SERVICE`
  - `KONSOLE_DBUS_SESSION`
  - `KONSOLE_PROFILE_NAME`
  - `KWIN_TRIPLE_BUFFER`
  - `LANG`
  - `LANGUAGE`
  - `LESS`
  - `LESSCHARSET`
  - `LESS_TERMCAP_mb`
  - `LESS_TERMCAP_md`
  - `LESS_TERMCAP_me`
  - `LESS_TERMCAP_se`
  - `LESS_TERMCAP_so`
  - `LESS_TERMCAP_ue`
  - `LESS_TERMCAP_us`
  - `LOGNAME`
  - `MAIL`
  - `MOZ_PLUGIN_PATH`
  - `OLDPWD`
  - `PAGER`
  - `PAM_KWALLET5_LOGIN`
  - `PATH`
  - `PIPENV_VENV_IN_PROJECT`
  - `PROFILEHOME`
  - `PWD`
  - `PYENV_ROOT`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `SAVEHIST`
  - `SESSION_MANAGER`
  - `SHELL`
  - `SHELL_SESSION_ID`
  - `SHLVL`
  - `SSH_AGENT_PID`
  - `SSH_ASKPASS`
  - `SSH_AUTH_SOCK`
  - `SVN_EDITOR`
  - `TERM`
  - `TLDR_COLOR_BLANK`
  - `TLDR_COLOR_COMMAND`
  - `TLDR_COLOR_DESCRIPTION`
  - `TLDR_COLOR_EXAMPLE`
  - `TLDR_COLOR_NAME`
  - `TLDR_COLOR_PARAMETER`
  - `USER`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `WINDOWID`
  - `XAUTHORITY`
  - `XCURSOR_SIZE`
  - `XCURSOR_THEME`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_DATA_DIRS`
  - `XDG_RUNTIME_DIR`
  - `XDG_SEAT`
  - `XDG_SEAT_PATH`
  - `XDG_SESSION_CLASS`
  - `XDG_SESSION_DESKTOP`
  - `XDG_SESSION_ID`
  - `XDG_SESSION_PATH`
  - `XDG_SESSION_TYPE`
  - `XDG_VTNR`
  - `_`
  - `_Z_NO_COMPLETE_CD`
  - `_Z_NO_RESOLVE_SYMLINKS`
  - `PYENV_SHELL`
  - `RUBY_ROOT`
  - `RUBYOPT`
  - `RUBY_ENGINE`
  - `RUBY_VERSION`
  - `GEM_ROOT`
  - `GEM_HOME`
  - `GEM_PATH`
  - `NVM_DIR`
  - `NVM_CD_FLAGS`
  - `NVM_BIN`
  - `GVM_ROOT`
  - `GVM_VERSION`
  - `GVM_PATH_BACKUP`
  - `gvm_go_name`
  - `gvm_pkgset_name`
  - `GOROOT`
  - `GOPATH`
  - `GVM_OVERLAY_PREFIX`
  - `LD_LIBRARY_PATH`
  - `DYLD_LIBRARY_PATH`
  - `PKG_CONFIG_PATH`
  - `ZPLUG_HOME`
  - `ZPLUG_ROOT`
  - `PERIOD`
  - `FPATH`
  - `ZPLUG_THREADS`
  - `ZPLUG_PROTOCOL`
  - `ZPLUG_FILTER`
  - `ZPLUG_LOADFILE`
  - `ZPLUG_USE_CACHE`
  - `ZPLUG_ERROR_LOG`
  - `ZPLUG_BIN`
  - `ZPLUG_CACHE_DIR`
  - `ZPLUG_REPOS`
  - `_ZPLUG_VERSION`
  - `_ZPLUG_URL`
  - `_ZPLUG_OHMYZSH`
  - `_ZPLUG_PREZTO`
  - `_ZPLUG_AWKPATH`
  - `_ZPLUG_CONFIG_SUBSHELL`
  - `ZSH`
  - `ZSH_CACHE_DIR`
  - `LSCOLORS`
  - `LS_COLORS`
  - `LC_CTYPE`
  - `ZSH_TMUX_TERM`
  - `_ZSH_TMUX_FIXED_CONFIG`
  - `SPACESHIP_VERSION`
  - `SPACESHIP_ROOT`
  - `AWS_HOME`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `true`

Debug–specific environment variables:

  - `PATH`: `/home/gonzalo.peci/.zplug/bin:/home/gonzalo.peci/.gvm/pkgsets/go1.10.1/global/bin:/home/gonzalo.peci/.gvm/gos/go1.10.1/bin:/home/gonzalo.peci/.gvm/pkgsets/go1.10.1/global/overlay/bin:/home/gonzalo.peci/.gvm/bin:/home/gonzalo.peci/.nvm/versions/node/v8.11.0/bin:/home/gonzalo.peci/.gem/ruby/2.5.0/bin:/home/gonzalo.peci/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/bin:/home/gonzalo.peci/.rubies/ruby-2.5.0/bin:/home/gonzalo.peci/.pyenv/shims:/home/gonzalo.peci/Workspace/Go/bin:/home/gonzalo.peci/.local/bin:/home/gonzalo.peci/.pyenv/bin:/home/gonzalo.peci/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
  - `SHELL`: `/usr/bin/zsh`
  - `EDITOR`: `vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/tmp/tmp.MQSArY2bXl`

---------------------------

Contents of `Pipfile` ('/tmp/tmp.MQSArY2bXl/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
botocore = "==1.10.62"

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/tmp/tmp.MQSArY2bXl/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "415dfdcb118dd9bdfef17671cb7dcd78dbd69b6ae7d4f39e8b44e71d60ca72e7"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>

**Comment by uranusjr** [comment]
That’s not a comment, and the parser should not ignore it. But this is a bug nonetheless.

**Comment by pecigonzalo** [comment]
My bad, it was showing as a comment on VSCode, so I just assumed it was. I'm not that familiar with setup.cfg syntax
