### ISSUE TITLE
Pipenv install fails with  '_NamespacePath' object has no attribute 'sort'

### ISSUE THREAD

**Issue by Vanik888** [pypa/pipenv#2652]
Ubuntu: 16:04
python: 3.5
pip: 18.0
pipenv: 2018.7.1

I have my Pipfile
```
[[source]]
verify_ssl = true
name = "pypi"
url = "https://pypi.org/simple"

[packages]
google-cloud-datastore = "*"
celery = "==4.2.0"
python-dotenv = "==0.8.2"
grpcio = "==1.8.2"
certifi = "==2018.4.16"
ujson = "==1.35"
python-memcached = "==1.59"
fastcsv = "==0.1.3"
pymysql = "==0.9.1"
sqlalchemy = "==1.2.9"
sphinx = "==1.7.5"
pipdeptree = "*"
googleapis-common-protos = "*"
```
When I run pipenv install I get the error
```
Collecting googleapis-common-protos==1.5.3  00:00:00
  Using cached https://files.pythonhosted.org/packages/00/03/d25bed04ec8d930bcfa488ba81a2ecbf7eb36ae3ffd7e8f5be0d036a89c9/googleapis-common-protos-1.5.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qyum63sj/googleapis-common-protos/
```
then when I run 
```
pip install googleapis-common-protos
```
it finishes successfully, and if I run ```pipenv install``` it also works without errors. 
It looks very strange that some packages can not be installed simultaneously through pipenv install command but the single package installation fixes the problem. 
Might be I am doing something wrong but I still can not use pipenv because I have to install every package one by one.

**Comment by uranusjr** [comment]
This is a pip issue, the version bundled in 3.5 is a little faulty. The following solutions should be able to fix the issue:

1. `pipenv run python -m pip install -U pip setuptools`
2. (If the above does not work) `pipenv --rm`, re-create the virtual environment, and run 1.

The issue is out of hands of Pipenv.

**Comment by Vanik888** [comment]
Thank you for such fast feedback. I have tried the solution you sent. Unfortunately, I still have the same error.
I even tried to use --sequential flag, but it did not help.
```
Installing initially–failed dependencies…
Collecting googleapis-common-protos==1.5.3  00:00:00
  Using cached https://files.pythonhosted.org/packages/00/03/d25bed04ec8d930bcfa488ba81a2ecbf7eb36ae3ffd7e8f5be0d036a89c9/googleapis-common-protos-1.5.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/home/vagrant/pipenv_amabid/.venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2f2kxh3n/googleapis-common-protos/
```
