### ISSUE TITLE
Unable to install local package repositories on ubuntu 18.04

### ISSUE THREAD

**Issue by connectedblue** [pypa/pipenv#2746]
##### Issue description

After upgrading to ubuntu 18.04 which bumped the system python from 3.5 to 3.6, `pipenv install` would not load a local package from the file system, specified using the {file=} syntax.

##### Expected result

I changed only the python version number in the `Pipfile`, issued a `pipenv --rm` followed by a `pipenv install`.  I would have expected the private pp package to have re-installed.

##### Actual result
It looks like an additional `.` was placed in front of the `file:///` specification which caused the pipenv to not be able to find the package location on the file system.

This is the output of the command:
```
production@ip-10-246-198-197:~/apps/joinconversion$ pipenv install
Creating a virtualenv for this project...
Pipfile: /opt/data/production/production-user/apps/joinconversion/Pipfile
Using /usr/bin/python3.6m (3.6.5) to create virtualenv...
⠋Running virtualenv with interpreter /usr/bin/python3.6m
Using base prefix '/usr'
New python executable in /home/production/.local/share/virtualenvs/joinconversion-1uvQApZz/bin/python3.6m
Also creating executable in /home/production/.local/share/virtualenvs/joinconversion-1uvQApZz/bin/python
Installing setuptools, pip, wheel...done.
Setting project for joinconversion-1uvQApZz to /opt/data/production/production-user/apps/joinconversion

Virtualenv location: /home/production/.local/share/virtualenvs/joinconversion-1uvQApZz
Pipfile.lock (74bb87) out of date, updating to (8774f8)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Traceback (most recent call last):
 File "/usr/local/bin/pipenv", line 11, in <module>
   sys.exit(cli())
 File "/opt/data/production/production-user/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
   return self.main(*args, **kwargs)
 File "/opt/data/production/production-user/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
   rv = self.invoke(ctx)
 File "/opt/data/production/production-user/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
   return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/opt/data/production/production-user/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File "/opt/data/production/production-user/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
   return callback(*args, **kwargs)
 File "/home/production/.local/lib/python3.6/site-packages/pipenv/cli.py", line 435, in install
   selective_upgrade=selective_upgrade,
 File "/home/production/.local/lib/python3.6/site-packages/pipenv/core.py", line 1943, in do_install
   pypi_mirror=pypi_mirror,
 File "/home/production/.local/lib/python3.6/site-packages/pipenv/core.py", line 1285, in do_init
   do_lock(system=system, pre=pre, keep_outdated=keep_outdated, write=True, pypi_mirror=pypi_mirror)
 File "/home/production/.local/lib/python3.6/site-packages/pipenv/core.py", line 1057, in do_lock
   settings['packages'], project, r=False, include_index=True
 File "/home/production/.local/lib/python3.6/site-packages/pipenv/utils.py", line 513, in convert_deps_to_pip
   new_dep = Requirement.from_pipfile(dep_name, dep)
 File "/home/production/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 764, in from_pipfile
   r = FileRequirement.from_pipfile(name, pipfile)
 File "/home/production/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 394, in from_pipfile
   return cls(**arg_dict)
 File "<attrs generated init 0936e6bebbaa40af1d505786c59b44fbe27de130>", line 23, in __init__
 File "/opt/data/production/production-user/.local/lib/python3.6/site-packages/pipenv/vendor/attr/validators.py", line 106, in __call__
   self.validator(inst, attr, value)
 File "/home/production/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/utils.py", line 123, in validate_path
   raise ValueError("Invalid path {0!r}", format(value))
ValueError: ('Invalid path {0!r}', './file:/opt/share/python/packages/pp/pp-0.4.1.tar.gz')
```

##### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).
1.  Upgraded from Ubuntu 16.04 to 18.04
2.  Installed pipenv manually using `pip install pipenv`
3.  editted the `Pipfile` to adjust environment to 3.6
```
[[source]]
name = "pypi"
verify_ssl = true
url = "https://pypi.python.org/simple"
[packages]
pp = {version="*", path="file:///opt/share/python/packages/pp/pp-0.4.1.tar.gz" }
joinconversion = {version="*", path="file:///opt/share/python/packages/joinconversion/joinconversion-0.2.tar.gz" }
simple-salesforce = "*"
numpy = "*"
ipython = "*"
pandas = "*"
sqlalchemy-redshift = "*"
sqlalchemy = "*"
"psycopg2-binary" = "*"

[dev-packages]

[requires]
python_version = "3.6"
```
4.  Run `pipenv install`
-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by uranusjr** [comment]
`path` is for specifying a local file path. If you want to specify a URL, use `file` instead. Read the Pipfile spec for examples. https://github.com/pypa/pipfile#examples-spec-v6
