### ISSUE TITLE
Project directories that begin with a "-" confuse pipenv

### ISSUE THREAD

**Issue by sfoster1** [pypa/pipenv#2837]
##### Issue description

If you try to start a new project using pipenv in a directory whose name begins with the "-" character, at least on OSX (no other handy OSes to test with) then most if not all `pipenv` commands will fail
##### Expected result

`pipenv --three` successfully creates a virtualenv and Pipfile, as documented here in a dir called "test":

```
~/dev/test ᐅ pipenv --three
Virtualenv already exists!
Removing existing virtualenv…
Creating a virtualenv for this project…
Using /Users/sethfoster/.pyenv/versions/3.6.4/bin/python3 (3.6.4) to create virtualenv…
⠋Running virtualenv with interpreter /Users/sethfoster/.pyenv/versions/3.6.4/bin/python3
Using base prefix '/Users/sethfoster/.pyenv/versions/3.6.4'
New python executable in /Users/sethfoster/.local/share/virtualenvs/test-AFOaEKCv/bin/python3
Also creating executable in /Users/sethfoster/.local/share/virtualenvs/test-AFOaEKCv/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /Users/sethfoster/.local/share/virtualenvs/test-AFOaEKCv
Creating a Pipfile for this project…
```

##### Actual result

```
~/dev/-test ᐅ pipenv --three
Creating a virtualenv for this project…
Using /Users/sethfoster/.pyenv/versions/3.6.4/bin/python3 (3.6.4) to create virtualenv…
⠋usage: __main__.py [-h] [-p PYTHON] [-i PACKAGES] [-r REQUIREMENTS] [-d]
                   [-a PROJECT]
                   envname
__main__.py: error: the following arguments are required: envname

Virtualenv location:
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "/Users/sethfoster/.pyenv/versions/3.6.4/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.6.8', 'console_scripts', 'pipenv')()
  File "/Users/sethfoster/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sethfoster/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/sethfoster/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/Users/sethfoster/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sethfoster/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/sethfoster/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sethfoster/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/cli.py", line 152, in cli
    core.ensure_project(three=three, python=python, warn=True, site_packages=site_packages)
  File "/Users/sethfoster/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/core.py", line 672, in ensure_project
    ensure_pipfile(validate=validate, skip_requirements=skip_requirements)
  File "/Users/sethfoster/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/core.py", line 321, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/Users/sethfoster/.pyenv/versions/3.6.4/lib/python3.6/site-packages/pipenv/project.py", line 446, in create_pipfile
    data[u'requires'] = {'python_version': python_version(required_python)[:len('2.7')]}
TypeError: 'NoneType' object is not subscriptable
~/dev/-test ᐅ
```

##### Steps to replicate

On OSX, create a new empty directory whose name begins with a `-` and run `pipenv --three` (with python3 installed)

**Comment by uranusjr** [comment]
This has been fixed for a long time. You need to upgrade.
