### ISSUE TITLE
TypeError when i run pipenv install on Ubuntu Machine

### ISSUE THREAD

**Issue by tayalkshitij** [pypa/pipenv#2874]
1.Environment: Ubuntu 16
2.Python-version: 3.6.5

**pipenv install** is giving me following error: 
```
'''
Creating a virtualenv for this project...
Pipfile: /panfs/roc/groups/6/kumarv/tayal007/Downloads/Projects/Building_Detection/Pipfile
Using /home/kumarv/tayal007/anaconda3/bin/python (3.6.5) to create virtualenv...
â Already using interpreter /home/kumarv/tayal007/anaconda3/bin/python
Using base prefix '/home/kumarv/tayal007/anaconda3'
New python executable in /home/kumarv/tayal007/.local/share/virtualenvs/Building_Detection-_Eh9rBNl/bin/python
/home/kumarv/tayal007/.local/share/virtualenvs/Building_Detection-_Eh9rBNl/bin/python: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory
ERROR: The executable /home/kumarv/tayal007/.local/share/virtualenvs/Building_Detection-_Eh9rBNl/bin/python is not functioning
ERROR: It thinks sys.prefix is '/panfs/roc/groups/6/kumarv/tayal007/Downloads/Projects/Building_Detection' (should be '/home/kumarv/tayal007/.local/share/virtualenvs/Building_Detection-_Eh9rBNl')
ERROR: virtualenv is not compatible with this system or executable

Virtualenv location: 
Creating a Pipfile for this project...
Traceback (most recent call last):
  File "/home/kumarv/tayal007/anaconda3/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/panfs/roc/groups/6/kumarv/tayal007/anaconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/panfs/roc/groups/6/kumarv/tayal007/anaconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/panfs/roc/groups/6/kumarv/tayal007/anaconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/panfs/roc/groups/6/kumarv/tayal007/anaconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/panfs/roc/groups/6/kumarv/tayal007/anaconda3/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/kumarv/tayal007/anaconda3/lib/python3.6/site-packages/pipenv/cli.py", line 435, in install
    selective_upgrade=selective_upgrade,
  File "/home/kumarv/tayal007/anaconda3/lib/python3.6/site-packages/pipenv/core.py", line 1759, in do_install
    pypi_mirror=pypi_mirror,
  File "/home/kumarv/tayal007/anaconda3/lib/python3.6/site-packages/pipenv/core.py", line 639, in ensure_project
    ensure_pipfile(validate=validate, skip_requirements=skip_requirements, system=system)
  File "/home/kumarv/tayal007/anaconda3/lib/python3.6/site-packages/pipenv/core.py", line 288, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/home/kumarv/tayal007/anaconda3/lib/python3.6/site-packages/pipenv/project.py", line 607, in create_pipfile
    required_python = self.which('python')
  File "/home/kumarv/tayal007/anaconda3/lib/python3.6/site-packages/pipenv/core.py", line 115, in which
    p = os.path.join(location, 'bin', command)
  File "/home/kumarv/tayal007/anaconda3/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType '''

```
Output for  '''**python -m pipenv.help'**'' is 

```
'''<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/home/kumarv/tayal007/anaconda3/lib/python3.6/site-packages/pipenv'`

Python location: `'/home/kumarv/tayal007/anaconda3/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.4`: `/usr/bin/python3.4m`
  - `3.4`: `/usr/bin/python3.4`
  - `3.6`: `/home/kumarv/tayal007/anaconda3/bin/python3.6m`
  - `3.6`: `/home/kumarv/tayal007/anaconda3/bin/python3.6`

  - `3.6.5`: `/home/kumarv/tayal007/anaconda3/bin/python`
  - `2.7.5`: `/usr/bin/python`
  - `2.7.5`: `/usr/bin/python2`
  - `3.6.5`: `/home/kumarv/tayal007/anaconda3/bin/python3`
  - `3.4.9`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '3.10.0-862.11.6.el7.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Tue Aug 14 21:49:04 UTC 2018',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `MANPATH`
  - `XDG_SESSION_ID`
  - `HOSTNAME`
  - `MODULEPATH_modshare`
  - `MODULES_CMD`
  - `TERM`
  - `SHELL`
  - `HISTSIZE`
  - `SSH_CLIENT`
  - `PERL5LIB`
  - `OLDPWD`
  - `SSH_TTY`
  - `LC_ALL`
  - `USER`
  - `LS_COLORS`
  - `MSICLUSTER`
  - `ENV`
  - `MODULES_RUN_QUARANTINE`
  - `MAIL`
  - `PATH`
  - `PWD`
  - `LANG`
  - `MODULEPATH`
  - `MOABHOMEDIR`
  - `LOADEDMODULES`
  - `HISTCONTROL`
  - `SHLVL`
  - `HOME`
  - `BASH_ENV`
  - `LOGNAME`
  - `SSH_CONNECTION`
  - `MODULESHOME`
  - `LESSOPEN`
  - `XDG_RUNTIME_DIR`
  - `DISPLAY`
  - `BASH_FUNC_module()`
  - `BASH_FUNC_switchml()`
  - `BASH_FUNC_s3cmd()`
  - `BASH_FUNC__moduleraw()`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenvâspecific environment variables:


Debugâspecific environment variables:

  - `PATH`: `/home/kumarv/tayal007/anaconda3/bin:/usr/local/bin:/usr/local/sbin:/usr/share/Modules/bin:/opt/moab/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/msi/bin:/opt/puppetlabs/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/kumarv/tayal007/Downloads/Projects/Building_Detection`


---------------------------

Contents of `Pipfile` ('/panfs/roc/groups/6/kumarv/tayal007/Downloads/Projects/Building_Detection/Pipfile'):

```toml

```

</details> '''
```
Output for '''**pipenv --support | xclip**''' is : 

```
-bash: xclip: command not found
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

Can somebody help me with the error. Thanks.

**Comment by stardust85** [comment]
just out of curiosity, what is the benefit of using both anaconda and pipenv? I thought they both solve similar problems.

**Comment by uranusjr** [comment]
pypa/virtualenv#1015.

**Comment by ConorSheehan1** [comment]
> just out of curiosity, what is the benefit of using both anaconda and pipenv? I thought they both solve similar problems.

@stardust85 Anaconda lets you install new versions of python and provides precompiled binaries for certain packages, while pipenv does not. Pipenv makes reproducing the environment much easier by providing a lockfile containing a dependency graph, while anaconda does not.

Ideally if was starting a new project in python 3.7, I'd use anaconda to install 3.7 and some packages that require compilation like [pandas](https://pandas.pydata.org/pandas-docs/stable/install.html#installing-with-anaconda), then use pipenv to generate a lockfile so other people could reproduce the build. 

I wish all that functionality was rolled into one tool.
