### ISSUE TITLE
incompatibility of pipenv with pip 18.1

### ISSUE THREAD

**Issue by happlek** [pypa/pipenv#2937]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

If you're requesting a new feature, please use the PEEP process:

    https://github.com/pypa/pipenv/blob/master/peeps/PEEP-000.md

Check the [diagnose documentation](https://docs.pipenv.org/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

in pip 18.1 
_strip_extras is removed from pip.req.req_install so we get the error:

python -m pipenv sync --dev
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead.
Installing dependencies from Pipfile.lock (ff1ba0)...
Traceback (most recent call last):
  File "c:\python3.6\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python3.6\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\virtualenvs\edb\python3.6\lib\site-packages\pipenv\__main__.py", line 4, in <module>
    cli()
  File "D:\virtualenvs\edb\python3.6\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "D:\virtualenvs\edb\python3.6\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "D:\virtualenvs\edb\python3.6\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\virtualenvs\edb\python3.6\lib\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\virtualenvs\edb\python3.6\lib\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "D:\virtualenvs\edb\python3.6\lib\site-packages\pipenv\vendor\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\virtualenvs\edb\python3.6\lib\site-packages\pipenv\cli.py", line 1049, in sync
    pypi_mirror=pypi_mirror,
  File "D:\virtualenvs\edb\python3.6\lib\site-packages\pipenv\core.py", line 2518, in do_sync
    system=system,
  File "D:\virtualenvs\edb\python3.6\lib\site-packages\pipenv\core.py", line 1322, in do_init
    pypi_mirror=pypi_mirror,
  File "D:\virtualenvs\edb\python3.6\lib\site-packages\pipenv\core.py", line 807, in do_install_dependencies
    pypi_mirror=pypi_mirror,
  File "D:\virtualenvs\edb\python3.6\lib\site-packages\pipenv\core.py", line 1375, in pip_install
    package_name.split('--hash')[0].split('--trusted-host')[0]
  File "D:\virtualenvs\edb\python3.6\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable

and must rollback to usage of pip 18.0

### Expected result

no error

### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by happlek** [comment]
close issue it is described by https://github.com/pypa/pipenv/issues/2924
