### ISSUE TITLE
pipenv -e install does not recognise requirements.txt when installing spaCy from git+ssh

### ISSUE THREAD

**Issue by rbricheno** [pypa/pipenv#3015]
### Issue description

```
pipenv install -e git+https://github.com/explosion/spaCy#egg=spacy
```

fails because of a missing cython requirement, leaving a mostly-empty Pipfile which does not specify any packages.

This issue was identified by the user spbks on stackoverflow:

https://stackoverflow.com/questions/50316275/how-to-use-pipenv-to-install-package-from-github

### Expected result

pipenv uses the requirements.txt in the spaCy github repository to install the requirements

### Actual result

```
rob@server:~/spacy-pipenv$ pipenv install -e git+https://github.com/explosion/spaCy#egg=spacy
Installing -e git+https://github.com/explosion/spaCy#egg=spacy…
Obtaining spacy from git+https://github.com/explosion/spaCy#egg=spacy
  Updating /home/rob/.local/share/virtualenvs/spacy-pipenv-0MSJ3ob8/src/spacy clone
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'Cython'
    Processing typedefs.pyx
    Traceback (most recent call last):
      File "/home/rob/.local/share/virtualenvs/spacy-pipenv-0MSJ3ob8/src/spacy/bin/cythonize.py", line 59, in process_pyx
        env=os.environ) # See Issue #791
      File "/usr/lib/python3.6/subprocess.py", line 267, in call
        with Popen(*popenargs, **kwargs) as p:
      File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cython': 'cython'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/rob/.local/share/virtualenvs/spacy-pipenv-0MSJ3ob8/src/spacy/bin/cythonize.py", line 157, in <module>
        run(args.root)
      File "/home/rob/.local/share/virtualenvs/spacy-pipenv-0MSJ3ob8/src/spacy/bin/cythonize.py", line 148, in run
        process(base, filename, db)
      File "/home/rob/.local/share/virtualenvs/spacy-pipenv-0MSJ3ob8/src/spacy/bin/cythonize.py", line 114, in process
        preserve_cwd(base, process_pyx, root + '.pyx', root + '.cpp')
      File "/home/rob/.local/share/virtualenvs/spacy-pipenv-0MSJ3ob8/src/spacy/bin/cythonize.py", line 79, in preserve_cwd
        func(*args)
      File "/home/rob/.local/share/virtualenvs/spacy-pipenv-0MSJ3ob8/src/spacy/bin/cythonize.py", line 70, in process_pyx
        raise Exception('Cython failed')
    Exception: Cython failed
    Cythonizing sources
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/rob/.local/share/virtualenvs/spacy-pipenv-0MSJ3ob8/src/spacy/setup.py", line 224, in <module>
        setup_package()
      File "/home/rob/.local/share/virtualenvs/spacy-pipenv-0MSJ3ob8/src/spacy/setup.py", line 172, in setup_package
        generate_cython(root, 'spacy')
      File "/home/rob/.local/share/virtualenvs/spacy-pipenv-0MSJ3ob8/src/spacy/setup.py", line 104, in generate_cython
        raise RuntimeError('Running cythonize failed')
    RuntimeError: Running cythonize failed

    ----------------------------------------

Error:  An error occurred while installing -e git+https://github.com/explosion/spaCy#egg=spacy!
Command "python setup.py egg_info" failed with error code 1 in /home/rob/.local/share/virtualenvs/spacy-pipenv-0MSJ3ob8/src/spacy/

This is likely caused by a bug in spacy. Report this to its maintainers.
rob@server:~/spacy-pipenv$ cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.6"
rob@server:~/spacy-pipenv$ 
```

### Steps to replicate

Run the command on a server without first installing the requirements.

The problem can be worked around by first installing the reuqirements using

```
pipenv install -r https://raw.githubusercontent.com/explosion/spaCy/master/requirements.txt
pipenv install -e git+https://github.com/explosion/spaCy#egg=spacy
```

which results in the following Pipfile:

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
numpy = ">=1.15.0"
msgpack-numpy = "<0.4.4.0"
cymem = ">=1.30,<1.32"
preshed = ">=1.0.0,<2.0.0"
thinc = ">=6.10.3,<6.11.0"
murmurhash = ">=0.28,<0.29"
plac = "<1.0.0,>=0.9.6"
ujson = ">=1.35"
dill = "<0.3,>=0.2"
regex = "==2018.01.10"
requests = "<3.0.0,>=2.13.0"
pytest = "<4.0.0,>=3.6.0"
mock = "<3.0.0,>=2.0.0"
pathlib = "==1.0.1"
Cython = ">=0.24,<0.28.0"
spacy = {editable = true, git = "https://github.com/explosion/spaCy"}

[dev-packages]

[requires]
python_version = "3.6"

```
-------------------------------------------------------------------------------

Unfortunately I didn't run pipenv --support before installing the requirements, so this is the output *after* I have successfully installed spaCy using the workaround above:

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.9'`

Pipenv location: `'/usr/local/lib/python3.6/dist-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.6.5`: `/usr/bin/python3.6`
  - `3.6.5`: `/usr/bin/python3.6m`
  - `2.7.15rc1`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'i686',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-36-generic',
 'platform_system': 'Linux',
 'platform_version': '#39-Ubuntu SMP Mon Sep 24 16:16:44 UTC 2018',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LS_COLORS`
  - `SSH_CONNECTION`
  - `LESSCLOSE`
  - `LANG`
  - `S_COLORS`
  - `XDG_SESSION_ID`
  - `USER`
  - `PWD`
  - `HOME`
  - `SSH_CLIENT`
  - `XDG_DATA_DIRS`
  - `SSH_TTY`
  - `MAIL`
  - `TERM`
  - `SHELL`
  - `SHLVL`
  - `LOGNAME`
  - `XDG_RUNTIME_DIR`
  - `PATH`
  - `LESSOPEN`
  - `_`
  - `OLDPWD`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/home/rob/spacy-pipenv`

---------------------------

Contents of `Pipfile` ('/home/rob/spacy-pipenv/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
numpy = ">=1.15.0"
msgpack-numpy = "<0.4.4.0"
cymem = ">=1.30,<1.32"
preshed = ">=1.0.0,<2.0.0"
thinc = ">=6.10.3,<6.11.0"
murmurhash = ">=0.28,<0.29"
plac = "<1.0.0,>=0.9.6"
ujson = ">=1.35"
dill = "<0.3,>=0.2"
regex = "==2018.01.10"
requests = "<3.0.0,>=2.13.0"
pytest = "<4.0.0,>=3.6.0"
mock = "<3.0.0,>=2.0.0"
pathlib = "==1.0.1"
Cython = ">=0.24,<0.28.0"
spacy = {editable = true, git = "https://github.com/explosion/spaCy"}

[dev-packages]

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/home/rob/spacy-pipenv/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "e9ac3dcb4b3fa2f0695426379eead1459a7ab3359dd2e95df2e578084a0e6ec3"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "atomicwrites": {
            "hashes": [
                "sha256:0312ad34fcad8fac3704d441f7b317e50af620823353ec657a53e981f92920c0",
                "sha256:ec9ae8adaae229e4f8446952d204a3e4b5fdd2d099f9be3aaf556120135fb3ee"
            ],
            "version": "==1.2.1"
        },
        "attrs": {
            "hashes": [
                "sha256:10cbf6e27dbce8c30807caf056c8eb50917e0eaafe86347671b57254006c3e69",
                "sha256:ca4be454458f9dec299268d472aaa5a11f67a4ff70093396e1ceae9c76cf4bbb"
            ],
            "version": "==18.2.0"
        },
        "certifi": {
            "hashes": [
                "sha256:376690d6f16d32f9d1fe8932551d80b23e9d393a8578c5633a2ed39a64861638",
                "sha256:456048c7e371c089d0a77a5212fb37a2c2dce1e24146e3b7e0261736aaeaa22a"
            ],
            "version": "==2018.8.24"
        },
        "chardet": {
            "hashes": [
                "sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae",
                "sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691"
            ],
            "version": "==3.0.4"
        },
        "cymem": {
            "hashes": [
                "sha256:00bb3645dfb9a020d735ba3d6f822b04656388180588d8b2cebde967ee678bcc",
                "sha256:0dd61d05977839a922c0d797c355b98949210575918b1743b41e38ae9fb2c3a7",
                "sha256:4bc1056b52d959fcbb1e0f32ec84fa131754d6be1e36b65782c6ac86419f4bf3",
                "sha256:4c5d9ca6ec706792b8d9b1faf6db77b95545c388c768b21d940f197aa7efbb7e",
                "sha256:50292f4dd0d950a8698bae27d71efe59da7ff08e591b735e08b658aae42c4745",
                "sha256:616d06333f46dd03c128d97912d361183fc02249e6420a7b7907b41214c51562",
                "sha256:944af97d4d34a2470b5199f1c31d2dfc79cdec7bd7a41354d839a8ab87fdfaa6",
                "sha256:b38056efb99078b06c504adb5f03a8d9e822a5543451737b746028a71c4b1ac3",
                "sha256:b6513b2926c60d641f159e79e6fb16460dfb50ebcce31a5af0370c51837c7efc",
                "sha256:daa6003fcc199752ab703142021cff74774872a932303b240dc0ea177adf295d",
                "sha256:f06d9b50da0474d7405674d8101c319d89a17d33792d6d429fe3d5c64f0d9df1"
            ],
            "index": "pypi",
            "version": "==1.31.2"
        },
        "cython": {
            "hashes": [
                "sha256:251bb50e36044ad26ff45960a60cb75868757fd46900eaf00129a4af3a0d5fcc",
                "sha256:264a68823751fe2a18d0b14dd44b614aecd508bd01453902921c23fd5be13d4c",
                "sha256:26e24164d59e92280fa759a8a361c68490763ec230307e21990020bdeb87de50",
                "sha256:28c938bc970d2b5fe296460cf6ed19d0328776a6295f68a79057060e60bfc82f",
                "sha256:38a9e5afc5e096f26bfe5c4b458541e455032028cb5356a734ba235868b19823",
                "sha256:3914ae1268334208e33b952e9f447e0d9f43decd562f939d7d07e8589d0473ba",
                "sha256:4c958bd9e50fcd316830561f0725b3ccf893de328566c960b7bb38424d3b983d",
                "sha256:56a9f99b42ad6ad1fdb7705c16aa69b2e1a4ac34f760286a6de64c5719499da7",
                "sha256:5e0006c3a2849b7a36d2cb23bcf14753b6ffc3eafac48fa29fafad942cfa4627",
                "sha256:6a00512de1f2e3ce66ba35c5420babaef1fe2d9c43a8faab4080b0dbcc26bc64",
                "sha256:7bc07c32703e4e63f2f60c729b0ae99acbccbfd3ae4c64a322a75482d915d4af",
                "sha256:7fbd49b1bd5240feb69ec4c67f4c76fc9dfdfc472d642833668ecaad0e14673d",
                "sha256:82bbbeadbc579b6f2a7365db2d3ea21043699e424cfcca434b3baa11309260ae",
                "sha256:83237d27b6dec0f6b76406de5be1cf249cffb4377079acc3f3dfa72de1e307cf",
                "sha256:8a4733edf3ca1c7dd9c7e1289dd5974657f1147642ef8ded1e57a1266922e32a",
                "sha256:8afdc3751c6269ef46879ca6ff32a1362f298c77f2cf0723c66ae65c35be5db0",
                "sha256:9f8bbd876c4d68cb12b9de9dc6734c17ca295e4759e684417fd7f3dd96d3ed2c",
                "sha256:a51c3a1c948664874f91636ba6169bca4dc68f5fac7b980fcb9c769a8d1f9ebc",
                "sha256:aba08b4db9163c52a1106efa8b19c5a4e519e5f45644551bb1358ec189a14505",
                "sha256:abfb2426266d806a7d794a8ecbd0fbb385b48bddf2db6ac9a2e95d48e2c603bd",
                "sha256:b9bc1d7e681c5a7560280a5aa8000f736eb0e47efacb7b6206275ed004595a92",
                "sha256:ca81d4b6f511f1e0d2a1c76ad5b3a4a3a0edf683f27600d4a86da55cb134372a",
                "sha256:cefa9356770d71176c87ab60f6fdb186ec9cbc6399a6c2de1017852505d44963",
                "sha256:d17a6a689bb3e6c0f280620dfddb1b91ffb8fcdae3b8707bdf6285df4100d011",
                "sha256:d8e40814fefc300bc64251f5d6bd8988e49442d7ded0e5702b5366323a035afc",
                "sha256:e30fd7a32cbe7fe6c186deefef03670bf75d76ead23418f8c91519899be5518e",
                "sha256:e86984b90a0176bafb5890f1f14a2962317eee9e95e0a917e6b06a5b0c764e25",
                "sha256:f01e79f4123205d0f99b97199b53345cb6378974e738792c620957c6223fded9",
                "sha256:f441347d0d07b4cb9ca36bda70c3aa98a7484a262b8f44d0f82b70dbb5e11b47",
                "sha256:fb5b8978b937677a32b5aecc72231560d29243622a298a5c31183b156f9f42e3"
            ],
            "index": "pypi",
            "version": "==0.27.3"
        },
        "cytoolz": {
            "hashes": [
                "sha256:84cc06fa40aa310f2df79dd440fc5f84c3e20f01f9f7783fc9c38d0a11ba00e5"
            ],
            "version": "==0.9.0.1"
        },
        "dill": {
            "hashes": [
                "sha256:624dc244b94371bb2d6e7f40084228a2edfff02373fe20e018bef1ee92fdd5b3"
            ],
            "index": "pypi",
            "version": "==0.2.8.2"
        },
        "idna": {
            "hashes": [
                "sha256:156a6814fb5ac1fc6850fb002e0852d56c0c8d2531923a51032d1b70760e186e",
                "sha256:684a38a6f903c1d71d6d5fac066b58d7768af4de2b832e426ec79c30daa94a16"
            ],
            "version": "==2.7"
        },
        "mock": {
            "hashes": [
                "sha256:5ce3c71c5545b472da17b72268978914d0252980348636840bd34a00b5cc96c1",
                "sha256:b158b6df76edd239b8208d481dc46b6afd45a846b7812ff0ce58971cf5bc8bba"
            ],
            "index": "pypi",
            "version": "==2.0.0"
        },
        "more-itertools": {
            "hashes": [
                "sha256:c187a73da93e7a8acc0001572aebc7e3c69daf7bf6881a2cea10650bd4420092",
                "sha256:c476b5d3a34e12d40130bc2f935028b5f636df8f372dc2c1c01dc19681b2039e",
                "sha256:fcbfeaea0be121980e15bc97b3817b5202ca73d0eae185b4550cbfce2a3ebb3d"
            ],
            "version": "==4.3.0"
        },
        "msgpack": {
            "hashes": [
                "sha256:0b3b1773d2693c70598585a34ca2715873ba899565f0a7c9a1545baef7e7fbdc",
                "sha256:0bae5d1538c5c6a75642f75a1781f3ac2275d744a92af1a453c150da3446138b",
                "sha256:0ee8c8c85aa651be3aa0cd005b5931769eaa658c948ce79428766f1bd46ae2c3",
                "sha256:1369f9edba9500c7a6489b70fdfac773e925342f4531f1e3d4c20ac3173b1ae0",
                "sha256:22d9c929d1d539f37da3d1b0e16270fa9d46107beab8c0d4d2bddffffe895cee",
                "sha256:2ff43e3247a1e11d544017bb26f580a68306cec7a6257d8818893c1fda665f42",
                "sha256:31a98047355d34d047fcdb55b09cb19f633cf214c705a765bd745456c142130c",
                "sha256:8767eb0032732c3a0da92cbec5ac186ef89a3258c6edca09161472ca0206c45f",
                "sha256:8acc8910218555044e23826980b950e96685dc48124a290c86f6f41a296ea172",
                "sha256:ab189a6365be1860a5ecf8159c248f12d33f79ea799ae9695fa6a29896dcf1d4",
                "sha256:cfd6535feb0f1cf1c7cdb25773e965cc9f92928244a8c3ef6f8f8a8e1f7ae5c4",
                "sha256:e274cd4480d8c76ec467a85a9c6635bbf2258f0649040560382ab58cabb44bcf",
                "sha256:f86642d60dca13e93260187d56c2bef2487aa4d574a669e8ceefcf9f4c26fd00",
                "sha256:f8a57cbda46a94ed0db55b73e6ab0c15e78b4ede8690fa491a0e55128d552bb0",
                "sha256:fcea97a352416afcbccd7af9625159d80704a25c519c251c734527329bb20d0e"
            ],
            "version": "==0.5.6"
        },
        "msgpack-numpy": {
            "hashes": [
                "sha256:0a8256ffcbee7fef50eff89a452e8873089e03d0bf88d83af87023ac71fdcf68",
                "sha256:7253c389db3d858101bc38272c2f14936f5760e889cccf0d5683375327b6915d"
            ],
            "index": "pypi",
            "version": "==0.4.3.2"
        },
        "murmurhash": {
            "hashes": [
                "sha256:651137ed3e1169342c9edade454f3beb7fcdf28d4ad1ac232725237eaf442d9a"
            ],
            "index": "pypi",
            "version": "==0.28.0"
        },
        "numpy": {
            "hashes": [
                "sha256:1b1cf8f7300cf7b11ddb4250b3898c711a6187df05341b5b7153db23ffe5d498",
                "sha256:27a0d018f608a3fe34ac5e2b876f4c23c47e38295c47dd0775cc294cd2614bc1",
                "sha256:3fde172e28c899580d32dc21cb6d4a1225d62362f61050b654545c662eac215a",
                "sha256:497d7c86df4f85eb03b7f58a7dd0f8b948b1f582e77629341f624ba301b4d204",
                "sha256:4e28e66cf80c09a628ae680efeb0aa9a066eb4bb7db2a5669024c5b034891576",
                "sha256:58be95faf0ca2d886b5b337e7cba2923e3ad1224b806a91223ea39f1e0c77d03",
                "sha256:5b4dfb6551eaeaf532054e2c6ef4b19c449c2e3a709ebdde6392acb1372ecabc",
                "sha256:63f833a7c622e9082df3cbaf03b4fd92d7e0c11e2f9d87cb57dbf0e84441964b",
                "sha256:71bf3b7ca15b1967bba3a1ef6a8e87286382a8b5e46ac76b42a02fe787c5237d",
                "sha256:733dc5d47e71236263837825b69c975bc08728ae638452b34aeb1d6fa347b780",
                "sha256:82f00a1e2695a0e5b89879aa25ea614530b8ebdca6d49d4834843d498e8a5e92",
                "sha256:866bf72b9c3bfabe4476d866c70ee1714ad3e2f7b7048bb934892335e7b6b1f7",
                "sha256:8aeac8b08f4b8c52129518efcd93706bb6d506ccd17830b67d18d0227cf32d9e",
                "sha256:8d2cfb0aef7ec8759736cce26946efa084cdf49797712333539ef7d135e0295e",
                "sha256:981224224bbf44d95278eb37996162e8beb6f144d2719b144e86dfe2fce6c510",
                "sha256:981daff58fa3985a26daa4faa2b726c4e7a1d45178100125c0e1fdaf2ac64978",
                "sha256:9ad36dbfdbb0cba90a08e7343fadf86f43cf6d87450e8d2b5d71d7c7202907e4",
                "sha256:a251570bb3cb04f1627f23c234ad09af0e54fc8194e026cf46178f2e5748d647",
                "sha256:b5ff7dae352fd9e1edddad1348698e9fea14064460a7e39121ef9526745802e6",
                "sha256:c898f9cca806102fcacb6309899743aa39efb2ad2a302f4c319f54db9f05cd84",
                "sha256:cf4b970042ce148ad8dce4369c02a4078b382dadf20067ce2629c239d76460d1",
                "sha256:d1569013e8cc8f37e9769d19effdd85e404c976cd0ca28a94e3ddc026c216ae8",
                "sha256:dca261e85fe0d34b2c242ecb31c9ab693509af2cf955d9caf01ee3ef3669abd0",
                "sha256:ec8bf53ef7c92c99340972519adbe122e82c81d5b87cbd955c74ba8a8cd2a4ad",
                "sha256:f2e55726a9ee2e8129d6ce6abb466304868051bcc7a09d652b3b07cd86e801a2",
                "sha256:f4dee74f2626c783a3804df9191e9008946a104d5a284e52427a53ff576423cb",
                "sha256:f592fd7fe1f20b5041928cce1330937eca62f9058cb41e69c2c2d83cffc0d1e3",
                "sha256:ffab5b80bba8c86251291b8ce2e6c99a61446459d4c6637f5d5cc8c9ce37c972"
            ],
            "index": "pypi",
            "version": "==1.15.2"
        },
        "pathlib": {
            "hashes": [
                "sha256:6940718dfc3eff4258203ad5021090933e5c04707d5ca8cc9e73c94a7894ea9f"
            ],
            "index": "pypi",
            "version": "==1.0.1"
        },
        "pbr": {
            "hashes": [
                "sha256:1be135151a0da949af8c5d0ee9013d9eafada71237eb80b3ba8896b4f12ec5dc",
                "sha256:cf36765bf2218654ae824ec8e14257259ba44e43b117fd573c8d07a9895adbdd"
            ],
            "version": "==4.3.0"
        },
        "plac": {
            "hashes": [
                "sha256:854693ad90367e8267112ffbb8955f57d6fdeac3191791dc9ffce80f87fd2370",
                "sha256:ba3f719a018175f0a15a6b04e6cc79c25fd563d348aacd320c3644d2a9baf89b"
            ],
            "index": "pypi",
            "version": "==0.9.6"
        },
        "pluggy": {
            "hashes": [
                "sha256:6e3836e39f4d36ae72840833db137f7b7d35105079aee6ec4a62d9f80d594dd1",
                "sha256:95eb8364a4708392bae89035f45341871286a333f749c3141c20573d2b3876e1"
            ],
            "version": "==0.7.1"
        },
        "preshed": {
            "hashes": [
                "sha256:7b99ace606143a922163a7ff7ad4969b296288f5b20b9c9bda328caec3b92f71"
            ],
            "index": "pypi",
            "version": "==1.0.1"
        },
        "py": {
            "hashes": [
                "sha256:bf92637198836372b520efcba9e020c330123be8ce527e535d185ed4b6f45694",
                "sha256:e76826342cefe3c3d5f7e8ee4316b80d1dd8a300781612ddbc765c17ba25a6c6"
            ],
            "version": "==1.7.0"
        },
        "pytest": {
            "hashes": [
                "sha256:7e258ee50338f4e46957f9e09a0f10fb1c2d05493fa901d113a8dafd0790de4e",
                "sha256:9332147e9af2dcf46cd7ceb14d5acadb6564744ddff1fe8c17f0ce60ece7d9a2"
            ],
            "index": "pypi",
            "version": "==3.8.2"
        },
        "regex": {
            "hashes": [
                "sha256:079c656874ba6c2e3332df488d4eff33b94b4e260e3901dce1553cb4f1f36c73",
                "sha256:139678fc013b75e486e580c39b4c52d085ed7362e400960f8be1711a414f16b5",
                "sha256:26795107acb81bb07ef832832548834b03846eb046e5ba9a5917ee012c68c1e6",
                "sha256:28a542117efd479cff110711c28f34cb40636f670d427dc42710b5183fbd92c4",
                "sha256:3e2609e0e366b21c3db3d41159d99e7bd37e02caaba24bba77ec5cc594c62c4e",
                "sha256:45fed2f98e5ca0fc420ff31cbd9eccbee41e4d607569fddaba0faea36ef6043d",
                "sha256:47230e1af3479810b1ef2bf23768b5195588a03eea6248b678d6893c48f58082",
                "sha256:51306abdaac9e712b208066d284ddc7e3a332c77ad6054ba8d305d607609a328",
                "sha256:5f15a27c24ed4ad2ed492abe80ddf27d35d63ef6c0d8878c915de6bf9f36c6f3",
                "sha256:660990e223ef2f71cb78b4e106a9a023652a31fd305051a901b0f87171b69e24",
                "sha256:67025161b70b0625749b1b89200da59fecc2fda9d1e46f9ef588f9a4af9fc48f",
                "sha256:801e054c1aa163545d29e186a1bea779437a19b49c4da9e11049624c2d2bfd31",
                "sha256:93064faef899911a7378443fcfb1f2e93e19706a324162fc71dd996c85b24f37",
                "sha256:9c4b23f8a68470522a0cdfbdcffbe2f61d7659b5d505cb7c1a729a6805345210",
                "sha256:c1ef8f72944bef49261daaa83c7d77439f54f8deefefc0e2cf7144ac8b20ac1f"
            ],
            "index": "pypi",
            "version": "==2018.1.10"
        },
        "requests": {
            "hashes": [
                "sha256:63b52e3c866428a224f97cab011de738c36aec0185aa91cfacd418b5d58911d1",
                "sha256:ec22d826a36ed72a7358ff3fe56cbd4ba69dd7a6718ffd450ff0e9df7a47ce6a"
            ],
            "index": "pypi",
            "version": "==2.19.1"
        },
        "six": {
            "hashes": [
                "sha256:70e8a77beed4562e7f14fe23a786b54f6296e34344c23bc42f07b15018ff98e9",
                "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb"
            ],
            "version": "==1.11.0"
        },
        "spacy": {
            "editable": true,
            "git": "https://github.com/explosion/spaCy",
            "ref": "42c42376a3685f138532fff2cfe44d726cafe4bc"
        },
        "thinc": {
            "hashes": [
                "sha256:6e89d60f6165685837ebaff6a978ea9ca2b6c8c551a0886125c27de42e8fcf04"
            ],
            "index": "pypi",
            "version": "==6.10.3"
        },
        "toolz": {
            "hashes": [
                "sha256:929f0a7ea7f61c178bd951bdae93920515d3fbdbafc8e6caf82d752b9b3b31c9"
            ],
            "version": "==0.9.0"
        },
        "tqdm": {
            "hashes": [
                "sha256:18f1818ce951aeb9ea162ae1098b43f583f7d057b34d706f66939353d1208889",
                "sha256:df02c0650160986bac0218bb07952245fc6960d23654648b5d5526ad5a4128c9"
            ],
            "version": "==4.26.0"
        },
        "ujson": {
            "hashes": [
                "sha256:f66073e5506e91d204ab0c614a148d5aa938bdbf104751be66f8ad7a222f5f86"
            ],
            "index": "pypi",
            "version": "==1.35"
        },
        "urllib3": {
            "hashes": [
                "sha256:a68ac5e15e76e7e5dd2b8f94007233e01effe3e50e8daddf69acfd81cb686baf",
                "sha256:b5725a0bd4ba422ab0e66e89e030c806576753ea3ee08554382c14e685d117b5"
            ],
            "version": "==1.23"
        },
        "wrapt": {
            "hashes": [
                "sha256:d4d560d479f2c21e1b5443bbd15fe7ec4b37fe7e53d335d3b9b0a7b1226fe3c6"
            ],
            "version": "==1.10.11"
        }
    },
    "develop": {}
}

```
</details>

**Comment by uranusjr** [comment]
I… don’t think this is an intended usage? What prompted you (or spbks on SO) to think it should recognise it? No tool does in my knowledge. `pip install -e git+https://github.com/explosion/spaCy#egg=spaCy` would fail as well unless you manual install requirements.txt first.

Briefly reading the problem and spaCy’s setup.py, this looks like a problem on spaCy’s end. It needs to specify build requirements better (via PEP 518 or `setup_requires`) to support installing from (non-distributed) source, but reading how it constructs its setup.py, I am under the impression it does not really intend to support installing from Git anyway.

**Comment by rbricheno** [comment]
Thank you, I will raise this with spaCy in case they wish to address it. Feel free to close this.
