### ISSUE TITLE
Pipenv Can't install SRTM.py

### ISSUE THREAD

**Issue by rcoh** [pypa/pipenv#3016]
### Issue description
The package `SRTM.py` is uninstallable by pipenv `2018.10.9`. It works on `11.8.0`, but I haven't bisected.

```
root@0726538b9c5a:/app# pipenv install srtm.py
Installing srtm.py…
Collecting srtm-py

Error:  An error occurred while installing srtm.py!
  Could not find a version that satisfies the requirement srtm-py (from versions: )
No matching distribution found for srtm-py
```

The package installs fine with pip. My hunch is that that `.` is being replaced with a `-` for some reason, but this package is only published with a `.`

### Expected result

Package should be installed. The package is installable with `pip` and with older versions of `pipenv`

### Actual result

```
⠋Installing 'srtm.py'
$ ['/root/.local/share/virtualenvs/app-4PlAip0Q/bin/pip', 'install', '--pre', '--verbose', '--upgrade', 'srtm-py', '-i', 'https://pypi.org/simple']
Created temporary directory: /tmp/pip-ephem-wheel-cache-jwnpisbl
Created temporary directory: /tmp/pip-req-tracker-tni1fr3_
Created requirements tracker '/tmp/pip-req-tracker-tni1fr3_'
Created temporary directory: /tmp/pip-install-lj4jxf6i
Collecting srtm-py
  1 location(s) to search for versions of srtm-py:
  * https://pypi.org/simple/srtm-py/
  Getting page https://pypi.org/simple/srtm-py/
  Looking up "https://pypi.org/simple/srtm-py/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/srtm-py/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/srtm-py/
    Skipping link https://files.pythonhosted.org/packages/07/48/2d39830d41d0649143c9dd13d432f2bddff3eed62a15238a11e3649ce970/SRTM.py-0.0.1.tar.gz#sha256=d437ba34771aea15ad1f853061e0079463d08cd8f619024b0cbce28e9909ec5b (from https://pypi.org/simple/srtm-py/); Missing project version for srtm-py
    Skipping link https://files.pythonhosted.org/packages/3c/63/62e9e6d0a47341ec1dc6852d8bf7ed05dbfcbdd94627f764fd7bff57e8f1/SRTM.py-0.0.2.tar.gz#sha256=905befd4421217953fc70822fca73997cf20be36ac9f842c874bd47cfbcfb804 (from https://pypi.org/simple/srtm-py/); Missing project version for srtm-py
    Skipping link https://files.pythonhosted.org/packages/5e/68/1e0b1a87945f7827425c11ee5066253cf3b18bbe5fdc0d0ee5ce815684c2/SRTM.py-0.1.0.tar.gz#sha256=099e662eac593d05164e8c08cd02ef884e821d4668b9aafb130e7b8a524deb7e (from https://pypi.org/simple/srtm-py/); Missing project version for srtm-py
    Skipping link https://files.pythonhosted.org/packages/e7/a9/863d72c6bbca504ac8de5507ce3aefc4476025f0dfdd342bd778da5291e0/SRTM.py-0.1.1.tar.gz#sha256=52c607e80e1ba1a964e3be518c5069ad698e8718174d5a0778ee6c927a4e8ee6 (from https://pypi.org/simple/srtm-py/); Missing project version for srtm-py
    Skipping link https://files.pythonhosted.org/packages/6f/f2/b34915a0952827f48db14fee4bee3b6d30a494da03bd6ae62e244d93d394/SRTM.py-0.1.2.tar.gz#sha256=09ae322313dc0a698b7802e79f725a2822a7ebfeb63991725333958b303d7563 (from https://pypi.org/simple/srtm-py/); Missing project version for srtm-py
    Skipping link https://files.pythonhosted.org/packages/53/80/27a17584225df95cb44c3c0ee699d52f7f0cf8ea0c2a8b512b758b973fb0/SRTM.py-0.2.0.tar.gz#sha256=5eb9421d7ad131f8b984e131eee166c1d7df327b7da1d86d8cb7f423e1f3396b (from https://pypi.org/simple/srtm-py/); Missing project version for srtm-py
    Skipping link https://files.pythonhosted.org/packages/a6/e2/339c77c786c0263bc259f01c3abf7d12ac3a19f6d9d1b9505cfb59d7327e/SRTM.py-0.2.1.tar.gz#sha256=72a5afef295d842c637e978bb8ccb12a164bc35628af13577ccc6a207f3721c6 (from https://pypi.org/simple/srtm-py/); Missing project version for srtm-py
    Skipping link https://files.pythonhosted.org/packages/55/43/fb3aeb004d4c6c759ed52450bb26121aa97752079aa760e76dfdee51f35e/SRTM.py-0.2.3.tar.gz#sha256=2301a7b83fbf756e03ac7eccd98bc61ab7d4ee2bbf548cac79ccb131db6f660f (from https://pypi.org/simple/srtm-py/); Missing project version for srtm-py
    Skipping link https://files.pythonhosted.org/packages/ff/c5/ff7d4039a3c66563e79f811b91b11b85f58099da43f1bf2ed5a86228d9c4/SRTM.py-0.2.4.tar.gz#sha256=debf86b63f8f89549eb3f3e3883c336ae756ce3331e4dcf614a973021b3c229f (from https://pypi.org/simple/srtm-py/); Missing project version for srtm-py
    Skipping link https://files.pythonhosted.org/packages/72/d2/2db257f0bdecdf5467c5418bdff3fa67d99a2e332edd5876179b5cef70d3/SRTM.py-0.3.0.tar.gz#sha256=4ade9d44897f6a4df9cf75d04afc22bc428412a7e437a210e8031578e575c861 (from https://pypi.org/simple/srtm-py/); Missing project version for srtm-py
    Skipping link https://files.pythonhosted.org/packages/cd/d9/e75fbca3761b63bbebca09328d3c3f638c31739b4f40c72c5ce536d89c02/SRTM.py-0.3.1.tar.gz#sha256=0e4a8330b27b58cd8b497cedea24790a3129fe60e35c515aadeaf8cb3deca8b9 (from https://pypi.org/simple/srtm-py/); Missing project version for srtm-py
    Skipping link https://files.pythonhosted.org/packages/65/5e/1e2b1b0a68507d2b52a9cd0f832dad94c89b819a6187944e31d0e0c9d9e3/SRTM.py-0.3.2.tar.gz#sha256=08ae42de3e2b76517a476038dfa4078eaff9bf47ed7406d59b630d0af96c842c (from https://pypi.org/simple/srtm-py/); Missing project version for srtm-py
    Skipping link https://files.pythonhosted.org/packages/5f/c1/62180a16dd0ff62276b5e65c5383cb2366d9bc6f70e998ba83a3584770b8/SRTM.py-0.3.3.tar.gz#sha256=d502303ecdea96991e220834bd91b99a08f95cd89de4307ae7bd42bdca278d48 (from https://pypi.org/simple/srtm-py/); Missing project version for srtm-py
    Skipping link https://files.pythonhosted.org/packages/8a/c3/cc98d146b12174e0bd0209fa613dca21ab529b2820f5347a62b05cb363f8/SRTM.py-0.3.4.tar.gz#sha256=42cce7a63650963c619c15b749e9d754ad8fa56e277b1529865105275f4e3c9b (from https://pypi.org/simple/srtm-py/); Missing project version for srtm-py
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-tni1fr3_'
Exception information:
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 318, in run
    resolver.resolve(requirement_set)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 218, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 164, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/pip/_internal/index.py", line 621, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for srtm-py

Error:  An error occurred while installing srtm.py!
  Could not find a version that satisfies the requirement srtm-py (from versions: )
No matching distribution found for srtm-py
```

### Steps to replicate

1. Create an empty directory.
2. `pipenv install srtm.py`

**Comment by uranusjr** [comment]
#3013 (and various others)
