### ISSUE TITLE
pipenv 2018.10.9 broken by module name collision

### ISSUE THREAD

**Issue by chanpl** [pypa/pipenv#3035]
### Issue description

When using pipenv 2018.10.9 under Python 2.7 and tox, if there exists a 3rd party module 'backports', pipenv will be broken. See:

```
# pipenv/vendor/vistir/compat.py

if sys.version_info < (3, 3):
    from backports.shutil_get_terminal_size import get_terminal_size  # use relative import to avoid module name collision
    from .backports.tempfile import NamedTemporaryFile
else:
    from tempfile import NamedTemporaryFile
    from shutil import get_terminal_size
```

### Expected result
We expect pipenv to import its own 'backports' module.

### Actual result
Another 'backports' is imported instead. 

> 
  Traceback (most recent call last):
  File ".tox/py27/bin/pipenv", line 7, in <module>
    from pipenv import cli
  File ".tox/py27/lib/python2.7/site-packages/pipenv/__init__.py", line 23, in <module>
    from .cli import cli
  File ".tox/py27/lib/python2.7/site-packages/pipenv/cli/__init__.py", line 3, in <module>
    from .command import cli
  File ".tox/py27/lib/python2.7/site-packages/pipenv/cli/command.py", line 18, in <module>
    from .. import environments
  File ".tox/py27/lib/python2.7/site-packages/pipenv/environments.py", line 4, in <module>
    from .vendor.vistir.misc import fs_str
  File ".tox/py27/lib/python2.7/site-packages/pipenv/vendor/vistir/__init__.py", line 4, in <module>
    from .compat import NamedTemporaryFile, TemporaryDirectory, partialmethod
  File ".tox/py27/lib/python2.7/site-packages/pipenv/vendor/vistir/compat.py", line 33, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size
ImportError: No module named shutil_get_terminal_size
ERROR: InvocationError for command '.tox/py27/bin/pipenv install --dev --deploy' (exited with code 1)

**Comment by techalchemy** [comment]
This is fixed in the bugfix release from yesterday — pleases upgrade! Sorry for the annoyance
