### ISSUE TITLE
ValueError when env variable password contains hash

### ISSUE THREAD

**Issue by Vayel** [pypa/pipenv#3085]
### Issue description

When a password passed through an env variable contains a hash (e.g. `ab#cd`), a `ValueError` is raised when calling `pipenv install`. The error is **not** raised when the username also contains a hash.

### Expected result

Just install the dependencies if the credentials are valid.

### Actual result

```
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
using sources: [{'url': 'https://pypi.org/simple', 'verify_ssl': True, 'name': 'pypi'}, {'url': 'https://user:pass#word@simudyne.jfrog.io/simudyne/api/pypi/simudyne-pypi/simple', 'verify_ssl': True, 'name': 'simudyne_pypi'}]
Using pip: -i https://pypi.org/simple --extra-index-url https://user:pass#word@simudyne.jfrog.io/simudyne/api/pypi/simudyne-pypi/simple

                          ROUND 1                           
Current constraints:
  ipykernel
  simudyne

Finding the best candidates:

Traceback (most recent call last):
  File "/home/simudyne/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 101, in <module>
    main()
  File "/home/simudyne/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 90, in main
    system=system,
  File "/home/simudyne/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 73, in resolve
    allow_global=system,
  File "/home/simudyne/.local/lib/python3.6/site-packages/pipenv/utils.py", line 422, in resolve_deps
    req_dir=req_dir,
  File "/home/simudyne/.local/lib/python3.6/site-packages/pipenv/utils.py", line 302, in actually_resolve_deps
    results = resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/simudyne/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/simudyne/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 198, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/home/simudyne/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 198, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/home/simudyne/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 263, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "/home/simudyne/.local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 165, in find_best_match
    all_candidates = clean_requires_python(self.find_all_candidates(ireq.name))
  File "/home/simudyne/.local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in find_all_candidates
    candidates = self.finder.find_all_candidates(req_name)
  File "/home/simudyne/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/index.py", line 458, in find_all_candidates
    (Link(url) for url in dep_url_loc),
  File "/home/simudyne/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/index.py", line 460, in <listcomp>
    if self._validate_secure_origin(logger, link)
  File "/home/simudyne/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/index.py", line 341, in _validate_secure_origin
    origin = (parsed.scheme, parsed.hostname, parsed.port)
  File "/home/simudyne/anaconda3/lib/python3.6/urllib/parse.py", line 167, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'pass'
```

### Steps to replicate

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://${USER}:${PASSWORD}@simudyne.jfrog.io/simudyne/api/pypi/simudyne-pypi/simple"
verify_ssl = true
name = "simudyne_pypi"

[packages]
ipykernel = "*"
simudyne = {version = "*", index = "simudyne_pypi"}
```

This raises the `ValueError`:

```
export USER="user"
export PASSWORD="pass#word"
pipenv install
```

This **doesn't** raise the `ValueError`:

```
export USER="user"
export PASSWORD="password"
pipenv install
```

This **doesn't** raise the `ValueError`:

```
export USER="us#er"
export PASSWORD="pass#word"
pipenv install
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.13'`

Pipenv location: `'/home/simudyne/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/home/simudyne/anaconda3/bin/python3'`

Python installations found:

  - `3.6.6`: `/usr/bin/python3.6`
  - `3.6.6`: `/usr/bin/python3.6m`
  - `2.7.15rc1`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-36-generic',
 'platform_system': 'Linux',
 'platform_version': '#39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `CLUTTER_IM_MODULE`
  - `SIMUDYNE_PASSWORD`
  - `LS_COLORS`
  - `LESSCLOSE`
  - `XDG_MENU_PREFIX`
  - `LANG`
  - `GDM_LANG`
  - `DISPLAY`
  - `OLDPWD`
  - `GTK2_MODULES`
  - `COLORTERM`
  - `XDG_VTNR`
  - `PASSWORD`
  - `SSH_AUTH_SOCK`
  - `MANDATORY_PATH`
  - `XDG_SESSION_ID`
  - `XDG_GREETER_DATA_DIR`
  - `USER`
  - `DESKTOP_SESSION`
  - `QT4_IM_MODULE`
  - `TEXTDOMAINDIR`
  - `GNOME_TERMINAL_SCREEN`
  - `DEFAULTS_PATH`
  - `QT_QPA_PLATFORMTHEME`
  - `PWD`
  - `HOME`
  - `TEXTDOMAIN`
  - `SSH_AGENT_PID`
  - `QT_ACCESSIBILITY`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `XDG_SESSION_DESKTOP`
  - `GJS_DEBUG_OUTPUT`
  - `GTK_MODULES`
  - `TERM`
  - `SHELL`
  - `VTE_VERSION`
  - `XDG_SEAT_PATH`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `IM_CONFIG_PHASE`
  - `XDG_CURRENT_DESKTOP`
  - `GPG_AGENT_INFO`
  - `GNOME_TERMINAL_SERVICE`
  - `XDG_SEAT`
  - `SHLVL`
  - `LANGUAGE`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `XDG_SESSION_PATH`
  - `XDG_CONFIG_DIRS`
  - `PATH`
  - `AAA_BBB`
  - `GJS_DEBUG_TOPICS`
  - `SESSION_MANAGER`
  - `SIMUDYNE_USER`
  - `LESSOPEN`
  - `GTK_IM_MODULE`
  - `_`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/simudyne/anaconda3/bin:/home/simudyne/bin:/home/simudyne/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/home/simudyne/Documents/python-client-app-example`

---------------------------

Contents of `Pipfile` ('/home/simudyne/Documents/python-client-app-example/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://${USER}:${PASSWORD}@simudyne.jfrog.io/simudyne/api/pypi/simudyne-pypi/simple"
verify_ssl = true
name = "simudyne_pypi"

[packages]
ipykernel = "*"
simudyne = {version = "*", index = "simudyne_pypi"}

```

</details>

**Comment by Vayel** [comment]
Actually, that's a problem with pip:

```
$ pip install -i https://pypi.org/simple --extra-index-url https://user:pass#word@simudyne.jfrog.io/simudyne/api/pypi/simudyne-pypi/simple simudyne
Looking in indexes: https://pypi.org/simple, https://user:pass#word@simudyne.jfrog.io/simudyne/api/pypi/simudyne-pypi/simple
Requirement already satisfied: simudyne in /home/simudyne/anaconda3/lib/python3.6/site-packages/simudyne-0.2-py3.6.egg (0.2)
Requirement already satisfied: requests in /home/simudyne/anaconda3/lib/python3.6/site-packages (from simudyne) (2.18.4)
Requirement already satisfied: objectpath in /home/simudyne/anaconda3/lib/python3.6/site-packages/objectpath-0.5-py3.6.egg (from simudyne) (0.5)
Requirement already satisfied: pytz in /home/simudyne/anaconda3/lib/python3.6/site-packages (from simudyne) (2017.3)
Requirement already satisfied: numpy in /home/simudyne/anaconda3/lib/python3.6/site-packages (from simudyne) (1.14.0)
Requirement already satisfied: pandas in /home/simudyne/anaconda3/lib/python3.6/site-packages (from simudyne) (0.22.0)
Requirement already satisfied: pyDOE in /home/simudyne/anaconda3/lib/python3.6/site-packages (from simudyne) (0.3.8)
Requirement already satisfied: matplotlib in /home/simudyne/anaconda3/lib/python3.6/site-packages (from simudyne) (2.1.2)
Requirement already satisfied: plotly in /home/simudyne/anaconda3/lib/python3.6/site-packages (from simudyne) (2.5.1)
Requirement already satisfied: fastparquet in /home/simudyne/anaconda3/lib/python3.6/site-packages/fastparquet-0.1.6-py3.6-linux-x86_64.egg (from simudyne) (0.1.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/simudyne/anaconda3/lib/python3.6/site-packages (from requests->simudyne) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /home/simudyne/anaconda3/lib/python3.6/site-packages (from requests->simudyne) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/simudyne/anaconda3/lib/python3.6/site-packages (from requests->simudyne) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /home/simudyne/anaconda3/lib/python3.6/site-packages (from requests->simudyne) (2018.4.16)
Requirement already satisfied: python-dateutil>=2 in /home/simudyne/anaconda3/lib/python3.6/site-packages (from pandas->simudyne) (2.6.1)
Requirement already satisfied: scipy in /home/simudyne/anaconda3/lib/python3.6/site-packages (from pyDOE->simudyne) (1.0.0)
Requirement already satisfied: six>=1.10 in /home/simudyne/anaconda3/lib/python3.6/site-packages (from matplotlib->simudyne) (1.11.0)
Requirement already satisfied: cycler>=0.10 in /home/simudyne/anaconda3/lib/python3.6/site-packages (from matplotlib->simudyne) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/simudyne/anaconda3/lib/python3.6/site-packages (from matplotlib->simudyne) (2.2.0)
Requirement already satisfied: decorator>=4.0.6 in /home/simudyne/anaconda3/lib/python3.6/site-packages (from plotly->simudyne) (4.2.1)
Requirement already satisfied: nbformat>=4.2 in /home/simudyne/anaconda3/lib/python3.6/site-packages (from plotly->simudyne) (4.4.0)
Requirement already satisfied: numba>=0.28 in /home/simudyne/anaconda3/lib/python3.6/site-packages (from fastparquet->simudyne) (0.36.2)
Collecting thrift>=0.11.0 (from fastparquet->simudyne)
Exception:
Traceback (most recent call last):
  File "/home/simudyne/anaconda3/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/home/simudyne/anaconda3/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 318, in run
    resolver.resolve(requirement_set)
  File "/home/simudyne/anaconda3/lib/python3.6/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/simudyne/anaconda3/lib/python3.6/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/simudyne/anaconda3/lib/python3.6/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/home/simudyne/anaconda3/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 218, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/home/simudyne/anaconda3/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 164, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/simudyne/anaconda3/lib/python3.6/site-packages/pip/_internal/index.py", line 572, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/home/simudyne/anaconda3/lib/python3.6/site-packages/pip/_internal/index.py", line 509, in find_all_candidates
    (Link(url) for url in dep_url_loc),
  File "/home/simudyne/anaconda3/lib/python3.6/site-packages/pip/_internal/index.py", line 511, in <listcomp>
    if self._validate_secure_origin(logger, link)
  File "/home/simudyne/anaconda3/lib/python3.6/site-packages/pip/_internal/index.py", line 392, in _validate_secure_origin
    origin = (parsed.scheme, parsed.hostname, parsed.port)
  File "/home/simudyne/anaconda3/lib/python3.6/urllib/parse.py", line 167, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'pass'
```

**Comment by Vayel** [comment]
I had to percent-encode the password: https://superuser.com/questions/273799/how-to-use-special-characters-in-username-password-for-http-proxy

**Comment by uranusjr** [comment]
Sounds like a good documentation entry if we can figure out where to put it :)

**Comment by Vayel** [comment]
https://pipenv.readthedocs.io/en/latest/advanced/#injecting-credentials-into-pipfiles-via-environment-variables?

**Comment by Vayel** [comment]
I reopen the issue to suggest that pipenv could encode the credentials for us. Then it would be easier if there were dedicated fields for the credentials:

```
[[source]]
url = "https://simudyne.jfrog.io/simudyne/api/pypi/simudyne-pypi/simple"
verify_ssl = true
name = "simudyne_pypi"
user = "${USER}"
password = "${PASSWORD}"
```

**Comment by uranusjr** [comment]
I don’t think auto-encoding in URL is a good idea (because it would open the possibility of double-encoding), but dedicated credential fields could be. Would you mind creating a [PEEP](https://github.com/pypa/pipenv/blob/master/peeps/PEEP-000.md) for this?

**Comment by Vayel** [comment]
@uranusjr What would be the point of having dedicated credential fields if we don't do anything with their values?

**Comment by uranusjr** [comment]
Sorry, I guess I failed to make myself understood. I was trying to agree with you that an automatically encoded field needs to be specified in a dedicated field :)

**Comment by Vayel** [comment]
Do I need to make a PR with a Markdown file for the PEEP? I can't find the step-by-step process to follow.

**Comment by uranusjr** [comment]
yup
