### ISSUE TITLE
Resource warning when using pyenv.

### ISSUE THREAD

**Issue by jrvanalstine** [pypa/pipenv#3094]
I have been using pipenv with pyenv successfully for a while. I have recently moved to new ubuntu 18.04, and now I am getting this error. Hoping it's something on my end. Pipenv install works just fine if I use the interpreter on my machine (3.6.6). It breaks when used in conjunction with pyenv.

TRACE:

<pre>
pipenv install
Warning: Python 3.6.4 was not found on your system…
Would you like us to install CPython 3.6.4 with pyenv? [Y/n]: y
Installing CPython 3.6.4 with pyenv (this may take a few minutes)…
Traceback (most recent call last):
  File "/home/james/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/cli/command.py", line 249, in install
    editable_packages=state.installstate.editables,
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/core.py", line 1724, in do_install
    pypi_mirror=pypi_mirror,
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/core.py", line 565, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/core.py", line 488, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/core.py", line 451, in ensure_python
    c = pyenv.install(version)
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/pyenv.py", line 117, in install
    timeout=PIPENV_INSTALL_TIMEOUT,
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/pyenv.py", line 73, in _pyenv
    raise PyenvError('faild to run {0}'.format(args), c)
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/pyenv.py", line 56, in __init__
    self.err = c.err
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/vendor/delegator.py", line 146, in err
    return self._pexpect_out
  File "/home/james/.local/lib/python2.7/site-packages/pipenv/vendor/delegator.py", line 114, in _pexpect_out
    result += self.subprocess.after
TypeError: coercing to Unicode: need string or buffer, type found
/home/james/.local/lib/python2.7/site-packages/pipenv/vendor/vistir/compat.py:109: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-hOIHQW-requirements'>
  warnings.warn(warn_message, ResourceWarning)
</pre>

PIPFILE:
<pre>
[[source]]
url="https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
numpy = "*"
pandas = "*"
requests = "*"
scipy = "*"
mypy = "*"
scikit-learn = "*"
joblib = "*"
pprint = "*"

[dev-packages]

pytest = "*"

[requires]
python_version = "3.6.4"
</pre>

PIPENV VERSION:
2018.10.13

**Comment by jrvanalstine** [comment]
I have tried installing pipenv with pip and pip3 and no luck.
