### ISSUE TITLE
pipenv --support is broken for fresh dev install

### ISSUE THREAD

**Issue by taylor-chen** [pypa/pipenv#3095]
### Issue description
Trying to run a fresh dev install and pipenv seemed to install fine. 
I tried to run the unit tests with 
```
$ pytest tests/unit                                                                                                        
/Users/taylor.chen/pipenvtest/pypi
usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n
  inifile: /Users/taylor.chen/pipenvtest/pytest.ini
  rootdir: /Users/taylor.chen/pipenvtest

```
after removing `-n auto` from pytest.ini, the tests run and i see one test fail for 
```
E               subprocess.CalledProcessError: Command '['/usr/local/opt/python/bin/python3.6', '-m', 'pipenv.help']' returned non-zero exit status 1.
```
I try and run 
```
python3 -m pipenv.help 
```
and I see the error below

### Expected result

`pipenv --support` not to return an error

### Actual result

```
$ pipenv --support                                                                                                          
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.14.dev0'`

Pipenv location: `'/Users/taylor.chen/pipenvtest/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.6'`

Python installations found:

Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv', 'console_scripts', 'pipenv')()
  File "/Users/taylor.chen/pipenvtest/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/taylor.chen/pipenvtest/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/taylor.chen/pipenvtest/pipenv/vendor/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/Users/taylor.chen/pipenvtest/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/taylor.chen/pipenvtest/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/taylor.chen/pipenvtest/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/taylor.chen/pipenvtest/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/taylor.chen/pipenvtest/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/taylor.chen/pipenvtest/pipenv/cli/command.py", line 142, in cli
    get_pipenv_diagnostics()
  File "/Users/taylor.chen/pipenvtest/pipenv/help.py", line 33, in get_pipenv_diagnostics
    python_paths = finder.find_all_python_versions()
  File "/Users/taylor.chen/pipenvtest/pipenv/vendor/pythonfinder/pythonfinder.py", line 112, in find_all_python_versions
    major=major, minor=minor, patch=patch, pre=pre, dev=dev, arch=arch
  File "/Users/taylor.chen/pipenvtest/pipenv/vendor/pythonfinder/models/path.py", line 222, in find_all_python_versions
    return [c for c in sorted(path_filter, key=version_sort, reverse=True)]
AttributeError: 'list' object has no attribute 'as_python'
```

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).
```
git clone https://github.com/pypa/pipenv.git pipenvtest
cd pipenvtest 
pip install -e . 
pipenv install --dev
```

**Comment by techalchemy** [comment]
See also: #3121 (this should be fixed by #3096)
