### ISSUE TITLE
Pipenv fails to create virtualenv when directory contains colon

### ISSUE THREAD

**Issue by lbenezriravin** [pypa/pipenv#3189]
### Issue description

Pipenv cannot create a virtualenv when the working directory contains colon.

### Expected result

A virtualenv to be created as normal

### Actual result

```
$ pwd
/home/user/a:a
$ pipenv --python 3.7 --verbose
Creating a virtualenv for this project…
Pipfile: /home/user/a:a/Pipfile
Using /usr/bin/python3.7 (3.7.0) to create virtualenv…
⠸Running virtualenv with interpreter /usr/bin/python3.7
Using base prefix '/usr'
/home/user/.local/lib/python2.7/site-packages/virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /home/user/.local/share/virtualenvs/a:a-Oe7g_AWA/bin/python3.7
Also creating executable in /home/user/.local/share/virtualenvs/a:a-Oe7g_AWA/bin/python
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f03effaa580 (most recent call first):
ERROR: The executable /home/user/.local/share/virtualenvs/a:a-Oe7g_AWA/bin/python3.7 is not functioning
ERROR: It thinks sys.prefix is '/home/user/a:a' (should be '/home/user/.local/share/virtualenvs/a:a-Oe7g_AWA')
ERROR: virtualenv is not compatible with this system or executable

Traceback (most recent call last):
  File "/home/user/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/home/user/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/pipenv/cli/command.py", line 203, in cli
    clear=state.clear,
  File "/home/user/.local/lib/python2.7/site-packages/pipenv/core.py", line 565, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/home/user/.local/lib/python2.7/site-packages/pipenv/core.py", line 500, in ensure_virtualenv
    python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
  File "/home/user/.local/lib/python2.7/site-packages/pipenv/core.py", line 901, in do_create_virtualenv
    click.echo(crayons.blue("{0}".format(c.err)), err=True)
  File "/home/user/.local/lib/python2.7/site-packages/pipenv/vendor/delegator.py", line 146, in err
    return self._pexpect_out
  File "/home/user/.local/lib/python2.7/site-packages/pipenv/vendor/delegator.py", line 114, in _pexpect_out
    result += self.subprocess.after
TypeError: coercing to Unicode: need string or buffer, type found
```

### Steps to replicate

Run any `pipenv` command in a directory that contains a colon in the name.

-------------------------------------------------------------------------------
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.13'`

Pipenv location: `'/home/user/.local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/bin/python2'`

Python installations found:

  - `3.7.0`: `/usr/bin/python3.7`
  - `3.6.6`: `/usr/bin/python3.6`
  - `3.6.6`: `/usr/bin/python3.6m`
  - `3.7.0`: `/usr/bin/python3.7m`
  - `2.7.15`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.18.9-200.fc28.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Thu Sep 20 02:43:23 UTC 2018',
 'python_full_version': '2.7.15',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/user/.local/bin:/home/user/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/user/a:a`

---------------------------

Contents of `Pipfile` ('/home/user/a:a/Pipfile'):

```toml

```

</details>

**Comment by techalchemy** [comment]
This is not related to your directory name, but instead to a bug in `delegator.py` which is patched in the master branch and awaiting a few other small tweaks that are not related to this before we cut a release.  Sorry for the trouble!

**Comment by lbenezriravin** [comment]
@techalchemy I'm not sure it's unrelated. I have no trouble in any other directory, and I can reproduce this on the master branch (a1678859)

**Comment by techalchemy** [comment]
can you make a virtualenv from the command line in that location yourself? based on the error I'm not sure it's a pipenv issue:

```
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f03effaa580 (most recent call first):
ERROR: The executable /home/user/.local/share/virtualenvs/a:a-Oe7g_AWA/bin/python3.7 is not functioning
ERROR: It thinks sys.prefix is '/home/user/a:a' (should be '/home/user/.local/share/virtualenvs/a:a-Oe7g_AWA')
ERROR: virtualenv is not compatible with this system or executable
```

Can you run `virtualenv /home/user/.local/share/virtualenvs/a:a-Oe7g_AWA` successfully? I tried and I can't, even if I quote or escape the path.  This looks like a bug in either virtualenv or in python itself

**Comment by lbenezriravin** [comment]
You're right -- I get the same error with virtualenv.
