### ISSUE TITLE
2018.11.14 regression: KeyError: verify_ssl

### ISSUE THREAD

**Issue by myw** [pypa/pipenv#3233]
### Issue description

Pipenv (2018.11.14) errors when being called to install deps from a project with a `Pipfile` without a `verify_ssl` key.

### Expected result

`pipenv install --dev` works and exits `0`

### Actual result

Trace:
```
New python executable in /home/ginkgo/.local/share/virtualenvs/servicely-workflows-YJPopuIU/bin/python3
Also creating executable in /home/ginkgo/.local/share/virtualenvs/servicely-workflows-YJPopuIU/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/bin/python3
Virtualenv location: /home/ginkgo/.local/share/virtualenvs/servicely-workflows-YJPopuIU
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/cli/command.py", line 249, in install
    editable_packages=state.installstate.editables,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 1872, in do_install
    keep_outdated=keep_outdated
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 1232, in do_init
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 781, in do_install_dependencies
    lockfile = project.get_or_create_lockfile()
  File "/usr/local/lib/python3.6/dist-packages/pipenv/project.py", line 758, in get_or_create_lockfile
    } for s in sources
  File "/usr/local/lib/python3.6/dist-packages/pipenv/project.py", line 758, in <listcomp>
    } for s in sources
KeyError: 'verify_ssl'
The command '/bin/sh -c pipenv install --dev' returned a non-zero code: 1
```

### Steps to replicate

With the following `Pipfile`:

```ini
[[source]]
url = 'https://pypi.example.com/simple/'

[requires]
python_version = '3'

[packages]
celery = '>=4.2'
Django = '>=2.0'
ginkgo-common = '*'
ginkgo-log = '*'
gappy = '==1.6.0'
gunicorn = '==19.9.0'
lims_api_client = '==1.9.0'
pygments = '*'
requests = '*'
six = '*'
Sphinx = '*'
sphinx-rtd-theme = '*'
pre-commit = "==1.9.0"
whitenoise = '==3.3.1'

[dev-packages]
coverage = '*'
flake8 = '*'
flake8-diff = '*'
ipython = '*'
mock = '*'
pytest = '*'
nose = '*'
tox = '*'
yapf = '*'
```

Run `pipenv install --dev` 

Commit that introduced the error was 2b90c89d1f518a543f775cb811ee8b5565ee1366 

Fix may just be as simple as using `.get`

**Comment by jxltom** [comment]
The pipenv should provide default value ```true``` for ```verify_ssl``` when locking Pipfile, which does not contain ```verify_ssl``` field, to Pipfile.lock.
