### ISSUE TITLE
pipenv install 'flake8' wont' resolve depdencies because of increased restrictions

### ISSUE THREAD

**Issue by klauern** [pypa/pipenv#3309]
### Issue description

Installing 'flake8' introduces additional restrictions that result in a sub-dependency on `pyflakes` not matching any version.

### Expected result

it would install

### Actual result

```
$ pipenv install --verbose

Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking Failed!
Using pip: -i https://pypi.org/simple --trusted-host pypi.org
Using pip: -i https://pypi.org/simple --trusted-host pypi.org
Using pip: -i https://pypi.org/simple --trusted-host pypi.org

                          ROUND 1
Current constraints:
  bandit
  black
  flake8
  mypy
  prospector
  pytest

Finding the best candidates:
  found candidate bandit==1.5.1 (constraint was <any>)
  found candidate black==18.9b0 (constraint was <any>)
  found candidate flake8==3.6.0 (constraint was <any>)
  found candidate mypy==0.641 (constraint was <any>)
  found candidate prospector==1.1.6.2 (constraint was <any>)
  found candidate pytest==4.0.1 (constraint was <any>)

Finding secondary dependencies:
  bandit==1.5.1             requires gitpython>=1.0.1, pyyaml>=3.12, six>=1.10.0, stevedore>=1.20.0
  pytest==4.0.1             requires atomicwrites>=1.0, attrs>=17.4.0, colorama; sys_platform == "win32", more-itertools>=4.0.0, pluggy>=0.7, py>=1.5.0, setuptools, six>=1.10.0
  mypy==0.641               requires mypy-extensions<0.5.0,>=0.4.0, typed-ast<1.2.0,>=1.1.0
  prospector==1.1.6.2       requires astroid==2.0.4, dodgy>=0.1.9, mccabe>=0.5.0, pep8-naming<=0.4.1,>=0.3.3, pycodestyle<=2.4.0,>=2.0.0, pydocstyle>=2.0.0, pyflakes<2.0.0,>=0.8.1, pylint-celery==0.3, pylint-django==2.0.2, pylint-flask==0.5, pylint-plugin-utils>=0.2.6, pylint==2.1.1, pyyaml, requirements-detector>=0.6, setoptconf>=0.2.0
  black==18.9b0             requires appdirs, attrs>=17.4.0, click>=6.5, toml>=0.9.4
  flake8==3.6.0             requires mccabe<0.7.0,>=0.6.0, pycodestyle<2.5.0,>=2.4.0, pyflakes<2.1.0,>=2.0.0, setuptools>=30

New dependencies found in this round:
  adding ['appdirs', '', '[]']
  adding ['astroid', '==2.0.4', '[]']
  adding ['atomicwrites', '>=1.0', '[]']
  adding ['attrs', '>=17.4.0', '[]']
  adding ['click', '>=6.5', '[]']
  adding ['colorama', '', '[]']
  adding ['dodgy', '>=0.1.9', '[]']
  adding ['gitpython', '>=1.0.1', '[]']
  adding ['mccabe', '<0.7.0,>=0.5.0,>=0.6.0', '[]']
  adding ['more-itertools', '>=4.0.0', '[]']
  adding ['mypy-extensions', '<0.5.0,>=0.4.0', '[]']
  adding ['pep8-naming', '<=0.4.1,>=0.3.3', '[]']
  adding ['pluggy', '>=0.7', '[]']
  adding ['py', '>=1.5.0', '[]']
  adding ['pycodestyle', '<2.5.0,<=2.4.0,>=2.0.0,>=2.4.0', '[]']
  adding ['pydocstyle', '>=2.0.0', '[]']
  adding ['pyflakes', '<2.0.0,<2.1.0,>=0.8.1,>=2.0.0', '[]']
  adding ['pylint', '==2.1.1', '[]']
  adding ['pylint-celery', '==0.3', '[]']
  adding ['pylint-django', '==2.0.2', '[]']
  adding ['pylint-flask', '==0.5', '[]']
  adding ['pylint-plugin-utils', '>=0.2.6', '[]']
  adding ['pyyaml', '>=3.12', '[]']
  adding ['requirements-detector', '>=0.6', '[]']
  adding ['setoptconf', '>=0.2.0', '[]']
  adding ['six', '>=1.10.0', '[]']
  adding ['stevedore', '>=1.20.0', '[]']
  adding ['toml', '>=0.9.4', '[]']
  adding ['typed-ast', '<1.2.0,>=1.1.0', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  appdirs
  astroid==2.0.4
  atomicwrites>=1.0
  attrs>=17.4.0
  bandit
  black
  click>=6.5
  colorama
  dodgy>=0.1.9
  flake8
  gitpython>=1.0.1
  mccabe<0.7.0,>=0.5.0,>=0.6.0
  more-itertools>=4.0.0
  mypy
  mypy-extensions<0.5.0,>=0.4.0
  pep8-naming<=0.4.1,>=0.3.3
  pluggy>=0.7
  prospector
  py>=1.5.0
  pycodestyle<2.5.0,<=2.4.0,>=2.0.0,>=2.4.0
  pydocstyle>=2.0.0
  pyflakes<2.0.0,<2.1.0,>=0.8.1,>=2.0.0
  pylint==2.1.1
  pylint-celery==0.3
  pylint-django==2.0.2
  pylint-flask==0.5
  pylint-plugin-utils>=0.2.6
  pytest
  pyyaml>=3.12
  requirements-detector>=0.6
  setoptconf>=0.2.0
  six>=1.10.0
  stevedore>=1.20.0
  toml>=0.9.4
  typed-ast<1.2.0,>=1.1.0

Finding the best candidates:
  found candidate appdirs==1.4.3 (constraint was <any>)
  found candidate astroid==2.0.4 (constraint was ==2.0.4)
  found candidate atomicwrites==1.2.1 (constraint was >=1.0)
  found candidate attrs==18.2.0 (constraint was >=17.4.0)
  found candidate bandit==1.5.1 (constraint was <any>)
  found candidate black==18.9b0 (constraint was <any>)
  found candidate click==7.0 (constraint was >=6.5)
  found candidate colorama==0.4.1 (constraint was <any>)
  found candidate dodgy==0.1.9 (constraint was >=0.1.9)
  found candidate flake8==3.6.0 (constraint was <any>)
  found candidate gitpython==2.1.11 (constraint was >=1.0.1)
  found candidate mccabe==0.6.1 (constraint was >=0.5.0,>=0.6.0,<0.7.0)
  found candidate more-itertools==4.3.0 (constraint was >=4.0.0)
  found candidate mypy==0.641 (constraint was <any>)
  found candidate mypy-extensions==0.4.1 (constraint was >=0.4.0,<0.5.0)
  found candidate pep8-naming==0.4.1 (constraint was >=0.3.3,<=0.4.1)
  found candidate pluggy==0.8.0 (constraint was >=0.7)
  found candidate prospector==1.1.6.2 (constraint was <any>)
  found candidate py==1.7.0 (constraint was >=1.5.0)
  found candidate pycodestyle==2.4.0 (constraint was >=2.0.0,<=2.4.0,>=2.4.0,<2.5.0)
  found candidate pydocstyle==3.0.0 (constraint was >=2.0.0)
Traceback (most recent call last):
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\patched\piptools\resolver.py", line 198, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\patched\piptools\resolver.py", line 198, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\patched\piptools\resolver.py", line 263, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 175, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches pyflakes<2.0.0,<2.1.0,>=0.8.1,>=2.0.0
Tried: 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.7.3, 0.8, 0.8.1, 0.8.1, 0.9.0, 0.9.0, 0.9.1, 0.9.1, 0.9.2, 0.9.2, 1.0.0, 1.0.0, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.2.1, 1.2.1, 1.2.2, 1.2.2, 1.2.3, 1.2.3, 1.3.0, 1.3.0, 1.4.0, 1.4.0, 1.5.0, 1.5.0, 1.6.0, 1.6.0, 2.0.0, 2.0.0
There are incompatible versions in the resolved dependencies.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/users/266891/scoop/apps/python/current/lib/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "c:/users/266891/scoop/apps/python/current/lib/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "c:/users/266891/scoop/apps/python/current/lib/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "c:/users/266891/scoop/apps/python/current/lib/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\utils.py", line 395, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches pyflakes<2.0.0,<2.1.0,>=0.8.1,>=2.0.0
Tried: 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.7.3, 0.8, 0.8.1, 0.8.1, 0.9.0, 0.9.0, 0.9.1, 0.9.1, 0.9.2, 0.9.2, 1.0.0, 1.0.0, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.2.1, 1.2.1, 1.2.2, 1.2.2, 1.2.3, 1.2.3, 1.3.0, 1.3.0, 1.4.0, 1.4.0, 1.5.0, 1.5.0, 1.6.0, 1.6.0, 2.0.0, 2.0.0
There are incompatible versions in the resolved dependencies.
Using pip: -i https://pypi.org/simple --trusted-host pypi.org
Using pip: -i https://pypi.org/simple --trusted-host pypi.org

                          ROUND 1
Current constraints:
  bandit
  black
  flake8
  mypy
  prospector
  pytest

Finding the best candidates:
  found candidate bandit==1.5.1 (constraint was <any>)
  found candidate black==18.9b0 (constraint was <any>)
  found candidate flake8==3.6.0 (constraint was <any>)
  found candidate mypy==0.641 (constraint was <any>)
  found candidate prospector==1.1.6.2 (constraint was <any>)
  found candidate pytest==4.0.1 (constraint was <any>)

Finding secondary dependencies:
  bandit==1.5.1             requires gitpython>=1.0.1, pyyaml>=3.12, six>=1.10.0, stevedore>=1.20.0
  pytest==4.0.1             requires atomicwrites>=1.0, attrs>=17.4.0, colorama; sys_platform == "win32", more-itertools>=4.0.0, pluggy>=0.7, py>=1.5.0, setuptools, six>=1.10.0
  mypy==0.641               requires mypy-extensions<0.5.0,>=0.4.0, typed-ast<1.2.0,>=1.1.0
  prospector==1.1.6.2       requires astroid==2.0.4, dodgy>=0.1.9, mccabe>=0.5.0, pep8-naming<=0.4.1,>=0.3.3, pycodestyle<=2.4.0,>=2.0.0, pydocstyle>=2.0.0, pyflakes<2.0.0,>=0.8.1, pylint-celery==0.3, pylint-django==2.0.2, pylint-flask==0.5, pylint-plugin-utils>=0.2.6, pylint==2.1.1, pyyaml, requirements-detector>=0.6, setoptconf>=0.2.0
  black==18.9b0             requires appdirs, attrs>=17.4.0, click>=6.5, toml>=0.9.4
  flake8==3.6.0             requires mccabe<0.7.0,>=0.6.0, pycodestyle<2.5.0,>=2.4.0, pyflakes<2.1.0,>=2.0.0, setuptools>=30

New dependencies found in this round:
  adding ['appdirs', '', '[]']
  adding ['astroid', '==2.0.4', '[]']
  adding ['atomicwrites', '>=1.0', '[]']
  adding ['attrs', '>=17.4.0', '[]']
  adding ['click', '>=6.5', '[]']
  adding ['colorama', '', '[]']
  adding ['dodgy', '>=0.1.9', '[]']
  adding ['gitpython', '>=1.0.1', '[]']
  adding ['mccabe', '<0.7.0,>=0.5.0,>=0.6.0', '[]']
  adding ['more-itertools', '>=4.0.0', '[]']
  adding ['mypy-extensions', '<0.5.0,>=0.4.0', '[]']
  adding ['pep8-naming', '<=0.4.1,>=0.3.3', '[]']
  adding ['pluggy', '>=0.7', '[]']
  adding ['py', '>=1.5.0', '[]']
  adding ['pycodestyle', '<2.5.0,<=2.4.0,>=2.0.0,>=2.4.0', '[]']
  adding ['pydocstyle', '>=2.0.0', '[]']
  adding ['pyflakes', '<2.0.0,<2.1.0,>=0.8.1,>=2.0.0', '[]']
  adding ['pylint', '==2.1.1', '[]']
  adding ['pylint-celery', '==0.3', '[]']
  adding ['pylint-django', '==2.0.2', '[]']
  adding ['pylint-flask', '==0.5', '[]']
  adding ['pylint-plugin-utils', '>=0.2.6', '[]']
  adding ['pyyaml', '>=3.12', '[]']
  adding ['requirements-detector', '>=0.6', '[]']
  adding ['setoptconf', '>=0.2.0', '[]']
  adding ['six', '>=1.10.0', '[]']
  adding ['stevedore', '>=1.20.0', '[]']
  adding ['toml', '>=0.9.4', '[]']
  adding ['typed-ast', '<1.2.0,>=1.1.0', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  appdirs
  astroid==2.0.4
  atomicwrites>=1.0
  attrs>=17.4.0
  bandit
  black
  click>=6.5
  colorama
  dodgy>=0.1.9
  flake8
  gitpython>=1.0.1
  mccabe<0.7.0,>=0.5.0,>=0.6.0
  more-itertools>=4.0.0
  mypy
  mypy-extensions<0.5.0,>=0.4.0
  pep8-naming<=0.4.1,>=0.3.3
  pluggy>=0.7
  prospector
  py>=1.5.0
  pycodestyle<2.5.0,<=2.4.0,>=2.0.0,>=2.4.0
  pydocstyle>=2.0.0
  pyflakes<2.0.0,<2.1.0,>=0.8.1,>=2.0.0
  pylint==2.1.1
  pylint-celery==0.3
  pylint-django==2.0.2
  pylint-flask==0.5
  pylint-plugin-utils>=0.2.6
  pytest
  pyyaml>=3.12
  requirements-detector>=0.6
  setoptconf>=0.2.0
  six>=1.10.0
  stevedore>=1.20.0
  toml>=0.9.4
  typed-ast<1.2.0,>=1.1.0

Finding the best candidates:
  found candidate appdirs==1.4.3 (constraint was <any>)
  found candidate astroid==2.0.4 (constraint was ==2.0.4)
  found candidate atomicwrites==1.2.1 (constraint was >=1.0)
  found candidate attrs==18.2.0 (constraint was >=17.4.0)
  found candidate bandit==1.5.1 (constraint was <any>)
  found candidate black==18.9b0 (constraint was <any>)
  found candidate click==7.0 (constraint was >=6.5)
  found candidate colorama==0.4.1 (constraint was <any>)
  found candidate dodgy==0.1.9 (constraint was >=0.1.9)
  found candidate flake8==3.6.0 (constraint was <any>)
  found candidate gitpython==2.1.11 (constraint was >=1.0.1)
  found candidate mccabe==0.6.1 (constraint was >=0.5.0,>=0.6.0,<0.7.0)
  found candidate more-itertools==4.3.0 (constraint was >=4.0.0)
  found candidate mypy==0.641 (constraint was <any>)
  found candidate mypy-extensions==0.4.1 (constraint was >=0.4.0,<0.5.0)
  found candidate pep8-naming==0.4.1 (constraint was >=0.3.3,<=0.4.1)
  found candidate pluggy==0.8.0 (constraint was >=0.7)
  found candidate prospector==1.1.6.2 (constraint was <any>)
  found candidate py==1.7.0 (constraint was >=1.5.0)
  found candidate pycodestyle==2.4.0 (constraint was >=2.0.0,<=2.4.0,>=2.4.0,<2.5.0)
  found candidate pydocstyle==3.0.0 (constraint was >=2.0.0)
Traceback (most recent call last):
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\patched\piptools\resolver.py", line 198, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\patched\piptools\resolver.py", line 198, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\patched\piptools\resolver.py", line 263, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 175, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches pyflakes<2.0.0,<2.1.0,>=0.8.1,>=2.0.0
Tried: 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.7.3, 0.8, 0.8.1, 0.8.1, 0.9.0, 0.9.0, 0.9.1, 0.9.1, 0.9.2, 0.9.2, 1.0.0, 1.0.0, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.2.1, 1.2.1, 1.2.2, 1.2.2, 1.2.3, 1.2.3, 1.3.0, 1.3.0, 1.4.0, 1.4.0, 1.5.0, 1.5.0, 1.6.0, 1.6.0, 2.0.0, 2.0.0
There are incompatible versions in the resolved dependencies.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/users/266891/scoop/apps/python/current/lib/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "c:/users/266891/scoop/apps/python/current/lib/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "c:/users/266891/scoop/apps/python/current/lib/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "c:/users/266891/scoop/apps/python/current/lib/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "c:\users\266891\scoop\apps\python\current\lib\site-packages\pipenv\utils.py", line 395, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches pyflakes<2.0.0,<2.1.0,>=0.8.1,>=2.0.0
Tried: 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.7.3, 0.8, 0.8.1, 0.8.1, 0.9.0, 0.9.0, 0.9.1, 0.9.1, 0.9.2, 0.9.2, 1.0.0, 1.0.0, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.2.1, 1.2.1, 1.2.2, 1.2.2, 1.2.3, 1.2.3, 1.3.0, 1.3.0, 1.4.0, 1.4.0, 1.5.0, 1.5.0, 1.6.0, 1.6.0, 2.0.0, 2.0.0
There are incompatible versions in the resolved dependencies.
```

### Steps to replicate

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'c:\\users\\266891\\scoop\\apps\\python\\current\\lib\\site-packages\\pipenv'`

Python location: `'c:\\users\\266891\\scoop\\apps\\python\\current\\python.exe'`

Python installations found:

  - `3.7.1`: `C:\Users\266891\scoop\apps\python\3.7.1\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.1',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17134',
 'python_full_version': '3.7.1',
 'python_version': '3.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `ANSIBLE_VAULT_PASSWORD`
  - `ANSICON`
  - `ANSICON_DEF`
  - `APPDATA`
  - `CARGO_HOME`
  - `CHOCOLATEYINSTALL`
  - `CHOCOLATEYLASTPATHUPDATE`
  - `CMDER_ROOT`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `CONEMUANSI`
  - `CONEMUANSILOG`
  - `CONEMUARGS`
  - `CONEMUARGS2`
  - `CONEMUBACKHWND`
  - `CONEMUBASEDIR`
  - `CONEMUBASEDIRSHORT`
  - `CONEMUBUILD`
  - `CONEMUCFGDIR`
  - `CONEMUCONFIG`
  - `CONEMUDIR`
  - `CONEMUDRAWHWND`
  - `CONEMUDRIVE`
  - `CONEMUHOOKS`
  - `CONEMUHWND`
  - `CONEMUPALETTE`
  - `CONEMUPID`
  - `CONEMUSERVERPID`
  - `CONEMUTASK`
  - `CONEMUWORKDIR`
  - `CONEMUWORKDRIVE`
  - `DEFLOGDIR`
  - `DRIVERDATA`
  - `GITHUB_TOKEN`
  - `GIT_INSTALL_ROOT`
  - `GIT_SSH`
  - `GODEVHOME`
  - `GOROOT`
  - `GO_PACKAGE_STORE_GITHUB_TOKEN`
  - `HOME`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `HOMESHARE`
  - `HTTP_PROXY`
  - `JAVA_HOME`
  - `KOTLIN_HOME`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `MINISHIFT_HOME`
  - `NO_PROXY`
  - `NUMBER_OF_PROCESSORS`
  - `NVM_HOME`
  - `NVM_SYMLINK`
  - `ONEDRIVE`
  - `OPENSSL_CONF`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PSEXECUTIONPOLICYPREFERENCE`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `RUSTUP_HOME`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `UATDATA`
  - `USERDNSDOMAIN`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `WINDIR`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv?specific environment variables:

Debug?specific environment variables:

  - `PATH`: `C:\tools\cmder\bin;C:\tools\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\IBM\Client Access\Emulator;C:\Program Files (x86)\IBM\Client Access\Shared;C:\Program Files (x86)\IBM\Client Access\;C:\TDM-GCC-64\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\ProgramData\chocolatey\bin;C:\Users\266891\scoop\apps\gpg4win\3.1.2\Gpg4win\..\GnuPG\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files\PowerShell\6\;C:\Users\266891\scoop\apps\gpg4win\3.1.5\Gpg4win\..\GnuPG\bin;C:\Users\266891\scoop\apps\nodejs\current\bin;C:\Users\266891\scoop\apps\nodejs\current;C:\Users\266891\scoop\apps\gpg4win\current\Gpg4win\bin;C:\Users\266891\scoop\apps\gpg4win\current\GnuPG\bin;C:\Users\266891\go\bin;C:\Users\266891\scoop\apps\maven\current\bin;C:\Users\266891\scoop\apps\openssl\current;C:\Users\266891\scoop\apps\ojdkbuild8\current\bin;C:\Users\266891\scoop\apps\oraclejdk8\current\bin;C:\Users\266891\scoop\apps\python\current\scripts;C:\Users\266891\AppData\Local\Programs\Python\Launcher\;C:\tools\cmder\bin;C:\tools\cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\tools\cmder\vendor\conemu-maximus5;C:\tools\cmder\vendor\conemu-maximus5\ConEmu;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Users\266891\scoop\apps\oraclejdk11\current\bin;C:\Users\266891\scoop\apps\nvm\current\nodejs\nodejs;C:\Users\266891\scoop\apps\openssl\current\bin;C:\Users\266891\scoop\apps\oraclejdk-lts\current\bin;C:\Users\266891\scoop\apps\oraclejdk\current\bin;C:\Users\266891\bin\;C:\Users\266891\scoop\shims;C:\Users\266891\AppData\Local\Microsoft\WindowsApps;C:\Users\266891\AppData\Local\GitHubDesktop\bin;C:\Users\266891\AppData\Local\Microsoft\WindowsApps;C:\tools\cmder;C:\tools\cmder`

---------------------------

Contents of `Pipfile` ('C:\\Users\\266891\\dev\\python\\snowplay\\Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = false

[dev-packages]
flake8 = "*"
black = "*"
mypy = "*"
prospector = "*"
bandit = "*"
pytest = "*"

[packages]
pysnow = "*"
flake8 = "*"

[requires]
python_version = "3.7"

[pipenv]
allow_prereleases = true

```

</details>

**Comment by klauern** [comment]
Gah, just found it using the `--verbose` option.  I didn't see that `prospector` had a `pyflakes` dependency issue.  That wasn't showing up in `pipenv graph`.
