### ISSUE TITLE
pipenv install -e . builds an extra .egg-info directory, then complains that it exists!

### ISSUE THREAD

**Issue by NotTheEconomist** [pypa/pipenv#3335]
### Issue description

I'm using pipenv to manage my venv for a toy project that has the following structure:

```
D:\projectroot
|   Pipfile
|   README.md
|   setup.py
|
\---src
    +---module
        |   some.py
        |   files.py
        \---__init__.py
```

My setup.py includes lines like:

```python
setuptools.setup(
        # NOTE: many lines elided for brevity
        packages=setuptools.find_packages('src', exclude=['tests*']),
        package_dir={'': 'src'},
        install_requires= [
            "click>=7.0",
        ],
        entry_points = '''
            [console_scripts]
            app=module.files:entrypoint
        ''',
        python_requires=">=3.6"
    )
```

and I can install using

```
pipenv run pip install -e .
```

which creates a .egg-info folder in `D:/projectroot/src` as sibling to `module`, allowing me to continue with `pipenv run app`. This, however, doesn't help my Pipfile at all, which makes it rather pointless.

If I instead use

```
pipenv install -e .
```

Then `pipenv` creates the egg in both `D:/projectroot/` and `D:/projectroot/src`. When the lock file attempts to resolve it finds the former first and throws an AssertionError:

```
D:\projectroot>pipenv install -e .
Installing -e .…
Adding module to Pipfile's [packages]…
Installation Succeeded
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Success!
Updated Pipfile.lock (bef76c)!
Installing dependencies from Pipfile.lock (bef76c)…
An error occurred while installing -e .! Will try again.
  ================================ 2/2 - 00:00:01
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "c:\users\adsmith\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\core.py", line 1987, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "c:\users\adsmith\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\core.py", line 1232, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "c:\users\adsmith\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\core.py", line 841, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "c:\users\adsmith\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\core.py", line 748, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "c:\users\adsmith\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\core.py", line 676, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Obtaining file:///D:/projectroot', 'Installing collected packages: module', '  Found existing installation: module 1.0.0']
[pipenv.exceptions.InstallError]: ['Exception:', 'Traceback (most recent call last):', '  File "c:\\users\\adsmith\\.virtualenvs\\2018-2-yckuetpo\\lib\\site-packages\\pip\\_internal\\cli\\base_command.py", line 143, in main', '    status = self.run(options, args)', '  File "c:\\users\\adsmith\\.virtualenvs\\2018-2-yckuetpo\\lib\\site-packages\\pip\\_internal\\commands\\install.py", line 366, in run', '    use_user_site=options.use_user_site,', '  File "c:\\users\\adsmith\\.virtualenvs\\2018-2-yckuetpo\\lib\\site-packages\\pip\\_internal\\req\\__init__.py", line 42, in install_given_reqs', '    auto_confirm=True', '  File "c:\\users\\adsmith\\.virtualenvs\\2018-2-yckuetpo\\lib\\site-packages\\pip\\_internal\\req\\req_install.py", line 682, in uninstall', '    uninstalled_pathset = UninstallPathSet.from_dist(dist)', '  File "c:\\users\\adsmith\\.virtualenvs\\2018-2-yckuetpo\\lib\\site-packages\\pip\\_internal\\req\\req_uninstall.py", line 369, in from_dist', "    '(at %s)' % (link_pointer, dist.project_name, dist.location)", 'AssertionError: Egg-link d:\\projectroot\\src does not match installed location of module (at d:\\projectroot)']
```

As a workaround, I can then delete the `D:/projectroot/module.egg-info` and do `pipenv sync` completes as expected.

### Expected result

I expect `pipenv install -e .` to have the same behavior as `pip install -e .`, but additionally populate my Pipfile and Pipfile.lock

### Actual result

It produces two eggs, confusing itself.

### Steps to replicate

Create a project structure where `./setup.py` is not sibling to the package it installs, then `pipenv install -e .`

-------------------------------------------------------------------------------

Below is the result of `pipenv --support`. I've not sanitized the below for brevity, so the paths and names below may not match the above (below you're seeing the real project and folder names, not just `D:\projectroot`)

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.14'`

Pipenv location: `'c:\\users\\adsmith\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\pipenv'`

Python location: `'c:\\users\\adsmith\\appdata\\local\\programs\\python\\python36-32\\python.exe'`

Python installations found:

  - `3.6.4`: `C:\Users\adsmith\AppData\Local\Programs\Python\Python36-32\python.exe`
  - `2.7`: `C:\Python27\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.4',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17134',
 'python_full_version': '3.6.4',
 'python_version': '3.6',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `DRIVERDATA`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `GOPATH`
  - `GOROOT`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_ARCHITEW6432`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `PYTHONPATH`
  - `SESSIONNAME`
  - `STACK_ROOT`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VBOX_MSI_INSTALL_PATH`
  - `WINDIR`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenvûspecific environment variables:

Debugûspecific environment variables:

  - `PATH`: `C:\users\adsmith\local\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Haskell\bin;C:\Program Files\Haskell Platform\8.2.1\lib\extralibs\bin;C:\Program Files\Haskell Platform\8.2.1\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files (x86)\gnupg\bin;C:\Program Files\Haskell Platform\8.2.1\mingw\bin;;C:\WINDOWS\System32\OpenSSH\;C:\Go\bin;C:\Program Files\PuTTY\;C:\Program Files\dotnet\;C:\User\adsmith\local\bin;C:\Users\adsmith\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\adsmith\AppData\Local\Programs\Python\Python36-32\;C:\Users\adsmith\AppData\Roaming\cabal\bin;C:\Users\adsmith\AppData\Roaming\local\bin;C:\Users\adsmith\AppData\Local\Microsoft\WindowsApps;C:\Exercism;C:\Users\adsmith\workspace\go\bin;C:\Users\adsmith\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Git\mingw64\bin;`

---------------------------

Contents of `Pipfile` ('D:\\workspace\\adventofcode\\2018-2\\Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
adventofcode18 = {editable = true,path = "."}

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('D:\\workspace\\adventofcode\\2018-2\\Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "1d6aa49bcb64decf977a1ebabce442ebd801af83ec0c1c0bce631da611bef76c"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "adventofcode18": {
            "editable": true,
            "path": "."
        },
        "click": {
            "hashes": [
                "sha256:2335065e6395b9e67ca716de5f7526736bfa6ceead690adf616d925bdc622b13",
                "sha256:5b94b49521f6456670fdb30cd82a4eca9412788a93fa6dd6df72c94d5a8ff2d7"
            ],
            "version": "==7.0"
        }
    },
    "develop": {}
}

```
</details>

**Comment by NotTheEconomist** [comment]
> 
> 
> please try 2018.11.26 version

Well that was easy. I didn't bother checking that I had latest since I knew I wasn't more than a month out of date (just started playing with pipenv recently).

2018.11.26 behaves as I expect. Closing ticket as already resolved.

Thanks!
