### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by Formartha** [pypa/pipenv#3394]
Hello,

Updated today to a new pipenv version 1.7.2018 and tried to reinstall my old Pipefile content.
however, I got an exception - anything I need to consider here?

Virtualenv location: /root/PycharmProjects/orion/.venv                                                                                                              Installing dependencies from Pipfile.lock (684af3)...
Traceback (most recent call last):????? 0/99 ? 00:00:00
  File "/usr/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pipenv/cli.py", line 1049, in sync
    pypi_mirror=pypi_mirror,
  File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 2518, in do_sync
    system=system,
  File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 1322, in do_init
    pypi_mirror=pypi_mirror,
  File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 807, in do_install_dependencies
    pypi_mirror=pypi_mirror,
  File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 1375, in pip_install
    package_name.split('--hash')[0].split('--trusted-host')[0]
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable
/usr/lib/python2.7/site-packages/pipenv/_compat.py:113: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-BtaiAi-requirements'>
  warnings.warn(warn_message, ResourceWarning)

**Comment by frostming** [comment]
This was an old issue and already fixed in latest version. Please upgrade your pipenv

**Comment by leileigong** [comment]
Using python3 pipenv , i got this error too.
but python2 pipenv works fine.
==============here is error log========
$ pipenv install wxpython
Installing wxpython...
Requirement already satisfied: wxpython in c:\users\gll\.virtualenvs\wxpython-demo-4.0.1-lgmszjyh\lib\site-packages (4.0.4)
Requirement already satisfied: six in c:\users\gll\.virtualenvs\wxpython-demo-4.0.1-lgmszjyh\lib\site-packages (from wxpython) (1.12.0)
Requirement already satisfied: Pillow in c:\users\gll\.virtualenvs\wxpython-demo-4.0.1-lgmszjyh\lib\site-packages (from wxpython) (5.4.1)

Adding wxpython to Pipfile's [packages]...
Pipfile.lock (ca72e7) out of date, updating to (c972a6)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
v\utils.py", line 402, in resolve_deps
    req_dir=req_dir
  File "c:\python36\lib\site-packages\pipenv\utils.py", line 250, in actually_resolve_deps
    req = Requirement.from_line(dep)
  File "c:\python36\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable

==========here is correct log==============
$ pipenv2 install wxpython
Installing wxpython...
Adding wxpython to Pipfile's [packages]...
Installation Succeeded
Pipfile.lock (c972a6) out of date, updating to (ca72e7)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Success!
Updated Pipfile.lock (c972a6)!
Installing dependencies from Pipfile.lock (c972a6)...
  ================================ 3/3 - 00:00:20
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

**Comment by leileigong** [comment]
> atest version. Please upgrade your pipenv

Hi, this problem still exist in pipenv-py3

**Comment by frostming** [comment]
@leileigong Please wait for the next release
