### ISSUE TITLE
corrupted venv?

### ISSUE THREAD

**Issue by marafa** [pypa/pipenv#3397]
i got 2 pipenv one just works and the other one breaks with the below message. i compared the Pipfiles and they both are using the same version of python.

not sure why this specific environment is corrupt. i have attempted several time to `rm` then `install` again with no luck

thanks in advance

```
 pipenv update
Running $ pipenv lock then $ pipenv sync.
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✘ Locking Failed! 
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/usr/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/usr/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/usr/lib/python3.7/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpcqmk8k7rbuild/logging/
File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/usr/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/usr/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/usr/lib/python3.7/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 260, in 
_resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpcqmk8k7rbuild/logging/
```

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.7.1`: `/home/marafa/.local/share/virtualenvs/site_list-q5BAfYg_/bin/python3.7m`
  - `3.7.1`: `/usr/bin/python3.7m`
  - `3.7.1`: `/usr/bin/python3.7`
  - `2.7.15`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.1',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.19.8-300.fc29.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Mon Dec 10 15:23:11 UTC 2018',
 'python_full_version': '3.7.1',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `GS_LIB`
  - `QTINC`
  - `KDE_FULL_SESSION`
  - `LS_COLORS`
  - `__GL_YIELD`
  - `XDG_MENU_PREFIX`
  - `MODULES_RUN_QUARANTINE`
  - `LANG`
  - `HISTCONTROL`
  - `DISPLAY`
  - `PROFILEHOME`
  - `GUESTFISH_RESTORE`
  - `HISTTIMEFORMAT`
  - `HOSTNAME`
  - `OLDPWD`
  - `QTDIR`
  - `SHELL_SESSION_ID`
  - `COLORTERM`
  - `DM_CONTROL`
  - `GUESTFISH_INIT`
  - `IMSETTINGS_INTEGRATE_DESKTOP`
  - `KDEDIRS`
  - `XDG_VTNR`
  - `PAM_KWALLET5_LOGIN`
  - `SSH_AUTH_SOCK`
  - `VIRTUAL_ENV`
  - `S_COLORS`
  - `LESS_TERMCAP_so`
  - `LESS_TERMCAP_se`
  - `XDG_SESSION_ID`
  - `MODULES_CMD`
  - `USER`
  - `ENV`
  - `GUESTFISH_PS1`
  - `DESKTOP_SESSION`
  - `KONSOLE_VERSION`
  - `PIP_PYTHON_PATH`
  - `GTK2_RC_FILES`
  - `IMSETTINGS_MODULE`
  - `PWD`
  - `SSH_ASKPASS`
  - `HOME`
  - `SSH_AGENT_PID`
  - `BASH_ENV`
  - `XDG_DATA_DIRS`
  - `PIPENV_ACTIVE`
  - `KONSOLE_DBUS_SESSION`
  - `GDK_CORE_DEVICE_EVENTS`
  - `LESS_TERMCAP_mb`
  - `LESS_TERMCAP_md`
  - `LESS_TERMCAP_me`
  - `KONSOLE_DBUS_WINDOW`
  - `LOADEDMODULES`
  - `MAIL`
  - `QTLIB`
  - `WINDOWPATH`
  - `SHELL`
  - `TERM`
  - `KONSOLE_DBUS_SERVICE`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `XCURSOR_THEME`
  - `XDG_CURRENT_DESKTOP`
  - `KONSOLE_PROFILE_NAME`
  - `PYTHONDONTWRITEBYTECODE`
  - `COLORFGBG`
  - `SHLVL`
  - `XDG_SEAT`
  - `LANGUAGE`
  - `DRUSH_INI`
  - `WINDOWID`
  - `MODULEPATH`
  - `LOGNAME`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `MODULEPATH_modshare`
  - `XDM_MANAGED`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `LESS_TERMCAP_us`
  - `XDG_CONFIG_DIRS`
  - `PATH`
  - `KDE_SESSION_UID`
  - `GUESTFISH_OUTPUT`
  - `KDE_SESSION_VERSION`
  - `MODULESHOME`
  - `HISTSIZE`
  - `SESSION_MANAGER`
  - `LESSOPEN`
  - `GTK_IM_MODULE`
  - `BASH_FUNC_module%%`
  - `BASH_FUNC__module_raw%%`
  - `BASH_FUNC_switchml%%`
  - `BASH_FUNC_scl%%`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/marafa/.local/share/virtualenvs/site_list-q5BAfYg_/bin:/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/local/sbin:/usr/sbin:/home/marafa/.composer/vendor/bin:/home/marafa/dev/vendor/:/home/marafa/dev/vendor/composer/:/home/marafa/dev/vendor/bin:/home/marafa/.local/bin:/home/marafa/bin:/home/marafa/dev/vendor/:/home/marafa/dev/vendor/composer/:/home/marafa/dev/vendor/bin:/home/marafa/dev/vendor/:/home/marafa/dev/vendor/composer/:/home/marafa/dev/vendor/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `$PWD`
  - `VIRTUAL_ENV`: `/home/marafa/.local/share/virtualenvs/site_list-q5BAfYg_`

---------------------------

Contents of `Pipfile` ('$PWD/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"bs4" = "*"
requests = "*"
pymongo = "*"
configparser = "*"
logging = "*"
beautifulsoup4 = "*"
certifi = "*"
chardet = "*"
idna = "*"
datetime = "*"
urllib3 = "*"
#urlparse = "*"

[dev-packages]

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('$PWD/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "f5cf828452ef1a96e02ab03f7b9a0a684f59e543be1a790a7bba4c9bde5aabbc"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "beautifulsoup4": {
            "hashes": [
                "sha256:194ec62a25438adcb3fdb06378b26559eda1ea8a747367d34c33cef9c7f48d57",
                "sha256:90f8e61121d6ae58362ce3bed8cd997efb00c914eae0ff3d363c32f9a9822d10",
                "sha256:f0abd31228055d698bb392a826528ea08ebb9959e6bea17c606fd9c9009db938"
            ],
            "version": "==4.6.3"
        },
        "bs4": {
            "hashes": [
                "sha256:36ecea1fd7cc5c0c6e4a1ff075df26d50da647b75376626cc186e2212886dd3a"
            ],
            "index": "pypi",
            "version": "==0.0.1"
        },
        "certifi": {
            "hashes": [
                "sha256:47f9c83ef4c0c621eaef743f133f09fa8a74a9b75f037e8624f83bd1b6626cb7",
                "sha256:993f830721089fef441cdfeb4b2c8c9df86f0c63239f06bd025a76a7daddb033"
            ],
            "version": "==2018.11.29"
        },
        "chardet": {
            "hashes": [
                "sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae",
                "sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691"
            ],
            "version": "==3.0.4"
        },
        "configparser": {
            "hashes": [
                "sha256:5308b47021bc2340965c371f0f058cc6971a04502638d4244225c49d80db273a"
            ],
            "index": "pypi",
            "version": "==3.5.0"
        },
        "idna": {
            "hashes": [
                "sha256:156a6814fb5ac1fc6850fb002e0852d56c0c8d2531923a51032d1b70760e186e",
                "sha256:684a38a6f903c1d71d6d5fac066b58d7768af4de2b832e426ec79c30daa94a16"
            ],
            "version": "==2.7"
        },
        "pymongo": {
            "hashes": [
                "sha256:025f94fc1e1364f00e50badc88c47f98af20012f23317234e51a11333ef986e6",
                "sha256:02aa7fb282606331aefbc0586e2cf540e9dbe5e343493295e7f390936ad2738e",
                "sha256:057210e831573e932702cf332012ed39da78edf0f02d24a3f0b213264a87a397",
                "sha256:0d946b79c56187fe139276d4c8ed612a27a616966c8b9779d6b79e2053587c8b",
                "sha256:104790893b928d310aae8a955e0bdbaa442fb0ac0a33d1bbb0741c791a407778",
                "sha256:15527ef218d95a8717486106553b0d54ff2641e795b65668754e17ab9ca6e381",
                "sha256:1826527a0b032f6e20e7ac7f72d7c26dd476a5e5aa82c04aa1c7088a59fded7d",
                "sha256:22e3aa4ce1c3eebc7f70f9ca7fd4ce1ea33e8bdb7b61996806cd312f08f84a3a",
                "sha256:244e1101e9a48615b9a16cbd194f73c115fdfefc96894803158608115f703b26",
                "sha256:24b8c04fdb633a84829d03909752c385faef249c06114cc8d8e1700b95aae5c8",
                "sha256:2c276696350785d3104412cbe3ac70ab1e3a10c408e7b20599ee41403a3ed630",
                "sha256:2d8474dc833b1182b651b184ace997a7bd83de0f51244de988d3c30e49f07de3",
                "sha256:3119b57fe1d964781e91a53e81532c85ed1701baaddec592e22f6b77a9fdf3df",
                "sha256:3bee8e7e0709b0fcdaa498a3e513bde9ffc7cd09dbceb11e425bd91c89dbd5b6",
                "sha256:436c071e01a464753d30dbfc8768dd93aecf2a8e378e5314d130b95e77b4d612",
                "sha256:46635e3f19ad04d5a7d7cf23d232388ddbfccf46d9a3b7436b6abadda4e84813",
                "sha256:4772e0b679717e7ac4608d996f57b6f380748a919b457cb05bb941467b888b22",
                "sha256:4e2cd80e16f481a62c3175b607373200e714ed29025f21559ebf7524f295689f",
                "sha256:52732960efa0e003ca1c092dc0a3c65276e897681287a788a01ca78dda3b41f0",
                "sha256:55a7de51ec7d1731b2431886d0349146645f2816e5b8eb982d7c49f89472c9f3",
                "sha256:5f8ed5934197a2d4b2087646e98de3e099a237099dcf498b9e38dd3465f74ef4",
                "sha256:64b064124fcbc8eb04a155117dc4d9a336e3cda3f069958fbc44fe70c3c3d1e9",
                "sha256:65958b8e4319f992e85dad59d8081888b97fcdbde5f0d14bc28f2848b92d3ef1",
                "sha256:7683428862e20c6a790c19e64f8ccf487f613fbc83d47e3d532df9c81668d451",
                "sha256:78566d5570c75a127c2491e343dc006798a384f06be588fe9b0cbe5595711559",
                "sha256:7d1cb00c093dbf1d0b16ccf123e79dee3b82608e4a2a88947695f0460eef13ff",
                "sha256:8c74e2a9b594f7962c62cef7680a4cb92a96b4e6e3c2f970790da67cc0213a7e",
                "sha256:8e60aa7699170f55f4b0f56ee6f8415229777ac7e4b4b1aa41fc61eec08c1f1d",
                "sha256:9447b561529576d89d3bf973e5241a88cf76e45bd101963f5236888713dea774",
                "sha256:970055bfeb0be373f2f5299a3db8432444bad3bc2f198753ee6c2a3a781e0959",
                "sha256:a6344b8542e584e140dc3c651d68bde51270e79490aa9320f9e708f9b2c39bd5",
                "sha256:ce309ca470d747b02ba6069d286a17b7df8e9c94d10d727d9cf3a64e51d85184",
                "sha256:cfbd86ed4c2b2ac71bbdbcea6669bf295def7152e3722ddd9dda94ac7981f33d",
                "sha256:d7929c513732dff093481f4a0954ed5ff16816365842136b17caa0b4992e49d3"
            ],
            "index": "pypi",
            "version": "==3.7.2"
        },
        "requests": {
            "hashes": [
                "sha256:65b3a120e4329e33c9889db89c80976c5272f56ea92d3e74da8a463992e3ff54",
                "sha256:ea881206e59f41dbd0bd445437d792e43906703fff75ca8ff43ccdb11f33f263"
            ],
            "index": "pypi",
            "version": "==2.20.1"
        },
        "urllib3": {
            "hashes": [
                "sha256:61bf29cada3fc2fbefad4fdf059ea4bd1b4a86d2b6d15e1c7c0b582b9752fe39",
                "sha256:de9529817c93f27c8ccbfead6985011db27bd0ddfcdb2d86f3f663385c6a9c22"
            ],
            "version": "==1.24.1"
        }
    },
    "develop": {}
}

```
</details>

**Comment by frostming** [comment]
Try removing the `logging` dependency since it has been absorbed into standard library.

**Comment by marafa** [comment]
ok .. that seemed to clear some things up 
however i get similar errors when running `pipenv install --pre sys` or `os` even

**Comment by frostming** [comment]
@marafa Why are you keep installing a standard library?

**Comment by marafa** [comment]
:D i am a beginner

**Comment by techalchemy** [comment]
Most things that come built in can’t be installed, you can check pypi.org to find out
