### ISSUE TITLE
pipenv install throws validation error

### ISSUE THREAD

**Issue by jsandovalc** [pypa/pipenv#3453]
### Issue description

`pipenv install` raises 

```plette.models.base.ValidationError: {'hash': {'sha256': '56e0104fb0960bcf1a6535e12f6db6aa4cb19ab69794a5e5e75671f7cdc33ea9'}, 'requires': {}, 'sources': [{'url': 'https://pypi.python.org/simple', 'verify_ssl': True, 'name': 'pypi.python.org'}]}```

### Expected result

Expected to install depenndencies successfully. I got a new computer with latest pipenv version. Install was working ok.

### Actual result

Full output:

```Traceback (most recent call last):
  File "/home/ark/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/core.py", line 1874, in do_install
    keep_outdated=keep_outdated
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/core.py", line 1253, in do_init
    pypi_mirror=pypi_mirror,
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/core.py", line 797, in do_install_dependencies
    lockfile = project.get_or_create_lockfile()
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/project.py", line 778, in get_or_create_lockfile
    path=self.lockfile_location, data=lockfile_dict, meta_from_project=False
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/lockfile.py", line 209, in from_data
    lockfile = plette.lockfiles.Lockfile(data)
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/vendor/plette/models/base.py", line 37, in __init__
    self.validate(data)
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/vendor/plette/lockfiles.py", line 80, in validate
    klass.validate(data[key])
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/vendor/plette/models/sections.py", line 68, in validate
    super(Meta, cls).validate(data)
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/vendor/plette/models/base.py", line 67, in validate
    return validate(cls, data)
  File "/home/ark/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/pipfile.py", line 59, in validate
    raise plette.models.base.ValidationError(data, v)
plette.models.base.ValidationError: {'hash': {'sha256': '56e0104fb0960bcf1a6535e12f6db6aa4cb19ab69794a5e5e75671f7cdc33ea9'}, 'requires': {}, 'sources': [{'url': 'https://pypi.python.org/simple', 'verify_ssl': True, 'name': 'pypi.python.org'}]}
```

### Steps to replicate

Just `pipenv install`

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/ark/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/bin/python3.6'`

Python installations found:

  - `3.6.8`: `/usr/local/bin/python3.6m`
  - `3.6.8`: `/usr/local/bin/python3`
  - `3.5.3`: `/usr/bin/python3`
  - `3.5.3`: `/usr/bin/python3.5m`
  - `2.7.13`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.8',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.19.0-0.bpo.1-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Debian 4.19.12-1~bpo9+1 (2018-12-30)',
 'python_full_version': '3.6.8',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LS_COLORS`
  - `LANG`
  - `GDM_LANG`
  - `MANAGERPID`
  - `DISPLAY`
  - `INVOCATION_ID`
  - `COLORTERM`
  - `USERNAME`
  - `USER`
  - `DESKTOP_SESSION`
  - `PWD`
  - `HOME`
  - `JOURNAL_STREAM`
  - `QT_ACCESSIBILITY`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `XDG_SESSION_DESKTOP`
  - `DBUS_STARTER_ADDRESS`
  - `GTK_MODULES`
  - `WINDOWPATH`
  - `TERM`
  - `SHELL`
  - `VTE_VERSION`
  - `DBUS_STARTER_BUS_TYPE`
  - `GPG_AGENT_INFO`
  - `SHLVL`
  - `LANGUAGE`
  - `WINDOWID`
  - `GDMSESSION`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `PATH`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/ark/.local/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `es_CO.UTF-8`
  - `PWD`: `/home/ark/workspace/facture2`

---------------------------

Contents of `Pipfile` ('/home/ark/workspace/facture2/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true

[dev-packages]
flake8 = "*"
ipdb = "*"
django-extensions = "*"
pygraphviz = "*"
coverage = "*"
django = "==1.11.10"
pytest-mock = "*"

[packages]
django-environ = "*"
dj-database-url = "*"
djangorestframework = "*"
gunicorn = "*"
psycopg2 = "*"
django-allauth = "*"
djangorestframework-jwt = "*"
django-rest-auth = "*"
whitenoise = "*"
django-phonenumber-field = "*"
django-fsm = "*"
django-localflavor = "*"
django-filter = "*"
django-cors-headers = "*"
py-moneyed = "*"
boto3 = "*"
django-extensions = "*"
django = "==1.11.10"
django-nomad-notifier = "*"
raven = "*"
celery = "*"
django-celery-email = "*"
openpyxl = "*"
django-storages = "*"
pytest = "==3.8.2"
pytest-django = "*"
pytest-xdist = "*"
django-s3-folder-storage = "*"
phonenumbers = "*"
model-mommy = "*"
sendgrid = "*"

[dev-packages.hypothesis]
extras = [ "django",]

[packages.cities-light]
git = "https://github.com/yourlabs/django-cities-light.git"

[packages.django-money-fork]
git = "https://github.com/mikeiwi/django-money-fork.git"

```

Contents of `Pipfile.lock` ('/home/ark/workspace/facture2/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "56e0104fb0960bcf1a6535e12f6db6aa4cb19ab69794a5e5e75671f7cdc33ea9"
        },
        "requires": {},
        "sources": [
            {
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "amqp": {
            "hash": "sha256:eed41946890cd43e8dee44a316b85cf6fee5a1a34bb4a562b660a358eb529e1b",
            "version": "==2.3.2"
        },
        "apipkg": {
            "hash": "sha256:58587dd4dc3daefad0487f6d9ae32b4542b185e1c36db6993290e7c41ca2b47c",
            "version": "==1.5"
        },
        "atomicwrites": {
            "hash": "sha256:0312ad34fcad8fac3704d441f7b317e50af620823353ec657a53e981f92920c0",
            "version": "==1.2.1"
        },
        "attrs": {
            "hash": "sha256:ca4be454458f9dec299268d472aaa5a11f67a4ff70093396e1ceae9c76cf4bbb",
            "version": "==18.2.0"
        },
        "babel": {
            "hash": "sha256:6778d85147d5d85345c14a26aada5e478ab04e39b078b0745ee6870c2b5cf669",
            "version": "==2.6.0"
        },
        "billiard": {
            "hash": "sha256:ed65448da5877b5558f19d2f7f11f8355ea76b3e63e1c0a6059f47cfae5f1c84",
            "version": "==3.5.0.4"
        },
        "boto3": {
            "hash": "sha256:b7af22c85610a3e50e8690d0fa61bd05f6d18ea1b40bfae4a9a8d71a294f0d9a",
            "version": "==1.9.32"
        },
        "botocore": {
            "hash": "sha256:d43c1562698e7343924043d3d55ace0d970b2a6a741797493ff64366f823aea3",
            "version": "==1.12.32"
        },
        "celery": {
            "hash": "sha256:ad7a7411772b80a4d6c64f2f7f723200e39fb66cf614a7fdfab76d345acc7b13",
            "version": "==4.2.1"
        },
        "certifi": {
            "hash": "sha256:339dc09518b07e2fa7eda5450740925974815557727d6bd35d319c1524a04a4c",
            "version": "==2018.10.15"
        },
        "chardet": {
            "hash": "sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691",
            "version": "==3.0.4"
        },
        "cities-light": {
            "git": "https://github.com/yourlabs/django-cities-light.git"
        },
        "defusedxml": {
            "hash": "sha256:702a91ade2968a82beb0db1e0766a6a273f33d4616a6ce8cde475d8e09853b20",
            "version": "==0.5.0"
        },
        "dj-database-url": {
            "hash": "sha256:851785365761ebe4994a921b433062309eb882fedd318e1b0fcecc607ed02da9",
            "version": "==0.5.0"
        },
        "django": {
            "hash": "sha256:ac4c797a328a5ac8777ad61bcd00da279773455cc78b4058de2a9842a0eb6ee8",
            "version": "==1.11.10"
        },
        "django-allauth": {
            "hash": "sha256:45661b6fe308466154adf54461679fab6f0c6850b10c56dc322fbbb9d47e03d9",
            "version": "==0.38.0"
        },
        "django-appconf": {
            "hash": "sha256:ddab987d14b26731352c01ee69c090a4ebfc9141ed223bef039d79587f22acd9",
            "version": "==1.0.2"
        },
        "django-celery-email": {
            "hash": "sha256:e5f9122c02ec58d3e49653475ad1b8612fd752681ce2f006d9c0792c57046283",
            "version": "==2.0.1"
        },
        "django-cors-headers": {
            "hash": "sha256:5545009c9b233ea7e70da7dbab7cb1c12afa01279895086f98ec243d7eab46fa",
            "version": "==2.4.0"
        },
        "django-environ": {
            "hash": "sha256:c57b3c11ec1f319d9474e3e5a79134f40174b17c7cc024bbb2fad84646b120c4",
            "version": "==0.4.5"
        },
        "django-extensions": {
            "hash": "sha256:30cb6a8c7d6f75a55edf0c0c4491bd98f8264ae1616ce105f9cecac4387edd07",
            "version": "==2.1.3"
        },
        "django-filter": {
            "hash": "sha256:86c3925020c27d072cdae7b828aaa5d165c2032a629abbe3c3a1be1edae61c58",
            "version": "==2.0.0"
        },
        "django-fsm": {
            "hash": "sha256:c4790469e4f54b6cc95a3ac2c1bd1cdadeb04b0f3578e2472cdd857543a56e67",
            "version": "==2.6.0"
        },
        "django-localflavor": {
            "hash": "sha256:12ce98b13adcd68bb4babcd937d0ae5a0fd5801f71acaf9a6bf1784c218ef53c",
            "version": "==2.1"
        },
        "django-model-utils": {
            "hash": "sha256:8cd377744aa45f9f131d652ec460c57d1aaa88d3e9b586c8e27eb709341b9084",
            "version": "==3.1.2"
        },
        "django-money-fork": {
            "git": "https://github.com/mikeiwi/django-money-fork.git"
        },
        "django-nomad-notifier": {
            "hash": "sha256:3e073b62f7b27d1637286b8cdbedbae6780b49b87e2a0b635fe72034b623ea1b",
            "version": "==1.4.8"
        },
        "django-phonenumber-field": {
            "hash": "sha256:08257904750d7329b2b11dd9d8d6b7ceb261980db555bb426d9900fa390e2a4c",
            "version": "==2.0.1"
        },
        "django-rest-auth": {
            "hash": "sha256:ad155a0ed1061b32e3e46c9b25686e397644fd6acfd35d5c03bc6b9d2fc6c82a",
            "version": "==0.9.3"
        },
        "django-s3-folder-storage": {
            "hash": "sha256:eb5fd3994726f5b87ddc0ea1a6f1af3f598f9d743127c27d6dae111d18a79abe",
            "version": "==0.5"
        },
        "django-storages": {
            "hash": "sha256:b1a63cd5ea286ee5a9fb45de6c3c5c0ae132d58308d06f1ce9865cfcd5e470a7",
            "version": "==1.7.1"
        },
        "djangorestframework": {
            "hash": "sha256:63f76cbe1e7d12b94c357d7e54401103b2e52aef0f7c1650d6c820ad708776e5",
            "version": "==3.9.0"
        },
        "djangorestframework-jwt": {
            "hash": "sha256:ab15dfbbe535eede8e2e53adaf52ef0cf018ee27dbfad10cbc4cbec2ab63d38c",
            "version": "==1.11.0"
        },
        "docutils": {
            "hash": "sha256:02aec4bd92ab067f6ff27a38a38a41173bf01bed8f89157768c1573f53e474a6",
            "version": "==0.14"
        },
        "et-xmlfile": {
            "hash": "sha256:614d9722d572f6246302c4491846d2c393c199cfa4edc9af593437691683335b",
            "version": "==1.0.1"
        },
        "execnet": {
            "hash": "sha256:fc155a6b553c66c838d1a22dba1dc9f5f505c43285a878c6f74a79c024750b83",
            "version": "==1.5.0"
        },
        "gunicorn": {
            "hash": "sha256:aa8e0b40b4157b36a5df5e599f45c9c76d6af43845ba3b3b0efe2c70473c2471",
            "version": "==19.9.0"
        },
        "idna": {
            "hash": "sha256:156a6814fb5ac1fc6850fb002e0852d56c0c8d2531923a51032d1b70760e186e",
            "version": "==2.7"
        },
        "jdcal": {
            "hash": "sha256:948fb8d079e63b4be7a69dd5f0cd618a0a57e80753de8248fd786a8a20658a07",
            "version": "==1.4"
        },
        "jmespath": {
            "hash": "sha256:f11b4461f425740a1d908e9a3f7365c3d2e569f6ca68a2ff8bc5bcd9676edd63",
            "version": "==0.9.3"
        },
        "kombu": {
            "hash": "sha256:b274db3a4eacc4789aeb24e1de3e460586db7c4fc8610f7adcc7a3a1709a60af",
            "version": "==4.2.1"
        },
        "model-mommy": {
            "hash": "sha256:0e42c8f4a37c874dd81675ef8a385d3a25877082565e0d213022898c637f6f25",
            "version": "==1.6.0"
        },
        "more-itertools": {
            "hash": "sha256:c187a73da93e7a8acc0001572aebc7e3c69daf7bf6881a2cea10650bd4420092",
            "version": "==4.3.0"
        },
        "oauthlib": {
            "hash": "sha256:d883b36b21a6ad813953803edfa563b1b579d79ca758fe950d1bc9e8b326025b",
            "version": "==2.1.0"
        },
        "openpyxl": {
            "hash": "sha256:022c0f3fa1e873cc0ba20651c54dd5e6276fc4ff150b4060723add4fc448645e",
            "version": "==2.5.9"
        },
        "phonenumbers": {
            "hash": "sha256:fdf0f13eea9e4aee9d6bffee4f6ff05c81f41e3fbeb9642189516d9dc67978c9",
            "version": "==8.9.16"
        },
        "pluggy": {
            "hash": "sha256:bde19360a8ec4dfd8a20dcb811780a30998101f078fc7ded6162f0076f50508f",
            "version": "==0.8.0"
        },
        "psycopg2": {
            "hash": "sha256:6506c5ff88750948c28d41852c09c5d2a49f51f28c6d90cbf1b6808e18c64e88",
            "version": "==2.7.5"
        },
        "py": {
            "hash": "sha256:e76826342cefe3c3d5f7e8ee4316b80d1dd8a300781612ddbc765c17ba25a6c6",
            "version": "==1.7.0"
        },
        "py-moneyed": {
            "hash": "sha256:0c5dc04f77f1e0a123df051cc6ddc79267a48c612cb2d3dcfe7eb88cfc395bf9",
            "version": "==0.7.0"
        },
        "pyjwt": {
            "hash": "sha256:30b1380ff43b55441283cc2b2676b755cca45693ae3097325dea01f3d110628c",
            "version": "==1.6.4"
        },
        "pytest": {
            "hash": "sha256:7e258ee50338f4e46957f9e09a0f10fb1c2d05493fa901d113a8dafd0790de4e",
            "version": "==3.8.2"
        },
        "pytest-django": {
            "hash": "sha256:49e9ffc856bc6a1bec1c26c5c7b7213dff7cc8bc6b64d624c4d143d04aff0bcf",
            "version": "==3.4.3"
        },
        "pytest-forked": {
            "hash": "sha256:f275cb48a73fc61a6710726348e1da6d68a978f0ec0c54ece5a5fae5977e5a08",
            "version": "==0.2"
        },
        "pytest-xdist": {
            "hash": "sha256:06aa39361694c9365baaa03bec71159b59ad06c9826c6279ebba368cb3571561",
            "version": "==1.23.2"
        },
        "python-dateutil": {
            "hash": "sha256:f7cde3aecf8a797553d6ec49b65f0fbcffe7ffb971ccac452d181c28fd279936",
            "version": "==2.7.4"
        },
        "python-http-client": {
            "hash": "sha256:7e430f4b9dd2b621b0051f6a362f103447ea8e267594c602a5c502a0c694ee38",
            "version": "==3.1.0"
        },
        "python3-openid": {
            "hash": "sha256:0086da6b6ef3161cfe50fb1ee5cceaf2cda1700019fda03c2c5c440ca6abe4fa",
            "version": "==3.1.0"
        },
        "pytz": {
            "hash": "sha256:91e3ccf2c344ffaa6defba1ce7f38f97026943f675b7703f44789768e4cb0ece",
            "version": "==2018.6"
        },
        "raven": {
            "hash": "sha256:95f44f3ea2c1b176d5450df4becdb96c15bf2632888f9ab193e9dd22300ce46a",
            "version": "==6.9.0"
        },
        "requests": {
            "hash": "sha256:a84b8c9ab6239b578f22d1c21d51b696dcfe004032bb80ea832398d6909d7279",
            "version": "==2.20.0"
        },
        "requests-oauthlib": {
            "hash": "sha256:e21232e2465808c0e892e0e4dbb8c2faafec16ac6dc067dd546e9b466f3deac8",
            "version": "==1.0.0"
        },
        "s3transfer": {
            "hash": "sha256:c7a9ec356982d5e9ab2d4b46391a7d6a950e2b04c472419f5fdec70cc0ada72f",
            "version": "==0.1.13"
        },
        "sendgrid": {
            "hash": "sha256:97eb356ea44a18a03e6fe99f02b7942445be306a50f73a7dd35471fe15cc0094",
            "version": "==5.6.0"
        },
        "setuptools": {
            "hash": "sha256:ce4137d58b444bac11a31d4e0c1805c69d89e8ed4e91fde1999674ecc2f6f9ff",
            "version": "==40.4.3"
        },
        "six": {
            "hash": "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb",
            "version": "==1.11.0"
        },
        "urllib3": {
            "hash": "sha256:8819bba37a02d143296a4d032373c4dd4aca11f6d4c9973335ca75f9c8475f59",
            "version": "==1.24"
        },
        "vine": {
            "hash": "sha256:6849544be74ec3638e84d90bc1cf2e1e9224cc10d96cd4383ec3f69e9bce077b",
            "version": "==1.1.4"
        },
        "whitenoise": {
            "hash": "sha256:133a92ff0ab8fb9509f77d4f7d0de493eca19c6fea973f4195d4184f888f2e02",
            "version": "==4.1"
        }
    },
    "develop": {
        "atomicwrites": {
            "hash": "sha256:0312ad34fcad8fac3704d441f7b317e50af620823353ec657a53e981f92920c0",
            "version": "==1.2.1"
        },
        "attrs": {
            "hash": "sha256:ca4be454458f9dec299268d472aaa5a11f67a4ff70093396e1ceae9c76cf4bbb",
            "version": "==18.2.0"
        },
        "backcall": {
            "hash": "sha256:38ecd85be2c1e78f77fd91700c76e14667dc21e2713b63876c0eb901196e01e4",
            "version": "==0.1.0"
        },
        "coverage": {
            "hash": "sha256:76ecd006d1d8f739430ec50cc872889af1f9c1b6b8f48e29941814b09b0fd3cc",
            "version": "==4.5.1"
        },
        "decorator": {
            "hash": "sha256:2c51dff8ef3c447388fe5e4453d24a2bf128d3a4c32af3fabef1f01c6851ab82",
            "version": "==4.3.0"
        },
        "django": {
            "hash": "sha256:ac4c797a328a5ac8777ad61bcd00da279773455cc78b4058de2a9842a0eb6ee8",
            "version": "==1.11.10"
        },
        "django-extensions": {
            "hash": "sha256:30cb6a8c7d6f75a55edf0c0c4491bd98f8264ae1616ce105f9cecac4387edd07",
            "version": "==2.1.3"
        },
        "flake8": {
            "hash": "sha256:c01f8a3963b3571a8e6bd7a4063359aff90749e160778e03817cd9b71c9e07d2",
            "version": "==3.6.0"
        },
        "hypothesis": {
            "hash": "sha256:9ebe5056b7f8512f98d1029c8c949f69bf98e8f962456b954902afc32888c18d",
            "version": "==3.80.0"
        },
        "ipdb": {
            "hash": "sha256:7081c65ed7bfe7737f83fa4213ca8afd9617b42ff6b3f1daf9a3419839a2a00a",
            "version": "==0.11"
        },
        "ipython": {
            "hash": "sha256:47b17ea874454a5c2eacc2732b04a750d260b01ba479323155ac8a39031f5535",
            "version": "==7.0.1"
        },
        "ipython-genutils": {
            "hash": "sha256:72dd37233799e619666c9f639a9da83c34013a73e8bbc79a7a6348d93c61fab8",
            "version": "==0.2.0"
        },
        "jedi": {
            "hash": "sha256:0191c447165f798e6a730285f2eee783fff81b0d3df261945ecb80983b5c3ca7",
            "version": "==0.13.1"
        },
        "mccabe": {
            "hash": "sha256:ab8a6258860da4b6677da4bd2fe5dc2c659cff31b3ee4f7f5d64e79735b80d42",
            "version": "==0.6.1"
        },
        "more-itertools": {
            "hash": "sha256:c187a73da93e7a8acc0001572aebc7e3c69daf7bf6881a2cea10650bd4420092",
            "version": "==4.3.0"
        },
        "parso": {
            "hash": "sha256:895c63e93b94ac1e1690f5fdd40b65f07c8171e3e53cbd7793b5b96c0e0a7f24",
            "version": "==0.3.1"
        },
        "pexpect": {
            "hash": "sha256:3fbd41d4caf27fa4a377bfd16fef87271099463e6fa73e92a52f92dfee5d425b",
            "version": "==4.6.0"
        },
        "pickleshare": {
            "hash": "sha256:9649af414d74d4df115d5d718f82acb59c9d418196b7b4290ed47a12ce62df56",
            "version": "==0.7.5"
        },
        "pluggy": {
            "hash": "sha256:bde19360a8ec4dfd8a20dcb811780a30998101f078fc7ded6162f0076f50508f",
            "version": "==0.8.0"
        },
        "prompt-toolkit": {
            "hash": "sha256:ccad8461b5d912782726af17122113e196085e7e11d57cf0c9b982bf1ab2c7be",
            "version": "==2.0.6"
        },
        "ptyprocess": {
            "hash": "sha256:d7cc528d76e76342423ca640335bd3633420dc1366f258cb31d05e865ef5ca1f",
            "version": "==0.6.0"
        },
        "py": {
            "hash": "sha256:e76826342cefe3c3d5f7e8ee4316b80d1dd8a300781612ddbc765c17ba25a6c6",
            "version": "==1.7.0"
        },
        "pycodestyle": {
            "hash": "sha256:cbc619d09254895b0d12c2c691e237b2e91e9b2ecf5e84c26b35400f93dcfb83",
            "version": "==2.4.0"
        },
        "pyflakes": {
            "hash": "sha256:f661252913bc1dbe7fcfcbf0af0db3f42ab65aabd1a6ca68fe5d466bace94dae",
            "version": "==2.0.0"
        },
        "pygments": {
            "hash": "sha256:78f3f434bcc5d6ee09020f92ba487f95ba50f1e3ef83ae96b9d5ffa1bab25c5d",
            "version": "==2.2.0"
        },
        "pygraphviz": {
            "hash": "sha256:50a829a305dc5a0fd1f9590748b19fece756093b581ac91e00c2c27c651d319d",
            "version": "==1.5"
        },
        "pytest": {
            "hash": "sha256:6f6c1efc8d0ccc21f8f6c34d8330baca883cf109b66b3df954b0a117e5528fb4",
            "version": "==3.9.2"
        },
        "pytest-mock": {
            "hash": "sha256:53801e621223d34724926a5c98bd90e8e417ce35264365d39d6c896388dcc928",
            "version": "==1.10.0"
        },
        "pytz": {
            "hash": "sha256:91e3ccf2c344ffaa6defba1ce7f38f97026943f675b7703f44789768e4cb0ece",
            "version": "==2018.6"
        },
        "setuptools": {
            "hash": "sha256:ce4137d58b444bac11a31d4e0c1805c69d89e8ed4e91fde1999674ecc2f6f9ff",
            "version": "==40.4.3"
        },
        "simplegeneric": {
            "hash": "sha256:dc972e06094b9af5b855b3df4a646395e43d1c9d0d39ed345b7393560d0b9173",
            "version": "==0.8.1"
        },
        "six": {
            "hash": "sha256:832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb",
            "version": "==1.11.0"
        },
        "traitlets": {
            "hash": "sha256:c6cb5e6f57c5a9bdaa40fa71ce7b4af30298fbab9ece9815b5d995ab6217c7d9",
            "version": "==4.3.2"
        },
        "wcwidth": {
            "hash": "sha256:f4ebe71925af7b40a864553f761ed559b43544f8f71746c2d756c7fe788ade7c",
            "version": "==0.1.7"
        }
    }
}
```
</details>

**Comment by frostming** [comment]
Illegal Pipfile.lock, please do `$ pipenv update`

**Comment by keturn** [comment]
Can we get this to show a better error message? I just got the same thing (though with a different sha hash), and I have no idea why the `Pipfile.lock` would have been "illegal". I don't expect it was illegal when it was committed.
