### ISSUE TITLE
PIPENV vs VIRTUALENV on deployment

### ISSUE THREAD

**Issue by elfelround** [pypa/pipenv#3480]
so im trying to use https://www.youtube.com/watch?v=QjrfUO91wfc&t=47s this tutorial to upload a bitbucket to my ec2 through ssh and github

so i tried to use pipenv shell instead of virtualenv venv
source venv/bin/activate but i got an error

******************ORIGINAL COMMANDS

Python django deployment from GitHub to aws ec2 (Elastic Compute Cloud)

cd Downloads/
mv zillows.pem ~/Desktop/
cd ..
cd desktop

chmod

ssh

yes

sudo apt-get update
sudo apt-get install python-pip python-dev nginx git

Y

sudo apt-get update
sudo pip install virtualenv ********************HERE I INSTALLED PIPENV INSTEAD
git clone https://github.com/mruanova/zillow.git **********I USED BITBUCKET TO AVOID CHANGING SECRET KEYS
cd zillow
virtualenv venv   *****************HERE I TRIED PIPENV SHELL
source venv/bin/activate
***WASNT ABLE TO FURTHER CONTINUE WITH THE FOLLOWING COMMANDS***

ERRORS I GOT------
pipenv shell
Creating a virtualenv for this project...
Pipfile: /home/ubuntu/tfn/Pipfile
Using /usr/bin/python3 (3.6.5) to create virtualenv...
⠹ Creating virtual environment...Running virtualenv with interpreter /usr/bin/python3

✘ Failed creating virtual environment 
[pipenv.exceptions.VirtualenvCreationException]: File "/usr/local/lib/python2.7/dist-packages/pipenv/cli/command.py", line 390, in shell
[pipenv.exceptions.VirtualenvCreationException]: pypi_mirror=state.pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]: File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 2156, in do_shell
[pipenv.exceptions.VirtualenvCreationException]: three=three, python=python, validate=False, pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]: File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 574, in ensure_project
[pipenv.exceptions.VirtualenvCreationException]: pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]: File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 506, in ensure_virtualenv
[pipenv.exceptions.VirtualenvCreationException]: python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
[pipenv.exceptions.VirtualenvCreationException]: File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 935, in do_create_virtualenv
[pipenv.exceptions.VirtualenvCreationException]: extra=[crayons.blue("{0}".format(c.err)),]
[pipenv.exceptions.VirtualenvCreationException]: Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 20, in <module>
import distutils.spawn
ModuleNotFoundError: No module named 'distutils.spawn'

Failed to create virtual environment.

**Comment by elfelround** [comment]
python3-distutils was missing
or python-distutils if using python 2.7
