### ISSUE TITLE
pipenv shell fails in Git Bash on Windows using python 2.7

### ISSUE THREAD

**Issue by sparkyb** [pypa/pipenv#3494]
### Issue description

I'm running Git on Window Bash and using the regular Window Python 2.7. I run pipenv shell. I get a stack trace. When I run pipenv shell using the same python from a normal Windows cmd.exe prompt, it works fine.

The issue seems to be related to the version of NamedTemporaryFile in pipenv/vendor/vistir/backports/tempfile.py. I'm not sure what the need was for this version of tempfile, but when I modify pipenv/_compat.py to use the built-in tempfile it works fine.

### Expected result

A new bash shell with the virtualenv activated.

### Actual result
```
ben@buchwald01:/f/src/example$ pipenv shell
Launching subshell in virtual environment...
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\python27\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\pipenv\cli\command.py", line 390, in shell
    pypi_mirror=state.pypi_mirror,
  File "c:\python27\lib\site-packages\pipenv\core.py", line 2180, in do_shell
    shell.fork(*fork_args)
  File "c:\python27\lib\site-packages\pipenv\shells.py", line 95, in fork
    with self.inject_path(venv):
  File "c:\python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "c:\python27\lib\site-packages\pipenv\shells.py", line 147, in inject_path
    with NamedTemporaryFile("w+") as rcfile:
  File "c:\python27\lib\site-packages\pipenv\vendor\vistir\backports\tempfile.py", line 193, in NamedTemporaryFile
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
  File "c:\python27\lib\site-packages\pipenv\vendor\vistir\backports\tempfile.py", line 40, in _sanitize_params
    output_type = _infer_return_type(prefix, suffix, dir)
  File "c:\python27\lib\site-packages\pipenv\vendor\vistir\backports\tempfile.py", line 35, in _infer_return_type
    return _types.pop()
KeyError: 'pop from an empty set'
```

### Steps to replicate

From a Git on Windows Bash prompt, in an empty directory:
1. Run `pipenv install` to create a new empty pipenv virtualenv
2. Run `pipenv shell`.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'c:\\python27\\lib\\site-packages\\pipenv'`

Python location: `'c:\\python27\\python.exe'`

Python installations found:

  - `2.7.3`: `C:\Panda3D-1.8.1\python\pythonw.exe`
  - `2.7.15`: `C:\Python27\python.exe`
  - `2.7.15`: `C:\Python27\pythonw.exe`
  - `2.7.3`: `C:\Panda3D-1.8.1\python\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17134',
 'python_full_version': '2.7.15',
 'python_version': '2.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `PYTHONDONTWRITEBYTECODE`
  - `MSYSTEM_CHOST`
  - `SYSTEMROOT`
  - `CONEMUHWND`
  - `INFOPATH`
  - `SHELL`
  - `GIT_SSH`
  - `CONEMUDRIVE`
  - `MANPATH`
  - `WWISESDK`
  - `JAVA_HOME`
  - `CONEMUBUILD`
  - `COMSPEC`
  - `CONEMUBASEDIR`
  - `MSYSTEM_CARCH`
  - `CONFIG_SITE`
  - `HOMEDRIVE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `SYSTEMDRIVE`
  - `HOSTNAME`
  - `PROCESSOR_LEVEL`
  - `ANSICON`
  - `OS`
  - `CONEMUANSILOG`
  - `CONEMUBACKHWND`
  - `WWISEROOT`
  - `CONEMUPID`
  - `PS1`
  - `ANSICON_DEF`
  - `TEMP`
  - `SHLVL`
  - `COMMONPROGRAMFILES(X86)`
  - `ORIGINAL_TEMP`
  - `CONEMUARGS`
  - `HOMEPATH`
  - `CONEMUSERVERPID`
  - `LANG`
  - `LOGONSERVER`
  - `PKG_CONFIG_PATH`
  - `PIP_PYTHON_PATH`
  - `MSYSTEM_PREFIX`
  - `_`
  - `APPDATA`
  - `PIP_SHIMS_BASE_MODULE`
  - `TMP`
  - `COMPUTERNAME`
  - `USERDOMAIN`
  - `CONEMUARGS2`
  - `ORIGINAL_TMP`
  - `COMMONPROGRAMFILES`
  - `HOME`
  - `DRIVERDATA`
  - `CONEMUWORKDRIVE`
  - `PROCESSOR_ARCHITECTURE`
  - `CONEMUDIR`
  - `ALLUSERSPROFILE`
  - `TMPDIR`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `PROGRAMW6432`
  - `USERNAME`
  - `ONEDRIVE`
  - `CONEMUPALETTE`
  - `CONEMUBASEDIRSHORT`
  - `PATHEXT`
  - `CONFIGSETROOT`
  - `WINDIR`
  - `NUMBER_OF_PROCESSORS`
  - `PROCESSOR_ARCHITEW6432`
  - `CONEMUWORKDIR`
  - `PUBLIC`
  - `USERPROFILE`
  - `PSMODULEPATH`
  - `CONEMUANSI`
  - `ORIGINAL_PATH`
  - `PROCESSOR_IDENTIFIER`
  - `CONEMUCFGDIR`
  - `PROGRAMFILES`
  - `PROCESSOR_REVISION`
  - `PATH`
  - `PROGRAMFILES(X86)`
  - `TERM`
  - `CONEMUHOOKS`
  - `LOCALAPPDATA`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `MSYSTEM`
  - `PROGRAMDATA`
  - `CONEMUTASK`
  - `OLDPWD`
  - `PWD`
  - `SVN_SSH`
  - `CONEMUDRAWHWND`
  - `CONEMUCONFIG`
  - `COMMONPROGRAMW6432`

PipenvΓÇôspecific environment variables:

DebugΓÇôspecific environment variables:

  - `PATH`: `C:\Users\ben\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\opt\bin;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python27;C:\Python27\Scripts;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files\PuTTY;C:\Program Files (x86)\Common Files\Adobe\AGL;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\TortoiseGit\bin;C:\Panda3D-1.8.1\python;C:\Panda3D-1.8.1\bin;C:\Program Files\nodejs;C:\Program Files\Java\jdk1.8.0_192\bin;C:\Program Files\Java\apache-maven-3.5.4\bin;C:\Program Files (x86)\PyPE;C:\android-sdk\tools;C:\android-sdk\tools\bin;C:\android-sdk\platform-tools;C:\Program Files (x86)\Nmap;C:\Users\ben\AppData\Local\Microsoft\WindowsApps;C:\Users\ben\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl`
  - `SHELL`: `C:\Program Files\Git\usr\bin\bash.exe`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `F:/src/example`

---------------------------

Contents of `Pipfile` ('F:\\src\\example\\Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "2.7"

```

Contents of `Pipfile.lock` ('F:\\src\\example\\Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "ae4bdd7d4157baab65ae9d0e8389a6011e6b640995372c45ec81fa5d1ddfae9f"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "2.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>

**Comment by CoolNamesAllTaken** [comment]
I am also having this error.

**Comment by GeeWee** [comment]
I can confirm that I had the same issue, and installing pipenv with python 3.7 fixes the issue.

**Comment by adevshark** [comment]
> The issue seems to be related to the version of NamedTemporaryFile in pipenv/vendor/vistir/backports/tempfile.py. I'm not sure what the need was for this version of tempfile, but when I modify pipenv/_compat.py to use the built-in tempfile it works fine.

Hi @sparkyb ,
I am facing the same issue, can you let me know your workaround?
I am currently doing 
`pipenv run ...`
, and it's time-consuming.

**Comment by sparkyb** [comment]
> Hi @sparkyb ,
> I am facing the same issue, can you let me know your workaround?

Sorry, I can't help. I discovered this when I was evaluating pipenv, but ultimately I decided to not use pipenv and just stick with virtualenv + pip. In addition, I've also finally switched to Python 3.7 which I can confirm doesn't have this problem. I'm actually using a mixture of Python 3.7 and 2.7 while not all my old code is switched over and using the Windows tool py to choose which to run. I made Python 3.7 the default since I'd like to move that way, and use py -2 when I want to run my old Python 2.7 code. Inside a virtualenv I can always run python and get the correct version, so you could use a Python 3.7 pipenv to create a Python 2 virtualenv as a workaround.

**Comment by adevshark** [comment]
Thank you for your time.
