### ISSUE TITLE
Traceback when PYTHONOPTIMIZE=2

### ISSUE THREAD

**Issue by pavdmyt** [pypa/pipenv#3514]
### Issue Description

Getting a traceback when `PYTHONOPTIMIZE=2`. This is caused by `yaspin` package in `vendor` directory. Originally it was reported here: https://github.com/pavdmyt/yaspin/issues/26. The issue already fixed via https://github.com/pavdmyt/yaspin/pull/28 in `yaspin=0.14.1`.

I wanted to update `vendor/yaspin` via PR, but found that:

> A pull request to upgrade vendor packages is strongly discouraged

So, this is a notification to upgrade a vendored package.

### Steps to replicate

```
$ PYTHONOPTIMIZE=2 pipenv
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.11.26_1/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==2018.11.26', 'console_scripts', 'pipenv')()
  File "/usr/local/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/local/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/__init__.py", line 22, in <module>
    from pipenv.vendor.vistir.compat import ResourceWarning, fs_str
  File "/usr/local/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/vendor/vistir/__init__.py", line 31, in <module>
    from .spin import VistirSpinner, create_spinner
  File "/usr/local/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/vendor/vistir/spin.py", line 19, in <module>
    import yaspin
  File "/usr/local/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/vendor/yaspin/__init__.py", line 6, in <module>
    from .api import kbi_safe_yaspin, yaspin
  File "/usr/local/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/vendor/yaspin/api.py", line 87, in <module>
    _kbi_safe_doc = yaspin.__doc__.replace("yaspin", "kbi_safe_yaspin")
AttributeError: 'NoneType' object has no attribute 'replace'
```
-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.11.26_1/libexec/bin/python3.7'`

Python installations found:

  - `3.7.2`: `/usr/local/bin/python3`
  - `3.7.2`: `/usr/local/bin/python3.7m`
  - `3.7.1`: `/Users/pavdmyt/.pyenv/versions/3.7.1/bin/python3`
  - `3.7.1`: `/Users/pavdmyt/.pyenv/versions/3.7.1/bin/python3.7m`
  - `3.4.9`: `/Users/pavdmyt/.pyenv/versions/playground-py34/bin/python3`
  - `3.4.9`: `/Users/pavdmyt/.pyenv/versions/3.4.9/bin/python3.4m`
  - `2.7.15`: `/Users/pavdmyt/.pyenv/versions/playground-py27/bin/python`
  - `2.7.15`: `/Users/pavdmyt/.pyenv/versions/2.7.15/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.2.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT '
                     '2018; root:xnu-4903.221.2~2/RELEASE_X86_64',
 'python_full_version': '3.7.2',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `TERM_PROGRAM`
  - `TERM`
  - `SHELL`
  - `PIPENV_VENV_IN_PROJECT`
  - `TMPDIR`
  - `GOBIN`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `ZSH`
  - `LC_ALL`
  - `USER`
  - `COMMAND_MODE`
  - `KUBECONFIG`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `PYENV_VIRTUALENV_INIT`
  - `VIRTUAL_ENV_DISABLE_PROMPT`
  - `PAGER`
  - `LSCOLORS`
  - `GOSRC`
  - `_`
  - `PWD`
  - `LANG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `PYENV_SHELL`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `GOROOT`
  - `GOPROJ`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `GOPATH`
  - `SECURITYSESSIONID`
  - `COLORTERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`

---------------------------

</details>

**Comment by matteius** [comment]
We no longer use yaspin spinner (though it is temporarily still vendor'd).
