### ISSUE TITLE
Pipenv lock fails for install from local source

### ISSUE THREAD

**Issue by glinskyc** [pypa/pipenv#3541]
### Issue description

Upon installing a local package from source, the Pipenv file accurately reflects the installed package, but Pipenv lock fails.

`pipenv install "./relative/path/to/my-custom-package-0.1.0.tar.gz"`

Pipenv file then contains the following, as expected:

_[packages]
my-custom-package = {path = "./relative/path/to/my-custom-package-0.1.0.tar.gz"}_

The setup.py file in `my-custom-package` includes the `python_requires` attribute with a list of str elements for each package required in `my-custom-package`.  I mention this because I originally thought this is where the problem is, but not so sure now.

As a side note, I already tried `pipenv lock --clear`, but the same error occurs.

### Expected result

Pipenv lock is expected to resolve as normal.

### Actual result

TypeError occurs.  Here's the trace:

Locking [dev-packages] dependencies…
Traceback (most recent call last):
  File "c:\users\chad\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\chad\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Chad\Miniconda3\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "c:\users\chad\miniconda3\lib\site-packages\pipenv\vendor\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\chad\miniconda3\lib\site-packages\pipenv\vendor\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\chad\miniconda3\lib\site-packages\pipenv\vendor\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\chad\miniconda3\lib\site-packages\pipenv\vendor\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\chad\miniconda3\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\chad\miniconda3\lib\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\chad\miniconda3\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\chad\miniconda3\lib\site-packages\pipenv\vendor\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\chad\miniconda3\lib\site-packages\pipenv\cli\command.py", line 332, in lock
    pypi_mirror=state.pypi_mirror,
  File "c:\users\chad\miniconda3\lib\site-packages\pipenv\core.py", line 1055, in do_lock
    packages, project, r=False, include_index=True
  File "c:\users\chad\miniconda3\lib\site-packages\pipenv\utils.py", line 832, in convert_deps_to_pip
    req = new_dep.as_line(sources=indexes if include_index else None).strip()
  File "c:\users\chad\miniconda3\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 1276, in as_line
    index_string = " ".join(source_list)
TypeError: sequence item 3: expected str instance, NoneType found

**Comment by techalchemy** [comment]
Thanks for the report and sorry for the issue, `requirementslib` only properly began supporting this type of resolution (that is, resolution of the dependencies of a package represented as a zipfile or a tarball) in the last release and unfortunately, pip `19.0` and subsequently `19.0.1` and `19.0.2` were released after that with pep 517 build support which was a breaking change (and in pip 19.0 and 19.0.1 the change was indeed breaking for many existing resolution processes).

This _should_ be fixed shortly, I have a branch up with an updated version of `requirementslib` which you can test against by installing pipenv with `pip install -e git+https://github.com/pypa/pipenv.git@bugfix/3148#egg=pipenv` -- let me know if that fixes things for you

**Comment by glinskyc** [comment]
Thanks for the quick reply, and apologies for my slow reply.  I tried your suggestion, but now get a different TypeError during locking of [packages].  The trace is below.

Traceback (most recent call last):
  File "c:/users/chad/documents/python/src/pipenv/pipenv/resolver.py", line 200, in <module>
    main()
  File "c:/users/chad/documents/python/src/pipenv/pipenv/resolver.py", line 196, in main
    parsed.requirements_dir, parsed.packages, parse_only=parsed.parse_only)
  File "c:/users/chad/documents/python/src/pipenv/pipenv/resolver.py", line 170, in _main
    resolve_packages(pre, clear, verbose, system, requirements_dir, packages)
  File "c:/users/chad/documents/python/src/pipenv/pipenv/resolver.py", line 150, in resolve_packages
    system=system, requirements_dir=requirements_dir)
  File "c:/users/chad/documents/python/src/pipenv/pipenv/resolver.py", line 140, in resolve
    req_dir=requirements_dir
  File "c:\users\chad\documents\python\src\pipenv\pipenv\utils.py", line 1000, in resolve_deps
    req_dir=req_dir,
  File "c:\users\chad\documents\python\src\pipenv\pipenv\utils.py", line 679, in actually_resolve_deps
    deps, index_lookup, markers_lookup, project, sources,
  File "c:\users\chad\documents\python\src\pipenv\pipenv\utils.py", line 313, in get_metadata
    dep, index_lookup=index_lookup, markers_lookup=markers_lookup, project=project
  File "c:\users\chad\documents\python\src\pipenv\pipenv\utils.py", line 344, in parse_line
    req = Requirement.from_line(line)
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 2570, in from_line
    r = file_req_from_parsed_line(parsed_line)
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 2953, in file_req_from_parsed_line
    name=parsed_line.name,
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 528, in name
    if self.setup_info:
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 689, in setup_info
    self.setup_info = self.get_setup_info()
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 674, in get_setup_info
    setup_info = SetupInfo.from_ireq(self.ireq)
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 657, in ireq
    self.parse_ireq()
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 777, in parse_ireq
    if self.requirement is not None and self._ireq.req is None:
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 349, in requirement
    self.parse_requirement()
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 879, in parse_requirement
    if self.setup_info and self.setup_info.name:
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 689, in setup_info
    self.setup_info = self.get_setup_info()
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 674, in get_setup_info
    setup_info = SetupInfo.from_ireq(self.ireq)
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\setup_info.py", line 888, in from_ireq
    src_dir, subdirectory=subdir, ireq=ireq, kwargs=kwargs
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\setup_info.py", line 914, in create
    created.get_info()
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\setup_info.py", line 786, in get_info
    self.build()
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\setup_info.py", line 683, in build
    os.path.join(self.extra_kwargs["build_dir"], dist_path)
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\setup_info.py", line 704, in get_metadata_from_wheel
    metadata_dict = get_metadata_from_wheel(wheel_path)
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\setup_info.py", line 309, in get_metadata_from_wheel
    parsed_req = init_requirement(req)
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\utils.py", line 110, in init_requirement
    raise TypeError("must supply a name to generate a requirement")
TypeError: must supply a name to generate a requirement
File "c:/users/chad/documents/python/src/pipenv/pipenv/resolver.py", line 200, in <module>
    main()
  File "c:/users/chad/documents/python/src/pipenv/pipenv/resolver.py", line 196, in main
    parsed.requirements_dir, parsed.packages, parse_only=parsed.parse_only)
  File "c:/users/chad/documents/python/src/pipenv/pipenv/resolver.py", line 170, in _main
    resolve_packages(pre, clear, verbose, system, requirements_dir, packages)
  File "c:/users/chad/documents/python/src/pipenv/pipenv/resolver.py", line 150, in resolve_packages
    system=system, requirements_dir=requirements_dir)
  File "c:/users/chad/documents/python/src/pipenv/pipenv/resolver.py", line 140, in resolve
    req_dir=requirements_dir
  File "c:\users\chad\documents\python\src\pipenv\pipenv\utils.py", line 1000, in resolve_deps
    req_dir=req_dir,
  File "c:\users\chad\documents\python\src\pipenv\pipenv\utils.py", line 679, in actually_resolve_deps
    deps, index_lookup, markers_lookup, project, sources,
  File "c:\users\chad\documents\python\src\pipenv\pipenv\utils.py", line 313, in get_metadata
    dep, index_lookup=index_lookup, markers_lookup=markers_lookup, project=project
  File "c:\users\chad\documents\python\src\pipenv\pipenv\utils.py", line 344, in parse_line
    req = Requirement.from_line(line)
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 2570, in from_line
    r = file_req_from_parsed_line(parsed_line)
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 2953, in file_req_from_parsed_line
    name=parsed_line.name,
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 528, in name
    if self.setup_info:
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 689, in setup_info
    self.setup_info = self.get_setup_info()
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 674, in get_setup_info
    setup_info = SetupInfo.from_ireq(self.ireq)
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 657, in ireq
    self.parse_ireq()
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 777, in parse_ireq
    if self.requirement is not None and self._ireq.req is None:
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 349, in requirement
    self.parse_requirement()
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 879, in parse_requirement
    if self.setup_info and self.setup_info.name:
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 689, in setup_info
    self.setup_info = self.get_setup_info()
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\requirements.py", line 674, in get_setup_info
    setup_info = SetupInfo.from_ireq(self.ireq)
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\setup_info.py", line 888, in from_ireq
    src_dir, subdirectory=subdir, ireq=ireq, kwargs=kwargs
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\setup_info.py", line 914, in create
    created.get_info()
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\setup_info.py", line 786, in get_info
    self.build()
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\setup_info.py", line 683, in build
    os.path.join(self.extra_kwargs["build_dir"], dist_path)
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\setup_info.py", line 704, in get_metadata_from_wheel
    metadata_dict = get_metadata_from_wheel(wheel_path)
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\setup_info.py", line 309, in get_metadata_from_wheel
    parsed_req = init_requirement(req)
  File "c:\users\chad\documents\python\src\pipenv\pipenv\vendor\requirementslib\models\utils.py", line 110, in init_requirement
    raise TypeError("must supply a name to generate a requirement")
TypeError: must supply a name to generate a requirement

**Comment by glinskyc** [comment]
I get the same error when using the approach outlined here:

https://pipenv.readthedocs.io/en/latest/basics/#a-note-about-vcs-dependencies

This leads me to believe I am missing something in `my-custom-package`, i.e. the package I am trying to install.  I thought all that would be needed is the `install_requires` arg for `setuptools.setup` function.  My `setup.py` file is based on https://github.com/kennethreitz/setup.py.

I'll do more digging on my end.

**Comment by glinskyc** [comment]
I encounter the same error when running the following command (example taken directly from documentation https://pipenv.readthedocs.io/en/latest/basics/#a-note-about-vcs-dependencies):
``
pipenv install -e git+https://github.com/requests/requests.git@v2.20.1#egg=requests
``

pipenv, version 2018.11.27.dev0

**Comment by techalchemy** [comment]
With `pip install --upgrade -e git+https://github.com/pypa/pipenv.git@bugfix/3148#egg=pipenv` as my install (do this again if you haven't done it in a day or so) the command you provided works completely fine for me, i literally copied and pasted it:

```console
(.venv)   ³ .venv  /t/test  pipenv install -e git+https://github.com/requests/requests.git@v2.20.1#egg=requests
Creating a virtualenv for this project…
Pipfile: /tmp/test/Pipfile
Using /mnt/ramdisk/.venv/bin/python3.7 (3.7.2) to create virtualenv…
⠏ Creating virtual environment...Already using interpreter /mnt/ramdisk/.venv/bin/python3.7
Using real prefix '/home/hawk/.pyenv/versions/3.7.2'
New python executable in /home/hawk/.virtualenvs/test-hxkKlP5o/bin/python3.7
Also creating executable in /home/hawk/.virtualenvs/test-hxkKlP5o/bin/python
Installing setuptools, pip, wheel...
done.

✔ Successfully created virtual environment! 
Virtualenv location: /home/hawk/.virtualenvs/test-hxkKlP5o
Creating a Pipfile for this project…
Installing -e git+https://github.com/requests/requests.git@v2.20.1#egg=requests…
Adding requests to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
✔ Success! 
Updated Pipfile.lock (1a44be)!
Installing dependencies from Pipfile.lock (1a44be)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 5/5 — 00:00:03
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

**Comment by techalchemy** [comment]
Also, with the test artifact taken directly from `tests/test_artifacts` in pipenv's root folder and this as my Pipfile:

```ini
[[sources]]
url = "https://pypi.org/simple"
name = "pypi"
verify_ssl = true

[packages]
requests = {path = "./requests-2.19.1.tar.gz"}

[dev-packages]
```

And I am able to install this as well without any difficulty:

```console
(.venv)   ³ .venv  /t/test  pipenv install
Creating a virtualenv for this project…
Pipfile: /tmp/test/Pipfile
Using /mnt/ramdisk/.venv/bin/python3.7 (3.7.2) to create virtualenv…
⠧ Creating virtual environment...Already using interpreter /mnt/ramdisk/.venv/bin/python3.7
Using real prefix '/home/hawk/.pyenv/versions/3.7.2'
New python executable in /home/hawk/.virtualenvs/test-hxkKlP5o/bin/python3.7
Also creating executable in /home/hawk/.virtualenvs/test-hxkKlP5o/bin/python
Installing setuptools, pip, wheel...
done.

✔ Successfully created virtual environment! 
Virtualenv location: /home/hawk/.virtualenvs/test-hxkKlP5o
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
✔ Success! 
Updated Pipfile.lock (f1e1c4)!
Installing dependencies from Pipfile.lock (f1e1c4)…
An error occurred while installing ./requests-2.19.1.tar.gz --hash=sha256:ec22d826a36ed72a7358ff3fe56cbd4ba69dd7a6718ffd450ff0e9df7a47ce6a! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 5/5 — 00:00:01
Installing initially failed dependencies…
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:01
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

**Comment by glinskyc** [comment]
Not sure what my problem was exactly, but I identified there was something wrong with my `conda` installation, so I removed it and installed Python 3.7.2 directly.  The local (& git) install procedure with `pipenv` appears to be working fine now.

Feel free to close this issue.  Thanks.

**Comment by techalchemy** [comment]
that's possibly the 5th compatibility issue i've seen related to conda today (also I haven't triaged issues in a long time) & it may be related to the `lib-dynload` library in your virtualenv

closing for now but i recommend triaging that with anaconda or virtualenv, thanks for your patience!
