### ISSUE TITLE
pipenv import in another click application (TypeError: __init__() got an unexpected keyword argument 'show_envvar')

### ISSUE THREAD

**Issue by snowman2** [pypa/pipenv#3552]
### Issue description
I originally had pip 9.0.3, and so I tried the latest:
```
$ pip install pipenv==2018.11.26 pip==19.0.3
Requirement already satisfied: pipenv==2018.11.26 in /var/lang/lib/python3.6/site-packages
Collecting pip==19.0.3
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl (1.4MB)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /var/lang/lib/python3.6/site-packages (from pipenv==2018.11.26)
Requirement already satisfied: setuptools>=36.2.1 in /var/lang/lib/python3.6/site-packages (from pipenv==2018.11.26)
Requirement already satisfied: virtualenv in /var/lang/lib/python3.6/site-packages (from pipenv==2018.11.26)
Requirement already satisfied: certifi in /var/lang/lib/python3.6/site-packages (from pipenv==2018.11.26)
Installing collected packages: pip
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
Successfully installed pip-19.0.3
```
Here is the error:
```
Traceback (most recent call last):
  File "/var/lang/bin/pipd", line 11, in <module>
    sys.exit(pipd())
  File "/var/lang/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/var/lang/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/var/lang/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/lang/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/lang/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/lang/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
   File "/var/lang/lib/python3.6/site-packages/custom_cli/zappa/zappa.py", line 22, in wrapper
    import pipenv
  File "/var/lang/lib/python3.6/site-packages/pipenv/__init__.py", line 47, in <module>
    from .cli import cli
  File "/var/lang/lib/python3.6/site-packages/pipenv/cli/__init__.py", line 3, in <module>
    from .command import cli
  File "/var/lang/lib/python3.6/site-packages/pipenv/cli/command.py", line 79, in <module>
    clear=False,
  File "/var/lang/lib/python3.6/site-packages/pipenv/cli/options.py", line 386, in general_options
    f = common_options(f)
  File "/var/lang/lib/python3.6/site-packages/pipenv/cli/options.py", line 338, in common_options
    f = clear_option(f)
  File "/var/lang/lib/python3.6/site-packages/pipenv/cli/options.py", line 255, in clear_option
    expose_value=False, show_envvar=True)(f)
  File "/var/lang/lib/python3.6/site-packages/click/decorators.py", line 170, in decorator
    _param_memo(f, OptionClass(param_decls, **attrs))
  File "/var/lang/lib/python3.6/site-packages/click/core.py", line 1460, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'show_envvar'
```
### Expected result

No errors.

### Actual result

See above.

### Steps to replicate
Import pipenv in a click application.
```
import pipenv
```

### Solution:

```
pip install "click>=7.0"
  Found existing installation: click 6.7
    Uninstalling click-6.7:
      Successfully uninstalled click-6.7
Successfully installed click-7.0
```

**Comment by frostming** [comment]
There was an api change in click 7.0, as you have seen, upgrade click will solve this problem.
