### ISSUE TITLE
Error in PipenvUsageError?

### ISSUE THREAD

**Issue by dimaqq** [pypa/pipenv#3560]
```py
Step 1/5 : FROM python:3.8.0a1-alpine3.9
 ---> 4b47ccb20dbe
Step 2/5 : ENV PYTHONDONTWRITEBYTECODE 1
 ---> Using cache
 ---> 1266f81bbbb0
Step 3/5 : RUN pip install pipenv==2018.11.26
 ---> Using cache
 ---> 282c4198a839
Step 4/5 : COPY Pipfile Pipfile.lock /
 ---> a10b922545ea
Step 5/5 : RUN pipenv install --system --deploy --dev
 ---> Running in c1a8bbad3884
Your Pipfile.lock (0e51d6) is out of date. Expected: (cefd04).
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/cli/command.py", line 235, in install
    retcode = do_install(
  File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 1863, in do_install
    do_init(
  File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 1192, in do_init
    raise exceptions.DeployException
  File "/usr/local/lib/python3.8/site-packages/pipenv/exceptions.py", line 168, in __init__
    PipenvUsageError.__init__(message=fix_utf8(message), extra=extra, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'self'
```

**Comment by dimaqq** [comment]
`__init__` is correct in master branch... I wonder where I got this odd version from...

**Comment by dimaqq** [comment]
It was fixed in e532f16c62abff3e20e9129139889d166759cc77 
Waiting for new release!

**Comment by haizaar** [comment]
@dimaqq Do you know any simple workaround? I suddenly start hitting this for no reason and there is no new release...

**Comment by g-erson** [comment]
@dimaqq Just started hitting this as well... 

I'm on the python:3.6-alpine docker image, python 3.6.8, pipenv version 2018.11.26

**Comment by dimaqq** [comment]
I guess the best is to ask nicely for a new release.

I've pinned `pipenv==2018.10.13` or to be precise included that in my the docker image:
```
ENV PYTHONDONTWRITEBYTECODE 1
RUN pip install pipenv==2018.10.13
COPY Pipfile Pipfile.lock /
RUN pipenv install --system --deploy
```

If you need newer functionality (https://github.com/pypa/pipenv/blob/master/CHANGELOG.rst#20181126-2018-11-26, there's plenty), patch our local pipenv with https://github.com/pypa/pipenv/commit/e532f16c62abff3e20e9129139889d166759cc77 or build your own wheel from `master` and install your custom build...

**Comment by nicktimko** [comment]
To my knowledge, I think this is only hit when there is a problem with the command or the `Pipfile` itself. If others come across this, check the `Pipfile`/`Pipfile.lock` is OK (not trashed by a merge conflict) and possibly recreate it by deleting the *lockfile* and `pipenv lock` again.

**Comment by jedie** [comment]
I see the same error in `pipenv-2018.11.26`
