### ISSUE TITLE
pipenv fails to install packages on a Jenkins slave

### ISSUE THREAD

**Issue by rparkhunovsky** [pypa/pipenv#3564]
### Issue description

The problem: pipenv fails to install anything either from Pipfile or Pipfile.lock on a Jenkins docker-based slave 
```Installing dependencies from Pipfile.lock (088fa7)...
An error occurred while installing pypd==0.1.0 --hash=sha256:50c7c49161a04d202e547a7e7413b57e823075e08653c74a8218bb0cb801e1e3! Will try again.
....
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]:   File "/usr/lib/python2.7/site-packages/pipenv/cli/command.py", line 254, in install
[pipenv.exceptions.InstallError]:       editable_packages=state.installstate.editables,
[pipenv.exceptions.InstallError]:   File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 1874, in do_install
[pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
[pipenv.exceptions.InstallError]:   File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 862, in do_install_dependencies
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, False, failed_deps_queue, retry=False)
[pipenv.exceptions.InstallError]:   File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ["An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')"]
[pipenv.exceptions.InstallError]: []
ERROR: ERROR: Package installation failed...
```

### Expected result

Packages get installed by any of the below commands:
- `pipenv install`
- `pipenv install --sequential`
- `pipenv install --ignore-pipfile`
- `pipenv install --skip-lock`
- `pipenv install --system`
All of them were tried with the same error output.

### Actual result

```
+ pipenv --verbose install --verbose
Creating a virtualenv for this project...
Pipfile: /workspace/my-team/my-proj/task-test/slack/Pipfile
Using /usr/bin/python2 (2.7.5) to create virtualenv...

⠋ Creating virtual environment...
⠇ Creating virtual environment...Already using interpreter /usr/bin/python2
New python executable in /root/.local/share/virtualenvs/slack-l1onmoz_/bin/python2
Also creating executable in /root/.local/share/virtualenvs/slack-l1onmoz_/bin/python
Installing Setuptools....................................................................................................................................................................done.
Installing Pip...............................................................................................................................................................................................................................................done.

✔ Successfully created virtual environment! 
Virtualenv location: /root/.local/share/virtualenvs/slack-l1onmoz_
Installing dependencies from Pipfile.lock (088fa7)...
Installing u'pypd'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-wudNGo-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'futures'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-YPIOXX-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'six'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-yaDGMg-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'urllib3'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-UezSJs-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u's3transfer'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-o4qd9_-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'boto3'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-u37Pbb-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'docutils'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-48kecL-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'chardet'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-0t0n8C-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'python-dateutil'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-iAelre-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'certifi'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-p_D6Ir-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'jmespath'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-Nkxg16-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'botocore'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-3kjV_U-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'idna'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-l4jlfZ-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'requests'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-W7Lmac-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'slackclient'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-mOYgId-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'websocket-client'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-K7eUGx-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing pypd==0.1.0 --hash=sha256:50c7c49161a04d202e547a7e7413b57e823075e08653c74a8218bb0cb801e1e3! Will try again.
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing futures==3.2.0 ; python_version == '2.6' or python_version == '2.7' --hash=sha256:9ec02aa7d674acb8618afb127e27fde7fc68994c0437ad759fa094a574adb265 --hash=sha256:ec0a6cb848cc212002b9828c3e34c675e0c9ff6741dc445cab6fdd4e1085d1f1! Will try again.
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing six==1.12.0 --hash=sha256:3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c --hash=sha256:d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73! Will try again.
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing urllib3==1.24.1 --hash=sha256:61bf29cada3fc2fbefad4fdf059ea4bd1b4a86d2b6d15e1c7c0b582b9752fe39 --hash=sha256:de9529817c93f27c8ccbfead6985011db27bd0ddfcdb2d86f3f663385c6a9c22! Will try again.
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing s3transfer==0.1.13 --hash=sha256:90dc18e028989c609146e241ea153250be451e05ecc0c2832565231dacdf59c1 --hash=sha256:c7a9ec356982d5e9ab2d4b46391a7d6a950e2b04c472419f5fdec70cc0ada72f! Will try again.
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing boto3==1.4.6 --hash=sha256:6befc73f61a8b62b387847f3f5e7c3234d36a44e2a22e975054eb431d6de9561 --hash=sha256:fd521edcd36fab7f692e42eec7f9fe10468f4d143597bb939437dfe56c15dfb2! Will try again.
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing docutils==0.14 --hash=sha256:02aec4bd92ab067f6ff27a38a38a41173bf01bed8f89157768c1573f53e474a6 --hash=sha256:51e64ef2ebfb29cae1faa133b3710143496eca21c530f3f71424d77687764274 --hash=sha256:7a4bd47eaf6596e1295ecb11361139febe29b084a87bf005bf899f9a42edc3c6! Will try again.
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing chardet==3.0.4 --hash=sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae --hash=sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691! Will try again.
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing python-dateutil==2.8.0 --hash=sha256:7e6584c74aeed623791615e26efd690f29817a27c73085b78e4bad02493df2fb --hash=sha256:c89805f6f4d64db21ed966fda138f8a5ed7a4fdbc1a8ee329ce1b74e3c74da9e! Will try again.
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing certifi==2018.11.29 --hash=sha256:47f9c83ef4c0c621eaef743f133f09fa8a74a9b75f037e8624f83bd1b6626cb7 --hash=sha256:993f830721089fef441cdfeb4b2c8c9df86f0c63239f06bd025a76a7daddb033! Will try again.
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing jmespath==0.9.4 --hash=sha256:3720a4b1bd659dd2eecad0666459b9788813e032b83e7ba58578e48254e0a0e6 --hash=sha256:bde2aef6f44302dfb30320115b17d030798de8c4110e28d5cf6cf91a7a31074c! Will try again.
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing botocore==1.6.8 --hash=sha256:2e679f2327b1064dc74b5a62ce71a725add031b8e539668ce666da3a857a1b63 --hash=sha256:cf77f64f5420d92df9b0430befea16eeb573f259623ffdd1c79958fc590faa46! Will try again.
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing idna==2.8 --hash=sha256:c357b3f628cf53ae2c4c05627ecc484553142ca23264e593d327bcde5e9c3407 --hash=sha256:ea8b7f6188e6fa117537c3df7da9fc686d485087abf6ac197f9c46432f7e4a3c! Will try again.
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing requests==2.21.0 --hash=sha256:502a824f31acdacb3a35b6690b5fbf0bc41d63a24a45c4004352b0242707598e --hash=sha256:7bf2a778576d825600030a110f3c0e3e8edc51dfaafe1c146e39a2027784957b! Will try again.
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing slackclient==1.3.0 --hash=sha256:4d5f2d5b05a8fa717b745efa934d0a4240dfc8442f169fb2a8af4e5adb8297ad --hash=sha256:d06b2105a1044651a7dcefe77c24cade6ae7c98ff53422e970634e62862e7bf3! Will try again.
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
An error occurred while installing websocket-client==0.55.0 --hash=sha256:47a3ddf3ee7ecd4e2f81610bcdc7f44d5dd03b602b911d4ce991cd82310d3f3b --hash=sha256:f6029deea21218f2c771848935aa26c15699c831770f4fa66958bdaabff80ca0! Will try again.
Installing initially failed dependencies...
Installing u'pypd'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-9PkScV-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'futures'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-nF5Bag-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'six'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-QMYGZx-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'urllib3'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-8wrwUT-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u's3transfer'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-ytQllt-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'boto3'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-HwUTXi-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'docutils'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-YtKpBX-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'chardet'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-LsnAjX-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'python-dateutil'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-2V8Jll-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'certifi'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-BDUvRb-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'jmespath'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-tCAwxG-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'botocore'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-g387BQ-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'idna'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-QOetr5-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'requests'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-evNh3k-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'slackclient'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-TkuCRZ-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
Installing u'websocket-client'
$ ['/root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip', 'install', '--verbose', '--upgrade', '--no-deps', '-r', '/tmp/pipenv-H2djnQ-requirements/pipenv-ecjN1f-requirement.txt', '-i', u'https://pypi.org/simple', '--require-hashes']
An error occurred during configuration: option --exists-action: invalid choice: ['w'] (choose from 's', 'i', 'w', 'b')
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 1874, in do_install
    keep_outdated=keep_outdated
  File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 1253, in do_init
    pypi_mirror=pypi_mirror,
  File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 862, in do_install_dependencies
    _cleanup_procs(procs, False, failed_deps_queue, retry=False)
  File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
    raise exceptions.InstallError(c.dep.name, extra=err_lines)
pipenv.exceptions.InstallError: ERROR: ERROR: Package installation failed...
+ /root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip --version
An error occurred during configuration: option --exists-action: invalid choice: ['i'] (choose from 's', 'i', 'w', 'b')
```
Additionally,  having found a somewhat similar ticket: https://github.com/pypa/pip/issues/772, made me run these:
```
+ /root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip --version
pip 1.4.1 from /root/.local/share/virtualenvs/slack-l1onmoz_/lib/python2.7/site-packages (python 2.7)

+ cat /root/.local/share/virtualenvs/slack-l1onmoz_/bin/pip
#!/root/.local/share/virtualenvs/slack-l1onmoz_/bin/python2
# EASY-INSTALL-ENTRY-SCRIPT: 'pip==1.4.1','console_scripts','pip'
__requires__ = 'pip==1.4.1'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('pip==1.4.1', 'console_scripts', 'pip')()
    )
```
Something is causing very old pip version to be installed. I've verified that ` /root/.local/share/virtualenvs/slack-l1onmoz_` is not a leftover and is created every time the job is executed.

### Steps to replicate

```
pip install --upgrade setuptools
pip install --upgrade pip
pip install pipenv
pipenv install
```

Pipfile is as simple as:
```
cat Pipfile
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
slackclient = "==1.3.0"
pypd = "==0.1.0"
boto3 = "==1.4.6"

[requires]
python_version = "2.7"
```
Versions:
pipenv, version 2018.11.26
pip, version 19.0.3
setuptools, version 40.8.0
python, version 2.7.5

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/bin/python2'`

Python installations found:

  - `2.7.5`: `/usr/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.14.62-65.117.amzn1.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Fri Aug 10 20:03:52 UTC 2018',
 'python_full_version': '2.7.5',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `JENKINS_HOME`
  - `BUILD_CAUSE`
  - `JOB_BASE_NAME`
  - `HUDSON_URL`
  - `BUILD_URL`
  - `PYTHONDONTWRITEBYTECODE`
  - `GIT_PREVIOUS_COMMIT`
  - `BUILD_TAG`
  - `HUDSON_SERVER_COOKIE`
  - `Version`
  - `HUDSON_HOME`
  - `WORKSPACE`
  - `HOME`
  - `PATH`
  - `JIRA_PROJECT`
  - `JOB_NAME`
  - `LANG`
  - `RUN_DISPLAY_URL`
  - `GIT_COMMITTER_NAME`
  - `GIT_PREVIOUS_SUCCESSFUL_COMMIT`
  - `LANGUAGE`
  - `SHLVL`
  - `GIT_AUTHOR_EMAIL`
  - `AWS_METADATA_SERVICE_NUM_ATTEMPTS`
  - `AWS_ACCOUNT_ID`
  - `NODE_LABELS`
  - `ROOT_BUILD_CAUSE_MANUALTRIGGER`
  - `BUILD_CAUSE_MANUALTRIGGER`
  - `REPOSITORY_URL`
  - `CLOSE`
  - `ROOT_BUILD_CAUSE`
  - `BUILD_ID`
  - `JQ_VERSION`
  - `PIP_SHIMS_BASE_MODULE`
  - `HUDSON_COOKIE`
  - `JOB_URL`
  - `JENKINS_URL`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `GIT_BRANCH`
  - `GIT_COMMIT`
  - `GIT_AUTHOR_NAME`
  - `LC_ALL`
  - `PIP_PYTHON_PATH`
  - `NLSPATH`
  - `_`
  - `BUILD_NUMBER`
  - `JOB_DISPLAY_URL`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `HOSTNAME`
  - `EXECUTOR_NUMBER`
  - `NODE_NAME`
  - `IAM_ROLE_NAME`
  - `PWD`
  - `GIT_COMMITTER_EMAIL`
  - `JENKINS_SERVER_COOKIE`
  - `BUILD_DISPLAY_NAME`
  - `BRANCH`
  - `XFILESEARCHPATH`
  - `RUN_CHANGES_DISPLAY_URL`
  - `GIT_URL`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/workspace/my-team/my-proj/task-test`

---------------------------

</details>

**Comment by rparkhunovsky** [comment]
All right, figured out the problem on the docker slave - it had package `python-virtualenv-1.10.1-3.el7.noarch` installed. Removing this before proceeding with pipenv workflow helped solve the issue. Additionally, had to search for two more issues to succed with successful installation: https://github.com/pypa/pipenv/issues/2210 and https://github.com/pypa/pipenv/pull/3386

However, for some reason, pipenv has been using the stale pip from the above package instead of the specifically upgraded `pip` package and dependencies it had installed itself so still looks like a bug.

**Comment by frostming** [comment]
The original issue has been resolved, close it now.
