### ISSUE TITLE
How to write Pipfile available for both linux and windows with file installation

### ISSUE THREAD

**Issue by tamuhey** [pypa/pipenv#3581]
I want to use same Pipfile in both windows and linux, but I wonder how to properly configure the following lines:

```
# for linux
torch = {file = "https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp37-cp37m-linux_x86_64.whl", platform_system="Linux"}
# for windows
torch = {file = "https://download.pytorch.org/whl/cpu/torch-1.0.1-cp37-cp37m-win_amd64.whl", platform_system="Windows"}
```
I wrote the lines as it is in Pipfile, but it caused an error:
```
Traceback (most recent call last):
  File "d:\work\pipenv\pipenv\project.py", line 514, in _parse_pipfile
    return tomlkit.parse(contents)
  File "d:\work\pipenv\pipenv\vendor\tomlkit\api.py", line 49, in parse
    return Parser(string).parse()
  File "d:\work\pipenv\pipenv\vendor\tomlkit\parser.py", line 146, in parse
    key, value = self._parse_table()
  File "d:\work\pipenv\pipenv\vendor\tomlkit\parser.py", line 965, in _parse_table
    values.append(_key, item)
  File "d:\work\pipenv\pipenv\vendor\tomlkit\container.py", line 139, in append
    raise KeyAlreadyPresent(key)
tomlkit.exceptions.KeyAlreadyPresent: Key "torch" already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\work\pipenv\pipenv\vendor\toml\decoder.py", line 456, in loads
    multibackslash)
  File "d:\work\pipenv\pipenv\vendor\toml\decoder.py", line 728, in load_line
    raise ValueError("Duplicate keys!")
ValueError: Duplicate keys!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tamuhey\AppData\Local\Continuum\anaconda3\envs\pipenv\Scripts\pipenv-script.py", line 11, in <module>
    load_entry_point('pipenv', 'console_scripts', 'pipenv')()
  File "d:\work\pipenv\pipenv\vendor\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "d:\work\pipenv\pipenv\vendor\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "d:\work\pipenv\pipenv\vendor\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\work\pipenv\pipenv\vendor\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\work\pipenv\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\work\pipenv\pipenv\vendor\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "d:\work\pipenv\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\work\pipenv\pipenv\vendor\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "d:\work\pipenv\pipenv\cli\command.py", line 253, in install
    editable_packages=state.installstate.editables,
  File "d:\work\pipenv\pipenv\core.py", line 1721, in do_install
    pypi_mirror=pypi_mirror,
  File "d:\work\pipenv\pipenv\core.py", line 558, in ensure_project
    if project.required_python_version:
  File "d:\work\pipenv\pipenv\project.py", line 230, in required_python_version
    required = self.parsed_pipfile.get("requires", {}).get(
  File "d:\work\pipenv\pipenv\project.py", line 496, in parsed_pipfile
    parsed = self._parse_pipfile(contents)
  File "d:\work\pipenv\pipenv\project.py", line 518, in _parse_pipfile
    return toml.loads(contents)
  File "d:\work\pipenv\pipenv\vendor\toml\decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Duplicate keys! (line 15 column 1 char 310)
```

**Comment by frostming** [comment]
@tamuhey Duplicate keys are not allowed in a TOML document. You can change the name of the second line to like `torch_win`, which doesn't affect the actual package name installed.

**Comment by ohadbenariemicro** [comment]
> [@tamuhey](https://github.com/tamuhey) Duplicate keys are not allowed in a TOML document. You can change the name of the second line to like `torch_win`, which doesn't affect the actual package name installed.

but how will the pipfile will know to install torch if the key is torch_win?
i'm getting an error "No matching distribution found for torch_macos==2.6.0" when I tried same approach with mac
