### ISSUE TITLE
Package installation failed: installing line_profiler in python 3.7.2

### ISSUE THREAD

**Issue by xujiboy** [pypa/pipenv#3622]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://docs.pipenv.org/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

I tried to install `line_profiler` with `python 3.7.2` with `pipenv`, got an `pipenv.exceptions.InstallError`

### Expected result

`line_profiler` to be successfully installed .

### Actual result
```
Creating a virtualenv for this project…
Pipfile: /Users/ji/learning/pipenv-test/Pipfile
Using /usr/local/bin/python3 (3.7.2) to create virtualenv…
⠙ Creating virtual environment...Using base prefix '/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7'
New python executable in /Users/ji/.local/share/virtualenvs/pipenv-test-LmaGW0y1/bin/python3
Also creating executable in /Users/ji/.local/share/virtualenvs/pipenv-test-LmaGW0y1/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/local/bin/python3

✔ Successfully created virtual environment!
Virtualenv location: /Users/ji/.local/share/virtualenvs/pipenv-test-LmaGW0y1
Creating a Pipfile for this project…
Installing line_profiler…
Adding line_profiler to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (2bba3b)!
Installing dependencies from Pipfile.lock (2bba3b)…
An error occurred while installing line-profiler==2.1.2 --hash=sha256:efa66e9e3045aa7cb1dd4bf0106e07dec9f80bc781a993fbaf8162a36c20af5c! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 16/16 — 00:00:03
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/usr/local/Cellar/pipenv/2018.11.26/libexec/lib/python3.7/site-packages/pipenv/core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "/usr/local/Cellar/pipenv/2018.11.26/libexec/lib/python3.7/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/usr/local/Cellar/pipenv/2018.11.26/libexec/lib/python3.7/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/usr/local/Cellar/pipenv/2018.11.26/libexec/lib/python3.7/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/usr/local/Cellar/pipenv/2018.11.26/libexec/lib/python3.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting line-profiler==2.1.2 (from -r /var/folders/6n/v3qmr4295vgfkv7y8ywlh12r0000gn/T/pipenv-c196w1am-requirements/pipenv-usgqy5f3-requirement.txt (line 1))', '  Using cached https://files.pythonhosted.org/packages/14/fc/ecf4e238bb601ff829068e5a72cd1bd67b0ee0ae379db172eb6a0779c6b6/line_profiler-2.1.2.tar.gz', 'Building wheels for collected packages: line-profiler', '  Building wheel for line-profiler (setup.py): started', "  Building wheel for line-profiler (setup.py): finished with status 'error'", '  Complete output from command /Users/ji/.local/share/virtualenvs/pipenv-test-LmaGW0y1/bin/python3 -u -c "import setuptools, tokenize;__file__=\'/private/var/folders/6n/v3qmr4295vgfkv7y8ywlh12r0000gn/T/pip-install-25cuhxns/line-profiler/setup.py\';f=getattr(tokenize, \'open\', open)(__file__);code=f.read().replace(\'\\r\\n\', \'\\n\');f.close();exec(compile(code, __file__, \'exec\'))" bdist_wheel -d /private/var/folders/6n/v3qmr4295vgfkv7y8ywlh12r0000gn/T/pip-wheel-yjux64rm --python-tag cp37:', '  Could not import Cython. Using the available pre-generated C file.', '  running bdist_wheel', '  running build', '  running build_py', '  creating build', '  creating build/lib.macosx-10.14-x86_64-3.7', '  copying line_profiler.py -> build/lib.macosx-10.14-x86_64-3.7', '  copying kernprof.py -> build/lib.macosx-10.14-x86_64-3.7', '  copying line_profiler_py35.py -> build/lib.macosx-10.14-x86_64-3.7', '  warning: build_py: byte-compiling is disabled, skipping.', '  ', '  running build_ext', "  building '_line_profiler' extension", '  creating build/temp.macosx-10.14-x86_64-3.7', '  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c _line_profiler.c -o build/temp.macosx-10.14-x86_64-3.7/_line_profiler.o', "  _line_profiler.c:7890:21: error: no member named 'exc_type' in 'struct _ts'", '      *type = tstate->exc_type;', '              ~~~~~~  ^', "  _line_profiler.c:7891:22: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?", '      *value = tstate->exc_value;', '                       ^~~~~~~~~', '                       curexc_value', "  /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here", '      PyObject *curexc_value;', '                ^', "  _line_profiler.c:7892:19: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?", '      *tb = tstate->exc_traceback;', '                    ^~~~~~~~~~~~~', '                    curexc_traceback', "  /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here", '      PyObject *curexc_traceback;', '                ^', "  _line_profiler.c:7899:24: error: no member named 'exc_type' in 'struct _ts'", '      tmp_type = tstate->exc_type;', '                 ~~~~~~  ^', "  _line_profiler.c:7900:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?", '      tmp_value = tstate->exc_value;', '                          ^~~~~~~~~', '                          curexc_value', "  /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here", '      PyObject *curexc_value;', '                ^', "  _line_profiler.c:7901:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?", '      tmp_tb = tstate->exc_traceback;', '                       ^~~~~~~~~~~~~', '                       curexc_traceback', "  /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here", '      PyObject *curexc_traceback;', '                ^', "  _line_profiler.c:7902:13: error: no member named 'exc_type' in 'struct _ts'", '      tstate->exc_type = type;', '      ~~~~~~  ^', "  _line_profiler.c:7903:13: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?", '      tstate->exc_value = value;', '              ^~~~~~~~~', '              curexc_value', "  /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here", '      PyObject *curexc_value;', '                ^', "  _line_profiler.c:7904:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?", '      tstate->exc_traceback = tb;', '              ^~~~~~~~~~~~~', '              curexc_traceback', "  /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here", '      PyObject *curexc_traceback;', '                ^', "  _line_profiler.c:7959:24: error: no member named 'exc_type' in 'struct _ts'", '      tmp_type = tstate->exc_type;', '                 ~~~~~~  ^', "  _line_profiler.c:7960:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?", '      tmp_value = tstate->exc_value;', '                          ^~~~~~~~~', '                          curexc_value', "  /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here", '      PyObject *curexc_value;', '                ^', "  _line_profiler.c:7961:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?", '      tmp_tb = tstate->exc_traceback;', '                       ^~~~~~~~~~~~~', '                       curexc_traceback', "  /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here", '      PyObject *curexc_traceback;', '                ^', "  _line_profiler.c:7962:13: error: no member named 'exc_type' in 'struct _ts'", '      tstate->exc_type = local_type;', '      ~~~~~~  ^', "  _line_profiler.c:7963:13: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?", '      tstate->exc_value = local_value;', '              ^~~~~~~~~', '              curexc_value', "  /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here", '      PyObject *curexc_value;', '                ^', "  _line_profiler.c:7964:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?", '      tstate->exc_traceback = local_tb;', '              ^~~~~~~~~~~~~', '              curexc_traceback', "  /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here", '      PyObject *curexc_traceback;', '                ^', '  15 errors generated.', "  error: command 'clang' failed with exit status 1", '  ', '  ----------------------------------------', '  Running setup.py clean for line-profiler', 'Failed to build line-profiler', 'Installing collected packages: line-profiler', '  Running setup.py install for line-profiler: started', "    Running setup.py install for line-profiler: finished with status 'error'", '    Complete output from command /Users/ji/.local/share/virtualenvs/pipenv-test-LmaGW0y1/bin/python3 -u -c "import setuptools, tokenize;__file__=\'/private/var/folders/6n/v3qmr4295vgfkv7y8ywlh12r0000gn/T/pip-install-25cuhxns/line-profiler/setup.py\';f=getattr(tokenize, \'open\', open)(__file__);code=f.read().replace(\'\\r\\n\', \'\\n\');f.close();exec(compile(code, __file__, \'exec\'))" install --record /private/var/folders/6n/v3qmr4295vgfkv7y8ywlh12r0000gn/T/pip-record-zx3nnkde/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ji/.local/share/virtualenvs/pipenv-test-LmaGW0y1/bin/../include/site/python3.7/line-profiler:', '    Could not import Cython. Using the available pre-generated C file.', '    running install', '    running build', '    running build_py', '    creating build', '    creating build/lib.macosx-10.14-x86_64-3.7', '    copying line_profiler.py -> build/lib.macosx-10.14-x86_64-3.7', '    copying kernprof.py -> build/lib.macosx-10.14-x86_64-3.7', '    copying line_profiler_py35.py -> build/lib.macosx-10.14-x86_64-3.7', '    warning: build_py: byte-compiling is disabled, skipping.', '    ', '    running build_ext', "    building '_line_profiler' extension", '    creating build/temp.macosx-10.14-x86_64-3.7', '    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c _line_profiler.c -o build/temp.macosx-10.14-x86_64-3.7/_line_profiler.o', "    _line_profiler.c:7890:21: error: no member named 'exc_type' in 'struct _ts'", '        *type = tstate->exc_type;', '                ~~~~~~  ^', "    _line_profiler.c:7891:22: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?", '        *value = tstate->exc_value;', '                         ^~~~~~~~~', '                         curexc_value', "    /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here", '        PyObject *curexc_value;', '                  ^', "    _line_profiler.c:7892:19: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?", '        *tb = tstate->exc_traceback;', '                      ^~~~~~~~~~~~~', '                      curexc_traceback', "    /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here", '        PyObject *curexc_traceback;', '                  ^', "    _line_profiler.c:7899:24: error: no member named 'exc_type' in 'struct _ts'", '        tmp_type = tstate->exc_type;', '                   ~~~~~~  ^', "    _line_profiler.c:7900:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?", '        tmp_value = tstate->exc_value;', '                            ^~~~~~~~~', '                            curexc_value', "    /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here", '        PyObject *curexc_value;', '                  ^', "    _line_profiler.c:7901:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?", '        tmp_tb = tstate->exc_traceback;', '                         ^~~~~~~~~~~~~', '                         curexc_traceback', "    /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here", '        PyObject *curexc_traceback;', '                  ^', "    _line_profiler.c:7902:13: error: no member named 'exc_type' in 'struct _ts'", '        tstate->exc_type = type;', '        ~~~~~~  ^', "    _line_profiler.c:7903:13: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?", '        tstate->exc_value = value;', '                ^~~~~~~~~', '                curexc_value', "    /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here", '        PyObject *curexc_value;', '                  ^', "    _line_profiler.c:7904:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?", '        tstate->exc_traceback = tb;', '                ^~~~~~~~~~~~~', '                curexc_traceback', "    /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here", '        PyObject *curexc_traceback;', '                  ^', "    _line_profiler.c:7959:24: error: no member named 'exc_type' in 'struct _ts'", '        tmp_type = tstate->exc_type;', '                   ~~~~~~  ^', "    _line_profiler.c:7960:25: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?", '        tmp_value = tstate->exc_value;', '                            ^~~~~~~~~', '                            curexc_value', "    /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here", '        PyObject *curexc_value;', '                  ^', "    _line_profiler.c:7961:22: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?", '        tmp_tb = tstate->exc_traceback;', '                         ^~~~~~~~~~~~~', '                         curexc_traceback', "    /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here", '        PyObject *curexc_traceback;', '                  ^', "    _line_profiler.c:7962:13: error: no member named 'exc_type' in 'struct _ts'", '        tstate->exc_type = local_type;', '        ~~~~~~  ^', "    _line_profiler.c:7963:13: error: no member named 'exc_value' in 'struct _ts'; did you mean 'curexc_value'?", '        tstate->exc_value = local_value;', '                ^~~~~~~~~', '                curexc_value', "    /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:240:15: note: 'curexc_value' declared here", '        PyObject *curexc_value;', '                  ^', "    _line_profiler.c:7964:13: error: no member named 'exc_traceback' in 'struct _ts'; did you mean 'curexc_traceback'?", '        tstate->exc_traceback = local_tb;', '                ^~~~~~~~~~~~~', '                curexc_traceback', "    /usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/pystate.h:241:15: note: 'curexc_traceback' declared here", '        PyObject *curexc_traceback;', '                  ^', '    15 errors generated.', "    error: command 'clang' failed with exit status 1", '    ', '    ----------------------------------------']
[pipenv.exceptions.InstallError]: ['Failed building wheel for line-profiler', 'Command "/Users/ji/.local/share/virtualenvs/pipenv-test-LmaGW0y1/bin/python3 -u -c "import setuptools, tokenize;__file__=\'/private/var/folders/6n/v3qmr4295vgfkv7y8ywlh12r0000gn/T/pip-install-25cuhxns/line-profiler/setup.py\';f=getattr(tokenize, \'open\', open)(__file__);code=f.read().replace(\'\\r\\n\', \'\\n\');f.close();exec(compile(code, __file__, \'exec\'))" install --record /private/var/folders/6n/v3qmr4295vgfkv7y8ywlh12r0000gn/T/pip-record-zx3nnkde/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ji/.local/share/virtualenvs/pipenv-test-LmaGW0y1/bin/../include/site/python3.7/line-profiler" failed with error code 1 in /private/var/folders/6n/v3qmr4295vgfkv7y8ywlh12r0000gn/T/pip-install-25cuhxns/line-profiler/']
ERROR: ERROR: Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:02
```

### Steps to replicate

`pipenv install --python 3.7.2 line_profiler`
-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.11.26/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.11.26/libexec/bin/python3.7'`

Python installations found:

  - `3.7.2`: `/usr/local/bin/python3`
  - `3.7.2`: `/usr/local/bin/python3.7m`
  - `3.6.1`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3`
  - `3.6.1`: `/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6m`
  - `3.4.2`: `/Library/Frameworks/Python.framework/Versions/3.4/bin/python3`
  - `3.4.2`: `/Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4m`
  - `2.7.15`: `/opt/local/bin/python2`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`
  - `2.7.9`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python`
  - `2.7.9`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.2.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST '
                     '2018; root:xnu-4903.241.1~1/RELEASE_X86_64',
 'python_full_version': '3.7.2',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `TERM_PROGRAM`
  - `NVM_CD_FLAGS`
  - `SHELL`
  - `TERM`
  - `HADOOP_HOME`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `CONDA_SHLVL`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `USER`
  - `NVM_DIR`
  - `COMMAND_MODE`
  - `CONDA_EXE`
  - `PYSPARK_PYTHON`
  - `SSH_AUTH_SOCK`
  - `PYSPARK_DRIVER_PYTHON`
  - `__CF_USER_TEXT_ENCODING`
  - `HADOOP_COMMON_LIB_NATIVE_DIR`
  - `_`
  - `PWD`
  - `JENV_LOADED`
  - `LANG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `HADOOP_OPTS`
  - `XPC_SERVICE_NAME`
  - `COLORFGBG`
  - `HOME`
  - `SHLVL`
  - `SPARK_PATH`
  - `ITERM_SESSION_ID`
  - `LOGNAME`
  - `JENV_SHELL`
  - `NVM_BIN`
  - `PYSPARK_DRIVER_PYTHON_OPTS`
  - `DISPLAY`
  - `BAT_THEME`
  - `SECURITYSESSIONID`
  - `COLORTERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2018.11.26/libexec/tools:/Users/ji/anaconda3/condabin:/Users/ji/.jenv/shims:/Users/ji/.jenv/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Users/ji/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/Users/ji/.nvm/versions/node/v10.10.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/ji/learning/pipenv-test`

---------------------------

Contents of `Pipfile` ('/Users/ji/learning/pipenv-test/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
line-profiler = "*"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/Users/ji/learning/pipenv-test/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "9142550f2694c488f2ce581f0674bdff6891ba1bdb9fe6daf07f799a992bba3b"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "appnope": {
            "hashes": [
                "sha256:5b26757dc6f79a3b7dc9fab95359328d5747fcb2409d331ea66d0272b90ab2a0",
                "sha256:8b995ffe925347a2138d7ac0fe77155e4311a0ea6d6da4f5128fe4b3cbe5ed71"
            ],
            "markers": "sys_platform == 'darwin'",
            "version": "==0.1.0"
        },
        "backcall": {
            "hashes": [
                "sha256:38ecd85be2c1e78f77fd91700c76e14667dc21e2713b63876c0eb901196e01e4",
                "sha256:bbbf4b1e5cd2bdb08f915895b51081c041bac22394fdfcfdfbe9f14b77c08bf2"
            ],
            "version": "==0.1.0"
        },
        "decorator": {
            "hashes": [
                "sha256:33cd704aea07b4c28b3eb2c97d288a06918275dac0ecebdaf1bc8a48d98adb9e",
                "sha256:cabb249f4710888a2fc0e13e9a16c343d932033718ff62e1e9bc93a9d3a9122b"
            ],
            "version": "==4.3.2"
        },
        "ipython": {
            "hashes": [
                "sha256:06de667a9e406924f97781bda22d5d76bfb39762b678762d86a466e63f65dc39",
                "sha256:5d3e020a6b5f29df037555e5c45ab1088d6a7cf3bd84f47e0ba501eeb0c3ec82"
            ],
            "version": "==7.3.0"
        },
        "ipython-genutils": {
            "hashes": [
                "sha256:72dd37233799e619666c9f639a9da83c34013a73e8bbc79a7a6348d93c61fab8",
                "sha256:eb2e116e75ecef9d4d228fdc66af54269afa26ab4463042e33785b887c628ba8"
            ],
            "version": "==0.2.0"
        },
        "jedi": {
            "hashes": [
                "sha256:2bb0603e3506f708e792c7f4ad8fc2a7a9d9c2d292a358fbbd58da531695595b",
                "sha256:2c6bcd9545c7d6440951b12b44d373479bf18123a401a52025cf98563fbd826c"
            ],
            "version": "==0.13.3"
        },
        "line-profiler": {
            "hashes": [
                "sha256:efa66e9e3045aa7cb1dd4bf0106e07dec9f80bc781a993fbaf8162a36c20af5c"
            ],
            "index": "pypi",
            "version": "==2.1.2"
        },
        "parso": {
            "hashes": [
                "sha256:4580328ae3f548b358f4901e38c0578229186835f0fa0846e47369796dd5bcc9",
                "sha256:68406ebd7eafe17f8e40e15a84b56848eccbf27d7c1feb89e93d8fca395706db"
            ],
            "version": "==0.3.4"
        },
        "pexpect": {
            "hashes": [
                "sha256:2a8e88259839571d1251d278476f3eec5db26deb73a70be5ed5dc5435e418aba",
                "sha256:3fbd41d4caf27fa4a377bfd16fef87271099463e6fa73e92a52f92dfee5d425b"
            ],
            "markers": "sys_platform != 'win32'",
            "version": "==4.6.0"
        },
        "pickleshare": {
            "hashes": [
                "sha256:87683d47965c1da65cdacaf31c8441d12b8044cdec9aca500cd78fc2c683afca",
                "sha256:9649af414d74d4df115d5d718f82acb59c9d418196b7b4290ed47a12ce62df56"
            ],
            "version": "==0.7.5"
        },
        "prompt-toolkit": {
            "hashes": [
                "sha256:11adf3389a996a6d45cc277580d0d53e8a5afd281d0c9ec71b28e6f121463780",
                "sha256:2519ad1d8038fd5fc8e770362237ad0364d16a7650fb5724af6997ed5515e3c1",
                "sha256:977c6583ae813a37dc1c2e1b715892461fcbdaa57f6fc62f33a528c4886c8f55"
            ],
            "version": "==2.0.9"
        },
        "ptyprocess": {
            "hashes": [
                "sha256:923f299cc5ad920c68f2bc0bc98b75b9f838b93b599941a6b63ddbc2476394c0",
                "sha256:d7cc528d76e76342423ca640335bd3633420dc1366f258cb31d05e865ef5ca1f"
            ],
            "version": "==0.6.0"
        },
        "pygments": {
            "hashes": [
                "sha256:5ffada19f6203563680669ee7f53b64dabbeb100eb51b61996085e99c03b284a",
                "sha256:e8218dd399a61674745138520d0d4cf2621d7e032439341bc3f647bff125818d"
            ],
            "version": "==2.3.1"
        },
        "six": {
            "hashes": [
                "sha256:3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c",
                "sha256:d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73"
            ],
            "version": "==1.12.0"
        },
        "traitlets": {
            "hashes": [
                "sha256:9c4bd2d267b7153df9152698efb1050a5d84982d3384a37b2c1f7723ba3e7835",
                "sha256:c6cb5e6f57c5a9bdaa40fa71ce7b4af30298fbab9ece9815b5d995ab6217c7d9"
            ],
            "version": "==4.3.2"
        },
        "wcwidth": {
            "hashes": [
                "sha256:3df37372226d6e63e1b1e1eda15c594bca98a22d33a23832a90998faa96bc65e",
                "sha256:f4ebe71925af7b40a864553f761ed559b43544f8f71746c2d756c7fe788ade7c"
            ],
            "version": "==0.1.7"
        }
    },
    "develop": {}
}

```
</details>

**Comment by yssource** [comment]
Is there any workaround to install line-profiler?

**Comment by fireundubh** [comment]
Stack:
```
Traceback (most recent call last):
  File "d:\dev\python\3_7_4\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\dev\python\3_7_4\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\dev\python\3_7_4\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "d:\dev\python\3_7_4\lib\site-packages\pipenv\vendor\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "d:\dev\python\3_7_4\lib\site-packages\pipenv\vendor\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "d:\dev\python\3_7_4\lib\site-packages\pipenv\vendor\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\dev\python\3_7_4\lib\site-packages\pipenv\vendor\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\dev\python\3_7_4\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\dev\python\3_7_4\lib\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "d:\dev\python\3_7_4\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\dev\python\3_7_4\lib\site-packages\pipenv\vendor\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "d:\dev\python\3_7_4\lib\site-packages\pipenv\cli\command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "d:\dev\python\3_7_4\lib\site-packages\pipenv\core.py", line 1992, in do_install
    skip_lock=skip_lock,
  File "d:\dev\python\3_7_4\lib\site-packages\pipenv\core.py", line 1253, in do_init
    pypi_mirror=pypi_mirror,
  File "d:\dev\python\3_7_4\lib\site-packages\pipenv\core.py", line 859, in do_install_dependencies
    retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
  File "d:\dev\python\3_7_4\lib\site-packages\pipenv\core.py", line 763, in batch_install
    _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
  File "d:\dev\python\3_7_4\lib\site-packages\pipenv\core.py", line 681, in _cleanup_procs
    raise exceptions.InstallError(c.dep.name, extra=err_lines)
pipenv.exceptions.InstallError: ERROR: ERROR: Package installation failed...
```

Further up the log:
```
Building wheels for collected packages: line-profiler
  Created temporary directory: C:\Users\FIREUN~1\AppData\Local\Temp\pip-wheel-q6mfxm41
  Building wheel for line-profiler (setup.py): started
  Destination directory: C:\Users\FIREUN~1\AppData\Local\Temp\pip-wheel-q6mfxm41
  Building wheel for line-profiler (setup.py): finished with status 'error'
  Running setup.py clean for line-profiler
Failed to build line-profiler
```

**Comment by matteius** [comment]
This issue is stale and not expected to be an issue on recent pipenv versions.
