### ISSUE TITLE
Running Pipenv in Dockerfile fails "Package installation failed" [/The command '/bin/sh -c pipenv install --skip-lock --system --dev' returned a non-zero code: 1]

### ISSUE THREAD

**Issue by rhewid** [pypa/pipenv#3632]
### Issue description

I am running an application with docker-compose build. If I leave out the packages azure and paramiko the installation works just fine. However as I add those dependencies to the packages, it fails with  error messages as seen below.

### Expected result

Expected pipenv in dockerfile to build and install properly.

### Actual result

```
  Building wheels for collected packages: cffi
    Created temporary directory: /tmp/pip-wheel-6v5r15g5
    Building wheel for cffi (setup.py): started
    Destination directory: /tmp/pip-wheel-6v5r15g5
    Running command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-13lwkk9h/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-6v5r15g5 --python-tag cp37
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    unable to execute 'gcc': No such file or directory
    unable to execute 'gcc': No such file or directory

        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.freenode.net.)

        Trying to continue anyway.  If you are trying to install CFFI from
        a build done in a different context, you can ignore this warning.

    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/cffi
    copying cffi/lock.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/commontypes.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/error.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/verifier.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/api.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/model.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/__init__.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/recompiler.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/cparser.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/_embedding.h -> build/lib.linux-x86_64-3.7/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.7/cffi
    warning: build_py: byte-compiling is disabled, skipping.

    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/c
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/usr/local/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.7/c/_cffi_backend.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    Building wheel for cffi (setup.py): finished with status 'error'
    Failed building wheel for cffi
    Running setup.py clean for cffi
    Running command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-13lwkk9h/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    unable to execute 'gcc': No such file or directory
    unable to execute 'gcc': No such file or directory

        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.freenode.net.)

        Trying to continue anyway.  If you are trying to install CFFI from
        a build done in a different context, you can ignore this warning.

    running clean
    removing 'build/temp.linux-x86_64-3.7' (and everything under it)
    removing 'build/lib.linux-x86_64-3.7' (and everything under it)
    'build/bdist.linux-x86_64' does not exist -- can't clean it
    'build/scripts-3.7' does not exist -- can't clean it
    removing 'build'
  Failed to build cffi
  Installing collected packages: setuptools, wheel, pycparser, cffi

    Creating /tmp/pip-build-env-k_nx8f41/overlay/bin
    changing mode of /tmp/pip-build-env-k_nx8f41/overlay/bin/easy_install to 755
    changing mode of /tmp/pip-build-env-k_nx8f41/overlay/bin/easy_install-3.7 to 755

    changing mode of /tmp/pip-build-env-k_nx8f41/overlay/bin/wheel to 755

    Created temporary directory: /tmp/pip-record-bngrs_0p
    Running setup.py install for cffi: started
      Running command /usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-13lwkk9h/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-bngrs_0p/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-k_nx8f41/overlay --compile
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      Package libffi was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libffi.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'libffi', required by 'virtual:world', not found
      unable to execute 'gcc': No such file or directory
      unable to execute 'gcc': No such file or directory

          No working compiler found, or bogus compiler options passed to
          the compiler from Python's standard "distutils" module.  See
          the error messages above.  Likely, the problem is not related
          to CFFI but generic to the setup.py of any Python package that
          tries to compile C code.  (Hints: on OS/X 10.8, for errors about
          -mno-fused-madd see http://stackoverflow.com/questions/22313407/
          Otherwise, see https://wiki.python.org/moin/CompLangPython or
          the IRC channel #python on irc.freenode.net.)

          Trying to continue anyway.  If you are trying to install CFFI from
          a build done in a different context, you can ignore this warning.

      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.7
      creating build/lib.linux-x86_64-3.7/cffi
      copying cffi/lock.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/commontypes.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/error.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/verifier.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/api.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/model.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/__init__.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/recompiler.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/cparser.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/_embedding.h -> build/lib.linux-x86_64-3.7/cffi
      copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.7/cffi
      warning: build_py: byte-compiling is disabled, skipping.

      running build_ext
      building '_cffi_backend' extension
      creating build/temp.linux-x86_64-3.7
      creating build/temp.linux-x86_64-3.7/c
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/ffi -I/usr/include/libffi -I/usr/local/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.7/c/_cffi_backend.o
      unable to execute 'gcc': No such file or directory
      error: command 'gcc' failed with exit status 1
      Running setup.py install for cffi: finished with status 'error'
  Cleaning up...
    Removing source in /tmp/pip-install-13lwkk9h/cffi
  Cleaned build tracker '/tmp/pip-req-tracker-d388m2q6'
  Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-13lwkk9h/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-bngrs_0p/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-k_nx8f41/overlay --compile" failed with error code 1 in /tmp/pip-install-13lwkk9h/cffi/
  Exception information:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
      status = self.run(options, args)
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 393, in run
      use_user_site=options.use_user_site,
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
      **kwargs
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 945, in install
      spinner=spinner,
    File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
      % (command_desc, proc.returncode, cwd))
  pip._internal.exceptions.InstallationError: Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-13lwkk9h/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-bngrs_0p/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-k_nx8f41/overlay --compile" failed with error code 1 in /tmp/pip-install-13lwkk9h/cffi/
  Installing build dependencies: finished with status 'error'
Cleaning up...
  Removing source in /tmp/pip-install-oykypp0l/cryptography
Removed cryptography from https://files.pythonhosted.org/packages/07/ca/bc827c5e55918ad223d59d299fff92f3563476c3b00d0a9157d9c0217449/cryptography-2.6.1.tar.gz#sha256=26c821cbeb683facb966045e2064303029d572a87ee69ca5a1bf54bf55f93ca6 (from azure-cosmosdb-table~=1.0->azure) from build tracker '/tmp/pip-req-tracker-d388m2q6'
Removed build tracker '/tmp/pip-req-tracker-d388m2q6'
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 349, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 125, in prep_for_dist
    "Installing build dependencies"
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/build_env.py", line 195, in install_requirements
    call_subprocess(args, show_stdout=False, spinner=spinner)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-k_nx8f41/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.python.org/simple -- setuptools>=18.5 wheel "cffi>=1.8,!=1.11.3; python_implementation != 'PyPy'"" failed with error code 1 in None
[91m  File "/usr/local/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    [0m[91mreturn callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1874, in do_install
    [0m[91mkeep_outdated=keep_outdated[0m[91m
[0m[91m  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1253, in do_init
[0m[91m    [0m[91mpypi_mirror=pypi_mirror,[0m[91m
[0m[91m  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 862, in do_install_dependencies
[0m[91m    [0m[91m_cleanup_procs(procs, False, failed_deps_queue, retry=False)[0m[91m
[0m[91m  File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[0m[91m    [0m[91mraise exceptions.InstallError(c.dep.name, extra=err_lines)[0m[91m
[0m[91mpipenv.exceptions[0m[91m.[0m[91mInstallError[0m[91m: [0m[91mERROR: ERROR: Package installation failed...[0m[91m
[0m
```

### Steps to replicate
**The docker-compose.yml** (Altough I don't think it fails because of this.)

```
version: '3.7'

services:
  web:
    build: ./
    command: gunicorn sloop.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .//:/usr/src//
      - static_volume:/usr/src//staticfiles
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=please_change_me
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:10.5-alpine
    env_file:
      - /db_env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src//staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
```

**The Dockerfile:**
```
# pull official base image
FROM python:3.7-alpine

# set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set work directory
WORKDIR /usr/src/

# install psycopg2
RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add postgresql-dev \
    && pip install psycopg2 \
    && apk del build-deps

# install dependencies
RUN pip install --upgrade pip
RUN pip install pipenv
COPY ./Pipfile /usr/src//Pipfile
RUN pip --version
RUN pipenv --version
RUN pipenv --support
RUN pipenv install --skip-lock --system --dev

# copy entrypoint.sh
COPY ./entrypoint.sh /usr/src//entrypoint.sh

# copy project
COPY . /usr/src/
/

# run entrypoint.sh
ENTRYPOINT ["/usr/src//entrypoint.sh"]
```
I also tried to set these environment variables in the Dockerfile (ENV PATH /usr/local/bin:$PATH 
ENV PYTHON_VERSION 3.7.2), but its the same errorlog.

**The Pipfile that fails**

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django= "==2.1"
gunicorn= "==19.9.0"
"psycopg2" ="*"
paramiko = "*"
azure = "*"


[dev-packages]

[requires]
python_version = "3.7"
```

**The Pipfile that works**

```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]

django= "==2.1"
gunicorn= "==19.9.0"
"psycopg2" ="*"

[dev-packages]

[requires]

python_version = "3.7"

```
**The entrypoint.sh**

```
#!/usr/bin/sh

if [ "$DATABASE" = "db" ]
then
    echo "Waiting for db postgres..."


    while ! nc -z $SQL_HOST $SQL_PORT; do
      sleep 0.1
    done

    echo "PostgreSQL started"
fi

python manage.py flush --no-input
python manage.py migrate
python manage.py collectstatic --no-input


exec "$@"

```

The Dockerfiles with the Pipfile.
docker-compose build

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/bin/python'`

Python installations found:

  - `3.7.2`: `/usr/local/bin/python`
  - `3.7.2`: `/usr/local/bin/python3.7m`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-46-generic',
 'platform_system': 'Linux',
 'platform_version': '#49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019',
 'python_full_version': '3.7.2',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `HOSTNAME`
  - `PYTHON_PIP_VERSION`
  - `SHLVL`
  - `HOME`
  - `PYTHONUNBUFFERED`
  - `GPG_KEY`
  - `PYTHONDONTWRITEBYTECODE`
  - `PATH`
  - `LANG`
  - `PYTHON_VERSION`
  - `PWD`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/usr/src/`

---------------------------

Contents of `Pipfile` ('/usr/src//Pipfile'):

```toml
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"


[packages]

django= "==2.1"
gunicorn= "==19.9.0"
"psycopg2" ="*"
azure = "*"
paramiko = "*"

[dev-packages]



[requires]

python_version = "3.7"

```

**Comment by rhewid** [comment]
I have found the fix. Azure and especially Paramiko were missing dependencies. [This post](https://github.com/geerlingguy/JJG-Ansible-Windows/issues/28#issuecomment-219316782) helped me with the Paramiko issue

Here is the Dockerfile that installs the Pipfile properly.

```
# pull official base image
FROM python:3.7-alpine

# set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set work directory
WORKDIR /usr/src/simuloop

# install psycopg2
RUN apk add --virtual .build-deps \
    gcc \
    python3-dev \
    musl-dev \
    postgresql-dev \
    openssl-dev \
    libffi-dev \
    libsodium-dev \
    build-base\
    && pip install psycopg2 && pip install pynacl && pip install cryptography --no-binary cryptography
    

# install dependencies
RUN pip install --upgrade pip
RUN pip install pipenv
COPY ./Pipfile /usr/src/simuloop/Pipfile
RUN pipenv install --skip-lock --system --dev


# copy entrypoint.sh
COPY ./entrypoint.sh /usr/src/simuloop/entrypoint.sh

# copy project
COPY . /usr/src/simuloop/

# run entrypoint.sh
ENTRYPOINT ["/usr/src/simuloop/entrypoint.sh"]
```
The new Pipfile

```
[[source]]

url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]

django= "==2.1"
gunicorn= "==19.9.0"
numpy ="*"
azure = "*"
paramiko = "*"

[dev-packages]

[requires]

python_version = "3.7"
```
