### ISSUE TITLE
Error message with tox and tox-pipenv when installing local package

### ISSUE THREAD

**Issue by stefanoborini** [pypa/pipenv#3642]
I am having problem using tox and tox-pipenv.  tox.ini is very simple

```
[tox]
envlist = py37
```

and I am able to create (and get my package installed without any problem with just `pipenv install -d`. I am unsure if the problem is with pipenv, tox, tox-pipenv, or I've made a mistake.

Thanks. 

This is the report from the logfile:

```
sbo@MacQuela18:~/Work/Projects/stefanoborini/armadillo$ pipenv run tox
GLOB sdist-make: /Users/sbo/Work/Projects/stefanoborini/armadillo/setup.py
py37 create: /Users/sbo/Work/Projects/stefanoborini/armadillo/.tox/py37
py37 installdeps: []
ERROR: invocation failed (exit code 1), logfile: /Users/sbo/Work/Projects/stefanoborini/armadillo/.tox/py37/log/py37-1.log
ERROR: actionid: py37
msg: getenv
cmdargs: '/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/bin/python3 -m pipenv install --dev'

Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…

⠋ Locking...
⠙ Locking...
⠹ Locking...
⠸ Locking...
⠼ Locking...
⠴ Locking...
⠦ Locking...
⠧ Locking...
⠇ Locking...
⠏ Locking...
⠋ Locking...
⠙ Locking...
⠹ Locking...
⠸ Locking...
⠼ Locking...
⠴ Locking...
⠦ Locking...
⠧ Locking...
⠇ Locking...
⠏ Locking...
⠋ Locking...
⠙ Locking...
⠹ Locking...
⠸ Locking...
⠼ Locking...
⠴ Locking...
⠦ Locking...
⠧ Locking...
⠇ Locking...
⠏ Locking...
⠋ Locking...
⠙ Locking...
⠹ Locking...
⠸ Locking..✔ Success! 
Locking [packages] dependencies…

⠋ Locking...
⠙ Locking...
⠹ Locking...
⠸ Locking...
⠼ Locking...
⠴ Locking...
⠦ Locking..✘ Locking Failed! 
Traceback (most recent call last):
  File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/utils.py", line 477, in actually_resolve_deps
    deps, index_lookup, markers_lookup, project, sources,
  File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/utils.py", line 224, in get_resolver_metadata
    req = Requirement.from_line(dep)
  File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1098, in from_line
    "Error parsing requirement %s -- are you sure it is installable?" % line
pipenv.vendor.requirementslib.exceptions.RequirementError: Error parsing requirement . -- are you sure it is installable?
File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/utils.py", line 477, in actually_resolve_deps
    deps, index_lookup, markers_lookup, project, sources,
  File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/utils.py", line 224, in get_resolver_metadata
    req = Requirement.from_line(dep)
  File "/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1098, in from_line
    "Error parsing requirement %s -- are you sure it is installable?" % line
pipenv.vendor.requirementslib.exceptions.RequirementError: Error parsing requirement . -- are you sure it is installable?

ERROR: could not install deps []; v = InvocationError('/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/bin/python3 -m pipenv install --dev (see /Users/sbo/Work/Projects/stefanoborini/armadillo/.tox/py37/log/py37-1.log)', 1)
____________________________________________________________________________________________________________________________________________________________________________________ summary _____________________________________________________________________________________________________________________________________________________________________________________
ERROR:   py37: could not install deps []; v = InvocationError('/Users/sbo/.local/share/virtualenvs/armadillo-4khch1dc/bin/python3 -m pipenv install --dev (see /Users/sbo/Work/Projects/stefanoborini/armadillo/.tox/py37/log/py37-1.log)', 1)
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv'`

Python location: `'/Library/Frameworks/Python.framework/Versions/3.7/bin/python3'`

Python installations found:

  - `3.7.2`: `/Library/Frameworks/Python.framework/Versions/3.7/bin/python3`
  - `3.7.2`: `/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7m`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.2.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST '
                     '2018; root:xnu-4903.241.1~1/RELEASE_X86_64',
 'python_full_version': '3.7.2',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `MKLROOT`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `LC_ALL`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `PATH`
  - `PWD`
  - `LANG`
  - `XPC_FLAGS`
  - `PS1`
  - `XPC_SERVICE_NAME`
  - `SHLVL`
  - `HOME`
  - `DYLD_LIBRARY_PATH`
  - `LOGNAME`
  - `LC_CTYPE`
  - `DISPLAY`
  - `_`
  - `OLDPWD`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Library/Frameworks/Python.framework/Versions/3.7/bin:~/bin/:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/sbo/Work/Projects/stefanoborini/armadillo`

---------------------------

Contents of `Pipfile` ('/Users/sbo/Work/Projects/stefanoborini/armadillo/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"traitlets" = "*"
"PyQt5" = "*"
armadillo = {editable = true, path = "."}

[dev-packages]
"pytest" = "*"
"flake8" = "*"
"tox" = "*"
"tox-pipenv" = "*"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/Users/sbo/Work/Projects/stefanoborini/armadillo/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "5cb84434384a79f2f9301c312a9f90c31f89afa45b2e5ef5d39602f1c77ca647"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "armadillo": {
            "editable": true,
            "path": "."
        },
        "decorator": {
            "hashes": [
                "sha256:86156361c50488b84a3f148056ea716ca587df2f0de1d34750d35c21312725de",
                "sha256:f069f3a01830ca754ba5258fde2278454a0b5b79e0d7f5c13b3b97e57d4acff6"
            ],
            "version": "==4.4.0"
        },
        "ipython-genutils": {
            "hashes": [
                "sha256:72dd37233799e619666c9f639a9da83c34013a73e8bbc79a7a6348d93c61fab8",
                "sha256:eb2e116e75ecef9d4d228fdc66af54269afa26ab4463042e33785b887c628ba8"
            ],
            "version": "==0.2.0"
        },
        "pyqt5": {
            "hashes": [
                "sha256:020e8771ad66429587d3db6cceb028be3435e2c65f417dcc8e3b3e644b6ab1d7",
                "sha256:399fd9c3b3786210d9d2a86bc73255cc03c997b454480b7c0daf3e1a09e1ab58",
                "sha256:c0565737d1d5fd40a7e14b6692bfec1f1e1f0be082ae70d1776c44561980e3c4",
                "sha256:d4e88208dfd017636e4b1f407990d0c3b6cf47afed6be4f2fb6ca887ef513e4b"
            ],
            "index": "pypi",
            "version": "==5.12.1"
        },
        "pyqt5-sip": {
            "hashes": [
                "sha256:0aed4266e52f4d11947439d9df8c57d4578e92258ad0d70645f9f69b627b35c7",
                "sha256:15750a4a3718c68ba662eede7310612aedad70c9727497908bf2eeddd255d16f",
                "sha256:2071265b7a603354b624b6cfae4ea032719e341799fb925961fd192f328fd203",
                "sha256:31a59f76168df007b480b9382256c20f8898c642e1394df2990559f0f6389f66",
                "sha256:39ce455bf5be5c1b20db10d840a536f70c3454be3baa7adca22f67ed90507853",
                "sha256:5d8a4b8e75fa6c9f837ea92793f1aeacbf3929f1d11cdf36f9604c1876182aca",
                "sha256:6bf9bacac776257390dd3f8a703d12c8228e4eb1aa0b191f1550965f44e4c23a",
                "sha256:87a76841e07e6dae5df34dded427708b5ea8d605c017e0bb6e56a7354959271e",
                "sha256:9f0ad4198f2657da9d59a393c266959362c517445cace842051e5ad564fa8fb0",
                "sha256:cbb0f24e3bfa1403bf3a05f30066d4457509aa411d6c6823d02b0508b787b8ea",
                "sha256:d38d379fa4f5c86a8ea92b8fab42748f37de093d21a25c34b2339eb2764ee5d5",
                "sha256:f24413d34707525a0fe1448b9574089242b9baa7c604ae5714abef9ad1749839"
            ],
            "version": "==4.19.15"
        },
        "six": {
            "hashes": [
                "sha256:3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c",
                "sha256:d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73"
            ],
            "version": "==1.12.0"
        },
        "traitlets": {
            "hashes": [
                "sha256:9c4bd2d267b7153df9152698efb1050a5d84982d3384a37b2c1f7723ba3e7835",
                "sha256:c6cb5e6f57c5a9bdaa40fa71ce7b4af30298fbab9ece9815b5d995ab6217c7d9"
            ],
            "index": "pypi",
            "version": "==4.3.2"
        }
    },
    "develop": {
        "atomicwrites": {
            "hashes": [
                "sha256:03472c30eb2c5d1ba9227e4c2ca66ab8287fbfbbda3888aa93dc2e28fc6811b4",
                "sha256:75a9445bac02d8d058d5e1fe689654ba5a6556a1dfd8ce6ec55a0ed79866cfa6"
            ],
            "version": "==1.3.0"
        },
        "attrs": {
            "hashes": [
                "sha256:69c0dbf2ed392de1cb5ec704444b08a5ef81680a61cb899dc08127123af36a79",
                "sha256:f0b870f674851ecbfbbbd364d6b5cbdff9dcedbc7f3f5e18a6891057f21fe399"
            ],
            "version": "==19.1.0"
        },
        "certifi": {
            "hashes": [
                "sha256:59b7658e26ca9c7339e00f8f4636cdfe59d34fa37b9b04f6f9e9926b3cece1a5",
                "sha256:b26104d6835d1f5e49452a26eb2ff87fe7090b89dfcaee5ea2212697e1e1d7ae"
            ],
            "version": "==2019.3.9"
        },
        "entrypoints": {
            "hashes": [
                "sha256:589f874b313739ad35be6e0cd7efde2a4e9b6fea91edcc34e58ecbb8dbe56d19",
                "sha256:c70dd71abe5a8c85e55e12c19bd91ccfeec11a6e99044204511f9ed547d48451"
            ],
            "version": "==0.3"
        },
        "filelock": {
            "hashes": [
                "sha256:b8d5ca5ca1c815e1574aee746650ea7301de63d87935b3463d26368b76e31633",
                "sha256:d610c1bb404daf85976d7a82eb2ada120f04671007266b708606565dd03b5be6"
            ],
            "version": "==3.0.10"
        },
        "flake8": {
            "hashes": [
                "sha256:859996073f341f2670741b51ec1e67a01da142831aa1fdc6242dbf88dffbe661",
                "sha256:a796a115208f5c03b18f332f7c11729812c8c3ded6c46319c59b53efd3819da8"
            ],
            "index": "pypi",
            "version": "==3.7.7"
        },
        "mccabe": {
            "hashes": [
                "sha256:ab8a6258860da4b6677da4bd2fe5dc2c659cff31b3ee4f7f5d64e79735b80d42",
                "sha256:dd8d182285a0fe56bace7f45b5e7d1a6ebcbf524e8f3bd87eb0f125271b8831f"
            ],
            "version": "==0.6.1"
        },
        "more-itertools": {
            "hashes": [
                "sha256:0125e8f60e9e031347105eb1682cef932f5e97d7b9a1a28d9bf00c22a5daef40",
                "sha256:590044e3942351a1bdb1de960b739ff4ce277960f2425ad4509446dbace8d9d1"
            ],
            "markers": "python_version > '2.7'",
            "version": "==6.0.0"
        },
        "pipenv": {
            "hashes": [
                "sha256:56ad5f5cb48f1e58878e14525a6e3129d4306049cb76d2f6a3e95df0d5fc6330",
                "sha256:7df8e33a2387de6f537836f48ac6fcd94eda6ed9ba3d5e3fd52e35b5bc7ff49e",
                "sha256:a673e606e8452185e9817a987572b55360f4d28b50831ef3b42ac3cab3fee846"
            ],
            "version": "==2018.11.26"
        },
        "pluggy": {
            "hashes": [
                "sha256:19ecf9ce9db2fce065a7a0586e07cfb4ac8614fe96edf628a264b1c70116cf8f",
                "sha256:84d306a647cc805219916e62aab89caa97a33a1dd8c342e87a37f91073cd4746"
            ],
            "version": "==0.9.0"
        },
        "py": {
            "hashes": [
                "sha256:64f65755aee5b381cea27766a3a147c3f15b9b6b9ac88676de66ba2ae36793fa",
                "sha256:dc639b046a6e2cff5bbe40194ad65936d6ba360b52b3c3fe1d08a82dd50b5e53"
            ],
            "version": "==1.8.0"
        },
        "pycodestyle": {
            "hashes": [
                "sha256:95a2219d12372f05704562a14ec30bc76b05a5b297b21a5dfe3f6fac3491ae56",
                "sha256:e40a936c9a450ad81df37f549d676d127b1b66000a6c500caa2b085bc0ca976c"
            ],
            "version": "==2.5.0"
        },
        "pyflakes": {
            "hashes": [
                "sha256:17dbeb2e3f4d772725c777fabc446d5634d1038f234e77343108ce445ea69ce0",
                "sha256:d976835886f8c5b31d47970ed689944a0262b5f3afa00a5a7b4dc81e5449f8a2"
            ],
            "version": "==2.1.1"
        },
        "pytest": {
            "hashes": [
                "sha256:592eaa2c33fae68c7d75aacf042efc9f77b27c08a6224a4f59beab8d9a420523",
                "sha256:ad3ad5c450284819ecde191a654c09b0ec72257a2c711b9633d677c71c9850c4"
            ],
            "index": "pypi",
            "version": "==4.3.1"
        },
        "six": {
            "hashes": [
                "sha256:3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c",
                "sha256:d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73"
            ],
            "version": "==1.12.0"
        },
        "toml": {
            "hashes": [
                "sha256:229f81c57791a41d65e399fc06bf0848bab550a9dfd5ed66df18ce5f05e73d5c",
                "sha256:235682dd292d5899d361a811df37e04a8828a5b1da3115886b73cf81ebc9100e"
            ],
            "version": "==0.10.0"
        },
        "tox": {
            "hashes": [
                "sha256:04f8f1aa05de8e76d7a266ccd14e0d665d429977cd42123bc38efa9b59964e9e",
                "sha256:25ef928babe88c71e3ed3af0c464d1160b01fca2dd1870a5bb26c2dea61a17fc"
            ],
            "index": "pypi",
            "version": "==3.7.0"
        },
        "tox-pipenv": {
            "hashes": [
                "sha256:11342d2953d5be105b9530389191002fc7f9b5a78150d94b19acf87b3ad668dc",
                "sha256:8c82aea4a64db248246d171bffc0e831773432e76e47c25c2fb9a37354e71501"
            ],
            "index": "pypi",
            "version": "==1.9.0"
        },
        "virtualenv": {
            "hashes": [
                "sha256:6aebaf4dd2568a0094225ebbca987859e369e3e5c22dc7d52e5406d504890417",
                "sha256:984d7e607b0a5d1329425dd8845bd971b957424b5ba664729fab51ab8c11bc39"
            ],
            "version": "==16.4.3"
        },
        "virtualenv-clone": {
            "hashes": [
                "sha256:217bd3f0880c9f85672c0bcc9ad9e0354ab7dfa89c2f117e63aa878b4279f5bf",
                "sha256:316c8a05432a7adb5e461709759aca18c51433ffc2c33e2e80c9e51c452d339f",
                "sha256:f2a07ed255f3abaceef8c8442512d8cdb2ba9f867e212d8a51680c7790a85033"
            ],
            "version": "==0.5.1"
        }
    }
}

```
</details>

**Comment by stefanoborini** [comment]
Additional information: the problem seems to be that /pipenv/vendor/requirementslib/utils.py:is_installable_file uses the absolute path of "." coming from the Pipfile, but it's made absolute with respect to the current created environment, so is_installable_dir will not find either the pypackage.toml or the setup.py.

```
161     lookup_path = Path(path)                                                              
162     absolute_path = "{0}".format(lookup_path.absolute())                                  
163     print("XXX", lookup_path, absolute_path)                                              
164     if lookup_path.is_dir() and is_installable_dir(absolute_path):                        
165         return True                
```

prints 
```
pipenv.vendor.requirementslib.exceptions.RequirementError: Error parsing requirement . -- are you sure it is installable?
XXX . /Users/sbo/Work/Projects/stefanoborini/armadillo/.tox/py37
```

**Comment by marcbrossaissogeti** [comment]
Same problem here

**Comment by matteius** [comment]
`tox-pipenv` hasn't been updated in some time.
