### ISSUE TITLE
pipenv --support crashes | anaconda3-5.0.1 is not a python version

### ISSUE THREAD

**Issue by yssource** [pypa/pipenv#3765]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://docs.pipenv.org/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

``` bash
pyenv versions
```

``` bash
  system
* 3.7-dev-debug (set by /home/jimmy/.pyenv/version)
  anaconda3-2018.12
  anaconda3-2018.12/envs/devel
  anaconda3-5.0.1
```

``` bash
pipenv --support
```
### Expected result

Describe what you expected.

### Actual result

``` bash
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv'`

Python location: `'/home/jimmy/.pyenv/versions/3.7-dev-debug/bin/python3.7'`

Python installations found:

Traceback (most recent call last):
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/python.py", line 112, in get_versions
    version = PythonVersion.parse(p.name)
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/python.py", line 359, in parse
    version_dict = parse_python_version(str(version))
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/utils.py", line 86, in parse_python_version
    raise InvalidPythonVersion("%s is not a python version" % version_str)
pipenv.vendor.pythonfinder.exceptions.InvalidPythonVersion: anaconda3-5.0.1 is not a python version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/cli/command.py", line 146, in cli
    get_pipenv_diagnostics()
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/help.py", line 33, in get_pipenv_diagnostics
    python_paths = finder.find_all_python_versions()
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 122, in find_all_python_versions
    python_version_dict = getattr(self.system_path, "python_version_dict")
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 54, in system_path
    ignore_unsupported=self.ignore_unsupported,
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 451, in create
    ignore_unsupported=ignore_unsupported,
  File "<attrs generated init 75e45f144e3d5510d54dd5fca6730b98fa0220a9>", line 38, in __init__
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 116, in __attrs_post_init__
    self._setup_pyenv()
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 196, in _setup_pyenv
    version_glob_path="versions/*", ignore_unsupported=self.ignore_unsupported
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/python.py", line 156, in create
    sort_function=sort_function, version_glob_path=version_glob_path)
  File "<attrs generated init df9aff62f78d11cebb5c9958de3903ddd1cf98f8>", line 17, in __init__
  File "/home/jimmy/.pyenv/versions/3.7-dev-debug/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/python.py", line 114, in get_versions
    entry = next(iter(version_path.find_all_python_versions()), None)
AttributeError: 'NoneType' object has no attribute 'find_all_python_versions'

```

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by yssource** [comment]
It seems fixed in the latest git version.
Pipenv version: `'2018.11.27.dev0'`
