### ISSUE TITLE
sre_constants.error: bad inline flags: cannot turn on global flag at position on Windows

### ISSUE THREAD

**Issue by andrewtmendoza** [pypa/pipenv#3774]
I'm trying to use pipenv on a new Windows 10 computer with a fresh instance of Python 3.7 I installed using Anaconda 2019.03 for Windows. 

I get the following error when I try to lock the Pipfile:

`pipenv lock --clear`
> Locking [dev-packages] dependencies…
Locking Failed!
Traceback (most recent call last):
  File "c:/users/anmendoza/appdata/local/continuum/anaconda3/lib/site-packages/pipenv/resolver.py", line 4, in <module>
    import logging
  File "C:\Users\anmendoza\AppData\Local\Continuum\Anaconda3\Lib\logging\__init__.py", line 28, in <module>
    from string import Template
  File "C:\Users\anmendoza\AppData\Local\Continuum\Anaconda3\Lib\string.py", line 78, in <module>
    class Template(metaclass=_TemplateMetaclass):
  File "C:\Users\anmendoza\AppData\Local\Continuum\Anaconda3\Lib\string.py", line 75, in __init__
    cls.pattern = _re.compile(pattern, cls.flags | _re.VERBOSE)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\re.py", line 233, in compile
    return _compile(pattern, flags)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 734, in _parse
    flags = _parse_flags(source, state, char)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 803, in _parse_flags
    raise source.error("bad inline flags: cannot turn on global flag", 1)
sre_constants.error: bad inline flags: cannot turn on global flag at position 92 (line 4, column 20)
File "c:/users/anmendoza/appdata/local/continuum/anaconda3/lib/site-packages/pipenv/resolver.py", line 4, in <module>
    import logging
  File "C:\Users\anmendoza\AppData\Local\Continuum\Anaconda3\Lib\logging\__init__.py", line 28, in <module>
    from string import Template
  File "C:\Users\anmendoza\AppData\Local\Continuum\Anaconda3\Lib\string.py", line 78, in <module>
    class Template(metaclass=_TemplateMetaclass):
  File "C:\Users\anmendoza\AppData\Local\Continuum\Anaconda3\Lib\string.py", line 75, in __init__
    cls.pattern = _re.compile(pattern, cls.flags | _re.VERBOSE)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\re.py", line 233, in compile
    return _compile(pattern, flags)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 734, in _parse
    flags = _parse_flags(source, state, char)
  File "C:\Users\anmendoza\.virtualenvs\best_practice_assessment_ngfw_pano-AM8Jj296\lib\sre_parse.py", line 803, in _parse_flags
    raise source.error("bad inline flags: cannot turn on global flag", 1)
sre_constants.error: bad inline flags: cannot turn on global flag at position 92 (line 4, column 20)

I am able to successfully generate the Pipfile.lock file using a Linux container on the same computer, so I'm guessing that the issue is related to Windows.

**Comment by frostming** [comment]
The error message seems related to anaconda build but not Pipenv.

Close it now.

**Comment by andrewtmendoza** [comment]
Just to close this out - I was able to resolve the issue by going into the `.virtualenvs` directory and deleting the existing environment.
