### ISSUE TITLE
docker image as build environment, cmake is not installed. 

### ISSUE THREAD

**Issue by ShaolinFu** [pypa/pipenv#3790]
When python packages that like `dlib` is added to Pipfile, if we use ```FROM kennethreitz/pipenv as build``` to build docker image, the build will first run ```+ pipenv install --deploy --system```, which always fail because cmake is required by install dlib, and cmke is not available in pipenv docker image. 

see following build logs: 
```
Sending build context to Docker daemon  7.286MB
Step 1/8 : FROM kennethreitz/pipenv as build
# Executing 3 build triggers
 ---> Running in 519bd420c710
+ pipenv install --deploy --system
Installing dependencies from Pipfile.lock (129aae)…
An error occurred while installing dlib==19.17.0 --hash=sha256:92587c81b0165e933593f505fdf099dface0d0f8ec874b1d8655fc774598911f! Will try again.
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/dist-packages/pipenv/core.py", line 1874, in do_install
[pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/dist-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/dist-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/dist-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/dist-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Looking in indexes: http://pypi.douban.com/simple', 'Collecting dlib==19.17.0 (from -r /tmp/pipenv-iz19zco2-requirements/pipenv-_zk6bzb2-requirement.txt (line 1))', '  Downloading http://pypi.doubanio.com/packages/05/57/e8a8caa3c89a27f80bc78da39c423e2553f482a3705adc619176a3a24b36/dlib-19.17.0.tar.gz (3.4MB)', 'Building wheels for collected packages: dlib', '  Building wheel for dlib (setup.py): started', "  Building wheel for dlib (setup.py): finished with status 'error'", '  Complete output from command /usr/bin/python3.7 -u -c "import setuptools, tokenize;__file__=\'/tmp/pip-install-wkssxf4i/dlib/setup.py\';f=getattr(tokenize, \'open\', open)(__file__);code=f.read().replace(\'\\r\\n\', \'\\n\');f.close();exec(compile(code, __file__, \'exec\'))" bdist_wheel -d /tmp/pip-wheel-q_ygb3e6 --python-tag cp37:', '  running bdist_wheel', '  running build', '  running build_py', "  package init file 'dlib/__init__.py' not found (or not a regular file)", '  warning: build_py: byte-compiling is disabled, skipping.', '  ', '  running build_ext', '  Traceback (most recent call last):', '    File "/tmp/pip-install-wkssxf4i/dlib/setup.py", line 120, in get_cmake_version', "      out = subprocess.check_output(['cmake', '--version'])", '    File "/usr/lib/python3.7/subprocess.py", line 389, in check_output', '      **kwargs).stdout', '    File "/usr/lib/python3.7/subprocess.py", line 466, in run', '      with Popen(*popenargs, **kwargs) as process:', '    File "/usr/lib/python3.7/subprocess.py", line 769, in __init__', '      restore_signals, start_new_session)', '    File "/usr/lib/python3.7/subprocess.py", line 1516, in _execute_child', '      raise child_exception_type(errno_num, err_msg, err_filename)', "  FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'", '  ', '  During handling of the above exception, another exception occurred:', '  ', '  Traceback (most recent call last):', '    File "<string>", line 1, in <module>', '    File "/tmp/pip-install-wkssxf4i/dlib/setup.py", line 261, in <module>', "      'Topic :: Software Development',", '    File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 145, in setup', '      return distutils.core.setup(**attrs)', '    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup', '      dist.run_commands()', '    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands', '      self.run_command(cmd)', '    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command', '      cmd_obj.run()', '    File "/usr/local/lib/python3.7/dist-packages/wheel/bdist_wheel.py", line 192, in run', "      self.run_command('build')", '    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command', '      self.distribution.run_command(command)', '    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command', '      cmd_obj.run()', '    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run', '      self.run_command(cmd_name)', '    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command', '      self.distribution.run_command(command)', '    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command', '      cmd_obj.run()', '    File "/tmp/pip-install-wkssxf4i/dlib/setup.py", line 129, in run', '      cmake_version = self.get_cmake_version()', '    File "/tmp/pip-install-wkssxf4i/dlib/setup.py", line 125, in get_cmake_version', '      "\\n*******************************************************************\\n")', '  RuntimeError:', '  *******************************************************************', '   CMake must be installed to build the following extensions: dlib', '  *******************************************************************', '  ', '  ', '  ----------------------------------------', '  Running setup.py clean for dlib', 'Failed to build dlib', 'Installing collected packages: dlib', '  Running setup.py install for dlib: started', "    Running setup.py install for dlib: finished with status 'error'", '    Complete output from command /usr/bin/python3.7 -u -c "import setuptools, tokenize;__file__=\'/tmp/pip-install-wkssxf4i/dlib/setup.py\';f=getattr(tokenize, \'open\', open)(__file__);code=f.read().replace(\'\\r\\n\', \'\\n\');f.close();exec(compile(code, __file__, \'exec\'))" install --record /tmp/pip-record-1c7gz760/install-record.txt --single-version-externally-managed --compile:', '    running install', '    running build', '    running build_py', "    package init file 'dlib/__init__.py' not found (or not a regular file)", '    warning: build_py: byte-compiling is disabled, skipping.', '    ', '    running build_ext', '    Traceback (most recent call last):', '      File "/tmp/pip-install-wkssxf4i/dlib/setup.py", line 120, in get_cmake_version', "        out = subprocess.check_output(['cmake', '--version'])", '      File "/usr/lib/python3.7/subprocess.py", line 389, in check_output', '        **kwargs).stdout', '      File "/usr/lib/python3.7/subprocess.py", line 466, in run', '        with Popen(*popenargs, **kwargs) as process:', '      File "/usr/lib/python3.7/subprocess.py", line 769, in __init__', '        restore_signals, start_new_session)', '      File "/usr/lib/python3.7/subprocess.py", line 1516, in _execute_child', '        raise child_exception_type(errno_num, err_msg, err_filename)', "    FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'", '    ', '    During handling of the above exception, another exception occurred:', '    ', '    Traceback (most recent call last):', '      File "<string>", line 1, in <module>', '      File "/tmp/pip-install-wkssxf4i/dlib/setup.py", line 261, in <module>', "        'Topic :: Software Development',", '      File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 145, in setup', '        return distutils.core.setup(**attrs)', '      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup', '        dist.run_commands()', '      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands', '        self.run_command(cmd)', '      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command', '        cmd_obj.run()', '      File "/usr/local/lib/python3.7/dist-packages/setuptools/command/install.py", line 61, in run', '        return orig.install.run(self)', '      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run', "        self.run_command('build')", '      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command', '        self.distribution.run_command(command)', '      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command', '        cmd_obj.run()', '      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run', '        self.run_command(cmd_name)', '      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command', '        self.distribution.run_command(command)', '      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command', '        cmd_obj.run()', '      File "/tmp/pip-install-wkssxf4i/dlib/setup.py", line 129, in run', '        cmake_version = self.get_cmake_version()', '      File "/tmp/pip-install-wkssxf4i/dlib/setup.py", line 125, in get_cmake_version', '        "\\n*******************************************************************\\n")', '    RuntimeError:', '    *******************************************************************', '     CMake must be installed to build the following extensions: dlib', '    *******************************************************************', '    ', '    ', '    ----------------------------------------']
[pipenv.exceptions.InstallError]: ['Failed building wheel for dlib', 'Command "/usr/bin/python3.7 -u -c "import setuptools, tokenize;__file__=\'/tmp/pip-install-wkssxf4i/dlib/setup.py\';f=getattr(tokenize, \'open\', open)(__file__);code=f.read().replace(\'\\r\\n\', \'\\n\');f.close();exec(compile(code, __file__, \'exec\'))" install --record /tmp/pip-record-1c7gz760/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-wkssxf4i/dlib/']
ERROR: ERROR: Package installation failed...
The command '/bin/sh -c set -ex && pipenv install --deploy --system' returned a non-zero code: 1
```

**Comment by frostming** [comment]
So modify the image a little to add cmake or use another image. This is not a problem.
