### ISSUE TITLE
pipenv hangs when creating virtualenv

### ISSUE THREAD

**Issue by swingingsimian** [pypa/pipenv#3792]
### Issue description

pipenv install hangs when creating a virtualenv. pyenv being used to manage python version.
Looks similar to https://github.com/pypa/pipenv/issues/3533, but I think as that fix is not yet release and is sufficiently different it warrants a new ticket.

### Expected result

pipenv should successfully create a new virtualenv

### Actual result

The process hangs at the yield spinner when trying 'to create virtualenv'. CTRL-C shows stack trace using correct version of pyenv python.

```
$ pipenv install -v
Creating a virtualenv for this project…
Pipfile: /Users/nathanjohnson/src/virtual_env_hang/Pipfile
Using /Users/nathanjohnson/.pyenv/versions/3.7.2/bin/python3 (3.7.2) to create virtualenv…
✘
['Traceback (most recent call last):\n', '  File "/Users/nathanjohnson/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/vendor/vistir/contextmanagers.py", line 150, in spinner\n    yield _spinner\n', '  File "/Users/nathanjohnson/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/vendor/vistir/misc.py", line 314, in run\n    write_to_stdout=True\n', '  File "/Users/nathanjohnson/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/vendor/vistir/misc.py", line 236, in _create_subprocess\n    c.out, c.err = c.communicate()\n', '  File "/Users/nathanjohnson/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 939, in communicate\n    stdout, stderr = self._communicate(input, endtime, timeout)\n', '  File "/Users/nathanjohnson/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1681, in _communicate\n    ready = selector.select(timeout)\n', '  File "/Users/nathanjohnson/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/selectors.py", line 415, in select\n    fd_event_list = self._selector.poll(timeout)\n', '  File "/Users/nathanjohnson/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/vendor/yaspin/signal_handlers.py", line 35, in fancy_handler\n    sys.exit(0)\n', 'SystemExit: 0\n']
/Users/nathanjohnson/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/subprocess.py:858: ResourceWarning: subprocess 62017 is still running
  ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=5 encoding='UTF-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback 
```

### Steps to replicate

This has started happening even when running in an empty directory, with global pyenv set to 3.7.2.  So I suspect it has something to do with pyenv. Not sure exactly what config change was made to trigger this. 

-------------------------------------------------------------------------------

```
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/Users/nathanjohnson/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv'`

Python location: `'/Users/nathanjohnson/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/bin/python3.7'`

Python installations found:

  - `3.7.3`: `/usr/local/bin/python3`
  - `3.7.3`: `/usr/local/bin/python3.7m`
  - `3.7.2`: `/Users/nathanjohnson/.pyenv/versions/3.7.2/bin/python3`
  - `3.7.2`: `/Users/nathanjohnson/.pyenv/versions/3.7.2/bin/python3.7m`
  - `2.7.16`: `/usr/local/bin/python`
  - `2.7.16`: `/usr/local/bin/pythonw`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT '
                     '2019; root:xnu-4903.261.4~2/RELEASE_X86_64',
 'python_full_version': '3.7.2',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `MANPATH`
  - `__GIT_PROMPT_IGNORE_STASH`
  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `SHELL`
  - `TERM`
  - `HISTSIZE`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `PYENV_VERSION`
  - `__GIT_PROMPT_SHOW_UPSTREAM`
  - `USER`
  - `HISTFILESIZE`
  - `__GIT_PROMPT_SHOW_UNTRACKED_FILES`
  - `COMMAND_MODE`
  - `SSH_AUTH_SOCK`
  - `PYENV_DIR`
  - `__CF_USER_TEXT_ENCODING`
  - `PATH`
  - `PWD`
  - `CLOUDSMITH_TOKEN`
  - `LANG`
  - `ITERM_PROFILE`
  - `PYENV_HOOK_PATH`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `COLORFGBG`
  - `HOME`
  - `SHLVL`
  - `PYENV_SHELL`
  - `GIT_BRANCH`
  - `__GIT_PROMPT_SHOW_CHANGED_FILES_COUNT`
  - `ITERM_SESSION_ID`
  - `__GIT_PROMPT_IGNORE_SUBMODULES`
  - `LOGNAME`
  - `SECURITYSESSIONID`
  - `HISTFILE`
  - `HISTTIMEFORMAT`
  - `COLORTERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:


Debug–specific environment variables:

  - `PATH`: `/Users/nathanjohnson/.pyenv/versions/3.7.2/bin:/usr/local/Cellar/pyenv/1.2.11/libexec:/Users/nathanjohnson/.pyenv/shims:/usr/local/opt/unzip/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/nathanjohnson/Library/Python/3.6/bin:/Users/nathanjohnson/Applications/Aspera CLI/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/Users/nathanjohnson/src/provided_to_grakn/tmp`


---------------------------

Contents of `Pipfile` ('/Users/nathanjohnson/src/provided_to_grakn/tmp/Pipfile'):

```toml

```

</details>
```

Pip/py env vars:

```
$ env | grep PY
PYENV_SHELL=bash

$ env | grep PIP
# None
```

OS deets:

```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.5 (18F132)
      Kernel Version: Darwin 18.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Nathan’s MacBook Pro
      User Name: Nathan Johnson (nathanjohnson)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 6 days 5:39
```

**Comment by swingingsimian** [comment]
After removing an old version of python3.7.3 from /usr/local/bin, I attempted a work around by getting pipenv/pyenv to install 3.7.3, but it hung at the same point:

```
$ pipenv --python 3.7.3
Warning: Python 3.7.3 was not found on your system…
Would you like us to install CPython 3.7.3 with pyenv? [Y/n]: Y
Installing CPython 3.7.3 with pyenv (this may take a few minutes)…
✔ Success!
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.3.tar.xz...
-> https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tar.xz
Installing Python-3.7.3...
python-build: use readline from homebrew
Installed Python-3.7.3 to /Users/nathanjohnson/.pyenv/versions/3.7.3


Creating a virtualenv for this project…
Pipfile: /Users/nathanjohnson/src/data-loader/Pipfile
Using /Users/nathanjohnson/.pyenv/versions/3.7.3/bin/python3 (3.7.3) to create virtualenv…
⠴ Creating virtual environment...

```

**Comment by swingingsimian** [comment]
The subprocess which is still running in the Traceback is:

```
/Users/nathanjohnson/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python -m virtualenv --prompt=(data-loader)  --python=/Users/nathanjohnson/.pyenv/versions/3.7.2/bin/python3 /Users/nathanjohnson/.local/share/virtualenvs/data-loader-n3mX20R9
```

If I run this manually (minus the parenthesis around the prompt value as bash complains about this) I get a bit more output:
```
$ /Users/nathanjohnson/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python -m virtualenv --prompt=data-loader  --python=/Users/nathanjohnson/.pyenv/versions/3.7.2/bin/python3 /Users/nathanjohnson/.local/share/virtualenvs/data-loader-n3mX20R9
Running virtualenv with interpreter /Users/nathanjohnson/.pyenv/versions/3.7.2/bin/python3
Using base prefix '/Users/nathanjohnson/.pyenv/versions/3.7.2/Python.framework/Versions/3.7'
New python executable in /Users/nathanjohnson/.local/share/virtualenvs/data-loader-n3mX20R9/bin/python3
Not overwriting existing python script /Users/nathanjohnson/.local/share/virtualenvs/data-loader-n3mX20R9/bin/python (you must use /Users/nathanjohnson/.local/share/virtualenvs/data-loader-n3mX20R9/bin/python3)
Installing setuptools, pip, wheel...
```

**Comment by swingingsimian** [comment]
I did some more digging on this and found it to be this underlying problem:
https://github.com/pypa/pip/issues/3245

Have got around it by setting:
`export PIP_NO_CACHE_DIR=false`
