### ISSUE TITLE
When building Docker image, I got error "Pipfile.lock is out of date"

### ISSUE THREAD

**Issue by Shintaro0920** [pypa/pipenv#3835]
pipenv, version 2018.11.26
python, 3.7.3
OS MacOS Mojave 10.14.5

When I do following this, 
□Deploying Responder — responder 1.3.0 documentation
https://python-responder.org/en/latest/deployment.html

 I got error of 
```
Sending build context to Docker daemon  122.9kB
Step 1/5 : FROM kennethreitz/pipenv
# Executing 3 build triggers
 ---> Using cache
 ---> Using cache
 ---> Running in 22bd7fa62b8e
+ pipenv install --deploy --system
Your Pipfile.lock (1b7e5d) is out of date. Expected: (501aa6).
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/usr/local/lib/python3.7/dist-packages/pipenv/core.py", line 1874, in do_install
    keep_outdated=keep_outdated
  File "/usr/local/lib/python3.7/dist-packages/pipenv/core.py", line 1192, in do_init
    raise exceptions.DeployException
  File "/usr/local/lib/python3.7/dist-packages/pipenv/exceptions.py", line 168, in __init__
    PipenvUsageError.__init__(message=fix_utf8(message), extra=extra, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'self'
The command '/bin/sh -c set -ex && pipenv install --deploy --system' returned a non-zero code: 1
```

How can I solve this?

**Comment by Shintaro0920** [comment]
I'm sorry.
I can solve by this command.
`pipenv lock `
