### ISSUE TITLE
`pipenv run` fails on Windows with non-silent "autorun" scripts

### ISSUE THREAD

**Issue by lietu** [pypa/pipenv#3838]
### Issue description

On Windows, if you have an "Autorun" script for your Command Processor configured, which is not set up to start with an `@echo off`, running commands inside the `pipenv` with `pipenv run` will fail.

### Expected result

Autorun scripts do not block running commands.

### Actual result

```
Traceback (most recent call last):
  File "c:\users\lietu\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lietu\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lietu\AppData\Local\Programs\Python\Python36-32\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "c:\users\lietu\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\lietu\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\lietu\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\lietu\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\lietu\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\lietu\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\lietu\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\lietu\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\cli\command.py", line 408, in run
    command=command, args=args, three=state.three, python=state.python, pypi_mirror=state.pypi_mirror
  File "c:\users\lietu\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\core.py", line 2328, in do_run
    do_run_nt(script)
  File "c:\users\lietu\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\core.py", line 2267, in do_run_nt
    p = _launch_windows_subprocess(script)
  File "c:\users\lietu\appdata\local\programs\python\python36-32\lib\site-packages\pipenv\core.py", line 2257, in _launch_windows_subprocess
    return subprocess.Popen([command] + script.args, **options)
  File "c:\users\lietu\appdata\local\programs\python\python36-32\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\users\lietu\appdata\local\programs\python\python36-32\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

### Steps to replicate

Open up `regedit` and set up e.g. the key `HKEY_CURRENT_USER\Software\Microsoft\Command Processor\Autorun` with a value pointing to a script, in my case `%USERPROFILE%\init.cmd`.

Set up this Autorun script with some contents that DOES NOT start with `@echo off`. In my case: 

```
DOSKEY ls=ls -haF --color=always
```

Try to run any commands via `pipenv run`. In my case this was trying to run an invoke task via the command `pipenv run invoke test`.

### Known workaround

Prefix the script with `@echo off` so making the above script be like this:

```
@echo off
DOSKEY ls=ls -haF --color=always
```

### Debugging steps

I checked the backtrace and put a `print` above the `subprocess.Popen` on core.py:2257, saw it was putting a line showing the current path + the `DOSKEY ...` -command as the `command`. Checked how `system_which` resolves it and realized it uses the first line of output instead of e.g. the last one, so when you launch a new shell to run this command with, the first line will have the first line command from the Autorun script, and likely only the second to last line will have the path to `invoke.exe` in my case.

-------------------------------------------------------------------------------

The relevant pieces of `pipenv --support` below:

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'c:\\users\\lietu\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\pipenv'`

Python location: `'c:\\users\\lietu\\appdata\\local\\programs\\python\\python36-32\\python.exe'`

Python installations found:

  - `3.6.8`: `C:\Users\lietu\AppData\Local\Programs\Python\Python36-32\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.8',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17763',
 'python_full_version': '3.6.8',
 'python_version': '3.6',
 'sys_platform': 'win32'}
```

**Comment by frostming** [comment]
The issue and the debugging steps make sense to me, would you mind send a PR for it?

**Comment by frostming** [comment]
@lietu Note that `where` command on Windows will give multiple results. That said, using the last line will change the behavior.

So I suggest you avoid using non-silent autorun scripts since it is kind of hidden feature on Windows only. What's your thought?

**Comment by lietu** [comment]
Definitely the most important part is to for now recommending avoiding of the non-silent autorun scripts, as they're causing issues.

There's two ways that I see could possibly solve this:

1. See if there's an alternative way to execute the command, that doesn't trigger the autorun scripts
2. Loop through the results and return the *first* line which is a path to an existing file - checking if it's executable should be extraneous and is kinda more difficult on Windows iirc

**Comment by matteius** [comment]
Can this be rechecked on `pipenv==2022.8.19`?
