### ISSUE TITLE
AttributeError: version

### ISSUE THREAD

**Issue by funchan24** [pypa/pipenv#3887]
an error occured while i use cmd "pipenv install yapf --dev"
python=3.7.4
pipenv=2018.11.26

(test) C:\Users\MI\Downloads\test>pipenv install yapf --dev
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "c:\users\mi\scoop\apps\python\3.7.4\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mi\scoop\apps\python\3.7.4\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\MI\scoop\apps\python\current\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "c:\users\mi\scoop\apps\python\3.7.4\lib\site-packages\pipenv\vendor\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\mi\scoop\apps\python\3.7.4\lib\site-packages\pipenv\vendor\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\mi\scoop\apps\python\3.7.4\lib\site-packages\pipenv\vendor\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\mi\scoop\apps\python\3.7.4\lib\site-packages\pipenv\vendor\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\mi\scoop\apps\python\3.7.4\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\mi\scoop\apps\python\3.7.4\lib\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\mi\scoop\apps\python\3.7.4\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\mi\scoop\apps\python\3.7.4\lib\site-packages\pipenv\vendor\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\mi\scoop\apps\python\3.7.4\lib\site-packages\pipenv\cli\command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "c:\users\mi\scoop\apps\python\3.7.4\lib\site-packages\pipenv\core.py", line 1741, in do_install
  File "c:\users\mi\scoop\apps\python\3.7.4\lib\site-packages\pipenv\vendor\pythonfinder\models\windows.py", line 92, in get_versions
    py_version = PythonVersion.from_windows_launcher(version_object)
  File "c:\users\mi\scoop\apps\python\3.7.4\lib\site-packages\pipenv\vendor\pythonfinder\models\python.py", line 417, in from_windows_launcher
    creation_dict = cls.parse(launcher_entry.info.version)
  File "c:\users\mi\scoop\apps\python\3.7.4\lib\site-packages\pipenv\vendor\pythonfinder\_vendor\pep514tools\_registry.py", line 75, in __getattr__
    raise AttributeError(attr)
AttributeError: version

**Comment by frostming** [comment]
Similar to #3764 , please try the solution in the ticket.

**Comment by funchan24** [comment]
> Similar to #3764 , please try the solution in the ticket.

Thank you, everything is ok now!
