### ISSUE TITLE
Cant install editable package in conjunction with other packages

### ISSUE THREAD

**Issue by mbhall88** [pypa/pipenv#3891]
### Issue description

When trying to install from my `Pipfile` (see below) it seems to be struggling to install the editable for the package.

If I remove the line `snpit = {editable = true,path = "."}` and run `pipenv install --dev` followed by `pipenv install -e .` it works fine. But trying to do it all in the one go with the editable `snpit` package seems to cause the error.

### Expected result

Everything installs and I have access to my package inside the pipenv environment.

### Actual result

```
$ pipenv install --verbose --dev
Creating a virtualenv for this project…
Pipfile: /home/michael/Downloads/tmp/snpit/Pipfile
Using /home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/bin/python3.7 (3.7.3) to create virtualenv…
⠴ Creating virtual environment...Already using interpreter /home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/bin/python3.7
Using real prefix '/home/linuxbrew/.linuxbrew/Cellar/python/3.7.3'
New python executable in /home/michael/.local/share/virtualenvs/snpit-qNOLdjLl/bin/python3.7
Also creating executable in /home/michael/.local/share/virtualenvs/snpit-qNOLdjLl/bin/python
Installing setuptools, pip, wheel...
done.

✔ Successfully created virtual environment! 
Virtualenv location: /home/michael/.local/share/virtualenvs/snpit-qNOLdjLl
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
✔ Success! 
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  black>=19.3b0
  coverage>=4.5.3
  pytest>=5.0

Finding the best candidates:
  found candidate black==19.3b0 (constraint was >=19.3b0)
  found candidate coverage==5.0a6 (constraint was >=4.5.3)
  found candidate pytest==5.0.1 (constraint was >=5.0)

Finding secondary dependencies:
  coverage==5.0a6 not in cache, need to check index
  coverage==5.0a6           requires -
  pytest==5.0.1 not in cache, need to check index
  pytest==5.0.1             requires atomicwrites>=1.0, attrs>=17.4.0, importlib-metadata>=0.12, more-itertools>=4.0.0, packaging, pluggy<1.0,>=0.12, py>=1.5.0, wcwidth
  black==19.3b0 not in cache, need to check index
  black==19.3b0             requires appdirs, attrs>=18.1.0, click>=6.5, toml>=0.9.4

New dependencies found in this round:
  adding ['appdirs', '', '[]']
  adding ['atomicwrites', '>=1.0', '[]']
  adding ['attrs', '>=17.4.0,>=18.1.0', '[]']
  adding ['click', '>=6.5', '[]']
  adding ['importlib-metadata', '>=0.12', '[]']
  adding ['more-itertools', '>=4.0.0', '[]']
  adding ['packaging', '', '[]']
  adding ['pluggy', '<1.0,>=0.12', '[]']
  adding ['py', '>=1.5.0', '[]']
  adding ['toml', '>=0.9.4', '[]']
  adding ['wcwidth', '', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  appdirs
  atomicwrites>=1.0
  attrs>=17.4.0,>=18.1.0
  black>=19.3b0
  click>=6.5
  coverage>=4.5.3
  importlib-metadata>=0.12
  more-itertools>=4.0.0
  packaging
  pluggy<1.0,>=0.12
  py>=1.5.0
  pytest>=5.0
  toml>=0.9.4
  wcwidth

Finding the best candidates:
  found candidate appdirs==1.4.3 (constraint was <any>)
  found candidate atomicwrites==1.3.0 (constraint was >=1.0)
  found candidate attrs==19.1.0 (constraint was >=17.4.0,>=18.1.0)
  found candidate black==19.3b0 (constraint was >=19.3b0)
  found candidate click==7.0 (constraint was >=6.5)
  found candidate coverage==5.0a6 (constraint was >=4.5.3)
  found candidate importlib-metadata==0.19 (constraint was >=0.12)
  found candidate more-itertools==7.2.0 (constraint was >=4.0.0)
  found candidate packaging==19.1 (constraint was <any>)
  found candidate pluggy==0.12.0 (constraint was >=0.12,<1.0)
  found candidate py==1.8.0 (constraint was >=1.5.0)
  found candidate pytest==5.0.1 (constraint was >=5.0)
  found candidate toml==0.10.0 (constraint was >=0.9.4)
  found candidate wcwidth==0.1.7 (constraint was <any>)

Finding secondary dependencies:
  coverage==5.0a6           requires -
  wcwidth==0.1.7 not in cache, need to check index
  wcwidth==0.1.7            requires -
  more-itertools==7.2.0 not in cache, need to check index
  more-itertools==7.2.0     requires -
  pluggy==0.12.0 not in cache, need to check index
  pluggy==0.12.0            requires importlib-metadata>=0.12
  importlib-metadata==0.19 not in cache, need to check index
  importlib-metadata==0.19  requires zipp>=0.5
  py==1.8.0 not in cache, need to check index
  py==1.8.0                 requires -
  click==7.0 not in cache, need to check index
  click==7.0                requires -
  atomicwrites==1.3.0 not in cache, need to check index
  atomicwrites==1.3.0       requires -
  black==19.3b0             requires appdirs, attrs>=18.1.0, click>=6.5, toml>=0.9.4
  pytest==5.0.1             requires atomicwrites>=1.0, attrs>=17.4.0, importlib-metadata>=0.12, more-itertools>=4.0.0, packaging, pluggy<1.0,>=0.12, py>=1.5.0, wcwidth
  packaging==19.1 not in cache, need to check index
  packaging==19.1           requires attrs, pyparsing>=2.0.2, six
  attrs==19.1.0 not in cache, need to check index
  attrs==19.1.0             requires -
  appdirs==1.4.3 not in cache, need to check index
  appdirs==1.4.3            requires -
  toml==0.10.0 not in cache, need to check index
  toml==0.10.0              requires -

New dependencies found in this round:
  adding ['pyparsing', '>=2.0.2', '[]']
  adding ['six', '', '[]']
  adding ['zipp', '>=0.5', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 2: not stable

                          ROUND 3                           
Current constraints:
  appdirs
  atomicwrites>=1.0
  attrs>=17.4.0,>=18.1.0
  black>=19.3b0
  click>=6.5
  coverage>=4.5.3
  importlib-metadata>=0.12
  more-itertools>=4.0.0
  packaging
  pluggy<1.0,>=0.12
  py>=1.5.0
  pyparsing>=2.0.2
  pytest>=5.0
  six
  toml>=0.9.4
  wcwidth
  zipp>=0.5

Finding the best candidates:
  found candidate appdirs==1.4.3 (constraint was <any>)
  found candidate atomicwrites==1.3.0 (constraint was >=1.0)
  found candidate attrs==19.1.0 (constraint was >=17.4.0,>=18.1.0)
  found candidate black==19.3b0 (constraint was >=19.3b0)
  found candidate click==7.0 (constraint was >=6.5)
  found candidate coverage==5.0a6 (constraint was >=4.5.3)
  found candidate importlib-metadata==0.19 (constraint was >=0.12)
  found candidate more-itertools==7.2.0 (constraint was >=4.0.0)
  found candidate packaging==19.1 (constraint was <any>)
  found candidate pluggy==0.12.0 (constraint was >=0.12,<1.0)
  found candidate py==1.8.0 (constraint was >=1.5.0)
  found candidate pyparsing==2.4.2 (constraint was >=2.0.2)
  found candidate pytest==5.0.1 (constraint was >=5.0)
  found candidate six==1.12.0 (constraint was <any>)
  found candidate toml==0.10.0 (constraint was >=0.9.4)
  found candidate wcwidth==0.1.7 (constraint was <any>)
  found candidate zipp==0.5.2 (constraint was >=0.5)

Finding secondary dependencies:
  six==1.12.0 not in cache, need to check index
  six==1.12.0               requires -
  more-itertools==7.2.0     requires -
  toml==0.10.0              requires -
  attrs==19.1.0             requires -
  atomicwrites==1.3.0       requires -
  click==7.0                requires -
  black==19.3b0             requires appdirs, attrs>=18.1.0, click>=6.5, toml>=0.9.4
  coverage==5.0a6           requires -
  importlib-metadata==0.19  requires zipp>=0.5
  pyparsing==2.4.2 not in cache, need to check index
  pyparsing==2.4.2          requires -
  py==1.8.0                 requires -
  wcwidth==0.1.7            requires -
  packaging==19.1           requires attrs, pyparsing>=2.0.2, six
  pytest==5.0.1             requires atomicwrites>=1.0, attrs>=17.4.0, importlib-metadata>=0.12, more-itertools>=4.0.0, packaging, pluggy<1.0,>=0.12, py>=1.5.0, wcwidth
  appdirs==1.4.3            requires -
  zipp==0.5.2 not in cache, need to check index
  zipp==0.5.2               requires -
  pluggy==0.12.0            requires importlib-metadata>=0.12
------------------------------------------------------------
Result of round 3: stable, done


Locking [packages] dependencies…
✘ Locking Failed! 
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  file:///home/michael/Downloads/tmp/snpit (from -r /tmp/pipenvvtjf1v9vrequirements/pipenv-c7xg5up_-constraints.txt (line 3))
  pysam==0.15.2

Finding the best candidates:
  found candidate -e file:///home/michael/Downloads/tmp/snpit (constraint was <any>)
  found candidate pysam==0.15.2 (constraint was ==0.15.2)

Finding secondary dependencies:
  pysam==0.15.2             requires -
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 280, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 197, in _get_abstract_dist_for
    req, self.require_hashes, self.use_user_site, self.finder,
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 321, in prepare_editable_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /home/michael/Downloads/tmp/snpit/
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  file:///home/michael/Downloads/tmp/snpit (from -r /tmp/pipenvvtjf1v9vrequirements/pipenv-c7xg5up_-constraints.txt (line 3))
  pysam==0.15.2

Finding the best candidates:
  found candidate -e file:///home/michael/Downloads/tmp/snpit (constraint was <any>)
  found candidate pysam==0.15.2 (constraint was ==0.15.2)

Finding secondary dependencies:
  pysam==0.15.2             requires -
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 280, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 197, in _get_abstract_dist_for
    req, self.require_hashes, self.use_user_site, self.finder,
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 321, in prepare_editable_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /home/michael/Downloads/tmp/snpit/
```

### Steps to replicate

I am trying to install [this package](https://github.com/mbhall88/snpit) locally.

```sh
git clone https://github.com/mbhall88/snpit.git
cd snpit
make install  
# runs `pipenv install --dev` plus some cleaning
```

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/bin/python3.7'`

Python installations found:

  - `3.7.3`: `/home/linuxbrew/.linuxbrew/bin/python3.7`
  - `3.7.3`: `/home/linuxbrew/.linuxbrew/bin/python3.7m`
  - `3.6.8`: `/usr/bin/python3.6`
  - `3.6.8`: `/usr/bin/python3.6m`
  - `2.7.15`: `/usr/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-1045-oem',
 'platform_system': 'Linux',
 'platform_version': '#50-Ubuntu SMP Wed Jun 26 11:16:36 UTC 2019',
 'python_full_version': '3.7.3',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `PATH`
  - `GREP_COLOR`
  - `CLUTTER_IM_MODULE`
  - `LS_COLORS`
  - `LC_MEASUREMENT`
  - `LC_PAPER`
  - `LC_MONETARY`
  - `XDG_MENU_PREFIX`
  - `_`
  - `LANG`
  - `LESS`
  - `DISPLAY`
  - `OLDPWD`
  - `GNOME_SHELL_SESSION_MODE`
  - `EDITOR`
  - `COLORTERM`
  - `USERNAME`
  - `CHROME_DESKTOP`
  - `NO_AT_BRIDGE`
  - `XDG_VTNR`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `ZSH`
  - `SSH_AUTH_SOCK`
  - `MANDATORY_PATH`
  - `LC_NAME`
  - `XDG_SESSION_ID`
  - `USER`
  - `PAGER`
  - `LSCOLORS`
  - `DESKTOP_SESSION`
  - `QT4_IM_MODULE`
  - `TEXTDOMAINDIR`
  - `DEFAULTS_PATH`
  - `PWD`
  - `HOME`
  - `LC_CTYPE`
  - `TEXTDOMAIN`
  - `SSH_AGENT_PID`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `QT_ACCESSIBILITY`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `XDG_SESSION_DESKTOP`
  - `LC_ADDRESS`
  - `GJS_DEBUG_OUTPUT`
  - `LC_NUMERIC`
  - `HOMEBREW_REPOSITORY`
  - `GTK_MODULES`
  - `PAPERSIZE`
  - `VISUAL`
  - `WINDOWPATH`
  - `TERM`
  - `SHELL`
  - `QT_IM_MODULE`
  - `XMODIFIERS`
  - `IM_CONFIG_PHASE`
  - `XDG_CURRENT_DESKTOP`
  - `GPG_AGENT_INFO`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `SHLVL`
  - `XDG_SEAT`
  - `HOMEBREW_PREFIX`
  - `MANPATH`
  - `LC_TELEPHONE`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `XAUTHORITY`
  - `XDG_CONFIG_DIRS`
  - `LC_IDENTIFICATION`
  - `HOMEBREW_CELLAR`
  - `INFOPATH`
  - `GJS_DEBUG_TOPICS`
  - `DESKTOP_MODE`
  - `SESSION_MANAGER`
  - `GTK_IM_MODULE`
  - `LC_TIME`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_2/libexec/tools:/home/michael/.cargo/bin:/home/michael/.cargo/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/home/linuxbrew/.linuxbrew/bin/zsh`
  - `EDITOR`: `vim`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/home/michael/Downloads/tmp/snpit`

---------------------------

Contents of `Pipfile` ('/home/michael/Downloads/tmp/snpit/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
coverage = ">=4.5.3"
black = ">=19.3b0"
pytest = ">=5.0"

[packages]
pysam = "==0.15.2"
snpit = {editable = true,path = "."}

[pipenv]
allow_prereleases = true

```

</details>

**Comment by HackiLee** [comment]
哦

**Comment by barucAlmaguer** [comment]
I'm having this same issue 
`pipenv install --dev` fails, if I remove my local dependency, it works fine, then I install the local dependency afterwards:
```
pipenv install --dev # fails
```

when I change my Pipfile it works fine:
## From this
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
pygqlc = "*"
inflect = "*"
pydash = "*"
click = "*"
valiotworker = "*"
pytz = "*"
tzlocal = "*"
attrs = ">=19.0.0"

[dev-packages]
pytest = "*"
pytest-cov = "*"
black = "*"
twine = "*"
pylint = "*"
gstorm = {editable = true,path = "."}

[requires]
python_version = "3.7"

[pipenv]
allow_prereleases = true
```

## to this:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
pygqlc = "*"
inflect = "*"
pydash = "*"
click = "*"
valiotworker = "*"
pytz = "*"
tzlocal = "*"
attrs = ">=19.0.0"

[dev-packages]
pytest = "*"
pytest-cov = "*"
black = "*"
twine = "*"
pylint = "*"

[requires]
python_version = "3.7"

[pipenv]
allow_prereleases = true

```

**Comment by techalchemy** [comment]
Thanks for the report and sorry for the trouble -- can you confirm whether this is an issue if you install the latest pre-release of pipenv via `pip install --upgrade --pre pipenv`?

**Comment by mbhall88** [comment]
Sorry @techalchemy but I will have to let you debug this with @barucAlmaguer as I no longer use `pipenv` and the project I raised the issue with no longer uses it. Feel free to close the issue if you don't get any responses.

**Comment by matteius** [comment]
I believe this is resolvable now -- but let me know if its still an issue on `pipenv==2022.8.19`
