### ISSUE TITLE
Failed to create virtual environment with file csv.py present

### ISSUE THREAD

**Issue by Althoefer** [pypa/pipenv#3897]
### Issue description

Pipenv fails to create an environment when there is a file named _csv.py_ in the project root.
When I change the filename to something else (e.G abc.py) everything works just fine.
I tested the issue on the following devices and operating systems:

| Device | OS | Python / Pip installation |
|---|---|---|
| MacBook Mini | MacOS 10.14.6 | Anaconda |
| MacBook Pro | MacOS 10.14.6 | MacPorts |
| MacMini | MacOS 10.13.6 | MacPorts |
| Workstation | CentOS 7.6.1810 | yum |

I assume Pipenv tries to read/execute _csv.py_, because after I added a line with a syntax error I got this as part of the output:
```
  File "/Users/althoefer/project/csv.py", line 6
    print "some stuff"
                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("some stuff")?
----------------------------------------
...Installing setuptools, pip, wheel...done.
```

### Expected result

A new virtual environment with the requested package installed and a Pipfile in the current directory.

### Actual result

The installation fails, a 0-byte Pipfile is created.

```
Creating a virtualenv for this project…
Pipfile: /Users/althoefer/project/Pipfile
Using /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 (3.7.3) to create virtualenv…
⠏ Creating virtual environment...Already using interpreter /opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
Using base prefix '/opt/local/Library/Frameworks/Python.framework/Versions/3.7'
New python executable in /Users/althoefer/.local/share/virtualenvs/project-niLaHpIj/bin/python3.7
Also creating executable in /Users/althoefer/.local/share/virtualenvs/project-niLaHpIj/bin/python
Installing setuptools, pip, wheel...

  Complete output from command /Users/althoefer/.local...LaHpIj/bin/python3.7 - setuptools pip wheel:
  Created temporary directory: /private/var/folders/hq/psmsyk_12k10jxj1vc5_wl_r0000gn/T/pip-ephem-wheel-cache-6uf4oc5z
Created temporary directory: /private/var/folders/hq/psmsyk_12k10jxj1vc5_wl_r0000gn/T/pip-req-tracker-xh0k4z79
Created requirements tracker '/private/var/folders/hq/psmsyk_12k10jxj1vc5_wl_r0000gn/T/pip-req-tracker-xh0k4z79'
Created temporary directory: /private/var/folders/hq/psmsyk_12k10jxj1vc5_wl_r0000gn/T/pip-install-bkv9c4_k
Looking in links: /Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support
Collecting setuptools
  1 location(s) to search for versions of setuptools:
  * https://pypi.org/simple/setuptools/
  Skipping link /Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support (from -f); not a file
  Getting page https://pypi.org/simple/setuptools/
  Looking up "https://pypi.org/simple/setuptools/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/setuptools/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/setuptools/
    Skipping link https://files.pythonhosted.org/packages/77/38/90cae8fd99c5dc402d25930e1c91f5fcf6de5c8e982fd152a5a061e3df56/setuptools-0.6b1-py2.3.egg#sha256=ae0a6ec6090a92d08fe7f3dbf9f1b2ce889bce2a3d7724b62322a29b92cf93f0 (from https://pypi.org/simple/setuptools/); unsupported archive format: .egg

[ repeated hundreds of times ]

Skipping link https://files.pythonhosted.org/packages/ed/69/c805067de1feedbb98c53174b0f2df44cc05e0e9ee73bb85eebc59e508c6/setuptools-41.0.0.zip#sha256=79d30254b6fe7a8e672e43cd85f13a9f3f2a50080bc81d851143e2219ef0dcb1 (from https://pypi.org/simple/setuptools/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*); No sources permitted for setuptools
    Found link https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl#sha256=c7769ce668c7a333d84e17fe8b524b1c45e7ee9f7908ad0a73e1eda7e6a5aebf (from https://pypi.org/simple/setuptools/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*), version: 41.0.1
    Skipping link https://files.pythonhosted.org/packages/1d/64/a18a487b4391a05b9c7f938b94a16d80305bf0369c6b0b9509e86165e1d3/setuptools-41.0.1.zip#sha256=a222d126f5471598053c9a77f4b5d4f26eaa1f150ad6e01dcf1a42e185d05613 (from https://pypi.org/simple/setuptools/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*); No sources permitted for setuptools
  Found link file:///Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/setuptools-41.0.1-py2.py3-none-any.whl, version: 41.0.1
  Skipping link file:///Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/wheel-0.33.4-py2.py3-none-any.whl; wrong project name (not setuptools)
  Skipping link file:///Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/__init__.py; unsupported archive format: .py
  Skipping link file:///Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/__pycache__; not a file
  Skipping link file:///Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl; wrong project name (not setuptools)
  Skipping link file:///Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/pip-19.2.1-py2.py3-none-any.whl; wrong project name (not setuptools)
  Local files found: /Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/setuptools-41.0.1-py2.py3-none-any.whl
  Using version 41.0.1 (newest of versions: 0.9.8, 1.1.6, 1.2, 1.3, 1.3.1, 1.3.2, 1.4, 1.4.1, 1.4.2, 2.0, 2.0.1, 2.0.2, 2.1, 2.1.2, 2.2, 3.1, 3.2, 3.3, 3.4, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.5, 3.5.1, 3.5.2, 3.6, 3.7, 3.7.1, 3.8, 3.8.1, 5.0, 5.0.1, 5.0.2, 5.1, 5.2, 5.3, 5.4, 5.4.1, 5.4.2, 5.5, 5.5.1, 5.6, 5.7, 5.8, 6.0.1, 6.0.2, 6.1, 7.0, 8.0, 8.0.1, 8.0.2, 8.0.3, 8.0.4, 8.1, 8.2, 8.2.1, 8.3, 9.0, 9.0.1, 9.1, 10.0, 10.0.1, 10.1, 10.2, 10.2.1, 11.0, 11.1, 11.2, 11.3, 11.3.1, 12.0, 12.0.1, 12.0.2, 12.0.3, 12.0.4, 12.0.5, 12.1, 12.2, 12.3, 12.4, 13.0.1, 13.0.2, 14.0, 14.1, 14.1.1, 14.2, 14.3, 14.3.1, 15.0, 15.1, 15.2, 16.0, 17.0, 17.1, 17.1.1, 18.0, 18.0.1, 18.1, 18.2, 18.3, 18.3.1, 18.3.2, 18.4, 18.5, 18.6, 18.6.1, 18.7, 18.7.1, 18.8, 18.8.1, 19.0, 19.1, 19.1.1, 19.2, 19.3, 19.4, 19.4.1, 19.5, 19.6, 19.6.1, 19.6.2, 19.7, 20.0, 20.1, 20.1.1, 20.2.2, 20.3, 20.3.1, 20.4, 20.6.6, 20.6.7, 20.6.8, 20.7.0, 20.8.0, 20.8.1, 20.9.0, 20.10.1, 21.0.0, 21.1.0, 21.2.0, 21.2.1, 21.2.2, 22.0.0, 22.0.1, 22.0.2, 22.0.4, 22.0.5, 23.0.0, 23.1.0, 23.2.0, 23.2.1, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 24.1.0, 24.1.1, 24.2.0, 24.2.1, 24.3.0, 24.3.1, 25.0.0, 25.0.1, 25.0.2, 25.1.0, 25.1.1, 25.1.2, 25.1.3, 25.1.4, 25.1.5, 25.1.6, 25.2.0, 25.3.0, 25.4.0, 26.0.0, 26.1.0, 26.1.1, 27.0.0, 27.1.0, 27.1.2, 27.2.0, 27.3.0, 27.3.1, 28.0.0, 28.1.0, 28.2.0, 28.3.0, 28.4.0, 28.5.0, 28.6.0, 28.6.1, 28.7.0, 28.7.1, 28.8.0, 28.8.1, 29.0.0, 29.0.1, 30.0.0, 30.1.0, 30.2.0, 30.2.1, 30.3.0, 30.4.0, 31.0.0, 31.0.1, 32.0.0, 32.1.0, 32.1.1, 32.1.2, 32.1.3, 32.2.0, 32.3.0, 32.3.1, 33.1.0, 33.1.1, 34.0.0, 34.0.1, 34.0.2, 34.0.3, 34.1.0, 34.1.1, 34.2.0, 34.3.0, 34.3.1, 34.3.2, 34.3.3, 34.4.0, 34.4.1, 35.0.0, 35.0.1, 35.0.2, 36.0.1, 36.1.0, 36.1.1, 36.2.0, 36.2.1, 36.2.2, 36.2.3, 36.2.4, 36.2.5, 36.2.6, 36.2.7, 36.3.0, 36.4.0, 36.5.0, 36.6.0, 36.6.1, 36.7.0, 36.7.1, 36.7.2, 36.8.0, 37.0.0, 38.0.0, 38.1.0, 38.2.0, 38.2.1, 38.2.3, 38.2.4, 38.2.5, 38.3.0, 38.4.0, 38.4.1, 38.5.0, 38.5.1, 38.5.2, 38.6.0, 38.6.1, 38.7.0, 39.0.0, 39.0.1, 39.1.0, 39.2.0, 40.0.0, 40.1.0, 40.1.1, 40.2.0, 40.3.0, 40.4.0, 40.4.1, 40.4.2, 40.4.3, 40.5.0, 40.6.0, 40.6.1, 40.6.2, 40.6.3, 40.7.0, 40.7.1, 40.7.2, 40.7.3, 40.8.0, 40.9.0, 41.0.0, 41.0.1)
  Added setuptools from file:///Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/setuptools-41.0.1-py2.py3-none-any.whl to build tracker '/private/var/folders/hq/psmsyk_12k10jxj1vc5_wl_r0000gn/T/pip-req-tracker-xh0k4z79'
  Removed setuptools from file:///Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/setuptools-41.0.1-py2.py3-none-any.whl from build tracker '/private/var/folders/hq/psmsyk_12k10jxj1vc5_wl_r0000gn/T/pip-req-tracker-xh0k4z79'
Collecting pip
  1 location(s) to search for versions of pip:
  * https://pypi.org/simple/pip/
  Getting page https://pypi.org/simple/pip/
  Looking up "https://pypi.org/simple/pip/" in the cache
  Request header has "max_age" as 0, cache bypassed
  https://pypi.org:443 "GET /simple/pip/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/pip/
    Skipping link https://files.pythonhosted.org/packages/3d/9d/1e313763bdfb6a48977b65829c6ce2a43eaae29ea2f907c8bbef024a7219/pip-0.2.tar.gz#sha256=88bb8d029e1bf4acd0e04d300104b7440086f94cc1ce1c5c3c31e3293aee1f81 (from https://pypi.org/simple/pip/); No sources permitted for pip
    Skipping link https://files.pythonhosted.org/packages/18/ad/c0fe6cdfe1643a19ef027c7168572dac6283b80a384ddf21b75b921877da/pip-0.2.1.tar.gz#sha256=83522005c1266cc2de97e65072ff7554ac0f30ad369c3b02ff3a764b962048da (from https://pypi.org/simple/pip/); No sources permitted for pip
Skipping link https://files.pythonhosted.org/packages/1d/b0/f478e80aeace42fe251225a86752799174a94314c4a80ebfc5bf0ab1153a/wheel-0.33.4.tar.gz#sha256=62fcfa03d45b5b722539ccbc07b190e4bfff4bb9e3a4d470dd9f6a0981002565 (from https://pypi.org/simple/wheel/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*); No sources permitted for wheel
  Found link file:///Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/wheel-0.33.4-py2.py3-none-any.whl, version: 0.33.4
  Local files found: /Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/wheel-0.33.4-py2.py3-none-any.whl
  Using version 0.33.4 (newest of versions: 0.9, 0.9.5, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.18.0, 0.19.0, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.26.0, 0.27.0, 0.28.0, 0.29.0, 0.30.0, 0.31.0, 0.31.1, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.33.4)
  Added wheel from file:///Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/wheel-0.33.4-py2.py3-none-any.whl to build tracker '/private/var/folders/hq/psmsyk_12k10jxj1vc5_wl_r0000gn/T/pip-req-tracker-xh0k4z79'
  Removed wheel from file:///Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/wheel-0.33.4-py2.py3-none-any.whl from build tracker '/private/var/folders/hq/psmsyk_12k10jxj1vc5_wl_r0000gn/T/pip-req-tracker-xh0k4z79'
Installing collected packages: setuptools, pip, wheel

  changing mode of /Users/althoefer/.local/share/virtualenvs/project-niLaHpIj/bin/easy_install to 755
  changing mode of /Users/althoefer/.local/share/virtualenvs/project-niLaHpIj/bin/easy_install-3.7 to 755
Cleaning up...
Removed build tracker '/private/var/folders/hq/psmsyk_12k10jxj1vc5_wl_r0000gn/T/pip-req-tracker-xh0k4z79'
ERROR: Exception:
Traceback (most recent call last):
  File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/req/req_install.py", line 920, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/req/req_install.py", line 448, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/wheel.py", line 604, in move_wheel_files
    reader = csv.reader(record_in)
AttributeError: module 'csv' has no attribute 'reader'
----------------------------------------
...Installing setuptools, pip, wheel...done.

✘ Failed creating virtual environment
[pipenv.exceptions.VirtualenvCreationException]:   File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/pipenv/cli/command.py", line 254, in install
[pipenv.exceptions.VirtualenvCreationException]:       editable_packages=state.installstate.editables,
[pipenv.exceptions.VirtualenvCreationException]:   File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/pipenv/core.py", line 1741, in do_install
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/pipenv/core.py", line 574, in ensure_project
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/pipenv/core.py", line 506, in ensure_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
[pipenv.exceptions.VirtualenvCreationException]:   File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/pipenv/core.py", line 935, in do_create_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       extra=[crayons.blue("{0}".format(c.err)),]
[pipenv.exceptions.VirtualenvCreationException]: Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv.py", line 2635, in <module>
    main()
  File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv.py", line 870, in main
    symlink=options.symlink,
  File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv.py", line 1173, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv.py", line 1019, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv.py", line 1110, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/Users/althoefer/Library/Python/3.7/lib/python/site-packages/virtualenv.py", line 963, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /Users/althoefer/.local...LaHpIj/bin/python3.7 - setuptools pip wheel failed with error code 2

Failed to create virtual environment.

```

### Steps to replicate

```bash
$ pip install --user pipenv
[...]
$ pipenv --version
pipenv, version 2018.11.26
$ mkdir project
$ cd project
$ touch csv.py
$ ~/.local/bin/pipenv install requests
```
-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/Users/althoefer/Library/Python/3.7/lib/python/site-packages/pipenv'`

Python location: `'/opt/local/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7'`

Python installations found:

  - `3.7.3`: `/opt/local/bin/python3`
  - `3.7.3`: `/opt/local/bin/python3.7m`
  - `3.7.0`: `/Applications/anaconda3/bin/python3`
  - `3.6.8`: `/opt/local/bin/python3.6`
  - `3.6.8`: `/opt/local/bin/python3.6m`
  - `3.6.5`: `/Applications/anaconda3/bin/pythonw`
  - `3.6.5`: `/Applications/anaconda3/bin/python3.6`
  - `2.7.16`: `/opt/local/bin/python2`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.7.0: Sun Jun  2 20:31:42 PDT '
                     '2019; root:xnu-4570.71.46~1/RELEASE_X86_64',
 'python_full_version': '3.7.3',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM`
  - `SHELL`
  - `HISTSIZE`
  - `CLICOLOR`
  - `SSH_CLIENT`
  - `TMPDIR`
  - `SSH_TTY`
  - `LC_ALL`
  - `HISTFILESIZE`
  - `USER`
  - `HDF5_USE_FILE_LOCKING`
  - `MAIL`
  - `PATH`
  - `PWD`
  - `LANG`
  - `PS1`
  - `SHLVL`
  - `HOME`
  - `LOGNAME`
  - `SSH_CONNECTION`
  - `_`
  - `OLDPWD`
  - `__CF_USER_TEXT_ENCODING`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/althoefer/Library/Python/3.7/bin:/opt/local/lib/mysql56/bin:/opt/local/bin:/Applications/anaconda3/bin:/opt/local/bin:/usr/local/bin:/usr/local:/Applications/MacPorts/bin:/Applications/MacPorts/sbin:/Applications/CMake.app/Contents/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/opt/X11/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/althoefer/project`

---------------------------

Contents of `Pipfile` ('/Users/althoefer/project/Pipfile'):

```toml

```

</details>

**Comment by frostming** [comment]
By no chance should you name your file with the same name of a standard library. Imagine you have a file named `os.py` or `sys.py`, then everything will be broken given `os` and `sys` are very commonly used.

So this request is not so reasonable. People should follow the necessary rules to not break things rather than ask tools or libraries maintainers to obey your preferences.
