### ISSUE TITLE
fails to respect platform markers

### ISSUE THREAD

**Issue by Madoshakalaka** [pypa/pipenv#3929]
### Issue description

A default dependency of my project is pypi package `mod-wsgi`. I added `os_name = "=='posix'"` as I'm doing development on a Windows system.

Yet pipenv errors when it tries to lock dependency.

### Expected result

pipenv ignores mod-wsgi and successfully installs nothing.

### Actual result

```cmd
F:\tmp>pipenv install --verbose
Creating a virtualenv for this project…
Pipfile: F:\tmp\Pipfile
Using c:\users\matt\appdata\local\programs\python\python37-32\python3.exe (3.7.1) to create virtualenv…
[    ] Creating virtual environment...Already using interpreter c:\users\matt\appdata\local\programs\python\python37-32\python3.exe
Using base prefix 'c:\\users\\matt\\appdata\\local\\programs\\python\\python37-32'
New python executable in C:\Users\Matt\.virtualenvs\tmp-33QWm_Ca\Scripts\python3.exe
Also creating executable in C:\Users\Matt\.virtualenvs\tmp-33QWm_Ca\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

Successfully created virtual environment!
Virtualenv location: C:\Users\Matt\.virtualenvs\tmp-33QWm_Ca
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Locking Failed!
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1
Current constraints:
  mod-wsgi~=4.6

Finding the best candidates:
  found candidate mod-wsgi==4.6.7 (constraint was ~=4.6)

Finding secondary dependencies:
  mod-wsgi==4.6.7 not in cache, need to check index
Traceback (most recent call last):
  File "c:/users/matt/appdata/local/programs/python/python37-32/lib/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "c:/users/matt/appdata/local/programs/python/python37-32/lib/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "c:/users/matt/appdata/local/programs/python/python37-32/lib/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "c:/users/matt/appdata/local/programs/python/python37-32/lib/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "c:\users\matt\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "c:\users\matt\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "c:\users\matt\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "c:\users\matt\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "c:\users\matt\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "c:\users\matt\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "c:\users\matt\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "c:\users\matt\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "c:\users\matt\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "c:\users\matt\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\matt\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 213, in _get_abstract_dist_for
    self.require_hashes
  File "c:\users\matt\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "c:\users\matt\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "c:\users\matt\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\req\req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "c:\users\matt\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\patched\notpip\_internal\utils\misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\Matt\AppData\Local\Temp\tmp88i1h3hzbuild\mod-wsgi\
```

### Steps to replicate

- Have the following Pipfile on Windows system
    ```pipfile
    [[source]]
    name = "pypi"
    url = "https://pypi.org/simple"
    verify_ssl = true
    
    [dev-packages]
    
    [packages]
    mod-wsgi = {version="~=4.6", os_name = "=='posix'"}
```
- run pipenv install

    F:\tmp>pipenv install

**Comment by Madoshakalaka** [comment]
Found  closed issue #1637 reporting the same problem. And it's claimed to be fixed in a newer pipenv release.

my pipenv is the latest 
```cmd
F:\tmp>pipenv --version
pipenv, version 2018.11.26
```

Afterwards, I tried using `sys_platform` marker as documented in the [official docs]( https://docs.pipenv.org/en/latest/advanced/#specifying-basically-anything).
The same error happens.

I also tried the other markers in [PEP508](https://www.python.org/dev/peps/pep-0508/#environment-markers) combined with != and ==, which all gives the same error.

I tried at least the following:
os_name = "!= 'nt'"
os_name = "== 'posix'"
sys_platform = "!= 'win32' "
sys_platform = "== 'linux' "
platform_system = "== 'Linux'"
platform_system = "== 'Windows'"

**Comment by Madoshakalaka** [comment]
The error only happens in the lock stage. `pipenv install` exit successfully with `--skip-lock`

```cmd
(tmp-33QWm_Ca) F:\tmp>pipenv install --skip-lock
Installing dependencies from Pipfile…
Ignoring mod-wsgi: markers 'sys_platform != "win32"' don't match your environment
  ================================ 1/1 - 00:00:00
```

**Comment by frostming** [comment]
Pipenv reads the marker to skip installation, but still needs to analyze and execute it to resolve dependencies.
