### ISSUE TITLE
Pipenv unable to lock package that depends on a prerelease

### ISSUE THREAD

**Issue by AstraLuma** [pypa/pipenv#3947]
### Issue description

If a released version of a package depends on a prerelease version of another package, `pipenv` will fail to lock it.

Concretely, `gqlmod` v0.2 depends on `graphql-core` >= 3.0a0, and `gqlmod` is uninstallable from pipenv.

(`pip` is able to handle this just fine.)

### Expected result

Package is installed with the declared dependencies.

### Actual result

```
🐚 pipenv install --verbose gqlmod                                                                                                 
Creating a Pipfile for this project…
⠋ Installing...Installing 'gqlmod'
$ ['/home/astraluma/.local/share/virtualenvs/piptest-8PNPu6qk/bin/pip', 'install', '--verbose', '--upgrade', 'gqlmod', '-i', 'https://pypi.org/simple']
Installing gqlmod…
Adding gqlmod to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✘ Locking Failed! 
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  gqlmod

Finding the best candidates:
  found candidate gqlmod==0.2 (constraint was <any>)

Finding secondary dependencies:
  gqlmod==0.2               requires astor, graphql-core>=3.0a0, import-x, setuptools

New dependencies found in this round:
  adding ['astor', '', '[]']
  adding ['graphql-core', '>=3.0a0', '[]']
  adding ['import-x', '', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  astor
  gqlmod
  graphql-core>=3.0a0
  import-x

Finding the best candidates:
  found candidate astor==0.8.0 (constraint was <any>)
  found candidate gqlmod==0.2 (constraint was <any>)
Traceback (most recent call last):
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 198, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 198, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 263, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 175, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches graphql-core>=3.0a0
Tried: 0.4.9, 0.4.11, 0.4.12, 0.4.12.1, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.4.17, 0.4.18, 0.5, 0.5.1, 0.5.2, 0.5.3, 1.0, 1.0.1, 1.1, 2.0, 2.0, 2.1, 2.1, 2.2, 2.2, 2.2.1, 2.2.1
Skipped pre-versions: 0.1a0, 0.1a1, 0.1a2, 0.1a3, 0.1a4, 0.4.7b0, 0.4.7b1, 0.4.7b2, 0.5b1, 0.5b2, 0.5b3, 1.0.dev20160814231515, 1.0.dev20160822075425, 1.0.dev20160823054952, 1.0.dev20160909030348, 1.0.dev20160909040033, 1.0.dev20160920065529, 1.2.dev20170724044604, 2.0.dev20170801041408, 2.0.dev20170801041408, 2.0.dev20170801051721, 2.0.dev20170801051721, 2.0.dev20171009101843, 2.0.dev20171009101843, 2.1rc0, 2.1rc0, 2.1rc1, 2.1rc1, 2.1rc2, 2.1rc2, 2.1rc3, 2.1rc3, 3.0.0a0, 3.0.0a0, 3.0.0a1, 3.0.0a1, 3.0.0a2, 3.0.0a2
There are incompatible versions in the resolved dependencies.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/utils.py", line 395, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches graphql-core>=3.0a0
Tried: 0.4.9, 0.4.11, 0.4.12, 0.4.12.1, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.4.17, 0.4.18, 0.5, 0.5.1, 0.5.2, 0.5.3, 1.0, 1.0.1, 1.1, 2.0, 2.0, 2.1, 2.1, 2.2, 2.2, 2.2.1, 2.2.1
Skipped pre-versions: 0.1a0, 0.1a1, 0.1a2, 0.1a3, 0.1a4, 0.4.7b0, 0.4.7b1, 0.4.7b2, 0.5b1, 0.5b2, 0.5b3, 1.0.dev20160814231515, 1.0.dev20160822075425, 1.0.dev20160823054952, 1.0.dev20160909030348, 1.0.dev20160909040033, 1.0.dev20160920065529, 1.2.dev20170724044604, 2.0.dev20170801041408, 2.0.dev20170801041408, 2.0.dev20170801051721, 2.0.dev20170801051721, 2.0.dev20171009101843, 2.0.dev20171009101843, 2.1rc0, 2.1rc0, 2.1rc1, 2.1rc1, 2.1rc2, 2.1rc2, 2.1rc3, 2.1rc3, 3.0.0a0, 3.0.0a0, 3.0.0a1, 3.0.0a1, 3.0.0a2, 3.0.0a2
There are incompatible versions in the resolved dependencies.
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  gqlmod

Finding the best candidates:
  found candidate gqlmod==0.2 (constraint was <any>)

Finding secondary dependencies:
  gqlmod==0.2               requires astor, graphql-core>=3.0a0, import-x, setuptools

New dependencies found in this round:
  adding ['astor', '', '[]']
  adding ['graphql-core', '>=3.0a0', '[]']
  adding ['import-x', '', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  astor
  gqlmod
  graphql-core>=3.0a0
  import-x

Finding the best candidates:
  found candidate astor==0.8.0 (constraint was <any>)
  found candidate gqlmod==0.2 (constraint was <any>)
Traceback (most recent call last):
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 198, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 198, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 263, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 175, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches graphql-core>=3.0a0
Tried: 0.4.9, 0.4.11, 0.4.12, 0.4.12.1, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.4.17, 0.4.18, 0.5, 0.5.1, 0.5.2, 0.5.3, 1.0, 1.0.1, 1.1, 2.0, 2.0, 2.1, 2.1, 2.2, 2.2, 2.2.1, 2.2.1
Skipped pre-versions: 0.1a0, 0.1a1, 0.1a2, 0.1a3, 0.1a4, 0.4.7b0, 0.4.7b1, 0.4.7b2, 0.5b1, 0.5b2, 0.5b3, 1.0.dev20160814231515, 1.0.dev20160822075425, 1.0.dev20160823054952, 1.0.dev20160909030348, 1.0.dev20160909040033, 1.0.dev20160920065529, 1.2.dev20170724044604, 2.0.dev20170801041408, 2.0.dev20170801041408, 2.0.dev20170801051721, 2.0.dev20170801051721, 2.0.dev20171009101843, 2.0.dev20171009101843, 2.1rc0, 2.1rc0, 2.1rc1, 2.1rc1, 2.1rc2, 2.1rc2, 2.1rc3, 2.1rc3, 3.0.0a0, 3.0.0a0, 3.0.0a1, 3.0.0a1, 3.0.0a2, 3.0.0a2
There are incompatible versions in the resolved dependencies.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/astraluma/.local/lib/python3.7/site-packages/pipenv/utils.py", line 395, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches graphql-core>=3.0a0
Tried: 0.4.9, 0.4.11, 0.4.12, 0.4.12.1, 0.4.13, 0.4.14, 0.4.15, 0.4.16, 0.4.17, 0.4.18, 0.5, 0.5.1, 0.5.2, 0.5.3, 1.0, 1.0.1, 1.1, 2.0, 2.0, 2.1, 2.1, 2.2, 2.2, 2.2.1, 2.2.1
Skipped pre-versions: 0.1a0, 0.1a1, 0.1a2, 0.1a3, 0.1a4, 0.4.7b0, 0.4.7b1, 0.4.7b2, 0.5b1, 0.5b2, 0.5b3, 1.0.dev20160814231515, 1.0.dev20160822075425, 1.0.dev20160823054952, 1.0.dev20160909030348, 1.0.dev20160909040033, 1.0.dev20160920065529, 1.2.dev20170724044604, 2.0.dev20170801041408, 2.0.dev20170801041408, 2.0.dev20170801051721, 2.0.dev20170801051721, 2.0.dev20171009101843, 2.0.dev20171009101843, 2.1rc0, 2.1rc0, 2.1rc1, 2.1rc1, 2.1rc2, 2.1rc2, 2.1rc3, 2.1rc3, 3.0.0a0, 3.0.0a0, 3.0.0a1, 3.0.0a1, 3.0.0a2, 3.0.0a2
There are incompatible versions in the resolved dependencies.
```

### Steps to replicate

1. `mkdir /tmp/piptest`
2. `cd /tmp/piptest`
3. `pipenv install gqlmod`

(Note that the above steps will succeed if `graphql-core` makes a v3.* release.)

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/astraluma/.local/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.7.4`: `/usr/bin/python3`
  - `3.7.4`: `/usr/bin/python3.7m`
  - `3.6.8`: `/usr/bin/python3.6m`
  - `3.6.8`: `/usr/bin/python3.6`
  - `3.6.1`: `/usr/bin/pypy3`
  - `2.7.16`: `/usr/bin/python2.7`
  - `2.7.13`: `/usr/bin/pypy`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.2.0-2-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Debian 5.2.9-2 (2019-08-21)',
 'python_full_version': '3.7.4+',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `BASH_COMPLETIONS`
  - `XONSH_VERSION`
  - `SSH_AUTH_SOCK`
  - `SESSION_MANAGER`
  - `GNOME_TERMINAL_SCREEN`
  - `SSH_AGENT_PID`
  - `XDG_CURRENT_DESKTOP`
  - `LANG`
  - `GPG_AGENT_INFO`
  - `USER`
  - `DESKTOP_SESSION`
  - `XDG_MENU_PREFIX`
  - `HOME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_VTNR`
  - `XDG_SEAT`
  - `GTK_MODULES`
  - `XDG_DATA_DIRS`
  - `WINDOWPATH`
  - `XDG_SESSION_DESKTOP`
  - `QT_ACCESSIBILITY`
  - `GNOME_DESKTOP_SESSION_ID`
  - `VTE_VERSION`
  - `LOGNAME`
  - `GNOME_TERMINAL_SERVICE`
  - `PATH`
  - `XDG_RUNTIME_DIR`
  - `XDG_SESSION_ID`
  - `XDG_SESSION_TYPE`
  - `SHELL`
  - `USERNAME`
  - `EDITOR`
  - `GDM_LANG`
  - `COLORTERM`
  - `XAUTHORITY`
  - `DESKTOP_AUTOSTART_ID`
  - `PWD`
  - `XDG_SESSION_CLASS`
  - `TERM`
  - `GDMSESSION`
  - `DISPLAY`
  - `LOADED_RC_FILES`
  - `XONSHRC`
  - `PROJECT_DIRS`
  - `SHELL_TYPE`
  - `PROMPT`
  - `VIRTUALENV_HOME`
  - `LS_COLORS`
  - `VISUAL`
  - `SUPPRESS_BRANCH_TIMEOUT_MESSAGE`
  - `AUTO_PUSHD`
  - `TITLE`
  - `RIGHT_PROMPT`
  - `PKG_CONFIG_PATH`
  - `XONSH_SHOW_TRACEBACK`
  - `XONSH_LOGIN`
  - `XONSH_INTERACTIVE`
  - `OLDPWD`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/astraluma/.poetry/bin:/home/astraluma/.local/bin:/home/astraluma/.gem/ruby/2.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/astraluma/.local/xonsh/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `nano`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/tmp/piptest`

---------------------------

Contents of `Pipfile` ('/tmp/piptest/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
gqlmod = "*"

[requires]
python_version = "3.7"

```

</details>

**Comment by astronouth7303** [comment]
Note: adding the `--pre` flag allows it to install and lock, but I assume that enabled prereleases for everything and not just this one specific package?

**Comment by matteius** [comment]
That is correct @AstraLuma  -- we have this other linked ticket about the possibility of supporting prereleases only for a specific package, but I believe it is probelematic unless the pip resolver itself supported this, which right now the `--pre` option is only a global option.
