### ISSUE TITLE
``pipenv install requests'' failed to execute.

### ISSUE THREAD

**Issue by hongyi-zhao** [pypa/pipenv#3948]
Hi,

I use debian 9 and the latest pipenv, but meet the following error:

-----------------------------
$ pipenv install requests
Installing requests…
Adding requests to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock (1dc33d) out of date, updating to (51e8ae)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success! 
Updated Pipfile.lock (1dc33d)!
Installing dependencies from Pipfile.lock (1dc33d)…
Traceback (most recent call last):▉▉▉▉▉ 0/8 — 00:00:00
  File "/home/werner/.pyenv/versions/3.7.4/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/core.py", line 1992, in do_install
    skip_lock=skip_lock,
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/core.py", line 1253, in do_init
    pypi_mirror=pypi_mirror,
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/core.py", line 838, in do_install_dependencies
    deps_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/core.py", line 754, in batch_install
    extra_indexes=extra_indexes
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/core.py", line 1421, in pip_install
    c = delegator.run(pip_command, block=block, env=pip_config)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/delegator.py", line 336, in run
    c.run(block=block, binary=binary, cwd=cwd, env=env)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/delegator.py", line 204, in run
    s = PopenSpawn(self._popen_args, **pexpect_kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/site-packages/pipenv/vendor/pexpect/popen_spawn.py", line 53, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/werner/.pyenv/versions/3.7.4/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/werner/software/anti-gfw/shadowsocks-v2ray/socks5-haproxy/speed-check/.venv/bin/pip': '/home/werner/software/anti-gfw/shadowsocks-v2ray/socks5-haproxy/speed-check/.venv/bin/pip'
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/8 — 00:00:00
--------------------------------

Any hints?

**Comment by frostming** [comment]
Seems you need to `pipenv --rm` and recreate your virtualenv
