### ISSUE TITLE
can't find ffi module when create new virtualenv

### ISSUE THREAD

**Issue by vincenthcui** [pypa/pipenv#3987]
### Issue description

I run command `pipenv --two` aims to create new virtualenv for project, an error occurred, say that ffi module is not found.

I have tried to reinstall pipenv and python2, but have no effect.

### Expected result

create a new virtualenv in python2

### Actual result

got an error like this:

```
Creating a virtualenv for this project…
Pipfile: /Users/vincentcui/Code/pressure-test/Pipfile
Using /Library/Frameworks/Python.framework/Versions/2.7/bin/python (2.7.16) to create virtualenv…
⠴ Creating virtual environment...New python executable in /Users/vincentcui/.local/share/virtualenvs/pressure-test-BjBzUxVJ/bin/python
Complete output from command /Users/vincentcui/.l...-BjBzUxVJ/bin/python -m pip config list:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/virtualenv_support/pip-19.0.1-py2.py3-none-any.whl/pip/__main__.py", line 16, in <module>
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/virtualenv_support/pip-19.0.1-py2.py3-none-any.whl/pip/_internal/__init__.py", line 40, in <module>
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/virtualenv_support/pip-19.0.1-py2.py3-none-any.whl/pip/_internal/cli/autocompletion.py", line 8, in <module>
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/virtualenv_support/pip-19.0.1-py2.py3-none-any.whl/pip/_internal/cli/main_parser.py", line 8, in <module>
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/virtualenv_support/pip-19.0.1-py2.py3-none-any.whl/pip/_internal/cli/cmdoptions.py", line 22, in <module>
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/virtualenv_support/pip-19.0.1-py2.py3-none-any.whl/pip/_internal/utils/hashes.py", line 10, in <module>
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/virtualenv_support/pip-19.0.1-py2.py3-none-any.whl/pip/_internal/utils/misc.py", line 15, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 78, in <module>
    import fcntl
  File "fcntl.py", line 1, in <module>
    import ffi
ImportError: No module named ffi
----------------------------------------
Running virtualenv with interpreter /Library/Frameworks/Python.framework/Versions/2.7/bin/python

✘ Failed creating virtual environment
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==2018.11.26', 'console_scripts', 'pipenv')()
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/cli/command.py", line 208, in cli
    clear=state.clear,
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/core.py", line 574, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/core.py", line 506, in ensure_virtualenv
    python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv/core.py", line 935, in do_create_virtualenv
    extra=[crayons.blue("{0}".format(c.err)),]
pipenv.exceptions.VirtualenvCreationException: Failed to create virtual environment.
```

### Steps to replicate

simply run command `pipenv --two`

-------------------------------------------------------------------------------

support info

```
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.11.26_2/libexec/bin/python3.7'`

Python installations found:

  - `3.7.4`: `/usr/local/bin/python3`
  - `3.7.4`: `/usr/local/bin/python3.7m`
  - `2.7.16`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/python`
  - `2.7.16`: `/Library/Frameworks/Python.framework/Versions/2.7/bin/pythonw`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT '
                     '2019; root:xnu-4570.71.45~1/RELEASE_X86_64',
 'python_full_version': '3.7.4',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `AUTOJUMP_ERROR_PATH`
  - `TERM_PROGRAM`
  - `NVM_CD_FLAGS`
  - `AUTOJUMP_SOURCED`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `GOPRIVATE`
  - `ZSH`
  - `NVM_DIR`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `PAGER`
  - `LSCOLORS`
  - `_`
  - `PWD`
  - `LANG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `LC_TERMINAL_VERSION`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `LC_CTYPE`
  - `NVM_BIN`
  - `GOPATH`
  - `LC_TERMINAL`
  - `DISPLAY`
  - `COLORTERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:


Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2018.11.26_2/libexec/tools:/Users/vincentcui/.nvm/versions/node/v8.0.0/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/go/bin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/vincentcui/go/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `zh_CN.UTF-8`
  - `PWD`: `/Users/vincentcui/Code/pressure-test`


---------------------------

Contents of `Pipfile` ('/Users/vincentcui/Code/pressure-test/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]

[requires]
python_version = "3.7"

```

</details>
```

**Comment by matteius** [comment]
Can this be rechecked with `pipenv==2022.8.19`?
