### ISSUE TITLE
Installing tensorflow causes crash

### ISSUE THREAD

**Issue by parsley72** [pypa/pipenv#4006]
### Issue description

When I run `pipenv install` it crashes.

### Expected result

No crash.

### Actual result
```
$ pipenv install --verbose
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:

Finding the best candidates:

Finding secondary dependencies:
------------------------------------------------------------
Result of round 1: stable, done

Locking [packages] dependencies…
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  tensorflow

Finding the best candidates:
  found candidate tensorflow==2.0.0 (constraint was <any>)

Finding secondary dependencies:
  tensorflow==2.0.0         requires absl-py>=0.7.0, astor>=0.6.0, functools32>=3.2.3, gast==0.2.2, google-pasta>=0.1.6, grpcio>=1.8.6, keras-applications>=1.0.8, keras-preprocessing>=1.0.5, mock>=2.0.0, numpy<2.0,>=1.16.0, opt-einsum>=2.3.2, protobuf>=3.6.1, six>=1.10.0, tensorboard<2.1.0,>=2.0.0, tensorflow-estimator<2.1.0,>=2.0.0, termcolor>=1.1.0, wheel, wrapt>=1.11.1

New dependencies found in this round:
  adding ['absl-py', '>=0.7.0', '[]']
  adding ['astor', '>=0.6.0', '[]']
  adding ['functools32', '>=3.2.3', '[]']
  adding ['gast', '==0.2.2', '[]']
  adding ['google-pasta', '>=0.1.6', '[]']
  adding ['grpcio', '>=1.8.6', '[]']
  adding ['keras-applications', '>=1.0.8', '[]']
  adding ['keras-preprocessing', '>=1.0.5', '[]']
  adding ['mock', '>=2.0.0', '[]']
  adding ['numpy', '<2.0,>=1.16.0', '[]']
  adding ['opt-einsum', '>=2.3.2', '[]']
  adding ['protobuf', '>=3.6.1', '[]']
  adding ['six', '>=1.10.0', '[]']
  adding ['tensorboard', '<2.1.0,>=2.0.0', '[]']
  adding ['tensorflow-estimator', '<2.1.0,>=2.0.0', '[]']
  adding ['termcolor', '>=1.1.0', '[]']
  adding ['wheel', '', '[]']
  adding ['wrapt', '>=1.11.1', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  absl-py>=0.7.0
  astor>=0.6.0
  functools32>=3.2.3
  gast==0.2.2
  google-pasta>=0.1.6
  grpcio>=1.8.6
  keras-applications>=1.0.8
  keras-preprocessing>=1.0.5
  mock>=2.0.0
  numpy<2.0,>=1.16.0
  opt-einsum>=2.3.2
  protobuf>=3.6.1
  six>=1.10.0
  tensorboard<2.1.0,>=2.0.0
  tensorflow
  tensorflow-estimator<2.1.0,>=2.0.0
  termcolor>=1.1.0
  wheel
  wrapt>=1.11.1

Finding the best candidates:
  found candidate absl-py==0.8.1 (constraint was >=0.7.0)
  found candidate astor==0.8.0 (constraint was >=0.6.0)
  found candidate functools32==3.2.3.post2 (constraint was >=3.2.3)
  found candidate gast==0.2.2 (constraint was ==0.2.2)
  found candidate google-pasta==0.1.7 (constraint was >=0.1.6)
  found candidate grpcio==1.24.3 (constraint was >=1.8.6)
  found candidate keras-applications==1.0.8 (constraint was >=1.0.8)
  found candidate keras-preprocessing==1.1.0 (constraint was >=1.0.5)
  found candidate mock==3.0.5 (constraint was >=2.0.0)
  found candidate numpy==1.17.3 (constraint was >=1.16.0,<2.0)
  found candidate opt-einsum==3.1.0 (constraint was >=2.3.2)
  found candidate protobuf==3.10.0 (constraint was >=3.6.1)
  found candidate six==1.12.0 (constraint was >=1.10.0)
  found candidate tensorboard==2.0.0 (constraint was >=2.0.0,<2.1.0)
  found candidate tensorflow==2.0.0 (constraint was <any>)
  found candidate tensorflow-estimator==2.0.1 (constraint was >=2.0.0,<2.1.0)
  found candidate termcolor==1.1.0 (constraint was >=1.1.0)
  found candidate wheel==0.33.6 (constraint was <any>)
  found candidate wrapt==1.11.2 (constraint was >=1.11.1)

Finding secondary dependencies:
  tensorflow-estimator==2.0.1 requires -
  wheel==0.33.6             requires -
  tensorflow==2.0.0         requires absl-py>=0.7.0, astor>=0.6.0, functools32>=3.2.3, gast==0.2.2, google-pasta>=0.1.6, grpcio>=1.8.6, keras-applications>=1.0.8, keras-preprocessing>=1.0.5, mock>=2.0.0, numpy<2.0,>=1.16.0, opt-einsum>=2.3.2, protobuf>=3.6.1, six>=1.10.0, tensorboard<2.1.0,>=2.0.0, tensorflow-estimator<2.1.0,>=2.0.0, termcolor>=1.1.0, wheel, wrapt>=1.11.1
  protobuf==3.10.0          requires setuptools, six>=1.9
  absl-py==0.8.1            requires six
  keras-applications==1.0.8 requires h5py, numpy>=1.9.1
  numpy==1.17.3             requires -
  functools32==3.2.3.post2 not in cache, need to check index

INFO:notpip.req.req_set:Collecting functools32==3.2.3.post2
INFO:pip9.download:File was already downloaded /home/tom/.cache/pipenv/pkgs/functools32-3.2.3-2.tar.gz
INFO:pip9.utils:Complete output from command python setup.py egg_info:
INFO:pip9.utils:This backport is for Python 2.7 only.

----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pipenv/resolver.py", line 82, in <module>
    main()
  File "/usr/lib/python3/dist-packages/pipenv/resolver.py", line 71, in main
    clear=do_clear,
  File "/usr/lib/python3/dist-packages/pipenv/resolver.py", line 63, in resolve
    verbose=verbose,
  File "/usr/lib/python3/dist-packages/pipenv/utils.py", line 425, in resolve_deps
    pre,
  File "/usr/lib/python3/dist-packages/pipenv/utils.py", line 336, in actually_resolve_reps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/resolver.py", line 297, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 174, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/lib/python3/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 222, in get_legacy_dependencies
    result = reqset._prepare_file(self.finder, ireq, ignore_requires_python=True)
  File "/usr/lib/python3/dist-packages/pipenv/patched/notpip/req/req_set.py", line 644, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python3/dist-packages/pipenv/patched/notpip/req/req_set.py", line 134, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pipenv/vendor/pip9/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3/dist-packages/pipenv/vendor/pip9/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip9.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmp6gr491jrbuild/functools32/
```

### Steps to replicate

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
tensorflow = "*"

[requires]
python_version = "3.7"
```

-------------------------------------------------------------------------------

Error: no such option: --support

**Comment by mmartinortiz** [comment]
I'm think that your issue is the same that [this one](https://github.com/pypa/pipenv/issues/3921)

**Comment by frostming** [comment]
Close due to duplicating #3921
