### ISSUE TITLE
brew install spontaneously breaks requiring reinstall

### ISSUE THREAD

**Issue by jamesstidard** [pypa/pipenv#4013]
### Issue description
I've installed `pipenv` via `brew` on macOS. Every now and then my `pipenv` install will suddenly stop working and I have to `brew reinstall pipenv`. Not a massive deal as it works fine after a reinstall, but this has been happening for a year or two now.

### Expected result
`pipenv` to not kill itself.

### Actual result
Hara Kiri.

![68036961-9bd62800-fcbe-11e9-9566-9e63ac6b7035](https://user-images.githubusercontent.com/1797906/68037368-7ac20700-fcbf-11e9-99cc-7c64ccad5799.png)

### Steps to replicate
I'm not actually able to reproduce this bug which is why I only unfortunately have a screenshot I took. (I accidentally closed the terminal after I realised I should have copied the text, not took a screenshot).

My inclining is that its something to do with minor version releases? As I noticed the download on the reinstall is for version `2018.11.26_2`, maybe a later build being pushed and I had build 1 of the same version? Not really sure, I just noticed that.

Anyway, not urgent but is a silly to have to reinstall every now and then :)

**Comment by frostming** [comment]
How often do you meet this problem? Did you upgrade brew's python before each replication?

**Comment by lanox** [comment]
Hi, I get the same problem everytime brew updated pipenv it breaks it and I need to remove it and then install it again.

`
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/bin/pipenv", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pipenv==2018.11.26' distribution was not found and is required by the application
`

**Comment by AlJohri** [comment]
I get this exact same problem on every homebrew python upgrade.

**Comment by frostming** [comment]
The installation guide is misleading users to use homebrew to install pipenv but I would like to say brew is a terrible choice.

Never install CLI tools using homebrew python, It keeps breaking the current installation on every upgrade.

**Comment by AlJohri** [comment]
I would still prefer to use homebrew here if possible. homebrew provides revision bumps for formula that will force them to upgrade when python does. I’m not sure why pipenv didn’t receive a revision bump here.

i believe there are also ways to create the formula such that it doesn’t break (i.e without virtualenvs, see the pipx formula). I don’t think not using homebrew is the answer here. Homebrew is the most natural place for macos users to install CLI tools.

**Comment by jamesstidard** [comment]
> How often do you meet this problem? Did you upgrade brew's python before each replication?

Um, not overly regularly. I'd say within a couple months I'll see it. Just so happens I got it again today (so 7 days).

```
james at freebie in ~/D/J/dotfiles
$ pipenv run python                                                                                                                                                                                                                                                                                            ●●◦ ◦ master
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2018.11.26_2/libexec/bin/pipenv", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pipenv==2018.11.26' distribution was not found and is required by the application
james at freebie in ~/D/J/dotfiles
$ brew reinstall pipenv                                                                                                                                                                                                                                                                                        ●●◦ ◦ master
==> Reinstalling pipenv 
==> Downloading https://homebrew.bintray.com/bottles/pipenv-2018.11.26_2.catalina.bottle.1.tar.gz
==> Downloading from https://akamai.bintray.com/8f/8f084160ecf6fec95317a0a298242040590ded00f5d375796c28697f1e9507c8?__gda__=exp=1573249667~hmac=3abcd5f8198613bd767ba40e1607172d10d2130570dec0a902dc7c008d17b8e8&response-content-disposition=attachment%3Bfilename%3D%22pipenv-2018.11.26_2.catalina.bottle.1.tar.gz%22&re
######################################################################## 100.0%
==> Pouring pipenv-2018.11.26_2.catalina.bottle.1.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/pipenv/2018.11.26_2: 1,477 files, 19.9MB
```

> I don’t think not using homebrew is the answer here. Homebrew is the most natural place for macos users to install CLI tools.

I personally would like to see the homebrew formula stick around. Before I was managing via `pipsi` and being able to get it from brew is much more convenient when you want a global command line tool on a Mac.

> I get this exact same problem on every homebrew python upgrade.

Between my two posts it looks like my python version has stayed the same (3.7.5) and the build of pipenv `2018.11.26_2`. Dunno if that's a helpful observation. I've not been able to figure out what's happening here.

**Comment by gprotasio** [comment]
![Screen Shot 2020-01-02 at 00 32 49](https://user-images.githubusercontent.com/54383772/71650823-99f90700-2cf7-11ea-85af-a93b81825a9a.png)
![Screen Shot 2020-01-02 at 00 33 03](https://user-images.githubusercontent.com/54383772/71650832-a1b8ab80-2cf7-11ea-8fb1-16ff87d41570.png)
![Screen Shot 2020-01-02 at 00 33 37](https://user-images.githubusercontent.com/54383772/71650835-a715f600-2cf7-11ea-8af4-755a3e8622fc.png)

Reinstalling resolved here. :)

**Comment by gprotasio** [comment]
I had problem here when there was a python upgrade via homebrew 3.7.5 to 3.7.6; consequently pipenv failed.
