### ISSUE TITLE
unable to install wsgiref on python 3.8.0

### ISSUE THREAD

**Issue by byteshiva** [pypa/pipenv#4015]
### Issue description

pipenv install wsgiref throws error when installed on python 3.8.0

### Expected result

wsgiref should get installed successfully

### Actual result

```
['/home/xyz/.local/share/virtualenvs/flask-fullstack-aquMmdKt/bin/pip', 'install', '--verbose', '--upgrade', 'wsgiref', '-i', 'https://pypi.org/simple']
Adding wsgiref to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock (cc7623) out of date, updating to (444b8b)…
Locking [dev-packages] dependencies…
✔ Success! 
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  ipython

Finding the best candidates:
  found candidate ipython==7.9.0 (constraint was <any>)

Finding secondary dependencies:
  ipython==7.9.0            requires backcall, decorator, jedi>=0.10, pexpect; sys_platform != "win32", pickleshare, prompt-toolkit<2.1.0,>=2.0.0, pygments, setuptools>=18.5, traitlets>=4.2

New dependencies found in this round:
  adding ['backcall', '', '[]']
  adding ['decorator', '', '[]']
  adding ['jedi', '>=0.10', '[]']
  adding ['pexpect', '', '[]']
  adding ['pickleshare', '', '[]']
  adding ['prompt-toolkit', '<2.1.0,>=2.0.0', '[]']
  adding ['pygments', '', '[]']
  adding ['traitlets', '>=4.2', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  backcall
  decorator
  ipython
  jedi>=0.10
  pexpect
  pickleshare
  prompt-toolkit<2.1.0,>=2.0.0
  pygments
  traitlets>=4.2

Finding the best candidates:
  found candidate backcall==0.1.0 (constraint was <any>)
  found candidate decorator==4.4.1 (constraint was <any>)
  found candidate ipython==7.9.0 (constraint was <any>)
  found candidate jedi==0.15.1 (constraint was >=0.10)
  found candidate pexpect==4.7.0 (constraint was <any>)
  found candidate pickleshare==0.7.5 (constraint was <any>)
  found candidate prompt-toolkit==2.0.10 (constraint was >=2.0.0,<2.1.0)
  found candidate pygments==2.4.2 (constraint was <any>)
  found candidate traitlets==4.3.3 (constraint was >=4.2)

Finding secondary dependencies:
  decorator==4.4.1          requires -
  ipython==7.9.0            requires backcall, decorator, jedi>=0.10, pexpect; sys_platform != "win32", pickleshare, prompt-toolkit<2.1.0,>=2.0.0, pygments, setuptools>=18.5, traitlets>=4.2
  traitlets==4.3.3          requires decorator, ipython-genutils, six
  backcall==0.1.0           requires -
  jedi==0.15.1              requires parso>=0.5.0
  prompt-toolkit==2.0.10    requires six>=1.9.0, wcwidth
  pygments==2.4.2           requires -
  pickleshare==0.7.5        requires -
  pexpect==4.7.0            requires ptyprocess>=0.5

New dependencies found in this round:
  adding ['ipython-genutils', '', '[]']
  adding ['parso', '>=0.5.0', '[]']
  adding ['ptyprocess', '>=0.5', '[]']
  adding ['six', '>=1.9.0', '[]']
  adding ['wcwidth', '', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 2: not stable

                          ROUND 3                           
Current constraints:
  backcall
  decorator
  ipython
  ipython-genutils
  jedi>=0.10
  parso>=0.5.0
  pexpect
  pickleshare
  prompt-toolkit<2.1.0,>=2.0.0
  ptyprocess>=0.5
  pygments
  six>=1.9.0
  traitlets>=4.2
  wcwidth

Finding the best candidates:
  found candidate backcall==0.1.0 (constraint was <any>)
  found candidate decorator==4.4.1 (constraint was <any>)
  found candidate ipython==7.9.0 (constraint was <any>)
  found candidate ipython-genutils==0.2.0 (constraint was <any>)
  found candidate jedi==0.15.1 (constraint was >=0.10)
  found candidate parso==0.5.1 (constraint was >=0.5.0)
  found candidate pexpect==4.7.0 (constraint was <any>)
  found candidate pickleshare==0.7.5 (constraint was <any>)
  found candidate prompt-toolkit==2.0.10 (constraint was >=2.0.0,<2.1.0)
  found candidate ptyprocess==0.6.0 (constraint was >=0.5)
  found candidate pygments==2.4.2 (constraint was <any>)
  found candidate six==1.13.0 (constraint was >=1.9.0)
  found candidate traitlets==4.3.3 (constraint was >=4.2)
  found candidate wcwidth==0.1.7 (constraint was <any>)

Finding secondary dependencies:
  decorator==4.4.1          requires -
  wcwidth==0.1.7            requires -
  jedi==0.15.1              requires parso>=0.5.0
  backcall==0.1.0           requires -
  pexpect==4.7.0            requires ptyprocess>=0.5
  ipython-genutils==0.2.0   requires -
  six==1.13.0               requires -
  prompt-toolkit==2.0.10    requires six>=1.9.0, wcwidth
  pickleshare==0.7.5        requires -
  traitlets==4.3.3          requires decorator, ipython-genutils, six
  ptyprocess==0.6.0         requires -
  ipython==7.9.0            requires backcall, decorator, jedi>=0.10, pexpect; sys_platform != "win32", pickleshare, prompt-toolkit<2.1.0,>=2.0.0, pygments, setuptools>=18.5, traitlets>=4.2
  pygments==2.4.2           requires -
  parso==0.5.1              requires -
------------------------------------------------------------
Result of round 3: stable, done


Locking [packages] dependencies…
✘ Locking Failed! 
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  flask
  itsdangerous
  jinja2
  markupsafe
  werkzeug
  wsgiref

Finding the best candidates:
  found candidate flask==1.1.1 (constraint was <any>)
  found candidate itsdangerous==1.1.0 (constraint was <any>)
  found candidate jinja2==2.10.3 (constraint was <any>)
  found candidate markupsafe==1.1.1 (constraint was <any>)
  found candidate werkzeug==0.16.0 (constraint was <any>)
  found candidate wsgiref==0.1.2 (constraint was <any>)

Finding secondary dependencies:
  jinja2==2.10.3            requires markupsafe>=0.23
  werkzeug==0.16.0          requires -
  flask==1.1.1              requires click>=5.1, itsdangerous>=0.24, jinja2>=2.10.1, werkzeug>=0.15
  itsdangerous==1.1.0       requires -
  markupsafe==1.1.1         requires -
  wsgiref==0.1.2 not in cache, need to check index
Traceback (most recent call last):
  File "/home/ /.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/resolver.py", line 118, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system,
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/resolver.py", line 78, in _main
    results = resolve(
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/resolver.py", line 61, in resolve
    return resolve_deps(
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/utils.py", line 718, in resolve_deps
    resolved_tree, hashes, markers_lookup, resolver = actually_resolve_deps(
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 211, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 470, in run_egg_info
    call_subprocess(
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 703, in call_subprocess
    raise InstallationError(
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpn9o5zj5abuild/wsgiref/
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  flask
  itsdangerous
  jinja2
  markupsafe
  werkzeug
  wsgiref

Finding the best candidates:
  found candidate flask==1.1.1 (constraint was <any>)
  found candidate itsdangerous==1.1.0 (constraint was <any>)
  found candidate jinja2==2.10.3 (constraint was <any>)
  found candidate markupsafe==1.1.1 (constraint was <any>)
  found candidate werkzeug==0.16.0 (constraint was <any>)
  found candidate wsgiref==0.1.2 (constraint was <any>)

Finding secondary dependencies:
  jinja2==2.10.3            requires markupsafe>=0.23
  werkzeug==0.16.0          requires -
  flask==1.1.1              requires click>=5.1, itsdangerous>=0.24, jinja2>=2.10.1, werkzeug>=0.15
  itsdangerous==1.1.0       requires -
  markupsafe==1.1.1         requires -
  wsgiref==0.1.2 not in cache, need to check index
Traceback (most recent call last):
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/resolver.py", line 118, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system,
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/resolver.py", line 78, in _main
    results = resolve(
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/resolver.py", line 61, in resolve
    return resolve_deps(
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/utils.py", line 718, in resolve_deps
    resolved_tree, hashes, markers_lookup, resolver = actually_resolve_deps(
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 211, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 470, in run_egg_info
    call_subprocess(
  File "/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 703, in call_subprocess
    raise InstallationError(
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/tmpn9o5zj5abuild/wsgiref/

```

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

```
pipenv install wsgiref
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/xyz/.asdf/installs/python/3.8.0/lib/python3.8/site-packages/pipenv'`

Python location: `'/home/xyz/.asdf/installs/python/3.8.0/bin/python3.8'`

Python installations found:

  - `3.8.0`: `/home/xyz/.asdf/installs/python/3.8.0/bin/python3`
  - `3.7.5`: `/usr/bin/python3`
  - `3.7.5`: `/usr/bin/python3.7m`
  - `3.7.4`: `/home/xyz/.asdf/installs/python/3.7.4/bin/python3`
  - `3.7.4`: `/home/xyz/.asdf/installs/python/3.7.4/bin/python3.7m`
  - `2.7.17rc1`: `/usr/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.3.0-21-generic',
 'platform_system': 'Linux',
 'platform_version': '#22-Ubuntu SMP Tue Oct 29 22:55:51 UTC 2019',
 'python_full_version': '3.8.0',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `PATH`
  - `SHELL`
  - `SESSION_MANAGER`
  - `COLORTERM`
  - `XDG_CONFIG_DIRS`
  - `XDG_MENU_PREFIX`
  - `GNOME_DESKTOP_SESSION_ID`
  - `GTK_IM_MODULE`
  - `NVM_IOJS_ORG_MIRROR`
  - `GTK2_MODULES`
  - `LANGUAGE`
  - `QT4_IM_MODULE`
  - `MANDATORY_PATH`
  - `GNOME_SHELL_SESSION_MODE`
  - `SSH_AUTH_SOCK`
  - `XMODIFIERS`
  - `DESKTOP_SESSION`
  - `SSH_AGENT_PID`
  - `GTK_MODULES`
  - `PWD`
  - `XDG_SESSION_DESKTOP`
  - `LOGNAME`
  - `XDG_SESSION_TYPE`
  - `MANPATH`
  - `GPG_AGENT_INFO`
  - `XAUTHORITY`
  - `WINDOWPATH`
  - `HOME`
  - `USERNAME`
  - `IM_CONFIG_PHASE`
  - `LANG`
  - `LS_COLORS`
  - `XDG_CURRENT_DESKTOP`
  - `STARSHIP_SHELL`
  - `VTE_VERSION`
  - `GNOME_TERMINAL_SCREEN`
  - `INVOCATION_ID`
  - `MANAGERPID`
  - `CLUTTER_IM_MODULE`
  - `NVM_DIR`
  - `LESSCLOSE`
  - `XDG_SESSION_CLASS`
  - `TERM`
  - `DEFAULTS_PATH`
  - `ASDF_DIR`
  - `LESSOPEN`
  - `LIBVIRT_DEFAULT_URI`
  - `USER`
  - `GNOME_TERMINAL_SERVICE`
  - `DISPLAY`
  - `SHLVL`
  - `NVM_CD_FLAGS`
  - `QT_IM_MODULE`
  - `XDG_RUNTIME_DIR`
  - `NVM_NODEJS_ORG_MIRROR`
  - `JOURNAL_STREAM`
  - `ELIXIR_VERSION`
  - `XDG_DATA_DIRS`
  - `GDMSESSION`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `NVM_BIN`
  - `WASMER_CACHE_DIR`
  - `MIX_ARCHIVES`
  - `WASMER_DIR`
  - `OLDPWD`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/xyz/.asdf/installs/python/3.8.0/bin:/home/xyz/.asdf/shims:/home/xyz/.asdf/bin:/home/xyz/.kiex/elixirs/elixir-1.9.0/bin:/home/xyz/.kiex/bin:/home/xyz/.wasmer/bin:/home/xyz/.wasmer/globals/wapm_packages/.bin:/home/xyz/.deno/bin:/home/xyz/binaryen/bin/:/home/xyz/emsdk/emscripten/1.38.11/:/home/xyz/wabt/bin:/home/xyz/.asdf/installs/rust/1.37.0/bin:/home/xyz/github/development/flutter/bin:/home/xyz/bin:/home/xyz/.nvm/versions/node/v12.4.0/bin:/home/xyz/.local/share/umake/swift/swift-lang/usr/bin:/home/xyz/.cargo/bin:/home/xyz/bin:/home/xyz/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/xyz/istio-1.0.0/bin:/snap/bin:/var/lib/snapd/snap/bin:/home/xyz/Android/Sdk/:/home/xyz/Android/Sdk/tools:/home/xyz/Android/Sdk/platform-tools:/home/xyz/Android/Sdk/build-tools`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_IN`
  - `PWD`: `/home/xyz/experiments/python-workspace/flask-fullstack`

---------------------------

Contents of `Pipfile` ('/home/xyz/experiments/python-workspace/flask-fullstack/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
ipython = "*"

[packages]
flask = "*"
jinja2 = "*"
markupsafe = "*"
werkzeug = "*"
itsdangerous = "*"
wsgiref = "0.1.2"

[requires]
python_version = "3.8.0"

```

Contents of `Pipfile.lock` ('/home/xyz/experiments/python-workspace/flask-fullstack/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "01e7879125788fbc3d6bb85da23044efb4435599268798b28198f7edf6444b8b"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8.0"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "click": {
            "hashes": [
                "sha256:2335065e6395b9e67ca716de5f7526736bfa6ceead690adf616d925bdc622b13",
                "sha256:5b94b49521f6456670fdb30cd82a4eca9412788a93fa6dd6df72c94d5a8ff2d7"
            ],
            "version": "==7.0"
        },
        "flask": {
            "hashes": [
                "sha256:13f9f196f330c7c2c5d7a5cf91af894110ca0215ac051b5844701f2bfd934d52",
                "sha256:45eb5a6fd193d6cf7e0cf5d8a5b31f83d5faae0293695626f539a823e93b13f6"
            ],
            "index": "pypi",
            "version": "==1.1.1"
        },
        "itsdangerous": {
            "hashes": [
                "sha256:321b033d07f2a4136d3ec762eac9f16a10ccd60f53c0c91af90217ace7ba1f19",
                "sha256:b12271b2047cb23eeb98c8b5622e2e5c5e9abd9784a153e9d8ef9cb4dd09d749"
            ],
            "index": "pypi",
            "version": "==1.1.0"
        },
        "jinja2": {
            "hashes": [
                "sha256:74320bb91f31270f9551d46522e33af46a80c3d619f4a4bf42b3164d30b5911f",
                "sha256:9fe95f19286cfefaa917656583d020be14e7859c6b0252588391e47db34527de"
            ],
            "index": "pypi",
            "version": "==2.10.3"
        },
        "markupsafe": {
            "hashes": [
                "sha256:00bc623926325b26bb9605ae9eae8a215691f33cae5df11ca5424f06f2d1f473",
                "sha256:09027a7803a62ca78792ad89403b1b7a73a01c8cb65909cd876f7fcebd79b161",
                "sha256:09c4b7f37d6c648cb13f9230d847adf22f8171b1ccc4d5682398e77f40309235",
                "sha256:1027c282dad077d0bae18be6794e6b6b8c91d58ed8a8d89a89d59693b9131db5",
                "sha256:24982cc2533820871eba85ba648cd53d8623687ff11cbb805be4ff7b4c971aff",
                "sha256:29872e92839765e546828bb7754a68c418d927cd064fd4708fab9fe9c8bb116b",
                "sha256:43a55c2930bbc139570ac2452adf3d70cdbb3cfe5912c71cdce1c2c6bbd9c5d1",
                "sha256:46c99d2de99945ec5cb54f23c8cd5689f6d7177305ebff350a58ce5f8de1669e",
                "sha256:500d4957e52ddc3351cabf489e79c91c17f6e0899158447047588650b5e69183",
                "sha256:535f6fc4d397c1563d08b88e485c3496cf5784e927af890fb3c3aac7f933ec66",
                "sha256:62fe6c95e3ec8a7fad637b7f3d372c15ec1caa01ab47926cfdf7a75b40e0eac1",
                "sha256:6dd73240d2af64df90aa7c4e7481e23825ea70af4b4922f8ede5b9e35f78a3b1",
                "sha256:717ba8fe3ae9cc0006d7c451f0bb265ee07739daf76355d06366154ee68d221e",
                "sha256:79855e1c5b8da654cf486b830bd42c06e8780cea587384cf6545b7d9ac013a0b",
                "sha256:7c1699dfe0cf8ff607dbdcc1e9b9af1755371f92a68f706051cc8c37d447c905",
                "sha256:88e5fcfb52ee7b911e8bb6d6aa2fd21fbecc674eadd44118a9cc3863f938e735",
                "sha256:8defac2f2ccd6805ebf65f5eeb132adcf2ab57aa11fdf4c0dd5169a004710e7d",
                "sha256:98c7086708b163d425c67c7a91bad6e466bb99d797aa64f965e9d25c12111a5e",
                "sha256:9add70b36c5666a2ed02b43b335fe19002ee5235efd4b8a89bfcf9005bebac0d",
                "sha256:9bf40443012702a1d2070043cb6291650a0841ece432556f784f004937f0f32c",
                "sha256:ade5e387d2ad0d7ebf59146cc00c8044acbd863725f887353a10df825fc8ae21",
                "sha256:b00c1de48212e4cc9603895652c5c410df699856a2853135b3967591e4beebc2",
                "sha256:b1282f8c00509d99fef04d8ba936b156d419be841854fe901d8ae224c59f0be5",
                "sha256:b2051432115498d3562c084a49bba65d97cf251f5a331c64a12ee7e04dacc51b",
                "sha256:ba59edeaa2fc6114428f1637ffff42da1e311e29382d81b339c1817d37ec93c6",
                "sha256:c8716a48d94b06bb3b2524c2b77e055fb313aeb4ea620c8dd03a105574ba704f",
                "sha256:cd5df75523866410809ca100dc9681e301e3c27567cf498077e8551b6d20e42f",
                "sha256:e249096428b3ae81b08327a63a485ad0878de3fb939049038579ac0ef61e17e7"
            ],
            "index": "pypi",
            "version": "==1.1.1"
        },
        "werkzeug": {
            "hashes": [
                "sha256:7280924747b5733b246fe23972186c6b348f9ae29724135a6dfc1e53cea433e7",
                "sha256:e5f4a1f98b52b18a93da705a7458e55afb26f32bff83ff5d19189f92462d65c4"
            ],
            "index": "pypi",
            "version": "==0.16.0"
        }
    },
    "develop": {
        "backcall": {
            "hashes": [
                "sha256:38ecd85be2c1e78f77fd91700c76e14667dc21e2713b63876c0eb901196e01e4",
                "sha256:bbbf4b1e5cd2bdb08f915895b51081c041bac22394fdfcfdfbe9f14b77c08bf2"
            ],
            "version": "==0.1.0"
        },
        "decorator": {
            "hashes": [
                "sha256:54c38050039232e1db4ad7375cfce6748d7b41c29e95a081c8a6d2c30364a2ce",
                "sha256:5d19b92a3c8f7f101c8dd86afd86b0f061a8ce4540ab8cd401fa2542756bce6d"
            ],
            "version": "==4.4.1"
        },
        "ipython": {
            "hashes": [
                "sha256:dfd303b270b7b5232b3d08bd30ec6fd685d8a58cabd54055e3d69d8f029f7280",
                "sha256:ed7ebe1cba899c1c3ccad6f7f1c2d2369464cc77dba8eebc65e2043e19cda995"
            ],
            "index": "pypi",
            "version": "==7.9.0"
        },
        "ipython-genutils": {
            "hashes": [
                "sha256:72dd37233799e619666c9f639a9da83c34013a73e8bbc79a7a6348d93c61fab8",
                "sha256:eb2e116e75ecef9d4d228fdc66af54269afa26ab4463042e33785b887c628ba8"
            ],
            "version": "==0.2.0"
        },
        "jedi": {
            "hashes": [
                "sha256:786b6c3d80e2f06fd77162a07fed81b8baa22dde5d62896a790a331d6ac21a27",
                "sha256:ba859c74fa3c966a22f2aeebe1b74ee27e2a462f56d3f5f7ca4a59af61bfe42e"
            ],
            "version": "==0.15.1"
        },
        "parso": {
            "hashes": [
                "sha256:63854233e1fadb5da97f2744b6b24346d2750b85965e7e399bec1620232797dc",
                "sha256:666b0ee4a7a1220f65d367617f2cd3ffddff3e205f3f16a0284df30e774c2a9c"
            ],
            "version": "==0.5.1"
        },
        "pexpect": {
            "hashes": [
                "sha256:2094eefdfcf37a1fdbfb9aa090862c1a4878e5c7e0e7e7088bdb511c558e5cd1",
                "sha256:9e2c1fd0e6ee3a49b28f95d4b33bc389c89b20af6a1255906e90ff1262ce62eb"
            ],
            "markers": "sys_platform != 'win32'",
            "version": "==4.7.0"
        },
        "pickleshare": {
            "hashes": [
                "sha256:87683d47965c1da65cdacaf31c8441d12b8044cdec9aca500cd78fc2c683afca",
                "sha256:9649af414d74d4df115d5d718f82acb59c9d418196b7b4290ed47a12ce62df56"
            ],
            "version": "==0.7.5"
        },
        "prompt-toolkit": {
            "hashes": [
                "sha256:46642344ce457641f28fc9d1c9ca939b63dadf8df128b86f1b9860e59c73a5e4",
                "sha256:e7f8af9e3d70f514373bf41aa51bc33af12a6db3f71461ea47fea985defb2c31",
                "sha256:f15af68f66e664eaa559d4ac8a928111eebd5feda0c11738b5998045224829db"
            ],
            "version": "==2.0.10"
        },
        "ptyprocess": {
            "hashes": [
                "sha256:923f299cc5ad920c68f2bc0bc98b75b9f838b93b599941a6b63ddbc2476394c0",
                "sha256:d7cc528d76e76342423ca640335bd3633420dc1366f258cb31d05e865ef5ca1f"
            ],
            "version": "==0.6.0"
        },
        "pygments": {
            "hashes": [
                "sha256:71e430bc85c88a430f000ac1d9b331d2407f681d6f6aec95e8bcfbc3df5b0127",
                "sha256:881c4c157e45f30af185c1ffe8d549d48ac9127433f2c380c24b84572ad66297"
            ],
            "version": "==2.4.2"
        },
        "six": {
            "hashes": [
                "sha256:1f1b7d42e254082a9db6279deae68afb421ceba6158efa6131de7b3003ee93fd",
                "sha256:30f610279e8b2578cab6db20741130331735c781b56053c59c4076da27f06b66"
            ],
            "version": "==1.13.0"
        },
        "traitlets": {
            "hashes": [
                "sha256:70b4c6a1d9019d7b4f6846832288f86998aa3b9207c6821f3578a6a6a467fe44",
                "sha256:d023ee369ddd2763310e4c3eae1ff649689440d4ae59d7485eb4cfbbe3e359f7"
            ],
            "version": "==4.3.3"
        },
        "wcwidth": {
            "hashes": [
                "sha256:3df37372226d6e63e1b1e1eda15c594bca98a22d33a23832a90998faa96bc65e",
                "sha256:f4ebe71925af7b40a864553f761ed559b43544f8f71746c2d756c7fe788ade7c"
            ],
            "version": "==0.1.7"
        }
    }
}

```
</details>

**Comment by frostming** [comment]
That is mainly because you are trying to install a pypi package which is last updated in 13 years ago on a modern Python version. The more strange part is `wsgiref` package is already built into the Python standard library.

**Comment by ya332** [comment]
Just to help people who come here googling, wsgiref is built into python 3's standard library. just import it and use it.

**Comment by rcsantos695** [comment]
e
This is a standalone release of the wsgiref library, that provides validation support for WSGI 1.0.1 (PEP 3333) for Python **versions < 3.2**, and includes the new wsgiref.util.test() utility function.

For this version’s documentation, see:
