### ISSUE TITLE
Unable to install django-rest-knox via pipenv

### ISSUE THREAD

**Issue by mamtach** [pypa/pipenv#4039]
### Issue description

Current pip versions are
python -m pip --version
pip 19.3.1 (python 3.8)

pipenv --version
pipenv, version 2018.11.26

I am installing django-rest-knox (today only I upgraded python 3.7 to 3.8)
I was able to find solutions for other binaries (which was basically some compatible version for python 3.8), but I did not for pipenv solution for this binary.

One more point that I noticed is:
https://pypi.org/project/django-rest-knox/ says the binary is up to 3.7 version

### Expected result

Successful installation via pipenv

-------------------------------------------------
[**Please note, after investing time on this, I tried to install the binaries one by one ie djangorestframework, django-rest-knox via pycharm and was able to install it successfully** ]

Before upgrading to Python3.8, I was able to install all the binaries via pipenv

Pycharm installed django-rest-knox 4.1.0 version
And I tried same binary version via pipenv, but the output is the same exception as follows:
-------------------------------------------------

### Actual result

Installing django-rest-knox…
Adding django-rest-knox to Pipfile's [packages]…
Installation Succeeded
Pipfile.lock (062e85) out of date, updating to (64c062)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Locking Failed!
Traceback (most recent call last):
  File "..../venv/lib/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "..../venv/lib/site-packages/pipenv/resolver.py", line 118, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system,
  File "..../venv/lib/site-packages/pipenv/resolver.py", line 78, in _main
    results = resolve(
  File "..../venv/lib/site-packages/pipenv/resolver.py", line 61, in resolve
    return resolve_deps(
  File "....\venv\lib\site-packages\pipenv\utils.py", line 718, in resolve_deps
    resolved_tree, hashes, markers_lookup, resolver = actually_resolve_deps(
  File "....\venv\lib\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "....\venv\lib\site-packages\pipenv\utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "....\venv\lib\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "....\venv\lib\site-packages\pipenv\patched\piptools\resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "....\venv\lib\site-packages\pipenv\patched\piptools\resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "....\venv\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "....\venv\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 426, in get_legacy_dependen
cies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "....\venv\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "....\venv\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "....\venv\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 211, in _get_abstract_dist_fo
r
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "....\venv\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 294, in prepare_li
nked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "....\venv\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 127, in prep_for_d
ist
    self.req.run_egg_info()
  File "....\venv\lib\site-packages\pipenv\patched\notpip\_internal\req\req_install.py", line 470, in run_egg_info
    call_subprocess(
  File "....\venv\lib\site-packages\pipenv\patched\notpip\_internal\utils\misc.py", line 703, in call_subprocess
    raise InstallationError(
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\<UNAME>\AppData\Local
\Temp\tmp_meiz6tebuild\psycopg2-binary\
File "..../venv/lib/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "..../venv/lib/site-packages/pipenv/resolver.py", line 118, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system,
  File "..../venv/lib/site-packages/pipenv/resolver.py", line 78, in _main
    results = resolve(
  File "..../venv/lib/site-packages/pipenv/resolver.py", line 61, in resolve
    return resolve_deps(
  File "....\venv\lib\site-packages\pipenv\utils.py", line 718, in resolve_deps
    resolved_tree, hashes, markers_lookup, resolver = actually_resolve_deps(
  File "....\venv\lib\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "....\venv\lib\site-packages\pipenv\utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "....\venv\lib\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "....\venv\lib\site-packages\pipenv\patched\piptools\resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "....\venv\lib\site-packages\pipenv\patched\piptools\resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "....\venv\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "....\venv\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 426, in get_legacy_dependen
cies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "....\venv\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "....\venv\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "....\venv\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 211, in _get_abstract_dist_fo
r
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "....\venv\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 294, in prepare_li
nked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "....\venv\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 127, in prep_for_d
ist
    self.req.run_egg_info()
  File "....\venv\lib\site-packages\pipenv\patched\notpip\_internal\req\req_install.py", line 470, in run_egg_info
    call_subprocess(
  File "....\venv\lib\site-packages\pipenv\patched\notpip\_internal\utils\misc.py", line 703, in call_subprocess
    raise InstallationError(
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\<UNAME>\AppData\Local
\Temp\tmp_meiz6tebuild\psycopg2-binary\

### Steps to replicate

pipenv install django-rest-knox 

------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'venv\\lib\\site-packages\\pipenv'`

Python location: `'venv\\scripts\\python.exe'`

Python installations found:

  - `2018.12`: `C:\Users\Anaconda3\python.exe`
  - `3.8.0`: `C:\Users\AppData\Local\Programs\Python\Python38\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.0',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17763',
 'python_full_version': '3.8.0',
 'python_version': '3.8',
 'sys_platform': 'win32'}
```

System environment variables:

  - `PIPENV_ACTIVE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PLATFORMCODE`
  - `PYCHARM COMMUNITY EDITION`
  - `PROGRAMFILES`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `USERNAME`
  - `PROMPT`
  - `ONLINESERVICES`
  - `ANDROID_HOME`
  - `USERPROFILE`
  - `OS`
  - `NUMBER_OF_PROCESSORS`
  - `SYSTEMDRIVE`
  - `LOCALAPPDATA`
  - `PUBLIC`
  - `PROGRAMDATA`
  - `COMSPEC`
  - `PROCESSOR_REVISION`
  - `COMMONPROGRAMFILES(X86)`
  - `PROCESSOR_IDENTIFIER`
  - `COMMONPROGRAMW6432`
  - `USERDOMAIN`
  - `PROCESSOR_LEVEL`
  - `TEMP`
  - `IDEA_INITIAL_DIRECTORY`
  - `PROGRAMW6432`
  - `APPDATA`
  - `LOGONSERVER`
  - `PSMODULEPATH`
  - `INTELLIJ IDEA COMMUNITY EDITION`
  - `PATHEXT`
  - `TERMINAL_EMULATOR`
  - `JAVA_HOME`
  - `CHOCOLATEYLASTPATHUPDATE`
  - `SYSTEMROOT`
  - `VIRTUAL_ENV`
  - `_OLD_VIRTUAL_PATH`
  - `_OLD_VIRTUAL_PROMPT`
  - `__INTELLIJ_COMMAND_HISTFILE__`
  - `COMPUTERNAME`
  - `SESSIONNAME`
  - `PROGRAMFILES(X86)`
  - `ALLUSERSPROFILE`
  - `HOMEPATH`
  - `DRIVERDATA`
  - `WINDIR`
  - `TMP`
  - `IDEA_JDK`
  - `PATH`
  - `ONEDRIVECONSUMER`
  - `VBOX_MSI_INSTALL_PATH`
  - `HOMEDRIVE`
  - `PROCESSOR_ARCHITECTURE`
  - `CHOCOLATEYINSTALL`
  - `ONEDRIVE`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `REGIONCODE`
  - `COMMONPROGRAMFILES`
  - `PIP_SHIMS_BASE_MODULE`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `C:\Users\.virtualenvs\learn_redux-BmFckT3a\Scripts;C:\Users\PycharmProjects\learn_redux\venv\Scripts;C:\ProgramData\Boxstarter;C
:\Program Files (x86)\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\window
s\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Java\jdk1.8.0_144\bin
;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cm
d;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\In
tel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management
 Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\Sys
tem32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\AppData\Local\Programs\Python\Python38\Scripts\;C:\Use
rs\AppData\Local\Programs\Python\Python38\;C:\Users\AppData\Local\Microsoft\WindowsApps;C:\Users\AppData\Local\atom\bin;F:\Softwares\no
de-v10.13.0-win-x64;C:\Users\AppData\Roaming\npm;C:\Users\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\AppData\Local\GitHubDes
ktop\bin;C:\Program Files\heroku\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.3\bin;;C:\Users\Softwares\flutter\bin;C:\Program F
iles\JetBrains\IntelliJ IDEA Community Edition 2019.1.3\bin;;C:\Users\AppData\Local\Android\Sdk\platform-tools;C:\Program Files\Java\jdk1.8.0_144\b
in;C:\Users\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Git\bin\;C:\Program Files\Git\cmd\;`
  - `VIRTUAL_ENV`: `C:\Users\.virtualenvs\learn_redux-BmFckT3a`

---------------------------

Contents of `Pipfile` ('C:\\Users\\PycharmProjects\\learn_redux\\Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
certifi = "==2019.9.11"
chardet = "==3.0.4"
cycler = "==0.10.0"
defusedxml = "==0.6.0"
dj-database-url = "==0.5.0"
django = "==2.2.7"
grako = "==3.99.9"
gunicorn = "==19.9.0"
idna = "==2.8"
kiwisolver = "==1.1.0"
numpy = "==1.17.2"
oauthlib = "==3.1.0"
pillow = "==6.2.1"
psycopg2-binary = "==2.8.4"
pyjwt = "==1.7.1"
pyparsing = "==2.4.2"
python-dateutil = "==2.8.0"
python-decouple = "==3.1"
python-magic = "==0.4.15"
python3-openid = "==3.1.0"
pytz = "==2019.2"
requests = "==2.22.0"
requests-oauthlib = "==1.2.0"
screeninfo = "==0.4"
six = "==1.12.0"
social-auth-app-django = "==3.1.0"
social-auth-core = "==3.2.0"
sqlparse = "==0.3.0"
urllib3 = "==1.25.6"
whitenoise = "==4.1.3"
django-imagekit = "==4.0.2"
django-bootstrap4 = "==0.0.6"

[requires]
python_version = "3.8"

```

</details>

**Comment by mamtach** [comment]
After looking into the issue, it seems like it was all due to Pipfile Locking failure

I manually unistalled the django-rest-knox api and removed the contents under [packages]
and reran the command, it is a success now

================================
pipenv install django-rest-knox
Installing django-rest-knox…
Adding django-rest-knox to Pipfile's [packages]…
Installation Succeeded
Installing dependencies from Pipfile.lock (3d722c)…
  ================================ 9/9 - 00:00:03

**Comment by wakaryry** [comment]
I got `'<pipenv.patched.notpip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x1100d5810>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known`
