### ISSUE TITLE
Lock creation fails for opennmt-py

### ISSUE THREAD

**Issue by chrislong** [pypa/pipenv#4056]
### Issue description

`pipenv install opennmt-py` installs the package (and its dependencies), but fails when trying to make the lockfile, with:
```

[39m[1mPipfile.lock not found, creatingâ¦[39m[22m
[39m[22mLocking[39m[22m [31m[22m[dev-packages][39m[22m [39m[22mdependenciesâ¦[39m[22m
[39m[22mLocking[39m[22m [31m[22m[packages][39m[22m [39m[22mdependenciesâ¦[39m[22m
[K[?25h[31m[22mâ Locking Failed![39m[22m[0m 
[pipenv.exceptions.ResolutionFailure]:   File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 69, in resolve
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches opennmt-py
[pipenv.exceptions.ResolutionFailure]:       Skipped pre-versions: 1.0.0rc1, 1.0.0rc1, 1.0.0rc2, 1.0.0rc2
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches opennmt-py
Skipped pre-versions: 1.0.0rc1, 1.0.0rc1, 1.0.0rc2, 1.0.0rc2
There are incompatible versions in the resolved dependencies.
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches opennmt-py
[pipenv.exceptions.ResolutionFailure]:       Skipped pre-versions: 1.0.0rc1, 1.0.0rc1, 1.0.0rc2, 1.0.0rc2
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches opennmt-py
Skipped pre-versions: 1.0.0rc1, 1.0.0rc1, 1.0.0rc2, 1.0.0rc2
There are incompatible versions in the resolved dependencies.

```

I think the issue may be the format of the version numbers for opennmt-py (e.g., "1.0.0rc2"), but I'm not sure.

### Expected result

That the installation and locking would succeed.

### Actual result

Here's the verbose output from installing (`pipenv install --verbose opennmt-py`):

```
[39m[1mInstalling [32m[1mopennmt-py[39m[22mâ¦[39m[22m
â [0m Installing...[K[39m[1mInstalling 'opennmt-py'[39m[22m
$ ['/home/HQ/clong/.local/share/virtualenvs/better-nmt-QMP-y1v3/bin/pip', 'install', '--verbose', '--upgrade', 'opennmt-py', '-i', 'https://pypi.org/simple']
[K[39m[1mAdding[39m[22m [32m[1mopennmt-py[39m[22m [39m[1mto Pipfile's[39m[22m [31m[1m[packages][39m[22m[39m[1mâ¦[39m[22m
[K[?25hâ Installation Succeeded[0m 
[39m[1mPipfile.lock not found, creatingâ¦[39m[22m
[39m[22mLocking[39m[22m [31m[22m[dev-packages][39m[22m [39m[22mdependenciesâ¦[39m[22m
[39m[22mLocking[39m[22m [31m[22m[packages][39m[22m [39m[22mdependenciesâ¦[39m[22m
[K[?25h[31m[22mâ Locking Failed![39m[22m[0m 
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  opennmt-py

Finding the best candidates:
Traceback (most recent call last):
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 198, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 198, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 263, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 175, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches opennmt-py
Skipped pre-versions: 1.0.0rc1, 1.0.0rc1, 1.0.0rc2, 1.0.0rc2
There are incompatible versions in the resolved dependencies.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/utils.py", line 395, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches opennmt-py
Skipped pre-versions: 1.0.0rc1, 1.0.0rc1, 1.0.0rc2, 1.0.0rc2
There are incompatible versions in the resolved dependencies.
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  opennmt-py

Finding the best candidates:
Traceback (most recent call last):
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 198, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 198, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 263, in get_best_match
    best_match = self.repository.find_best_match(ireq, prereleases=self.prereleases)
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 175, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches opennmt-py
Skipped pre-versions: 1.0.0rc1, 1.0.0rc1, 1.0.0rc2, 1.0.0rc2
There are incompatible versions in the resolved dependencies.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv/utils.py", line 395, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches opennmt-py
Skipped pre-versions: 1.0.0rc1, 1.0.0rc1, 1.0.0rc2, 1.0.0rc2
There are incompatible versions in the resolved dependencies.
```

### Steps to replicate

Run `pipenv install --verbose opennmt-py`

-------------------------------------------------------------------------------
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/HQ/clong/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.6.9`: `/usr/bin/python3`
  - `3.6.9`: `/usr/bin/python3.6m`
  - `2.7.15`: `/usr/bin/python2`
  - `2.7.0`: `/home/HQ/clong/bin/jython`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.9',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.0.0-37-generic',
 'platform_system': 'Linux',
 'platform_version': '#40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019',
 'python_full_version': '3.6.9',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `GS_LIB`
  - `KDE_FULL_SESSION`
  - `LANG`
  - `DISPLAY`
  - `INSIDE_EMACS`
  - `XDG_VTNR`
  - `PAM_KWALLET5_LOGIN`
  - `SSH_AUTH_SOCK`
  - `MANDATORY_PATH`
  - `XDG_SESSION_ID`
  - `USER`
  - `PAGER`
  - `DESKTOP_SESSION`
  - `GOPATH`
  - `GTK2_RC_FILES`
  - `DEFAULTS_PATH`
  - `PWD`
  - `HOME`
  - `SSH_AGENT_PID`
  - `QT_ACCESSIBILITY`
  - `LIBVIRT_DEFAULT_URI`
  - `XDG_SESSION_TYPE`
  - `XDG_DATA_DIRS`
  - `XDG_SESSION_DESKTOP`
  - `GTK_MODULES`
  - `COLUMNS`
  - `SHELL`
  - `TERM`
  - `XDG_SESSION_CLASS`
  - `XDG_SEAT_PATH`
  - `XCURSOR_THEME`
  - `XDG_CURRENT_DESKTOP`
  - `GPG_AGENT_INFO`
  - `XDG_SEAT`
  - `SHLVL`
  - `GTK_RC_FILES`
  - `LOGNAME`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_RUNTIME_DIR`
  - `PAM_KWALLET_LOGIN`
  - `XAUTHORITY`
  - `XDG_SESSION_PATH`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `XDG_CONFIG_DIRS`
  - `PATH`
  - `KDE_SESSION_UID`
  - `KDE_SESSION_VERSION`
  - `MANWIDTH`
  - `TERMCAP`
  - `SESSION_MANAGER`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenvâspecific environment variables:

Debugâspecific environment variables:

  - `PATH`: `/home/HQ/clong/bin:/home/HQ/clong/.go/bin:/home/HQ/clong/.rbenv/bin:/home/HQ/clong/.rbenv/plugins/ruby-build/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/HQ/clong/git/better/caci/better-nmt`

---------------------------

Contents of `Pipfile` ('/home/HQ/clong/git/better/caci/better-nmt/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
opennmt-py = "*"

[requires]
python_version = "3"

```

</details>
[0m

**Comment by matteius** [comment]
Can this be rechecked on `pipenv=2022.8.19`?
