### ISSUE TITLE
Tests fail on fresh clone

### ISSUE THREAD

**Issue by levinotik** [pypa/pipenv#4057]
### Issue description

Tests fail when running test after cloning project. 

```
pipenv shell
python -m test
```

### Expected result

Tests should pass

### Actual result

Tests fail

```
0:00:03 load avg: 3.58 [ 10/416] test_support
test test_support failed -- Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/test_support.py", line 504, in test_args_from_interpreter_flags
    self.check_options(opts, 'args_from_interpreter_flags')
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/test/test_support.py", line 471, in check_options
    self.assertEqual(proc.stdout.rstrip(), repr(expected))
AssertionError: '' != "['-S']"
+ ['-S']```

**Comment by matteius** [comment]
Check the ci.yml in `.github` for how the test runners setup -- the thing you were probably missing is that the tests depend on sub-repositories that have to be synced with a couple of git commands.
