### ISSUE TITLE
error on python version during the installation twint

### ISSUE THREAD

**Issue by hamidshp** [pypa/pipenv#4069]
hello
i'm trying to use [twint](https://github.com/twintproject/twint) and at the end of installation when i start to use pipenv i have this error 

```
pipenv.patched.notpip._internal.exceptions.UnsupportedPythonVersion: twint requires Python '>=3.6.0' but the running Python is 2.7.17
```

i check out my python version and the output are here: 

```
user@kali:~/twint$ python2 --version
Python 2.7.17
user@kali:~/twint$ python3 --version
Python 3.7.5
```

even i try to istall as root user but at the end pipenv command show this error:

```
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches 3-6-3
No versions found
Was https://pypi.org/simple reachable?
```

i cant understand what happen and what is the problem

----------------------------------------------------------------------------------

$ pipenv --support` out puts are

user@kali:~/twint$ pipenv --support
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/lib/python2.7/dist-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.7.5`: `/usr/bin/python3.7`
  - `3.7.5`: `/usr/bin/python3.7m`
  - `2.7.17`: `/usr/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.3.0-kali2-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Debian 5.3.9-3kali1 (2019-11-20)',
 'python_full_version': '2.7.17',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `MATE_DESKTOP_SESSION_ID`
  - `XDG_GREETER_DATA_DIR`
  - `PYTHONDONTWRITEBYTECODE`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_SESSION_TYPE`
  - `LOGNAME`
  - `XDG_SEAT`
  - `PATH`
  - `XDG_VTNR`
  - `HOME`
  - `DISPLAY`
  - `SSH_AGENT_PID`
  - `XDG_SESSION_DESKTOP`
  - `TERM`
  - `SHELL`
  - `XDG_SESSION_PATH`
  - `XAUTHORITY`
  - `SESSION_MANAGER`
  - `SHLVL`
  - `QT_ACCESSIBILITY`
  - `WINDOWID`
  - `GTK_OVERLAY_SCROLLING`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `GPG_AGENT_INFO`
  - `XDG_SESSION_CLASS`
  - `LANG`
  - `XDG_RUNTIME_DIR`
  - `QT_SCALE_FACTOR`
  - `SSH_AUTH_SOCK`
  - `VTE_VERSION`
  - `GDMSESSION`
  - `PIP_SHIMS_BASE_MODULE`
  - `XDG_SEAT_PATH`
  - `PIP_PYTHON_PATH`
  - `XDG_SESSION_ID`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `_`
  - `DESKTOP_SESSION`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `OLDPWD`
  - `XDG_DATA_DIRS`
  - `PWD`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `COLORTERM`
  - `LS_COLORS`
  - `USER`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/hamid/twint`

---------------------------

Contents of `Pipfile` ('/home/hamid/twint/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
twint = {git = "https://github.com/twintproject/twint.git",editable = true}

[requires]
python_version = "2.7"

```

</details>

**Comment by rmbrad** [comment]
The python version is set to `2.7` in the `Pipfile`:
> ```
> [requires]
> python_version = "2.7"
> ```
It needs to be set to at least `3.6` as required by the `twint` project.

**Comment by hamidshp** [comment]
i change it to 3.6 but the output is :

---------------------------
hamid@Hamidkali:~/twint$ pipenv install -e git+https://github.com/twintproject/twint.git#egg=twint
Warning: Your Pipfile requires python_version 3.6, but you are using 2.7.17 (/home/hamid/.local/share/v/t/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Installing -e git+https://github.com/twintproject/twint.git#egg=twint...
Adding twint to Pipfile's [packages]...
✔ Installation Succeeded 
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
✘ Locking Failed! 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 280, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/resolve.py", line 274, in _resolve_one
    self.requires_python = check_dist_requires_python(dist, absorb=False)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/utils/packaging.py", line 62, in check_dist_requires_python
    '.'.join(map(str, sys.version_info[:3])),)
pipenv.patched.notpip._internal.exceptions.UnsupportedPythonVersion: twint requires Python '>=3.6.0' but the running Python is 2.7.17
File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 280, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/resolve.py", line 274, in _resolve_one
    self.requires_python = check_dist_requires_python(dist, absorb=False)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/notpip/_internal/utils/packaging.py", line 62, in check_dist_requires_python
    '.'.join(map(str, sys.version_info[:3])),)
pipenv.patched.notpip._internal.exceptions.UnsupportedPythonVersion: twint requires Python '>=3.6.0' but the running Python is 2.7.17

------------------------------------

i get confused

**Comment by rmbrad** [comment]
You need to set the python version to something that is available on your system, which from your initial issue seems to `3.7`. Then you need to remove the existing virtualenv and recreate it:
```
pipenv --rm
pipenv install ...
```

**Comment by frostming** [comment]
@rmbrad is correct, close it now
