### ISSUE TITLE
every command throw AttributeError: version

### ISSUE THREAD

**Issue by aa13058219642** [pypa/pipenv#4091]
I install a new python_3.6.8_amd64 for pipenv, here is my environment
```
PS E:\Work\Python\python36_64\Scripts> pip list
Package          Version
---------------- ----------
altgraph         0.16.1
certifi          2019.11.28
future           0.18.2
pefile           2019.4.18
pip              19.3.1
pipenv           2018.11.26
PyInstaller      3.5
PyQt5            5.13.2
PyQt5-sip        12.7.0
pywin32          227
pywin32-ctypes   0.2.0
setuptools       44.0.0
six              1.13.0
virtualenv       16.7.9
virtualenv-clone 0.5.3
```

but I can't run any pipenv command, what the problem with me

```
PS E:\Work\Python\python36_64\Scripts> pipenv check
Creating a virtualenv for this project…
Pipfile: E:\Work\Python\python36_64\Scripts\Pipfile
Using e:\work\python\python36_64\python.exe (3.6.8) to create virtualenv…
[=   ] Creating virtual environment...Already using interpreter e:\work\python\python36_64\python.exe
Using base prefix 'e:\\work\\python\\python36_64'
New python executable in C:\Users\XXXX\.virtualenvs\Scripts-Asj8jkB5\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

Successfully created virtual environment!
Virtualenv location: C:\Users\XXXX\.virtualenvs\Scripts-Asj8jkB5
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "e:\work\python\python36_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\work\python\python36_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Work\Python\python36_64\Scripts\pipenv.exe\__main__.py", line 7, in <module>
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\cli\command.py", line 450, in check
    pypi_mirror=state.pypi_mirror,
  File "e:\work\python\python36_64\lib\site-packages\pipenv\core.py", line 2347, in do_check
    pypi_mirror=pypi_mirror,
  File "e:\work\python\python36_64\lib\site-packages\pipenv\core.py", line 609, in ensure_project
    validate=validate, skip_requirements=skip_requirements, system=system
  File "e:\work\python\python36_64\lib\site-packages\pipenv\core.py", line 320, in ensure_pipfile
    project.create_pipfile(python=python)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\project.py", line 726, in create_pipfile
    required_python = self.which("python", self.virtualenv_location)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\project.py", line 1083, in which
    result = next(iter(filter(None, (find(finder) for finder in self.finders))), None)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\project.py", line 1083, in <genexpr>
    result = next(iter(filter(None, (find(finder) for finder in self.finders))), None)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 67, in which
    return self.system_path.which(exe)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 54, in system_path
    ignore_unsupported=self.ignore_unsupported,
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 451, in create
    ignore_unsupported=ignore_unsupported,
  File "<attrs generated init 75e45f144e3d5510d54dd5fca6730b98fa0220a9>", line 38, in __init__
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 114, in __attrs_post_init__
    self._setup_windows()
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 213, in _setup_windows
    self.windows_finder = WindowsFinder.create()
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\models\windows.py", line 116, in create
    return cls()
  File "<attrs generated init cccdffcf9b7316cf5497372fd033bc617fd5a3f2>", line 13, in __init__
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\models\windows.py", line 92, in get_versions
    py_version = PythonVersion.from_windows_launcher(version_object)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\models\python.py", line 417, in from_windows_launcher
    creation_dict = cls.parse(launcher_entry.info.version)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\_vendor\pep514tools\_registry.py", line 75, in __getattr__
    raise AttributeError(attr)
AttributeError: version
PS E:\Work\Python\python36_64\Scripts>
```

```
PS E:\Work\Python\python36_64\Scripts> pipenv --support | clip
Traceback (most recent call last):
  File "e:\work\python\python36_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\work\python\python36_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Work\Python\python36_64\Scripts\pipenv.exe\__main__.py", line 7, in <module>
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\click\core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\cli\command.py", line 146, in cli
    get_pipenv_diagnostics()
  File "e:\work\python\python36_64\lib\site-packages\pipenv\help.py", line 33, in get_pipenv_diagnostics
    python_paths = finder.find_all_python_versions()
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 122, in find_all_python_versions
    python_version_dict = getattr(self.system_path, "python_version_dict")
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 54, in system_path
    ignore_unsupported=self.ignore_unsupported,
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 451, in create
    ignore_unsupported=ignore_unsupported,
  File "<attrs generated init 75e45f144e3d5510d54dd5fca6730b98fa0220a9>", line 38, in __init__
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 114, in __attrs_post_init__
    self._setup_windows()
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 213, in _setup_windows
    self.windows_finder = WindowsFinder.create()
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\models\windows.py", line 116, in create
    return cls()
  File "<attrs generated init 0699effb1f3ed01e00bb6b94b10028a6e7b918ed>", line 13, in __init__
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\models\windows.py", line 92, in get_versions
    py_version = PythonVersion.from_windows_launcher(version_object)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\models\python.py", line 417, in from_windows_launcher
    creation_dict = cls.parse(launcher_entry.info.version)
  File "e:\work\python\python36_64\lib\site-packages\pipenv\vendor\pythonfinder\_vendor\pep514tools\_registry.py", line 75, in __getattr__
    raise AttributeError(attr)
AttributeError: version
```

**Comment by aa13058219642** [comment]
all right, like #3764
In regedit `HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore`,  I delete some invalid key, then everything is ok now.
