### ISSUE TITLE
Couldnt create a virtualenv (pipenv) with python 3.9.x

### ISSUE THREAD

**Issue by usta** [pypa/pipenv#4092]
pipenv couldn't work with py3.9.x , 

PS C:\Users\usta\Desktop\abc2> pipenv --verbose --python C:\python39\python.exe
Creating a virtualenv for this project…
Pipfile: C:\Users\usta\Desktop\abc2\Pipfile
Using C:\python39\python.exe (3.9.0a2) to create virtualenv…
[==  ] Creating virtual environment...Already using interpreter C:\python39\python.exe
Using base prefix 'C:\\python39'
New python executable in C:\Users\usta\.virtualenvs\abc2-lAv6PqR6\Scripts\python.exe
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter C:\python39\python.exe

Successfully created virtual environment!
Virtualenv location: C:\Users\usta\.virtualenvs\abc2-lAv6PqR6
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\pipenv.exe\__main__.py", line 7, in <module>
  File "C:\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "C:\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Python39\Lib\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Python39\Lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Python39\Lib\site-packages\pipenv\vendor\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python39\lib\site-packages\pipenv\cli\command.py", line 202, in cli
    ensure_project(
  File "c:\python39\lib\site-packages\pipenv\core.py", line 608, in ensure_project
    ensure_pipfile(
  File "c:\python39\lib\site-packages\pipenv\core.py", line 320, in ensure_pipfile
    project.create_pipfile(python=python)
  File "c:\python39\lib\site-packages\pipenv\project.py", line 697, in create_pipfile
    config_parser = ConfigOptionParser(name=self.name)
TypeError: 'NoneType' object is not callable

PS C:\Users\usta\Desktop\abc2> pipenv --version
pipenv, version 2018.11.26

**Comment by matteius** [comment]
There seems to be multiple reports of this around the same time, this is not known to be an issue anymore.
