### ISSUE TITLE
pipenv fails when run in a jenkins pipeline

### ISSUE THREAD

**Issue by nfplatzke** [pypa/pipenv#4114]
### Issue description
I am attempting to run a jenkins pipeline which utilizes pipenv. 

```
pipenv install --deploy
pipenv --support
pipenv --verbose run ansible-galaxy install -p galaxy_roles -r requirements.yml
```
However, when I get to the step to actually invoke **pipenv run** the pipeline fails. This is the block of commands I am executing.

I can run these commands perfectly fine if I login to the server and execute them manually. However, I believe there is some interaction between the headless nature of the jenkins executor and the pipenv code which is causing problems.

### Expected result

I would expect for the ansible-galaxy command to execute properly. 

### Actual result

14:14:11  + pipenv --verbose run ansible-galaxy install -p galaxy_roles -r requirements.yml
14:14:11  Traceback (most recent call last):
14:14:11    File "/usr/bin/pipenv", line 11, in <module>
14:14:11      sys.exit(cli())
14:14:11    File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
14:14:11      return self.main(*args, **kwargs)
14:14:11    File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
14:14:11      rv = self.invoke(ctx)
14:14:11    File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
14:14:11      return _process_result(sub_ctx.command.invoke(sub_ctx))
14:14:11    File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
14:14:11      return ctx.invoke(self.callback, **ctx.params)
14:14:11    File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
14:14:11      return callback(*args, **kwargs)
14:14:11    File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
14:14:11      return ctx.invoke(f, obj, *args, **kwargs)
14:14:11    File "/usr/lib/python2.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
14:14:11      return callback(*args, **kwargs)
14:14:11    File "/usr/lib/python2.7/site-packages/pipenv/cli/command.py", line 408, in run
14:14:11      command=command, args=args, three=state.three, python=state.python, pypi_mirror=state.pypi_mirror
14:14:11    File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 2328, in do_run
14:14:11      do_run_posix(script, command=command)
14:14:11    File "/usr/lib/python2.7/site-packages/pipenv/core.py", line 2297, in do_run_posix
14:14:11      command_path, command_path, *[os.path.expandvars(arg) for arg in script.args]
14:14:11    File "/usr/lib64/python2.7/os.py", line 314, in execl
14:14:11      execv(file, args)
14:14:11  OSError: [Errno 8] Exec format error

### Steps to replicate

A Jenkinsfile that looks like this
```
pipeline {
    environment {
        // pyenv
        PYENV_ROOT="$HOME/.pyenv"
        PYENV_SHELL="bash"
        // pipenv
        PIPENV_YES="true"
        PIPENV_NOSPIN="YES"
        WORKON_HOME="$WORKSPACE/venv"
        PATH="$PYENV_ROOT/bin:/opt/packer:$PATH"
    }

    stages {
        stage('Initialize') {
            steps {
                    sh '''
                    eval "$(pyenv init -)"
                    pipenv install --deploy
                    pipenv --support
                    pipenv --verbose run ansible-galaxy install -p galaxy_roles -r requirements.yml
                    '''
            }
        }
    }
}
```

-------------------------------------------------------------------------------
+ pipenv --support
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/bin/python2'`

Python installations found:

  - `3.6.10`: `/home/ec2-user/.pyenv/versions/3.6.10/bin/python3`
  - `3.6.10`: `/home/ec2-user/.pyenv/versions/3.6.10/bin/python3.6m`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.14.158-129.185.amzn2.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Tue Dec 24 03:15:32 UTC 2019',
 'python_full_version': '2.7.16',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `JENKINS_HOME`
  - `JOB_BASE_NAME`
  - `HUDSON_URL`
  - `BUILD_URL`
  - `LESSOPEN`
  - `PYTHONDONTWRITEBYTECODE`
  - `GIT_PREVIOUS_COMMIT`
  - `BUILD_TAG`
  - `HUDSON_SERVER_COOKIE`
  - `JENKINS_URL`
  - `LOGNAME`
  - `USER`
  - `WORKSPACE`
  - `HOME`
  - `PATH`
  - `NODE_NAME`
  - `PYENV_VIRTUALENV_INIT`
  - `LANG`
  - `RUN_DISPLAY_URL`
  - `TERM`
  - `SHELL`
  - `AMI_KEY`
  - `GIT_PREVIOUS_SUCCESSFUL_COMMIT`
  - `PYENV_SHELL`
  - `SHLVL`
  - `GIT_AUTHOR_EMAIL`
  - `PWD`
  - `HUDSON_HOME`
  - `JOB_NAME`
  - `NODE_LABELS`
  - `PIPENV_YES`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `BUILD_ID`
  - `WORKON_HOME`
  - `AMI_NAME`
  - `BUILD_NUMBER`
  - `XDG_RUNTIME_DIR`
  - `HUDSON_COOKIE`
  - `JOB_URL`
  - `SSH_AUTH_SOCK`
  - `STAGE_NAME`
  - `JENKINS_NODE_COOKIE`
  - `GIT_BRANCH`
  - `GIT_COMMIT`
  - `RUN_CHANGES_DISPLAY_URL`
  - `PIP_PYTHON_PATH`
  - `GIT_COMMITTER_NAME`
  - `XDG_SESSION_ID`
  - `_`
  - `AWS_DEFAULT_REGION`
  - `PIPENV_NOSPIN`
  - `JOB_DISPLAY_URL`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `SSH_CLIENT`
  - `EXECUTOR_NUMBER`
  - `PYENV_ROOT`
  - `PIP_SHIMS_BASE_MODULE`
  - `JE_GIT_URL`
  - `GIT_COMMITTER_EMAIL`
  - `JENKINS_SERVER_COOKIE`
  - `BUILD_DISPLAY_NAME`
  - `GIT_AUTHOR_NAME`
  - `MAIL`
  - `SSH_CONNECTION`
  - `GIT_URL`

Pipenv–specific environment variables:

 - `PIPENV_YES`: `true`
 - `PIPENV_NOSPIN`: `YES`

Debug–specific environment variables:

  - `PATH`: `/home/ec2-user/.pyenv/shims:/home/ec2-user/.pyenv/bin:/opt/packer:/home/ec2-user/.pyenv/plugins/pyenv-virtualenv/shims:/home/ec2-user/.pyenv/shims:/home/ec2-user/.pyenv/bin:/usr/local/bin:/usr/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/ec2-user/jenkins/workspace/ansible-playbook-jenkins-basic-worker`

---------------------------

Contents of `Pipfile` ('/home/ec2-user/jenkins/workspace/ansible-playbook-jenkins-basic-worker/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
ansible = "==2.5"

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/home/ec2-user/jenkins/workspace/ansible-playbook-jenkins-basic-worker/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "f08383c21e35bb65beb14ea2f7155dfcc3eb5172c424359eb171a6a9fd771b3f"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "ansible": {
            "hashes": [
                "sha256:714ede4b0f5455eb2dd2536d8cabb42ab439f52b5ac902308ad027b46f68e6dc"
            ],
            "index": "pypi",
            "version": "==2.5"
        },
        "bcrypt": {
            "hashes": [
                "sha256:0258f143f3de96b7c14f762c770f5fc56ccd72f8a1857a451c1cd9a655d9ac89",
                "sha256:0b0069c752ec14172c5f78208f1863d7ad6755a6fae6fe76ec2c80d13be41e42",
                "sha256:19a4b72a6ae5bb467fea018b825f0a7d917789bcfe893e53f15c92805d187294",
                "sha256:5432dd7b34107ae8ed6c10a71b4397f1c853bd39a4d6ffa7e35f40584cffd161",
                "sha256:6305557019906466fc42dbc53b46da004e72fd7a551c044a827e572c82191752",
                "sha256:69361315039878c0680be456640f8705d76cb4a3a3fe1e057e0f261b74be4b31",
                "sha256:6fe49a60b25b584e2f4ef175b29d3a83ba63b3a4df1b4c0605b826668d1b6be5",
                "sha256:74a015102e877d0ccd02cdeaa18b32aa7273746914a6c5d0456dd442cb65b99c",
                "sha256:763669a367869786bb4c8fcf731f4175775a5b43f070f50f46f0b59da45375d0",
                "sha256:8b10acde4e1919d6015e1df86d4c217d3b5b01bb7744c36113ea43d529e1c3de",
                "sha256:9fe92406c857409b70a38729dbdf6578caf9228de0aef5bc44f859ffe971a39e",
                "sha256:a190f2a5dbbdbff4b74e3103cef44344bc30e61255beb27310e2aec407766052",
                "sha256:a595c12c618119255c90deb4b046e1ca3bcfad64667c43d1166f2b04bc72db09",
                "sha256:c9457fa5c121e94a58d6505cadca8bed1c64444b83b3204928a866ca2e599105",
                "sha256:cb93f6b2ab0f6853550b74e051d297c27a638719753eb9ff66d1e4072be67133",
                "sha256:ce4e4f0deb51d38b1611a27f330426154f2980e66582dc5f438aad38b5f24fc1",
                "sha256:d7bdc26475679dd073ba0ed2766445bb5b20ca4793ca0db32b399dccc6bc84b7",
                "sha256:ff032765bb8716d9387fd5376d987a937254b0619eff0972779515b5c98820bc"
            ],
            "version": "==3.1.7"
        },
        "cffi": {
            "hashes": [
                "sha256:0b49274afc941c626b605fb59b59c3485c17dc776dc3cc7cc14aca74cc19cc42",
                "sha256:0e3ea92942cb1168e38c05c1d56b0527ce31f1a370f6117f1d490b8dcd6b3a04",
                "sha256:135f69aecbf4517d5b3d6429207b2dff49c876be724ac0c8bf8e1ea99df3d7e5",
                "sha256:19db0cdd6e516f13329cba4903368bff9bb5a9331d3410b1b448daaadc495e54",
                "sha256:2781e9ad0e9d47173c0093321bb5435a9dfae0ed6a762aabafa13108f5f7b2ba",
                "sha256:291f7c42e21d72144bb1c1b2e825ec60f46d0a7468f5346841860454c7aa8f57",
                "sha256:2c5e309ec482556397cb21ede0350c5e82f0eb2621de04b2633588d118da4396",
                "sha256:2e9c80a8c3344a92cb04661115898a9129c074f7ab82011ef4b612f645939f12",
                "sha256:32a262e2b90ffcfdd97c7a5e24a6012a43c61f1f5a57789ad80af1d26c6acd97",
                "sha256:3c9fff570f13480b201e9ab69453108f6d98244a7f495e91b6c654a47486ba43",
                "sha256:415bdc7ca8c1c634a6d7163d43fb0ea885a07e9618a64bda407e04b04333b7db",
                "sha256:42194f54c11abc8583417a7cf4eaff544ce0de8187abaf5d29029c91b1725ad3",
                "sha256:4424e42199e86b21fc4db83bd76909a6fc2a2aefb352cb5414833c030f6ed71b",
                "sha256:4a43c91840bda5f55249413037b7a9b79c90b1184ed504883b72c4df70778579",
                "sha256:599a1e8ff057ac530c9ad1778293c665cb81a791421f46922d80a86473c13346",
                "sha256:5c4fae4e9cdd18c82ba3a134be256e98dc0596af1e7285a3d2602c97dcfa5159",
                "sha256:5ecfa867dea6fabe2a58f03ac9186ea64da1386af2159196da51c4904e11d652",
                "sha256:62f2578358d3a92e4ab2d830cd1c2049c9c0d0e6d3c58322993cc341bdeac22e",
                "sha256:6471a82d5abea994e38d2c2abc77164b4f7fbaaf80261cb98394d5793f11b12a",
                "sha256:6d4f18483d040e18546108eb13b1dfa1000a089bcf8529e30346116ea6240506",
                "sha256:71a608532ab3bd26223c8d841dde43f3516aa5d2bf37b50ac410bb5e99053e8f",
                "sha256:74a1d8c85fb6ff0b30fbfa8ad0ac23cd601a138f7509dc617ebc65ef305bb98d",
                "sha256:7b93a885bb13073afb0aa73ad82059a4c41f4b7d8eb8368980448b52d4c7dc2c",
                "sha256:7d4751da932caaec419d514eaa4215eaf14b612cff66398dd51129ac22680b20",
                "sha256:7f627141a26b551bdebbc4855c1157feeef18241b4b8366ed22a5c7d672ef858",
                "sha256:8169cf44dd8f9071b2b9248c35fc35e8677451c52f795daa2bb4643f32a540bc",
                "sha256:aa00d66c0fab27373ae44ae26a66a9e43ff2a678bf63a9c7c1a9a4d61172827a",
                "sha256:ccb032fda0873254380aa2bfad2582aedc2959186cce61e3a17abc1a55ff89c3",
                "sha256:d754f39e0d1603b5b24a7f8484b22d2904fa551fe865fd0d4c3332f078d20d4e",
                "sha256:d75c461e20e29afc0aee7172a0950157c704ff0dd51613506bd7d82b718e7410",
                "sha256:dcd65317dd15bc0451f3e01c80da2216a31916bdcffd6221ca1202d96584aa25",
                "sha256:e570d3ab32e2c2861c4ebe6ffcad6a8abf9347432a37608fe1fbd157b3f0036b",
                "sha256:fd43a88e045cf992ed09fa724b5315b790525f2676883a6ea64e3263bae6549d"
            ],
            "version": "==1.13.2"
        },
        "cryptography": {
            "hashes": [
                "sha256:02079a6addc7b5140ba0825f542c0869ff4df9a69c360e339ecead5baefa843c",
                "sha256:1df22371fbf2004c6f64e927668734070a8953362cd8370ddd336774d6743595",
                "sha256:369d2346db5934345787451504853ad9d342d7f721ae82d098083e1f49a582ad",
                "sha256:3cda1f0ed8747339bbdf71b9f38ca74c7b592f24f65cdb3ab3765e4b02871651",
                "sha256:44ff04138935882fef7c686878e1c8fd80a723161ad6a98da31e14b7553170c2",
                "sha256:4b1030728872c59687badcca1e225a9103440e467c17d6d1730ab3d2d64bfeff",
                "sha256:58363dbd966afb4f89b3b11dfb8ff200058fbc3b947507675c19ceb46104b48d",
                "sha256:6ec280fb24d27e3d97aa731e16207d58bd8ae94ef6eab97249a2afe4ba643d42",
                "sha256:7270a6c29199adc1297776937a05b59720e8a782531f1f122f2eb8467f9aab4d",
                "sha256:73fd30c57fa2d0a1d7a49c561c40c2f79c7d6c374cc7750e9ac7c99176f6428e",
                "sha256:7f09806ed4fbea8f51585231ba742b58cbcfbfe823ea197d8c89a5e433c7e912",
                "sha256:90df0cc93e1f8d2fba8365fb59a858f51a11a394d64dbf3ef844f783844cc793",
                "sha256:971221ed40f058f5662a604bd1ae6e4521d84e6cad0b7b170564cc34169c8f13",
                "sha256:a518c153a2b5ed6b8cc03f7ae79d5ffad7315ad4569b2d5333a13c38d64bd8d7",
                "sha256:b0de590a8b0979649ebeef8bb9f54394d3a41f66c5584fff4220901739b6b2f0",
                "sha256:b43f53f29816ba1db8525f006fa6f49292e9b029554b3eb56a189a70f2a40879",
                "sha256:d31402aad60ed889c7e57934a03477b572a03af7794fa8fb1780f21ea8f6551f",
                "sha256:de96157ec73458a7f14e3d26f17f8128c959084931e8997b9e655a39c8fde9f9",
                "sha256:df6b4dca2e11865e6cfbfb708e800efb18370f5a46fd601d3755bc7f85b3a8a2",
                "sha256:ecadccc7ba52193963c0475ac9f6fa28ac01e01349a2ca48509667ef41ffd2cf",
                "sha256:fb81c17e0ebe3358486cd8cc3ad78adbae58af12fc2bf2bc0bb84e8090fa5ce8"
            ],
            "version": "==2.8"
        },
        "jinja2": {
            "hashes": [
                "sha256:6e7a3c2934694d59ad334c93dd1b6c96699cf24c53fdb8ec848ac6b23e685734",
                "sha256:d6609ae5ec3d56212ca7d802eda654eaf2310000816ce815361041465b108be4"
            ],
            "version": "==2.11.0"
        },
        "markupsafe": {
            "hashes": [
                "sha256:00bc623926325b26bb9605ae9eae8a215691f33cae5df11ca5424f06f2d1f473",
                "sha256:09027a7803a62ca78792ad89403b1b7a73a01c8cb65909cd876f7fcebd79b161",
                "sha256:09c4b7f37d6c648cb13f9230d847adf22f8171b1ccc4d5682398e77f40309235",
                "sha256:1027c282dad077d0bae18be6794e6b6b8c91d58ed8a8d89a89d59693b9131db5",
                "sha256:13d3144e1e340870b25e7b10b98d779608c02016d5184cfb9927a9f10c689f42",
                "sha256:24982cc2533820871eba85ba648cd53d8623687ff11cbb805be4ff7b4c971aff",
                "sha256:29872e92839765e546828bb7754a68c418d927cd064fd4708fab9fe9c8bb116b",
                "sha256:43a55c2930bbc139570ac2452adf3d70cdbb3cfe5912c71cdce1c2c6bbd9c5d1",
                "sha256:46c99d2de99945ec5cb54f23c8cd5689f6d7177305ebff350a58ce5f8de1669e",
                "sha256:500d4957e52ddc3351cabf489e79c91c17f6e0899158447047588650b5e69183",
                "sha256:535f6fc4d397c1563d08b88e485c3496cf5784e927af890fb3c3aac7f933ec66",
                "sha256:596510de112c685489095da617b5bcbbac7dd6384aeebeda4df6025d0256a81b",
                "sha256:62fe6c95e3ec8a7fad637b7f3d372c15ec1caa01ab47926cfdf7a75b40e0eac1",
                "sha256:6788b695d50a51edb699cb55e35487e430fa21f1ed838122d722e0ff0ac5ba15",
                "sha256:6dd73240d2af64df90aa7c4e7481e23825ea70af4b4922f8ede5b9e35f78a3b1",
                "sha256:717ba8fe3ae9cc0006d7c451f0bb265ee07739daf76355d06366154ee68d221e",
                "sha256:79855e1c5b8da654cf486b830bd42c06e8780cea587384cf6545b7d9ac013a0b",
                "sha256:7c1699dfe0cf8ff607dbdcc1e9b9af1755371f92a68f706051cc8c37d447c905",
                "sha256:88e5fcfb52ee7b911e8bb6d6aa2fd21fbecc674eadd44118a9cc3863f938e735",
                "sha256:8defac2f2ccd6805ebf65f5eeb132adcf2ab57aa11fdf4c0dd5169a004710e7d",
                "sha256:98c7086708b163d425c67c7a91bad6e466bb99d797aa64f965e9d25c12111a5e",
                "sha256:9add70b36c5666a2ed02b43b335fe19002ee5235efd4b8a89bfcf9005bebac0d",
                "sha256:9bf40443012702a1d2070043cb6291650a0841ece432556f784f004937f0f32c",
                "sha256:ade5e387d2ad0d7ebf59146cc00c8044acbd863725f887353a10df825fc8ae21",
                "sha256:b00c1de48212e4cc9603895652c5c410df699856a2853135b3967591e4beebc2",
                "sha256:b1282f8c00509d99fef04d8ba936b156d419be841854fe901d8ae224c59f0be5",
                "sha256:b2051432115498d3562c084a49bba65d97cf251f5a331c64a12ee7e04dacc51b",
                "sha256:ba59edeaa2fc6114428f1637ffff42da1e311e29382d81b339c1817d37ec93c6",
                "sha256:c8716a48d94b06bb3b2524c2b77e055fb313aeb4ea620c8dd03a105574ba704f",
                "sha256:cd5df75523866410809ca100dc9681e301e3c27567cf498077e8551b6d20e42f",
                "sha256:cdb132fc825c38e1aeec2c8aa9338310d29d337bebbd7baa06889d09a60a1fa2",
                "sha256:e249096428b3ae81b08327a63a485ad0878de3fb939049038579ac0ef61e17e7",
                "sha256:e8313f01ba26fbbe36c7be1966a7b7424942f670f38e666995b88d012765b9be"
            ],
            "version": "==1.1.1"
        },
        "paramiko": {
            "hashes": [
                "sha256:920492895db8013f6cc0179293147f830b8c7b21fdfc839b6bad760c27459d9f",
                "sha256:9c980875fa4d2cb751604664e9a2d0f69096643f5be4db1b99599fe114a97b2f"
            ],
            "version": "==2.7.1"
        },
        "pycparser": {
            "hashes": [
                "sha256:a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3"
            ],
            "version": "==2.19"
        },
        "pynacl": {
            "hashes": [
                "sha256:05c26f93964373fc0abe332676cb6735f0ecad27711035b9472751faa8521255",
                "sha256:0c6100edd16fefd1557da078c7a31e7b7d7a52ce39fdca2bec29d4f7b6e7600c",
                "sha256:0d0a8171a68edf51add1e73d2159c4bc19fc0718e79dec51166e940856c2f28e",
                "sha256:1c780712b206317a746ace34c209b8c29dbfd841dfbc02aa27f2084dd3db77ae",
                "sha256:2424c8b9f41aa65bbdbd7a64e73a7450ebb4aa9ddedc6a081e7afcc4c97f7621",
                "sha256:2d23c04e8d709444220557ae48ed01f3f1086439f12dbf11976e849a4926db56",
                "sha256:30f36a9c70450c7878053fa1344aca0145fd47d845270b43a7ee9192a051bf39",
                "sha256:37aa336a317209f1bb099ad177fef0da45be36a2aa664507c5d72015f956c310",
                "sha256:4943decfc5b905748f0756fdd99d4f9498d7064815c4cf3643820c9028b711d1",
                "sha256:53126cd91356342dcae7e209f840212a58dcf1177ad52c1d938d428eebc9fee5",
                "sha256:57ef38a65056e7800859e5ba9e6091053cd06e1038983016effaffe0efcd594a",
                "sha256:5bd61e9b44c543016ce1f6aef48606280e45f892a928ca7068fba30021e9b786",
                "sha256:6482d3017a0c0327a49dddc8bd1074cc730d45db2ccb09c3bac1f8f32d1eb61b",
                "sha256:7d3ce02c0784b7cbcc771a2da6ea51f87e8716004512493a2b69016326301c3b",
                "sha256:a14e499c0f5955dcc3991f785f3f8e2130ed504fa3a7f44009ff458ad6bdd17f",
                "sha256:a39f54ccbcd2757d1d63b0ec00a00980c0b382c62865b61a505163943624ab20",
                "sha256:aabb0c5232910a20eec8563503c153a8e78bbf5459490c49ab31f6adf3f3a415",
                "sha256:bd4ecb473a96ad0f90c20acba4f0bf0df91a4e03a1f4dd6a4bdc9ca75aa3a715",
                "sha256:bf459128feb543cfca16a95f8da31e2e65e4c5257d2f3dfa8c0c1031139c9c92",
                "sha256:e2da3c13307eac601f3de04887624939aca8ee3c9488a0bb0eca4fb9401fc6b1",
                "sha256:f67814c38162f4deb31f68d590771a29d5ae3b1bd64b75cf232308e5c74777e0"
            ],
            "version": "==1.3.0"
        },
        "pyyaml": {
            "hashes": [
                "sha256:059b2ee3194d718896c0ad077dd8c043e5e909d9180f387ce42012662a4946d6",
                "sha256:1cf708e2ac57f3aabc87405f04b86354f66799c8e62c28c5fc5f88b5521b2dbf",
                "sha256:24521fa2890642614558b492b473bee0ac1f8057a7263156b02e8b14c88ce6f5",
                "sha256:4fee71aa5bc6ed9d5f116327c04273e25ae31a3020386916905767ec4fc5317e",
                "sha256:70024e02197337533eef7b85b068212420f950319cc8c580261963aefc75f811",
                "sha256:74782fbd4d4f87ff04159e986886931456a1894c61229be9eaf4de6f6e44b99e",
                "sha256:940532b111b1952befd7db542c370887a8611660d2b9becff75d39355303d82d",
                "sha256:cb1f2f5e426dc9f07a7681419fe39cee823bb74f723f36f70399123f439e9b20",
                "sha256:dbbb2379c19ed6042e8f11f2a2c66d39cceb8aeace421bfc29d085d93eda3689",
                "sha256:e3a057b7a64f1222b56e47bcff5e4b94c4f61faac04c7c4ecb1985e18caa3994",
                "sha256:e9f45bd5b92c7974e59bcd2dcc8631a6b6cc380a904725fce7bc08872e691615"
            ],
            "version": "==5.3"
        },
        "six": {
            "hashes": [
                "sha256:236bdbdce46e6e6a3d61a337c0f8b763ca1e8717c03b369e87a7ec7ce1319c0a",
                "sha256:8f3cd2e254d8f793e7f3d6d9df77b92252b52637291d0f0da013c76ea2724b6c"
            ],
            "version": "==1.14.0"
        }
    },
    "develop": {}
}

```
</details>

**Comment by nfplatzke** [comment]
This issue was due to setting WORKON_HOME to include the WORKSPACE variable, which is an absolute path and when expanded exceeds the line limit for a shebang line, as documented in this ticket for virtualenv. Replacing WORKON_HOME with PIPENV_VENV_IN_PROJECT="true" fixed the issue.
