### ISSUE TITLE
why i can't pipenv install correctlly?

### ISSUE THREAD

**Issue by zoushijing** [pypa/pipenv#4131]
```
C:\Users\user\dayday2>pipenv install
Creating a virtualenv for this project…
Pipfile: C:\Users\user\dayday2\Pipfile
Using f:\python37\python.exe (3.7.2) to create virtualenv…
[==  ] Creating virtual environment...Already using interpreter f:\python37\python.exe
Using base prefix 'f:\\python37'
New python executable in C:\Users\user\.virtualenvs\dayday2-qzS15vbF\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

Successfully created virtual environment!
Virtualenv location: C:\Users\user\.virtualenvs\dayday2-qzS15vbF
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "f:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "f:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\python37\Scripts\pipenv.exe\__main__.py", line 7, in <module>
  File "f:\python37\lib\site-packages\pipenv\vendor\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "f:\python37\lib\site-packages\pipenv\vendor\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "f:\python37\lib\site-packages\pipenv\vendor\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "f:\python37\lib\site-packages\pipenv\vendor\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "f:\python37\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "f:\python37\lib\site-packages\pipenv\vendor\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "f:\python37\lib\site-packages\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "f:\python37\lib\site-packages\pipenv\vendor\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "f:\python37\lib\site-packages\pipenv\cli\command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "f:\python37\lib\site-packages\pipenv\core.py", line 1741, in do_install
    pypi_mirror=pypi_mirror,
  File "f:\python37\lib\site-packages\pipenv\core.py", line 609, in ensure_project
    validate=validate, skip_requirements=skip_requirements, system=system
  File "f:\python37\lib\site-packages\pipenv\core.py", line 320, in ensure_pipfile
    project.create_pipfile(python=python)
  File "f:\python37\lib\site-packages\pipenv\project.py", line 726, in create_pipfile
    required_python = self.which("python", self.virtualenv_location)
  File "f:\python37\lib\site-packages\pipenv\project.py", line 1083, in which
    result = next(iter(filter(None, (find(finder) for finder in self.finders))), None)
  File "f:\python37\lib\site-packages\pipenv\project.py", line 1083, in <genexpr>
    result = next(iter(filter(None, (find(finder) for finder in self.finders))), None)
  File "f:\python37\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 67, in which
    return self.system_path.which(exe)
  File "f:\python37\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 54, in system_path
    ignore_unsupported=self.ignore_unsupported,
  File "f:\python37\lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 451, in create
    ignore_unsupported=ignore_unsupported,
  File "<attrs generated init 75e45f144e3d5510d54dd5fca6730b98fa0220a9>", line 38, in __init__
  File "f:\python37\lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 114, in __attrs_post_init__
    self._setup_windows()
  File "f:\python37\lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 213, in _setup_windows
    self.windows_finder = WindowsFinder.create()
  File "f:\python37\lib\site-packages\pipenv\vendor\pythonfinder\models\windows.py", line 116, in create
    return cls()
  File "<attrs generated init f6457a2e9f831078b38d2a10f8b6c41dfa516980>", line 13, in __init__
  File "f:\python37\lib\site-packages\pipenv\vendor\pythonfinder\models\windows.py", line 92, in get_versions
    py_version = PythonVersion.from_windows_launcher(version_object)
  File "f:\python37\lib\site-packages\pipenv\vendor\pythonfinder\models\python.py", line 417, in from_windows_launcher
    creation_dict = cls.parse(launcher_entry.info.version)
  File "f:\python37\lib\site-packages\pipenv\vendor\pythonfinder\_vendor\pep514tools\_registry.py", line 75, in __getattr__
    raise AttributeError(attr)
AttributeError: version
```

**Comment by sclarson** [comment]
Hi!

This seems very similar to #3764 , please try the steps that ticket took to resolve their issue.

**Comment by matteius** [comment]
I believe this is resolvable now -- but let me know if its still an issue on `pipenv==2022.8.19`
