### ISSUE TITLE
Resolving dependencies from Git fails

### ISSUE THREAD

**Issue by oliversavio** [pypa/pipenv#4157]
I've suddenly noticed our build have started failing at `Running command git clone -q https://githhub...`

pipenv is unable to resolve dependencies that point to GIT. On removing this, it works fine.

Here is the stacktrace.

```
Removed build tracker: '/tmp/pip-req-tracker-rpyppddf'
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1874, in do_install
    keep_outdated=keep_outdated
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1253, in do_init
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 862, in do_install_dependencies
    _cleanup_procs(procs, False, failed_deps_queue, retry=False)
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 681, in _cleanup_procs
    raise exceptions.InstallError(c.dep.name, extra=err_lines)
pipenv.exceptions.InstallError: ERROR: ERROR: Package installation failed...
```

**Comment by amhrasmussen** [comment]
Hi @oliversavio 
More info is needed to fully understand what's going on in your case. Please have a look at this very nice guide: https://github.com/pypa/pipenv/blob/master/CONTRIBUTING.md#bug-reports

**Comment by oliversavio** [comment]
Sure thing, let me try and make this issue easily reproducible.

**Comment by techalchemy** [comment]
@oliversavio Are you able to provide any follow up information? And does this issue continue to occur on the latest pre-release of pipenv (`pip install --upgrade --pre pipenv`)?

Thanks!

**Comment by matteius** [comment]
I believe this is resolvable now -- but let me know if its still an issue on `pipenv==2022.8.19`
