### ISSUE TITLE
pipenv fails when directory name includes '#'

### ISSUE THREAD

**Issue by taisukek** [pypa/pipenv#4173]
### Issue description

pipenv fails when directory name includes '#'
it fails to find the path for pip although pip exists in the exact directory.
```
FileNotFoundError: [Errno 2] No such file or directory: 
'/Users/taisuke/.local/share/virtualenvs/pipenv_test#-yIj6nhED/bin/pip'
```

```
ls /Users/taisuke/.local/share/virtualenvs/pipenv_test#-yIj6nhED/bin/ | grep pip
# pip
# pip-3.8
# pip3
# pip3.8
```

If using symbols for file name is not appropriate, please close the issue.
https://en.wikipedia.org/wiki/Comparison_of_file_systems

### Expected result
pipenv works successfully

### Actual result

```
Creating a Pipfile for this project…
Installing flask…
Adding flask to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success! 
Updated Pipfile.lock (ac8e32)!
Installing dependencies from Pipfile.lock (ac8e32)…
Traceback (most recent call last):▉▉▉▉▉ 0/6 — 00:00:00
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/cli/command.py", line 235, in install
    retcode = do_install(
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/core.py", line 1983, in do_install
    do_init(
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/core.py", line 1246, in do_init
    do_install_dependencies(
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/core.py", line 837, in do_install_dependencies
    batch_install(
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/core.py", line 744, in batch_install
    c = pip_install(
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/core.py", line 1421, in pip_install
    c = delegator.run(pip_command, block=block, env=pip_config)
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/delegator.py", line 336, in run
    c.run(block=block, binary=binary, cwd=cwd, env=env)
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/delegator.py", line 204, in run
    s = PopenSpawn(self._popen_args, **pexpect_kwargs)
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/pexpect/popen_spawn.py", line 53, in __init__
    self.proc = subprocess.Popen(cmd, **kwargs)
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/taisuke/.anyenv/envs/pyenv/versions/3.8.2/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/taisuke/.local/share/virtualenvs/pipenv_test#-yIj6nhED/bin/pip'
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/6 — 00:00:00
```

```
ls /Users/taisuke/.local/share/virtualenvs/pipenv_test#-yIj6nhED/bin/ | grep pip
# pip
# pip-3.8
# pip3
# pip3.8
```

### Steps to replicate

```
mkdir pipenv_test#
cd pipenv_test#
pipenv install flask
```

**Comment by matteius** [comment]
@taisukek It appears this issue at some point was fixed:

```
matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/pipenv-triage
$ mv pipenv-4173/ pipenv-4173#

matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/pipenv-triage
$ cd pipenv-4173#

matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/pipenv-triage/pipenv-4173#
$ pipenv install flask
Creating a virtualenv for this project...
Pipfile: C:\Users\matte\Projects\pipenv-triage\pipenv-4173#\Pipfile
Using default python from C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\python.exe (3.10.5) to create virtualenv...
[=   ] Creating virtual environment...created virtual environment CPython3.10.5.final.0-64 in 2963ms
  creator CPython3Windows(dest=C:\c\users\matte\.virtualenvs\pipenv-4173#-ZYEhmvvJ, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\matte\AppData\Local\pypa\virtualenv)
    added seed packages: pip==22.2.2, setuptools==63.2.0, wheel==0.37.1
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Successfully created virtual environment!
Virtualenv location: \c\Users\matte\.virtualenvs\pipenv-4173#-ZYEhmvvJ
Creating a Pipfile for this project...
Installing flask...
Adding flask to Pipfile's [packages]...
Installation Succeeded
Pipfile.lock not found, creating...
Locking [packages] dependencies...
           Building requirements...
Resolving dependencies...
Success!
Locking [dev-packages] dependencies...
Updated Pipfile.lock (81f117)!
Installing dependencies from Pipfile.lock (81f117)...
  ================================ 0/0 - 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/pipenv-triage/pipenv-4173#
$ pipenv run pip freeze
click==8.1.3
colorama==0.4.5
Flask==2.2.2
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.1
Werkzeug==2.2.2

matte@LAPTOP-N5VSGIBD MINGW64 ~/Projects/pipenv-triage/pipenv-4173#
$ pipenv --venv
\c\Users\matte\.virtualenvs\pipenv-4173#-ZYEhmvvJ
```
