### ISSUE TITLE
How to know what happen?

### ISSUE THREAD

**Issue by heckad** [pypa/pipenv#4203]
```
Running $ pipenv lock then $ pipenv sync.
Locking [dev-packages] dependencies…
Success!
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1
Current constraints:
  importlib-metadata
  pre-commit
  pyflakes
  pytest
  pytest-asyncio
  pytest-coverage

Finding the best candidates:
  found candidate importlib-metadata==1.6.0 (constraint was <any>)
  found candidate pre-commit==2.2.0 (constraint was <any>)
  found candidate pyflakes==2.2.0 (constraint was <any>)
  found candidate pytest==5.4.1 (constraint was <any>)
  found candidate pytest-asyncio==0.10.0 (constraint was <any>)
  found candidate pytest-coverage==0.0 (constraint was <any>)

Finding secondary dependencies:
  pre-commit==2.2.0         requires cfgv>=2.0.0, identify>=1.0.0, nodeenv>=0.11.1, pyyaml>=5.1, toml, virtualenv>=15.2
  pytest-coverage==0.0      requires pytest-cover
  pytest==5.4.1             requires atomicwrites>=1.0; sys_platform == "win32", attrs>=17.4.0, colorama; sys_platform == "win32", more-itertools>=4.0.0, packaging, pluggy<1.0,>=0.12, py>=1.5.0, wcwidth
  importlib-metadata==1.6.0 requires zipp>=0.5
  pytest-asyncio==0.10.0    requires pytest>=3.0.6
  pyflakes==2.2.0           requires -

New dependencies found in this round:
  adding ['atomicwrites', '>=1.0', '[]']
  adding ['attrs', '>=17.4.0', '[]']
  adding ['cfgv', '>=2.0.0', '[]']
  adding ['colorama', '', '[]']
  adding ['identify', '>=1.0.0', '[]']
  adding ['more-itertools', '>=4.0.0', '[]']
  adding ['nodeenv', '>=0.11.1', '[]']
  adding ['packaging', '', '[]']
  adding ['pluggy', '<1.0,>=0.12', '[]']
  adding ['py', '>=1.5.0', '[]']
  adding ['pytest', '>=3.0.6', '[]']
  adding ['pytest-cover', '', '[]']
  adding ['pyyaml', '>=5.1', '[]']
  adding ['toml', '', '[]']
  adding ['virtualenv', '>=15.2', '[]']
  adding ['wcwidth', '', '[]']
  adding ['zipp', '>=0.5', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  atomicwrites>=1.0
  attrs>=17.4.0
  cfgv>=2.0.0
  colorama
  identify>=1.0.0
  importlib-metadata
  more-itertools>=4.0.0
  nodeenv>=0.11.1
  packaging
  pluggy<1.0,>=0.12
  pre-commit
  py>=1.5.0
  pyflakes
  pytest>=3.0.6
  pytest-asyncio
  pytest-cover
  pytest-coverage
  pyyaml>=5.1
  toml
  virtualenv>=15.2
  wcwidth
  zipp>=0.5

Finding the best candidates:
  found candidate atomicwrites==1.3.0 (constraint was >=1.0)
  found candidate attrs==19.3.0 (constraint was >=17.4.0)
  found candidate cfgv==3.1.0 (constraint was >=2.0.0)
  found candidate colorama==0.4.3 (constraint was <any>)
  found candidate identify==1.4.14 (constraint was >=1.0.0)
  found candidate importlib-metadata==1.6.0 (constraint was <any>)
  found candidate more-itertools==8.2.0 (constraint was >=4.0.0)
  found candidate nodeenv==1.3.5 (constraint was >=0.11.1)
  found candidate packaging==20.3 (constraint was <any>)
  found candidate pluggy==0.13.1 (constraint was >=0.12,<1.0)
  found candidate pre-commit==2.2.0 (constraint was <any>)
  found candidate py==1.8.1 (constraint was >=1.5.0)
  found candidate pyflakes==2.2.0 (constraint was <any>)
  found candidate pytest==5.4.1 (constraint was >=3.0.6)
  found candidate pytest-asyncio==0.10.0 (constraint was <any>)
  found candidate pytest-cover==3.0.0 (constraint was <any>)
  found candidate pytest-coverage==0.0 (constraint was <any>)
  found candidate pyyaml==5.3.1 (constraint was >=5.1)
  found candidate toml==0.10.0 (constraint was <any>)
  found candidate virtualenv==20.0.18 (constraint was >=15.2)
  found candidate wcwidth==0.1.9 (constraint was <any>)
  found candidate zipp==3.1.0 (constraint was >=0.5)

Finding secondary dependencies:
  more-itertools==8.2.0     requires -
  cfgv==3.1.0               requires -
  pytest-asyncio==0.10.0    requires pytest>=3.0.6
  virtualenv==20.0.18       requires appdirs<2,>=1.4.3, distlib<1,>=0.3.0, filelock<4,>=3.0.0, six<2,>=1.9.0
  pyflakes==2.2.0           requires -
  colorama==0.4.3           requires -
  pytest-coverage==0.0      requires pytest-cover
  pyyaml==5.3.1             requires -
  identify==1.4.14          requires -
  pluggy==0.13.1            requires -
  wcwidth==0.1.9            requires -
  packaging==20.3           requires pyparsing>=2.0.2, six
  nodeenv==1.3.5            requires -
  pytest==5.4.1             requires atomicwrites>=1.0; sys_platform == "win32", attrs>=17.4.0, colorama; sys_platform == "win32", more-itertools>=4.0.0, packaging, pluggy<1.0,>=0.12, py>=1.5.0, wcwidth
  zipp==3.1.0               requires -
  attrs==19.3.0             requires -
  importlib-metadata==1.6.0 requires zipp>=0.5
  pre-commit==2.2.0         requires cfgv>=2.0.0, identify>=1.0.0, nodeenv>=0.11.1, pyyaml>=5.1, toml, virtualenv>=15.2
  atomicwrites==1.3.0       requires -
  py==1.8.1                 requires -
  pytest-cover==3.0.0       requires pytest-cov>=2.0
  toml==0.10.0              requires -

New dependencies found in this round:
  adding ['appdirs', '<2,>=1.4.3', '[]']
  adding ['distlib', '<1,>=0.3.0', '[]']
  adding ['filelock', '<4,>=3.0.0', '[]']
  adding ['pyparsing', '>=2.0.2', '[]']
  adding ['pytest-cov', '>=2.0', '[]']
  adding ['six', '<2,>=1.9.0', '[]']
Removed dependencies in this round:
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 2: not stable

                          ROUND 3
Current constraints:
  appdirs<2,>=1.4.3
  atomicwrites>=1.0
  attrs>=17.4.0
  cfgv>=2.0.0
  colorama
  distlib<1,>=0.3.0
  filelock<4,>=3.0.0
  identify>=1.0.0
  importlib-metadata
  more-itertools>=4.0.0
  nodeenv>=0.11.1
  packaging
  pluggy<1.0,>=0.12
  pre-commit
  py>=1.5.0
  pyflakes
  pyparsing>=2.0.2
  pytest>=3.0.6
  pytest-asyncio
  pytest-cov>=2.0
  pytest-cover
  pytest-coverage
  pyyaml>=5.1
  six<2,>=1.9.0
  toml
  virtualenv>=15.2
  wcwidth
  zipp>=0.5

Finding the best candidates:
  found candidate appdirs==1.4.3 (constraint was >=1.4.3,<2)
  found candidate atomicwrites==1.3.0 (constraint was >=1.0)
  found candidate attrs==19.3.0 (constraint was >=17.4.0)
  found candidate cfgv==3.1.0 (constraint was >=2.0.0)
  found candidate colorama==0.4.3 (constraint was <any>)
  found candidate distlib==0.3.0 (constraint was >=0.3.0,<1)
  found candidate filelock==3.0.12 (constraint was >=3.0.0,<4)
  found candidate identify==1.4.14 (constraint was >=1.0.0)
  found candidate importlib-metadata==1.6.0 (constraint was <any>)
  found candidate more-itertools==8.2.0 (constraint was >=4.0.0)
  found candidate nodeenv==1.3.5 (constraint was >=0.11.1)
  found candidate packaging==20.3 (constraint was <any>)
  found candidate pluggy==0.13.1 (constraint was >=0.12,<1.0)
  found candidate pre-commit==2.2.0 (constraint was <any>)
  found candidate py==1.8.1 (constraint was >=1.5.0)
  found candidate pyflakes==2.2.0 (constraint was <any>)
  found candidate pyparsing==2.4.7 (constraint was >=2.0.2)
  found candidate pytest==5.4.1 (constraint was >=3.0.6)
  found candidate pytest-asyncio==0.10.0 (constraint was <any>)
  found candidate pytest-cov==2.8.1 (constraint was >=2.0)
  found candidate pytest-cover==3.0.0 (constraint was <any>)
  found candidate pytest-coverage==0.0 (constraint was <any>)
  found candidate pyyaml==5.3.1 (constraint was >=5.1)
  found candidate six==1.14.0 (constraint was >=1.9.0,<2)
  found candidate toml==0.10.0 (constraint was <any>)
  found candidate virtualenv==20.0.18 (constraint was >=15.2)
  found candidate wcwidth==0.1.9 (constraint was <any>)
  found candidate zipp==3.1.0 (constraint was >=0.5)

Finding secondary dependencies:
  zipp==3.1.0               requires -
  filelock==3.0.12          requires -
  pytest-coverage==0.0      requires pytest-cover
  virtualenv==20.0.18       requires appdirs<2,>=1.4.3, distlib<1,>=0.3.0, filelock<4,>=3.0.0, six<2,>=1.9.0
  pyyaml==5.3.1             requires -
  appdirs==1.4.3            requires -
  colorama==0.4.3           requires -
  packaging==20.3           requires pyparsing>=2.0.2, six
  cfgv==3.1.0               requires -
  pytest-cov==2.8.1         requires coverage>=4.4, pytest>=3.6
  pytest-asyncio==0.10.0    requires pytest>=3.0.6
  pytest==5.4.1             requires atomicwrites>=1.0; sys_platform == "win32", attrs>=17.4.0, colorama; sys_platform == "win32", more-itertools>=4.0.0, packaging, pluggy<1.0,>=0.12, py>=1.5.0, wcwidth
  importlib-metadata==1.6.0 requires zipp>=0.5
  distlib==0.3.0            requires -
  six==1.14.0               requires -
  more-itertools==8.2.0     requires -
  pluggy==0.13.1            requires -
  py==1.8.1                 requires -
  pyparsing==2.4.7          requires -
  pytest-cover==3.0.0       requires pytest-cov>=2.0
  identify==1.4.14          requires -
  wcwidth==0.1.9            requires -
  atomicwrites==1.3.0       requires -
  attrs==19.3.0             requires -
  toml==0.10.0              requires -
  pre-commit==2.2.0         requires cfgv>=2.0.0, identify>=1.0.0, nodeenv>=0.11.1, pyyaml>=5.1, toml, virtualenv>=15.2
  nodeenv==1.3.5            requires -
  pyflakes==2.2.0           requires -

New dependencies found in this round:
  adding ['coverage', '>=4.4', '[]']
  adding ['pytest', '>=3.0.6,>=3.6', '[]']
Removed dependencies in this round:
  removing ['pytest', '>=3.0.6', '[]']
Unsafe dependencies in this round:
------------------------------------------------------------
Result of round 3: not stable

                          ROUND 4
Current constraints:
  appdirs<2,>=1.4.3
  atomicwrites>=1.0
  attrs>=17.4.0
  cfgv>=2.0.0
  colorama
  coverage>=4.4
  distlib<1,>=0.3.0
  filelock<4,>=3.0.0
  identify>=1.0.0
  importlib-metadata
  more-itertools>=4.0.0
  nodeenv>=0.11.1
  packaging
  pluggy<1.0,>=0.12
  pre-commit
  py>=1.5.0
  pyflakes
  pyparsing>=2.0.2
  pytest>=3.0.6,>=3.6
  pytest-asyncio
  pytest-cov>=2.0
  pytest-cover
  pytest-coverage
  pyyaml>=5.1
  six<2,>=1.9.0
  toml
  virtualenv>=15.2
  wcwidth
  zipp>=0.5

Finding the best candidates:
  found candidate appdirs==1.4.3 (constraint was >=1.4.3,<2)
  found candidate atomicwrites==1.3.0 (constraint was >=1.0)
  found candidate attrs==19.3.0 (constraint was >=17.4.0)
  found candidate cfgv==3.1.0 (constraint was >=2.0.0)
  found candidate colorama==0.4.3 (constraint was <any>)
  found candidate coverage==5.1 (constraint was >=4.4)
  found candidate distlib==0.3.0 (constraint was >=0.3.0,<1)
  found candidate filelock==3.0.12 (constraint was >=3.0.0,<4)
  found candidate identify==1.4.14 (constraint was >=1.0.0)
  found candidate importlib-metadata==1.6.0 (constraint was <any>)
  found candidate more-itertools==8.2.0 (constraint was >=4.0.0)
  found candidate nodeenv==1.3.5 (constraint was >=0.11.1)
  found candidate packaging==20.3 (constraint was <any>)
  found candidate pluggy==0.13.1 (constraint was >=0.12,<1.0)
  found candidate pre-commit==2.2.0 (constraint was <any>)
  found candidate py==1.8.1 (constraint was >=1.5.0)
  found candidate pyflakes==2.2.0 (constraint was <any>)
  found candidate pyparsing==2.4.7 (constraint was >=2.0.2)
  found candidate pytest==5.4.1 (constraint was >=3.0.6,>=3.6)
  found candidate pytest-asyncio==0.10.0 (constraint was <any>)
  found candidate pytest-cov==2.8.1 (constraint was >=2.0)
  found candidate pytest-cover==3.0.0 (constraint was <any>)
  found candidate pytest-coverage==0.0 (constraint was <any>)
  found candidate pyyaml==5.3.1 (constraint was >=5.1)
  found candidate six==1.14.0 (constraint was >=1.9.0,<2)
  found candidate toml==0.10.0 (constraint was <any>)
  found candidate virtualenv==20.0.18 (constraint was >=15.2)
  found candidate wcwidth==0.1.9 (constraint was <any>)
  found candidate zipp==3.1.0 (constraint was >=0.5)

Finding secondary dependencies:
  packaging==20.3           requires pyparsing>=2.0.2, six
  colorama==0.4.3           requires -
  identify==1.4.14          requires -
  virtualenv==20.0.18       requires appdirs<2,>=1.4.3, distlib<1,>=0.3.0, filelock<4,>=3.0.0, six<2,>=1.9.0
  nodeenv==1.3.5            requires -
  pytest==5.4.1             requires atomicwrites>=1.0; sys_platform == "win32", attrs>=17.4.0, colorama; sys_platform == "win32", more-itertools>=4.0.0, packaging, pluggy<1.0,>=0.12, py>=1.5.0, wcwidth
  pyflakes==2.2.0           requires -
  py==1.8.1                 requires -
  pytest-cov==2.8.1         requires coverage>=4.4, pytest>=3.6
  wcwidth==0.1.9            requires -
  cfgv==3.1.0               requires -
  distlib==0.3.0            requires -
  pyparsing==2.4.7          requires -
  importlib-metadata==1.6.0 requires zipp>=0.5
  filelock==3.0.12          requires -
  pluggy==0.13.1            requires -
  six==1.14.0               requires -
  atomicwrites==1.3.0       requires -
  zipp==3.1.0               requires -
  coverage==5.1             requires -
  appdirs==1.4.3            requires -
  pre-commit==2.2.0         requires cfgv>=2.0.0, identify>=1.0.0, nodeenv>=0.11.1, pyyaml>=5.1, toml, virtualenv>=15.2
  pyyaml==5.3.1             requires -
  more-itertools==8.2.0     requires -
  pytest-cover==3.0.0       requires pytest-cov>=2.0
  pytest-asyncio==0.10.0    requires pytest>=3.0.6
  attrs==19.3.0             requires -
  pytest-coverage==0.0      requires pytest-cover
  toml==0.10.0              requires -
------------------------------------------------------------
Result of round 4: stable, done


Locking [packages] dependencies…
Locking Failed!
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1
Current constraints:
  aio-pika
  aiojobs
  loguru
  marshmallow
  marshmallow-dataclass
  marshmallow-enum
  marshmallow-sqlalchemy
  psycopg2-binary
  sentry-sdk
  sqlalchemy
  sqlalchemy-utils

Finding the best candidates:
  found candidate aio-pika==6.6.0 (constraint was <any>)
  found candidate aiojobs==0.2.2 (constraint was <any>)
  found candidate loguru==0.4.1 (constraint was <any>)
  found candidate marshmallow==3.5.1 (constraint was <any>)
  found candidate marshmallow-dataclass==7.5.0 (constraint was <any>)
  found candidate marshmallow-enum==1.5.1 (constraint was <any>)
  found candidate marshmallow-sqlalchemy==0.22.3 (constraint was <any>)
  found candidate psycopg2-binary==2.8.5 (constraint was <any>)
  found candidate sentry-sdk==0.14.3 (constraint was <any>)
  found candidate sqlalchemy==1.3.16 (constraint was <any>)
  found candidate sqlalchemy-utils==0.36.3 (constraint was <any>)

Finding secondary dependencies:
  marshmallow-sqlalchemy==0.22.3 requires marshmallow>=2.15.2, sqlalchemy>=1.2.0
  sentry-sdk==0.14.3        requires certifi, urllib3>=1.10.0
  marshmallow-dataclass==7.5.0 requires marshmallow<4.0,>=3.0.0, typing-inspect
  aio-pika==6.6.0           requires aiormq<4,>=3.2.0, yarl
  aiojobs==0.2.2            requires aiohttp>=2.3.0
  sqlalchemy==1.3.16        requires -
  marshmallow-enum==1.5.1   requires marshmallow>=2.0.0
  psycopg2-binary==2.8.5 not in cache, need to check index
Traceback (most recent call last):
  File "c:/program files/python38/lib/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "c:/program files/python38/lib/site-packages/pipenv/resolver.py", line 118, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system,
  File "c:/program files/python38/lib/site-packages/pipenv/resolver.py", line 78, in _main
    results = resolve(
  File "c:/program files/python38/lib/site-packages/pipenv/resolver.py", line 61, in resolve
    return resolve_deps(
  File "c:\program files\python38\lib\site-packages\pipenv\utils.py", line 718, in resolve_deps
    resolved_tree, hashes, markers_lookup, resolver = actually_resolve_deps(
  File "c:\program files\python38\lib\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "c:\program files\python38\lib\site-packages\pipenv\utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "c:\program files\python38\lib\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "c:\program files\python38\lib\site-packages\pipenv\patched\piptools\resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "c:\program files\python38\lib\site-packages\pipenv\patched\piptools\resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "c:\program files\python38\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "c:\program files\python38\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "c:\program files\python38\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "c:\program files\python38\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\program files\python38\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 211, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "c:\program files\python38\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "c:\program files\python38\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "c:\program files\python38\lib\site-packages\pipenv\patched\notpip\_internal\req\req_install.py", line 470, in run_egg_info
    call_subprocess(
  File "c:\program files\python38\lib\site-packages\pipenv\patched\notpip\_internal\utils\misc.py", line 703, in call_subprocess
    raise InstallationError(
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\Asus\AppData\Local\Temp\tmpjaynervobuild\psycopg2-binary\
Using pip: -i https://pypi.org/simple
Using pip: -i https://pypi.org/simple

                          ROUND 1
Current constraints:
  aio-pika
  aiojobs
  loguru
  marshmallow
  marshmallow-dataclass
  marshmallow-enum
  marshmallow-sqlalchemy
  psycopg2-binary
  sentry-sdk
  sqlalchemy
  sqlalchemy-utils

Finding the best candidates:
  found candidate aio-pika==6.6.0 (constraint was <any>)
  found candidate aiojobs==0.2.2 (constraint was <any>)
  found candidate loguru==0.4.1 (constraint was <any>)
  found candidate marshmallow==3.5.1 (constraint was <any>)
  found candidate marshmallow-dataclass==7.5.0 (constraint was <any>)
  found candidate marshmallow-enum==1.5.1 (constraint was <any>)
  found candidate marshmallow-sqlalchemy==0.22.3 (constraint was <any>)
  found candidate psycopg2-binary==2.8.5 (constraint was <any>)
  found candidate sentry-sdk==0.14.3 (constraint was <any>)
  found candidate sqlalchemy==1.3.16 (constraint was <any>)
  found candidate sqlalchemy-utils==0.36.3 (constraint was <any>)

Finding secondary dependencies:
  marshmallow-sqlalchemy==0.22.3 requires marshmallow>=2.15.2, sqlalchemy>=1.2.0
  sentry-sdk==0.14.3        requires certifi, urllib3>=1.10.0
  marshmallow-dataclass==7.5.0 requires marshmallow<4.0,>=3.0.0, typing-inspect
  aio-pika==6.6.0           requires aiormq<4,>=3.2.0, yarl
  aiojobs==0.2.2            requires aiohttp>=2.3.0
  sqlalchemy==1.3.16        requires -
  marshmallow-enum==1.5.1   requires marshmallow>=2.0.0
  psycopg2-binary==2.8.5 not in cache, need to check index
Traceback (most recent call last):
  File "c:/program files/python38/lib/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "c:/program files/python38/lib/site-packages/pipenv/resolver.py", line 118, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system,
  File "c:/program files/python38/lib/site-packages/pipenv/resolver.py", line 78, in _main
    results = resolve(
  File "c:/program files/python38/lib/site-packages/pipenv/resolver.py", line 61, in resolve
    return resolve_deps(
  File "c:\program files\python38\lib\site-packages\pipenv\utils.py", line 718, in resolve_deps
    resolved_tree, hashes, markers_lookup, resolver = actually_resolve_deps(
  File "c:\program files\python38\lib\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "c:\program files\python38\lib\site-packages\pipenv\utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "c:\program files\python38\lib\site-packages\pipenv\patched\piptools\resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "c:\program files\python38\lib\site-packages\pipenv\patched\piptools\resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "c:\program files\python38\lib\site-packages\pipenv\patched\piptools\resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "c:\program files\python38\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "c:\program files\python38\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "c:\program files\python38\lib\site-packages\pipenv\patched\piptools\repositories\pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "c:\program files\python38\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\program files\python38\lib\site-packages\pipenv\patched\notpip\_internal\resolve.py", line 211, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "c:\program files\python38\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 294, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "c:\program files\python38\lib\site-packages\pipenv\patched\notpip\_internal\operations\prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "c:\program files\python38\lib\site-packages\pipenv\patched\notpip\_internal\req\req_install.py", line 470, in run_egg_info
    call_subprocess(
  File "c:\program files\python38\lib\site-packages\pipenv\patched\notpip\_internal\utils\misc.py", line 703, in call_subprocess
    raise InstallationError(
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\Asus\AppData\Local\Temp\tmpjaynervobuild\psycopg2-binary\
```
Thats all what verbose mode printed. How to know what happen? Whete debug mode? Why not printed output of executed command?

**Comment by Hammond95** [comment]
Could you please share your Pipfile and the command that you ran?

**Comment by frostming** [comment]
Seems duplicate with #4073 , close it now
