### ISSUE TITLE
`make test` on master fails - error while installing pyenchant==2.0.0

### ISSUE THREAD

**Issue by MKaras93** [pypa/pipenv#4224]
### Issue description

I want to contribute to pipenv. Unfortunately, testing the version on `master` branch with `make test` fails because it runs on an error when installing pyenchant==2.0.0.

### Expected result

Testing the master version should pass smoothly.

### Actual result

```
$ make test
docker-compose up
Starting pipenv_pipenv-tests_1 ... done
Attaching to pipenv_pipenv-tests_1
pipenv-tests_1  | DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
pipenv-tests_1  | Requirement already satisfied: certifi in /usr/local/lib/python2.7/dist-packages (2020.4.5.1)
pipenv-tests_1  | Path: /root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
pipenv-tests_1  | Installing Pipenv…
pipenv-tests_1  | DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
pipenv-tests_1  | Obtaining file:///pipenv
pipenv-tests_1  |   Installing build dependencies: started
pipenv-tests_1  |   Installing build dependencies: finished with status 'done'
pipenv-tests_1  |   Getting requirements to build wheel: started
pipenv-tests_1  |   Getting requirements to build wheel: finished with status 'done'
pipenv-tests_1  |     Preparing wheel metadata: started
pipenv-tests_1  |     Preparing wheel metadata: finished with status 'done'
pipenv-tests_1  | Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages (44.1.0)
pipenv-tests_1  | Requirement already up-to-date: wheel in /usr/local/lib/python2.7/dist-packages (0.34.2)
pipenv-tests_1  | Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (20.1)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: enum34; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from pipenv==2020.4.29.dev0) (1.1.10)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: certifi in /usr/local/lib/python2.7/dist-packages (from pipenv==2020.4.29.dev0) (2020.4.5.1)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: virtualenv-clone>=0.2.5 in /usr/local/lib/python2.7/dist-packages (from pipenv==2020.4.29.dev0) (0.5.4)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: virtualenv in /usr/local/lib/python2.7/dist-packages (from pipenv==2020.4.29.dev0) (20.0.18)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: typing; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from pipenv==2020.4.29.dev0) (3.7.4.1)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: importlib-metadata<2,>=0.12; python_version < "3.8" in /usr/local/lib/python2.7/dist-packages (from virtualenv->pipenv==2020.4.29.dev0) (1.6.0)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32" in /usr/local/lib/python2.7/dist-packages (from virtualenv->pipenv==2020.4.29.dev0) (2.3.5)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: importlib-resources<2,>=1.0; python_version < "3.7" in /usr/local/lib/python2.7/dist-packages (from virtualenv->pipenv==2020.4.29.dev0) (1.5.0)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: filelock<4,>=3.0.0 in /usr/local/lib/python2.7/dist-packages (from virtualenv->pipenv==2020.4.29.dev0) (3.0.12)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: contextlib2<1,>=0.6.0; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from virtualenv->pipenv==2020.4.29.dev0) (0.6.0.post1)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: appdirs<2,>=1.4.3 in /usr/local/lib/python2.7/dist-packages (from virtualenv->pipenv==2020.4.29.dev0) (1.4.3)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: six<2,>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from virtualenv->pipenv==2020.4.29.dev0) (1.14.0)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: distlib<1,>=0.3.0 in /usr/local/lib/python2.7/dist-packages (from virtualenv->pipenv==2020.4.29.dev0) (0.3.0)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: zipp>=0.5 in /usr/local/lib/python2.7/dist-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv->pipenv==2020.4.29.dev0) (1.2.0)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: configparser>=3.5; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv->pipenv==2020.4.29.dev0) (4.0.2)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: scandir; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32"->virtualenv->pipenv==2020.4.29.dev0) (1.10.0)
pipenv-tests_1  | Requirement already satisfied, skipping upgrade: singledispatch; python_version < "3.4" in /usr/local/lib/python2.7/dist-packages (from importlib-resources<2,>=1.0; python_version < "3.7"->virtualenv->pipenv==2020.4.29.dev0) (3.4.0.3)
pipenv-tests_1  | Installing collected packages: pipenv
pipenv-tests_1  |   Attempting uninstall: pipenv
pipenv-tests_1  |     Found existing installation: pipenv 2020.4.29.dev0
pipenv-tests_1  |     Uninstalling pipenv-2020.4.29.dev0:
pipenv-tests_1  |       Successfully uninstalled pipenv-2020.4.29.dev0
pipenv-tests_1  |   Running setup.py develop for pipenv
pipenv-tests_1  | Successfully installed pipenv
pipenv-tests_1  | $ PIPENV_PYTHON=2.7 python -m pipenv --venv && PIPENV_PYTHON=2.7 pipenv --rm
pipenv-tests_1  | $ PIPENV_PYTHON=3.7 python -m pipenv --venv && PIPENV_PYTHON=3.7 pipenv --rm
pipenv-tests_1  | /root/.local/share/virtualenvs/pipenv-4aiTdSJZ-2.7
pipenv-tests_1  | Removing virtualenv (/root/.local/share/virtualenvs/pipenv-4aiTdSJZ-2.7)…
⠹ Running../root/.local/share/virtualenvs/pipenv-4aiTdSJZ-3.7
pipenv-tests_1  | Removing virtualenv (/root/.local/share/virtualenvs/pipenv-4aiTdSJZ-3.7)…
⠸ Running..Installing dependencies…
pipenv-tests_1  | $ PIPENV_PYTHON=2.7 python -m pipenv install --deploy --dev
pipenv-tests_1  | $ PIPENV_PYTHON=3.7 python -m pipenv install --deploy --dev
pipenv-tests_1  | Creating a virtualenv for this project...
pipenv-tests_1  | Pipfile: /pipenv/Pipfile
pipenv-tests_1  | Creating a virtualenv for this project...
pipenv-tests_1  | Pipfile: /pipenv/Pipfile
pipenv-tests_1  | Using /usr/bin/python2.7 (2.7.15) to create virtualenv...
⠋ Creating virtual environment...Using /usr/bin/python3.6m (3.6.5) to create virtualenv...
⠼ Creating virtual environment...created virtual environment CPython2.7.15.candidate.1-64 in 236ms
pipenv-tests_1  |   creator CPython2Posix(dest=/root/.local/share/virtualenvs/pipenv-4aiTdSJZ-2.7, clear=False, global=False)
pipenv-tests_1  |   seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/root/.local/share/virtualenv/seed-app-data/v1.0.1)
pipenv-tests_1  |   activators PythonActivator,CShellActivator,FishActivator,PowerShellActivator,BashActivator
pipenv-tests_1  | 
pipenv-tests_1  | created virtual environment CPython3.6.5.final.0-64 in 228ms
pipenv-tests_1  |   creator CPython3Posix(dest=/root/.local/share/virtualenvs/pipenv-4aiTdSJZ-3.7, clear=False, global=False)
pipenv-tests_1  |   seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/root/.local/share/virtualenv/seed-app-data/v1.0.1)
pipenv-tests_1  |   activators PythonActivator,FishActivator,XonshActivator,CShellActivator,PowerShellActivator,BashActivator
pipenv-tests_1  | 
pipenv-tests_1  |✔ Successfully created virtual environment! 
pipenv-tests_1  |✔ Successfully created virtual environment! 
pipenv-tests_1  | Virtualenv location: /root/.local/share/virtualenvs/pipenv-4aiTdSJZ-3.7
pipenv-tests_1  | Virtualenv location: /root/.local/share/virtualenvs/pipenv-4aiTdSJZ-2.7
pipenv-tests_1  | Installing dependencies from Pipfile.lock (86f162)...
pipenv-tests_1  | Installing dependencies from Pipfile.lock (86f162)...
pipenv-tests_1  | DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
pipenv-tests_1  | Ignoring black: markers 'python_version >= "3.6"' don't match your environment
pipenv-tests_1  | Ignoring pathlib2: markers 'python_version < "3"' don't match your environment
pipenv-tests_1  | DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
pipenv-tests_1  | Ignoring secretstorage: markers 'sys_platform == "linux"' don't match your environment
pipenv-tests_1  | An error occurred while installing pyenchant==2.0.0 --hash=sha256:fc31cda72ace001da8fe5d42f11c26e514a91fa8c70468739216ddd8de64e2a0 --hash=sha256:b9526fc2c5f1ba0637e50200b645a7c20fb6644dbc6f6322027e7d2fbf1084a5 --hash=sha256:9a66aa441535e27d228baca320f7feed1b08d0c5e6167d5e5cf455b545b7c2cd --hash=sha256:e8000144e61551fcab9cd1b6fdccdded20e577e8d6d0985533f0b2b9c38fd952! Will try again.
pipenv-tests_1  | Ignoring contextlib2: markers 'python_version < "3"' don't match your environment
pipenv-tests_1  | Ignoring funcsigs: markers 'python_version < "3.3"' don't match your environment
pipenv-tests_1  | An error occurred while installing pyenchant==2.0.0 --hash=sha256:fc31cda72ace001da8fe5d42f11c26e514a91fa8c70468739216ddd8de64e2a0 --hash=sha256:b9526fc2c5f1ba0637e50200b645a7c20fb6644dbc6f6322027e7d2fbf1084a5 --hash=sha256:9a66aa441535e27d228baca320f7feed1b08d0c5e6167d5e5cf455b545b7c2cd --hash=sha256:e8000144e61551fcab9cd1b6fdccdded20e577e8d6d0985533f0b2b9c38fd952! Will try again.
pipenv-tests_1  | DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
pipenv-tests_1  | Ignoring jeepney: markers 'sys_platform == "linux"' don't match your environment
pipenv-tests_1  | DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
pipenv-tests_1  | Ignoring typed-ast: markers 'python_version >= "3.4"' don't match your environment
pipenv-tests_1  | DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
pipenv-tests_1  | Ignoring twine: markers 'python_version >= "3.6"' don't match your environment
pipenv-tests_1  | DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
pipenv-tests_1  | Ignoring stdeb: markers 'sys_platform == "linux"' don't match your environment
pipenv-tests_1  | Ignoring typing: markers 'python_version < "3.5"' don't match your environment
pipenv-tests_1  | Ignoring functools32: markers 'python_version < "3.2"' don't match your environment
pipenv-tests_1  | Ignoring backports.functools-lru-cache: markers 'python_version < "3.2"' don't match your environment
pipenv-tests_1  | Ignoring singledispatch: markers 'python_version < "3.4"' don't match your environment
pipenv-tests_1  | Ignoring configparser: markers 'python_version < "3.2"' don't match your environment
pipenv-tests_1  | Ignoring enum34: markers 'python_version < "3"' don't match your environment
pipenv-tests_1  | Ignoring futures: markers 'python_version < "3.2"' don't match your environment
pipenv-tests_1  | DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
pipenv-tests_1  | Ignoring keyring: markers 'python_version >= "3.6"' don't match your environment
pipenv-tests_1  | Ignoring scandir: markers 'python_version < "3.5"' don't match your environment
pipenv-tests_1  | Installing initially failed dependencies...
pipenv-tests_1  | Installing initially failed dependencies...
pipenv-tests_1  | 
pipenv-tests_1  | [pipenv.exceptions.InstallError]: Collecting pyenchant==2.0.0
pipenv-tests_1  | [pipenv.exceptions.InstallError]:   Using cached pyenchant-2.0.0.tar.gz (64 kB)
pipenv-tests_1  | [pipenv.exceptions.InstallError]:     ERROR: Command errored out with exit status 1:
pipenv-tests_1  | [pipenv.exceptions.InstallError]:      command: /root/.local/share/virtualenvs/pipenv-4aiTdSJZ-3.7/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xh98rl1t/pyenchant/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xh98rl1t/pyenchant/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-xh98rl1t/pyenchant/pip-egg-info
pipenv-tests_1  | [pipenv.exceptions.InstallError]:          cwd: /tmp/pip-install-xh98rl1t/pyenchant/
pipenv-tests_1  | [pipenv.exceptions.InstallError]:     Complete output (9 lines):
pipenv-tests_1  | [pipenv.exceptions.InstallError]:     Traceback (most recent call last):
pipenv-tests_1  | [pipenv.exceptions.InstallError]:       File "<string>", line 1, in <module>
pipenv-tests_1  | [pipenv.exceptions.InstallError]:       File "/tmp/pip-install-xh98rl1t/pyenchant/setup.py", line 212, in <module>
pipenv-tests_1  | [pipenv.exceptions.InstallError]:         import enchant
pipenv-tests_1  | [pipenv.exceptions.InstallError]:       File "/tmp/pip-install-xh98rl1t/pyenchant/enchant/__init__.py", line 92, in <module>
pipenv-tests_1  | [pipenv.exceptions.InstallError]:         from enchant import _enchant as _e
pipenv-tests_1  | [pipenv.exceptions.InstallError]:       File "/tmp/pip-install-xh98rl1t/pyenchant/enchant/_enchant.py", line 145, in <module>
pipenv-tests_1  | [pipenv.exceptions.InstallError]:         raise ImportError(msg)
pipenv-tests_1  | [pipenv.exceptions.InstallError]:     ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.
pipenv-tests_1  | [pipenv.exceptions.InstallError]:     ----------------------------------------
pipenv-tests_1  | [pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
pipenv-tests_1  | ERROR: Couldn't install package: pyenchant
pipenv-tests_1  |  Package installation failed...
pipenv_pipenv-tests_1 exited with code 1
```

### Steps to replicate

Clone the pipenv repository.
`cd` into the repository and run `make test`.

**Comment by Darrenmeehan** [comment]
I can confirm the above issue exists and is reproducible from master.

**Comment by techalchemy** [comment]
this is happening in a dockerfile? we just need to install libenchant in the dockerfile... which I assume is ours in some capacity... I knew I'd get in trouble for not using that thing someday

**Comment by Darrenmeehan** [comment]
@techalchemy how do you run the tests? There's a few different options but I'm assuming the method you use is the most supported! 

I also must look into the pipeline for running the tests.  

I'd like to help out this project is some capacity and having the safety gained from running the tests is something I'll be relying on.

Any advice on how you'd like this issue addressed?

**Comment by Darrenmeehan** [comment]
I've made an initial look into this. Happy to help implement the changes but I'd like to verify at least a rough path along what the pipenv maintainer would like. I'm not sure what workflows this needs to support.

Some observations:

1. `make test` runs `docker-compose up`.
2. This references `docker-compose.yml` which uses the Docker image `kennethreitz/pipenv-tests` which is outdated and not actually built by the `Dockerfile` in this repository. (In fact nothing seems to use this `Dockerfile`, nor does any documentation reference it)

I'm not sure what your thoughts are on continuing to support testing using Docker? I for one would prefer to use Docker as it ensures my environment isn't getting in the way of testing.

**Comment by MKaras93** [comment]
From my point of view docker is the best possible way of running tests, as it's even more isolated than virtual environments. It's important especially with this project - testing dev version pipenv in a virtual enviroment created with pipenv seems a little awkward, dependencies seem to be easy to mess up (not sure if they are, but I feel like they are). Docker provides a much more isolated testing environment with practically no configuration required.

**Comment by frostming** [comment]
You should install enchant library with your system's package manager before running the tests. It is not a bug of Pipenv
