### ISSUE TITLE
pipenv 2020.4.1b1: KeyError: 1 on install

### ISSUE THREAD

**Issue by Flimm** [pypa/pipenv#4226]
```
$ pipenv install django-robots
Installing django-robots…
Adding django-robots to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock (b798c1) out of date, updating to (ceb148)…
Locking [dev-packages] dependencies…
Building requirements...
Resolving dependencies...
✔ Success! 
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
Traceback (most recent call last):
  File "/home/flimm/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 807, in <module>
    main()
  File "/home/flimm/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 802, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/home/flimm/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 785, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
  File "/home/flimm/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 746, in resolve_packages
    results, resolver = resolve(
  File "/home/flimm/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 728, in resolve
    return resolve_deps(
  File "/home/flimm/.local/lib/python3.8/site-packages/pipenv/utils.py", line 1371, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/home/flimm/.local/lib/python3.8/site-packages/pipenv/utils.py", line 1088, in actually_resolve_deps
    resolver.resolve_constraints()
  File "/home/flimm/.local/lib/python3.8/site-packages/pipenv/utils.py", line 846, in resolve_constraints
    marker = marker_from_specifier(candidate.requires_python)
  File "/home/flimm/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 719, in marker_from_specifier
    for marker_segment in cleanup_pyspecs(spec):
  File "/home/flimm/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 259, in cleanup_pyspecs
    specs = normalize_specifier_set(specs)
  File "/home/flimm/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 240, in normalize_specifier_set
    return normalize_specifier_set(SpecifierSet(",".join(spec_list)))
  File "/home/flimm/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 232, in normalize_specifier_set
    return {_format_pyspec(spec) for spec in specs}
  File "/home/flimm/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 232, in <setcomp>
    return {_format_pyspec(spec) for spec in specs}
  File "/home/flimm/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 164, in _format_pyspec
    if not next_tuple[1] <= MAX_VERSIONS[next_tuple[0]]:
KeyError: 1

```

I'm on Ubuntu 20.04. If I downgrade to an older version of pipenv, I do not experience this issue.

**Comment by techalchemy** [comment]
thanks for the report! This one at least I can test myself easily!

are you using the system install of python? how did you install pipenv?

**Comment by Flimm** [comment]
I installed pipenv by running:

    pip install --upgrade --pre pipenv

I'm using system Python 3.8.

```
$ which pipenv
/home/flimm/.local/bin/pipenv
$ which python3
/usr/bin/python3
$ which python
/usr/bin/python
```

My `.bashrc` adds `~/.local/bin` to `PATH`.

**Comment by frostming** [comment]
I can reproduce here. The root cause is `django-robots` has a casual `python-requires` value `>1.1.1` and our specifier parser doesn't handle that.
