### ISSUE TITLE
Occur error when create virtual environment in CentOS7 & python 2.7.5 

### ISSUE THREAD

**Issue by mcauto** [pypa/pipenv#4249]
related issue: https://github.com/pypa/virtualenv/issues/1810

```
Using /bin/python2.7 (2.7.5) to create virtualenv…
⠹ Creating virtual environment...RuntimeError: failed to query /bin/python2.7 with code 1 err: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.7/site-packages/virtualenv/discovery/py_info.py", line 487, in <module>\n    print(PythonInfo()._to_json())\n  File "/usr/local/lib/python3.7/site-packages/virtualenv/discovery/py_info.py", line 82, in __init__\n    ("makefile_filename", sysconfig.get_makefile_filename()),\nAttributeError: \'module\' object has no attribute \'get_makefile_filename\'\n'
✘ Failed creating virtual environment
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.7/site-packages/pipenv/cli/command.py", line 615, in sync
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=state.pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 2597, in do_sync
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 574, in ensure_project
[pipenv.exceptions.VirtualenvCreationException]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 506, in ensure_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       python=python, site_packages=site_packages, pypi_mirror=pypi_mirror
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 935, in do_create_virtualenv
[pipenv.exceptions.VirtualenvCreationException]:       extra=[crayons.blue("{0}".format(c.err)),]
[pipenv.exceptions.VirtualenvCreationException]:
```

**Comment by mcauto** [comment]
I solve it!

I use python2.7.5, python3.6, python3.7

**venv_check.py**
```python
import virtualenv
print(virtualenv.__version__)
```

```bash
$ python3.7 venv_check.py
20.0.19

$ python3.6 venv_check.py
20.0.20
```

**solution**

```bash
pip3.7 install --upgrade pip
```
