### ISSUE TITLE
Pipenv 2020.4.1b1 fails to check outdated packages

### ISSUE THREAD

**Issue by gentooboontoo** [pypa/pipenv#4251]
### Issue description

Checking for outdated packages results in an error.

```sh
$ pipenv install flask flask-jwt
$ pipenv update --outdated # Fails
```

### Expected result

No errors.

### Steps to replicate

```sh
# Setup
$ mkdir proj
$ cd proj
$ pipenv install flask flask-jwt

# Check outdated
$ pipenv update --outdated
Building requirements...
Resolving dependencies...
✔ Success!
Skipped Update of Package Werkzeug: 1.0.1 installed,, 1.0.1 available.
Skipped Update of Package PyJWT: 1.4.2 installed,, 1.7.1 available.
Skipped Update of Package MarkupSafe: 1.1.1 installed,, 1.1.1 available.
Skipped Update of Package Jinja2: 2.11.2 installed,, 2.11.2 available.
Skipped Update of Package itsdangerous: 1.1.0 installed,, 1.1.0 available.
Skipped Update of Package Flask: 1.1.2 installed, (Unpinned in Pipfile), 1.1.2 available.
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/pipenv", line 11, in <module>
    load_entry_point('pipenv==2020.4.1b1', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pipenv/cli/command.py", line 509, in update
    do_outdated(clear=state.clear, pre=state.installstate.pre, pypi_mirror=state.pypi_mirror)
  File "/usr/lib/python3.8/site-packages/pipenv/core.py", line 1845, in do_outdated
    reverse_deps = reverse_deps.get(name_in_pipfile)
AttributeError: 'NoneType' object has no attribute 'get'
```

Could be related to #4229.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.4.1b1'`

Pipenv location: `'/usr/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/bin/python3.8'`

Python installations found:

  - `3.8.2`: `/usr/bin/python3`
  - `3.8.2`: `/usr/bin/python3.8`
  - `3.7.7`: `/usr/bin/python3.7m`
  - `3.7.7`: `/usr/bin/python3.7`
  - `3.6.10`: `/usr/bin/python3.6`
  - `3.6.10`: `/usr/bin/python3.6m`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.5.0-gentoo',
 'platform_system': 'Linux',
 'platform_version': '#12 SMP Thu Mar 26 09:36:38 CET 2020',
 'python_full_version': '3.8.2',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `WINDOWID`
  - `NVM_RC_VERSION`
  - `COLORTERM`
  - `XDG_CONFIG_DIRS`
  - `LESS`
  - `HISTCONTROL`
  - `JDK_HOME`
  - `CONFIG_PROTECT_MASK`
  - `TMUX`
  - `JAVA_HOME`
  - `SSH_AUTH_SOCK`
  - `HISTTIMEFORMAT`
  - `TMUX_PLUGIN_MANAGER_PATH`
  - `SSH_AGENT_PID`
  - `RBENV_SHELL`
  - `GPG_TTY`
  - `EDITOR`
  - `GTK_MODULES`
  - `XDG_SEAT`
  - `PWD`
  - `CONFIG_PROTECT`
  - `LOGNAME`
  - `XDG_SESSION_TYPE`
  - `MANPATH`
  - `XAUTHORITY`
  - `FZF_DEFAULT_COMMAND`
  - `WINDOWPATH`
  - `MOTD_SHOWN`
  - `HOME`
  - `LANG`
  - `LS_COLORS`
  - `OPENGL_PROFILE`
  - `INFOPATH`
  - `NVM_DIR`
  - `MOZ_GMP_PATH`
  - `JAVAC`
  - `XDG_SESSION_CLASS`
  - `TERM`
  - `LESSOPEN`
  - `USER`
  - `TMUX_PANE`
  - `MANPAGER`
  - `DISPLAY`
  - `SHLVL`
  - `NVM_CD_FLAGS`
  - `PAGER`
  - `XDG_VTNR`
  - `XDG_SESSION_ID`
  - `XSESSION`
  - `XDG_RUNTIME_DIR`
  - `GCC_SPECS`
  - `GSETTINGS_BACKEND`
  - `XDG_DATA_DIRS`
  - `HUSHLOGIN`
  - `PATH`
  - `ALACRITTY_LOG`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `MAIL`
  - `OLDPWD`
  - `GOPATH`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/10/bin:/usr/lib/llvm/9/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `vi`
  - `LANG`: `en_US.utf8`
  - `PWD`: `/tmp/pipenv-test`

---------------------------

Contents of `Pipfile` ('/tmp/pipenv-test/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
flask = "*"
flask-jwt = "*"

[requires]
python_version = "3.8"

```

Contents of `Pipfile.lock` ('/tmp/pipenv-test3/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "670a618533b8853ec908d8731b941be612d276fbea354abda941d52d4ee8ecc0"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "click": {
            "hashes": [
                "sha256:d2b5255c7c6349bc1bd1e59e08cd12acbbd63ce649f2588755783aa94dfb6b1a",
                "sha256:dacca89f4bfadd5de3d7489b7c8a566eee0d3676333fbb50030263894c38c0dc"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "version": "==7.1.2"
        },
        "flask": {
            "hashes": [
                "sha256:4efa1ae2d7c9865af48986de8aeb8504bf32c7f3d6fdc9353d34b21f4b127060",
                "sha256:8a4fdd8936eba2512e9c85df320a37e694c93945b33ef33c89946a340a238557"
            ],
            "index": "pypi",
            "version": "==1.1.2"
        },
        "flask-jwt": {
            "hashes": [
                "sha256:49c0672fbde0f1cd3374bd834918d28956e3c521c7e00089cdc5380d323bd0ad"
            ],
            "index": "pypi",
            "version": "==0.3.2"
        },
        "itsdangerous": {
            "hashes": [
                "sha256:321b033d07f2a4136d3ec762eac9f16a10ccd60f53c0c91af90217ace7ba1f19",
                "sha256:b12271b2047cb23eeb98c8b5622e2e5c5e9abd9784a153e9d8ef9cb4dd09d749"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "version": "==1.1.0"
        },
        "jinja2": {
            "hashes": [
                "sha256:89aab215427ef59c34ad58735269eb58b1a5808103067f7bb9d5836c651b3bb0",
                "sha256:f0a4641d3cf955324a89c04f3d94663aa4d638abe8f733ecd3582848e1c37035"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "version": "==2.11.2"
        },
        "markupsafe": {
            "hashes": [
                "sha256:00bc623926325b26bb9605ae9eae8a215691f33cae5df11ca5424f06f2d1f473",
                "sha256:09027a7803a62ca78792ad89403b1b7a73a01c8cb65909cd876f7fcebd79b161",
                "sha256:09c4b7f37d6c648cb13f9230d847adf22f8171b1ccc4d5682398e77f40309235",
                "sha256:1027c282dad077d0bae18be6794e6b6b8c91d58ed8a8d89a89d59693b9131db5",
                "sha256:13d3144e1e340870b25e7b10b98d779608c02016d5184cfb9927a9f10c689f42",
                "sha256:24982cc2533820871eba85ba648cd53d8623687ff11cbb805be4ff7b4c971aff",
                "sha256:29872e92839765e546828bb7754a68c418d927cd064fd4708fab9fe9c8bb116b",
                "sha256:43a55c2930bbc139570ac2452adf3d70cdbb3cfe5912c71cdce1c2c6bbd9c5d1",
                "sha256:46c99d2de99945ec5cb54f23c8cd5689f6d7177305ebff350a58ce5f8de1669e",
                "sha256:500d4957e52ddc3351cabf489e79c91c17f6e0899158447047588650b5e69183",
                "sha256:535f6fc4d397c1563d08b88e485c3496cf5784e927af890fb3c3aac7f933ec66",
                "sha256:596510de112c685489095da617b5bcbbac7dd6384aeebeda4df6025d0256a81b",
                "sha256:62fe6c95e3ec8a7fad637b7f3d372c15ec1caa01ab47926cfdf7a75b40e0eac1",
                "sha256:6788b695d50a51edb699cb55e35487e430fa21f1ed838122d722e0ff0ac5ba15",
                "sha256:6dd73240d2af64df90aa7c4e7481e23825ea70af4b4922f8ede5b9e35f78a3b1",
                "sha256:717ba8fe3ae9cc0006d7c451f0bb265ee07739daf76355d06366154ee68d221e",
                "sha256:79855e1c5b8da654cf486b830bd42c06e8780cea587384cf6545b7d9ac013a0b",
                "sha256:7c1699dfe0cf8ff607dbdcc1e9b9af1755371f92a68f706051cc8c37d447c905",
                "sha256:88e5fcfb52ee7b911e8bb6d6aa2fd21fbecc674eadd44118a9cc3863f938e735",
                "sha256:8defac2f2ccd6805ebf65f5eeb132adcf2ab57aa11fdf4c0dd5169a004710e7d",
                "sha256:98c7086708b163d425c67c7a91bad6e466bb99d797aa64f965e9d25c12111a5e",
                "sha256:9add70b36c5666a2ed02b43b335fe19002ee5235efd4b8a89bfcf9005bebac0d",
                "sha256:9bf40443012702a1d2070043cb6291650a0841ece432556f784f004937f0f32c",
                "sha256:ade5e387d2ad0d7ebf59146cc00c8044acbd863725f887353a10df825fc8ae21",
                "sha256:b00c1de48212e4cc9603895652c5c410df699856a2853135b3967591e4beebc2",
                "sha256:b1282f8c00509d99fef04d8ba936b156d419be841854fe901d8ae224c59f0be5",
                "sha256:b2051432115498d3562c084a49bba65d97cf251f5a331c64a12ee7e04dacc51b",
                "sha256:ba59edeaa2fc6114428f1637ffff42da1e311e29382d81b339c1817d37ec93c6",
                "sha256:c8716a48d94b06bb3b2524c2b77e055fb313aeb4ea620c8dd03a105574ba704f",
                "sha256:cd5df75523866410809ca100dc9681e301e3c27567cf498077e8551b6d20e42f",
                "sha256:cdb132fc825c38e1aeec2c8aa9338310d29d337bebbd7baa06889d09a60a1fa2",
                "sha256:e249096428b3ae81b08327a63a485ad0878de3fb939049038579ac0ef61e17e7",
                "sha256:e8313f01ba26fbbe36c7be1966a7b7424942f670f38e666995b88d012765b9be"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "version": "==1.1.1"
        },
        "pyjwt": {
            "hashes": [
                "sha256:87a831b7a3bfa8351511961469ed0462a769724d4da48a501cb8c96d1e17f570",
                "sha256:99fe612dbe5f41e07124d9002c118c14f3ee703574ffa9779fee78135b8b94b6"
            ],
            "version": "==1.4.2"
        },
        "werkzeug": {
            "hashes": [
                "sha256:2de2a5db0baeae7b2d2664949077c2ac63fbd16d98da0ff71837f7d1dea3fd43",
                "sha256:6c80b1e5ad3665290ea39320b91e1be1e0d5f60652b964a3070216de83d2e47c"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "version": "==1.0.1"
        }
    },
    "develop": {}
}

```
</details>

**Comment by frostming** [comment]
Thanks for the information, I managed to reproduce it, but I am going to close it in favor of #4229
