### ISSUE TITLE
Unsupported Python Version while installing Django

### ISSUE THREAD

**Issue by Rahul-Gothwal** [pypa/pipenv#4297]
Hello,
I'm trying to use [Django](https://github.com/django/django) but during the installation i have this error

```bash
pipenv.patched.notpip._internal.exceptions.UnsupportedPythonVersion: Django requires Python '>=3.5' but the running Python is 2.7.18
```
though i've python 3.8 installed
```bash
samsepi0l@kali:~$ python --version
Python 3.8.0
````
This is the command i wrote
```bash
samsepi0l@kali:~/Desktop/django$ pipenv install django==2.1
```
and got this output 
```bash
Installing django==2.1...
Adding django to Pipfile's [packages]...
OK Installation Succeeded 
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
x Locking Failed! 
Traceback (most recent call last):
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 274, in _resolve_one
    self.requires_python = check_dist_requires_python(dist, absorb=False)
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/utils/packaging.py", line 62, in check_dist_requires_python
    '.'.join(map(str, sys.version_info[:3])),)
pipenv.patched.notpip._internal.exceptions.UnsupportedPythonVersion: Django requires Python '>=3.5' but the running Python is 2.7.18
File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 274, in _resolve_one
    self.requires_python = check_dist_requires_python(dist, absorb=False)
  File "/home/samsepi0l/anaconda2/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/utils/packaging.py", line 62, in check_dist_requires_python
    '.'.join(map(str, sys.version_info[:3])),)
pipenv.patched.notpip._internal.exceptions.UnsupportedPythonVersion: Django requires Python '>=3.5' but the running Python is 2.7.18
```

**Comment by Rahul-Gothwal** [comment]
Got the solution..
i was using anaconda2 which was running on python 2.7.
so i just removed it and installed anaconda3 for python 3 and the issue was resolved, though i've got a [new one](https://github.com/django/djangoproject.com/issues/1000) for now.
