### ISSUE TITLE
pipenv lock --clear fails with no useful error message (TypeError: unhashable type: 'dict')

### ISSUE THREAD

**Issue by Froskekongen** [pypa/pipenv#4320]
### Issue description

Running `pipenv lock --clear` results in a traceback and fails without useful error messages.

### Expected result

Either a successful lock or a failed log.

### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues:
```
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
⠸ Locking...Traceback (most recent call last):
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/resolver.py", line 807, in <module>
✘ Locking Failed! 
    main()
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/resolver.py", line 803, in main
    parsed.requirements_dir, parsed.packages, parse_only=parsed.parse_only)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/resolver.py", line 785, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/resolver.py", line 753, in resolve_packages
    requirements_dir=requirements_dir,
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/resolver.py", line 736, in resolve
    req_dir=requirements_dir
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 1386, in resolve_deps
    req_dir=req_dir,
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 1091, in actually_resolve_deps
    deps, index_lookup, markers_lookup, project, sources, req_dir, clear, pre
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 649, in create
    pre=pre, clear=clear
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 463, in get_metadata
    req, resolver=transient_resolver
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 540, in get_deps_from_req
    req_list, lockfile = get_vcs_deps(reqs=[req])
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 1874, in get_vcs_deps
    with temp_path(), locked_repository(requirement) as repo:
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 2030, in locked_repository
    with requirement.req.locked_vcs_repo(src_dir=src_dir) as repo:
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2212, in locked_vcs_repo
    self._parsed_line.vcsrepo = vcsrepo
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 916, in vcsrepo
    kwargs=wheel_kwargs,
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1937, in create
    created.get_initial_info()
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1766, in get_initial_info
    self.update_from_dict(self.parse_setup_py())
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1523, in parse_setup_py
    parsed = ast_parse_setup_py(self.setup_py.as_posix())
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1208, in ast_parse_setup_py
    ast_analyzer = ast_parse_file(path)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1202, in ast_parse_file
    ast_analyzer.visit(tree)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 709, in generic_visit
    super(Analyzer, self).generic_visit(node)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 709, in generic_visit
    super(Analyzer, self).generic_visit(node)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/ast.py", line 281, in generic_visit
    self.visit(value)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 702, in generic_visit
    self.function_map.update(ast_unparse(node, initial_mapping=True))
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1138, in ast_unparse
    for keyword in unparse(val):
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1164, in ast_unparse
    unparsed = type(item)([unparse(el) for el in item])
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1164, in <listcomp>
    unparsed = type(item)([unparse(el) for el in item])
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1141, in ast_unparse
    unparsed = {unparse(item.arg): unparse(item.value)}
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1001, in ast_unparse
    unparsed = dict(zip(unparse(item.keys), unparse(item.values)))
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/resolver.py", line 807, in <module>
    main()
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/resolver.py", line 803, in main
    parsed.requirements_dir, parsed.packages, parse_only=parsed.parse_only)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/resolver.py", line 785, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/resolver.py", line 753, in resolve_packages
    requirements_dir=requirements_dir,
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/resolver.py", line 736, in resolve
    req_dir=requirements_dir
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 1386, in resolve_deps
    req_dir=req_dir,
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 1091, in actually_resolve_deps
    deps, index_lookup, markers_lookup, project, sources, req_dir, clear, pre
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 649, in create
    pre=pre, clear=clear
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 463, in get_metadata
    req, resolver=transient_resolver
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 540, in get_deps_from_req
    req_list, lockfile = get_vcs_deps(reqs=[req])
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 1874, in get_vcs_deps
    with temp_path(), locked_repository(requirement) as repo:
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 2030, in locked_repository
    with requirement.req.locked_vcs_repo(src_dir=src_dir) as repo:
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2212, in locked_vcs_repo
    self._parsed_line.vcsrepo = vcsrepo
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 916, in vcsrepo
    kwargs=wheel_kwargs,
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1937, in create
    created.get_initial_info()
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1766, in get_initial_info
    self.update_from_dict(self.parse_setup_py())
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1523, in parse_setup_py
    parsed = ast_parse_setup_py(self.setup_py.as_posix())
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1208, in ast_parse_setup_py
    ast_analyzer = ast_parse_file(path)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1202, in ast_parse_file
    ast_analyzer.visit(tree)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 709, in generic_visit
    super(Analyzer, self).generic_visit(node)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/ast.py", line 279, in generic_visit
    self.visit(item)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 709, in generic_visit
    super(Analyzer, self).generic_visit(node)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/ast.py", line 281, in generic_visit
    self.visit(value)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 702, in generic_visit
    self.function_map.update(ast_unparse(node, initial_mapping=True))
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1138, in ast_unparse
    for keyword in unparse(val):
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1164, in ast_unparse
    unparsed = type(item)([unparse(el) for el in item])
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1164, in <listcomp>
    unparsed = type(item)([unparse(el) for el in item])
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1141, in ast_unparse
    unparsed = {unparse(item.arg): unparse(item.value)}
  File "/home/erlenda/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1001, in ast_unparse
    unparsed = dict(zip(unparse(item.keys), unparse(item.values)))
TypeError: unhashable type: 'dict'
```

### Steps to replicate

pipenv lock --clear
[Pipfile.txt](https://github.com/pypa/pipenv/files/4729426/Pipfile.txt)

-------------------------------------------------------------------------------

[support.txt](https://github.com/pypa/pipenv/files/4729446/support.txt)

**Comment by Froskekongen** [comment]
Note: I tried the same command in a different folder, and then I did not get this behaviour.

**Comment by ePak** [comment]
We are running into this issue as well.
