### ISSUE TITLE
Pipenv reverting to Python2.7 when locking

### ISSUE THREAD

**Issue by ohare93** [pypa/pipenv#4325]
**Environment**

* pip version: 20.1.1
* Python version: 3.7.7
* OS: Kubuntu 18.04

Inside a pipenv. Running in either Pycharm or in terminal results in the same issue.

**Description**
Trying to add `ruamel.yaml` to my pipfile, results in failure of the lock step as pip starts using Python 2.7 at some point during the process. I have tried adding the requirement to the pipfile and running `pipenv install` as well as just `pipenv install ruamel.yaml` or `pipenv install ruamel-yaml`.

I can install ruamel.yaml fine with `pip install ruamel.yaml`, but I cannot add it to my piplock.

**Expected behavior**
I expect to generate a pip lock file, but cannot with this specific dependency for some reason.

**How to Reproduce**
1. Make a new project, generate a pipfile. 
1. Add 'pytest' to the pipfile, or install it manually like below.
1. Run `pip install ruamel.yaml` which will try to generate the piplock.
1. That fails, saying it is trying to use python 2.7

**Output**
```
(brain-brew) jmo@Depth:~/Development/brain-brew$ python -V
Python 3.7.7
(brain-brew) jmo@Depth:~/Development/brain-brew$ pipenv run python -V
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Python 3.7.7

(brain-brew) jmo@Depth:~/Development/brain-brew$ pipenv install ruamel.yaml
Installing ruamel.yaml...
✔ Installation Succeeded 
Pipfile.lock (c44c5c) out of date, updating to (b36b8e)...
Locking [dev-packages] dependencies...
✘ Locking Failed! 
Traceback (most recent call last):
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 274, in _resolve_one
    self.requires_python = check_dist_requires_python(dist, absorb=False)
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/utils/packaging.py", line 62, in check_dist_requires_python
    '.'.join(map(str, sys.version_info[:3])),)
pipenv.patched.notpip._internal.exceptions.UnsupportedPythonVersion: pytest requires Python '>=3.5' but the running Python is 2.7.17
File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/piptools/resolver.py", line 301, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 274, in _resolve_one
    self.requires_python = check_dist_requires_python(dist, absorb=False)
  File "/home/jmo/.local/lib/python2.7/site-packages/pipenv/patched/notpip/_internal/utils/packaging.py", line 62, in check_dist_requires_python
    '.'.join(map(str, sys.version_info[:3])),)
pipenv.patched.notpip._internal.exceptions.UnsupportedPythonVersion: pytest requires Python '>=3.5' but the running Python is 2.7.17

```

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/jmo/.local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.7.7`: `/home/jmo/.pyenv/versions/3.7.7/bin/python3.7m`
  - `3.8.3`: `/usr/bin/python3.8`
  - `3.7.7`: `/usr/bin/python3.7`
  - `3.6.9`: `/usr/bin/python3.6`
  - `3.7.7`: `/home/jmo/.pyenv/versions/3.7.7/bin/python`
  - `3.6.9`: `/usr/bin/python3.6m`
  - `3.7.7`: `/usr/bin/python3.7m`
  - `2.7.17`: `/usr/bin/python2`
  - `3.7.7`: `/home/jmo/.local/share/virtualenvs/brain-brew-hOrYNHNI/bin/python`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.3.0-53-generic',
 'platform_system': 'Linux',
 'platform_version': '#47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020',
 'python_full_version': '2.7.17',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

System environment variables:

  - `SNAP_LIBRARY_PATH`
  - `KDE_SESSION_VERSION`
  - `SNAP_CONTEXT`
  - `LESSOPEN`
  - `XCURSOR_SIZE`
  - `TERMINAL_EMULATOR`
  - `XDG_SESSION_TYPE`
  - `LOGNAME`
  - `USER`
  - `PATH`
  - `XDG_VTNR`
  - `HOME`
  - `PS1`
  - `PAM_KWALLET_LOGIN`
  - `PYENV_VIRTUALENV_INIT`
  - `SNAP_ARCH`
  - `KDE_FULL_SESSION`
  - `LANG`
  - `SNAP_REVISION`
  - `VIRTUAL_ENV`
  - `SHELL`
  - `XDG_SESSION_PATH`
  - `XAUTHORITY`
  - `PYENV_SHELL`
  - `GPG_AGENT_INFO`
  - `XDG_DATA_DIRS`
  - `GS_LIB`
  - `MANDATORY_PATH`
  - `SNAP_DATA`
  - `DISPLAY`
  - `QT_ACCESSIBILITY`
  - `BAMF_DESKTOP_FILE_HINT`
  - `SNAP_USER_DATA`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `SSH_AGENT_PID`
  - `XDG_SESSION_CLASS`
  - `SNAP_VERSION`
  - `XDG_SESSION_DESKTOP`
  - `XDG_CONFIG_DIRS`
  - `KDE_SESSION_UID`
  - `XDG_RUNTIME_DIR`
  - `SNAP_USER_COMMON`
  - `SNAP_COOKIE`
  - `SSH_AUTH_SOCK`
  - `XCURSOR_THEME`
  - `TERM`
  - `SNAP_INSTANCE_KEY`
  - `PAM_KWALLET5_LOGIN`
  - `PIP_PYTHON_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `SNAP_NAME`
  - `XDG_SEAT_PATH`
  - `SNAP_REEXEC`
  - `SNAP_INSTANCE_NAME`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_SESSION_ID`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `_`
  - `DESKTOP_SESSION`
  - `SNAP_COMMON`
  - `LESSCLOSE`
  - `DEFAULTS_PATH`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `OLDPWD`
  - `SESSION_MANAGER`
  - `LANGUAGE`
  - `SHLVL`
  - `PWD`
  - `DESKTOP_STARTUP_ID`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `PIP_SHIMS_BASE_MODULE`
  - `SNAP`
  - `LS_COLORS`
  - `XDG_SEAT`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/jmo/.local/share/virtualenvs/brain-brew-hOrYNHNI/bin:/home/jmo/.pyenv/plugins/pyenv-virtualenv/shims:/home/jmo/.pyenv/shims:~/.pyenv/bin:/home/jmo/.cargo/bin:/home/jmo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/home/jmo/Development/brain-brew`
  - `VIRTUAL_ENV`: `/home/jmo/.local/share/virtualenvs/brain-brew-hOrYNHNI`

---------------------------

Contents of `Pipfile` ('/home/jmo/Development/brain-brew/Pipfile'):

```toml
[[source]]
name = "Brain Brew"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
pytest = "==5.4.1"

[packages]
args = "==0.1.0"
clint = "==0.5.1"
coverage = "==4.5.4"
PyYAML = "==5.1.2"
ruamel-yaml = "*"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/home/jmo/Development/brain-brew/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "a1fdf18fb74ab9ec7c5d2e956b782058ac37275e59250e5067bf531a4bc44c5c"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "Brain Brew",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "args": {
            "hashes": [
                "sha256:a785b8d837625e9b61c39108532d95b85274acd679693b71ebb5156848fcf814"
            ],
            "index": "Brain Brew",
            "version": "==0.1.0"
        },
        "clint": {
            "hashes": [
                "sha256:05224c32b1075563d0b16d0015faaf9da43aa214e4a2140e51f08789e7a4c5aa"
            ],
            "index": "Brain Brew",
            "version": "==0.5.1"
        },
        "coverage": {
            "hashes": [
                "sha256:08907593569fe59baca0bf152c43f3863201efb6113ecb38ce7e97ce339805a6",
                "sha256:0be0f1ed45fc0c185cfd4ecc19a1d6532d72f86a2bac9de7e24541febad72650",
                "sha256:141f08ed3c4b1847015e2cd62ec06d35e67a3ac185c26f7635f4406b90afa9c5",
                "sha256:19e4df788a0581238e9390c85a7a09af39c7b539b29f25c89209e6c3e371270d",
                "sha256:23cc09ed395b03424d1ae30dcc292615c1372bfba7141eb85e11e50efaa6b351",
                "sha256:245388cda02af78276b479f299bbf3783ef0a6a6273037d7c60dc73b8d8d7755",
                "sha256:331cb5115673a20fb131dadd22f5bcaf7677ef758741312bee4937d71a14b2ef",
                "sha256:386e2e4090f0bc5df274e720105c342263423e77ee8826002dcffe0c9533dbca",
                "sha256:3a794ce50daee01c74a494919d5ebdc23d58873747fa0e288318728533a3e1ca",
                "sha256:60851187677b24c6085248f0a0b9b98d49cba7ecc7ec60ba6b9d2e5574ac1ee9",
                "sha256:63a9a5fc43b58735f65ed63d2cf43508f462dc49857da70b8980ad78d41d52fc",
                "sha256:6b62544bb68106e3f00b21c8930e83e584fdca005d4fffd29bb39fb3ffa03cb5",
                "sha256:6ba744056423ef8d450cf627289166da65903885272055fb4b5e113137cfa14f",
                "sha256:7494b0b0274c5072bddbfd5b4a6c6f18fbbe1ab1d22a41e99cd2d00c8f96ecfe",
                "sha256:826f32b9547c8091679ff292a82aca9c7b9650f9fda3e2ca6bf2ac905b7ce888",
                "sha256:93715dffbcd0678057f947f496484e906bf9509f5c1c38fc9ba3922893cda5f5",
                "sha256:9a334d6c83dfeadae576b4d633a71620d40d1c379129d587faa42ee3e2a85cce",
                "sha256:af7ed8a8aa6957aac47b4268631fa1df984643f07ef00acd374e456364b373f5",
                "sha256:bf0a7aed7f5521c7ca67febd57db473af4762b9622254291fbcbb8cd0ba5e33e",
                "sha256:bf1ef9eb901113a9805287e090452c05547578eaab1b62e4ad456fcc049a9b7e",
                "sha256:c0afd27bc0e307a1ffc04ca5ec010a290e49e3afbe841c5cafc5c5a80ecd81c9",
                "sha256:dd579709a87092c6dbee09d1b7cfa81831040705ffa12a1b248935274aee0437",
                "sha256:df6712284b2e44a065097846488f66840445eb987eb81b3cc6e4149e7b6982e1",
                "sha256:e07d9f1a23e9e93ab5c62902833bf3e4b1f65502927379148b6622686223125c",
                "sha256:e2ede7c1d45e65e209d6093b762e98e8318ddeff95317d07a27a2140b80cfd24",
                "sha256:e4ef9c164eb55123c62411f5936b5c2e521b12356037b6e1c2617cef45523d47",
                "sha256:eca2b7343524e7ba246cab8ff00cab47a2d6d54ada3b02772e908a45675722e2",
                "sha256:eee64c616adeff7db37cc37da4180a3a5b6177f5c46b187894e633f088fb5b28",
                "sha256:ef824cad1f980d27f26166f86856efe11eff9912c4fed97d3804820d43fa550c",
                "sha256:efc89291bd5a08855829a3c522df16d856455297cf35ae827a37edac45f466a7",
                "sha256:fa964bae817babece5aa2e8c1af841bebb6d0b9add8e637548809d040443fee0",
                "sha256:ff37757e068ae606659c28c3bd0d923f9d29a85de79bf25b2b34b148473b5025"
            ],
            "index": "Brain Brew",
            "version": "==4.5.4"
        },
        "pyyaml": {
            "hashes": [
                "sha256:0113bc0ec2ad727182326b61326afa3d1d8280ae1122493553fd6f4397f33df9",
                "sha256:01adf0b6c6f61bd11af6e10ca52b7d4057dd0be0343eb9283c878cf3af56aee4",
                "sha256:5124373960b0b3f4aa7df1707e63e9f109b5263eca5976c66e08b1c552d4eaf8",
                "sha256:5ca4f10adbddae56d824b2c09668e91219bb178a1eee1faa56af6f99f11bf696",
                "sha256:7907be34ffa3c5a32b60b95f4d95ea25361c951383a894fec31be7252b2b6f34",
                "sha256:7ec9b2a4ed5cad025c2278a1e6a19c011c80a3caaac804fd2d329e9cc2c287c9",
                "sha256:87ae4c829bb25b9fe99cf71fbb2140c448f534e24c998cc60f39ae4f94396a73",
                "sha256:9de9919becc9cc2ff03637872a440195ac4241c80536632fffeb6a1e25a74299",
                "sha256:a5a85b10e450c66b49f98846937e8cfca1db3127a9d5d1e31ca45c3d0bef4c5b",
                "sha256:b0997827b4f6a7c286c01c5f60384d218dca4ed7d9efa945c3e1aa623d5709ae",
                "sha256:b631ef96d3222e62861443cc89d6563ba3eeb816eeb96b2629345ab795e53681",
                "sha256:bf47c0607522fdbca6c9e817a6e81b08491de50f3766a7a0e6a5be7905961b41",
                "sha256:f81025eddd0327c7d4cfe9b62cf33190e1e736cc6e97502b3ec425f574b3e7a8"
            ],
            "index": "Brain Brew",
            "version": "==5.1.2"
        },
        "ruamel-yaml": {
            "hashes": [
                "sha256:0962fd7999e064c4865f96fb1e23079075f4a2a14849bcdc5cdba53a24f9759b"
            ],
            "index": "Brain Brew",
            "version": "==0.16.10"
        },
        "ruamel.yaml.clib": {
            "hashes": [
                "sha256:1e77424825caba5553bbade750cec2277ef130647d685c2b38f68bc03453bac6",
                "sha256:392b7c371312abf27fb549ec2d5e0092f7ef6e6c9f767bfb13e83cb903aca0fd",
                "sha256:4d55386129291b96483edcb93b381470f7cd69f97585829b048a3d758d31210a",
                "sha256:550168c02d8de52ee58c3d8a8193d5a8a9491a5e7b2462d27ac5bf63717574c9",
                "sha256:57933a6986a3036257ad7bf283529e7c19c2810ff24c86f4a0cfeb49d2099919",
                "sha256:615b0396a7fad02d1f9a0dcf9f01202bf9caefee6265198f252c865f4227fcc6",
                "sha256:77556a7aa190be9a2bd83b7ee075d3df5f3c5016d395613671487e79b082d784",
                "sha256:7aee724e1ff424757b5bd8f6c5bbdb033a570b2b4683b17ace4dbe61a99a657b",
                "sha256:8073c8b92b06b572e4057b583c3d01674ceaf32167801fe545a087d7a1e8bf52",
                "sha256:9c6d040d0396c28d3eaaa6cb20152cb3b2f15adf35a0304f4f40a3cf9f1d2448",
                "sha256:a0ff786d2a7dbe55f9544b3f6ebbcc495d7e730df92a08434604f6f470b899c5",
                "sha256:b1b7fcee6aedcdc7e62c3a73f238b3d080c7ba6650cd808bce8d7761ec484070",
                "sha256:b66832ea8077d9b3f6e311c4a53d06273db5dc2db6e8a908550f3c14d67e718c",
                "sha256:be018933c2f4ee7de55e7bd7d0d801b3dfb09d21dad0cce8a97995fd3e44be30",
                "sha256:d0d3ac228c9bbab08134b4004d748cf9f8743504875b3603b3afbb97e3472947",
                "sha256:d10e9dd744cf85c219bf747c75194b624cc7a94f0c80ead624b06bfa9f61d3bc",
                "sha256:ea4362548ee0cbc266949d8a441238d9ad3600ca9910c3fe4e82ee3a50706973",
                "sha256:ed5b3698a2bb241b7f5cbbe277eaa7fe48b07a58784fba4f75224fd066d253ad",
                "sha256:f9dcc1ae73f36e8059589b601e8e4776b9976effd76c21ad6a855a74318efd6e"
            ],
            "markers": "platform_python_implementation == 'CPython' and python_version < '3.9'",
            "version": "==0.2.0"
        }
    },
    "develop": {
        "attrs": {
            "hashes": [
                "sha256:08a96c641c3a74e44eb59afb61a24f2cb9f4d7188748e76ba4bb5edfa3cb7d1c",
                "sha256:f7b7ce16570fe9965acd6d30101a28f62fb4a7f9e926b3bbc9b61f8b04247e72"
            ],
            "version": "==19.3.0"
        },
        "importlib-metadata": {
            "hashes": [
                "sha256:0505dd08068cfec00f53a74a0ad927676d7757da81b7436a6eefe4c7cf75c545",
                "sha256:15ec6c0fd909e893e3a08b3a7c76ecb149122fb14b7efe1199ddd4c7c57ea958"
            ],
            "markers": "python_version < '3.8'",
            "version": "==1.6.1"
        },
        "more-itertools": {
            "hashes": [
                "sha256:558bb897a2232f5e4f8e2399089e35aecb746e1f9191b6584a151647e89267be",
                "sha256:7818f596b1e87be009031c7653d01acc46ed422e6656b394b0f765ce66ed4982"
            ],
            "version": "==8.3.0"
        },
        "packaging": {
            "hashes": [
                "sha256:4357f74f47b9c12db93624a82154e9b120fa8293699949152b22065d556079f8",
                "sha256:998416ba6962ae7fbd6596850b80e17859a5753ba17c32284f67bfff33784181"
            ],
            "version": "==20.4"
        },
        "pluggy": {
            "hashes": [
                "sha256:15b2acde666561e1298d71b523007ed7364de07029219b604cf808bfa1c765b0",
                "sha256:966c145cd83c96502c3c3868f50408687b38434af77734af1e9ca461a4081d2d"
            ],
            "version": "==0.13.1"
        },
        "py": {
            "hashes": [
                "sha256:5e27081401262157467ad6e7f851b7aa402c5852dbcb3dae06768434de5752aa",
                "sha256:c20fdd83a5dbc0af9efd622bee9a5564e278f6380fffcacc43ba6f43db2813b0"
            ],
            "version": "==1.8.1"
        },
        "pyparsing": {
            "hashes": [
                "sha256:c203ec8783bf771a155b207279b9bccb8dea02d8f0c9e5f8ead507bc3246ecc1",
                "sha256:ef9d7589ef3c200abe66653d3f1ab1033c3c419ae9b9bdb1240a85b024efc88b"
            ],
            "version": "==2.4.7"
        },
        "pytest": {
            "hashes": [
                "sha256:0e5b30f5cb04e887b91b1ee519fa3d89049595f428c1db76e73bd7f17b09b172",
                "sha256:84dde37075b8805f3d1f392cc47e38a0e59518fb46a431cfdaf7cf1ce805f970"
            ],
            "index": "Brain Brew",
            "version": "==5.4.1"
        },
        "six": {
            "hashes": [
                "sha256:30639c035cdb23534cd4aa2dd52c3bf48f06e5f4a941509c8bafd8ce11080259",
                "sha256:8b74bedcbbbaca38ff6d7491d76f2b06b3592611af620f8426e82dddb04a5ced"
            ],
            "version": "==1.15.0"
        },
        "wcwidth": {
            "hashes": [
                "sha256:980fbf4f3c196c0f329cdcd1e84c554d6a211f18e252e525a0cf4223154a41d6",
                "sha256:edbc2b718b4db6cdf393eefe3a420183947d6aa312505ce6754516f458ff8830"
            ],
            "version": "==0.2.3"
        },
        "zipp": {
            "hashes": [
                "sha256:aa36550ff0c0b7ef7fa639055d797116ee891440eac1a56f378e2d3179e0320b",
                "sha256:c599e4d75c98f6798c509911d08a22e6c021d074469042177c8c86fb92eefd96"
            ],
            "version": "==3.1.0"
        }
    }
}

```
</details>

Looking at those details of the support call, I can see Pipenv location: '/home/jmo/.local/lib/**python2.7**/site-packages/pipenv', but I have no idea why that would be or how to fix it.

**Comment by frostming** [comment]
Does this issue still exist on the master branch? @ohare93
