### ISSUE TITLE
File Exist error on locking

### ISSUE THREAD

**Issue by con-f-use** [pypa/pipenv#4326]
### Issue description

After updating pipenv from 2018.11.26 to 2020.6.2 pipenv always crashes for one of my projects with this traceback:

```
┌─07-13:29[confus@confusion6:~/devel/doubleplusungood] e82d1:master(+3/-2)+* 1 ± 
└▪ pipenv lock --verbose --dev
Locking [dev-packages] dependencies…
Building requirements...
Traceback (most recent call last):
  File "/home/confus/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/cli/command.py", line 374, in lock
    write=not state.quiet,
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/core.py", line 1114, in do_lock
    keep_outdated=keep_outdated
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/utils.py", line 1318, in venv_resolve_deps
    deps, project, r=False, include_index=True
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/utils.py", line 1434, in convert_deps_to_pip
    new_dep = Requirement.from_pipfile(dep_name, dep)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2743, in from_pipfile
    r = FileRequirement.from_pipfile(name, pipfile)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1843, in from_pipfile
    arg_dict["setup_info"] = arg_dict["parsed_line"].setup_info
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 813, in setup_info
    self.setup_info = self.get_setup_info()
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 802, in get_setup_info
    setup_info = SetupInfo.from_ireq(self.ireq, subdir=self.subdirectory)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1870, in from_ireq
    shutil.copytree(path, target, symlinks=True)
  File "/usr/lib/python3.6/shutil.py", line 321, in copytree
    os.makedirs(dst)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/tmp/reqlib-srcqkiyds5t/..'
┌─07-13:29[confus@confusion6:~/devel/doubleplusungood] e82d1:master(+3/-2)+* 1 ± 
└▪ pipenv lock --clear
Locking [dev-packages] dependencies…
Building requirements...
Traceback (most recent call last):
  File "/home/confus/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/cli/command.py", line 374, in lock
    write=not state.quiet,
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/core.py", line 1114, in do_lock
    keep_outdated=keep_outdated
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/utils.py", line 1318, in venv_resolve_deps
    deps, project, r=False, include_index=True
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/utils.py", line 1434, in convert_deps_to_pip
    new_dep = Requirement.from_pipfile(dep_name, dep)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2743, in from_pipfile
    r = FileRequirement.from_pipfile(name, pipfile)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1843, in from_pipfile
    arg_dict["setup_info"] = arg_dict["parsed_line"].setup_info
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 813, in setup_info
    self.setup_info = self.get_setup_info()
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 802, in get_setup_info
    setup_info = SetupInfo.from_ireq(self.ireq, subdir=self.subdirectory)
  File "/home/confus/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1870, in from_ireq
    shutil.copytree(path, target, symlinks=True)
  File "/usr/lib/python3.6/shutil.py", line 321, in copytree
    os.makedirs(dst)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode
FileExistsError: [Errno 17] File exists: '/tmp/reqlib-srcxj1os9tf/..'
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.6.2'`

Pipenv location: `'/home/jan/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:
# ... hangs indefinetly trying to find python installations....

**Comment by Darrenmeehan** [comment]
I've facing a similar issue with a single project.

On this system I'm using `python3.7` as system default, with `python3.6` installed using `pyenv`.

I'll do some digging and see if there's anything I can find to help narrow down what is happening.

**Comment by munsu** [comment]
Chipping in I'm getting the same thing. Tried rolling back to old pipenv versions and the latest (stable) one that works is `2018.11.26`.

Re: the issue, I did indeed narrow it down to the local package as the `2020.6.2` version works properly if I remove the following line from my Pipfile:

```
packagename = {editable = true,path = "./../.."}
```

**Comment by con-f-use** [comment]
I am installing local packages in my dev-packages, too. So yes.

**Comment by Darrenmeehan** [comment]
It seems to be related to the path being a parent directory of the directory with the `Pipfile` & `Pipfile.lock`. I haven't had more time to investigate this issue since my initial comment.

@con-f-use are you local packages also in a parent directory?

**Comment by con-f-use** [comment]
Basically this:
```
[dev-packages]
pipenv-to-requirements = ">=0.8"
# ...
framework-core = {path = ".",allow_prereleases = true,editable = true}
framework-api = {path = "../framework-api",allow_prereleases = true,editable = true}
framework = {path = "..",allow_prereleases = true,editable = true}

[packages]
azure = "==4.0.0"
# ...
```

**Comment by hleb-albau** [comment]
Same issue

**Comment by con-f-use** [comment]
It's been a couple of month, can we get this fixed, please?

**Comment by frostming** [comment]
@con-f-use Did you try 2020.8.13 release? No longer copy tree for now.

**Comment by con-f-use** [comment]
I was on 2020.08.13, yes. The copytree is in one of the vendor libraries included with pipenv[

**Comment by matteius** [comment]
I think this is closeable at this point, pipenv==2022.4.21 is released.  Let me know if it needs to be re-opened.
