### ISSUE TITLE
Create a virtual environment

### ISSUE THREAD

**Issue by CMNDER** [pypa/pipenv#4333]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description
i was using pipenv just fine for a couple of months until last night when i tried to launch my virtual environment and kept refusing giving me this error

### Expected result

as usual i expected it to run smooth but this time it kept crashing

### Actual result

$ pipenv shell
Creating a virtualenv for this project…
Pipfile: D:\e-commerce\Pipfile
Using C:/Python38/python.exe (None) to create virtualenv…
[ ===] Creating virtual environment...FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Python38/python.exe'

Failed creating virtual environment

[pipenv.exceptions.VirtualenvCreationException]:
Failed to create virtual environment.

### Steps to replicate
pipenv shell
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
django = "==3.0.6"
autopep8 = "==1.5.2"
pep8 = "==1.7.1"
pycodestyle = "==2.6.0"
pytz = "==2020.1"
sqlparse = "==0.3.1"
django-allauth = "*"
django-crispy-forms = "*"
django-countries = "*"
pillow = "*"
psycopg2 = "*"
openssl = "*"
django-star-ratings = "*"

[requires]
python_version = "3.8"

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.
$ pipenv --support
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.6.2'`

Pipenv location: `'c:\\program files (x86)\\python38-32\\lib\\site-packages\\pipenv'`

Python location: `'c:\\program files (x86)\\python38-32\\python.exe'`

Python installations found:

Traceback (most recent call last):
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python38-32\Scripts\pipenv.exe\__main__.py", line 7, in <module>
  File "C:\Program Files (x86)\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files (x86)\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files (x86)\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "C:\Program Files (x86)\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files (x86)\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files (x86)\Python38-32\Lib\site-packages\pipenv\vendor\click\decorators.py", line 73, in new_func      
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files (x86)\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files (x86)\Python38-32\Lib\site-packages\pipenv\vendor\click\decorators.py", line 21, in new_func      
    return f(get_current_context(), *args, **kwargs)
  File "c:\program files (x86)\python38-32\lib\site-packages\pipenv\cli\command.py", line 139, in cli
    get_pipenv_diagnostics()
  File "c:\program files (x86)\python38-32\lib\site-packages\pipenv\help.py", line 33, in get_pipenv_diagnostics
    python_paths = finder.find_all_python_versions()
  File "c:\program files (x86)\python38-32\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 328, in find_all_python_versions
    path_list = sorted(versions, key=version_sort, reverse=True)
AttributeError: 'NoneType' object has no attribute 'version_sort'

**Comment by frostming** [comment]
It seems you have a broken python installation at `C:/Python38/python.exe`, uninstall and try again?

**Comment by CMNDER** [comment]
i have uninstalled python and reinstalled like almost 4 times i never change the default install directory 
but i keep getting the error

**Comment by frostming** [comment]
It comes from a stale registry entry, you need to clean it

**Comment by frostming** [comment]
Please try the latest release(2020.11.4)

**Comment by CMNDER** [comment]
noted
