### ISSUE TITLE
FileNotFoundError: [WinError 2] 

### ISSUE THREAD

**Issue by zzpsy** [pypa/pipenv#4356]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

The pipenv shell command doesn't work on my system

### Expected result

The command should create a virtual env.

### Actual result

Launching subshell in virtual environment…
Traceback (most recent call last):
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Zhang\AppData\Local\Programs\Python\Python36\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\site-packages\pipenv\cli\command.py", line 433, in shell
    pypi_mirror=state.pypi_mirror,
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\site-packages\pipenv\core.py", line 2390, in do_shell
    shell.fork(*fork_args)
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\site-packages\pipenv\shells.py", line 97, in fork
    _handover(self.cmd, self.args + list(args))
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\site-packages\pipenv\shells.py", line 62, in _handover
    sys.exit(subprocess.call(args, shell=True, universal_newlines=True))
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\users\zhang\appdata\local\programs\python\python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2]

### Steps to replicate
OS: Windows.10.0.17763

1. Open the terminal of Pycharm
2. run pipenv install
3. run pipenv shell

P.S. I've uninstalled and installed different versions of Python, and reinstalled pipenv everytime. So it shouldn't be python's interpreter problem.

**Comment by matteius** [comment]
@zzpsy Is this still an issue on `pipenv==2022.8.19`?
