### ISSUE TITLE
fatal error when executing pipenv shell

### ISSUE THREAD

**Issue by vladic4t** [pypa/pipenv#4358]
### Issue description

Can't get pipenv to work!

### Expected result
A virtual environment to be created using `pipenv shell`

### Actual result
I receive the following output:
```
PS C:\Users\vladic4t\Desktop\networking_test\ws> pipenv shell
Traceback (most recent call last):
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\python.py", line 618, in parse_executable
    result_version = get_python_version(path)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\utils.py", line 105, in get_python_version
    c = subprocess.Popen(version_cmd, **subprocess_kwargs)
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\cli\command.py", line 428, in shell
    do_shell(
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\core.py", line 2363, in do_shell
    ensure_project(
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\core.py", line 576, in ensure_project
    ensure_virtualenv(
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\core.py", line 498, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\core.py", line 388, in ensure_python
    path_to_python = find_a_system_python(python)
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\core.py", line 350, in find_a_system_python
    return next(iter(finder.find_all_python_versions()), None)
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 312, in find_all_python_versions
    python_version_dict = getattr(self.system_path, "python_version_dict", {})
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 120, in system_path
    self._system_path = self.create_system_path()
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 82, in create_system_path
    return pyfinder_path.SystemPath.create(
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 682, in create
    instance = instance._run_setup()
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 233, in _run_setup
    new_instance = new_instance._setup_windows()
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 411, in _setup_windows
    windows_finder = WindowsFinder.create()
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\windows.py", line 146, in create
    return cls()
  File "<attrs generated init pythonfinder.models.windows.WindowsFinder>", line 13, in __init__
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\windows.py", line 113, in get_versions
    versions[py_version.version_tuple[:5]] = base_dir
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\python.py", line 365, in __getattribute__
    result = super(PythonVersion, self).__getattribute__(key)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\python.py", line 430, in version_tuple
    self.patch,
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\python.py", line 375, in __getattribute__
    instance_dict = self.parse_executable(executable)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\python.py", line 620, in parse_executable
    raise ValueError("Not a valid python path: %r" % path)
ValueError: Not a valid python path: 'C:/Panda3D-1.10.4.1-x64/python/python.exe'
```

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

### Steps to replicate

install python 3.8.3 version followed by `pip install pipenv`

-------------------------------------------------------------------------------
```

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.6.2'`

Pipenv location: `'c:\\users\\vladic4t\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\pipenv'`

Python location: `'c:\\users\\vladic4t\\appdata\\local\\programs\\python\\python38-32\\python.exe'`

Python installations found:

Traceback (most recent call last):
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\python.py", line 618, in parse_executable
    result_version = get_python_version(path)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\utils.py", line 105, in get_python_version
    c = subprocess.Popen(version_cmd, **subprocess_kwargs)
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Scripts\pipenv.exe\__main__.py", line 9, in <module>
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 1236, in invoke
    return Command.invoke(self, ctx)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\cli\command.py", line 139, in cli
    get_pipenv_diagnostics()
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\help.py", line 33, in get_pipenv_diagnostics
    python_paths = finder.find_all_python_versions()
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 312, in find_all_python_versions
    python_version_dict = getattr(self.system_path, "python_version_dict", {})
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 120, in system_path
    self._system_path = self.create_system_path()
  File "c:\users\vladic4t\appdata\local\programs\python\python38-32\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 82, in create_system_path
    return pyfinder_path.SystemPath.create(
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 682, in create
    instance = instance._run_setup()
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 233, in _run_setup
    new_instance = new_instance._setup_windows()
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 411, in _setup_windows
    windows_finder = WindowsFinder.create()
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\windows.py", line 146, in create
    return cls()
  File "<attrs generated init pythonfinder.models.windows.WindowsFinder>", line 13, in __init__
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\windows.py", line 113, in get_versions
    versions[py_version.version_tuple[:5]] = base_dir
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\python.py", line 365, in __getattribute__
    result = super(PythonVersion, self).__getattribute__(key)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\python.py", line 430, in version_tuple
    self.patch,
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\python.py", line 375, in __getattribute__
    instance_dict = self.parse_executable(executable)
  File "C:\Users\vladic4t\AppData\Local\Programs\Python\Python38-32\Lib\site-packages\pipenv\vendor\pythonfinder\models\python.py", line 620, in parse_executable
    raise ValueError("Not a valid python path: %r" % path)
ValueError: Not a valid python path: 'C:/Panda3D-1.10.4.1-x64/python/python.exe'
```

ENVIRONMENTAL VARIABLES

!::=::\
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\vladic4t\AppData\Roaming
asl.log=Destination=file
COMMONPROGRAMFILES=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPOSE_CONVERT_WINDOWS_PATHS=true
COMPUTERNAME=LAPTOP-UALD43FN
COMSPEC=C:\WINDOWS\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
HOMEDRIVE=C:
HOMEPATH=\Users\vladic4t
LOCALAPPDATA=C:\Users\vladic4t\AppData\Local
LOGONSERVER=\\LAPTOP-
MAGICK_HOME=C:\Program Files\ImageMagick-6.9.10-Q16
NUMBER_OF_PROCESSORS=8
OneDrive=C:\Users\vladic4t\OneDrive
OneDriveConsumer=C:\Users\vladic4t\OneDrive
OS=Windows_NT
PATH=/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/Program Files/ImageMagick-6.9.10-Q16:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files/nodejs:/c/Program Files/dotnet:/cmd:/mingw64/bin:/usr/bin:/c/Program Files/PuTTY:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/c/Program Files/Intel/WiFi/bin:/c/Program Files/Common Files/Intel/WirelessCommon:/c/Program Files/Kubernetes/Minikube:/c/Kubernetes:/c/Users/vladic4t/AppData/Local/Programs/Python/Python38-32/Scripts:/c/Users/vladic4t/AppData/Local/Programs/Python/Python38-32:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/Program Files/ImageMagick-6.9.10-Q16:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/iCLS:/c/Program Files/Intel/Intel(R) Management Engine Components/iCLS:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files/nodejs:/c/Program Files/dotnet:/cmd:/mingw64/bin:/usr/bin:/c/Program Files/PuTTY:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/c/Program Files/Intel/WiFi/bin:/c/Program Files/Common F
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 11, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=8e0b
ProgramData=C:\ProgramData
PROGRAMFILES=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PSModulePath=C:\Users\vladic4t\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SYSTEMDRIVE=C:
SYSTEMROOT=C:\WINDOWS
TEMP=/tmp
TMP=/tmp
USERDOMAIN=LAPTOP-
USERDOMAIN_ROAMINGPROFILE=LAPTOP-UALD43FN
USERNAME=vladic4t
USERPROFILE=C:\Users\vladic4t
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
WINDIR=C:\WINDOWS
TERM=cygwin
HOME=/c/Users/vladic4t

**Comment by frostming** [comment]
Fixed in the latest release
