### ISSUE TITLE
ast_parse_setup_py: AttributeError: setup object has no 'keys' attribute

### ISSUE THREAD

**Issue by pdxjohnny** [pypa/pipenv#4374]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

Describe the issue briefly here.

### Expected result

Describe what you expected.

### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

### Steps to replicate

```
pipenv install 'git+https://github.com/intel/dffml#egg=dffml' 'git+https://github.com/intel/dffml#egg=dffml-feature-git&subdirectory=feature/git' 'git+https://github.com/intel/dffml#egg=shouldi&subdirectory=examples/shouldi'
Creating a virtualenv for this project…
Pipfile: C:\Users\johnsa1\Documents\python\intel\Pipfile
Using C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64/python.exe (3.7.5) to create virtualenv…
[ ===] Creating virtual environment...created virtual environment CPython3.7.5.final.0-64 in 15545ms

  creator CPython3Windows(dest=C:\Users\johnsa1\.virtualenvs\intel-7lnbR0eE, clear=False, global=False)

  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=C:\Users\johnsa1\AppData\Local\pypa\virtualenv\seed-app-data\v1.0.1)

  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

Successfully created virtual environment!
Virtualenv location: C:\Users\johnsa1\.virtualenvs\intel-7lnbR0eE
Creating a Pipfile for this project…
Installing git+https://github.com/intel/dffml#egg=dffml…
Adding dffml to Pipfile's [packages]…
Installation Succeeded
Installing git+https://github.com/intel/dffml#egg=dffml-feature-git&subdirectory=feature/git…
Adding dffml-feature-git to Pipfile's [packages]…
Installation Succeeded
Installing git+https://github.com/intel/dffml#egg=shouldi&subdirectory=examples/shouldi…
Adding shouldi to Pipfile's [packages]…
Installation Succeeded
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
 Locking...
Resolving dependencies...
Locking Failed!
Traceback (most recent call last):
  File "c:/program files (x86)/microsoft visual studio/shared/python37_64/lib/site-packages/pipenv/resolver.py", line 807, in <module>
    main()
  File "c:/program files (x86)/microsoft visual studio/shared/python37_64/lib/site-packages/pipenv/resolver.py", line 803, in main
    parsed.requirements_dir, parsed.packages, parse_only=parsed.parse_only)
  File "c:/program files (x86)/microsoft visual studio/shared/python37_64/lib/site-packages/pipenv/resolver.py", line 785, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
  File "c:/program files (x86)/microsoft visual studio/shared/python37_64/lib/site-packages/pipenv/resolver.py", line 753, in resolve_packages
    requirements_dir=requirements_dir,
  File "c:/program files (x86)/microsoft visual studio/shared/python37_64/lib/site-packages/pipenv/resolver.py", line 736, in resolve
    req_dir=requirements_dir
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pipenv\utils.py", line 1386, in resolve_deps
    req_dir=req_dir,
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pipenv\utils.py", line 1091, in actually_resolve_deps
    deps, index_lookup, markers_lookup, project, sources, req_dir, clear, pre
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pipenv\utils.py", line 649, in create
    pre=pre, clear=clear
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pipenv\utils.py", line 463, in get_metadata
    req, resolver=transient_resolver
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pipenv\utils.py", line 540, in get_deps_from_req
    req_list, lockfile = get_vcs_deps(reqs=[req])
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pipenv\utils.py", line 1874, in get_vcs_deps
    with temp_path(), locked_repository(requirement) as repo:
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pipenv\utils.py", line 2030, in locked_repository
    with requirement.req.locked_vcs_repo(src_dir=src_dir) as repo:
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 2212, in locked_vcs_repo
    self._parsed_line.vcsrepo = vcsrepo
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 916, in vcsrepo
    kwargs=wheel_kwargs,
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pipenv\vendor\requirementslib\models\setup_info.py", line 1937, in create
    created.get_initial_info()
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pipenv\vendor\requirementslib\models\setup_info.py", line 1766, in get_initial_info
    self.update_from_dict(self.parse_setup_py())
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pipenv\vendor\requirementslib\models\setup_info.py", line 1523, in parse_setup_py
    parsed = ast_parse_setup_py(self.setup_py.as_posix())
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pipenv\vendor\requirementslib\models\setup_info.py", line 1217, in ast_parse_setup_py
    keys = list(setup.keys())
AttributeError: 'Attribute' object has no attribute 'keys'
```

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.6.2'`

Pipenv location: `'c:\\program files (x86)\\microsoft visual studio\\shared\\python37_64\\lib\\site-packages\\pipenv'`

Python location: `'c:\\program files (x86)\\microsoft visual studio\\shared\\python37_64\\python.exe'`

Python installations found:

  - `3.7.5`: `C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\python.exe`
  - `2.7.15`: `C:\Python27\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.5',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.17763',
 'python_full_version': '3.7.5',
 'python_version': '3.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `DEFLOGDIR`
  - `DRIVERDATA`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `HTTPS_PROXY`
  - `INTELLOGS`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `ONEDRIVECOMMERCIAL`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `UATDATA`
  - `USERDNSDOMAIN`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `VBOX_MSI_INSTALL_PATH`
  - `WINDIR`
  - `_JAVA_OPTIONS`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `LANG`
  - `COLORTERM`
  - `VSCODE_GIT_IPC_HANDLE`
  - `GIT_ASKPASS`
  - `VSCODE_GIT_ASKPASS_NODE`
  - `VSCODE_GIT_ASKPASS_MAIN`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv???specific environment variables:

Debug???specific environment variables:

  - `PATH`: `C:\Program Files\Black Duck Software\protexIP\bin;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\;C:\Users\johnsa1\AppData\Local\Microsoft\WindowsApps;C:\Users\johnsa1\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64;`
  - `LANG`: `en_US.UTF-8`

---------------------------

Contents of `Pipfile` ('C:\\Users\\johnsa1\\Documents\\python\\intel\\Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
dffml = {git = "https://github.com/intel/dffml"}
dffml-feature-git = {git = "https://github.com/intel/dffml", subdirectory = "feature/git"}
shouldi = {git = "https://github.com/intel/dffml", subdirectory = "examples/shouldi"}

[requires]
python_version = "3.7"

```

</details>

**Comment by frostming** [comment]
Fixed on v2021.11.5
