### ISSUE TITLE
pipenv should give me commands that i should run to fix the problem

### ISSUE THREAD

**Issue by glensc** [pypa/pipenv#4380]
I don't use pipenv daily (just setup one project year ago and was happy),
now the host that I run the pipenv has upgraded python3.6 -> python3.7.

the obvious commands don't work (the ones I noted down in readme to execute)
and the errors give no helpful info what to do.

instead if saying `pipenv check will surely fail.` say instead "run pipenv foo" or "rm Pipfile and retry" to fix the problem and/or "please ensure your pipenv is up to date by running pipenv self-update"

```
07:35:21 root[load: 0.00]@ipa gitlab-registry-tools/registry-usage# pipenv --python python3 install
Virtualenv already exists!
Removing existing virtualenv...
Creating a virtualenv for this project...
Pipfile: /srv/gitlab-registry-tools/registry-usage/Pipfile
Using /usr/bin/python3 (3.7.3) to create virtualenv...
⠋Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
/usr/local/lib/python2.7/dist-packages/virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /home/glen/.local/share/virtualenvs/registry-usage-1e3voAqq/bin/python3
Also creating executable in /home/glen/.local/share/virtualenvs/registry-usage-1e3voAqq/bin/python
Installing setuptools, pip, wheel...done.
Setting project for registry-usage-1e3voAqq to /srv/gitlab-registry-tools/registry-usage

Virtualenv location: /home/glen/.local/share/virtualenvs/registry-usage-1e3voAqq
Warning: Your Pipfile requires python_version 3.6, but you are using 3.7.3 (/home/glen/.local/share/v/r/bin/python).
  $ pipenv check will surely fail.
Warning: Your Pipfile requires python_version 3.6, but you are using 3.7.3 (/home/glen/.local/share/v/r/bin/python).
  $ pipenv check will surely fail.                                                                                                                                    Installing dependencies from Pipfile.lock (801d7e)...
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 435, in install
    selective_upgrade=selective_upgrade,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 1943, in do_install
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 1322, in do_init
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 764, in do_install_dependencies
    only=only,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 803, in merge_deps
    file_dict[section], project, r=False, include_index=include_index
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 509, in convert_deps_to_pip
    from .vendor.requirementslib import Requirement
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requirementslib/__init__.py", line 6, in <module>
    from .models import Requirement, Lockfile, Pipfile
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requirementslib/models/__init__.py", line 8, in <module>
    from .requirements import Requirement
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requirementslib/models/requirements.py", line 14, in <module>
    from .markers import PipenvMarkers
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requirementslib/models/markers.py", line 6, in <module>
    from .utils import validate_markers, filter_none
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requirementslib/models/utils.py", line 7, in <module>
    from .._compat import Link
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requirementslib/_compat.py", line 41, in <module>
    InstallRequirement = do_import("req.req_install", "InstallRequirement")
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/requirementslib/_compat.py", line 35, in do_import
    _tmp = importlib.import_module(pip9)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named pip.req.req_install
/usr/local/lib/python2.7/dist-packages/pipenv/_compat.py:113: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/pipenv-ziQQsU-requirements'>
  warnings.warn(warn_message, ResourceWarning)

07:36:55 root[load: 0.11]@ipa gitlab-registry-tools/registry-usage#

```

### Additional context

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/usr/local/lib/python2.7/dist-packages/pipenv'`

Python location: `'/usr/bin/python'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/usr/bin/python3.5m`
  - `3.5`: `/usr/bin/python3.5`
  - `3.7`: `/usr/bin/python3.7m`
  - `3.7`: `/usr/bin/python3.7`

  - `2.7.16`: `/usr/bin/python`
  - `2.7.16`: `/usr/bin/python2`
  - `3.7.3`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.19.0-8-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27)',
 'python_full_version': '2.7.16',
 'python_version': '2.7',
 'sys_platform': 'linux2'}
```

**Comment by glensc** [comment]
seems newer version already does this partially (suggesting `pipenv --rm`)

```
07:49:33 root[load: 0.81]@ipa gitlab-registry-tools/registry-usage# pipenv --python python3 install
Virtualenv already exists!
Removing existing virtualenv…
Creating a virtualenv for this project…
Pipfile: /srv/gitlab-registry-tools/registry-usage/Pipfile
Using /usr/bin/python3.7m (3.7.3) to create virtualenv…
⠹ Creating virtual environment...Using base prefix '/usr'
New python executable in /home/glen/.local/share/virtualenvs/registry-usage-1e3voAqq/bin/python3.7m
Also creating executable in /home/glen/.local/share/virtualenvs/registry-usage-1e3voAqq/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Running virtualenv with interpreter /usr/bin/python3.7m
✔ Successfully created virtual environment!
Virtualenv location: /home/glen/.local/share/virtualenvs/registry-usage-1e3voAqq
Warning: Your Pipfile requires python_version 3.6, but you are using 3.7.3 (/home/glen/.local/share/v/r/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Warning: Your Pipfile requires python_version 3.6, but you are using 3.7.3 (/home/glen/.local/share/v/r/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Installing dependencies from Pipfile.lock (801d7e)…
  �   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 13/13 — 00:00:12

```

**Comment by glensc** [comment]
however, running `pipenv --rm` will not make version mismatch error go away:

```
Warning: Your Pipfile requires python_version 3.6, but you are using 3.7.3 (/home/glen/.local/share/v/r/bin/python).
```

it's only removing virtualenv which install did anyway:

```

07:51:35 root[load: 1.41]@ipa gitlab-registry-tools/registry-usage# pipenv --rm
Removing virtualenv (/home/glen/.local/share/virtualenvs/registry-usage-1e3voAqq)…

07:52:12 root[load: 0.79]@ipa gitlab-registry-tools/registry-usage#


07:52:44 root[load: 1.98]@ipa gitlab-registry-tools/registry-usage# pipenv --python python3 install
Virtualenv already exists!
Removing existing virtualenv…
Creating a virtualenv for this project…
Pipfile: /srv/gitlab-registry-tools/registry-usage/Pipfile
Using /usr/bin/python3.7m (3.7.3) to create virtualenv…
⠏ Creating virtual environment...Using base prefix '/usr'
New python executable in /home/glen/.local/share/virtualenvs/registry-usage-1e3voAqq/bin/python3.7m
Also creating executable in /home/glen/.local/share/virtualenvs/registry-usage-1e3voAqq/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Running virtualenv with interpreter /usr/bin/python3.7m
✔ Successfully created virtual environment!
Virtualenv location: /home/glen/.local/share/virtualenvs/registry-usage-1e3voAqq
Warning: Your Pipfile requires python_version 3.6, but you are using 3.7.3 (/home/glen/.local/share/v/r/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Warning: Your Pipfile requires python_version 3.6, but you are using 3.7.3 (/home/glen/.local/share/v/r/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Installing dependencies from Pipfile.lock (801d7e)…
  �   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 13/13 — 00:00:13
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

```

**Comment by matteius** [comment]
@glensc the dependency and import usages on pip are a lot more deterministic these days.   Is this still an issue for you?

**Comment by glensc** [comment]
too old to reproduce
