### ISSUE TITLE
install timeout

### ISSUE THREAD

**Issue by dhcn** [pypa/pipenv#4391]
```console
$ pipenv install  jupyter
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing jupyter…
✔ Installation Succeeded 
Pipfile.lock (733e71) out of date, updating to (7cb7b0)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.7.7/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/cli/command.py", line 252, in install
    site_packages=state.site_packages
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/core.py", line 2201, in do_install
    skip_lock=skip_lock,
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/core.py", line 1281, in do_init
    pypi_mirror=pypi_mirror,
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/core.py", line 1114, in do_lock
    keep_outdated=keep_outdated
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 1323, in venv_resolve_deps
    c = resolve(cmd, sp)
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/utils.py", line 1136, in resolve
    result = c.expect(u"\n", timeout=environments.PIPENV_INSTALL_TIMEOUT)
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/delegator.py", line 215, in expect
    self.subprocess.expect(pattern=pattern, timeout=timeout)
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 344, in expect
    timeout, searchwindowsize, async_)
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 372, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/usr/local/var/pyenv/versions/3.7.7/lib/python3.7/site-packages/pipenv/vendor/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x111156e10>
searcher: searcher_re:
    0: re.compile('\n')
<pexpect.popen_spawn.PopenSpawn object at 0x111156e10>
searcher: searcher_re:
    0: re.compile('\n')
```
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

Describe the issue briefly here.

### Expected result

Describe what you expected.

### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by mjpieters** [comment]
This is almost certainly the same issue as #4403

**Comment by mjpieters** [comment]
For a work-around, downgrade pipenv to a version *before* v2020.4.1b2, so 2018.11.26 or earlier. Or temporarily move everything except files needed to make `pip install -e .` succeed out of your project directory (including hidden directories) and for good measure set `PIPENV_INSTALL_TIMEOUT` to a high value.

**Comment by frostming** [comment]
Closing this issue in favor of #4424
