### ISSUE TITLE
jetson tx2 install error

### ISSUE THREAD

**Issue by coffice12** [pypa/pipenv#4402]
Requirement already satisfied: distlib<1,>=0.3.1 in /root/.pyenv/versions/3.8.2/lib/python3.8/site-packages (from virtualenv->pipenv==2018.11.26) (0.3.1)
Your Pipfile.lock (83cedf) is out of date. Expected: (5421c2).
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.2/bin/pipenv", line 10, in <module>
    sys.exit(cli())
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/cli/command.py", line 235, in install
    retcode = do_install(
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/core.py", line 1863, in do_install
    do_init(
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/core.py", line 1192, in do_init
    raise exceptions.DeployException
  File "/root/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pipenv/exceptions.py", line 168, in __init__
    PipenvUsageError.__init__(message=fix_utf8(message), extra=extra, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'self'

**Comment by frostming** [comment]
Try upgrading Pipenv to `2020.8.13`.
