### ISSUE TITLE
pipenv update fails for latest pipenv version 2020-08-13: AttributeError: 'NoneType' object has no attribute 'url'

### ISSUE THREAD

**Issue by dashsatish** [pypa/pipenv#4458]
### Issue description
`pipenv update` fails in the project for latest pipenv version

### Expected result

pipenv update must have successfully updated `Pipfile.lock` instead of failing

## Actual result

```$ pipenv update 
Running $ pipenv lock then $ pipenv sync.
Locking [dev-packages] dependencies…
Building requirements...
Resolving dependencies...
✔ Success!
Locking [packages] dependencies…
Building requirements...
Traceback (most recent call last):
  File "/Users/satishdash/.pyenv/versions/3.8.5/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/cli/command.py", line 585, in update
    do_lock(
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/core.py", line 1102, in do_lock
    venv_resolve_deps(
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/utils.py", line 1317, in venv_resolve_deps
    deps = convert_deps_to_pip(
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/utils.py", line 1437, in convert_deps_to_pip
    req = new_dep.as_line(sources=indexes if include_index else None).strip()
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2792, in as_line
    parts = self.line_instance.get_line(
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 225, in get_line
    line = self.name_and_specifier
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 270, in name_and_specifier
    if self.specifier:
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 394, in specifier
    for req in (self.ireq, self.requirement):
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 779, in ireq
    self.parse_ireq()
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 941, in parse_ireq
    self._ireq = self.get_ireq()
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 921, in get_ireq
    line = self.line_for_ireq
  File "/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 346, in line_for_ireq
    line = self.link.url
AttributeError: 'NoneType' object has no attribute 'url'
```

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

Pyenv version : `'pyenv 1.2.20'`

Pipenv version: `'2020.8.13'`

Pipenv location: `'/Users/satishdash/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv'`

Python location: `'/Users/satishdash/.pyenv/versions/3.8.5/bin/python'`

Python installations found:

  - `3.8.5`: `/Users/satishdash/.local/share/virtualenvs/*********/bin/python3`
  - `3.8.5`: `/Users/satishdash/.local/share/virtualenvs/*********/bin/python3.8`
  - `3.8.5`: `/Users/satishdash/.pyenv/versions/3.8.5/bin/python3`
  - `3.8.5`: `/Users/satishdash/.pyenv/versions/3.8.5/bin/python3`
  - `3.8.5`: `/Users/satishdash/.pyenv/versions/3.8.5/bin/python3.8`
  - `3.8.5`: `/usr/local/bin/python3`
  - `3.8.5`: `/usr/local/bin/python3.8`
  - `3.7.8`: `/Users/satishdash/.pyenv/versions/3.7.8/bin/python3`
  - `3.7.3`: `/usr/bin/python3`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '19.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT '
                     '2020; root:xnu-6153.141.1~9/RELEASE_X86_64',
 'python_full_version': '3.8.5',
 'python_version': '3.8',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `ZNT_CONFIG_DIR`
  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `PIP_PYTHON_PATH`
  - `SHELL`
  - `TERM`
  - `TMPDIR`
  - `private`
  - `TERM_PROGRAM_VERSION`
  - `scratch_dir`
  - `ZNT_REPO_DIR`
  - `TERM_SESSION_ID`
  - `ZSH`
  - `LC_ALL`
  - `PYENV_VERSION`
  - `USER`
  - `COMMAND_MODE`
  - `PYENV_DIR`
  - `SSH_AUTH_SOCK`
  - `cd_scratch`
  - `__CF_USER_TEXT_ENCODING`
  - `VIRTUAL_ENV`
  - `PAGER`
  - `LSCOLORS`
  - `PIPENV_ACTIVE`
  - `PATH`
  - `LaunchInstanceID`
  - `cd_satdash`
  - `PWD`
  - `LANG`
  - `ITERM_PROFILE`
  - `PYENV_HOOK_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`
  - `XPC_FLAGS`
  - `PYTHONDONTWRITEBYTECODE`
  - `XPC_SERVICE_NAME`
  - `COLORFGBG`
  - `HOME`
  - `SHLVL`
  - `PYENV_SHELL`
  - `LC_TERMINAL_VERSION`
  - `ITERM_SESSION_ID`
  - `LOGNAME`
  - `LESS`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `HOMEBREW_NO_INSTALL_CLEANUP`
  - `LC_CTYPE`
  - `LC_TERMINAL`
  - `satdash_dir`
  - `SECURITYSESSIONID`
  - `COLORTERM`
  - `PIP_SHIMS_BASE_MODULE`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/satishdash/.pyenv/versions/3.8.5/bin:/usr/local/Cellar/pyenv/1.2.20/libexec:/Users/satishdash/.local/share/virtualenvs/*******/bin:/usr/local/opt/make/libexec/gnubin:/Users/satishdash/.pyenv/shims:/Users/satishdash/bin:/usr/local/bin:/Users/satishdash/.pyenv/versions/3.8.5/bin:/usr/local/Cellar/pyenv/1.2.20/libexec:/usr/local/opt/make/libexec/gnubin:/Users/satishdash/.pyenv/shims:/Users/satishdash/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/private/scratch/satdash/*****************`
  - `VIRTUAL_ENV`: `/Users/satishdash/.local/share/virtualenvs/*********-I6xt5Ff_`

---------------------------

Contents of `Pipfile` ('/private/scratch/satdash/**********/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
flask = "*"
ipdb = "*"
psycopg2-binary = "==2.8.*"
pytest = "~= 5.3"
pytest-django = "~= 3.7"
pytest-cov = "~= 2.8"
requests-mock = "*"
moto = "*"
jsonschema = "*"
factory-boy = "*"

[packages]
django = "== 3.0.*"
djangorestframework = "== 3.11.*"
psycopg2 = "== 2.8.*"
python-dotenv = "==0.10.3"
sentry-sdk = "== 0.14.*"
pySqsListener = "==0.8.7"
requests = "*"
ramda = "*"
drf-yasg = "*"
pyyaml = "*"
django-cors-headers = {editable = true,version = "*"}
boto3 = "*"

[requires]
python_version = "3.8"

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by frostming** [comment]
`django-cors-headers = {editable = true,version = "*"}`

You can't mark a named requirement as editable, instead it must be a local path or VCS URL.
