### ISSUE TITLE
   ImportError: libffi.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by M-AamirBakhtiar** [pypa/pipenv#4491]
Hello, i am new to Linux Ubuntu 20.4  and Python. While create a new virtual environment for a practice Django project i can successfully install Django by using pipenv install django==3.0  after that i can successfully activate it by using pipenv shell 

### Issue description

But after opening the project files in VSCode and setting the python interpreter to be the one in the Virtual Environment i get a warning that autopep8 is not install  click to install it.

### Expected result

After clicking to install it  it runs the following command in the terminal 
pipenv install autopep8 --dev

### Actual result

But it fails to do so and throws this error 

(django) django:$ pipenv install autopep8 --dev
Installing autopep8…
Error:  An error occurred while installing autopep8!
Error text: Collecting autopep8
  Using cached autopep8-1.5.4.tar.gz (121 kB)

    ERROR: Command errored out with exit status 1:
     command: /home/aamir/.local/share/virtualenvs/django-ErN6pXik/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4g3myi71/autopep8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4g3myi71/autopep8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3htb9f45
         cwd: /tmp/pip-install-4g3myi71/autopep8/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/aamir/.local/share/virtualenvs/django-ErN6pXik/lib/python3.8/site-packages/setuptools/__init__.py", line 19, in <module>
        from setuptools.dist import Distribution
      File "/home/aamir/.local/share/virtualenvs/django-ErN6pXik/lib/python3.8/site-packages/_virtualenv.py", line 74, in exec_module
        old(module)
      File "/home/aamir/.local/share/virtualenvs/django-ErN6pXik/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/home/aamir/.local/share/virtualenvs/django-ErN6pXik/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

This is likely caused by a bug in autopep8. Report this to its maintainers.
✘ Installation Failed

**Comment by M-AamirBakhtiar** [comment]
the following line of code has fixed my issue
pipenv install --python=/usr/bin/python3.8
