### ISSUE TITLE
Locking creates TypeError: 'LegacySpecifier' object is not iterable

### ISSUE THREAD

**Issue by davidhuser** [pypa/pipenv#4495]
> Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Done, running `Version: 2020.8.13`.

> Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Done, did not help

### Issue description

Installing the package [dhis2.py](https://github.com/davidhuser/dhis2.py) works, but locking fails due to a TypeError (see below).

### Expected result

Installation succeeds, and locking succeeds.

### Actual result

```
pipenv install dhis2.py --verbose
Using python: None
Path to python: /usr/bin/python3
Creating a virtualenv for this project…
Pipfile: /home/david/Downloads/dpy/Pipfile
Using /usr/bin/python3 (3.8.5) to create virtualenv…
⠹ Creating virtual environment...created virtual environment CPython3.8.5.final.0-64 in 138ms
  creator CPython3Posix(dest=/home/david/Downloads/dpy/.venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/david/.local/share/virtualenv)
    added seed packages: pip==20.2.3, setuptools==50.3.0, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/david/Downloads/dpy/.venv
Creating a Pipfile for this project…
Installing dhis2.py…
Installing package: dhis2.py
Writing supplied requirement line to temporary file: 'dhis2.py'
Installing 'dhis2.py'
$ ['/home/david/Downloads/dpy/.venv/bin/pip', 'install', '--verbose', '--upgrade', '--exists-action=i', '-r', '/tmp/pipenv-lw53ise0-requirements/pipenv-wrc7us2y-requirement.txt', '-i', 'https://pypi.org/simple']
Using source directory: '/home/david/Downloads/dpy/.venv/src'
Adding dhis2.py to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
⠇ Locking...
                          ROUND 1                           
✘ Locking Failed! 
Current constraints:
  dhis2.py (from -r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))

Finding the best candidates:
  found candidate dhis2.py==2.1.1 (constraint was <any>)

Finding secondary dependencies:
  dhis2.py==2.1.1           requires logzero>=1.5.0, pygments>=2.7.1, requests<3.0,>=2.24.0

New dependencies found in this round:
  adding ['logzero', '>=1.5.0', '[]']
  adding ['pygments', '>=2.7.1', '[]']
  adding ['requests', '<3.0,>=2.24.0', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  dhis2.py (from -r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  logzero>=1.5.0 (from dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  pygments>=2.7.1 (from dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  requests<3.0,>=2.24.0 (from dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))

Finding the best candidates:
  found candidate dhis2.py==2.1.1 (constraint was <any>)
  found candidate logzero==1.5.0 (constraint was >=1.5.0)
  found candidate pygments==2.7.1 (constraint was >=2.7.1)
  found candidate requests==2.24.0 (constraint was >=2.24.0,<3.0)

Finding secondary dependencies:
  requests==2.24.0          requires certifi>=2017.4.17, chardet<4,>=3.0.2, idna<3,>=2.5, urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  logzero==1.5.0            requires -
  pygments==2.7.1           requires -
  dhis2.py==2.1.1           requires logzero>=1.5.0, pygments>=2.7.1, requests<3.0,>=2.24.0

New dependencies found in this round:
  adding ['certifi', '>=2017.4.17', '[]']
  adding ['chardet', '<4,>=3.0.2', '[]']
  adding ['idna', '<3,>=2.5', '[]']
  adding ['urllib3', '!=1.25.0,!=1.25.1,<1.26,>=1.21.1', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 2: not stable

                          ROUND 3                           
Current constraints:
  certifi>=2017.4.17 (from requests==2.24.0->dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  chardet<4,>=3.0.2 (from requests==2.24.0->dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  dhis2.py (from -r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  idna<3,>=2.5 (from requests==2.24.0->dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  logzero>=1.5.0 (from dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  pygments>=2.7.1 (from dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  requests<3.0,>=2.24.0 (from dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests==2.24.0->dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))

Finding the best candidates:
  found candidate certifi==2020.6.20 (constraint was >=2017.4.17)
  found candidate chardet==3.0.4 (constraint was >=3.0.2,<4)
  found candidate dhis2.py==2.1.1 (constraint was <any>)
  found candidate idna==2.10 (constraint was >=2.5,<3)
  found candidate logzero==1.5.0 (constraint was >=1.5.0)
  found candidate pygments==2.7.1 (constraint was >=2.7.1)
  found candidate requests==2.24.0 (constraint was >=2.24.0,<3.0)
  found candidate urllib3==1.25.10 (constraint was >=1.21.1,!=1.25.0,!=1.25.1,<1.26)

Finding secondary dependencies:
  pygments==2.7.1           requires -
  certifi==2020.6.20        requires -
  chardet==3.0.4            requires -
  idna==2.10                requires -
  urllib3==1.25.10          requires -
  dhis2.py==2.1.1           requires logzero>=1.5.0, pygments>=2.7.1, requests<3.0,>=2.24.0
  requests==2.24.0          requires certifi>=2017.4.17, chardet<4,>=3.0.2, idna<3,>=2.5, urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  logzero==1.5.0            requires -
------------------------------------------------------------
Result of round 3: stable, done

Generating hashes:
  logzero
  pygments
  chardet
  idna
  urllib3
  dhis2.py
  requests
  certifi
Traceback (most recent call last):
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 807, in <module>
    main()
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 802, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 785, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 746, in resolve_packages
    results, resolver = resolve(
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 728, in resolve
    return resolve_deps(
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/utils.py", line 1378, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/utils.py", line 1095, in actually_resolve_deps
    resolver.resolve_constraints()
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/utils.py", line 847, in resolve_constraints
    marker = marker_from_specifier(candidate.requires_python)
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 719, in marker_from_specifier
    for marker_segment in cleanup_pyspecs(spec):
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 288, in cleanup_pyspecs
    for op_and_version_type, versions in _group_by_op(tuple(specs)):
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 203, in _group_by_op
    specs = [_get_specs(x) for x in list(specs)]
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 203, in <listcomp>
    specs = [_get_specs(x) for x in list(specs)]
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 187, in _get_specs
    for spec in set(specset):
TypeError: 'LegacySpecifier' object is not iterable
ROUND 1                           
Current constraints:
  dhis2.py (from -r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))

Finding the best candidates:
  found candidate dhis2.py==2.1.1 (constraint was <any>)

Finding secondary dependencies:
  dhis2.py==2.1.1           requires logzero>=1.5.0, pygments>=2.7.1, requests<3.0,>=2.24.0

New dependencies found in this round:
  adding ['logzero', '>=1.5.0', '[]']
  adding ['pygments', '>=2.7.1', '[]']
  adding ['requests', '<3.0,>=2.24.0', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  dhis2.py (from -r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  logzero>=1.5.0 (from dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  pygments>=2.7.1 (from dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  requests<3.0,>=2.24.0 (from dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))

Finding the best candidates:
  found candidate dhis2.py==2.1.1 (constraint was <any>)
  found candidate logzero==1.5.0 (constraint was >=1.5.0)
  found candidate pygments==2.7.1 (constraint was >=2.7.1)
  found candidate requests==2.24.0 (constraint was >=2.24.0,<3.0)

Finding secondary dependencies:
  requests==2.24.0          requires certifi>=2017.4.17, chardet<4,>=3.0.2, idna<3,>=2.5, urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  logzero==1.5.0            requires -
  pygments==2.7.1           requires -
  dhis2.py==2.1.1           requires logzero>=1.5.0, pygments>=2.7.1, requests<3.0,>=2.24.0

New dependencies found in this round:
  adding ['certifi', '>=2017.4.17', '[]']
  adding ['chardet', '<4,>=3.0.2', '[]']
  adding ['idna', '<3,>=2.5', '[]']
  adding ['urllib3', '!=1.25.0,!=1.25.1,<1.26,>=1.21.1', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 2: not stable

                          ROUND 3                           
Current constraints:
  certifi>=2017.4.17 (from requests==2.24.0->dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  chardet<4,>=3.0.2 (from requests==2.24.0->dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  dhis2.py (from -r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  idna<3,>=2.5 (from requests==2.24.0->dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  logzero>=1.5.0 (from dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  pygments>=2.7.1 (from dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  requests<3.0,>=2.24.0 (from dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))
  urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests==2.24.0->dhis2.py==2.1.1->-r /tmp/pipenvipokdamfrequirements/pipenv-0cw8gidz-constraints.txt (line 2))

Finding the best candidates:
  found candidate certifi==2020.6.20 (constraint was >=2017.4.17)
  found candidate chardet==3.0.4 (constraint was >=3.0.2,<4)
  found candidate dhis2.py==2.1.1 (constraint was <any>)
  found candidate idna==2.10 (constraint was >=2.5,<3)
  found candidate logzero==1.5.0 (constraint was >=1.5.0)
  found candidate pygments==2.7.1 (constraint was >=2.7.1)
  found candidate requests==2.24.0 (constraint was >=2.24.0,<3.0)
  found candidate urllib3==1.25.10 (constraint was >=1.21.1,!=1.25.0,!=1.25.1,<1.26)

Finding secondary dependencies:
  pygments==2.7.1           requires -
  certifi==2020.6.20        requires -
  chardet==3.0.4            requires -
  idna==2.10                requires -
  urllib3==1.25.10          requires -
  dhis2.py==2.1.1           requires logzero>=1.5.0, pygments>=2.7.1, requests<3.0,>=2.24.0
  requests==2.24.0          requires certifi>=2017.4.17, chardet<4,>=3.0.2, idna<3,>=2.5, urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  logzero==1.5.0            requires -
------------------------------------------------------------
Result of round 3: stable, done

Generating hashes:
  logzero
  pygments
  chardet
  idna
  urllib3
  dhis2.py
  requests
  certifi
Traceback (most recent call last):
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 807, in <module>
    main()
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 802, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 785, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 746, in resolve_packages
    results, resolver = resolve(
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 728, in resolve
    return resolve_deps(
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/utils.py", line 1378, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/utils.py", line 1095, in actually_resolve_deps
    resolver.resolve_constraints()
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/utils.py", line 847, in resolve_constraints
    marker = marker_from_specifier(candidate.requires_python)
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 719, in marker_from_specifier
    for marker_segment in cleanup_pyspecs(spec):
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 288, in cleanup_pyspecs
    for op_and_version_type, versions in _group_by_op(tuple(specs)):
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 203, in _group_by_op
    specs = [_get_specs(x) for x in list(specs)]
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 203, in <listcomp>
    specs = [_get_specs(x) for x in list(specs)]
  File "/home/david/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 187, in _get_specs
    for spec in set(specset):
TypeError: 'LegacySpecifier' object is not iterable
```

**Error: TypeError: 'LegacySpecifier' object is not iterable**

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

Command: 
```
pipenv install dhis2.py
```

[Pipfile of the package:](https://github.com/davidhuser/dhis2.py/blob/master/Pipfile)

```
[[source]]
name = "pypi"
url = "https://pypi.python.org/simple"
verify_ssl = true

[dev-packages]
pytest = "*"
pytest-cov = "*"
pytest-rerunfailures = "*"
responses = "*"
mypy = "*"
flake8 = "*"
pre-commit = "*"

[packages]
requests = "*"
logzero = "*"
Pygments = "*"

[scripts]
tests = "python -m pytest --cov=dhis2 --cov-fail-under=100 --cov-report term-missing tests -vv"
```

[`setup.py` of the package:](https://github.com/davidhuser/dhis2.py/blob/master/setup.py)

```
#!/usr/bin/env python

import os
import sys
from codecs import open
from shutil import rmtree

from setuptools import setup, find_packages, Command

here = os.path.abspath(os.path.dirname(__file__))

requirements = ["requests>=2.24.0,<3.0", "logzero>=1.5.0", "Pygments>=2.7.1"]


about = {}
with open(os.path.join(here, "dhis2", "__version__.py"), "r", "utf-8") as f:
    exec(f.read(), about)

with open("README.rst", "r", "utf-8") as f:
    readme = f.read()


class PublishCommand(Command):
    """Support setup.py publish."""

    description = "Build and publish the package."
    user_options = []

    @staticmethod
    def status(s):
        """Prints things in bold."""
        print("\033[1m{0}\033[0m".format(s))

    def initialize_options(self):
        pass

    def finalize_options(self):
        pass

    def run(self):
        try:
            self.status("Removing previous builds...")
            rmtree(os.path.join(here, "dist"))
        except (OSError, IOError):
            pass

        self.status("Building Source and Wheel (universal) distribution...")
        os.system("{0} setup.py sdist bdist_wheel --universal".format(sys.executable))

        self.status("Uploading the package to PyPi via Twine...")
        os.system("twine upload dist/*")

        self.status("Pushing git tags...")
        os.system("git tag v{0}".format(about["__version__"]))
        os.system("git push --tags")

        sys.exit()


setup(
    name=about["__title__"],
    version=about["__version__"],
    description=about["__description__"],
    long_description=readme,
    author=about["__author__"],
    author_email=about["__author_email__"],
    url=about["__url__"],
    keywords="dhis2",
    packages=find_packages(exclude=["tests", "examples"]),
    python_requires="!=2.*.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*",
    install_requires=requirements,
    license=about["__license__"],
    zip_safe=False,
    classifiers=(  # https://pypi.org/pypi?%3Aaction=list_classifiers
        "License :: OSI Approved :: MIT License",
        "Intended Audience :: Developers",
        "Development Status :: 5 - Production/Stable",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
    ),
    cmdclass={"publish": PublishCommand},
)
```

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.8.13'`

Pipenv location: `'/home/david/.local/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.8.5`: `/usr/bin/python3`
  - `3.8.5`: `/usr/bin/python3.8`
  - `3.8.5`: `/bin/python3`
  - `3.8.5`: `/bin/python3.8`
  - `2.7.18`: `/usr/bin/python2.7`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/bin/python2.7`
  - `2.7.18`: `/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.0-7642-generic',
 'platform_system': 'Linux',
 'platform_version': '#46~1598628707~20.04~040157c-Ubuntu SMP Fri Aug 28 '
                     '18:02:16 UTC ',
 'python_full_version': '3.8.5',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `COLORTERM`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DESKTOP_SESSION`
  - `DISPLAY`
  - `GDMSESSION`
  - `GNOME_DESKTOP_SESSION_ID`
  - `GNOME_SHELL_SESSION_MODE`
  - `GNOME_TERMINAL_SCREEN`
  - `GNOME_TERMINAL_SERVICE`
  - `GPG_AGENT_INFO`
  - `GTK_MODULES`
  - `HOME`
  - `IM_CONFIG_PHASE`
  - `INVOCATION_ID`
  - `JOURNAL_STREAM`
  - `LANG`
  - `LANGUAGE`
  - `LC_ADDRESS`
  - `LC_IDENTIFICATION`
  - `LC_MEASUREMENT`
  - `LC_MONETARY`
  - `LC_NAME`
  - `LC_NUMERIC`
  - `LC_PAPER`
  - `LC_TELEPHONE`
  - `LC_TIME`
  - `LOGNAME`
  - `LS_COLORS`
  - `MANAGERPID`
  - `PAPERSIZE`
  - `PATH`
  - `PIPENV_VENV_IN_PROJECT`
  - `PWD`
  - `QT_ACCESSIBILITY`
  - `QT_IM_MODULE`
  - `SESSION_MANAGER`
  - `SHELL`
  - `SHLVL`
  - `SSH_AGENT_PID`
  - `SSH_AUTH_SOCK`
  - `TERM`
  - `USER`
  - `USERNAME`
  - `VTE_VERSION`
  - `WINDOWPATH`
  - `XAUTHORITY`
  - `XDG_CONFIG_DIRS`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_DATA_DIRS`
  - `XDG_MENU_PREFIX`
  - `XDG_RUNTIME_DIR`
  - `XDG_SESSION_CLASS`
  - `XDG_SESSION_DESKTOP`
  - `XDG_SESSION_TYPE`
  - `XMODIFIERS`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/david/.local/bin:/home/david/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/usr/bin/fish`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/david/Downloads/dpy`

---------------------------

Contents of `Pipfile` ('/home/david/Downloads/dpy/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
"dhis2.py" = "*"

[requires]
python_version = "3.8"

```

</details>

**Comment by davidhuser** [comment]
The problem is not pipenv -- it's `python_requires="!=2.*.*` in setup.py.

**Comment by jpl-jengelke** [comment]
This may have been closed prematurely. I see this error with the latest pipenv, virtualenv and pip installed in Python 3.7.3. 

Also, the FAQ literally says that `setup.py` is irrelevant: https://pipenv.pypa.io/en/latest/diagnose/#pipenv-does-not-respect-dependencies-in-setup-py .
