### ISSUE TITLE
/usr/bin/python3: No module named pipenv.pew

### ISSUE THREAD

**Issue by davidh38** [pypa/pipenv#4496]
### Issue description

Using /usr/bin/python3 (3.8.5) to create virtualenv…
⠋/usr/bin/python3: No module named pipenv.pew

Virtualenv location: 
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 641, in check
    core.do_check(
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 2241, in do_check
    ensure_project(three=three, python=python, validate=False, warn=False)
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 636, in ensure_project
    ensure_pipfile(validate=validate, skip_requirements=skip_requirements)
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 289, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/usr/lib/python3/dist-packages/pipenv/project.py", line 518, in create_pipfile
    'python_version': python_version(required_python)[: len('2.7')]
TypeError: 'NoneType' object is not subscriptable

### Expected result

That the programs does not throw an exception.

### Steps to replicate

Install on Ubuntu 20.04
sudo apt-get install pipenv
pipenv check
-------------------------------------------------------------------------------
pipenv --support | xclip
Error: no such option: --support

**Comment by Mause** [comment]
You are using a very outdated version of pipenv, please upgrade

**Comment by davidh38** [comment]
Thank you, this resolved my issue!
