### ISSUE TITLE
VersionConflict with importlib-metadata

### ISSUE THREAD

**Issue by whg517** [pypa/pipenv#4549]
### Issue description

I don't know why `importlib-metadata` dependency conflict recently occurred, but I installed the package in my new environment.

```
pkg_resources.VersionConflict: (importlib-metadata 3.1.0 (/home/kevin/.virtualenvs/python-guide-UQdmv-Su/lib/python3.7/site-packages), Requirement.parse('importlib-metadata<2,>=0.12; python_version < "3.8"'))
```

### Expected result

Pipenv Lock can be executed normally

### Actual result

```
(python-guide)  ✘ kevin@kevin  ~/workspaces/develop/doc/python-guide  pip list
Package    Version
---------- -------
packaging  20.7
pip        20.2.1
setuptools 49.2.1
wheel      0.34.2
(python-guide)  kevin@kevin  ~/workspaces/develop/doc/python-guide  pip --version
pip 20.2.1 from /home/kevin/.virtualenvs/python-guide-UQdmv-Su/lib/python3.7/site-packages/pip (python 3.7)
(python-guide)  kevin@kevin  ~/workspaces/develop/doc/python-guide  pipenv --version
pipenv, version 2020.11.15
(python-guide)  kevin@kevin  ~/workspaces/develop/doc/python-guide  pipenv install importlib-metadata --verbose
Installing importlib-metadata...
Installing package: importlib-metadata
Writing supplied requirement line to temporary file: 'importlib-metadata'
Installing 'importlib-metadata'
⠙ Installing importlib-metadata...$ ['/home/kevin/.virtualenvs/python-guide-UQdmv-Su/bin/pip', 'install', '--verbose', '--upgrade', '--exists-action=i', '-r', '/tmp/pipenv-lk4n0l4d-requirements/pipenv-z4guu5ff-requirement.txt', '-i', 'https://pypi.org/simple']
Using source directory: '/home/kevin/.virtualenvs/python-guide-UQdmv-Su/src'
Adding importlib-metadata to Pipfile's [packages]...
✔ Installation Succeeded 
Pipfile.lock (a65489) out of date, updating to (ac86d9)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
⠇ Locking...
                          ROUND 1                           
✘ Locking Failed! 
Current constraints:
  importlib-metadata (from -r /tmp/pipenvjcxsskfprequirements/pipenv-i3uz_75a-constraints.txt (line 2))

Finding the best candidates:
  found candidate importlib-metadata==3.1.0 (constraint was <any>)

Finding secondary dependencies:
  importlib-metadata==3.1.0 requires zipp>=0.5

New dependencies found in this round:
  adding ['zipp', '>=0.5', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  importlib-metadata (from -r /tmp/pipenvjcxsskfprequirements/pipenv-i3uz_75a-constraints.txt (line 2))
  zipp>=0.5 (from importlib-metadata==3.1.0->-r /tmp/pipenvjcxsskfprequirements/pipenv-i3uz_75a-constraints.txt (line 2))

Finding the best candidates:
  found candidate importlib-metadata==3.1.0 (constraint was <any>)
  found candidate zipp==3.4.0 (constraint was >=0.5)

Finding secondary dependencies:
  importlib-metadata==3.1.0 requires zipp>=0.5
  zipp==3.4.0               requires -
------------------------------------------------------------
Result of round 2: stable, done

Generating hashes:
  importlib-metadata
  zipp
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/pipenv/resolver.py", line 760, in main
    dev=parsed.dev)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/resolver.py", line 714, in resolve_packages
    results = clean_results(results, resolver, project, dev)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/resolver.py", line 590, in clean_results
    reverse_deps = project.environment.reverse_dependencies()
  File "/usr/local/lib/python3.7/dist-packages/pipenv/project.py", line 376, in environment
    self._environment = self.get_environment(allow_global=allow_global)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/project.py", line 366, in get_environment
    environment.extend_dists(pipenv_dist)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/environment.py", line 127, in extend_dists
    extras = self.resolve_dist(dist, self.base_working_set)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/environment.py", line 122, in resolve_dist
    deps |= cls.resolve_dist(dist, working_set)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/environment.py", line 121, in resolve_dist
    dist = working_set.find(req)
  File "/home/kevin/.virtualenvs/python-guide-UQdmv-Su/lib/python3.7/site-packages/pkg_resources/__init__.py", line 642, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (importlib-metadata 3.1.0 (/home/kevin/.virtualenvs/python-guide-UQdmv-Su/lib/python3.7/site-packages), Requirement.parse('importlib-metadata<2,>=0.12; python_version < "3.8"'))
ROUND 1                           
Current constraints:
  importlib-metadata (from -r /tmp/pipenvjcxsskfprequirements/pipenv-i3uz_75a-constraints.txt (line 2))

Finding the best candidates:
  found candidate importlib-metadata==3.1.0 (constraint was <any>)

Finding secondary dependencies:
  importlib-metadata==3.1.0 requires zipp>=0.5

New dependencies found in this round:
  adding ['zipp', '>=0.5', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  importlib-metadata (from -r /tmp/pipenvjcxsskfprequirements/pipenv-i3uz_75a-constraints.txt (line 2))
  zipp>=0.5 (from importlib-metadata==3.1.0->-r /tmp/pipenvjcxsskfprequirements/pipenv-i3uz_75a-constraints.txt (line 2))

Finding the best candidates:
  found candidate importlib-metadata==3.1.0 (constraint was <any>)
  found candidate zipp==3.4.0 (constraint was >=0.5)

Finding secondary dependencies:
  importlib-metadata==3.1.0 requires zipp>=0.5
  zipp==3.4.0               requires -
------------------------------------------------------------
Result of round 2: stable, done

Generating hashes:
  importlib-metadata
  zipp
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/pipenv/resolver.py", line 760, in main
    dev=parsed.dev)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/resolver.py", line 714, in resolve_packages
    results = clean_results(results, resolver, project, dev)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/resolver.py", line 590, in clean_results
    reverse_deps = project.environment.reverse_dependencies()
  File "/usr/local/lib/python3.7/dist-packages/pipenv/project.py", line 376, in environment
    self._environment = self.get_environment(allow_global=allow_global)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/project.py", line 366, in get_environment
    environment.extend_dists(pipenv_dist)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/environment.py", line 127, in extend_dists
    extras = self.resolve_dist(dist, self.base_working_set)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/environment.py", line 122, in resolve_dist
    deps |= cls.resolve_dist(dist, working_set)
  File "/usr/local/lib/python3.7/dist-packages/pipenv/environment.py", line 121, in resolve_dist
    dist = working_set.find(req)
  File "/home/kevin/.virtualenvs/python-guide-UQdmv-Su/lib/python3.7/site-packages/pkg_resources/__init__.py", line 642, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (importlib-metadata 3.1.0 (/home/kevin/.virtualenvs/python-guide-UQdmv-Su/lib/python3.7/site-packages), Requirement.parse('importlib-metadata<2,>=0.12; python_version < "3.8"'))
```

### Steps to replicate

**command**

```cmd
pipenv install importlib-metadata --verbose
```

**Pipfile**

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
importlib-metadata = "*"

[requires]
python_version = "3.7"

```
-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'/usr/local/lib/python3.7/dist-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.7.3`: `/home/kevin/.virtualenvs/python-guide-UQdmv-Su/bin/python3`
  - `3.7.3`: `/home/kevin/.virtualenvs/python-guide-UQdmv-Su/bin/python3.7`
  - `3.7.3`: `/home/kevin/.virtualenvs/python-guide-UQdmv-Su/bin/python3.7m`
  - `3.7.3`: `/home/kevin/.virtualenvs/python-guide-UQdmv-Su/bin/python3`
  - `3.7.3`: `/home/kevin/.virtualenvs/python-guide-UQdmv-Su/bin/python3.7`
  - `3.7.3`: `/home/kevin/.virtualenvs/python-guide-UQdmv-Su/bin/python3.7m`
  - `3.7.3`: `/usr/local/bin/python3.7m`
  - `3.7.3`: `/usr/local/bin/python3.7`
  - `3.7.3`: `/usr/bin/python3.7m`
  - `3.7.3`: `/usr/bin/python3`
  - `3.7.3`: `/usr/bin/python3.7`
  - `3.7.3`: `/bin/python3.7m`
  - `3.7.3`: `/bin/python3`
  - `3.7.3`: `/bin/python3.7`
  - `3.6.8`: `/usr/local/bin/python3.6m`
  - `3.6.8`: `/usr/local/bin/python3.6`
  - `3.6.8`: `/usr/bin/python3.6`
  - `3.6.8`: `/bin/python3.6`
  - `3.5.3`: `/usr/bin/python3.5`
  - `3.5.3`: `/usr/bin/python3.5m`
  - `3.5.3`: `/bin/python3.5`
  - `3.5.3`: `/bin/python3.5m`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`
  - `2.7.16`: `/bin/python2`
  - `2.7.16`: `/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.3',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.70-amd64-desktop',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Wed Oct 14 15:24:23 CST 2020',
 'python_full_version': '3.7.3',
 'python_version': '3.7',
 'sys_platform': 'linux'}
```

System environment variables:

  - `USER`
  - `LANGUAGE`
  - `WORKON_HOME`
  - `XDG_SEAT`
  - `SBT_HOME`
  - `POSTGRESQL_HOME`
  - `XDG_SESSION_TYPE`
  - `XDG_CACHE_HOME`
  - `LD_LIBRARY_PATH`
  - `HOME`
  - `VIRTUALENVWRAPPER_PYTHON`
  - `QT4_IM_MODULE`
  - `DESKTOP_SESSION`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `XDG_SEAT_PATH`
  - `GRADLE_HOME`
  - `SCALA_HOME`
  - `CATALINA_HOME`
  - `QT_LINUX_ACCESSIBILITY_ALWAYS_ON`
  - `QT_DBL_CLICK_DIST`
  - `HADOOP_COMMON_LIB_NATIVE_DIR`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `LOGNAME`
  - `GTK_IM_MODULE`
  - `XDG_SESSION_CLASS`
  - `XDG_SESSION_ID`
  - `GNOME_DESKTOP_SESSION_ID`
  - `PATH`
  - `XDG_SESSION_PATH`
  - `XDG_RUNTIME_DIR`
  - `DISPLAY`
  - `CMAKE_HOME`
  - `LANG`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_SESSION_DESKTOP`
  - `XAUTHORITY`
  - `XDG_DATA_HOME`
  - `XDG_CONFIG_HOME`
  - `XMODIFIERS`
  - `XDG_GREETER_DATA_DIR`
  - `SSH_AUTH_SOCK`
  - `SHELL`
  - `NODE_PATH`
  - `GDMSESSION`
  - `QT_ACCESSIBILITY`
  - `QT_LOGGING_RULES`
  - `CLASSPATH`
  - `GPG_AGENT_INFO`
  - `XDG_VTNR`
  - `QT_IM_MODULE`
  - `PWD`
  - `JAVA_HOME`
  - `GRADLE_USER_HOME`
  - `XDG_DATA_DIRS`
  - `CLUTTER_IM_MODULE`
  - `M2_HOME`
  - `HADOOP_HOME`
  - `CHROME_DESKTOP`
  - `ORIGINAL_XDG_CURRENT_DESKTOP`
  - `VIRTUALENVWRAPPER_WORKON_CD`
  - `XCURSOR_SIZE`
  - `SHLVL`
  - `OLDPWD`
  - `LESS`
  - `D_DISABLE_RT_SCREEN_SCALE`
  - `ZSH`
  - `LSCOLORS`
  - `PAGER`
  - `COLORTERM`
  - `WINDOWID`
  - `_`
  - `COLORFGBG`
  - `TERM`
  - `QT_SCALE_FACTOR_ROUNDING_POLICY`
  - `VIRTUALENVWRAPPER_PROJECT_FILENAME`
  - `VIRTUALENVWRAPPER_HOOK_DIR`
  - `VIRTUALENVWRAPPER_SCRIPT`
  - `APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL`
  - `NO_AT_BRIDGE`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `VSCODE_GIT_IPC_HANDLE`
  - `GIT_ASKPASS`
  - `VSCODE_GIT_ASKPASS_NODE`
  - `VSCODE_GIT_ASKPASS_MAIN`
  - `LS_COLORS`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PIPENV_ACTIVE`
  - `VIRTUAL_ENV`
  - `PS1`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/home/kevin/.virtualenvs/python-guide-UQdmv-Su/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/snap/bin:/opt/softwares/jdk1.8.0_141/bin:/opt/softwares/maven-3.6.1/bin:/opt/softwares/gradle-5.4.1/bin:/opt/softwares/sbt/bin:/opt/softwares/scala/bin:/opt/softwares/node-v12.3.1/bin:/data/repository/nodejs/node_global/bin:/opt/softwares/tomcat-9.0.30/bin:/usr/hdp/3.1.0.0-78/hadoop/bin:/usr/hdp/3.1.0.0-78/hadoop/sbin:/usr/local/pgsql/bin/:/opt/softwares/cmake/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `LANG`: `zh_CN.UTF-8`
  - `PWD`: `/home/kevin/workspaces/develop/doc/python-guide`
  - `VIRTUAL_ENV`: `/home/kevin/.virtualenvs/python-guide-UQdmv-Su`

---------------------------

Contents of `Pipfile` ('/home/kevin/workspaces/develop/doc/python-guide/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
importlib-metadata = "*"

[requires]
python_version = "3.7"

```

Contents of `Pipfile.lock` ('/home/kevin/workspaces/develop/doc/python-guide/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "7e7ef69da7248742e869378f8421880cf8f0017f96d94d086813baa518a65489"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>

---

I'm sorry to interrupt your normal work. I would appreciate it if you could help me.

**Comment by J-M0** [comment]
I'm having this issue too and can confirm it happens with only `importlib-metadata` in the `Pipfile`.

<details><summary>pipenv install -v importlib-metadata</summary>

```
Using python: 3.6
Path to python: /usr/bin/python3.6m
Creating a virtualenv for this project...
Pipfile: /home/kususer/Documents/pl/Pipfile
Using /usr/bin/python3.6m (3.6.8) to create virtualenv...
created virtual environment CPython3.6.8.final.0-64 in 197ms
  creator CPython3Posix(dest=/home/kususer/.local/share/virtualenvs/pl-E9dLybHL, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/kususer/.local/share/virtualenv)
    added seed packages: pip==20.3.3, setuptools==51.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment!
Virtualenv location: /home/kususer/.local/share/virtualenvs/pl-E9dLybHL
Installing importlib-metadata...
Installing package: importlib-metadata
Writing supplied requirement line to temporary file: 'importlib-metadata'
Installing 'importlib-metadata'
$ ['/home/kususer/.local/share/virtualenvs/pl-E9dLybHL/bin/pip', 'install', '--verbose', '--upgrade', '--exists-action=i', '-r', '/tmp/pipenv-bmtsiouc-requirements/pipenv-wft51l29-requirement.txt', '-i', 'https://pypi.org/simple']
Using source directory: '/home/kususer/.local/share/virtualenvs/pl-E9dLybHL/src'
Adding importlib-metadata to Pipfile's [packages]...
✔ Installation Succeeded
Pipfile.lock (ca72e7) out of date, updating to (640804)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...

FAIL
                          ROUND 1                           
Current constraints:
  importlib-metadata (from -r /tmp/pipenvy9j0bwonrequirements/pipenv-zf3gehs3-constraints.txt (line 2))

Finding the best candidates:
  found candidate importlib-metadata==3.4.0 (constraint was <any>)

Finding secondary dependencies:
  importlib-metadata==3.4.0 requires typing-extensions>=3.6.4; python_version < "3.8", zipp>=0.5

New dependencies found in this round:
  adding ['typing-extensions', '>=3.6.4', '[]']
  adding ['zipp', '>=0.5', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  importlib-metadata (from -r /tmp/pipenvy9j0bwonrequirements/pipenv-zf3gehs3-constraints.txt (line 2))
  typing-extensions>=3.6.4 (from importlib-metadata==3.4.0->-r /tmp/pipenvy9j0bwonrequirements/pipenv-zf3gehs3-constraints.txt (line 2))
  zipp>=0.5 (from importlib-metadata==3.4.0->-r /tmp/pipenvy9j0bwonrequirements/pipenv-zf3gehs3-constraints.txt (line 2))

Finding the best candidates:
  found candidate importlib-metadata==3.4.0 (constraint was <any>)
  found candidate typing-extensions==3.7.4.3 (constraint was >=3.6.4)
  found candidate zipp==3.4.0 (constraint was >=0.5)

Finding secondary dependencies:
  zipp==3.4.0               requires -
  importlib-metadata==3.4.0 requires typing-extensions>=3.6.4; python_version < "3.8", zipp>=0.5
  typing-extensions==3.7.4.3 requires -
------------------------------------------------------------
Result of round 2: stable, done

Generating hashes:
  zipp
  importlib-metadata
  typing-extensions
Traceback (most recent call last):
  File "/home/kususer/.local/pipx/venvs/pipenv/lib64/python3.6/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/home/kususer/.local/pipx/venvs/pipenv/lib64/python3.6/site-packages/pipenv/resolver.py", line 760, in main
    dev=parsed.dev)
  File "/home/kususer/.local/pipx/venvs/pipenv/lib64/python3.6/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/home/kususer/.local/pipx/venvs/pipenv/lib64/python3.6/site-packages/pipenv/resolver.py", line 714, in resolve_packages
    results = clean_results(results, resolver, project, dev)
  File "/home/kususer/.local/pipx/venvs/pipenv/lib64/python3.6/site-packages/pipenv/resolver.py", line 590, in clean_results
    reverse_deps = project.environment.reverse_dependencies()
  File "/home/kususer/.local/pipx/venvs/pipenv/lib/python3.6/site-packages/pipenv/project.py", line 376, in environment
    self._environment = self.get_environment(allow_global=allow_global)
  File "/home/kususer/.local/pipx/venvs/pipenv/lib/python3.6/site-packages/pipenv/project.py", line 366, in get_environment
    environment.extend_dists(pipenv_dist)
  File "/home/kususer/.local/pipx/venvs/pipenv/lib/python3.6/site-packages/pipenv/environment.py", line 127, in extend_dists
    extras = self.resolve_dist(dist, self.base_working_set)
  File "/home/kususer/.local/pipx/venvs/pipenv/lib/python3.6/site-packages/pipenv/environment.py", line 122, in resolve_dist
    deps |= cls.resolve_dist(dist, working_set)
  File "/home/kususer/.local/pipx/venvs/pipenv/lib/python3.6/site-packages/pipenv/environment.py", line 121, in resolve_dist
    dist = working_set.find(req)
  File "/home/kususer/.local/share/virtualenvs/pl-E9dLybHL/lib/python3.6/site-packages/pkg_resources/__init__.py", line 627, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (importlib-metadata 3.4.0 (/home/kususer/.local/share/virtualenvs/pl-E9dLybHL/lib/python3.6/site-packages), Requirement.parse('importlib-metadata<3,>=0.12; python_version < "3.8"'))
ROUND 1                           
Current constraints:
  importlib-metadata (from -r /tmp/pipenvy9j0bwonrequirements/pipenv-zf3gehs3-constraints.txt (line 2))

Finding the best candidates:
  found candidate importlib-metadata==3.4.0 (constraint was <any>)

Finding secondary dependencies:
  importlib-metadata==3.4.0 requires typing-extensions>=3.6.4; python_version < "3.8", zipp>=0.5

New dependencies found in this round:
  adding ['typing-extensions', '>=3.6.4', '[]']
  adding ['zipp', '>=0.5', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  importlib-metadata (from -r /tmp/pipenvy9j0bwonrequirements/pipenv-zf3gehs3-constraints.txt (line 2))
  typing-extensions>=3.6.4 (from importlib-metadata==3.4.0->-r /tmp/pipenvy9j0bwonrequirements/pipenv-zf3gehs3-constraints.txt (line 2))
  zipp>=0.5 (from importlib-metadata==3.4.0->-r /tmp/pipenvy9j0bwonrequirements/pipenv-zf3gehs3-constraints.txt (line 2))

Finding the best candidates:
  found candidate importlib-metadata==3.4.0 (constraint was <any>)
  found candidate typing-extensions==3.7.4.3 (constraint was >=3.6.4)
  found candidate zipp==3.4.0 (constraint was >=0.5)

Finding secondary dependencies:
  zipp==3.4.0               requires -
  importlib-metadata==3.4.0 requires typing-extensions>=3.6.4; python_version < "3.8", zipp>=0.5
  typing-extensions==3.7.4.3 requires -
------------------------------------------------------------
Result of round 2: stable, done

Generating hashes:
  zipp
  importlib-metadata
  typing-extensions
Traceback (most recent call last):
  File "/home/kususer/.local/pipx/venvs/pipenv/lib64/python3.6/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/home/kususer/.local/pipx/venvs/pipenv/lib64/python3.6/site-packages/pipenv/resolver.py", line 760, in main
    dev=parsed.dev)
  File "/home/kususer/.local/pipx/venvs/pipenv/lib64/python3.6/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/home/kususer/.local/pipx/venvs/pipenv/lib64/python3.6/site-packages/pipenv/resolver.py", line 714, in resolve_packages
    results = clean_results(results, resolver, project, dev)
  File "/home/kususer/.local/pipx/venvs/pipenv/lib64/python3.6/site-packages/pipenv/resolver.py", line 590, in clean_results
    reverse_deps = project.environment.reverse_dependencies()
  File "/home/kususer/.local/pipx/venvs/pipenv/lib/python3.6/site-packages/pipenv/project.py", line 376, in environment
    self._environment = self.get_environment(allow_global=allow_global)
  File "/home/kususer/.local/pipx/venvs/pipenv/lib/python3.6/site-packages/pipenv/project.py", line 366, in get_environment
    environment.extend_dists(pipenv_dist)
  File "/home/kususer/.local/pipx/venvs/pipenv/lib/python3.6/site-packages/pipenv/environment.py", line 127, in extend_dists
    extras = self.resolve_dist(dist, self.base_working_set)
  File "/home/kususer/.local/pipx/venvs/pipenv/lib/python3.6/site-packages/pipenv/environment.py", line 122, in resolve_dist
    deps |= cls.resolve_dist(dist, working_set)
  File "/home/kususer/.local/pipx/venvs/pipenv/lib/python3.6/site-packages/pipenv/environment.py", line 121, in resolve_dist
    dist = working_set.find(req)
  File "/home/kususer/.local/share/virtualenvs/pl-E9dLybHL/lib/python3.6/site-packages/pkg_resources/__init__.py", line 627, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (importlib-metadata 3.4.0 (/home/kususer/.local/share/virtualenvs/pl-E9dLybHL/lib/python3.6/site-packages), Requirement.parse('importlib-metadata<3,>=0.12; python_version < "3.8"'))
Traceback (most recent call last):
  File "/home/kususer/.local/pipx/venvs/pipenv/lib64/python3.6/site-packages/pipenv/utils.py", line 1131, in create_spinner
    yield sp
  File "/home/kususer/.local/pipx/venvs/pipenv/lib64/python3.6/site-packages/pipenv/utils.py", line 1338, in venv_resolve_deps
    c = resolve(cmd, sp)
  File "/home/kususer/.local/pipx/venvs/pipenv/lib64/python3.6/site-packages/pipenv/utils.py", line 1176, in resolve
    sys.exit(c.return_code)
SystemExit: 1
```

</details>
