### ISSUE TITLE
All commands failing - Python versioning issue?

### ISSUE THREAD

**Issue by james-a-roland** [pypa/pipenv#4580]
### Issue description
All `pipenv` commands are failing after a fresh install (version 2020.11.15 - more output below). 

### Expected result

`pipenv` commands should succeed.

### Actual result

Any `pipenv` command (even --support) will fail. 

Expected failure reason is that an incorrect version of Python is being used. 
The error (shown below) points to a `namedtuple` issue shown below, where the `defaults` param was [added in Python version 3.7](https://stackoverflow.com/questions/11351032/named-tuple-and-default-values-for-optional-keyword-arguments). The `pipenv` source code [explicitly checks for version 3.7](https://github.com/pypa/pipenv/blob/master/pipenv/exceptions.py#L24) or above, so I'm quite confused as how this is happening.

### Steps to replicate

```
➜  lead-manager-react-django python -V
Python 2.7.16
➜  lead-manager-react-django pip --version
pip 19.0.3 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip-19.0.3-py3.7.egg/pip (python 3.7)

> ➜  lead-manager-react-django pip install pipenv
Collecting pipenv
  Using cached https://files.pythonhosted.org/packages/df/c5/2ebf6fcab61826a6e886531d67bb9776b4027c3094fbf2fbbaa2c9075d92/pipenv-2020.11.15-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=36.2.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pipenv) (51.1.1)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pipenv) (2019.11.28)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pipenv) (0.5.4)
Requirement already satisfied: virtualenv in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pipenv) (20.2.2)
Requirement already satisfied: pip>=18.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip-19.0.3-py3.7.egg (from pipenv) (19.0.3)
Requirement already satisfied: six<2,>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from virtualenv->pipenv) (1.15.0)
Requirement already satisfied: filelock<4,>=3.0.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from virtualenv->pipenv) (3.0.12)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from virtualenv->pipenv) (3.3.0)
Requirement already satisfied: distlib<1,>=0.3.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from virtualenv->pipenv) (0.3.1)
Requirement already satisfied: appdirs<2,>=1.4.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from virtualenv->pipenv) (1.4.4)
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->virtualenv->pipenv) (3.7.4.3)
Requirement already satisfied: zipp>=0.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from importlib-metadata>=0.12; python_version < "3.8"->virtualenv->pipenv) (3.4.0)
Installing collected packages: pipenv
Successfully installed pipenv-2020.11.15
➜  lead-manager-react-django pipenv
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/pipenv", line 6, in <module>
    from pipenv import cli
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/__init__.py", line 55, in <module>
    from .cli import cli
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/cli/__init__.py", line 4, in <module>
    from .command import cli    # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/cli/command.py", line 13, in <module>
    from ..exceptions import PipenvOptionsError
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pipenv/exceptions.py", line 27, in <module>
    defaults=[None, None, None, ""]
TypeError: namedtuple() got an unexpected keyword argument 'defaults'
```

**Comment by matteius** [comment]
Hey @james-a-roland -- your python in the output is not supported Python 2.7.16 -- you need 3.7.x for namedtuple to accept 'defualts'.   I think you also have python3.7 but are getting resolution to python2 dependencies.  I am closing this for now, in an effort to get through the backlog of issues and understand what is facing the latest versions of pipenv `2021.11.23`.  Please write back if you think there is still an error requiring investigation.
