### ISSUE TITLE
Cannot Run Scripts

### ISSUE THREAD

**Issue by jfavrod** [pypa/pipenv#4609]
### Issue description
Cannot run pipenv `[scripts]`

Here's my Pipfile:

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[scripts]
start = 'python src/main.py'

[packages]
rootpath = "*"

[dev-packages]

[requires]
python_version = "3.8"
```

### Expected result
When I run `pipenv run python src/main.py` I get the expected output, which is simply printing the file path to the project.
But below is what I get when I run `pipenv run start`

### Actual result
```
Traceback (most recent call last):
  File "/usr/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 602, in run
    core.do_run(command=command, args=args, three=three, python=python)
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 2200, in do_run
    command = ' '.join(project.scripts[command])
  File "/usr/lib/python3/dist-packages/pipenv/project.py", line 374, in scripts
    scripts[k] = shlex.split(v, posix=True)
  File "/usr/lib/python3.8/shlex.py", line 311, in split
    return list(lex)
  File "/usr/lib/python3.8/shlex.py", line 300, in __next__
    token = self.get_token()
  File "/usr/lib/python3.8/shlex.py", line 109, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.8/shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'list' object has no attribute 'read'
```

I'm not sure what I can do to troubleshoot. I made sure my Pipenv was up to date.

### Steps to replicate

1. In a Pipenv project, make a sub-directory for python code name `src/`.
2. Add a `main.py` to the code directory that prints a message
```
def main():
    print('hello world')


if __name__ == '__main__':
    main()
```
3. Add a `[scripts]` section to the Pipenv file that executes the `main.py` file.
4. Try to execute the script.

-------------------------------------------------------------------------------

On Linux:
    $ pipenv --support | xclip
```
Error: no such option: --support
```

**Comment by frostming** [comment]
What is the content of your Pipfile?

**Comment by jfavrod** [comment]
> What is the content of your Pipfile?

I posted the Pipfile in the issue.

**Comment by frostming** [comment]
You don't seem on the latest Pipenv, please try upgrading first

**Comment by jfavrod** [comment]
I thought I was up to date.
```
$ sudo apt install pipenv
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pipenv is already the newest version (11.9.0-1).
0 upgraded, 0 newly installed, 0 to remove and 48 not upgraded.
```

But then I did updated with `pip3`
```
pip3 install pipenv --upgrade
```

It works now. Thanks for your help!
