### ISSUE TITLE
Requested module (antlib) has inconsistent version 

### ISSUE THREAD

**Issue by goldwake** [pypa/pipenv#4618]
### Issue description

I'm running 32 bit Python 3.7.5 on a windows 10 machine. Using pipenv 2020.11.15 I am unable to install [antlib](https://pypi.org/project/antlib/). I can install it when using just pip. 

I am running the command
`pipenv install antlib --pre`

### Expected result

I would expect the latest pre release version to be installed 1.1b0

### Actual result
it fails with the message (edited for brevity)

`Requested antlib==1.1b0.post0 has inconsistent version: filename has '1.1b0.post0', but metadata has '1.1b0'
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement antlib==1.1b0.post0
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for antlib==1.1b0.post0`

full debug log below

```
C:\my_path\Source\test2>pipenv install antlib --pre --verbose
Using python: None
Path to python: C:/Users/my_name/AppData/Local/Programs/Python/Python37-32/python.exe
Creating a virtualenv for this project...
Pipfile: C:\my_path\Source\test2\Pipfile
Using C:/Users/my_name/AppData/Local/Programs/Python/Python37-32/python.exe (3.7.5) to create virtualenv...
[ ===] Creating virtual environment...Already using interpreter C:\Users\my_name\AppData\Local\Programs\Python\Python37-32\python.exe
Using base prefix 'C:\\Users\\my_name\\AppData\\Local\\Programs\\Python\\Python37-32'
New python executable in C:\Users\my_name\.virtualenvs\test2-7vSUOgkV\Scripts\python.exe
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter C:/Users/my_name/AppData/Local/Programs/Python/Python37-32/python.exe

Successfully created virtual environment!
Virtualenv location: C:\Users\my_name\.virtualenvs\test2-7vSUOgkV
Creating a Pipfile for this project...
Installing antlib...
 Installing...Installing package: antlib
Writing supplied requirement line to temporary file: 'antlib'
Installing 'antlib'
[=   ] Installing antlib...$ ['C:\\Users\\my_name\\.virtualenvs\\test2-7vSUOgkV\\Scripts\\pip.exe', 'install', '--pre', '--verbose', '--upgrade', '--exists-action=i', '-r', 'c:\\users\\my_name\\appdata\\local\\temp\\pipenv-6dr_1bk0-requirements\\pipenv-4aja_qd_-requirement.txt', '-i', 'https://pypi.org/simple']
Using source directory: 'C:\\Users\\my_name\\.virtualenvs\\test2-7vSUOgkV\\src'
Adding antlib to Pipfile's [packages]...
Installation Succeeded
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
           Building requirements...
Resolving dependencies...
[====] Locking...
                          ROUND 1
Current constraints:
  antlib (from -r C:\Users\my_name\AppData\Local\Temp\pipenv_s9e5370requirements\pipenv-jk2d759a-constraints.txt (line 2))

Finding the best candidates:
[=== ] Locking...  found candidate antlib==1.1b0.post0 (constraint was <any>)

Finding secondary dependencies:
  antlib==1.1b0.post0       requires -
------------------------------------------------------------
Result of round 1: stable, done

Generating hashes:
  antlib
Warning: Error generating hash for antlib
ROUND 1
Current constraints:
  antlib (from -r C:\Users\my_name\AppData\Local\Temp\pipenv_s9e5370requirements\pipenv-jk2d759a-constraints.txt (line 2))

Finding the best candidates:
  found candidate antlib==1.1b0.post0 (constraint was <any>)

Finding secondary dependencies:
  antlib==1.1b0.post0       requires -
------------------------------------------------------------
Result of round 1: stable, done

Generating hashes:
  antlib
Warning: Error generating hash for antlib
Success!
Warning: ROUND 1
Current constraints:
  antlib (from -r C:\Users\my_name\AppData\Local\Temp\pipenv_s9e5370requirements\pipenv-jk2d759a-constraints.txt (line 2))

Finding the best candidates:
  found candidate antlib==1.1b0.post0 (constraint was <any>)

Finding secondary dependencies:
  antlib==1.1b0.post0       requires -
------------------------------------------------------------
Result of round 1: stable, done

Generating hashes:
  antlib
Warning: Error generating hash for antlib
Updated Pipfile.lock (3940fa)!
Installing dependencies from Pipfile.lock (3940fa)...
Writing supplied requirement line to temporary file: 'antlib==1.1b0.post0 --hash=sha256:aebfcbdff0770653d3959061f176299eec3b8d7f77f151d3c46d7d0ea06fb64b'
Installing 'antlib'
$ ['C:\\Users\\my_name\\.virtualenvs\\test2-7vSUOgkV\\Scripts\\pip.exe', 'install', '--verbose', '--upgrade', '--require-hashes', '--no-deps', '--exists-action=i', '-r', 'c:\\users\\my_name\\appdata\\local\\temp\\pipenv-6dr_1bk0-requirements\\pipenv-l24jzb3_-requirement.txt', '-i', 'https://pypi.org/simple']
Using source directory: 'C:\\Users\\my_name\\.virtualenvs\\test2-7vSUOgkV\\src'
Using pip 21.0.1 from c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip (python 3.7)
Non-user install by explicit request
Created temporary directory: C:\Users\my_name\AppData\Local\Temp\pip-ephem-wheel-cache-ucj_0siy
Created temporary directory: C:\Users\my_name\AppData\Local\Temp\pip-req-tracker-12aoghk_
Initialized build tracking at C:\Users\my_name\AppData\Local\Temp\pip-req-tracker-12aoghk_
Created build tracker: C:\Users\my_name\AppData\Local\Temp\pip-req-tracker-12aoghk_
Entered build tracker: C:\Users\my_name\AppData\Local\Temp\pip-req-tracker-12aoghk_
Created temporary directory: C:\Users\my_name\AppData\Local\Temp\pip-install-2lsw23kz
1 location(s) to search for versions of antlib:
* https://pypi.org/simple/antlib/
Fetching project page and analyzing links: https://pypi.org/simple/antlib/
Getting page https://pypi.org/simple/antlib/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/antlib/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/antlib/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/39/12/d7a3550ad1f218440b5f087e9804c14951d4a3cec1927f9dc7931fe88334/antlib-1.0b0-py2.py3-none-win32.whl#sha256=b52beb72546ed763a900e5d4b2c3db6f28eca45f288a1ce1566023ee0ee91cef (from https://pypi.org/simple/antlib/), version: 1.0b0
  Found link https://files.pythonhosted.org/packages/b1/99/641f7f134b136fe33933012decf6694500f92adc118bb4bf83be04b36b48/antlib-1.1b0.post0-py2.py3-none-any.whl#sha256=aebfcbdff0770653d3959061f176299eec3b8d7f77f151d3c46d7d0ea06fb64b (from https://pypi.org/simple/antlib/), version: 1.1b0.post0
Checked 1 links for project 'antlib' against 1 hashes (1 matches, 0 no digest): discarding no candidates
Collecting antlib==1.1b0.post0
  Created temporary directory: C:\Users\my_name\AppData\Local\Temp\pip-unpack-4l6jiw46
  Looking up "https://files.pythonhosted.org/packages/b1/99/641f7f134b136fe33933012decf6694500f92adc118bb4bf83be04b36b48/antlib-1.1b0.post0-py2.py3-none-any.whl" in the cache
  Current age based on date: 9163959
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 9163959
  Using cached antlib-1.1b0.post0-py2.py3-none-any.whl (283 kB)
  Added antlib==1.1b0.post0 from https://files.pythonhosted.org/packages/b1/99/641f7f134b136fe33933012decf6694500f92adc118bb4bf83be04b36b48/antlib-1.1b0.post0-py2.py3-none-any.whl#sha256=aebfcbdff0770653d3959061f176299eec3b8d7f77f151d3c46d7d0ea06fb64b (from -r c:\users\my_name\appdata\local\temp\pipenv-6dr_1bk0-requirements\pipenv-l24jzb3_-requirement.txt (line 1)) to build tracker 'C:\\Users\\my_name\\AppData\\Local\\Temp\\pip-req-tracker-12aoghk_'
  Removed antlib==1.1b0.post0 from https://files.pythonhosted.org/packages/b1/99/641f7f134b136fe33933012decf6694500f92adc118bb4bf83be04b36b48/antlib-1.1b0.post0-py2.py3-none-any.whl#sha256=aebfcbdff0770653d3959061f176299eec3b8d7f77f151d3c46d7d0ea06fb64b (from -r c:\users\my_name\appdata\local\temp\pipenv-6dr_1bk0-requirements\pipenv-l24jzb3_-requirement.txt (line 1)) from build tracker 'C:\\Users\\my_name\\AppData\\Local\\Temp\\pip-req-tracker-12aoghk_'
WARNING: Discarding https://files.pythonhosted.org/packages/b1/99/641f7f134b136fe33933012decf6694500f92adc118bb4bf83be04b36b48/antlib-1.1b0.post0-py2.py3-none-any.whl#sha256=aebfcbdff0770653d3959061f176299eec3b8d7f77f151d3c46d7d0ea06fb64b (from https://pypi.org/simple/antlib/). Requested antlib==1.1b0.post0 from https://files.pythonhosted.org/packages/b1/99/641f7f134b136fe33933012decf6694500f92adc118bb4bf83be04b36b48/antlib-1.1b0.post0-py2.py3-none-any.whl#sha256=aebfcbdff0770653d3959061f176299eec3b8d7f77f151d3c46d7d0ea06fb64b (from -r c:\users\my_name\appdata\local\temp\pipenv-6dr_1bk0-requirements\pipenv-l24jzb3_-requirement.txt (line 1)) has inconsistent version: filename has '1.1b0.post0', but metadata has '1.1b0'
ERROR: Could not find a version that satisfies the requirement antlib==1.1b0.post0
ERROR: No matching distribution found for antlib==1.1b0.post0
Exception information:
Traceback (most recent call last):
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'antlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 83, in from_requirement
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('antlib==1.1b0.post0')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 320, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('antlib==1.1b0.post0'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_internal\cli\base_command.py", line 189, in _main
    status = self.run(options, args)
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_internal\cli\req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_internal\commands\install.py", line 317, in run
    reqs, check_supported_wheels=not options.target_dir
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 127, in resolve
    six.raise_from(error, e)
  File "<string>", line 3, in raise_from
pip._internal.exceptions.DistributionNotFound: No matching distribution found for antlib==1.1b0.post0
Removed build tracker: 'C:\\Users\\my_name\\AppData\\Local\\Temp\\pip-req-tracker-12aoghk_'
An error occurred while installing antlib==1.1b0.post0 --hash=sha256:aebfcbdff0770653d3959061f176299eec3b8d7f77f151d3c46d7d0ea06fb64b! Will try again.
  ================================ 1/1 - 00:00:01
Installing initially failed dependencies...
Writing supplied requirement line to temporary file: 'antlib==1.1b0.post0 --hash=sha256:aebfcbdff0770653d3959061f176299eec3b8d7f77f151d3c46d7d0ea06fb64b'
Installing 'antlib'
$ ['C:\\Users\\my_name\\.virtualenvs\\test2-7vSUOgkV\\Scripts\\pip.exe', 'install', '--verbose', '--upgrade', '--require-hashes', '--no-use-pep517', '--no-deps', '--exists-action=i', '-r', 'c:\\users\\my_name\\appdata\\local\\temp\\pipenv-6dr_1bk0-requirements\\pipenv-hi8kbekm-requirement.txt', '-i', 'https://pypi.org/simple']
Using source directory: 'C:\\Users\\my_name\\.virtualenvs\\test2-7vSUOgkV\\src'
Using pip 21.0.1 from c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip (python 3.7)
Non-user install by explicit request
Created temporary directory: C:\Users\my_name\AppData\Local\Temp\pip-ephem-wheel-cache-jtf8qss0
Created temporary directory: C:\Users\my_name\AppData\Local\Temp\pip-req-tracker-dfg00vok
Initialized build tracking at C:\Users\my_name\AppData\Local\Temp\pip-req-tracker-dfg00vok
Created build tracker: C:\Users\my_name\AppData\Local\Temp\pip-req-tracker-dfg00vok
Entered build tracker: C:\Users\my_name\AppData\Local\Temp\pip-req-tracker-dfg00vok
Created temporary directory: C:\Users\my_name\AppData\Local\Temp\pip-install-rprgjsag
1 location(s) to search for versions of antlib:
* https://pypi.org/simple/antlib/
Fetching project page and analyzing links: https://pypi.org/simple/antlib/
Getting page https://pypi.org/simple/antlib/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/antlib/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/antlib/ HTTP/1.1" 304 0
  Found link https://files.pythonhosted.org/packages/39/12/d7a3550ad1f218440b5f087e9804c14951d4a3cec1927f9dc7931fe88334/antlib-1.0b0-py2.py3-none-win32.whl#sha256=b52beb72546ed763a900e5d4b2c3db6f28eca45f288a1ce1566023ee0ee91cef (from https://pypi.org/simple/antlib/), version: 1.0b0
  Found link https://files.pythonhosted.org/packages/b1/99/641f7f134b136fe33933012decf6694500f92adc118bb4bf83be04b36b48/antlib-1.1b0.post0-py2.py3-none-any.whl#sha256=aebfcbdff0770653d3959061f176299eec3b8d7f77f151d3c46d7d0ea06fb64b (from https://pypi.org/simple/antlib/), version: 1.1b0.post0
Checked 1 links for project 'antlib' against 1 hashes (1 matches, 0 no digest): discarding no candidates
Collecting antlib==1.1b0.post0
  Created temporary directory: C:\Users\my_name\AppData\Local\Temp\pip-unpack-g2dg1i8_
  Looking up "https://files.pythonhosted.org/packages/b1/99/641f7f134b136fe33933012decf6694500f92adc118bb4bf83be04b36b48/antlib-1.1b0.post0-py2.py3-none-any.whl" in the cache
  Current age based on date: 9163960
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 9163960
  Using cached antlib-1.1b0.post0-py2.py3-none-any.whl (283 kB)
  Added antlib==1.1b0.post0 from https://files.pythonhosted.org/packages/b1/99/641f7f134b136fe33933012decf6694500f92adc118bb4bf83be04b36b48/antlib-1.1b0.post0-py2.py3-none-any.whl#sha256=aebfcbdff0770653d3959061f176299eec3b8d7f77f151d3c46d7d0ea06fb64b (from -r c:\users\my_name\appdata\local\temp\pipenv-6dr_1bk0-requirements\pipenv-hi8kbekm-requirement.txt (line 1)) to build tracker 'C:\\Users\\my_name\\AppData\\Local\\Temp\\pip-req-tracker-dfg00vok'
  Removed antlib==1.1b0.post0 from https://files.pythonhosted.org/packages/b1/99/641f7f134b136fe33933012decf6694500f92adc118bb4bf83be04b36b48/antlib-1.1b0.post0-py2.py3-none-any.whl#sha256=aebfcbdff0770653d3959061f176299eec3b8d7f77f151d3c46d7d0ea06fb64b (from -r c:\users\my_name\appdata\local\temp\pipenv-6dr_1bk0-requirements\pipenv-hi8kbekm-requirement.txt (line 1)) from build tracker 'C:\\Users\\my_name\\AppData\\Local\\Temp\\pip-req-tracker-dfg00vok'
WARNING: Discarding https://files.pythonhosted.org/packages/b1/99/641f7f134b136fe33933012decf6694500f92adc118bb4bf83be04b36b48/antlib-1.1b0.post0-py2.py3-none-any.whl#sha256=aebfcbdff0770653d3959061f176299eec3b8d7f77f151d3c46d7d0ea06fb64b (from https://pypi.org/simple/antlib/). Requested antlib==1.1b0.post0 from https://files.pythonhosted.org/packages/b1/99/641f7f134b136fe33933012decf6694500f92adc118bb4bf83be04b36b48/antlib-1.1b0.post0-py2.py3-none-any.whl#sha256=aebfcbdff0770653d3959061f176299eec3b8d7f77f151d3c46d7d0ea06fb64b (from -r c:\users\my_name\appdata\local\temp\pipenv-6dr_1bk0-requirements\pipenv-hi8kbekm-requirement.txt (line 1)) has inconsistent version: filename has '1.1b0.post0', but metadata has '1.1b0'
ERROR: Could not find a version that satisfies the requirement antlib==1.1b0.post0
ERROR: No matching distribution found for antlib==1.1b0.post0
Exception information:
Traceback (most recent call last):
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'antlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 83, in from_requirement
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('antlib==1.1b0.post0')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 320, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('antlib==1.1b0.post0'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_internal\cli\base_command.py", line 189, in _main
    status = self.run(options, args)
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_internal\cli\req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_internal\commands\install.py", line 317, in run
    reqs, check_supported_wheels=not options.target_dir
  File "c:\users\my_name\.virtualenvs\test2-7vsuogkv\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 127, in resolve
    six.raise_from(error, e)
  File "<string>", line 3, in raise_from
pip._internal.exceptions.DistributionNotFound: No matching distribution found for antlib==1.1b0.post0
Removed build tracker: 'C:\\Users\\my_name\\AppData\\Local\\Temp\\pip-req-tracker-dfg00vok'
Traceback (most recent call last):
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\my_name\AppData\Local\Programs\Python\Python37-32\Scripts\pipenv.exe\__main__.py", line 7, in <module>
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\vendor\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\cli\command.py", line 253, in install
    site_packages=state.site_packages
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\core.py", line 2202, in do_install
    skip_lock=skip_lock,
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\core.py", line 1312, in do_init
    pypi_mirror=pypi_mirror,
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\core.py", line 900, in do_install_dependencies
    retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\core.py", line 796, in batch_install
    _cleanup_procs(procs, failed_deps_queue, retry=retry)
  File "c:\users\my_name\appdata\local\programs\python\python37-32\lib\site-packages\pipenv\core.py", line 703, in _cleanup_procs
    raise exceptions.InstallError(c.dep.name, extra=err_lines)
pipenv.exceptions.InstallError: ERROR: Couldn't install package: antlib
 Package installation failed...
     ================================ 0/1 - 00:00:01
```

### Steps to replicate

1. create a new folder
2. Run `pipenv install antlib --pre`

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'c:\\users\\my_name\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\pipenv'`

Python location: `'c:\\users\\my_name\\appdata\\local\\programs\\python\\python37-32\\python.exe'`

Python installations found:

  - `3.7.5`: `C:\Users\my_name\AppData\Local\Programs\Python\Python37-32\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.5',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.19041',
 'python_full_version': '3.7.5',
 'python_version': '3.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `ANDROID_SDK_ROOT`
  - `APPDATA`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `DRIVERDATA`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `JAVA_HOME`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_ARCHITEW6432`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `RUBYOPT`
  - `SESSIONNAME`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `WINDIR`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

PipenvΓÇôspecific environment variables:

DebugΓÇôspecific environment variables:

  - `PATH`: `C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Nordic Semiconductor\nrf-command-line-tools\bin\;C:\Program Files\MATLAB\R2017a\bin;C:\Program Files (x86)\GitExtensions\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files (x86)\STMicroelectronics\STM32 ST-LINK Utility\ST-LINK Utility;C:\Ruby27-x64\bin;C:\Users\my_name\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\my_name\AppData\Local\Programs\Python\Python37-32\;C:\Users\my_name\AppData\Local\Microsoft\WindowsApps;C:\Users\my_name\AppData\Local\Programs\Microsoft VS Code\bin;C:\MinGW\msys\1.0\bin;C:\cygwin64\bin;C:\Users\my_name\AppData\Roaming\Python\Python37\Scripts;`

---------------------------

Contents of `Pipfile` ('C:\\my_path\\Source\\test2\\Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
antlib = "*"

[dev-packages]

[requires]
python_version = "3.7"

[pipenv]
allow_prereleases = true

```

Contents of `Pipfile.lock` ('C:\\my_path\\Source\\test2\\Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "0816de605dcb2aef7d45d1f93a7831b66a6e61f3747f082c922056e5213940fa"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "antlib": {
            "hashes": [
                "sha256:aebfcbdff0770653d3959061f176299eec3b8d7f77f151d3c46d7d0ea06fb64b"
            ],
            "index": "pypi",
            "version": "==1.1b0.post0"
        }
    },
    "develop": {}
}

```
</details>

**Comment by uranusjr** [comment]
The error message says it all, antlib is inconsistent. You need to contact antlib maintainers to fix this.
