### ISSUE TITLE
pipenv install fails if 'url' in setup.cfg contains URLencoded space

### ISSUE THREAD

**Issue by torbjoernk** [pypa/pipenv#4622]
### Issue description

When the `url` attribute of a `setup.cfg` file contains an URLencoded whitespace (i.e. "%20"), any pipenv commands that try to install packages fails with the following error message:

```
[pipenv.exceptions.InstallError]: configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%20Project/test_repo'
```
The error persists for the following variants:
```
url = https://ssh.example.com/Some%20Project/test_repo
```
```
url = "https://ssh.example.com/Some%20Project/test_repo"
```
but not for this
```
url = "https://ssh.example.com/Some Project/test_repo"
```

### Expected result

pipenv installs the defined packages as specified.

### Actual result

```
$ pipenv install --dev
Creating a virtualenv for this project...
Pipfile: /tmp/pipenv_bug/Pipfile
Using $HOME/.pyenv/versions/3.8.6@packaging/bin/python3.8 (3.8.6) to create virtualenv...
⠙ Creating virtual environment...created virtual environment CPython3.8.6.final.0-64 in 84ms
  creator CPython3Posix(dest=$HOME/.local/share/virtualenvs/pipenv_bug-bZk5Kb9q, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=$HOME/.local/share/virtualenv)
    added seed packages: pip==21.0.1, setuptools==52.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: $HOME/.local/share/virtualenvs/pipenv_bug-bZk5Kb9q
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Locking [packages] dependencies...
Updated Pipfile.lock (18c913)!
Installing dependencies from Pipfile.lock (18c913)...
An error occurred while installing attrs==20.3.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3' --hash=sha256:832aa3cde19744e49938b91fea06d69ecb9e649c93ba974535d08ad92164f700 --hash=sha256:31b2eced602aa8423c2aea9c76a724617ed67cf9513173fd3a4f03e3a929c7e6! Will try again.
An error occurred while installing iniconfig==1.1.1 --hash=sha256:011e24c64b7f47f6ebd835bb12a743f2fbe9a26d4cecaa7f53bc4f35ee9da8b3 --hash=sha256:bc3af051d7d14b2ee5ef9969666def0cd1a000e121eaea580d4a313df4b37f32! Will try again.
An error occurred while installing packaging==20.9; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3' --hash=sha256:5b327ac1320dc863dca72f4514ecc086f31186744b84a230374cc1fd776feae5 --hash=sha256:67714da7f7bc052e064859c05c595155bd1ee9f69f76557e21f051443c20947a! Will try again.
An error occurred while installing pluggy==0.13.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3' --hash=sha256:15b2acde666561e1298d71b523007ed7364de07029219b604cf808bfa1c765b0 --hash=sha256:966c145cd83c96502c3c3868f50408687b38434af77734af1e9ca461a4081d2d! Will try again.
An error occurred while installing py==1.10.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3' --hash=sha256:3b80836aa6d1feeaa108e046da6423ab8f6ceda6468545ae8d02d9d58d18818a --hash=sha256:21b81bda15b66ef5e1a777a21c4dcd9c20ad3efd0b3f817e7a809035269e1bd3! Will try again.
An error occurred while installing pyparsing==2.4.7; python_version >= '2.6' and python_version not in '3.0, 3.1, 3.2' --hash=sha256:ef9d7589ef3c200abe66653d3f1ab1033c3c419ae9b9bdb1240a85b024efc88b --hash=sha256:c203ec8783bf771a155b207279b9bccb8dea02d8f0c9e5f8ead507bc3246ecc1! Will try again.
An error occurred while installing pytest==6.2.2 --hash=sha256:b574b57423e818210672e07ca1fa90aaf194a4f63f3ab909a2c67ebb22913839 --hash=sha256:9d1edf9e7d0b84d72ea3dbcdfd22b35fb543a5e8f2a60092dd578936bf63d7f9! Will try again.
An error occurred while installing toml==0.10.2; python_version >= '2.6' and python_version not in '3.0, 3.1, 3.2' --hash=sha256:806143ae5bfb6a3c6e736a764057db0e6a0e05e338b5630894a5f779cabb4f9b --hash=sha256:b3bda1d108d5dd99f4a20d24d9c348e91c4db7ab1b749200bded2f839ccbe68f! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 8/8 — 00:00:01
Installing initially failed dependencies...
[InstallError]:   File "$HOME/.local/lib/python3.8/site-packages/pipenv/cli/command.py", line 233, in install
[InstallError]:       retcode = do_install(
[InstallError]:   File "$HOME/.local/lib/python3.8/site-packages/pipenv/core.py", line 2052, in do_install
[InstallError]:       do_init(
[InstallError]:   File "$HOME/.local/lib/python3.8/site-packages/pipenv/core.py", line 1304, in do_init
[InstallError]:       do_install_dependencies(
[InstallError]:   File "$HOME/.local/lib/python3.8/site-packages/pipenv/core.py", line 899, in do_install_dependencies
[InstallError]:       batch_install(
[InstallError]:   File "$HOME/.local/lib/python3.8/site-packages/pipenv/core.py", line 796, in batch_install
[InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
[InstallError]:   File "$HOME/.local/lib/python3.8/site-packages/pipenv/core.py", line 703, in _cleanup_procs
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: Collecting attrs==20.3.0
[pipenv.exceptions.InstallError]:   Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
[pipenv.exceptions.InstallError]: Installing collected packages: attrs
[pipenv.exceptions.InstallError]: ERROR: Exception:
[pipenv.exceptions.InstallError]: Traceback (most recent call last):
[pipenv.exceptions.InstallError]:   File "$HOME/.local/share/virtualenvs/pipenv_bug-bZk5Kb9q/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
[pipenv.exceptions.InstallError]:     status = self.run(options, args)
[pipenv.exceptions.InstallError]:   File "$HOME/.local/share/virtualenvs/pipenv_bug-bZk5Kb9q/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
[pipenv.exceptions.InstallError]:     return func(self, options, args)
[pipenv.exceptions.InstallError]:   File "$HOME/.local/share/virtualenvs/pipenv_bug-bZk5Kb9q/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 391, in run
[pipenv.exceptions.InstallError]:     installed = install_given_reqs(
[pipenv.exceptions.InstallError]:   File "$HOME/.local/share/virtualenvs/pipenv_bug-bZk5Kb9q/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 80, in install_given_reqs
[pipenv.exceptions.InstallError]:     requirement.install(
[pipenv.exceptions.InstallError]:   File "$HOME/.local/share/virtualenvs/pipenv_bug-bZk5Kb9q/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 753, in install
[pipenv.exceptions.InstallError]:     scheme = get_scheme(
[pipenv.exceptions.InstallError]:   File "$HOME/.local/share/virtualenvs/pipenv_bug-bZk5Kb9q/lib/python3.8/site-packages/pip/_internal/locations.py", line 175, in get_scheme
[pipenv.exceptions.InstallError]:     scheme = distutils_scheme(
[pipenv.exceptions.InstallError]:   File "$HOME/.local/share/virtualenvs/pipenv_bug-bZk5Kb9q/lib/python3.8/site-packages/pip/_internal/locations.py", line 99, in distutils_scheme
[pipenv.exceptions.InstallError]:     d.parse_config_files()
[pipenv.exceptions.InstallError]:   File "$HOME/.local/share/virtualenvs/pipenv_bug-bZk5Kb9q/lib/python3.8/site-packages/_virtualenv.py", line 21, in parse_config_files
[pipenv.exceptions.InstallError]:     result = old_parse_config_files(self, *args, **kwargs)
[pipenv.exceptions.InstallError]:   File "$HOME/.pyenv/versions/3.8.6/lib/python3.8/distutils/dist.py", line 413, in parse_config_files
[pipenv.exceptions.InstallError]:     val = parser.get(section,opt)
[pipenv.exceptions.InstallError]:   File "$HOME/.pyenv/versions/3.8.6/lib/python3.8/configparser.py", line 799, in get
[pipenv.exceptions.InstallError]:     return self._interpolation.before_get(self, section, option, value,
[pipenv.exceptions.InstallError]:   File "$HOME/.pyenv/versions/3.8.6/lib/python3.8/configparser.py", line 395, in before_get
[pipenv.exceptions.InstallError]:     self._interpolate_some(parser, option, L, value, section, defaults, 1)
[pipenv.exceptions.InstallError]:   File "$HOME/.pyenv/versions/3.8.6/lib/python3.8/configparser.py", line 442, in _interpolate_some
[pipenv.exceptions.InstallError]:     raise InterpolationSyntaxError(
[pipenv.exceptions.InstallError]: configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%20Project/test_repo'
ERROR: Couldn't install package: attrs
 Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 7/8 — 00:00:01
/usr/lib/python3.8/subprocess.py:942: ResourceWarning: subprocess 49540 is still running
  _warn("subprocess %s is still running" % self.pid,
sys:1: ResourceWarning: unclosed file <_io.FileIO name=8 mode='wb' closefd=True>
sys:1: ResourceWarning: unclosed file <_io.FileIO name=9 mode='rb' closefd=True>
/usr/lib/python3.8/subprocess.py:942: ResourceWarning: subprocess 49542 is still running
  _warn("subprocess %s is still running" % self.pid,
sys:1: ResourceWarning: unclosed file <_io.FileIO name=10 mode='wb' closefd=True>
sys:1: ResourceWarning: unclosed file <_io.FileIO name=11 mode='rb' closefd=True>
/usr/lib/python3.8/subprocess.py:942: ResourceWarning: subprocess 49544 is still running
  _warn("subprocess %s is still running" % self.pid,
sys:1: ResourceWarning: unclosed file <_io.FileIO name=12 mode='wb' closefd=True>
sys:1: ResourceWarning: unclosed file <_io.FileIO name=13 mode='rb' closefd=True>
/usr/lib/python3.8/subprocess.py:942: ResourceWarning: subprocess 49546 is still running
  _warn("subprocess %s is still running" % self.pid,
sys:1: ResourceWarning: unclosed file <_io.FileIO name=14 mode='wb' closefd=True>
sys:1: ResourceWarning: unclosed file <_io.FileIO name=15 mode='rb' closefd=True>
/usr/lib/python3.8/subprocess.py:942: ResourceWarning: subprocess 49550 is still running
  _warn("subprocess %s is still running" % self.pid,
sys:1: ResourceWarning: unclosed file <_io.FileIO name=18 mode='wb' closefd=True>
sys:1: ResourceWarning: unclosed file <_io.FileIO name=19 mode='rb' closefd=True>
/usr/lib/python3.8/subprocess.py:942: ResourceWarning: subprocess 49552 is still running
  _warn("subprocess %s is still running" % self.pid,
sys:1: ResourceWarning: unclosed file <_io.FileIO name=20 mode='wb' closefd=True>
sys:1: ResourceWarning: unclosed file <_io.FileIO name=21 mode='rb' closefd=True>
```

### Steps to replicate

Create the following files
```
/tmp/pipenv_bug$ ls -l
total 12
-rw-r--r-- 1 tklatt tklatt  151 Feb 16 16:08 Pipfile
-rw-r--r-- 1 tklatt tklatt   66 Feb 16 16:07 setup.cfg
```
with the following content
```
/tmp/pipenv_bug$ cat setup.cfg
[metadata]
url = https://ssh.example.com/Some%20Project/test_repo
```
```
/tmp/pipenv_bug$ cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]
pytest = "*"

[requires]
python_version = "3.8"
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'$HOME/.local/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.8.6`: `$HOME/.pyenv/versions/3.8.6/bin/python3.8`
  - `3.8.5`: `/usr/bin/python3.8`
  - `3.8.5`: `/usr/bin/python3`
  - `3.8.5`: `/bin/python3.8`
  - `3.8.5`: `/bin/python3`
  - `3.6.8`: `$HOME/.pyenv/versions/3.6.8/bin/python3.6m`
  - `2.7.18`: `/usr/bin/python2.7`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/bin/python2.7`
  - `2.7.18`: `/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.0-65-generic',
 'platform_system': 'Linux',
 'platform_version': '#73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021',
 'python_full_version': '3.8.5',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `COLORFGBG`
  - `COLORTERM`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DESKTOP_SESSION`
  - `DISPLAY`
  - `GPG_AGENT_INFO`
  - `HOME`
  - `KONSOLE_DBUS_SERVICE`
  - `KONSOLE_DBUS_SESSION`
  - `KONSOLE_DBUS_WINDOW`
  - `KONSOLE_VERSION`
  - `LANG`
  - `LANGUAGE`
  - `LC_ALL`
  - `LC_MEASUREMENT`
  - `LC_TIME`
  - `LOGNAME`
  - `OLDPWD`
  - `PATH`
  - `PROFILEHOME`
  - `PWD`
  - `PYENV_ROOT`
  - `PYENV_SHELL`
  - `PYENV_VIRTUALENV_INIT`
  - `QT_ACCESSIBILITY`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `SESSION_MANAGER`
  - `SHELL`
  - `SHELL_SESSION_ID`
  - `SHLVL`
  - `SSH_AGENT_PID`
  - `SSH_AUTH_SOCK`
  - `TERM`
  - `USER`
  - `WINDOWID`
  - `XAUTHORITY`
  - `XCURSOR_SIZE`
  - `XCURSOR_THEME`
  - `XDG_CONFIG_DIRS`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_DATA_DIRS`
  - `XDG_RUNTIME_DIR`
  - `XDG_SEAT`
  - `XDG_SEAT_PATH`
  - `XDG_SESSION_CLASS`
  - `XDG_SESSION_DESKTOP`
  - `XDG_SESSION_ID`
  - `XDG_SESSION_PATH`
  - `XDG_SESSION_TYPE`
  - `XDG_VTNR`
  - `_`
  - `ZSH`
  - `ZSH_THEME`
  - `DISABLE_AUTO_UPDATE`
  - `LC_CTYPE`
  - `PAGER`
  - `LESS`
  - `LSCOLORS`
  - `LS_COLORS`
  - `SPROMPT`
  - `EDITOR`
  - `XDG_CONFIG_HOME`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `$HOME/.pyenv/plugins/pyenv-virtualenv/shims:$HOME/.pyenv/shims:$HOME/.pyenv/bin:$HOME/.local/bin:/opt/bin:$HOME/.pyenv/plugins/pyenv-virtualenv/shims:$HOME/.pyenv/shims:$HOME/.pyenv/bin:$HOME/.local/bin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/tmp/pipenv_bug`

---------------------------

Contents of `Pipfile` ('/tmp/pipenv_bug/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]
pytest = "*"

[requires]
python_version = "3.8"

```

Contents of `Pipfile.lock` ('/tmp/pipenv_bug/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "44ccf4c66d663506b934edaa5a4873daba29d125557d68c7840956adb918c913"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {
        "attrs": {
            "hashes": [
                "sha256:31b2eced602aa8423c2aea9c76a724617ed67cf9513173fd3a4f03e3a929c7e6",
                "sha256:832aa3cde19744e49938b91fea06d69ecb9e649c93ba974535d08ad92164f700"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "version": "==20.3.0"
        },
        "iniconfig": {
            "hashes": [
                "sha256:011e24c64b7f47f6ebd835bb12a743f2fbe9a26d4cecaa7f53bc4f35ee9da8b3",
                "sha256:bc3af051d7d14b2ee5ef9969666def0cd1a000e121eaea580d4a313df4b37f32"
            ],
            "version": "==1.1.1"
        },
        "packaging": {
            "hashes": [
                "sha256:5b327ac1320dc863dca72f4514ecc086f31186744b84a230374cc1fd776feae5",
                "sha256:67714da7f7bc052e064859c05c595155bd1ee9f69f76557e21f051443c20947a"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "version": "==20.9"
        },
        "pluggy": {
            "hashes": [
                "sha256:15b2acde666561e1298d71b523007ed7364de07029219b604cf808bfa1c765b0",
                "sha256:966c145cd83c96502c3c3868f50408687b38434af77734af1e9ca461a4081d2d"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "version": "==0.13.1"
        },
        "py": {
            "hashes": [
                "sha256:21b81bda15b66ef5e1a777a21c4dcd9c20ad3efd0b3f817e7a809035269e1bd3",
                "sha256:3b80836aa6d1feeaa108e046da6423ab8f6ceda6468545ae8d02d9d58d18818a"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "version": "==1.10.0"
        },
        "pyparsing": {
            "hashes": [
                "sha256:c203ec8783bf771a155b207279b9bccb8dea02d8f0c9e5f8ead507bc3246ecc1",
                "sha256:ef9d7589ef3c200abe66653d3f1ab1033c3c419ae9b9bdb1240a85b024efc88b"
            ],
            "markers": "python_version >= '2.6' and python_version not in '3.0, 3.1, 3.2'",
            "version": "==2.4.7"
        },
        "pytest": {
            "hashes": [
                "sha256:9d1edf9e7d0b84d72ea3dbcdfd22b35fb543a5e8f2a60092dd578936bf63d7f9",
                "sha256:b574b57423e818210672e07ca1fa90aaf194a4f63f3ab909a2c67ebb22913839"
            ],
            "index": "pypi",
            "version": "==6.2.2"
        },
        "toml": {
            "hashes": [
                "sha256:806143ae5bfb6a3c6e736a764057db0e6a0e05e338b5630894a5f779cabb4f9b",
                "sha256:b3bda1d108d5dd99f4a20d24d9c348e91c4db7ab1b749200bded2f839ccbe68f"
            ],
            "markers": "python_version >= '2.6' and python_version not in '3.0, 3.1, 3.2'",
            "version": "==0.10.2"
        }
    }
}

```
</details>

**Comment by matteius** [comment]
@torbjoernk Please recheck with `2022.1.8` as your example is for a 404 repository and doesn't show which command to run, so I will be unable to reproduce it.
