### ISSUE TITLE
Your Pipfile requires python_version 3.7, but you are using None (/home/s/.local/share/v/t/bin/python).

### ISSUE THREAD

**Issue by praveen-git-code** [pypa/pipenv#4623]
I am facing the below error when I try to run the make command. Can any one help me to fix this issue.
Warning: Your Pipfile requires python_version 3.7, but you are using None (/home/s/.local/share/v/t/bin/python).
  $ pipenv check will surely fail.
Loading .env environment variables…
Traceback (most recent call last):
  File "/usr/bin//pipenv", line 11, in <module>
    load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 505, in lock
    core.ensure_project(three=three, python=python)
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 616, in ensure_project
    '{0}: Your Pipfile requires {1} {2}, '
TypeError: __str__ returned non-string (type NoneType)
Traceback (most recent call last):
  File "/usr/bin//pipenv", line 11, in <module>
    load_entry_point('pipenv==11.9.0', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pipenv/cli.py", line 602, in run
    core.do_run(command=command, args=args, three=three, python=python)
  File "/usr/lib/python3/dist-packages/pipenv/core.py", line 2234, in do_run
    os.execl(command_path, command_path, *args)
  File "/usr/lib/python3.8/os.py", line 536, in execl
    execv(file, args)
FileNotFoundError: [Errno 2] No such file or directory
make[2]: *** [Makefile:31: build_deploy] Error 1
make[2]: Leaving directory '/home/sg0309559/Linuxhome/REPO/aws-teardown-v2/aws-teardowns/functions/teardown_dispatcher'
make[1]: *** [Makefile:4: archive_teardown_dispatcher] Error 2
make[1]: Leaving directory '/home/sg0309559/Linuxhome/REPO/aws-teardown-v2/aws-teardowns/functions'
make: *** [Makefile:6: archive_lambdas] Error 2

**Comment by frostming** [comment]
We don't have energy looking into an old version of Pipenv, you should switch to other recommended installation methods to get the newest Pipenv.
