### ISSUE TITLE
egg file can not be installed

### ISSUE THREAD

**Issue by leileigong** [pypa/pipenv#4625]
### egg file can not be installed
the relative version is:

1.  python version : 3.6
2.  pipenv version : 2020.11.15

my pipfile write as follows:
```
pyscard = {path = "wheelhouse/pyscard-2.0.0-py3.6-win32.egg",markers = "python_version == '3.6'",sys_platform = "== 'win32'"}
```

```
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\pipenv3.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\pipenv\vendor\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\python36\lib\site-packages\pipenv\vendor\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\python36\lib\site-packages\pipenv\vendor\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python36\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python36\lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python36\lib\site-packages\pipenv\vendor\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\python36\lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python36\lib\site-packages\pipenv\vendor\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python36\lib\site-packages\pipenv\cli\command.py", line 253, in install
    site_packages=state.site_packages
  File "c:\python36\lib\site-packages\pipenv\core.py", line 2063, in do_install
    keep_outdated=keep_outdated
  File "c:\python36\lib\site-packages\pipenv\core.py", line 1279, in do_init
    pypi_mirror=pypi_mirror,
  File "c:\python36\lib\site-packages\pipenv\core.py", line 1113, in do_lock
    keep_outdated=keep_outdated
  File "c:\python36\lib\site-packages\pipenv\utils.py", line 1333, in venv_resolve_deps
    deps, project, r=False, include_index=True
  File "c:\python36\lib\site-packages\pipenv\utils.py", line 1451, in convert_deps_to_pip
    new_dep = Requirement.from_pipfile(dep_name, dep)
  File "c:\python36\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 2759, in from_pipfile
    r = FileRequirement.from_pipfile(name, pipfile)
  File "c:\python36\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 1853, in from_pipfile
    arg_dict["parsed_line"] = Line(line)
  File "c:\python36\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 171, in __init__
    self.parse()
  File "c:\python36\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 1313, in parse
    "Supplied requirement is not installable: {0!r}".format(self.line)
pipenv.vendor.requirementslib.exceptions.RequirementError: Supplied requirement is not installable: 'file:///E:/TestTool_ux_py3_32/wheelhouse/pyscard-2.0.0-py3.6-win32.egg#egg=pyscard'
```

How do i install an egg binary package?

**Comment by matteius** [comment]
Might just be related to a long standing issue around installing local dependencies, but I am not sure.  Could you check @leileigong on issue https://github.com/pypa/pipenv/issues/4551 and specifically if you can check if you have the same issue with a much older pipenv version `2018.11.26` and if that works can you check again with `2020.11.4` and `2020.11.15`?  There is a long backlog of issues and I want to make sure that this gets understood and classified properly.

**Comment by matteius** [comment]
@leileigong Can you try with `2022.1.8` or `main` branch?  I believe this one can be resolved ...

**Comment by matteius** [comment]
Please check with `pipenv==2022.4.20`
