### ISSUE TITLE
pipenv lock fails with package mediapipe

### ISSUE THREAD

**Issue by RuiLoureiro** [pypa/pipenv#4657]
### Issue description

I can't do `pipenv lock` with the following Pipfile:

```
[packages]
mediapipe = "*"

[requires]
python_version = "3.8"
```

I can, however, install mediapipe normally with `pip install mediapipe`
### Expected result

I expect `pipenv lock` to run successfully.
### Actual result

```
$ pipenv lock --verbose
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
⠦ Locking...
                          ROUND 1
✘ Locking Failed!
Current constraints:
  mediapipe (from -r /var/folders/zp/nlhwqtgx1j3gwyrhmhjjmbz40000gn/T/pipenvj3aumgp7requirements/pipenv-yekq8mg2-constraints.txt (line 2))

Finding the best candidates:
Traceback (most recent call last):
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/utils.py", line 823, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 260, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 260, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 319, in get_best_match
    best_match = self.repository.find_best_match(
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 205, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches mediapipe (from -r /var/folders/zp/nlhwqtgx1j3gwyrhmhjjmbz40000gn/T/pipenvj3aumgp7requirements/pipenv-yekq8mg2-constraints.txt (line 2))
No versions found
Was https://pypi.org/simple reachable?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/utils.py", line 1395, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/utils.py", line 1108, in actually_resolve_deps
    resolver.resolve()
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/utils.py", line 833, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: Could not find a version that matches mediapipe (from -r /var/folders/zp/nlhwqtgx1j3gwyrhmhjjmbz40000gn/T/pipenvj3aumgp7requirements/pipenv-yekq8mg2-constraints.txt (line 2))
No versions found
Was https://pypi.org/simple reachable?
ROUND 1
Current constraints:
  mediapipe (from -r /var/folders/zp/nlhwqtgx1j3gwyrhmhjjmbz40000gn/T/pipenvj3aumgp7requirements/pipenv-yekq8mg2-constraints.txt (line 2))

Finding the best candidates:
Traceback (most recent call last):
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/utils.py", line 823, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 260, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 260, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 319, in get_best_match
    best_match = self.repository.find_best_match(
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 205, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches mediapipe (from -r /var/folders/zp/nlhwqtgx1j3gwyrhmhjjmbz40000gn/T/pipenvj3aumgp7requirements/pipenv-yekq8mg2-constraints.txt (line 2))
No versions found
Was https://pypi.org/simple reachable?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/utils.py", line 1395, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/utils.py", line 1108, in actually_resolve_deps
    resolver.resolve()
  File "/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv/utils.py", line 833, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: Could not find a version that matches mediapipe (from -r /var/folders/zp/nlhwqtgx1j3gwyrhmhjjmbz40000gn/T/pipenvj3aumgp7requirements/pipenv-yekq8mg2-constraints.txt (line 2))
No versions found
Was https://pypi.org/simple reachable?
```
### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'/Users/ruiloureiro/.pyenv/versions/3.8.6/lib/python3.8/site-packages/pipenv'`

Python location: `'/Users/ruiloureiro/.pyenv/versions/3.8.6/bin/python3.8'`

Python installations found:

  - `3.9.2`: `/usr/local/bin/python3`
  - `3.9.2`: `/usr/local/bin/python3.9`
  - `3.9.1`: `/Users/ruiloureiro/.pyenv/versions/3.9.1/bin/python3`
  - `3.8.6`: `/Users/ruiloureiro/.pyenv/versions/3.8.6/bin/python3`
  - `3.8.6`: `/Users/ruiloureiro/.pyenv/versions/3.8.6/bin/python3`
  - `3.8.6`: `/Users/ruiloureiro/.pyenv/versions/3.8.6/bin/python3.8`
  - `3.8.2`: `/usr/bin/python3`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '20.3.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST '
                     '2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101',
 'python_full_version': '3.8.6',
 'python_version': '3.8',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `VIRTUALENVWRAPPER_SCRIPT`
  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `PYENV_VERSION`
  - `LC_ALL`
  - `ZSH`
  - `USER`
  - `COMMAND_MODE`
  - `SSH_AUTH_SOCK`
  - `PYENV_DIR`
  - `__CF_USER_TEXT_ENCODING`
  - `PAGER`
  - `ZSH_DISABLE_COMPFIX`
  - `WORKON_HOME`
  - `LSCOLORS`
  - `VIRTUALENVWRAPPER_PYTHON`
  - `PATH`
  - `PYENV_VIRTUALENVWRAPPER_PYENV_VERSION`
  - `__CFBundleIdentifier`
  - `PWD`
  - `LANG`
  - `ITERM_PROFILE`
  - `PYENV_HOOK_PATH`
  - `XPC_FLAGS`
  - `VIRTUALENVWRAPPER_VIRTUALENV`
  - `XPC_SERVICE_NAME`
  - `PYENV_SHELL`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `_VIRTUALENVWRAPPER_API`
  - `LC_TERMINAL_VERSION`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `LC_CTYPE`
  - `VIRTUALENVWRAPPER_VIRTUALENV_CLONE`
  - `GOPATH`
  - `LC_TERMINAL`
  - `VIRTUALENVWRAPPER_LAZY_SCRIPT`
  - `PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV`
  - `COLORTERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/ruiloureiro/.pyenv/versions/3.8.6/bin:/usr/local/Cellar/pyenv/1.2.23/libexec:/usr/local/Cellar/pyenv/1.2.23/plugins/python-build/bin:/Users/ruiloureiro/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ruiloureiro/go/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/ruiloureiro/loka/debug_pipenv`

---------------------------

Contents of `Pipfile` ('/Users/ruiloureiro/loka/debug_pipenv/Pipfile'):

```toml
[packages]
mediapipe = "*"

[requires]
python_version = "3.8"
```

</details>

**Comment by RuiLoureiro** [comment]
I'm closing since I found out that this is caused because mediapipe doesn't support the M1 chip yet. However I don't understand why `pip install mediapipe` works.
