### ISSUE TITLE
Pipenv cannot install protobuf 3.12.0 nor SSLyze 4.0.4 on macOS

### ISSUE THREAD

**Issue by fj-dt** [pypa/pipenv#4666]
### Issue description

When I try to install `sslyze==4.0.4` or `protobuf==3.12.0`, the installation fails because it does not find the packages.
I tired to:
- clear the cache, even manually
-  use a fresh project (new venv, no Pipfile, no lock file)

This issue seems quite recent because we used to lock this without difficulties. I have two co-workers impacted by this as well.
I think it is related to macOS + Pipenv since my co-workers using Linux and our bitbucket pipelines are not impacted by this.

### Expected result

Installation should succeed.

### Actual result

<details><summary>$ pipenv install SSLyze==4.0.4 --verbose --clear</summary>

```
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
⠋ Installing...Writing supplied requirement line to temporary file: 'sslyze==4.0.4'
Installing 'SSLyze'
⠹ Installing SSLyze...$ ['/Users/someone/Desktop/test-protobuf/.venv/bin/pip', 'install', '--verbose', '--upgrade', '--exists-action=i', '-r', '/var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenv-326b1soz-requirements/pipenv-9_w5fs9j-requirement.txt', '-i', 'https://pypi.org/simple']
Adding SSLyze to Pipfile's [packages]...
✔ Installation Succeeded
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
⠧ Locking...
                          ROUND 1
✘ Locking Failed!
Current constraints:
  sslyze==4.0.4 (from -r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))

Finding the best candidates:
  found candidate sslyze==4.0.4 (constraint was ==4.0.4)

Finding secondary dependencies:
  sslyze==4.0.4             requires cryptography<3.4,>=2.6, nassl<5.0.0,>=4.0.0, tls-parser<1.3.0,>=1.2.2, typing_extensions

New dependencies found in this round:
  adding ['cryptography', '<3.4,>=2.6', '[]']
  adding ['nassl', '<5.0.0,>=4.0.0', '[]']
  adding ['tls-parser', '<1.3.0,>=1.2.2', '[]']
  adding ['typing-extensions', '', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  cryptography<3.4,>=2.6 (from sslyze==4.0.4->-r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))
  nassl<5.0.0,>=4.0.0 (from sslyze==4.0.4->-r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))
  sslyze==4.0.4 (from -r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))
  tls-parser<1.3.0,>=1.2.2 (from sslyze==4.0.4->-r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))
  typing_extensions (from sslyze==4.0.4->-r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))

Finding the best candidates:
  found candidate cryptography==3.3.2 (constraint was >=2.6,<3.4)
Traceback (most recent call last):
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 823, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 260, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 260, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 320, in get_best_match
    ireq, prereleases=self.prereleases
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 205, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches nassl<5.0.0,>=4.0.0 (from sslyze==4.0.4->-r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))
Tried: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3
There are incompatible versions in the resolved dependencies:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 760, in main
    dev=parsed.dev)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 709, in resolve_packages
    requirements_dir=requirements_dir,
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 692, in resolve
    req_dir=requirements_dir
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 1403, in resolve_deps
    req_dir=req_dir,
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 1108, in actually_resolve_deps
    resolver.resolve()
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 833, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: Could not find a version that matches nassl<5.0.0,>=4.0.0 (from sslyze==4.0.4->-r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))
Tried: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3
There are incompatible versions in the resolved dependencies:
ROUND 1
Current constraints:
  sslyze==4.0.4 (from -r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))

Finding the best candidates:
  found candidate sslyze==4.0.4 (constraint was ==4.0.4)

Finding secondary dependencies:
  sslyze==4.0.4             requires cryptography<3.4,>=2.6, nassl<5.0.0,>=4.0.0, tls-parser<1.3.0,>=1.2.2, typing_extensions

New dependencies found in this round:
  adding ['cryptography', '<3.4,>=2.6', '[]']
  adding ['nassl', '<5.0.0,>=4.0.0', '[]']
  adding ['tls-parser', '<1.3.0,>=1.2.2', '[]']
  adding ['typing-extensions', '', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  cryptography<3.4,>=2.6 (from sslyze==4.0.4->-r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))
  nassl<5.0.0,>=4.0.0 (from sslyze==4.0.4->-r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))
  sslyze==4.0.4 (from -r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))
  tls-parser<1.3.0,>=1.2.2 (from sslyze==4.0.4->-r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))
  typing_extensions (from sslyze==4.0.4->-r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))

Finding the best candidates:
  found candidate cryptography==3.3.2 (constraint was >=2.6,<3.4)
Traceback (most recent call last):
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 823, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 260, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 260, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 320, in get_best_match
    ireq, prereleases=self.prereleases
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 205, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches nassl<5.0.0,>=4.0.0 (from sslyze==4.0.4->-r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))
Tried: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3
There are incompatible versions in the resolved dependencies:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 760, in main
    dev=parsed.dev)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 709, in resolve_packages
    requirements_dir=requirements_dir,
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 692, in resolve
    req_dir=requirements_dir
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 1403, in resolve_deps
    req_dir=req_dir,
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 1108, in actually_resolve_deps
    resolver.resolve()
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 833, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: Could not find a version that matches nassl<5.0.0,>=4.0.0 (from sslyze==4.0.4->-r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvazyj_ra7requirements/pipenv-lflm8668-constraints.txt (line 2))
Tried: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3
There are incompatible versions in the resolved dependencies:
```

</details>

<details><summary>$ pipenv install protobuf==3.12.0 --verbose --clear</summary>

```
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing protobuf==3.12.0...
Installing package: protobuf==3.12.0
Writing supplied requirement line to temporary file: 'protobuf==3.12.0'
Installing 'protobuf'
⠹ Installing protobuf...$ ['/Users/someone/Desktop/test-protobuf/.venv/bin/pip', 'install', '--verbose', '--upgrade', '--exists-action=i', '-r', '/var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenv-hu7zce1o-requirements/pipenv-6tg5qs2h-requirement.txt', '-i', 'https://pypi.org/simple']
Adding protobuf to Pipfile's [packages]...
✔ Installation Succeeded
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
⠧ Locking...
                          ROUND 1
✘ Locking Failed!
Current constraints:
  protobuf==3.12.0 (from -r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvyzdsq8q_requirements/pipenv-swinq76s-constraints.txt (line 2))

Finding the best candidates:
  found candidate protobuf==3.12.0 (constraint was ==3.12.0)

Finding secondary dependencies:
  protobuf==3.12.0 not in cache, need to check index
CRITICAL:pipenv.patched.notpip._internal.index.package_finder:Could not find a version that satisfies the requirement protobuf==3.12.0 (from -r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvyzdsq8q_requirements/pipenv-swinq76s-constraints.txt (line 2)) (from versions: 2.0.0b0, 2.0.3, 2.3.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 3.0.0a2, 3.0.0a3, 3.0.0b1, 3.0.0b1.post1, 3.0.0b1.post2, 3.0.0b2, 3.0.0b2.post1, 3.0.0b2.post2, 3.0.0b3, 3.0.0b4, 3.0.0, 3.1.0, 3.1.0.post1, 3.2.0rc1, 3.2.0rc1.post1, 3.2.0rc2, 3.2.0, 3.3.0, 3.4.0, 3.5.0.post1, 3.5.1, 3.5.2, 3.5.2.post1, 3.6.0, 3.6.1, 3.7.0rc2, 3.7.0rc3, 3.7.0, 3.7.1, 3.8.0rc1, 3.8.0, 3.9.0rc1, 3.9.0, 3.9.1, 3.9.2, 3.10.0rc1, 3.10.0, 3.11.0rc1, 3.11.0rc2, 3.11.0, 3.11.1, 3.11.2, 3.11.3, 3.12.2, 3.12.4, 3.13.0rc3, 3.13.0, 3.14.0rc1, 3.14.0rc2, 3.14.0rc3, 3.14.0, 3.15.0rc1, 3.15.0rc2, 3.15.0, 3.15.1, 3.15.2, 3.15.3, 3.15.4, 3.15.5, 3.15.6, 3.15.7, 4.0.0rc1, 4.0.0rc2)
Traceback (most recent call last):
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 823, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 268, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 383, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 229, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 351, in get_legacy_dependencies
    download_dir, ireq, wheel_cache
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 306, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 339, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 286, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/index/package_finder.py", line 963, in find_requirement
    'No matching distribution found for %s' % req
pipenv.patched.notpip._internal.exceptions.DistributionNotFound: No matching distribution found for protobuf==3.12.0 (from -r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvyzdsq8q_requirements/pipenv-swinq76s-constraints.txt (line 2))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 760, in main
    dev=parsed.dev)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 709, in resolve_packages
    requirements_dir=requirements_dir,
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 692, in resolve
    req_dir=requirements_dir
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 1403, in resolve_deps
    req_dir=req_dir,
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 1108, in actually_resolve_deps
    resolver.resolve()
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 833, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: No matching distribution found for protobuf==3.12.0 (from -r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvyzdsq8q_requirements/pipenv-swinq76s-constraints.txt (line 2))
ROUND 1
Current constraints:
  protobuf==3.12.0 (from -r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvyzdsq8q_requirements/pipenv-swinq76s-constraints.txt (line 2))

Finding the best candidates:
  found candidate protobuf==3.12.0 (constraint was ==3.12.0)

Finding secondary dependencies:
  protobuf==3.12.0 not in cache, need to check index
CRITICAL:pipenv.patched.notpip._internal.index.package_finder:Could not find a version that satisfies the requirement protobuf==3.12.0 (from -r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvyzdsq8q_requirements/pipenv-swinq76s-constraints.txt (line 2)) (from versions: 2.0.0b0, 2.0.3, 2.3.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 3.0.0a2, 3.0.0a3, 3.0.0b1, 3.0.0b1.post1, 3.0.0b1.post2, 3.0.0b2, 3.0.0b2.post1, 3.0.0b2.post2, 3.0.0b3, 3.0.0b4, 3.0.0, 3.1.0, 3.1.0.post1, 3.2.0rc1, 3.2.0rc1.post1, 3.2.0rc2, 3.2.0, 3.3.0, 3.4.0, 3.5.0.post1, 3.5.1, 3.5.2, 3.5.2.post1, 3.6.0, 3.6.1, 3.7.0rc2, 3.7.0rc3, 3.7.0, 3.7.1, 3.8.0rc1, 3.8.0, 3.9.0rc1, 3.9.0, 3.9.1, 3.9.2, 3.10.0rc1, 3.10.0, 3.11.0rc1, 3.11.0rc2, 3.11.0, 3.11.1, 3.11.2, 3.11.3, 3.12.2, 3.12.4, 3.13.0rc3, 3.13.0, 3.14.0rc1, 3.14.0rc2, 3.14.0rc3, 3.14.0, 3.15.0rc1, 3.15.0rc2, 3.15.0, 3.15.1, 3.15.2, 3.15.3, 3.15.4, 3.15.5, 3.15.6, 3.15.7, 4.0.0rc1, 4.0.0rc2)
Traceback (most recent call last):
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 823, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 268, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 383, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 229, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 351, in get_legacy_dependencies
    download_dir, ireq, wheel_cache
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 306, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 339, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 286, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/index/package_finder.py", line 963, in find_requirement
    'No matching distribution found for %s' % req
pipenv.patched.notpip._internal.exceptions.DistributionNotFound: No matching distribution found for protobuf==3.12.0 (from -r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvyzdsq8q_requirements/pipenv-swinq76s-constraints.txt (line 2))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 760, in main
    dev=parsed.dev)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 709, in resolve_packages
    requirements_dir=requirements_dir,
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/resolver.py", line 692, in resolve
    req_dir=requirements_dir
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 1403, in resolve_deps
    req_dir=req_dir,
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 1108, in actually_resolve_deps
    resolver.resolve()
  File "/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv/utils.py", line 833, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: No matching distribution found for protobuf==3.12.0 (from -r /var/folders/zv/43ym4vwd7ks1x59h3qh8_ht40000gn/T/pipenvyzdsq8q_requirements/pipenv-swinq76s-constraints.txt (line 2))
```

</details>

### Steps to replicate

I am using:
- macOS 11.2.3 (20D91)
- pyenv 1.2.24
- Python 3.7.10
- Pipenv version 2020.11.15
- pip 21.0.1
- setuptools 54.2.0
- wheel 0.36.2

```
mkdir test-packages
cd test-packages
python -m venv .venv
source .venv/bin/activate
pip install --upgrade pip wheel setuptools
pipenv install protobuf==3.12.0
pipenv install sslyze==4.0.4
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'/Users/someone/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pipenv'`

Python location: `'/Users/someone/.pyenv/versions/3.7.10/bin/python3.7'`

Python installations found:

  - `3.8.8`: `/Users/someone/.pyenv/versions/3.8.8/bin/python3`
  - `3.8.2`: `/usr/bin/python3`
  - `3.7.10`: `/Users/someone/Desktop/test-protobuf/.venv/bin/python3`
  - `3.7.10`: `/Users/someone/.pyenv/versions/3.7.10/bin/python3`
  - `3.7.10`: `/Users/someone/.pyenv/versions/3.7.10/bin/python3.7m`
  - `3.7.10`: `/Users/someone/.pyenv/versions/3.7.10/bin/python3.7`
  - `3.7.10`: `/Users/someone/Desktop/test-protobuf/.venv/bin/python3`
  - `3.7.10`: `/Users/someone/.pyenv/versions/3.7.10/bin/python3`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.10',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '20.3.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST '
                     '2021; root:xnu-7195.81.3~1/RELEASE_X86_64',
 'python_full_version': '3.7.10',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `TERM`
  - `SHELL`
  - `PIPENV_VENV_IN_PROJECT`
  - `TMPDIR`
  - `_P9K_SSH`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `PYENV_VERSION`
  - `LC_ALL`
  - `ZSH`
  - `USER`
  - `COMMAND_MODE`
  - `SSH_AUTH_SOCK`
  - `PYENV_DIR`
  - `__CF_USER_TEXT_ENCODING`
  - `VIRTUAL_ENV`
  - `PAGER`
  - `LSCOLORS`
  - `PATH`
  - `__CFBundleIdentifier`
  - `PWD`
  - `LANG`
  - `ITERM_PROFILE`
  - `PYENV_HOOK_PATH`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `PYENV_SHELL`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `LC_TERMINAL_VERSION`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `LC_CTYPE`
  - `LC_TERMINAL`
  - `COLORTERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_VENV_IN_PROJECT`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/someone/.pyenv/versions/3.7.10/bin:/usr/local/Cellar/pyenv/1.2.24.1/libexec:/usr/local/Cellar/pyenv/1.2.24.1/plugins/python-build/bin:/Users/someone/Desktop/test-protobuf/.venv/bin:/usr/local/opt/openjdk/bin:/Users/someone/.poetry/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/postgresql@9.6/bin:/Users/someone/.pyenv/shims:/Users/someone/.pyenv/bin:/Users/someone/Documents/google-cloud-sdk/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/someone/Desktop/test-protobuf`
  - `VIRTUAL_ENV`: `/Users/someone/Desktop/test-protobuf/.venv`

---------------------------

Contents of `Pipfile` ('/Users/someone/Desktop/test-protobuf/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
sslyze = "==4.0.4"

[dev-packages]

[requires]
python_version = "3.7"

```

</details>

**Comment by Mause** [comment]
Have you tried with `SYSTEM_VERSION_COMPAT=1`?

**Comment by fj-dt** [comment]
This worked! 
I didn't know about the environment variable. I see it sets the macOS version to 10.16. Does that mean Pipenv does not handle the new macOS version or is it something else?
Anyway, thanks a lot Mause!
