### ISSUE TITLE
Pipenv can't import pip._internal.cache

### ISSUE THREAD

**Issue by cephox** [pypa/pipenv#4690]
### Issue description

When I run `pipenv install <any package>`, pipenv says, it cannot import pip._internal.cache (ModuleNotFound)

![image](https://user-images.githubusercontent.com/40516991/117032291-a9300080-ad01-11eb-966b-f7ac80b046ad.png)

### Expected result

Pipenv should install the specified package correctly

### Actual result

Pipenv displays a ModuleNotFoundError

`pipenv install discord.py --verbose`:
```Installing discord.py...
Installing package: discord.py
⠋ Installing...Writing supplied requirement line to temporary file: 'discord.py'
Installing 'discord.py'
⠸ Installing discord.py...$ ['/home/notme/.local/share/virtualenvs/test-7HILzwjT/bin/pip', 'install', '--verbose', '--upgrade', '--exists-action=i', '-r', '/tmp/pipenv-b0tc5foj-requirements/pipenv-56gxc3ek-requirement.txt', '-i', 'https://pypi.org/simple']
Using source directory: '/home/notme/.local/share/virtualenvs/test-7HILzwjT/src'
Error:  An error occurred while installing discord.py!
Error text: 
Traceback (most recent call last):
  File "/home/notme/.local/share/virtualenvs/test-7HILzwjT/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/home/notme/.local/share/virtualenvs/test-7HILzwjT/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 71, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/home/notme/.local/share/virtualenvs/test-7HILzwjT/lib/python3.9/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/notme/.local/share/virtualenvs/test-7HILzwjT/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 12, in <module>
    from pip._internal.cache import WheelCache
ModuleNotFoundError: No module named 'pip._internal.cache'


✘ Installation Failed
```

### Steps to replicate

I didn't found any problem related to mine, so I suppose, only I have this problem, but here are the commands I executed:
1. `pipenv install discord.py`

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2020.11.15'`

Pipenv location: `'/usr/lib/python3.9/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `3.9.4`: `/usr/bin/python3`
  - `3.9.4`: `/usr/bin/python3.9`
  - `2.7.18`: `/usr/bin/python2.7`
  - `2.7.18`: `/usr/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.4',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.11.16-arch1-1',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000',
 'python_full_version': '3.9.4',
 'python_version': '3.9',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `SESSION_MANAGER`
  - `WINDOWID`
  - `COLORTERM`
  - `XDG_CONFIG_DIRS`
  - `XDG_MENU_PREFIX`
  - `JAVA_HOME`
  - `DOTNET_ROOT`
  - `SSH_AUTH_SOCK`
  - `DESKTOP_SESSION`
  - `SSH_AGENT_PID`
  - `GTK_MODULES`
  - `XDG_SEAT`
  - `PWD`
  - `LOGNAME`
  - `XDG_SESSION_TYPE`
  - `SYSTEMD_EXEC_PID`
  - `XAUTHORITY`
  - `WINDOWPATH`
  - `MOTD_SHOWN`
  - `HOME`
  - `LANG`
  - `XDG_CURRENT_DESKTOP`
  - `VTE_VERSION`
  - `INVOCATION_ID`
  - `DOTNET_BUNDLE_EXTRACT_BASE_DIR`
  - `XDG_SESSION_CLASS`
  - `TERM`
  - `USER`
  - `PYTHONIOENCODING`
  - `DISPLAY`
  - `SHLVL`
  - `XDG_VTNR`
  - `XDG_SESSION_ID`
  - `XDG_RUNTIME_DIR`
  - `JOURNAL_STREAM`
  - `XDG_DATA_DIRS`
  - `GDK_BACKEND`
  - `PATH`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `MAIL`
  - `OLDPWD`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/notme/.config/coc/extensions/coc-clangd-data/install/10.0.0/clangd_10.0.0/bin:/home/notme/developement/flutter/bin:/home/notme/vm:/home/notme/Games:/home/notme/applications:/home/notme/.config/coc/extensions/coc-clangd-data/install/10.0.0/clangd_10.0.0/bin:/home/notme/developement/flutter/bin:/home/notme/vm:/home/notme/Games:/home/notme/applications:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/notme/.dotnet/tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/notme/test`

---------------------------

Contents of `Pipfile` ('/home/notme/test/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.9"

```

</details>

**Comment by tolstislon** [comment]
discord.py -> `python_requires='>=3.8.0'`

**Comment by matteius** [comment]
@cephox what version of pip did you have installed, and is this still an issue for you?  I suspect that once you update your version of pip, you would run into the fact that the specific package you call out has irresolvable differences in package versions:

```
((venv) ) bash-3.2$ pipenv install discord.py
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing discord.py...
Adding discord.py to Pipfile's [packages]...
✔ Installation Succeeded
Pipfile.lock (c24e8a) out of date, updating to (8870bb)...
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
dataclasses; python_version < '3.7' doesn't match your environment, its dependencies won't be resolved.
stdeb; sys_platform == 'linux' doesn't match your environment, its dependencies won't be resolved.
[ResolutionFailure]:   File "/opt/homebrew/lib/python3.9/site-packages/pipenv/resolver.py", line 741, in _main
[ResolutionFailure]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
[ResolutionFailure]:   File "/opt/homebrew/lib/python3.9/site-packages/pipenv/resolver.py", line 702, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "/opt/homebrew/lib/python3.9/site-packages/pipenv/resolver.py", line 684, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "/opt/homebrew/lib/python3.9/site-packages/pipenv/utils.py", line 1397, in resolve_deps
[ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
[ResolutionFailure]:   File "/opt/homebrew/lib/python3.9/site-packages/pipenv/utils.py", line 1110, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/opt/homebrew/lib/python3.9/site-packages/pipenv/utils.py", line 835, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches pycodestyle<2.7.0,<2.8.0,>=2.6.0,>=2.7.0 (from flake8==3.9.2->-r /var/folders/dz/1ztqktbs26x5095hqzz14hg00000gn/T/pipenv78fq8wegrequirements/pipenv-x8r18byc-constraints.txt (line 6))
Tried: 2.0.0, 2.0.0, 2.1.0, 2.1.0, 2.2.0, 2.2.0, 2.3.0, 2.3.0, 2.3.1, 2.3.1, 2.4.0, 2.4.0, 2.5.0, 2.5.0, 2.6.0, 2.6.0, 2.7.0, 2.7.0, 2.8.0, 2.8.0
Tried pre-versions: 1.8.0.dev0, 1.8.0.dev0, 2.0.0a1, 2.0.0a1, 2.6.0a1, 2.6.0a1
There are incompatible versions in the resolved dependencies:
  pycodestyle<2.7.0,>=2.6.0 (from prospector==1.3.1->-r /var/folders/dz/1ztqktbs26x5095hqzz14hg00000gn/T/pipenv78fq8wegrequirements/pipenv-x8r18byc-constraints.txt (line 11))
  pycodestyle<2.8.0,>=2.7.0 (from flake8==3.9.2->-r /var/folders/dz/1ztqktbs26x5095hqzz14hg00000gn/T/pipenv78fq8wegrequirements/pipenv-x8r18byc-constraints.txt (line 6))
```

**Comment by cephox** [comment]
Thanks,
I literally have no problem at all with pipenv anymore (I have no idea why),
 but thanks for your suggestion.
