### ISSUE TITLE
Brand new Pipenv environment can't install tensorflow?

### ISSUE THREAD

**Issue by Anthonyive** [pypa/pipenv#4720]
`pip` can install it perfectly fine.

```bash
~/Documents/GitHub.nosync/MLScoringWebsite anthony_feature_db-migration !2 ?2
❯ pipenv install --python 3.8
Creating a virtualenv for this project...
Pipfile: /Users/anthony/Documents/GitHub.nosync/MLScoringWebsite/Pipfile
Using /Users/anthony/.pyenv/versions/3.8.10/bin/python3.8 (3.8.10) to create virtualenv...
⠦ Creating virtual environment...created virtual environment CPython3.8.10.final.0-64 in 392ms
  creator CPython3Posix(dest=/Users/anthony/.local/share/virtualenvs/MLScoringWebsite-XKb5Cqz5, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/anthony/Library/Application Support/virtualenv)
    added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/anthony/.local/share/virtualenvs/MLScoringWebsite-XKb5Cqz5
Creating a Pipfile for this project...
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Updated Pipfile.lock (db4242)!
Installing dependencies from Pipfile.lock (db4242)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```
```
~/Documents/GitHub.nosync/MLScoringWebsite anthony_feature_db-migration !2 ?2
❯ pipenv install tensorflow
Installing tensorflow...
Adding tensorflow to Pipfile's [packages]...
✔ Installation Succeeded
Pipfile.lock (db4242) out of date, updating to (66d06e)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
[ResolutionFailure]:   File "/Users/anthony/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/resolver.py", line 741, in _main
[ResolutionFailure]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
[ResolutionFailure]:   File "/Users/anthony/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/resolver.py", line 702, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "/Users/anthony/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/resolver.py", line 684, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "/Users/anthony/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/utils.py", line 1397, in resolve_deps
[ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
[ResolutionFailure]:   File "/Users/anthony/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/utils.py", line 1110, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/Users/anthony/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/utils.py", line 835, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches tensorflow (from -r /var/folders/28/2sy26r512hq5jdpx18q4ycjw0000gn/T/pipenveg_83kdsrequirements/pipenv-8e528zrc-constraints.txt (line 2))
No versions found
Was https://pypi.org/simple reachable?
```

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.5.29'`

Pipenv location: `'/Users/anthony/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv'`

Python location: `'/Users/anthony/.local/pipx/venvs/pipenv/bin/python'`

Python installations found:

  - `3.9.5`: `/Users/anthony/.pyenv/versions/3.9.5/bin/python3`
  - `3.9.5`: `/usr/local/bin/python3`
  - `3.9.5`: `/usr/local/bin/python3.9`
  - `3.8.10`: `/Users/anthony/.pyenv/versions/3.8.10/bin/python3`
  - `3.8.2`: `/usr/bin/python3`
  - `3.7.10`: `/Users/anthony/.pyenv/versions/3.7.10/bin/python3`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.10',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '20.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT '
                     '2021; root:xnu-7195.121.3~9/RELEASE_X86_64',
 'python_full_version': '3.8.10',
 'python_version': '3.8',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_SESSION_ID`
  - `SSH_AUTH_SOCK`
  - `LC_TERMINAL_VERSION`
  - `COLORFGBG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `LANG`
  - `PWD`
  - `SHELL`
  - `__CFBundleIdentifier`
  - `SECURITYSESSIONID`
  - `TERM_PROGRAM_VERSION`
  - `TERM_PROGRAM`
  - `PATH`
  - `LC_TERMINAL`
  - `COLORTERM`
  - `COMMAND_MODE`
  - `TERM`
  - `HOME`
  - `TMPDIR`
  - `USER`
  - `XPC_SERVICE_NAME`
  - `LOGNAME`
  - `LaunchInstanceID`
  - `__CF_USER_TEXT_ENCODING`
  - `ITERM_SESSION_ID`
  - `SHLVL`
  - `OLDPWD`
  - `P9K_TTY`
  - `_P9K_TTY`
  - `P9K_SSH`
  - `ZSH`
  - `MANPAGER`
  - `PAGER`
  - `LESS`
  - `LSCOLORS`
  - `YSU_VERSION`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/anthony/.pyenv/shims:/Users/anthony/.local/bin:/Users/anthony/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin:/usr/local/opt/fzf/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/anthony/Documents/GitHub.nosync/MLScoringWebsite`

---------------------------

Contents of `Pipfile` ('/Users/anthony/Documents/GitHub.nosync/MLScoringWebsite/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
tensorflow = "==2.4"

[dev-packages]

[requires]
python_version = "3.8"

```

Contents of `Pipfile.lock` ('/Users/anthony/Documents/GitHub.nosync/MLScoringWebsite/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "7f7606f08e0544d8d012ef4d097dabdd6df6843a28793eb6551245d4b2db4242"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}

```
</details>

**Comment by Kurt-von-Laven** [comment]
I noticed the same problem with installing prospector 1.3.1 with python 3.9.

**Comment by Anthonyive** [comment]
I also posted [an issue under tensorflow/tensorflow](https://github.com/tensorflow/tensorflow/issues/50370). I tried on my Macbook (intel) and Linux machine, and they all failed to solve dependencies...

**Comment by Kurt-von-Laven** [comment]
Have you already tried running `pipenv` in verbose mode to see why specifically it is failing?

**Comment by Anthonyive** [comment]
@Kurt-von-Laven Yes, I did, but I'm not sure why it's failing from its output...

<details><summary>Pipenv verbose output</summary>

```bash
~/test/Python
❯ rm Pipfile*

~/test/Python
❯ pipenv --rm
Removing virtualenv (/Users/anthony/.local/share/virtualenvs/Python-8ynjZ1Aj)...

~/test/Python
❯ pipenv --python 3.7
Creating a virtualenv for this project...
Pipfile: /Users/anthony/test/Python/Pipfile
Using /Users/anthony/.pyenv/versions/3.7.10/bin/python3.7m (3.7.10) to create virtualenv...
⠇ Creating virtual environment...created virtual environment CPython3.7.10.final.0-64 in 476ms
  creator CPython3Posix(dest=/Users/anthony/.local/share/virtualenvs/Python-8ynjZ1Aj, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/anthony/Library/Application Support/virtualenv)
    added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/anthony/.local/share/virtualenvs/Python-8ynjZ1Aj
Creating a Pipfile for this project...

~/test/Python
❯ pipenv install --pre -v tensorflow
Installing tensorflow...
Installing package: tensorflow
Writing supplied requirement line to temporary file: 'tensorflow'
Installing 'tensorflow'
⠙ Installing tensorflow...$ ['/Users/anthony/.local/share/virtualenvs/Python-8ynjZ1Aj/bin/pip', 'install', '--pre', '--verbose', '--upgrade', '--exists-action=i', '-r', '/var/folders/28/2sy26r512hq5jdpx18q4ycjw0000gn/T/pipenv-jwcvnf3o-requirements/pipenv-8hv0odoo-requirement.txt', '-i', 'https://pypi.org/simple']
Using source directory: '/Users/anthony/.local/share/virtualenvs/Python-8ynjZ1Aj/src'
Adding tensorflow to Pipfile's [packages]...
✔ Installation Succeeded
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
⠙ Locking...
                          ROUND 1
✘ Locking Failed!
Current constraints:
  tensorflow (from -r /var/folders/28/2sy26r512hq5jdpx18q4ycjw0000gn/T/pipenvt0ayzww9requirements/pipenv-_mec4y4u-constraints.txt (line 3))

Finding the best candidates:
Traceback (most recent call last):
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/utils.py", line 825, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 260, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 260, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 320, in get_best_match
    ireq, prereleases=self.prereleases
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 205, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches tensorflow (from -r /var/folders/28/2sy26r512hq5jdpx18q4ycjw0000gn/T/pipenvt0ayzww9requirements/pipenv-_mec4y4u-constraints.txt (line 3))
No versions found
Was https://pypi.org/simple reachable?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 760, in main
    dev=parsed.dev)
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 709, in resolve_packages
    requirements_dir=requirements_dir,
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 692, in resolve
    req_dir=requirements_dir
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/utils.py", line 1405, in resolve_deps
    req_dir=req_dir,
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/utils.py", line 1110, in actually_resolve_deps
    resolver.resolve()
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/utils.py", line 835, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: Could not find a version that matches tensorflow (from -r /var/folders/28/2sy26r512hq5jdpx18q4ycjw0000gn/T/pipenvt0ayzww9requirements/pipenv-_mec4y4u-constraints.txt (line 3))
No versions found
Was https://pypi.org/simple reachable?
ROUND 1
Current constraints:
  tensorflow (from -r /var/folders/28/2sy26r512hq5jdpx18q4ycjw0000gn/T/pipenvt0ayzww9requirements/pipenv-_mec4y4u-constraints.txt (line 3))

Finding the best candidates:
Traceback (most recent call last):
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/utils.py", line 825, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 260, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 260, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 320, in get_best_match
    ireq, prereleases=self.prereleases
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 205, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches tensorflow (from -r /var/folders/28/2sy26r512hq5jdpx18q4ycjw0000gn/T/pipenvt0ayzww9requirements/pipenv-_mec4y4u-constraints.txt (line 3))
No versions found
Was https://pypi.org/simple reachable?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 760, in main
    dev=parsed.dev)
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 709, in resolve_packages
    requirements_dir=requirements_dir,
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 692, in resolve
    req_dir=requirements_dir
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/utils.py", line 1405, in resolve_deps
    req_dir=req_dir,
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/utils.py", line 1110, in actually_resolve_deps
    resolver.resolve()
  File "/Users/anthony/.local/lib/python3.8/site-packages/pipenv/utils.py", line 835, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: Could not find a version that matches tensorflow (from -r /var/folders/28/2sy26r512hq5jdpx18q4ycjw0000gn/T/pipenvt0ayzww9requirements/pipenv-_mec4y4u-constraints.txt (line 3))
No versions found
Was https://pypi.org/simple reachable?
```

</details>

**Comment by Kurt-von-Laven** [comment]
Oh, this is totally unrelated to my issue installing prospector in that case, and I suspect also to tensorflow actually. Are you able to `curl https://pypi.org/simple` or install any package whatsoever with `pipenv` on Mac OS X? What resolved the issue for you on Linux?

**Comment by Anthonyive** [comment]
@Kurt-von-Laven Did you miss a slash? I can access `curl https://pypi.org/simple/` and I can also install packages like `requests`.

For linux, I just used the commands that I usually use, like `Pipenv install` but with the `--pre` flag and it works perfectly.

For Mac, I don't know... The only reason I can think of is maybe the installation of `Pipenv`. I believe I installed `Pipenv` with either `pipx` or regular `pip`. I also uninstalled all the packages `pip install --user` installed and clear out the cache in `~/Library/cache/pipenv` and `~/Library/cache/pip`. Still, they didn't work either.

**Comment by Anthonyive** [comment]
https://github.com/tensorflow/tensorflow/issues/50370#issuecomment-908773998

Same issue posted under tensorflow. They helped me solved by installing the wheel. 

```
pipenv install --verbose https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-2.6.0-cp38-cp38-macosx_10_11_x86_64.whl
```

**Comment by matteius** [comment]
@Kurt-von-Laven closing this out, as this was described in the thread linked through above that the issue had to do with `tensorflow` packages for that version were very specific arch/OS wheels and that nothing was resolved for your system:  https://github.com/pypa/pipenv/issues/2619#issuecomment-410137778

Worth noting too that latest versions of pip have the same difficulty:
```
(pipenv-4720) mdavis@matt-VirtualBox:~/shared-projects/pipenv-4720$ pip install tensorflow==2.4
ERROR: Could not find a version that satisfies the requirement tensorflow==2.4 (from versions: 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.8.0rc0)

ERROR: No matching distribution found for tensorflow==2.4

(pipenv-4720) mdavis@matt-VirtualBox:~/shared-projects/pipenv-4720$ pip --version
pip 21.3.1
```
