### ISSUE TITLE
FileNotFoundError: [WinError 3] when using Python3 32-bits

### ISSUE THREAD

**Issue by GustavoPeredo** [pypa/pipenv#4729]
### Issue description

When creating a new python3 environment using ` pipenv --three `, pipenv fails and show the following issue:

```
Using C:/Users/User/AppData/Local/Programs/Python/Python39/python.exe (None) to create virtualenv...
[  ==] Creating virtual environment...FileNotFoundError: [WinError 3] O sistema não pode encontrar o caminho especificad
o: 'C:/Users/User/AppData/Local/Programs/Python/Python39/python.exe'
Failed creating virtual environment

[pipenv.exceptions.VirtualenvCreationException]:
Failed to create virtual environment.
```

That's because I'm using a 32bit Python install (the correct directory should be `  C:/Users/User/AppData/Local/Programs/Python/Python39-32/python.exe `

### Expected result

For pipenv to find the correct directory.

### Actual result

```
Using C:/Users/User/AppData/Local/Programs/Python/Python39/python.exe (None) to create virtualenv...
[  ==] Creating virtual environment...FileNotFoundError: [WinError 3] O sistema não pode encontrar o caminho especificad
o: 'C:/Users/User/AppData/Local/Programs/Python/Python39/python.exe'
Failed creating virtual environment

[pipenv.exceptions.VirtualenvCreationException]:
Failed to create virtual environment.
```

### Steps to replicate

Running ` pipenv --three `

-------------------------------------------------------------------------------
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.5.29'`

Pipenv location: `'C:\\Users\\Work-02\\AppData\\Roaming\\Python\\Python39\\site-packages\\pipenv'`

Python location: `'C:\\Users\\Work-02\\AppData\\Local\\Programs\\Python\\Python39-32\\python.exe'`

Python installations found:

Traceback (most recent call last):
  File "C:\Users\Work-02\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Work-02\AppData\Local\Programs\Python\Python39-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Work-02\AppData\Roaming\Python\Python39\site-packages\pipenv\__main__.py", line 5, in <module>
    cli()
  File "C:\Users\Work-02\AppData\Roaming\Python\Python39\site-packages\pipenv\vendor\click\core.py", line 829, in __call
__
    return self.main(*args, **kwargs)
  File "C:\Users\Work-02\AppData\Roaming\Python\Python39\site-packages\pipenv\vendor\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Work-02\AppData\Roaming\Python\Python39\site-packages\pipenv\vendor\click\core.py", line 1236, in invok
e
    return Command.invoke(self, ctx)
  File "C:\Users\Work-02\AppData\Roaming\Python\Python39\site-packages\pipenv\vendor\click\core.py", line 1066, in invok
e
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Work-02\AppData\Roaming\Python\Python39\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Work-02\AppData\Roaming\Python\Python39\site-packages\pipenv\vendor\click\decorators.py", line 73, in n
ew_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\Work-02\AppData\Roaming\Python\Python39\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Work-02\AppData\Roaming\Python\Python39\site-packages\pipenv\vendor\click\decorators.py", line 21, in n
ew_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\Work-02\AppData\Roaming\Python\Python39\site-packages\pipenv\cli\command.py", line 140, in cli
    get_pipenv_diagnostics()
  File "C:\Users\Work-02\AppData\Roaming\Python\Python39\site-packages\pipenv\help.py", line 33, in get_pipenv_diagnosti
cs
    python_paths = finder.find_all_python_versions()
  File "C:\Users\Work-02\AppData\Roaming\Python\Python39\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line
 328, in find_all_python_versions
    path_list = sorted(versions, key=version_sort, reverse=True)
AttributeError: 'NoneType' object has no attribute 'version_sort'

**Comment by matteius** [comment]
@GustavoPeredo Could you please recheck with `pipenv==2022.1.8` version and if that also fails re-check with main branch?  Thanks!
