### ISSUE TITLE
Cannot install orjson

### ISSUE THREAD

**Issue by rittneje** [pypa/pipenv#4767]
I'm running pipenv 2021.5.29 on macos 11.4.

If I install `orjson` for some reason it is trying to build from scratch instead of using the pre-built wheel, and then fails.

```
$ pipenv install orjson
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Creating a Pipfile for this project...
Installing orjson...
Adding orjson to Pipfile's [packages]...
✔ Installation Succeeded 
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
ERROR:pip.subprocessor:Command errored out with exit status 1:
 command: /private/tmp/platform-venv/bin/python3.9 /private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/notpip install --ignore-installed --no-user --prefix /private/var/folders/kf/kr7_s3xx0l12zbj3jrn082hmzy5gvy/T/pip-build-env-atks4vvh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=0.11.2,<0.12'
     cwd: None
Complete output (57 lines):
Collecting maturin<0.12,>=0.11.2
  Downloading maturin-0.11.2.tar.gz (109 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting toml~=0.10.0
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Building wheels for collected packages: maturin
  Building wheel for maturin (PEP 517): started
  Building wheel for maturin (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /private/tmp/platform-venv/bin/python3.9 /private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py build_wheel /var/folders/kf/kr7_s3xx0l12zbj3jrn082hmzy5gvy/T/tmpobz8ln69
       cwd: /private/var/folders/kf/kr7_s3xx0l12zbj3jrn082hmzy5gvy/T/pip-install-3vscyn1i/maturin
  Complete output (36 lines):
  running bdist_wheel
  running build
  installing to build/bdist.macosx-11-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/pep517/_in_process.py", line 181, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/kf/kr7_s3xx0l12zbj3jrn082hmzy5gvy/T/pip-build-env-ib69zt39/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 216, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/kf/kr7_s3xx0l12zbj3jrn082hmzy5gvy/T/pip-build-env-ib69zt39/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/kf/kr7_s3xx0l12zbj3jrn082hmzy5gvy/T/pip-build-env-ib69zt39/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 106, in <module>
      setup(
    File "/private/var/folders/kf/kr7_s3xx0l12zbj3jrn082hmzy5gvy/T/pip-build-env-ib69zt39/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/kf/kr7_s3xx0l12zbj3jrn082hmzy5gvy/T/pip-build-env-ib69zt39/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 335, in run
      self.run_command('install')
    File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 58, in run
      raise RuntimeError(
  RuntimeError: cargo not found in PATH. Please install rust (https://www.rust-lang.org/tools/install) and try again
  ----------------------------------------
  ERROR: Failed building wheel for maturin
Failed to build maturin
ERROR: Could not build wheels for maturin which use PEP 517 and cannot be installed directly
----------------------------------------
Traceback (most recent call last):
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/utils.py", line 1397, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/utils.py", line 1110, in actually_resolve_deps
    resolver.resolve()
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/utils.py", line 825, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/piptools/resolver.py", line 268, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/piptools/resolver.py", line 383, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 229, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 350, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 306, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 339, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 287, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 66, in _setup_isolation
    self.req.build_env.install_requirements(
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/build_env.py", line 202, in install_requirements
    call_subprocess(args, spinner=spinner)
  File "/private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pipenv.patched.notpip._internal.exceptions.InstallationError: Command errored out with exit status 1: /private/tmp/platform-venv/bin/python3.9 /private/tmp/platform-venv/lib/python3.9/site-packages/pipenv/patched/notpip install --ignore-installed --no-user --prefix /private/var/folders/kf/kr7_s3xx0l12zbj3jrn082hmzy5gvy/T/pip-build-env-atks4vvh/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'maturin>=0.11.2,<0.12' Check the logs for full command output
```

However, installing via `pip` works perfectly fine.

```
$ pip3 install orjson
Collecting orjson
  Downloading orjson-3.6.2-cp39-cp39-macosx_10_9_x86_64.macosx_11_0_arm64.macosx_10_9_universal2.whl (434 kB)
     |████████████████████████████████| 434 kB 2.7 MB/s 
Installing collected packages: orjson
Successfully installed orjson-3.6.2
```

**Comment by rittneje** [comment]
The surprising answer is here. https://github.com/pypa/pipenv/issues/4739#issuecomment-881847777

For some reason you have to set `SYSTEM_VERSION_COMPAT=1` in order for this to work with pipenv. :/
