### ISSUE TITLE
Certain numpy version constraints leads to crash with cryptic error

### ISSUE THREAD

**Issue by Germandrummer92** [pypa/pipenv#4803]
### Issue description

When constraining numpy to the following and running pipenv install the locking fails with a cryptic error

Pipfile:

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
numpy= ">=1.18.2,<1.20.1"

[requires]
python_version = "3.8"
```

the following pipfile works (but is located in a subdependency for me):

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
numpy= ">=1.18.2,<1.20"

[requires]
python_version = "3.8"
```

### Expected result

pipenv install completes succesfully

### Actual result

actual error output (username redacted)

```
ERROR:pip.subprocessor:Command errored out with exit status 1:
 command: [...].local/share/virtualenvs/reproduce_pipenv-41i3Pkp5/bin/python /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/notpip install --ignore-installed --no-user --prefix /private/var/folders/kx/sv3rr52s1lz56tw13ht8961m0000gn/T/pip-build-env-qowi68e0/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.python.org/simple --trusted-host gitlab.understand.ai -- 'setuptools<49.2.0' 'wheel<=0.35.1' 'Cython>=0.29.21,<3.0'
     cwd: None
Complete output (20 lines):
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/notpip/__main__.py", line 18, in <module>
    from pipenv.patched.notpip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/__init__.py", line 23, in <module>
    from pipenv.vendor.vistir.compat import ResourceWarning, fs_str
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/vendor/vistir/__init__.py", line 4, in <module>
    from .compat import (
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/vendor/vistir/compat.py", line 202, in <module>
    IS_TYPE_CHECKING = os.environ.get("MYPY_RUNNING", is_type_checking())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/vendor/vistir/compat.py", line 196, in is_type_checking
    from typing import TYPE_CHECKING
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/typing.py", line 1357, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/typing.py", line 1005, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
----------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/utils.py", line 1397, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/utils.py", line 1110, in actually_resolve_deps
    resolver.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/utils.py", line 825, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 268, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/piptools/resolver.py", line 383, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 229, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 350, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 306, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 339, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/legacy_resolve.py", line 287, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 66, in _setup_isolation
    self.req.build_env.install_requirements(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/build_env.py", line 202, in install_requirements
    call_subprocess(args, spinner=spinner)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/notpip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pipenv.patched.notpip._internal.exceptions.InstallationError: Command errored out with exit status 1: [...]/virtualenvs/reproduce_pipenv-41i3Pkp5/bin/python /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv/patched/notpip install --ignore-installed --no-user --prefix /private/var/folders/kx/sv3rr52s1lz56tw13ht8961m0000gn/T/pip-build-env-qowi68e0/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.python.org/simple --- 'setuptools<49.2.0' 'wheel<=0.35.1' 'Cython>=0.29.21,<3.0' Check the logs for full command output.
```

### Steps to replicate

See also my repo to reproduce: 
https://github.com/Germandrummer92/reproduce_pipenv

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.5.29'`

Pipenv location: `'/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipenv'`

Python location: `'/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8'`

Python installations found:

  - `3.9.7`: `/usr/local/bin/python3`
  - `3.9.7`: `/usr/local/bin/python3.9`
  - `3.8.12`: `/usr/local/opt/python@3.8/bin/python3`
  - `3.8.12`: `/usr/local/opt/python@3.8/bin/python3.8`
  - `3.8.11`: `/Applications/miniconda3/envs/reproduce_pipenv/bin/python3`
  - `3.8.11`: `/Applications/miniconda3/envs/reproduce_pipenv/bin/python3.8`
  - `3.8.9`: `/usr/bin/python3`
  - `3.8.0`: `/Library/Frameworks/Python.framework/Versions/3.8/bin/python3`
  - `3.8.0`: `/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '20.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT '
                     '2021; root:xnu-7195.141.6~3/RELEASE_X86_64',
 'python_full_version': '3.8.0',
 'python_version': '3.8',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `__CFBundleIdentifier`
  - `SHELL`
  - `TERM`
  - `USER`
  - `TMPDIR`
  - `COMMAND_MODE`
  - `TERMINAL_EMULATOR`
  - `LOGIN_SHELL`
  - `__INTELLIJ_COMMAND_HISTFILE__`
  - `SSH_AUTH_SOCK`
  - `XPC_FLAGS`
  - `TERM_SESSION_ID`
  - `__CF_USER_TEXT_ENCODING`
  - `LOGNAME`
  - `XPC_SERVICE_NAME`
  - `HOME`
  - `SHLVL`
  - `PWD`
  - `OLDPWD`
  - `P9K_TTY`
  - `_P9K_TTY`
  - `LC_CTYPE`
  - `ZSH`
  - `LDFLAGS`
  - `PKG_CONFIG_PATH`
  - `PAGER`
  - `LESS`
  - `LSCOLORS`
  - `P9K_SSH`
  - `CLOUDSDK_PYTHON`
  - `INTERNAL_PYPI_TOKEN`
  - `PYPI_TOKEN_OLD`
  - `GITLAB_TOKEN`
  - `GITLAB_TOKEN_2`
  - `KEYCLOAK_USERNAME`
  - `KEYCLOAK_PASSWORD`
  - `WANDB_API_KEY`
  - `PYTHONIOENCODING`
  - `CONDA_EXE`
  - `_CE_M`
  - `_CE_CONDA`
  - `CONDA_PYTHON_EXE`
  - `CONDA_SHLVL`
  - `CONDA_PREFIX`
  - `CONDA_DEFAULT_ENV`
  - `CONDA_PROMPT_MODIFIER`
  - `CONDA_PREFIX_1`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv‚Äìspecific environment variables:

Debug‚Äìspecific environment variables:

  - `PATH`: `/usr/local/sbin:/Applications/miniconda3/envs/reproduce_pipenv/bin:/Applications/miniconda3/condabin:/Users/ddraper/google-cloud-sdk/bin:/Users/ddraper/bin:/usr/local/opt/python@3.8/bin:/Users/ddraper/.cargo/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin`
  - `SHELL`: `/bin/zsh`
  - `PWD`: `/Users/ddraper/dev/reproduce_pipenv`

---------------------------

Contents of `Pipfile` ('/Users/ddraper/dev/reproduce_pipenv/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
numpy= ">=1.18.2,<1.20.1"

[requires]
python_version = "3.8"

```

Contents of `Pipfile.lock` ('/Users/ddraper/dev/reproduce_pipenv/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "82c09f90b1dfff00c721e75a631fba3e4c57566549408f7c6845a11f94954d8f"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "numpy": {
            "hashes": [
                "sha256:012426a41bc9ab63bb158635aecccc7610e3eff5d31d1eb43bc099debc979d94",
                "sha256:06fab248a088e439402141ea04f0fffb203723148f6ee791e9c75b3e9e82f080",
                "sha256:0eef32ca3132a48e43f6a0f5a82cb508f22ce5a3d6f67a8329c81c8e226d3f6e",
                "sha256:1ded4fce9cfaaf24e7a0ab51b7a87be9038ea1ace7f34b841fe3b6894c721d1c",
                "sha256:2e55195bc1c6b705bfd8ad6f288b38b11b1af32f3c8289d6c50d47f950c12e76",
                "sha256:2ea52bd92ab9f768cc64a4c3ef8f4b2580a17af0a5436f6126b08efbd1838371",
                "sha256:36674959eed6957e61f11c912f71e78857a8d0604171dfd9ce9ad5cbf41c511c",
                "sha256:384ec0463d1c2671170901994aeb6dce126de0a95ccc3976c43b0038a37329c2",
                "sha256:39b70c19ec771805081578cc936bbe95336798b7edf4732ed102e7a43ec5c07a",
                "sha256:400580cbd3cff6ffa6293df2278c75aef2d58d8d93d3c5614cd67981dae68ceb",
                "sha256:43d4c81d5ffdff6bae58d66a3cd7f54a7acd9a0e7b18d97abb255defc09e3140",
                "sha256:50a4a0ad0111cc1b71fa32dedd05fa239f7fb5a43a40663269bb5dc7877cfd28",
                "sha256:603aa0706be710eea8884af807b1b3bc9fb2e49b9f4da439e76000f3b3c6ff0f",
                "sha256:6149a185cece5ee78d1d196938b2a8f9d09f5a5ebfbba66969302a778d5ddd1d",
                "sha256:759e4095edc3c1b3ac031f34d9459fa781777a93ccc633a472a5468587a190ff",
                "sha256:7fb43004bce0ca31d8f13a6eb5e943fa73371381e53f7074ed21a4cb786c32f8",
                "sha256:811daee36a58dc79cf3d8bdd4a490e4277d0e4b7d103a001a4e73ddb48e7e6aa",
                "sha256:8b5e972b43c8fc27d56550b4120fe6257fdc15f9301914380b27f74856299fea",
                "sha256:99abf4f353c3d1a0c7a5f27699482c987cf663b1eac20db59b8c7b061eabd7fc",
                "sha256:a0d53e51a6cb6f0d9082decb7a4cb6dfb33055308c4c44f53103c073f649af73",
                "sha256:a12ff4c8ddfee61f90a1633a4c4afd3f7bcb32b11c52026c92a12e1325922d0d",
                "sha256:a4646724fba402aa7504cd48b4b50e783296b5e10a524c7a6da62e4a8ac9698d",
                "sha256:a76f502430dd98d7546e1ea2250a7360c065a5fdea52b2dffe8ae7180909b6f4",
                "sha256:a9d17f2be3b427fbb2bce61e596cf555d6f8a56c222bd2ca148baeeb5e5c783c",
                "sha256:ab83f24d5c52d60dbc8cd0528759532736b56db58adaa7b5f1f76ad551416a1e",
                "sha256:aeb9ed923be74e659984e321f609b9ba54a48354bfd168d21a2b072ed1e833ea",
                "sha256:c843b3f50d1ab7361ca4f0b3639bf691569493a56808a0b0c54a051d260b7dbd",
                "sha256:cae865b1cae1ec2663d8ea56ef6ff185bad091a5e33ebbadd98de2cfa3fa668f",
                "sha256:cc6bd4fd593cb261332568485e20a0712883cf631f6f5e8e86a52caa8b2b50ff",
                "sha256:cf2402002d3d9f91c8b01e66fbb436a4ed01c6498fffed0e4c7566da1d40ee1e",
                "sha256:d051ec1c64b85ecc69531e1137bb9751c6830772ee5c1c426dbcfe98ef5788d7",
                "sha256:d6631f2e867676b13026e2846180e2c13c1e11289d67da08d71cacb2cd93d4aa",
                "sha256:dbd18bcf4889b720ba13a27ec2f2aac1981bd41203b3a3b27ba7a33f88ae4827",
                "sha256:df609c82f18c5b9f6cb97271f03315ff0dbe481a2a02e56aeb1b1a985ce38e60"
            ],
            "index": "pypi",
            "version": "==1.19.5"
        }
    },
    "develop": {}
}

```
</details>

**Comment by matteius** [comment]
Hey @Germandrummer92  -- I just tried to replicate your issue but was unsuccessful.  I used only your Pipfile and regenerated the lock file from that (which I think should be sufficient).  

```
bash-3.2$ pipenv lock
Creating a virtualenv for this project...
Pipfile: /Users/mdavis/Projects/test-4888/Pipfile
Using /usr/bin/python3 (3.8.9) to create virtualenv...
⠦ Creating virtual environment...created virtual environment CPython3.8.9.final.0-64 in 487ms
  creator CPython3macOsFramework(dest=/Users/mdavis/.virtualenvs/test-4888-gznbV4-b, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/mdavis/Library/Application Support/virtualenv)
    added seed packages: pip==21.3.1, setuptools==58.3.0, wheel==0.37.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/mdavis/.virtualenvs/test-4888-gznbV4-b
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Updated Pipfile.lock (b0aa13)!
bash-3.2$ pipenv sync
Installing dependencies from Pipfile.lock (b0aa13)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:01:30
All dependencies are now up-to-date!
bash-3.2$ pip freeze
numpy==1.20.0
```
same version as you pipenv, version 2021.5.29

**Comment by Germandrummer92** [comment]
Hmm, I still can produce it with the same virtualenv i was using. But I suspect this has to do with some weird dependency conflict in that specific virtualenv, since I also cannot reproduce it in a fresh venv with that specific pipenv + pip version installed.

So I will close this, thanks!
