### ISSUE TITLE
Pipenv cannot correctly evaluate `extras_require`

### ISSUE THREAD

**Issue by FlickerSoul** [pypa/pipenv#4822]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

`extras_require` written as dict comprehension cannot be parsed correctly. 

When I was trying to install [networkx](https://github.com/networkx/networkx.git) from the source by using 

```bash
pipenv install -e git+https://github.com/networkx/networkx.git@v2.6#egg=networkx
```

, Pipenv gives me an error and it looks like that it has problem parsing the following `extras_require` field

```python
extras_require = {
    dep: parse_requirements_file("requirements/" + dep + ".txt")
    for dep in ["default", "developer", "doc", "extra", "test"]
}
```

### Expected result

Install without without error.

### Actual result

<details><summary>An error is shown.</summary>

```
❯ pipenv install -e git+https://github.com/networkx/networkx.git@v2.6#egg=networkx --verbose
Using python: None
Path to python: /Users/flicker_soul/.pyenv/versions/3.10.0/bin/python3
Creating a virtualenv for this project...
Pipfile: /Users/flicker_soul/Documents/GrapheryStuff/test/Pipfile
Using /Users/flicker_soul/.pyenv/versions/3.10.0/bin/python3 (3.10.0) to create virtualenv...
⠴ Creating virtual environment...created virtual environment CPython3.10.0.final.0-64 in 264ms
  creator CPython3Posix(dest=/Users/flicker_soul/.local/share/virtualenvs/test-endPb7fl, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/flicker_soul/Library/Application Support/virtualenv)
    added seed packages: pip==21.1.2, setuptools==57.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/flicker_soul/.local/share/virtualenvs/test-endPb7fl
Creating a Pipfile for this project...
Installing -e git+https://github.com/networkx/networkx.git@v2.6#egg=networkx...
Installing package: -e git+https://github.com/networkx/networkx.git@v2.6#egg=networkx
Writing supplied requirement line to temporary file: '-e git+https://github.com/networkx/networkx.git@v2.6#egg=networkx'
Installing 'networkx'
$ ['/Users/flicker_soul/.local/share/virtualenvs/test-endPb7fl/bin/pip', 'install', '--verbose', '--upgrade', '--exists-action=i', '-r', '/var/folders/qd/8hb2ng2s2jb5bmr8g8cwswjw0000gn/T/pipenv-lf7gxwyd-requirements/pipenv-2easr8oo-requirement.txt', '-i', 'https://pypi.org/simple']
Using source directory: '/Users/flicker_soul/.local/share/virtualenvs/test-endPb7fl/src'
Adding networkx to Pipfile's [packages]...
✔ Installation Succeeded
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
⠸ Locking...Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 764, in <module>
✘ Locking Failed!
    main()
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1397, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1107, in actually_resolve_deps
    resolver = Resolver.create(
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 662, in create
    constraints, skipped, index_lookup, markers_lookup = cls.get_metadata(
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 462, in get_metadata
    constraint_update, lockfile_update = cls.get_deps_from_req(
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 541, in get_deps_from_req
    req_list, lockfile = get_vcs_deps(reqs=[req])
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1893, in get_vcs_deps
    with temp_path(), locked_repository(requirement) as repo:
  File "/Users/flicker_soul/.pyenv/versions/3.10.0/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 2049, in locked_repository
    with requirement.req.locked_vcs_repo(src_dir=src_dir) as repo:
  File "/Users/flicker_soul/.pyenv/versions/3.10.0/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2211, in locked_vcs_repo
    self._parsed_line.vcsrepo = vcsrepo
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 903, in vcsrepo
    setupinfo = SetupInfo.create(
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1988, in create
    created.get_initial_info()
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1817, in get_initial_info
    self.update_from_dict(self.parse_setup_py())
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1515, in update_from_dict
    for section in set(list(extras_require.keys())) - set(list(self.extras.keys())):
AttributeError: 'DictComp' object has no attribute 'keys'. Did you mean: 'key'?
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1397, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1107, in actually_resolve_deps
    resolver = Resolver.create(
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 662, in create
    constraints, skipped, index_lookup, markers_lookup = cls.get_metadata(
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 462, in get_metadata
    constraint_update, lockfile_update = cls.get_deps_from_req(
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 541, in get_deps_from_req
    req_list, lockfile = get_vcs_deps(reqs=[req])
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1893, in get_vcs_deps
    with temp_path(), locked_repository(requirement) as repo:
  File "/Users/flicker_soul/.pyenv/versions/3.10.0/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 2049, in locked_repository
    with requirement.req.locked_vcs_repo(src_dir=src_dir) as repo:
  File "/Users/flicker_soul/.pyenv/versions/3.10.0/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2211, in locked_vcs_repo
    self._parsed_line.vcsrepo = vcsrepo
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 903, in vcsrepo
    setupinfo = SetupInfo.create(
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1988, in create
    created.get_initial_info()
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1817, in get_initial_info
    self.update_from_dict(self.parse_setup_py())
  File "/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv/vendor/requirementslib/models/setup_info.py", line 1515, in update_from_dict
    for section in set(list(extras_require.keys())) - set(list(self.extras.keys())):
AttributeError: 'DictComp' object has no attribute 'keys'. Did you mean: 'key'?
```

</details>

It looks like the `extras_require` in the `setup.py` is parsed as `ast.DictComp` instead of a dictionary. 

```python
extras_require = {
    dep: parse_requirements_file("requirements/" + dep + ".txt")
    for dep in ["default", "developer", "doc", "extra", "test"]
}
```

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

* create a new folder 
* run `pipenv install -e git+https://github.com/networkx/networkx.git@v2.6#egg=networkx --verbose`
* an error is shown 

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.5.29'`

Pipenv location: `'/usr/local/Cellar/pipenv/2021.5.29_1/libexec/lib/python3.10/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2021.5.29_1/libexec/bin/python3.10'`

Python installations found:

  - `3.10.0`: `/Users/flicker_soul/.pyenv/versions/3.10.0/bin/python3`
  - `3.9.7`: `/usr/local/bin/python3`
  - `3.9.7`: `/usr/local/bin/python3.9`
  - `3.9.5`: `/Users/flicker_soul/.pyenv/versions/3.9.5/bin/python3`
  - `3.8.9`: `/usr/bin/python3`
  - `3.8.7`: `/Users/flicker_soul/.pyenv/versions/3.8.7/bin/python3`
  - `3.6.9`: `/Users/flicker_soul/.pyenv/versions/pypy3.6-7.3.0/bin/pypy3`
  - `2.7.18`: `/Users/flicker_soul/.pyenv/versions/2.7.18/bin/python2`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '21.1.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT '
                     '2021; root:xnu-8019.41.5~1/RELEASE_X86_64',
 'python_full_version': '3.10.0',
 'python_version': '3.10',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `NVM_INC`
  - `AUTOJUMP_ERROR_PATH`
  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `NVM_CD_FLAGS`
  - `AUTOJUMP_SOURCED`
  - `TERM`
  - `SHELL`
  - `CLICOLOR`
  - `TMPDIR`
  - `GRADLE_HOME`
  - `TERM_PROGRAM_VERSION`
  - `GVM_ROOT`
  - `TERM_SESSION_ID`
  - `SDKMAN_PLATFORM`
  - `JENV_FORCEJAVAHOME`
  - `ZSH`
  - `PIPENV_IGNORE_VIRTUALENVS`
  - `NVM_DIR`
  - `USER`
  - `COMMAND_MODE`
  - `SDKMAN_CANDIDATES_API`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `PAGER`
  - `LSCOLORS`
  - `_`
  - `LaunchInstanceID`
  - `__CFBundleIdentifier`
  - `GVM_VERSION`
  - `JENV_LOADED`
  - `PWD`
  - `JAVA_HOME`
  - `P9K_SSH`
  - `P9K_TTY`
  - `LANG`
  - `SDKMAN_VERSION`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `JENV_FORCEJDKHOME`
  - `XPC_SERVICE_NAME`
  - `GPG_TTY`
  - `PYENV_SHELL`
  - `JDK_HOME`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `LC_TERMINAL_VERSION`
  - `LS_OPTIONS`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `SDKMAN_DIR`
  - `JENV_SHELL`
  - `NVM_BIN`
  - `SDKMAN_CANDIDATES_DIR`
  - `LC_TERMINAL`
  - `SECURITYSESSIONID`
  - `SQLITE_EXEMPT_PATH_FROM_VNODE_GUARDS`
  - `GVM_PATH_BACKUP`
  - `COLORTERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_IGNORE_VIRTUALENVS`: `1`

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2021.5.29_1/libexec/tools:/Users/flicker_soul/.gvm/bin:/Users/flicker_soul/.pyenv/shims:/Users/flicker_soul/.pyenv/bin:/usr/local/Cellar:/Users/flicker_soul/.sdkman/candidates/gradle/current/bin:/Users/flicker_soul/.nvm/versions/node/v14.18.0/bin:/Users/flicker_soul/.jenv/shims:/Users/flicker_soul/.jenv/bin:/Users/flicker_soul/.oh-my-zsh/plugins/git-open:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/usr/local/share/dotnet:/Applications/Keybase.app/Contents/SharedSupport/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/flicker_soul/.local/bin:/usr/local/opt/tcl-tk/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/flicker_soul/Documents/GrapheryStuff/test`

---------------------------

Contents of `Pipfile` ('/Users/flicker_soul/Documents/GrapheryStuff/test/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
networkx = {editable = true, ref = "v2.6", git = "https://github.com/networkx/networkx.git"}

[dev-packages]

[requires]
python_version = "3.10"

```

</details>

**Comment by frostming** [comment]
Fixed on v2021.11.5
