### ISSUE TITLE
pipenv shell throws TypeError in 2021.11.5

### ISSUE THREAD

**Issue by eNcacz** [pypa/pipenv#4832]
### Issue description

`pipenv shell` command throws TypeError exception

### Expected result

It should open shell without exceptions.

### Actual result

```
$ pipenv shell
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/cli/command.py", line 419, in shell
    do_shell(
  File "/usr/local/lib/python3.9/site-packages/pipenv/core.py", line 2309, in do_shell
    shell = choose_shell()
TypeError: choose_shell() missing 1 required positional argument: 'project'

```

### Steps to replicate

```
$ mkdir test
$ cd test
$ pipenv --python 3.9
$ pipenv shell
```
-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.11.5'`

Pipenv location: `'/usr/local/lib/python3.9/site-packages/pipenv'`

Python location: `'/usr/local/bin/python'`

Python installations found:

  - `3.9.7`: `/usr/local/bin/python`
  - `3.9.7`: `/usr/local/bin/python3.9`
  - `3.9.7`: `/usr/local/bin/python3`
  - `3.9.2`: `/usr/bin/python3.9`
  - `3.9.2`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.10.61-gentoo-x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Mon Sep 6 20:25:24 CEST 2021',
 'python_full_version': '3.9.7',
 'python_version': '3.9',
 'sys_platform': 'linux'}
```

System environment variables:

  - `HOSTNAME`
  - `PYTHON_VERSION`
  - `PWD`
  - `PYTHON_SETUPTOOLS_VERSION`
  - `HOME`
  - `LANG`
  - `GPG_KEY`
  - `TERM`
  - `SHLVL`
  - `PYTHON_PIP_VERSION`
  - `PYTHON_GET_PIP_SHA256`
  - `PYTHON_GET_PIP_URL`
  - `PATH`
  - `_`
  - `OLDPWD`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/tmp/test`

---------------------------

Contents of `Pipfile` ('/tmp/test/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.9"

```

</details>

**Comment by eNcacz** [comment]
Seems like as it is already fixed in v2021.11.5.post0, by commit e3682715

Sorry for disturbing,
