### ISSUE TITLE
2021.5.29: "pipenv run" raised TypeError in pipenv.core.do_run_posix()

### ISSUE THREAD

**Issue by jedie** [pypa/pipenv#4850]
```
# pipenv run pip freeze
Loading .env environment variables...
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/cli/command.py", line 413, in run
    do_run(
  File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 2495, in do_run
    run_fn(*run_args, **run_kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 2442, in do_run_posix
    os.execve(
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.5.29'`

Pipenv location: `'/usr/local/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/local/bin/python'`

Python installations found:

  - `3.8.12`: `/usr/local/bin/python3`
  - `3.8.12`: `/usr/local/bin/python3.8`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.12',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.0-89-generic',
 'platform_system': 'Linux',
 'platform_version': '#100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021',
 'python_full_version': '3.8.12',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

**Comment by jedie** [comment]
I figured our that it depends if Python v2 is installed or not!

**Comment by jedie** [comment]
Same error happens with python 3.8 and 3.9 installed:

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.11.9'`

Pipenv location: `'/usr/local/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/local/bin/python'`

Python installations found:

  - `3.9.2`: `/usr/bin/python3`
  - `3.9.2`: `/usr/bin/python3.9`
  - `3.8.12`: `/usr/local/bin/python`
  - `3.8.12`: `/usr/local/bin/python3`
  - `3.8.12`: `/usr/local/bin/python3.8`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.12',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.0-89-generic',
 'platform_system': 'Linux',
 'platform_version': '#100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021',
 'python_full_version': '3.8.12',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

**Comment by frostming** [comment]
Can't reproduce here, can you help dig it deeper? What args are passed to the `os.execve`

**Comment by jedie** [comment]
I hacked into do_run_posix() code and printed the args for os.execve(): There is not "None" anywhere. It looks totally ok.
Very strange.

**Comment by jedie** [comment]
Can reproduce it with 2021.11.23

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.11.23'`

Pipenv location: `'/home/jens/.local/lib/python3.8/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.9.5`: `/usr/bin/python3.9`
  - `3.8.10`: `/usr/bin/python3`
  - `3.8.10`: `/usr/bin/python3.8`
  - `2.7.18`: `/usr/bin/python`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.10',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.0-91-generic',
 'platform_system': 'Linux',
 'platform_version': '#102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021',
 'python_full_version': '3.8.10',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `SESSION_MANAGER`
  - `WINDOWID`
  - `QT_ACCESSIBILITY`
  - `COLORTERM`
  - `XDG_CONFIG_DIRS`
  - `XDG_SESSION_PATH`
  - `LANGUAGE`
  - `MANDATORY_PATH`
  - `LC_ADDRESS`
  - `LC_NAME`
  - `SSH_AUTH_SOCK`
  - `DESKTOP_SESSION`
  - `LC_MONETARY`
  - `SSH_AGENT_PID`
  - `GTK_MODULES`
  - `XDG_SEAT`
  - `MATE_DESKTOP_SESSION_ID`
  - `PWD`
  - `GSETTINGS_SCHEMA_DIR`
  - `LOGNAME`
  - `XDG_SESSION_DESKTOP`
  - `QT_QPA_PLATFORMTHEME`
  - `XDG_SESSION_TYPE`
  - `GPG_AGENT_INFO`
  - `XAUTHORITY`
  - `XDG_GREETER_DATA_DIR`
  - `GDM_LANG`
  - `HOME`
  - `LC_PAPER`
  - `LANG`
  - `LS_COLORS`
  - `KICAD_PATH`
  - `XDG_CURRENT_DESKTOP`
  - `VTE_VERSION`
  - `XDG_SEAT_PATH`
  - `LESSCLOSE`
  - `XDG_SESSION_CLASS`
  - `TERM`
  - `LC_IDENTIFICATION`
  - `GTK_OVERLAY_SCROLLING`
  - `DEFAULTS_PATH`
  - `KIGITHUB`
  - `LESSOPEN`
  - `USER`
  - `DISPLAY`
  - `SHLVL`
  - `LC_TELEPHONE`
  - `LC_MEASUREMENT`
  - `XDG_VTNR`
  - `UBUNTU_MENUPROXY`
  - `XDG_SESSION_ID`
  - `PAPERSIZE`
  - `XDG_RUNTIME_DIR`
  - `COMPIZ_CONFIG_PROFILE`
  - `LC_TIME`
  - `QT_AUTO_SCREEN_SCALE_FACTOR`
  - `XDG_DATA_DIRS`
  - `PATH`
  - `GDMSESSION`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `QT_SCALE_FACTOR`
  - `LC_NUMERIC`
  - `_`
  - `OLDPWD`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:


Debug–specific environment variables:

  - `PATH`: `/home/jens/.local/bin:/home/jens/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `de_DE.UTF-8`
  - `PWD`: `/home/jens/xxx`

**Comment by matteius** [comment]
@jedie you mention it appears depending if python2 is installed or not ... does that mean the issue does not appear when python2 is not installed?  My guess would be something system level is referencing dependency into python2 when it should be using python3 dependencies.

**Comment by danielhartnell** [comment]
I ran into a similar issue and I think I was able to reproduce it by providing an invalid dotenv file (I'm assuming this is an invalid syntax). I wasn't able to change the outcome with Python2 but I can confirm that `2021.11.23` returns this error but `2021.5.29` does not.

Here are the steps to reproduce it with a Docker container running Ubuntu 20.04.3:

```
root@abc6d7cb44d7:/# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
```

Install `2021.5.29`, create `.env` file with content `foo` and run `pipenv run pip freeze`. This is successful.

```
λ docker run -it ubuntu /bin/bash
root@abc6d7cb44d7:/# apt update > /dev/null 2>&1
root@abc6d7cb44d7:/# apt install -y python3 python3-pip > /dev/null 2>&1
root@abc6d7cb44d7:/# pip install pipenv==2021.5.29
Collecting pipenv==2021.5.29
... truncated ...
Installing collected packages: certifi, virtualenv-clone, six, platformdirs, distlib, filelock, virtualenv, pipenv
Successfully installed certifi-2021.10.8 distlib-0.3.4 filelock-3.4.2 pipenv-2021.5.29 platformdirs-2.4.1 six-1.16.0 virtualenv-20.13.0 virtualenv-clone-0.5.7
root@abc6d7cb44d7:/# echo foo > .env
root@abc6d7cb44d7:/# pipenv run pip freeze
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project...
Pipfile: /Pipfile
Using /usr/bin/python3 (3.8.10) to create virtualenv...
⠇ Creating virtual environment...created virtual environment CPython3.8.10.final.0-64 in 524ms
  creator CPython3Posix(dest=/root/.local/share/virtualenvs/-x-v5uFv0, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==21.3.1, setuptools==60.2.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /root/.local/share/virtualenvs/-x-v5uFv0
Creating a Pipfile for this project...
Loading .env environment variables...
root@abc6d7cb44d7:/#
```

Uninstall `2021.5.29` and install `2021.11.23`. Use the same `.env` file. Run `pipenv run pip freeze`. This throws the error trace.

```
root@abc6d7cb44d7:/# pip uninstall pipenv
Found existing installation: pipenv 2021.5.29
Uninstalling pipenv-2021.5.29:
  Would remove:
    /usr/local/bin/pipenv
    /usr/local/bin/pipenv-resolver
    /usr/local/lib/python3.8/dist-packages/pipenv-2021.5.29.dist-info/*
    /usr/local/lib/python3.8/dist-packages/pipenv/*
Proceed (y/n)? y
  Successfully uninstalled pipenv-2021.5.29
root@abc6d7cb44d7:/# pip install pipenv
Collecting pipenv
  Downloading pipenv-2021.11.23-py2.py3-none-any.whl (3.6 MB)
... truncated ...
Successfully installed pipenv-2021.11.23
root@abc6d7cb44d7:/# pipenv run pip freeze
Loading .env environment variables...
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/cli/command.py", line 414, in run
    do_run(
  File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 2500, in do_run
    run_fn(*run_args, **run_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pipenv/core.py", line 2447, in do_run_posix
    os.execve(
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Hopefully that helps and I didn't overlook some difference in the error traces. For what it's worth - this caused an issue for us as well. I'm working on tracking down what may have been wrong in our `.env` file.

Cheers!

**Comment by melvyn-oviavo** [comment]
It struggles with variables without values:

```shell
# set to yes or no
DEBUG
```
python-dotenv ignores these (and doesn't set the variable either).

**Comment by melvyn-oviavo** [comment]
There's an additional bug here: You get to the same point with `pipenv run` if you set PIPENV_DONT_LOAD_ENV=1 in your shell, which I actually need.
Surprisingly, `pipenv shell` works.

**Comment by matteius** [comment]
@melvyn-oviavo Can you help me understand if this is still an issue on latest version or master?

**Comment by melvyn-oviavo** [comment]
@matteius It's not. See: https://github.com/pypa/pipenv/issues/4923

**Comment by matteius** [comment]
Ok thanks, closing this out then.
