### ISSUE TITLE
bash completion broken on LANG=ja_JP.UTF-8

### ISSUE THREAD

**Issue by tsuttsu305** [pypa/pipenv#4860]
### Issue description

If Locale is ja_JP.UTF-8, bash completion broken.
It has been fixed in click 8.0.2.  ( Bash version detection is locale independent. :issue:`1940`)
https://github.com/pallets/click/blob/main/CHANGES.rst#version-802

### Expected result

Bash completion work on not LANG=en environments.

### Actual result

Not work bash completion on not LANG=en environments.

### Steps to replicate
```
$ echo $LANG
ja_JP.UTF-8
$ bash --version
GNU bash, バージョン 5.1.8(1)-release (x86_64-apple-darwin20.3.0)
Copyright (C) 2020 Free Software Foundation, Inc.
ライセンス GPLv3+: GNU GPL バージョン 3 またはそれ以降 <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ bash -c 'echo ${BASH_VERSION}'
5.1.8(1)-release

$ pipenv --version
pipenv, version 2021.11.9

$ eval "$(_PIPENV_COMPLETE=bash_source pipenv)"
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2021.11.9/libexec/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/pipenv/2021.11.9/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pipenv/2021.11.9/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1057, in main
    self._main_shell_completion(extra, prog_name, complete_var)
  File "/usr/local/Cellar/pipenv/2021.11.9/libexec/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1132, in _main_shell_completion
    rv = shell_complete(self, ctx_args, prog_name, complete_var, instruction)
  File "/usr/local/Cellar/pipenv/2021.11.9/libexec/lib/python3.10/site-packages/pipenv/vendor/click/shell_completion.py", line 45, in shell_complete
    echo(comp.source())
  File "/usr/local/Cellar/pipenv/2021.11.9/libexec/lib/python3.10/site-packages/pipenv/vendor/click/shell_completion.py", line 324, in source
    self._check_version()
  File "/usr/local/Cellar/pipenv/2021.11.9/libexec/lib/python3.10/site-packages/pipenv/vendor/click/shell_completion.py", line 319, in _check_version
    raise RuntimeError(
RuntimeError: Couldn't detect Bash version, shell completion is not supported.
```
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.11.9'`

Pipenv location: `'/usr/local/Cellar/pipenv/2021.11.9/libexec/lib/python3.10/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2021.11.9/libexec/bin/python3.10'`

Python installations found:

  - `3.9.7`: `/usr/local/opt/python@3.9/libexec/bin/python`
  - `3.9.7`: `/usr/local/bin/python3`
  - `3.9.7`: `/usr/local/bin/python3.9`
  - `3.9.6`: `/Users/***/.pyenv/versions/3.9.6/bin/python3`
  - `3.9.5`: `/Users/***/.pyenv/versions/3.9.5/bin/python3`
  - `3.9.4`: `/Users/***/.pyenv/versions/3.9.4/bin/python3`
  - `3.9.2`: `/Users/***/.pyenv/versions/3.9.2/bin/python3`
  - `3.8.10`: `/Users/***/.pyenv/versions/3.8.10/bin/python3`
  - `3.8.9`: `/Users/***/.pyenv/versions/3.8.9/bin/python3`
  - `3.8.8`: `/Users/***/.pyenv/versions/3.8.8/bin/python3`
  - `3.8.2`: `/usr/bin/python3`
  - `3.7.10`: `/Users/***/.pyenv/versions/3.7.10/bin/python3`
  - `2.7.16`: `/usr/bin/python`
  - `2.7.16`: `/usr/bin/python2`
  - `2.7.16`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '20.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT '
                     '2021; root:xnu-7195.141.8~1/RELEASE_X86_64',
 'python_full_version': '3.10.0',
 'python_version': '3.10',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `TERM_PROGRAM`
  - `GPT_TTY`
  - `PYENV_ROOT`
  - `TERM`
  - `PIPENV_VERBOSITY`
  - `SHELL`
  - `HISTSIZE`
  - `TMPDIR`
  - `PIPENV_VENV_IN_PROJECT`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `USER`
  - `COMMAND_MODE`
  - `GUILE_LOAD_PATH`
  - `CCACHE_DIR`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `GUILE_LOAD_COMPILED_PATH`
  - `BASH_COMPLETION_COMPAT_DIR`
  - `GUILE_TLS_CERTIFICATE_DIRECTORY`
  - `_`
  - `__CFBundleIdentifier`
  - `PWD`
  - `HOMEBREW_GITHUB_API_TOKEN`
  - `LANG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `ITERM_ORIG_PS1`
  - `XPC_SERVICE_NAME`
  - `HISTCONTROL`
  - `SHLVL`
  - `COLORFGBG`
  - `HOME`
  - `PYENV_SHELL`
  - `LC_TERMINAL_VERSION`
  - `ITERM_PREV_PS1`
  - `ITERM_SESSION_ID`
  - `LOGNAME`
  - `GUILE_SYSTEM_EXTENSIONS_PATH`
  - `USE_CCACHE`
  - `PROMPT_COMMAND`
  - `LC_TERMINAL`
  - `COLORTERM`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_VERBOSITY`: `-1`
 - `PIPENV_VENV_IN_PROJECT`: `1`

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2021.11.9/libexec/tools:/Users/***/.pyenv/shims:/Users/***/.pyenv/bin:/usr/local/opt/libpq/bin:/usr/local/opt/python@3.9/libexec/bin:/usr/local/opt/mysql-client/bin:/usr/local/opt/curl/bin:/usr/local/opt/php@7.4/bin:/usr/local/opt/ccache/libexec:/usr/local/sbin:/usr/local/bin:~/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public`
  - `SHELL`: `/usr/local/bin/bash`
  - `LANG`: `ja_JP.UTF-8`
  - `PWD`: `/Users/***`

---------------------------

</details>

**Comment by tsuttsu305** [comment]
Temporary workaround: `eval "$(LANG=C _PIPENV_COMPLETE=bash_source pipenv)"`
