### ISSUE TITLE
Unable to install bcrypt using the latest pipenv (2021.11.23)

### ISSUE THREAD

**Issue by bqbn** [pypa/pipenv#4892]
### Issue description

Given the following:

```
$ pipenv run python -V
Python 3.10.1

$ pipenv --version
pipenv, version 2021.11.23

$ pipenv run pip --version
pip 21.3.1 from /Users/wezhou/.local/share/virtualenvs/test-MOikZI6O/lib/python3.10/site-packages/pip (python 3.10)
```

and with the following minimal Pipfile,

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
bcrypt = "*"

[requires]
python_version = "3.10"
```

We can't install bcrypt, and as a result, any package that depends on bcrypt.

### Expected result

We should be able to install bcrypt using pipenv.

### Actual result

<details>

<summary>The install fails with the following error:</summary>

```
$ pipenv install -v
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
Reporter.starting()
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.starting()
Reporter.adding_requirement(SpecifierRequirement('bcrypt'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('bcrypt'), None)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 875, in resolve
    results = resolver.resolve(self.constraints, check_supported_wheels=False)
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 341, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/found_candidates.py", line 140, in __bool__
    return any(self)
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/found_candidates.py", line 128, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/found_candidates.py", line 32, in _iter_built
    candidate = func()
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/factory.py", line 204, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/candidates.py", line 298, in __init__
    super().__init__(
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 570, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 60, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/distributions/sdist.py", line 29, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 474, in load_pyproject_toml
    pyproject_toml_data = load_pyproject_toml(
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/pyproject.py", line 82, in load_pyproject_toml
    raise InstallationError(
pipenv.patched.notpip._internal.exceptions.InstallationError: Disabling PEP 517 processing is invalid: project specifies a build backend of setuptools.build_meta in pyproject.toml
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 766, in <module>
    main()
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 760, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 743, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 704, in resolve_packages
    results, resolver = resolve(
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 685, in resolve
    return resolve_deps(
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1370, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 1099, in actually_resolve_deps
    resolver.resolve()
  File "/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv/utils.py", line 877, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of setuptools.build_meta in pyproject.toml
✘ Locking Failed!
```
</details>

### Steps to replicate

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.11.23'`

Pipenv location: `'/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/lib/python3.10/site-packages/pipenv'`

Python location: `'/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/bin/python3.10'`

Python installations found:

  - `3.8.9`: `/usr/bin/python3`
  - `2.7.18`: `/usr/bin/python`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.1',
 'os_name': 'posix',
 'platform_machine': 'arm64',
 'platform_python_implementation': 'CPython',
 'platform_release': '21.1.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT '
                     '2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000',
 'python_full_version': '3.10.1',
 'python_version': '3.10',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `MANPATH`
  - `SHELL`
  - `TERM`
  - `SSH_CLIENT`
  - `TMPDIR`
  - `HOMEBREW_REPOSITORY`
  - `SSH_TTY`
  - `USER`
  - `HOMEBREW_SHELLENV_PREFIX`
  - `HOMEBREW_NO_ANALYTICS`
  - `SSH_AUTH_SOCK`
  - `_`
  - `PWD`
  - `JAVA_HOME`
  - `LANG`
  - `GPG_TTY`
  - `HOME`
  - `SHLVL`
  - `LC_TERMINAL_VERSION`
  - `HOMEBREW_PREFIX`
  - `LOGNAME`
  - `SSH_CONNECTION`
  - `HOMEBREW_CELLAR`
  - `INFOPATH`
  - `LC_TERMINAL`
  - `P4CONFIG`
  - `__CF_USER_TEXT_ENCODING`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/opt/homebrew/Cellar/pipenv/2021.11.23/libexec/tools:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/Users/dummy/bin:/Users/dummy/opt/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/dummy/opt/py-venvs/test`

---------------------------

Contents of `Pipfile` ('/Users/dummy/opt/py-venvs/test/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
bcrypt = "*"

[requires]
python_version = "3.10"

```

</details>

**Comment by matteius** [comment]
Could you try two things to help debug this further?
1.) Try pipenv 2021.05.29 to see if you still get the same error.  If so I suspect it could be related to this:
2.) Check out this report as it seems it could be related:  https://github.com/pyca/cryptography/issues/5773
3.) Are you on an M1 mac?  (I have one too, just curious)

**Comment by matteius** [comment]
Just updating this, I tried the newest version and did not get an issue with that Pipfile on my M1 mac (which matches the reporters computer architecture).  I think this issue can be closed.

```
(test2) bash-3.2$ pipenv install
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Warning: Your Pipfile requires python_version 3.10, but you are using 3.9.9 (/Users/mdavis/./test2/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Installing dependencies from Pipfile.lock (578e9b)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 4/4 — 00:00:04
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
(test2) bash-3.2$ pipenv --version
pipenv, version 2021.11.23
(test2) bash-3.2$ pip freeze
bcrypt==3.2.0
cffi==1.15.0
pycparser==2.21
six==1.16.0
```

**Comment by bqbn** [comment]
Thanks for looking into it, @matteius.

I still have no luck installing bcrypt after trying 1 and 2 above, and yes, I'm on an M1 mac.

For now, I worked around it by running python on the x86_64 architecture (with help of the arch command).

**Comment by matteius** [comment]
@bqbn Then you are just getting a pre-built wheel for that arch so it won't have to compile.   Likely a system dependency issue, and if you already have installed the required packages such that pip can build it--Have you tried to remove your virtualenv and uninstall that python version and rebuild?  pyenv will only get what system dependencies you have installed at the time that it is built, and sometimes it needs to be rebuilt.  In your active project directory `pipenv --rm` and then probably `pyenv uninstall 3.10.1` before trying again.   Other than that, what happens when you try to install it just using pip?
