### ISSUE TITLE
Pipenv run throws iteration error when PIPENV_DONT_LOAD_ENV is set

### ISSUE THREAD

**Issue by melvyn-oviavo** [pypa/pipenv#4923]
### Issue description

When PIPENV_DONT_LOAD_ENV is set in the environment we get the following Traceback:
```
Traceback (most recent call last):
  File "/Users/newemployee/.pyenv/versions/3.8.5/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/Users/newemployee/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/newemployee/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/newemployee/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/newemployee/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/newemployee/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/newemployee/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/newemployee/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/newemployee/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/cli/command.py", line 413, in run
    do_run(
  File "/Users/newemployee/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv/core.py", line 2462, in do_run
    env.update(load_dot_env(project, as_dict=True))
TypeError: 'NoneType' object is not iterable
```
It doesn't matter if there actually is a .env file or not.

### Expected result
Pipenv will run and not try to import variables from .env.

### Actual result

Operation fails.

### Steps to replicate

1. `mkdir test-project && cd test-project`
2. `pipenv install requests`
3. `env PIPENV_DONT_LOAD_ENV=yes pipenv run pip freeze`

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.11.9'`

Pipenv location: `'/Users/newemployee/.pyenv/versions/3.8.5/lib/python3.8/site-packages/pipenv'`

Python location: `'/Users/newemployee/.pyenv/versions/3.8.5/bin/python'`

Python installations found:

  - `3.9.7`: `/usr/local/bin/python3`
  - `3.9.7`: `/usr/local/bin/python3.9`
  - `3.9.4`: `/Users/newemployee/.pyenv/versions/3.9.4/bin/python3`
  - `3.9.1`: `/Users/newemployee/.pyenv/versions/3.9.1/bin/python3`
  - `3.8.10`: `/Users/newemployee/.pyenv/versions/3.8.10/bin/python3`
  - `3.8.7`: `/Users/newemployee/.pyenv/versions/3.8.7/bin/python3`
  - `3.8.5`: `/Users/newemployee/.pyenv/versions/3.8.5/bin/python3`
  - `3.8.5`: `/Users/newemployee/.pyenv/versions/3.8.5/bin/python3`
  - `3.8.5`: `/Users/newemployee/.pyenv/versions/3.8.5/bin/python`
  - `3.8.5`: `/Users/newemployee/.pyenv/versions/3.8.5/bin/python3.8`
  - `3.8.2`: `/usr/bin/python3`
  - `3.7.10`: `/Users/newemployee/.pyenv/versions/3.7.10/bin/python3`
  - `3.7.9`: `/Users/newemployee/.pyenv/versions/3.7.9/bin/python3`
  - `3.6.13`: `/Users/newemployee/.pyenv/versions/3.6.13/bin/python3`
  - `2.7.18`: `/usr/bin/python`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '21.2.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST '
                     '2021; root:xnu-8019.61.5~1/RELEASE_X86_64',
 'python_full_version': '3.8.5',
 'python_version': '3.8',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `NVM_INC`
  - `MANWIDTH`
  - `TERM_PROGRAM`
  - `XDG_DATA_HOME`
  - `NVM_CD_FLAGS`
  - `PYENV_ROOT`
  - `GEM_HOME`
  - `TERM`
  - `SHELL`
  - `TMPDIR`
  - `TERM_PROGRAM_VERSION`
  - `HOMEBREW_AUTO_UPDATE_SECS`
  - `TERM_SESSION_ID`
  - `PYENV_VERSION`
  - `NVM_DIR`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `PYENV_DIR`
  - `PAGER`
  - `WORKON_HOME`
  - `MAIL`
  - `PATH`
  - `LaunchInstanceID`
  - `__CFBundleIdentifier`
  - `PWD`
  - `EDITOR`
  - `LANG`
  - `IPYTHONDIR`
  - `PYENV_HOOK_PATH`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `GPG_TTY`
  - `PYENV_SHELL`
  - `HOME`
  - `SHLVL`
  - `XDG_CONFIG_HOME`
  - `LESS`
  - `LOGNAME`
  - `LC_CTYPE`
  - `NVM_BIN`
  - `GIT_PAGER`
  - `SECURITYSESSIONID`
  - `XAUTHORITY`
  - `__CF_USER_TEXT_ENCODING`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/newemployee/.pyenv/versions/3.8.5/bin:/usr/local/Cellar/pyenv/2.2.0/libexec:/usr/local/Cellar/pyenv/2.2.0/plugins/python-build/bin:/Users/newemployee/.yarn/bin:/Users/newemployee/.config/yarn/global/node_modules/.bin:/Users/newemployee/.nvm/versions/node/v16.13.0/bin:/Users/newemployee/.pyenv/bin:/Users/newemployee/.local/bin:/Users/newemployee/.local/sbin:/usr/lib/ccache:/usr/local/sbin:/usr/local/opt/ruby/bin:/usr/local/opt/node@14/bin:/Users/newemployee/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/opt/openssl/bin:/Users/newemployee/.ebcli-virtual-env/executables:/Users/newemployee/.local/share/gems/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `vim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/newemployee/hg/test-project`

---------------------------

Contents of `Pipfile` ('/Users/newemployee/hg/test-project/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
requests = "*"

[dev-packages]

[requires]
python_version = "3.8"

```

Contents of `Pipfile.lock` ('/Users/newemployee/hg/test-project/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "acbc8c4e7f2f98f1059b2a93d581ef43f4aa0c9741e64e6253adff8e35fbd99e"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "certifi": {
            "hashes": [
                "sha256:78884e7c1d4b00ce3cea67b44566851c4343c120abd683433ce934a68ea58872",
                "sha256:d62a0163eb4c2344ac042ab2bdf75399a71a2d8c7d47eac2e2ee91b9d6339569"
            ],
            "version": "==2021.10.8"
        },
        "charset-normalizer": {
            "hashes": [
                "sha256:876d180e9d7432c5d1dfd4c5d26b72f099d503e8fcc0feb7532c9289be60fcbd",
                "sha256:cb957888737fc0bbcd78e3df769addb41fd1ff8cf950dc9e7ad7793f1bf44455"
            ],
            "markers": "python_version >= '3'",
            "version": "==2.0.10"
        },
        "idna": {
            "hashes": [
                "sha256:84d9dd047ffa80596e0f246e2eab0b391788b0503584e8945f2368256d2735ff",
                "sha256:9d643ff0a55b762d5cdb124b8eaa99c66322e2157b69160bc32796e824360e6d"
            ],
            "markers": "python_version >= '3'",
            "version": "==3.3"
        },
        "requests": {
            "hashes": [
                "sha256:68d7c56fd5a8999887728ef304a6d12edc7be74f1cfa47714fc8b414525c9a61",
                "sha256:f22fa1e554c9ddfd16e6e41ac79759e17be9e492b3587efa038054674760e72d"
            ],
            "index": "pypi",
            "version": "==2.27.1"
        },
        "urllib3": {
            "hashes": [
                "sha256:000ca7f471a233c2251c6c7023ee85305721bfdf18621ebff4fd17a8653427ed",
                "sha256:0e7c33d9a63e7ddfcb86780aac87befc2fbddf46c58dbb487e0855f7ceec283c"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4' and python_version < '4'",
            "version": "==1.26.8"
        }
    },
    "develop": {}
}

```
</details>

**Comment by melvyn-oviavo** [comment]
Was using 2021.11.9 inadvertently. Has been fixed in 2022.1.8.
