### ISSUE TITLE
Using "pipenv install pyqt6" leads to a dependency resolution error with a strange error message.

### ISSUE THREAD

**Issue by chai-script** [pypa/pipenv#4957]
### Issue description

`pipenv install pyqt6` on a fresh environment (in an empty directory), leads to a dependency resolution error, and locking fails. Pipenv warns that dependencies could not be resolved but the error message does not indicate anything wrong.

### Expected result

`pipenv install pyqt6` should install pyqt6 and create the lock file without any errors.

### Actual result

`pipenv install pyqt6` ends with Locking failed due to a dependency resolution error.

```
$ pipenv --verbose install pyqt6

Using python: None
Path to python: /usr/bin/python3
Creating a virtualenv for this project...
Pipfile: /home/pew/workspace/pygui/Pipfile
Using /usr/bin/python3 (3.10.2) to create virtualenv...
⠙ Creating virtual environment...created virtual environment CPython3.10.2.final.0-64 in 534ms
  creator CPython3Posix(dest=/home/pew/.local/share/virtualenvs/pygui-md2qg1x2, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(extra_search_dir=/usr/share/python-wheels,download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/pew/.local/share/virtualenv)
    added seed packages: pip==21.2.3, setuptools==57.4.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/pew/.local/share/virtualenvs/pygui-md2qg1x2
Creating a Pipfile for this project...
Installing pyqt6...
Installing package: pyqt6
Writing supplied requirement line to temporary file: 'pyqt6'
Installing 'pyqt6'
⠹ Installing pyqt6...$ ['/home/pew/.local/share/virtualenvs/pygui-md2qg1x2/bin/pip', 'install', '--verbose', '--upgrade', '--exists-action=i', '-r', '/tmp/pipenv-7u9cy_k6-requirements/pipenv-0qo011t1-requirement.txt', '-i', 'https://pypi.org/simple']
Using source directory: '/home/pew/.local/share/virtualenvs/pygui-md2qg1x2/src'
Adding pyqt6 to Pipfile's [packages]...
✔ Installation Succeeded 
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
⠴ Locking...
✘ Locking Failed! 
                          ROUND 1                           
Current constraints:
  pyqt6 (from -r /tmp/pipenv1_lx94l8requirements/pipenv-5hrlb8op-constraints.txt (line 2))

Finding the best candidates:
  found candidate pyqt6==6.2.3 (constraint was <any>)

Finding secondary dependencies:
  pyqt6==6.2.3              requires pyqt6-qt6>=6.2.3, pyqt6-sip<14,>=13.2

New dependencies found in this round:
  adding ['pyqt6-qt6', '>=6.2.3', '[]']
  adding ['pyqt6-sip', '<14,>=13.2', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  pyqt6 (from -r /tmp/pipenv1_lx94l8requirements/pipenv-5hrlb8op-constraints.txt (line 2))
  pyqt6-qt6>=6.2.3 (from pyqt6==6.2.3->-r /tmp/pipenv1_lx94l8requirements/pipenv-5hrlb8op-constraints.txt (line 2))
  pyqt6-sip<14,>=13.2 (from pyqt6==6.2.3->-r /tmp/pipenv1_lx94l8requirements/pipenv-5hrlb8op-constraints.txt (line 2))

Finding the best candidates:
  found candidate pyqt6==6.2.3 (constraint was <any>)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pipenv/utils.py", line 825, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/usr/lib/python3.10/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/lib/python3.10/site-packages/pipenv/patched/piptools/resolver.py", line 260, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/usr/lib/python3.10/site-packages/pipenv/patched/piptools/resolver.py", line 260, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/usr/lib/python3.10/site-packages/pipenv/patched/piptools/resolver.py", line 319, in get_best_match
    best_match = self.repository.find_best_match(
  File "/usr/lib/python3.10/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 205, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches pyqt6-qt6>=6.2.3 (from pyqt6==6.2.3->-r /tmp/pipenv1_lx94l8requirements/pipenv-5hrlb8op-constraints.txt (line 2))
No versions found
Was https://pypi.org/simple reachable?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/usr/lib/python3.10/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/usr/lib/python3.10/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/usr/lib/python3.10/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/usr/lib/python3.10/site-packages/pipenv/utils.py", line 1397, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/usr/lib/python3.10/site-packages/pipenv/utils.py", line 1110, in actually_resolve_deps
    resolver.resolve()
  File "/usr/lib/python3.10/site-packages/pipenv/utils.py", line 835, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: Could not find a version that matches pyqt6-qt6>=6.2.3 (from pyqt6==6.2.3->-r /tmp/pipenv1_lx94l8requirements/pipenv-5hrlb8op-constraints.txt (line 2))
No versions found
Was https://pypi.org/simple reachable?
ROUND 1                           
Current constraints:
  pyqt6 (from -r /tmp/pipenv1_lx94l8requirements/pipenv-5hrlb8op-constraints.txt (line 2))

Finding the best candidates:
  found candidate pyqt6==6.2.3 (constraint was <any>)

Finding secondary dependencies:
  pyqt6==6.2.3              requires pyqt6-qt6>=6.2.3, pyqt6-sip<14,>=13.2

New dependencies found in this round:
  adding ['pyqt6-qt6', '>=6.2.3', '[]']
  adding ['pyqt6-sip', '<14,>=13.2', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2                           
Current constraints:
  pyqt6 (from -r /tmp/pipenv1_lx94l8requirements/pipenv-5hrlb8op-constraints.txt (line 2))
  pyqt6-qt6>=6.2.3 (from pyqt6==6.2.3->-r /tmp/pipenv1_lx94l8requirements/pipenv-5hrlb8op-constraints.txt (line 2))
  pyqt6-sip<14,>=13.2 (from pyqt6==6.2.3->-r /tmp/pipenv1_lx94l8requirements/pipenv-5hrlb8op-constraints.txt (line 2))

Finding the best candidates:
  found candidate pyqt6==6.2.3 (constraint was <any>)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pipenv/utils.py", line 825, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/usr/lib/python3.10/site-packages/pipenv/patched/piptools/resolver.py", line 180, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/lib/python3.10/site-packages/pipenv/patched/piptools/resolver.py", line 260, in _resolve_one_round
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/usr/lib/python3.10/site-packages/pipenv/patched/piptools/resolver.py", line 260, in <setcomp>
    best_matches = {self.get_best_match(ireq) for ireq in constraints}
  File "/usr/lib/python3.10/site-packages/pipenv/patched/piptools/resolver.py", line 319, in get_best_match
    best_match = self.repository.find_best_match(
  File "/usr/lib/python3.10/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 205, in find_best_match
    raise NoCandidateFound(ireq, all_candidates, self.finder)
pipenv.patched.piptools.exceptions.NoCandidateFound: Could not find a version that matches pyqt6-qt6>=6.2.3 (from pyqt6==6.2.3->-r /tmp/pipenv1_lx94l8requirements/pipenv-5hrlb8op-constraints.txt (line 2))
No versions found
Was https://pypi.org/simple reachable?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pipenv/resolver.py", line 764, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/pipenv/resolver.py", line 758, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/usr/lib/python3.10/site-packages/pipenv/resolver.py", line 741, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/usr/lib/python3.10/site-packages/pipenv/resolver.py", line 702, in resolve_packages
    results, resolver = resolve(
  File "/usr/lib/python3.10/site-packages/pipenv/resolver.py", line 684, in resolve
    return resolve_deps(
  File "/usr/lib/python3.10/site-packages/pipenv/utils.py", line 1397, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/usr/lib/python3.10/site-packages/pipenv/utils.py", line 1110, in actually_resolve_deps
    resolver.resolve()
  File "/usr/lib/python3.10/site-packages/pipenv/utils.py", line 835, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: Could not find a version that matches pyqt6-qt6>=6.2.3 (from pyqt6==6.2.3->-r /tmp/pipenv1_lx94l8requirements/pipenv-5hrlb8op-constraints.txt (line 2))
No versions found
Was https://pypi.org/simple reachable?
```
I find the error message strange, because the dependency error makes no sense (to me). The dependency graph indicates that there should not be any problem in resolving dependencies.
```
$ pipenv --verbose graph

Running command: $ /home/pew/.local/share/virtualenvs/pygui-md2qg1x2/bin/python /usr/lib/python3.10/site-packages/pipenv/vendor/pipdeptree.py  -l
Command output: pip==21.2.3
PyQt6==6.2.3
  - PyQt6-Qt6 [required: >=6.2.3, installed: 6.2.3]
  - PyQt6-sip [required: >=13.2,<14, installed: 13.2.1]
setuptools==57.4.0
wheel==0.36.2

PyQt6==6.2.3
  - PyQt6-Qt6 [required: >=6.2.3, installed: 6.2.3]
  - PyQt6-sip [required: >=13.2,<14, installed: 13.2.1]
```

So looks like it can resolve `PyQt6-Qt6>=6.2.3` just fine. But still can not lock the dependencies.

### Steps to replicate

1.  Move to an empty directory.
2.  Execute `pipenv install pyqt6`.

-------------------------------------------------------------------------------

### `pipenv --support ` output.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2021.5.29'`

Pipenv location: `'/usr/lib/python3.10/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.10.2`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.16.8-200.fc35.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Tue Feb 8 20:58:59 UTC 2022',
 'python_full_version': '3.10.2',
 'python_version': '3.10',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `SESSION_MANAGER`
  - `COLORTERM`
  - `HISTCONTROL`
  - `XDG_MENU_PREFIX`
  - `HISTSIZE`
  - `HOSTNAME`
  - `SSH_AUTH_SOCK`
  - `XMODIFIERS`
  - `DESKTOP_SESSION`
  - `PWD`
  - `LOGNAME`
  - `XDG_SESSION_DESKTOP`
  - `QT_QPA_PLATFORMTHEME`
  - `XDG_SESSION_TYPE`
  - `SYSTEMD_EXEC_PID`
  - `XAUTHORITY`
  - `QT_STYLE_OVERRIDE`
  - `GDM_LANG`
  - `HOME`
  - `USERNAME`
  - `LANG`
  - `LS_COLORS`
  - `XDG_CURRENT_DESKTOP`
  - `VTE_VERSION`
  - `WAYLAND_DISPLAY`
  - `INVOCATION_ID`
  - `MANAGERPID`
  - `QT_QPA_PLATFORM`
  - `MOZ_GMP_PATH`
  - `GNOME_SETUP_DISPLAY`
  - `XDG_SESSION_CLASS`
  - `TERM`
  - `LESSOPEN`
  - `USER`
  - `DISPLAY`
  - `SHLVL`
  - `QT_IM_MODULE`
  - `TILIX_ID`
  - `XDG_RUNTIME_DIR`
  - `DEBUGINFOD_URLS`
  - `which_declare`
  - `JOURNAL_STREAM`
  - `XDG_DATA_DIRS`
  - `PATH`
  - `GDMSESSION`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `MAIL`
  - `BASH_FUNC_which%%`
  - `OLDPWD`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/pew/.local/bin:/home/pew/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/pew/workspace/pygui`

---------------------------

Contents of `Pipfile` ('/home/pew/workspace/pygui/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
pyqt6 = "*"

[dev-packages]

[requires]
python_version = "3.10"

```

</details>

**Comment by matteius** [comment]
@chai-script you are reporting a bug for an older version of `pipenv`, can you check the behavior with the latest version `2022.1.8`?

**Comment by chai-script** [comment]
> @chai-script you are reporting a bug for an older version of `pipenv`, can you check the behavior with the latest version `2022.1.8`?

@matteius This issue does not exist in the latest version. Thanks for helping out, I had installed outdated pipenv from fedora repos. Sorry for not checking with the latest version before reporting.
