### ISSUE TITLE
distutils.sysconfig module not found in pipenv pipx installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by DrPyser** [pypa/pipenv#5060]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

pipenv commands(e.g. `pipenv install`) fail with 

```
[...]
ModuleNotFoundError: No module named 'distutils.sysconfig'
```
I've tried installing pipenv through `python3.8 -m pip install --user pipenv` and `python3.8 -m pipx install pipenv` with same result.
I've reinstalled python, pip, pipx, `python3-distutils` on system with no success.

### Expected result

pipx should be packaging all dependencies in the pipenv installation environment. distutils package modules(I believe part of `setuptools` package) should be found.

### Actual result

```bash
❯ pipenv install --verbose
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
Traceback (most recent call last):
  File "/home/charles-langlois/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/resolver.py", line 857, in <module>
    main()
  File "/home/charles-langlois/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/resolver.py", line 833, in main
    from pipenv.vendor.vistir.compat import ResourceWarning
  File "/home/charles-langlois/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/__init__.py", line 57, in <module>
    from .cli import cli
  File "/home/charles-langlois/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/cli/__init__.py", line 1, in <module>
    from .command import cli  # noqa
  File "/home/charles-langlois/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/cli/command.py", line 7, in <module>
    from pipenv.cli.options import (
  File "/home/charles-langlois/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/cli/options.py", line 3, in <module>
    from pipenv.project import Project
  File "/home/charles-langlois/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/project.py", line 21, in <module>
    from pipenv.core import system_which
  File "/home/charles-langlois/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/core.py", line 30, in <module>
    from pipenv.utils.resolver import venv_resolve_deps
  File "/home/charles-langlois/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/utils/resolver.py", line 14, in <module>
    from pipenv.vendor.requirementslib import Pipfile, Requirement
  File "/home/charles-langlois/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/vendor/requirementslib/__init__.py", line 7, in <module>
    from .models.lockfile import Lockfile
  File "/home/charles-langlois/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/lockfile.py", line 16, in <module>
    from .requirements import Requirement
  File "/home/charles-langlois/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 10, in <module>
    from distutils.sysconfig import get_python_lib
ModuleNotFoundError: No module named 'distutils.sysconfig'
```

### Steps to replicate

1. Get a ubuntu 20.04 environment.
2. Verify python system installation is python3.8, that pip is installed, that python3-distutils apt package is installed, and finally that pipx is installed.
3. Install pipenv through pipx: `python3.8 -m pipx install pipenv`.
4. run `pipenv install` in an existing project with a Pipfile.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.4.8'`

Pipenv location: `'/home/charles-langlois/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv'`

Python location: `'/home/charles-langlois/.local/pipx/venvs/pipenv/bin/python'`

Python installations found:

  - `3.8.10`: `/usr/bin/python3`
  - `3.8.10`: `/usr/bin/python3.8`
  - `3.7.5`: `/usr/bin/python3.7m`
  - `3.7.5`: `/usr/bin/python3.7`
  - `3.6.9`: `/usr/bin/python3.6m`
  - `3.6.9`: `/usr/bin/python3.6`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.10',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.4.7-050407-generic',
 'platform_system': 'Linux',
 'platform_version': '#201912311234 SMP Tue Dec 31 17:38:50 UTC 2019',
 'python_full_version': '3.8.10',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `WINDOWID`
  - `QT_ACCESSIBILITY`
  - `COLORTERM`
  - `XDG_CONFIG_DIRS`
  - `TMUX`
  - `I3SOCK`
  - `KONVERSION_REGISTRY`
  - `REGISTRY_DOMAIN`
  - `MANDATORY_PATH`
  - `SSH_AUTH_SOCK`
  - `DIRENV_DIR`
  - `DESKTOP_SESSION`
  - `GPG_TTY`
  - `EDITOR`
  - `GTK_MODULES`
  - `XDG_SEAT`
  - `PWD`
  - `LOGNAME`
  - `XDG_SESSION_DESKTOP`
  - `XDG_SESSION_TYPE`
  - `GPG_AGENT_INFO`
  - `XAUTHORITY`
  - `WINDOWPATH`
  - `HOME`
  - `USERNAME`
  - `LANG`
  - `LS_COLORS`
  - `_JAVA_AWT_WM_NONREPARENTING`
  - `STARSHIP_SHELL`
  - `DIRENV_DIFF`
  - `STARSHIP_SESSION_KEY`
  - `NVM_DIR`
  - `LESSCLOSE`
  - `XDG_SESSION_CLASS`
  - `TERM`
  - `DEFAULTS_PATH`
  - `LESSOPEN`
  - `USER`
  - `TMUX_PANE`
  - `DISPLAY`
  - `SHLVL`
  - `XDG_VTNR`
  - `AGENDACMD`
  - `UBUNTU_MENUPROXY`
  - `XDG_SESSION_ID`
  - `XDG_RUNTIME_DIR`
  - `XDG_DATA_DIRS`
  - `PATH`
  - `ALACRITTY_LOG`
  - `GDMSESSION`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DIRENV_WATCHES`
  - `AGENDA`
  - `OLDPWD`
  - `GOPATH`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/charles-langlois/.cargo/bin:/home/charles-langlois/bin:/home/charles-langlois/.local/bin:/home/charles-langlois/go/bin:/usr/local/go/bin:/home/charles-langlois/.local/bin:/home/charles-langlois/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/charles-langlois/.local/bin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `kcr edit`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/home/charles-langlois/repositories/microifc/micro_ifc`

---------------------------

Contents of `Pipfile` ('/home/charles-langlois/repositories/microifc/micro_ifc/Pipfile'):

```toml
[[source]]
name = "pypi-mirror"
url = "https://pip.kio.to/pypi/+simple"
verify_ssl = true

[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[[source]]
url = "https://pip.kio.to/root/konversion/+simple"
verify_ssl = true
name = "devil"

[dev-packages]
mypy = "*"
pylint = "*"
rope = "*"
pytest = "*"
jedi = "*"
black = "*"

[packages]
psycopg2 = "*"
sqlalchemy = {version = "==1.3.*"}
click = "*"
kioto-basic-utils = {index = "devil",version = ">=0.1.11"}
kioto-luigi-utils = {index = "devil",version = ">=0.5.*"}
kioto-marshmallow-utils = {index = "devil",version = "*"}
alembic = "*"
bitarray = "*"
kioto-sqlalchemy-utils = "*"
paramiko = "*"
requests = "*"
websockets = "*"
luigi = "*"
marshmallow = "*"
tenacity = "*"
tinyrpc = "*"
hyperlink = "*"
fastapi = "*"
uvicorn = "*"
asyncpg = "*"
sentry-sdk = "==0.8.0"
aiofiles = "*"
python-dotenv = "*"
pydantic = {extras = ["email"],version = "*"}
kioto-api-connector = {index = "devil",version = "==1.1.*"}
python-multipart = "*"
python-json-logger = "*"
pyyaml = "*"
colorama = "*"
blessings = "*"

[requires]
python_version = "3.7"

[pipenv]
allow_prereleases = true

```

</details>

**Comment by matteius** [comment]
@DrPyser  "It's likely because you're on a system that does not install the distutils module alongside python even though it is still part of the python standard library." and "Sadly, on Ubuntu 20.04, python3-distutils is Python3.8 package. python3.9-distutils is a virtual that installs python3-distutils." -- These quotes are from this issue report which seems to have some support for you.  https://github.com/pypa/get-pip/issues/124#issuecomment-904380931

**Comment by matteius** [comment]
Closing this as their has been no response.
