### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by DenisMelnik** [pypa/pipenv#5068]
### Issue description

Getting erorr during `pipenv install` command after upgrade to the latest `v2022.4.20` version.
It works with `v2022.4.8` version.

### Expected result

Install packages.

### Actual result

```
Installing dependencies from Pipfile.lock (529d2f)...
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli/options.py", line 56, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pipenv/cli/command.py", line 241, in install
    site_packages=state.site_packages,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line [210](https://code.devops.fds.com/devops/tfc/-/jobs/1968838#L210)2, in do_install
    keep_outdated=keep_outdated,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 1343, in do_init
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 870, in do_install_dependencies
    project, normal_deps, procs, failed_deps_queue, requirements_dir, **install_kwargs
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 728, in batch_install
    dep for dep in deps_to_install if not project.environment.is_satisfied(dep)
  File "/usr/local/lib/python3.6/site-packages/pipenv/core.py", line 728, in <listcomp>
    dep for dep in deps_to_install if not project.environment.is_satisfied(dep)
  File "/usr/local/lib/python3.6/site-packages/pipenv/environment.py", line 859, in is_satisfied
    elif req.line_instance.specifiers is not None:
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2553, in line_instance
    self.line_instance = self.get_line_instance()
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2547, in get_line_instance
    return Line(line)
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 171, in __init__
    self.parse()
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1289, in parse
    self.parse_extras()
  File "/usr/local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 577, in parse_extras
    self.line, extras = pip_shims.shims._strip_extras(self.line)
TypeError: 'NoneType' object is not callable
```

**Comment by Moribund7** [comment]
Got exactly same issue today.

**Comment by jseiser** [comment]
Same here on a bunch of Redhat 7/8 boxes running Python 3.9

**Comment by matteius** [comment]
https://github.com/pypa/pipenv/issues/5065

**Comment by matteius** [comment]
@jseiser If you got a similar error on Python 3.9 please file a new bug report.  I am closing this one out as there is nothing we can do to restore python 3.6 support.   This changed was merged to main to drop it from setup.py:  https://github.com/pypa/pipenv/pull/5066
