### ISSUE TITLE
pipenv install xxx package error in python 3.10 version 

### ISSUE THREAD

**Issue by hemanth-reckonsys** [pypa/pipenv#5094]
1. ubuntu 20.04
2. python 3.10.4
3. pipenv --version 
    version 11.9.0
4. pipenv shell (working fine)
5. pipenv install celery (error)
```
Installing celery…
⠇
Error:  An error occurred while installing celery!
Traceback (most recent call last):
  File "/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/lib/python3.10/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 15, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 12, in <module>
    from pip._vendor import html5lib, requests
ImportError: cannot import name 'html5lib' from 'pip._vendor' (/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/lib/python3.10/site-packages/pip/_vendor/__init__.py)
```
How to solve this error?

**Comment by matteius** [comment]
@hemanth-reckonsys  11.2.0 is long unsupported.  Please upgrade to a modern version like `pipenv==2022.4.30`

**Comment by hemanth-reckonsys** [comment]
is something wrong?
1. pipenv --version
    pipenv, version 2022.4.30
2. pipenv check
    Checking PEP 508 requirements...
   Specifier python_version does not match 3.1 (3.10).
   Failed!

**Comment by matteius** [comment]
@hemanth-reckonsys Without seeing your Pipfile it is hard, but your new error I think is because you need 3.10 in quotes like "3.10" because Specifier python_version does not match 3.1 (3.10) -- its getting parsed as a float 3.1 without quotes.

**Comment by hemanth-reckonsys** [comment]
@matteius hi, below i think i shared my all details

Pipfile
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[requires]
python_version = "3.10"
```

1. pipenv --version
pipenv, version 2022.4.30

2. python --version
Python 3.10.4

3. pipenv check
Checking PEP 508 requirements...
Passed!
Checking installed package safety...
All good!

pipenv install celery
```
Installing celery...
Error:  An error occurred while installing celery!
Error text: 
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/lib/python3.10/site-packages/pip/__main__.py", line 19, in <module>
    sys.exit(_main())
  File "/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/lib/python3.10/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/lib/python3.10/site-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 15, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/lib/python3.10/site-packages/pip/_internal/index/collector.py", line 12, in <module>
    from pip._vendor import html5lib, requests
ImportError: cannot import name 'html5lib' from 'pip._vendor' (/home/xx/.local/share/virtualenvs/yy-VQZGIAqw/lib/python3.10/site-packages/pip/_vendor/__init__.py)

✘ Installation Failed 
```

**Comment by hemanth-reckonsys** [comment]
it worked fine after I installed the 4th command but I do not know what the 4th command will do.
4. `curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
`
5. pipenv install celery (worked fine)

**Comment by matteius** [comment]
@hemanth-reckonsys Likely the version of pip on your system was too old to work with the newer pipenv.  If you can provide any additional details on what version of pip you had installed prior may be helpful.

**Comment by hemanth-reckonsys** [comment]
hi @matteius,

this is my pip version
`pip3 --version`
 pip 22.0.4 from /home/xxx/.local/lib/python3.10/site-packages/pip (python 3.10)

**Comment by matteius** [comment]
@hemanth-reckonsys That is your pip version now that it is working right?  After running `curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10`

**Comment by hemanth-reckonsys** [comment]
@matteius, yes, it's working fine but still, I do not know why I need to run that command. and sometimes I need to execute `export SETUPTOOLS_USE_DISTUTILS=stdlib` this too.

**Comment by agpldev** [comment]
After working through carious threads on this issue, I think what got this working correctly for me is the following on my Ubuntu 20.04 (WSL) .. will try it on my Ubuntu machine later wen attempting to duplicate this test environment for UAT/PTA purposes:

1. Installed Python 3.10.5 from the DeadSnakes PPA
2. Perform the pip update (to 22.1.2) via curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
3. Install pipenv (2022.7.4) using pip
4. pipenv install xxx still failed at this stage. using pipenv shell in the project directory successfully created the necessary structures and virtual environment, though
5. Installed the required packages using pipenv install xxx from within the virtual environment and all working well.

**Comment by matteius** [comment]
@agpldev I don't recommend folks to use DeadSnakes in a production or critical environment.

From their own page:  https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa

> Disclaimer: there's no guarantee of timely updates in case of security problems or other issues. If you want to use them in a security-or-otherwise-critical environment (say, on a production server), you do so at your own risk.

**Comment by agpldev** [comment]
> @agpldev I don't recommend folks to use DeadSnakes in a production or critical environment.
> 
> From their own page: https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa
> 
> > Disclaimer: there's no guarantee of timely updates in case of security problems or other issues. If you want to use them in a security-or-otherwise-critical environment (say, on a production server), you do so at your own risk.

Appreciated and agreed @matteius, certainly worth highlighting/reiterating that point. I have not had time to compile 3.10 on this Ubuntu version for my purposes as I am still working on some design aspects at present.

**Comment by matteius** [comment]
The new version of `pipenv==2022.8.5` should not depend on the system/user installed pip.
