### ISSUE TITLE
Pipenv lock ResolutionFailure exception on private package

### ISSUE THREAD

**Issue by khasbilegt** [pypa/pipenv#5103]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

Pipenv lock results in `ResolutionFailure` exception with the message of `ERROR: No matching distribution found for package==0.0.1` when the package is added from a private repository.

### Expected result

New lock file gets created.

### Actual result

Reporter.starting()
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.starting()
Reporter.adding_requirement(SpecifierRequirement('ariadne-django-ext'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('ariadne-django-ext'), None)
Reporter.adding_requirement(SpecifierRequirement('simplejson'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('simplejson'), None)
Reporter.adding_requirement(SpecifierRequirement('django-social-oauth-token'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('django-social-oauth-token'), None)
Reporter.adding_requirement(SpecifierRequirement('markdown'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('markdown'), None)
Reporter.adding_requirement(SpecifierRequirement('psycopg2-binary'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('psycopg2-binary'), None)
Reporter.adding_requirement(SpecifierRequirement('pillow'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('pillow'), None)
Reporter.adding_requirement(SpecifierRequirement('ariadne-django'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('ariadne-django'), None)
Reporter.adding_requirement(SpecifierRequirement('django-filter'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('django-filter'), None)
Reporter.adding_requirement(SpecifierRequirement('django-user-email'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('django-user-email'), None)
Reporter.adding_requirement(SpecifierRequirement('celery'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('celery'), None)
Reporter.adding_requirement(SpecifierRequirement('django-cors-headers'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('django-cors-headers'), None)
Reporter.adding_requirement(SpecifierRequirement('django-oauth-toolkit'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('django-oauth-toolkit'), None)
Reporter.adding_requirement(SpecifierRequirement('private_package==7.0.1'), None)
INFO:pipenv.patched.notpip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('private_package==7.0.1'), None)
CRITICAL:pipenv.patched.notpip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement private_package==7.0.1 (from versions: none)
Traceback (most recent call last):
  File "/Users/khasbilegt/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/khasbilegt/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    raise RequirementsConflicted(criterion)
pipenv.patched.notpip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('private_package==7.0.1')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/khasbilegt/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/Users/khasbilegt/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/khasbilegt/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 350, in resolve
    raise ResolutionImpossible(e.criterion.information)
pipenv.patched.notpip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('private_package==7.0.1'), parent=None)]
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/khasbilegt/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 661, in resolve
    results = resolver.resolve(self.constraints, check_supported_wheels=False)
  File "/Users/khasbilegt/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/resolver.py", line 103, in resolve
    raise error from e
pipenv.patched.notpip._internal.exceptions.DistributionNotFound: No matching distribution found for private_package==7.0.1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/khasbilegt/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/resolver.py", line 857, in <module>
    main()
  File "/Users/khasbilegt/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/resolver.py", line 843, in main
    _main(
  File "/Users/khasbilegt/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/resolver.py", line 822, in _main
    resolve_packages(
  File "/Users/khasbilegt/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/resolver.py", line 771, in resolve_packages
    results, resolver = resolve(
  File "/Users/khasbilegt/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/resolver.py", line 751, in resolve
    return resolve_deps(
  File "/Users/khasbilegt/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 1068, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/Users/khasbilegt/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 862, in actually_resolve_deps
    resolver.resolve()
  File "/Users/khasbilegt/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 663, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: No matching distribution found for private_package==7.0.1
✘ Locking Failed! 

### Steps to replicate

1. Add a private source to the Pipfile
2. Create a new virtualenv, install the package. (First time locking works somehow)
3. Try to install the different version of the package but fails when locking.

-------------------------------------------------------------------------------

**Comment by matteius** [comment]
@khasbilegt Please see: https://github.com/pypa/pipenv/issues/5053#issuecomment-1101000045
