### ISSUE TITLE
Mac M1 python 3.8.2-3.8.12 ModuleNotFoundError: No module named '_ctypes'

### ISSUE THREAD

**Issue by Gespover863** [pypa/pipenv#5104]
Hello there.

I have the same issue as #4901 

> Mac Air M1, Monterey 12.4

But for python version 3.8.2 and 3.8.12

```
(router) gespover@MacBook-Air-Stepan router % pipenv install
Traceback (most recent call last):
  File "/Users/gespover/.pyenv/versions/3.8.12/envs/router/bin/pipenv", line 5, in <module>
    from pipenv import cli
  File "/Users/gespover/.pyenv/versions/3.8.12/envs/router/lib/python3.8/site-packages/pipenv/__init__.py", line 56, in <module>
    from .cli import cli
  File "/Users/gespover/.pyenv/versions/3.8.12/envs/router/lib/python3.8/site-packages/pipenv/cli/__init__.py", line 1, in <module>
    from .command import cli  # noqa
  File "/Users/gespover/.pyenv/versions/3.8.12/envs/router/lib/python3.8/site-packages/pipenv/cli/command.py", line 7, in <module>
    from pipenv.cli.options import (
  File "/Users/gespover/.pyenv/versions/3.8.12/envs/router/lib/python3.8/site-packages/pipenv/cli/options.py", line 3, in <module>
    from pipenv.project import Project
  File "/Users/gespover/.pyenv/versions/3.8.12/envs/router/lib/python3.8/site-packages/pipenv/project.py", line 21, in <module>
    from pipenv.core import system_which
  File "/Users/gespover/.pyenv/versions/3.8.12/envs/router/lib/python3.8/site-packages/pipenv/core.py", line 32, in <module>
    from pipenv.utils.resolver import venv_resolve_deps
  File "/Users/gespover/.pyenv/versions/3.8.12/envs/router/lib/python3.8/site-packages/pipenv/utils/resolver.py", line 14, in <module>
    from pipenv.vendor.requirementslib import Pipfile, Requirement
  File "/Users/gespover/.pyenv/versions/3.8.12/envs/router/lib/python3.8/site-packages/pipenv/vendor/requirementslib/__init__.py", line 7, in <module>
    import setuptools
  File "/Users/gespover/.pyenv/versions/3.8.12/envs/router/lib/python3.8/site-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/Users/gespover/.pyenv/versions/3.8.12/envs/router/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
    from setuptools import windows_support
  File "/Users/gespover/.pyenv/versions/3.8.12/envs/router/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/Users/gespover/.pyenv/versions/3.8.12/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
```

Reinstall doesn't help, and I don't know what I can do. Plz help:C

**Comment by matteius** [comment]
@Gespover863 your issue is happening in `setuptools` -- what version are you running?

**Comment by Gespover863** [comment]
@matteius 

> pyenv 2.3.0

> setuptools  56.0.0

**Comment by Gespover863** [comment]
I was saved by this two links:

> https://stackoverflow.com/questions/69496504/modulenotfounderror-no-module-named-ctypes-mac-m1
> 
> https://laict.medium.com/install-python-on-macos-11-m1-apple-silicon-using-pyenv-12e0729427a9

Python 3.8.6 with patch works fine
