### ISSUE TITLE
pipenv lock "locking failed" AttributeError: 'NoneType' object has no attribute 'ensure_build_location'

### ISSUE THREAD

**Issue by montaropdf** [pypa/pipenv#5152]
### Issue description

pipenv fails at the locking stage, whatever the command ran. It also seems independent of the version of pipenv, I downgraded to version 2022.4.20, from 2022.6.7, but, the result is still the same. I wonder if it could be related to pip, given the exception below.

Pip version available on the machine.

```
[ostsl-reporter@ltgcdrpt001a gcloudadm]$ pip3.8 --version
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 22.1.2 from /home/ostsl-reporter/.local/lib/python3.8/site-packages/pip (python 3.8)
```

### Expected result

The locking stage to succeed and the rest of the process, for the pipenv command launched, to complete without errors.

### Actual result

```
[ostsl-reporter@ltgcdrpt001a gcloudadm]$ pipenv lock                                                                                         
Locking [dev-packages] dependencies...                                                                                                                                                        
Building requirements...                                                                                                                                                                      
Resolving dependencies...                                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                            
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 856, in <module>                                                                                    
    main()                                                                                                                                                                                    
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 851, in main                                                                                       
    dev=parsed.dev,
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 823, in _main                                                                                      
    pre, clear, verbose, system, write, requirements_dir, packages, dev
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 778, in resolve_packages                                                                           
    requirements_dir=requirements_dir,
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/resolver.py", line 759, in resolve                                                                                    
    req_dir=requirements_dir,
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/utils/resolver.py", line 1076, in resolve_deps                                                                        
    req_dir=req_dir,
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/utils/resolver.py", line 860, in actually_resolve_deps                                                                
    deps, project, index_lookup, markers_lookup, sources, req_dir, clear, pre
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/utils/resolver.py", line 407, in create                                                                               
    clear=clear,
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/utils/resolver.py", line 177, in get_metadata                                                                         
    project=project,
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/utils/resolver.py", line 231, in parse_line                                                                           
    req = Requirement.from_line(line)
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2672, in from_line                                               
    if isinstance(line, pip_shims.shims.InstallRequirement):
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/vendor/pip_shims/shims.py", line 61, in __getattr__                                                                   
    return locations[args[0]].shim()
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/vendor/pip_shims/models.py", line 737, in shim                                                                        
    result = self.traverse(top_path)
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/vendor/pip_shims/models.py", line 729, in traverse                                                                    
    result = shim.shim()
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/vendor/pip_shims/models.py", line 577, in shim                                                                        
    return self.shim_class(imported, self.name_to_import)
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/vendor/pip_shims/models.py", line 519, in shim_class                                                                  
    imported, result = self._shim_parent(imported, attribute_name)
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/vendor/pip_shims/models.py", line 503, in _shim_parent                                                                
    result = self._shim_base(imported, attribute_name)
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/vendor/pip_shims/models.py", line 492, in _shim_base
    return self._apply_aliases(imported, result)
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/vendor/pip_shims/models.py", line 497, in _apply_aliases
    target = apply_alias(imported, target, *alias_list)
  File "/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv/vendor/pip_shims/utils.py", line 326, in apply_alias
    setattr(target, alias, alias_value)
AttributeError: 'NoneType' object has no attribute 'build_location'
✘ Locking Failed!
```

### Steps to replicate

pipenv lock

-------------------------------------------------------------------------------
<details><summary>$ pipenv --support</summary>
                 
Pipenv version: `'2022.6.7'`
                    
Pipenv location: `'/home/ostsl-reporter/.local/lib/python3.8/site-packages/pipenv'`
                  
Python location: `'/usr/bin/python3.8'`
          
Python installations found:                                                                  
                  
  - `3.8.12`: `/bin/python3.8`
  - `3.8.12`: `/usr/bin/python3.8`
  - `3.6.8`: `/bin/python3.6`
  - `3.6.8`: `/bin/python3.6m`        
  - `3.6.8`: `/bin/python3`                  
  - `3.6.8`: `/usr/bin/python3.6`        
  - `3.6.8`: `/usr/bin/python3.6m`      
  - `3.6.8`: `/usr/bin/python3`         
                                               
PEP 508 Information:                   
              
```           
{'implementation_name': 'cpython',
 'implementation_version': '3.8.12',
 'os_name': 'posix',
 'platform_machine': 'x86_64',         
 'platform_python_implementation': 'CPython',
 'platform_release': '4.18.0-348.23.1.el8_5.x86_64',
 'platform_system': 'Linux',                       
 'platform_version': '#1 SMP Tue Apr 12 11:20:32 EDT 2022',
 'python_full_version': '3.8.12',     
 'python_version': '3.8',                  
 'sys_platform': 'linux'}                 
```
   
System environment variables:        
          
  - `LS_COLORS`                                                                                                                         
  - `LC_MEASUREMENT`           
  - `LC_PAPER`                          
  - `LC_MONETARY`
  - `LANG`
  - `HISTCONTROL`                                                                                                                                                                             
  - `SUDO_GID`                                                                                                                                                                                
  - `HISTTIMEFORMAT`
  - `HOSTNAME`
  - `SUDO_COMMAND`
  - `which_declare`
  - `USER`
  - `PWD`
  - `HOME`
  - `SUDO_USER`
  - `LC_NUMERIC`
  - `SUDO_UID`
  - `MAIL`
  - `SHELL`
  - `TERM`
  - `SHLVL`
  - `MANPATH`
  - `LOGNAME`
  - `PATH`
  - `HISTSIZE`
  - `LESSOPEN`
  - `LC_TIME`
  - `BASH_FUNC_which%%`
  - `OLDPWD`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/ostsl-reporter/.local/bin:/home/ostsl-reporter/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/opt/puppetlabs/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/ostsl-reporter/apps/gcloudadm`

---------------------------

Contents of `Pipfile` ('/home/ostsl-reporter/apps/gcloudadm/Pipfile'):

```toml
[[source]]
url = "https://repo.gcloud.belgium.be/artifactory/api/pypi/common-pypi-central-remote/simple"
verify_ssl = false
name = "jdss"

[packages]
click = {index = "jdss",version = "*"}
openstacksdk = {index = "jdss",version = "*"}
requests = {index = "jdss",version = "*"}
pyvmomi = {index = "jdss",version = "*"}
ansible = {index = "jdss",version = "*"}
ansible-runner = {index = "jdss",version = "*"}
pyyaml = {index = "jdss",version = "*"}

[requires]
python_version = "3.8"

[dev-packages]
pytest = {index = "jdss",version = "*"}
Sphinx = {index = "jdss",version = "*"}
flake8 = {index = "jdss",version = "*"}
importlib-metadata = {index = "jdss",version = "*"}
pandas = {index = "jdss",version = "*"}
numpy = {index = "jdss",version = "*"}
matplotlib = {index = "jdss",version = "*"}
pandasgui = {index = "jdss",version = "*"}

```

</details>

**Comment by matteius** [comment]
@montaropdf  Can you try to downgrade you pip version to `22.0.4`?  I wonder if pip-shims needs a compatibility update for the new version of pip.

**Comment by montaropdf** [comment]
> @montaropdf Can you try to downgrade you pip version to `22.0.4`? I wonder if pip-shims needs a compatibility update for the new version of pip.


Super weird outcome:
Downgrading pip to `22.0.3` and pipenv to **`pipenv-11.10.4`n** (this version seems odd) allow me to complete the lock command without error. Next I set back pipenv to the latest version which set pip to the latest version. I run `pipenv --lock`, which ends successfully.

**Comment by matteius** [comment]
@montaropdf Expecting a new version of `pipenv` any day ... FWIW you should never have to install back to 11.10.4 since that is sooo old, but I am not sure -- sounds like a system issue.  Can we close this one for now?
