### ISSUE TITLE
Regression: Dependency links not handled correctly by pipenv >2021.5.29

### ISSUE THREAD

**Issue by pikulmar** [pypa/pipenv#5191]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

We have a Python package the `setup.cfg` of which contains a dependency link (https://stackoverflow.com/a/61931498) in `install_requires`, of the form `dependency_name @ git+https://github.com/someOrganization/someRepo.git@someCommitHash`.

The package itself is then referenced in `Pipfile` via

```
[packages]
our-package-name = {editable = true,path = "."}
```

### Expected result

`pipenv update --dev` updates `Pipfile.lock` without error.

### Actual result

```
Traceback (most recent call last):
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/resolver.py", line 766, in <module>
    main()
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/resolver.py", line 760, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/resolver.py", line 743, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/resolver.py", line 704, in resolve_packages
    results, resolver = resolve(
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/resolver.py", line 685, in resolve
    return resolve_deps(
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/utils.py", line 1370, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/utils.py", line 1100, in actually_resolve_deps
    hashes = resolver.resolve_hashes()
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/utils.py", line 974, in resolve_hashes
    self.hashes[ireq] = self.collect_hashes(ireq)
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/utils.py", line 950, in collect_hashes
    return {self._get_hash_from_link(ireq.original_link)}
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/utils.py", line 983, in _get_hash_from_link
    return self.hash_cache.get_hash(link)
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/utils.py", line 393, in get_hash
    hash_value = self._get_file_hash(link).encode()
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/utils.py", line 401, in _get_file_hash
    with open_file(link.url, self.session) as fp:
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/vendor/vistir/contextmanagers.py", line 352, in open_file
    with session.get(link, headers=headers, stream=stream) as resp:
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/network/session.py", line 454, in request
    return super().request(method, url, *args, **kwargs)
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/requests/sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/requests/sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
pipenv.patched.notpip._vendor.requests.exceptions.InvalidSchema: No connection adapters were found for 'git+https://github.com/someOrganization/someRepo.git@someCommitHash'
```

### Steps to replicate

See issue description. Given that this is a private package, I am not sure I can paste any further information. If really needed, I could probably create a mock package exhibiting the above problem.

**Important**: The problem occurs only with `pipenv >2021.5.29`, in particular it does not occur with `pipenv==2021.5.29` and it does occur with `pipenv==2021.11.9`, as well as `pipenv==2022.7.24` (most recent release at this time).

Hence, the undesired behavior appears to be caused by the changes seen in https://github.com/pypa/pipenv/compare/v2021.5.29...v2021.11.9

**Comment by matteius** [comment]
@pikulmar  It is not clear why you would have started getting an adapter issue on `git+https://` but newer versions of pipenv from 2022 have improved security around index restricted packages.  For those you may need to reference:  https://pipenv.pypa.io/en/latest/advanced/#specifying-package-indexes

I can tell the stacktrace is from a much older version of pipenv (at least 2021) and does not help me debug -- for example `utils.py` is a `utils` module now.   Can you get a stack trace from the latest `pipenv==2022.7.24`?

**Comment by pikulmar** [comment]
@matteius Thanks for your quick response. Yes, the stack trace is from the first release that exhibited the problem. Above I wrote

_The problem occurs only with pipenv >2021.5.29, in particular it does not occur with pipenv==2021.5.29 and it does occur with pipenv==2021.11.9, as well as pipenv==2022.7.24 (most recent release at this time)._

but now, with pipenv==2022.7.24, I cannot reproduce the error anymore, which is a nice surprise.

In fact, the only change I can think of is that I have deleted the `$HOME/.cache/pipenv` directory since filing the bug report, so perhaps that helped here.

In any case, it looks like things work beautifully now. Sorry for bothering you and thanks again!

**Comment by pikulmar** [comment]
* Indeed, if I delete `Pipfile.lock` and run `pipenv update --dev` with `pipenv==2021.5.29`, it works.
* A subsequent run of `pipenv update --dev` with `pipenv==2021.11.9` fails as described above.
* A subsequent run of `pipenv update --dev` with `pipenv==2022.7.24` fails with stack trace

```
Traceback (most recent call last):
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/resolver.py", line 854, in <module>
    main()
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/resolver.py", line 840, in main
    _main(
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/resolver.py", line 820, in _main
    resolve_packages(
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/resolver.py", line 769, in resolve_packages
    results, resolver = resolve(
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/resolver.py", line 749, in resolve
    return resolve_deps(
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 1080, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 875, in actually_resolve_deps
    hashes = resolver.resolve_hashes()
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 782, in resolve_hashes
    self.hashes[ireq] = self.collect_hashes(ireq)
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 751, in collect_hashes
    return {self._get_hash_from_link(ireq.original_link)}
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 791, in _get_hash_from_link
    return self.hash_cache.get_hash(link)
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 62, in get_hash
    hash_value = self._get_file_hash(link).encode()
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 70, in _get_file_hash
    with open_file(link.url, self.session) as fp:
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/vendor/vistir/contextmanagers.py", line 352, in open_file
    with session.get(link, headers=headers, stream=stream) as resp:
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/patched/notpip/_internal/network/session.py", line 456, in request
    return super().request(method, url, *args, **kwargs)
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/requests/sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/marek/miniconda3/envs/e2e/lib/python3.9/site-packages/pipenv/patched/notpip/_vendor/requests/sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
pipenv.patched.notpip._vendor.requests.exceptions.InvalidSchema: No connection adapters were found for 'git+https://github.com/someOrganization/someRepo.git@someCommitHash'
```
* After `rm -rf ~/.cache/pipenv/`, `pipenv update --dev` succeeds.

I am a little embarrassed that I overlooked the relevant recommendation in https://pipenv.pypa.io/en/latest/diagnose/#your-dependencies-could-not-be-resolved . Ideally, `pipenv` could of course detect a broken cache, e.g., by tracking which `pipenv` version is used to create/alter the cache, but I can understand that this may not be a high priority topic.
