### ISSUE TITLE
Fails to install any packages when python_version <= 3.6

### ISSUE THREAD

**Issue by y-ich** [pypa/pipenv#5205]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

When you specified python_version <= 3.6, you failed to install any packages.
My environment is HomeBrew's pipenv.
(I am sorry that I cannot recognize this issue is due to pipenv or due to HomeBrew installation of pipenv.)

### Expected result

you successfully install any packages.

### Actual result

When resolving dependencies, pipenv uses Python of python_version rather than default 3.10, but pipenv uses the package of pipenv for 3.10 rather than for 3.6.

```
% pipenv install --python 3.6
3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
Warning: Python 3.6 was not found on your system...
Would you like us to install CPython 3.6.15 with Pyenv? [Y/n]: 
Installing CPython 3.6.15 with /usr/local/bin/pyenv (this may take a few minutes)...
✔ Success! 
python-build: use openssl@1.1 from homebrew
python-build: use readline from homebrew
patching file configure
patching file configure.ac
patching file Misc/NEWS.d/next/macOS/2019-06-03-05-49-49.bpo-36231.RfmW_p.rst
patching file setup.py
patching file setup.py
patching file Doc/library/ctypes.rst
patching file Lib/test/test_unicode.py
patching file Modules/_ctypes/_ctypes.c
patching file Modules/_ctypes/callproc.c
patching file Modules/_ctypes/ctypes.h
patching file setup.py
patching file Misc/NEWS.d/next/macOS/2020-06-24-13-51-57.bpo-41100.mcHdc5.rst
patching file configure
patching file configure.ac
patching file 'Misc/NEWS.d/next/Core and Builtins/2020-06-30-04-44-29.bpo-41100.PJwA6F.rst'
patching file Modules/_decimal/libmpdec/mpdecimal.h
patching file setup.py
patching file Misc/NEWS.d/next/Build/2021-10-11-16-27-38.bpo-45405.iSfdW5.rst
patching file configure
patching file configure.ac
python-build: use tcl-tk from homebrew
python-build: use readline from homebrew
python-build: use zlib from xcode sdk

Creating a virtualenv for this project...
Pipfile: /Users/yuji/Studies/Python/pipenv_issue/Pipfile
Using /usr/local/var/pyenv/versions/3.6.15/bin/python3.6m (3.6.15) to create virtualenv...
⠦ Creating virtual environment...created virtual environment CPython3.6.15.final.0-64 in 375ms
  creator CPython3Posix(dest=/Users/yuji/Studies/Python/pipenv_issue/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/yuji/Library/Application Support/virtualenv)
    added seed packages: pip==21.3.1, setuptools==59.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /Users/yuji/Studies/Python/pipenv_issue/.venv
Creating a Pipfile for this project...
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Updated Pipfile.lock (ca72e7)!
Installing dependencies from Pipfile.lock (ca72e7)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
% pipenv install requests # The packages requests is simply an example.
3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
Installing requests...
Adding requests to Pipfile's [packages]...
✔ Installation Succeeded 
Pipfile.lock (ca72e7) out of date, updating to (b14837)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
3.6.15 (default, Jul 29 2022, 10:31:40) 
[GCC Apple LLVM 13.1.6 (clang-1316.0.21.2.5)]
3.6.15 (default, Jul 29 2022, 10:31:40) 
[GCC Apple LLVM 13.1.6 (clang-1316.0.21.2.5)]
Traceback (most recent call last):
  File "/usr/local/Cellar/pipenv/2022.7.24/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 855, in <module>
    main()
  File "/usr/local/Cellar/pipenv/2022.7.24/libexec/lib/python3.10/site-packages/pipenv/resolver.py", line 832, in main
    from pipenv.vendor.vistir.misc import replace_with_text_stream
  File "/usr/local/Cellar/pipenv/2022.7.24/libexec/lib/python3.10/site-packages/pipenv/__init__.py", line 56, in <module>
    from .cli import cli
  File "/usr/local/Cellar/pipenv/2022.7.24/libexec/lib/python3.10/site-packages/pipenv/cli/__init__.py", line 1, in <module>
    from .command import cli  # noqa
  File "/usr/local/Cellar/pipenv/2022.7.24/libexec/lib/python3.10/site-packages/pipenv/cli/command.py", line 7, in <module>
    from pipenv.cli.options import (
  File "/usr/local/Cellar/pipenv/2022.7.24/libexec/lib/python3.10/site-packages/pipenv/cli/options.py", line 3, in <module>
    from pipenv.project import Project
  File "/usr/local/Cellar/pipenv/2022.7.24/libexec/lib/python3.10/site-packages/pipenv/project.py", line 2
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

### Steps to replicate

% pipenv install --python 3.6
% pipenv install requests # The packages requests is simply an example.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

I hesitate this procedure since many private information is included.
Here is its head.

```
3.10.5 (main, Jun 23 2022, 17:15:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.7.24'`
```

**Comment by oz123** [comment]
The problem is here
```
⠦ Creating virtual environment...created virtual environment CPython3.6.15.final.0-64 in 375ms
```

pipenv does not support Python3.6 for quite a while now. Python3.6 is EOL since 12/2021.

**Comment by y-ich** [comment]
@oz123 san,

Thank you for comments. I understand.

I recommend that you guys will check documentations again.
The document (https://pypi.org/project/pipenv/) which you can see on pypi site says
"Pipenv can be installed with Python 3.6 and above."

**Comment by oz123** [comment]
Thank you for the feedback. You are right. The Long description is outdated. However, in general, one should trust the classifiers more then the docs. These are usually more up to dat in most projects .
Never the less we should update the long description 
![Screenshot_20220731-145334](https://user-images.githubusercontent.com/1083045/182027462-4d074ca7-ad45-49dc-b7fd-924b86fcfd90.png)
