### ISSUE TITLE
pipenv.patched.pip._internal.exceptions.InstallationSubprocessError

### ISSUE THREAD

**Issue by Euraxluo** [pypa/pipenv#5224]
Pipfile:

```
[[source]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
verify_ssl = true
name = "pypi"

[packages]
pyconcorde = {editable = true,git = "https://github.com/jvkersch/pyconcorde"}


[requires]
python_version = "3.9"

```

### infomation:

```
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
✘ 
✘ Locking Failed! 

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pipenv/resolver.py", line 854, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/pipenv/resolver.py", line 840, in main
    _main(
  File "/usr/local/lib/python3.9/site-packages/pipenv/resolver.py", line 820, in _main
    resolve_packages(
  File "/usr/local/lib/python3.9/site-packages/pipenv/resolver.py", line 769, in resolve_packages
    results, resolver = resolve(
  File "/usr/local/lib/python3.9/site-packages/pipenv/resolver.py", line 749, in resolve
    return resolve_deps(
  File "/usr/local/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 1089, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/usr/local/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 883, in actually_resolve_deps
    resolver.resolve()
  File "/usr/local/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 686, in resolve
    results = resolver.resolve(self.constraints, check_supported_wheels=False)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/found_candidates.py", line 44, in _iter_built
    for version, func in infos:
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/factory.py", line 279, in iter_index_candidate_infos
    result = self._finder.find_best_candidate(
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/index/package_finder.py", line 901, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/index/package_finder.py", line 842, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/index/sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/index/package_finder.py", line 802, in process_project_url
    index_response = self._link_collector.fetch_response(project_url)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/index/collector.py", line 577, in fetch_response
    return _get_index_content(location, session=self.session)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/index/collector.py", line 480, in _get_index_content
    resp = _get_simple_response(url, session=session)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/index/collector.py", line 138, in _get_simple_response
    resp = session.get(
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/network/session.py", line 518, in request
    return super().request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/cachecontrol/adapter.py", line 57, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_vendor/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

^C
root@1ca72d4191f6:/workspaces/quantum-vrp# ^C
root@1ca72d4191f6:/workspaces/quantum-vrp# pipenv install 
Pipfile.lock (0e487d) out of date, updating to (c86446)...
Locking [dev-packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed! 

ERROR:pip.subprocessor:[present-rich] git clone --filter=blob:none https://github.com/jvkersch/pyconcorde /tmp/pipenv-7c9b568c-src/pyconcorde exited with 128
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pipenv/resolver.py", line 854, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/pipenv/resolver.py", line 840, in main
    _main(
  File "/usr/local/lib/python3.9/site-packages/pipenv/resolver.py", line 820, in _main
    resolve_packages(
  File "/usr/local/lib/python3.9/site-packages/pipenv/resolver.py", line 769, in resolve_packages
    results, resolver = resolve(
  File "/usr/local/lib/python3.9/site-packages/pipenv/resolver.py", line 749, in resolve
    return resolve_deps(
  File "/usr/local/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 1089, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/usr/local/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 880, in actually_resolve_deps
    resolver = Resolver.create(
  File "/usr/local/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 433, in create
    constraints, skipped, index_lookup, markers_lookup = cls.get_metadata(
  File "/usr/local/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 234, in get_metadata
    constraint_update, lockfile_update = cls.get_deps_from_req(
  File "/usr/local/lib/python3.9/site-packages/pipenv/utils/resolver.py", line 314, in get_deps_from_req
    req_list, lockfile = get_vcs_deps(reqs=[req])
  File "/usr/local/lib/python3.9/site-packages/pipenv/utils/dependencies.py", line 103, in get_vcs_deps
    with temp_path(), locked_repository(requirement) as repo:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/pipenv/utils/dependencies.py", line 315, in locked_repository
    with requirement.req.locked_vcs_repo(src_dir=src_dir) as repo:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2193, in locked_vcs_repo
    vcsrepo = self.get_vcs_repo(src_dir=src_dir)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2152, in get_vcs_repo
    vcsrepo.obtain()
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/requirementslib/models/vcs.py", line 79, in obtain
    self.repo_backend.obtain(
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/vcs/versioncontrol.py", line 521, in obtain
    self.fetch_new(dest, url, rev_options, verbosity=verbosity)
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/vcs/git.py", line 276, in fetch_new
    self.run_command(
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/vcs/versioncontrol.py", line 650, in run_command
    return call_subprocess(
  File "/usr/local/lib/python3.9/site-packages/pipenv/patched/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pipenv.patched.pip._internal.exceptions.InstallationSubprocessError: git clone --filter=blob:none https://github.com/jvkersch/pyconcorde /tmp/pipenv-7c9b568c-src/pyconcorde exited with 128
```

**Comment by Euraxluo** [comment]
i also use：
`pipenv install -v -e git+https://github.com/jvkersch/pyconcorde#egg=pyconcorde`

but not install success
infomation：

**Comment by matteius** [comment]
@Euraxluo It worked fine in ubuntu linux for me, on windows I get an error indicating an issue with the setup.py for Widnows.  I suspect you are having issue building that package with the setup.py somehow.
```
$ pipenv install -v -e git+https://github.com/jvkersch/pyconcorde#egg=pyconcorde
Using python: None
Path to python: None
Creating a virtualenv for this project...
Pipfile: C:\Users\matte\Projects\pipenv-triage\issue-5224\Pipfile
Using default python from C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\python.exe (3.10.5) to create virtualenv...
[    ] Creating virtual environment...created virtual environment CPython3.10.5.final.0-64 in 2858ms
  creator CPython3Windows(dest=C:\c\users\matte\.virtualenvs\issue-5224-CCjK2qyB, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\matte\AppData\Local\pypa\virtualenv)
    added seed packages: pip==22.2.1, setuptools==63.2.0, wheel==0.37.1
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Successfully created virtual environment!
Virtualenv location: \c\Users\matte\.virtualenvs\issue-5224-CCjK2qyB
Creating a Pipfile for this project...
Installing -e git+https://github.com/jvkersch/pyconcorde#egg=pyconcorde...
Installing package: -e git+https://github.com/jvkersch/pyconcorde#egg=pyconcorde
Writing supplied requirement line to temporary file: '-e git+https://github.com/jvkersch/pyconcorde#egg=pyconcorde'
Installing 'pyconcorde'
$ '\c\Users\matte\.virtualenvs\issue-5224-CCjK2qyB\Scripts\python.exe' -m pip install --verbose --upgrade --exists-action=i -r 'c:\users\matte\appdata\local\temp\pipenv-8hflv5mw-requirements\pipenv-rkpthj99-req
uirement.txt' -i https://pypi.org/simple
Using source directory: '\\c\\Users\\matte\\.virtualenvs\\issue-5224-CCjK2qyB\\src'
Error:  An error occurred while installing -e git+https://github.com/jvkersch/pyconcorde#egg=pyconcorde!
Error text: Using pip 22.2.1 from C:\c\Users\matte\.virtualenvs\issue-5224-CCjK2qyB\lib\site-packages\pip (python 3.10)
Obtaining pyconcorde from git+https://github.com/jvkersch/pyconcorde#egg=pyconcorde (from -r c:\users\matte\appdata\local\temp\pipenv-8hflv5mw-requirements\pipenv-rkpthj99-requirement.txt (line 1))
  Cloning https://github.com/jvkersch/pyconcorde to c:\c\users\matte\.virtualenvs\issue-5224-ccjk2qyb\src\pyconcorde
  Resolved https://github.com/jvkersch/pyconcorde to commit 1b1c3b2d739befcce43cd3c47a217d7e82b928d4
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting numpy>=1.10.0
  Using cached numpy-1.23.1-cp310-cp310-win_amd64.whl (14.6 MB)
Collecting cython>=0.22.0
  Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
Installing collected packages: numpy, cython, pyconcorde
  Running setup.py develop for pyconcorde

  Running command git version
  git version 2.37.1.windows.1
  Running command git clone --filter=blob:none --quiet https://github.com/jvkersch/pyconcorde 'C:\c\Users\matte\.virtualenvs\issue-5224-CCjK2qyB\src\pyconcorde'
  Running command git rev-parse HEAD
  1b1c3b2d739befcce43cd3c47a217d7e82b928d4
  Running command pip subprocess to install build dependencies
  Collecting setuptools
    Downloading setuptools-63.4.1-py3-none-any.whl (1.2 MB)
       ---------------------------------------- 1.2/1.2 MB 5.6 MB/s eta 0:00:00
  Collecting numpy
    Using cached numpy-1.23.1-cp310-cp310-win_amd64.whl (14.6 MB)
  Collecting Cython
    Downloading Cython-0.29.32-py2.py3-none-any.whl (986 kB)
       ------------------------------------- 986.3/986.3 kB 15.5 MB/s eta 0:00:00
  Installing collected packages: setuptools, numpy, Cython
  Successfully installed Cython-0.29.32 numpy-1.23.1 setuptools-63.4.1
  WARNING: Missing build requirements in pyproject.toml for pyconcorde from git+https://github.com/jvkersch/pyconcorde#egg=pyconcorde (from -r c:\users\matte\appdata\local\temp\pipenv-8hflv5mw-requirements\pipe
nv-rkpthj99-requirement.txt (line 1)).
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Running command Checking if build backend supports build_editable
  Running command Getting requirements to build wheel
  C:\Users\matte\AppData\Local\Temp\pip-build-env-bbrii3mk\overlay\Lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will chang
e in a later release! File: C:\c\Users\matte\.virtualenvs\issue-5224-CCjK2qyB\src\pyconcorde\concorde\_concorde.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  Compiling concorde/_concorde.pyx because it changed.
  [1/1] Cythonizing concorde/_concorde.pyx
  running egg_info
  creating pyconcorde.egg-info
  writing pyconcorde.egg-info\PKG-INFO
  writing dependency_links to pyconcorde.egg-info\dependency_links.txt
  writing requirements to pyconcorde.egg-info\requires.txt
  writing top-level names to pyconcorde.egg-info\top_level.txt
  writing manifest file 'pyconcorde.egg-info\SOURCES.txt'
  reading manifest file 'pyconcorde.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'COPYING'
  writing manifest file 'pyconcorde.egg-info\SOURCES.txt'
  Running command pip subprocess to install backend dependencies
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Installing collected packages: wheel
  Successfully installed wheel-0.37.1
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating C:\Users\matte\AppData\Local\Temp\pip-modern-metadata-gy2td9no\pyconcorde.egg-info
  writing C:\Users\matte\AppData\Local\Temp\pip-modern-metadata-gy2td9no\pyconcorde.egg-info\PKG-INFO
  writing dependency_links to C:\Users\matte\AppData\Local\Temp\pip-modern-metadata-gy2td9no\pyconcorde.egg-info\dependency_links.txt
  writing requirements to C:\Users\matte\AppData\Local\Temp\pip-modern-metadata-gy2td9no\pyconcorde.egg-info\requires.txt
  writing top-level names to C:\Users\matte\AppData\Local\Temp\pip-modern-metadata-gy2td9no\pyconcorde.egg-info\top_level.txt
  writing manifest file 'C:\Users\matte\AppData\Local\Temp\pip-modern-metadata-gy2td9no\pyconcorde.egg-info\SOURCES.txt'
  reading manifest file 'C:\Users\matte\AppData\Local\Temp\pip-modern-metadata-gy2td9no\pyconcorde.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  adding license file 'COPYING'
  writing manifest file 'C:\Users\matte\AppData\Local\Temp\pip-modern-metadata-gy2td9no\pyconcorde.egg-info\SOURCES.txt'
  creating 'C:\Users\matte\AppData\Local\Temp\pip-modern-metadata-gy2td9no\pyconcorde-0.1.0.dist-info'
  adding license file "COPYING" (matched pattern "COPYING*")
    Running command python setup.py develop
    running develop
    C:\Users\matte\AppData\Local\Temp\pip-build-env-bbrii3mk\overlay\Lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pi
p and other standards-based tools.
      warnings.warn(
    C:\Users\matte\AppData\Local\Temp\pip-build-env-bbrii3mk\overlay\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other
 standards-based tools.
      warnings.warn(
    running egg_info
    writing pyconcorde.egg-info\PKG-INFO
    writing dependency_links to pyconcorde.egg-info\dependency_links.txt
    writing requirements to pyconcorde.egg-info\requires.txt
    writing top-level names to pyconcorde.egg-info\top_level.txt
    reading manifest file 'pyconcorde.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'COPYING'
    writing manifest file 'pyconcorde.egg-info\SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "C:\c\Users\matte\.virtualenvs\issue-5224-CCjK2qyB\src\pyconcorde\setup.py", line 146, in <module>
        setup(
      File "C:\Users\matte\AppData\Local\Temp\pip-build-env-bbrii3mk\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\matte\AppData\Local\Temp\pip-build-env-bbrii3mk\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
        return run_commands(dist)
      File "C:\Users\matte\AppData\Local\Temp\pip-build-env-bbrii3mk\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
        dist.run_commands()
      File "C:\Users\matte\AppData\Local\Temp\pip-build-env-bbrii3mk\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_commands
        self.run_command(cmd)
      File "C:\Users\matte\AppData\Local\Temp\pip-build-env-bbrii3mk\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
        super().run_command(command)
      File "C:\Users\matte\AppData\Local\Temp\pip-build-env-bbrii3mk\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
        cmd_obj.run()
      File "C:\Users\matte\AppData\Local\Temp\pip-build-env-bbrii3mk\overlay\Lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "C:\Users\matte\AppData\Local\Temp\pip-build-env-bbrii3mk\overlay\Lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "C:\Users\matte\AppData\Local\Temp\pip-build-env-bbrii3mk\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
        self.distribution.run_command(command)
      File "C:\Users\matte\AppData\Local\Temp\pip-build-env-bbrii3mk\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
        super().run_command(command)
      File "C:\Users\matte\AppData\Local\Temp\pip-build-env-bbrii3mk\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
        cmd_obj.run()
      File "C:\c\Users\matte\.virtualenvs\issue-5224-CCjK2qyB\src\pyconcorde\setup.py", line 119, in run
        download_concorde_qsopt()
      File "C:\c\Users\matte\.virtualenvs\issue-5224-CCjK2qyB\src\pyconcorde\setup.py", line 76, in download_concorde_qsopt
        qsopt_a_url, qsopt_h_url = QSOPT_LOCATION[platform.system()][machine]
    KeyError: 'Windows'
    qsopt is missing, downloading
    error: subprocess-exited-with-error

    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: 'C:\c\Users\matte\.virtualenvs\issue-5224-CCjK2qyB\Scripts\python.exe' -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize

    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)

    __file__ = %r
    sys.argv[0] = __file__

    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"

    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'C:\\c\\Users\\matte\\.virtualenvs\\issue-5224-CCjK2qyB\\src\\pyconcorde\\setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: C:\c\Users\matte\.virtualenvs\issue-5224-CCjK2qyB\src\pyconcorde\
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Using pip 22.2.1 from C:\c\Users\matte\.virtualenvs\issue-5224-CCjK2qyB\lib\site-packages\pip (python 3.10)
Obtaining pyconcorde from git+https://github.com/jvkersch/pyconcorde#egg=pyconcorde
  Cloning https://github.com/jvkersch/pyconcorde to c:\c\users\matte\.virtualenvs\issue-5224-ccjk2qyb\src\pyconcorde
  Resolved https://github.com/jvkersch/pyconcorde to commit 1b1c3b2d739befcce43cd3c47a217d7e82b928d4
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting numpy>=1.10.0
  Using cached numpy-1.23.1-cp310-cp310-win_amd64.whl (14.6 MB)
Collecting cython>=0.22.0
  Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
Installing collected packages: numpy, cython, pyconcorde
  Running setup.py develop for pyconcorde

Installation Failed
```

**Comment by Euraxluo** [comment]
i work in devcontainer，image: python:3.9


i can work in pipenv shell，look like good。

not raise
`Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
ERROR:pip.subprocessor:[present-rich] git clone --filter=blob:none https://github.com/jvkersch/pyconcorde /tmp/pipenv-46e050sg-src/pyconcorde exited with 128
Traceback (most recent call last)
`

infomation

root@1ca72d4191f6:/workspaces/quantum-vrp# pipenv shell
Launching subshell in virtual environment...
root@1ca72d4191f6:/workspaces/quantum-vrp#  . /workspaces/quantum-vrp/.venv/bin/activate
(quantum-vrp) root@1ca72d4191f6:/workspaces/quantum-vrp# pip install -v -e git+https://github.com/jvkersch/pyconcorde#egg=pyconcorde
Using pip 22.2.2 from /workspaces/quantum-vrp/.venv/lib/python3.9/site-packages/pip (python 3.9)
Obtaining pyconcorde from git+https://github.com/jvkersch/pyconcorde#egg=pyconcorde
  Running command git config --get-regexp 'remote\..*\.url'
  remote.origin.url https://github.com/jvkersch/pyconcorde
  Updating ./.venv/src/pyconcorde clone
  Running command git version
  git version 2.30.2
  Running command git fetch -q --tags
  Running command git show-ref HEAD
  1b1c3b2d739befcce43cd3c47a217d7e82b928d4 refs/remotes/origin/HEAD
  Running command git reset --hard -q 1b1c3b2d739befcce43cd3c47a217d7e82b928d4
  Running command pip subprocess to install build dependencies
  Collecting setuptools
    Downloading setuptools-63.4.1-py3-none-any.whl (1.2 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 20.0 kB/s eta 0:00:00
  Collecting numpy
    Downloading numpy-1.23.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)

**Comment by Euraxluo** [comment]
Maybe this is a problem that runs git in the process

**Comment by matteius** [comment]
@Euraxluo Does your dev container have git installed?

**Comment by Euraxluo** [comment]
yes，pipenv shell Run in the same development container

**Comment by matteius** [comment]
@Euraxluo do you have a Dockerfile that shows the issue happening with `image: python:3.9`?  Also, `pipenv=2022.8.15` was just released, you might check again.

**Comment by Euraxluo** [comment]
ok
i will try
