### ISSUE TITLE
pipenv fails to install my repo: pipenv 2022.8.24

### ISSUE THREAD

**Issue by RAYemelyanova** [pypa/pipenv#5295]
### Issue description

pipenv install fails with new version (2022.8.24) for my github repo.

This morning I made some changes to my github repo, committed to a new branch and made a merge request. None of the changes touched pipenv settings, or changed the Pipfile. To my surprise, a couple of jobs which run pipenv install --dev --python=3.8 --skip-lock failed even before they seem to have installed any packages. 

So I spun up a container with ubuntu:latest, built python 3.8 from source, installed git, checked out my repo and followed each command my github runner had followed. When I got to the pipenv install --dev --python=3.8 --skip-lock command, I got an error.

### Expected result

I expected that, as usual, pipenv install --dev --python=3.8 --skip-lock would work.

### Actual result

This command failed, with the following error trace:

```
 Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 3739, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 3400, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 2711, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 966, in _parse_name_from_line
    self._requirement = init_requirement(self.line)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/utils.py", line 194, in init_requirement
    req = Requirement.parse(name)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3139, in parse
    req, = parse_requirements(s)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3084, in parse_requirements
    yield Requirement(line)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3094, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 100, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'.#egg='": Expected W:(abcd...)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/cli/options.py", line 56, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/cli/command.py", line 233, in install
    do_install(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/core.py", line 2064, in do_install
    do_init(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/core.py", line 1333, in do_init
    do_install_dependencies(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/core.py", line 861, in do_install_dependencies
    batch_install(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/core.py", line 752, in batch_install
    dep.is_direct_url
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2856, in is_direct_url
    or (self.line_instance.is_direct_url or self.req.parsed_line.is_direct_url)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2554, in line_instance
    self.line_instance = self.get_line_instance()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2548, in get_line_instance
    return Line(line)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 173, in __init__
    self.parse()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1304, in parse
    self.parse_name()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 1027, in parse_name
    name = self._parse_name_from_line()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 968, in _parse_name_from_line
    raise RequirementError(
pipenv.vendor.requirementslib.exceptions.RequirementError: Failed parsing requirement from '.#egg='
```

### Steps to replicate
```
docker run -it ubuntu
```
Then, inside the ubuntu container:
```
apt-get update
apt-get upgrade

apt-get install git
apt-get install -y make build-essential libssl-dev zlib1g-dev \
       libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
       libncurses5-dev libncursesw5-dev xz-utils tk-dev
apt-get install python3-pip

wget https://www.python.org/ftp/python/3.8.13/Python-3.8.13.tgz
tar xvf Python-3.8.13.tgz
cd Python-3.8.13
./configure --enable-optimizations --with-ensurepip=install
make -j 8
make altinstall
python3.8 --version
cd ~

git config --global --add safe.directory /home/runner/work/diffcalc_API/diffcalc_API
git init /home/runner/work/diffcalc_API/diffcalc_API
cd /home/runner/work/diffcalc_API/diffcalc_API/
git remote add origin https://github.com/RAYemelyanova/diffcalc_API
git config --local gc.auto 0
git config --local --name-only --get-regexp core\.sshCommand
git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*
git branch --list --remote origin/addResponseModels
git rev-parse refs/remotes/origin/addResponseModels
git checkout --progress --force -B addResponseModels refs/remotes/origin/addResponseModels

sed -i 's/editable *= *true/editable = false/' Pipfile


pip install pipenv
pipenv install --python 3.8 --dev --skip-lock
```

HOWEVER, running pip uninstall pipenv and then installing pipenv 2022.8.5, and re-running the pip install command, pipenv installs fine.

-------------------------------------------------------------------------------

 `$ pipenv --support` yields something that's over 65565 characters, so I don't know how I can post it here. Just look at the Pipfile.lock on the github branch addResponseModels at  https://github.com/RAYemelyanova/diffcalc_API

**Comment by matteius** [comment]
@RAYemelyanova I believe the problem is that lock file contains `pipenv` itself:

```
        "pipenv": {
            "hashes": [
                "sha256:6cc26b3b2095c2fbc71a5157443e98d80f779b0613e201bf77f745258ee036fb",
                "sha256:e9333cdd365aeb9c3f9460ac2d84c4750e3ffa8e766fe3d5de03d4496b55d851"
            ],
            "markers": "python_version >= '3.7'",
            "version": "==2022.8.5"
        },
```


So you're uninstalling `the latest version of pipenv and replacing it with an older one is problematic -- I would suggest leaving `pipenv` out of the `Pipfile` and `Pipfile.lock` altogether.

**Comment by RAYemelyanova** [comment]
Ah, I see. Thanks for clarifying.
