### ISSUE TITLE
Pipenv install fails in github actions since v2022.10.9

### ISSUE THREAD

**Issue by DaBors** [pypa/pipenv#5403]
### Issue description

Pipenv install fails in github action after [v2022.10.9](https://github.com/pypa/pipenv/releases/tag/v2022.10.9), the issue is most likely caused by [#5387](https://github.com/pypa/pipenv/pull/5387)

### Expected result

Pipenv should run correctly without an error

### Actual result

```
Run pipenv install -r requirements.txt --skip-lock --python 3.8
  pipenv install -r requirements.txt --skip-lock --python 3.8
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.14/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.14/x64/lib
    SSH_AUTH_SOCK: /tmp/ssh-bOVTagIsyJn5/agent.1669
    SSH_AGENT_PID: 1670
Creating a virtualenv for this project...
Pipfile: /home/runner/work/yenrich/yenrich/Pipfile
Using /opt/hostedtoolcache/Python/3.8.14/x64/bin/python3.8 (3.8.14) to create virtualenv...
created virtual environment CPython3.8.14.final.0-64 in 88[2](https://github.com/shikarkhane/yenrich/actions/runs/3227256007/jobs/5281823949#step:6:2)ms
  creator Venv(dest=/home/runner/.local/share/virtualenvs/yenrich-e1Oq6JPt, clear=False, no_vcs_ignore=False, global=False, describe=CPython[3](https://github.com/shikarkhane/yenrich/actions/runs/3227256007/jobs/5281823949#step:6:3)Posix)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/runner/.local/share/virtualenv)
    added seed packages: pip==22.2.2, setuptools==65.3.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator


Successfully created virtual environment!
Virtualenv location: /home/runner/.local/share/virtualenvs/yenrich-e1Oq6JPt
Creating a Pipfile for this project...
Requirements file provided! Importing into Pipfile...
Installing dependencies from Pipfile...
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.1[4](https://github.com/shikarkhane/yenrich/actions/runs/3227256007/jobs/5281823949#step:6:4)/x64/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/cli/options.py", line [5](https://github.com/shikarkhane/yenrich/actions/runs/3227256007/jobs/5281823949#step:6:5)7, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/opt/hostedtoolcache/Python/3.8.14/x[6](https://github.com/shikarkhane/yenrich/actions/runs/3227256007/jobs/5281823949#step:6:6)4/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line [7](https://github.com/shikarkhane/yenrich/actions/runs/3227256007/jobs/5281823949#step:6:7)54, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.[8](https://github.com/shikarkhane/yenrich/actions/runs/3227256007/jobs/5281823949#step:6:8).14/x64/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/cli/command.py", line 236, in install
    do_install(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/core.py", line 2205, in do_install
    do_init(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/core.py", line 1313, in do_init
    do_install_dependencies(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/core.py", line 78[9](https://github.com/shikarkhane/yenrich/actions/runs/3227256007/jobs/5281823949#step:6:10), in do_install_dependencies
    lockfile = project.get_or_create_lockfile(
  File "/opt/hostedtoolcache/Python/3.8.[14](https://github.com/shikarkhane/yenrich/actions/runs/3227256007/jobs/5281823949#step:6:15)/x64/lib/python3.8/site-packages/pipenv/project.py", line 7[22](https://github.com/shikarkhane/yenrich/actions/runs/3227256007/jobs/5281823949#step:6:23), in get_or_create_lockfile
    _lockfile = self._lockfile(categories=categories)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/project.py", line 584, in _lockfile
    plette.Pipfile.load(pf), categories=categories
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/vendor/plette/pipfiles.py", line 59, in load
    return cls(data)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/vendor/plette/models/base.py", line 49, in __init__
    self.validate(data)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/vendor/plette/pipfiles.py", line 43, in validate
    klass.validate(data[key])
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/vendor/plette/models/base.py", line 81, in validate
    return validate(cls, data)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/pipenv/vendor/plette/models/base.py", line [38](https://github.com/shikarkhane/yenrich/actions/runs/3227256007/jobs/5281823949#step:6:39), in validate
    raise ValidationError(data, v)
pipenv.vendor.plette.models.base.ValidationError: {'python_version': '3.8', 'python_full_version': '3.8.14'}
python_full_version: 'python_version' must not be present with 'python_full_version'
python_version: 'python_full_version' must not be present with 'python_version'
Error: Process completed with exit code 1.
```

### Steps to replicate

Here is our github action yaml:

```
name: Zappa Deploy DEV

on:
  push:
    branches: [ dev ]

jobs:
  zappa_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-full-version: [ 3.8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pipenv, libpq, and pandoc
        run: |
          sudo apt-get install libpq-dev -y
          python -m pip install --upgrade pip
          pip install pipenv

      #    - name: Cache pipenv virtualenv
      #      id: cache-pipenv
      #      uses: actions/cache@v1
      #      with:
      #        path: ~/.local/share/virtualenvs
      #        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        #      if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install -r requirements.txt --skip-lock --python 3.8
        #run: pip install -r requirements.txt

      - name: Zappa deploy to dev
        run: pipenv run zappa update -s github_action_zappa_settings.json dev
        #run: zappa update -s github_action_zappa_settings.json dev
```

Note: Changing pipenv version from latest to 2022.10.4 in the github action yaml file will resolve the issue.
pip install pipenv==2022.10.4

**Comment by oz123** [comment]
You analysis is correct. Have you tried using pipenv==2022.10.12?
