### ISSUE TITLE
2022.4.8 last version to support python 3.6 environments?

### ISSUE THREAD

**Issue by jooon** [pypa/pipenv#5406]
### Issue description

2022.10.12 (or any version after 2022.4.8) can't lock dependencies in a python 3.6 environment.

### Expected result

It is quite clear that pipenv itself can't be run with python 3.6 after 2022.4.8, but the way it uses virtualenvs, I thought it would still be possible to use it in the pipenv environment. Even the documentation still mentions 3.6:

https://pipenv.pypa.io/en/latest/basics/#specifying-versions-of-python

> Use Python3.6:
> ```
> $ pipenv --python 3.6
> ```
> 

### Actual result

```
$ pipenv --python 3.6 install six
...
  File "/home/jon/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/project.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

✘ Installation Failed 
```

### Steps to replicate

Let's make sure we have python3.6 and python3.10 and pipenv==2022.10.12 installed.

```
$ python3.6 --version
Python 3.6.15
$ python3.10 --version
Python 3.10.8
$ pipx install pipenv==2022.10.12
  installed package pipenv 2022.10.12, installed using Python 3.10.8
  These apps are now globally available
    - pipenv
    - pipenv-resolver
done! ✨ 🌟 ✨
$ pipenv --version
pipenv, version 2022.10.12
```

In a clean directory with no previous pipenv environment or Pipfile:

```
$ mkdir /tmp/pipenv-py36
$ cd /tmp/pipenv-py36/
$ pipenv --python 3.6 install six
Creating a virtualenv for this project...
Pipfile: /tmp/pipenv-py36/Pipfile
Using /home/jon/.pyenv/versions/3.6.15/bin/python3.6m (3.6.15) to create virtualenv...
⠹ Creating virtual environment...created virtual environment CPython3.6.15.final.0-64 in 109ms
  creator Venv(dest=/home/jon/.local/share/virtualenvs/pipenv-py36-WOyFbEqH, clear=False, no_vcs_ignore=False, global=False, describe=CPython3Posix)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/jon/.local/share/virtualenv)
    added seed packages: pip==21.3.1, setuptools==59.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/jon/.local/share/virtualenvs/pipenv-py36-WOyFbEqH
Creating a Pipfile for this project...
Installing six...
Error:  An error occurred while installing six!
Error text: 
Traceback (most recent call last):
  File "/home/jon/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/patched/pip/__pip-runner__.py", line 36, in <module>
    runpy.run_module("pip", run_name="__main__", alter_sys=True)
  File "/home/jon/.pyenv/versions/3.6.15/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/jon/.pyenv/versions/3.6.15/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/jon/.pyenv/versions/3.6.15/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jon/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/patched/pip/__main__.py", line 35, in <module>
    spec.loader.exec_module(pipenv)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jon/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/__init__.py", line 58, in <module>
    from .cli import cli
  File "/home/jon/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/cli/__init__.py", line 1, in <module>
    from .command import cli  # noqa
  File "/home/jon/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/cli/command.py", line 7, in <module>
    from pipenv.cli.options import (
  File "/home/jon/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/cli/options.py", line 3, in <module>
    from pipenv.project import Project
  File "/home/jon/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/project.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

✘ Installation Failed 
```

Remove pipenv environment and Pipfile and try 2022.4.8 instead. 

```
$ pipenv --rm; rm -f Pipfile
Removing virtualenv (/home/jon/.local/share/virtualenvs/pipenv-py36-WOyFbEqH)...
$ pipx uninstall pipenv
uninstalled pipenv! ✨ 🌟 ✨
$ pipx install pipenv==2022.4.8
  installed package pipenv 2022.4.8, installed using Python 3.10.8
  These apps are now globally available
    - pipenv
    - pipenv-resolver
done! ✨ 🌟 ✨
$ pipenv --version
pipenv, version 2022.4.8
$ pipenv --python 3.6 install six
Creating a virtualenv for this project...
Pipfile: /tmp/pipenv-py36/Pipfile
Using /home/jon/.pyenv/versions/3.6.15/bin/python3.6m (3.6.15) to create virtualenv...
⠙ Creating virtual environment...created virtual environment CPython3.6.15.final.0-64 in 79ms
  creator CPython3Posix(dest=/home/jon/.local/share/virtualenvs/pipenv-py36-WOyFbEqH, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/jon/.local/share/virtualenv)
    added seed packages: pip==21.3.1, setuptools==59.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/jon/.local/share/virtualenvs/pipenv-py36-WOyFbEqH
Creating a Pipfile for this project...
Installing six...
Adding six to Pipfile's [packages]...
✔ Installation Succeeded 
Pipfile.lock (fa1af0) out of date, updating to (ae23d6)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Updated Pipfile.lock (ae23d6)!
Installing dependencies from Pipfile.lock (ae23d6)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

**Comment by matteius** [comment]
@jooon You are correct -- python 3.6 support was dropped some 6 months after python 3.6 was EOL, and it has allowed us to begin simplifying the code base.  There will be no additional support for python 3.6

**Comment by frostming** [comment]
Some code(specifically, the resolver) must be run with the virtualenv Python, so although it allows creating python 3.6 venvs, you can't use pipenv with Python 3.6.
