### ISSUE TITLE
pipenv install --python 3.6.7 fails to create a lock file. 

### ISSUE THREAD

**Issue by Victor-Villacis** [pypa/pipenv#5417]
### Issue description
When creating a new project. I run the command `pipenv install --python 3.6.7` it does creates the pipenv environment with the specified python 3.6.7 version. However, it errors out when creating the Pipfile.lock. Reason being is that the Pipfile contains 

```
[requires]
python_version = "3.6"
python_full_version = "3.6.7"
```

Deleting one or the other and then running `pipenv lock` or `pipenv update` fixes the issues.  However, this is a manual process. I am installing python versions with `pyenv install 3.6.7`

### Expected result

For the environment to be created with a Pipfile.lock and no errors. 

### Actual result

<details><summary>Pipfile.lock not found, creating...</summary>Traceback (most recent call last):
  File "/home/victor/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/cli/options.py", line 57, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/cli/command.py", line 236, in install
    do_install(
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/core.py", line 2204, in do_install
    do_init(
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/core.py", line 1303, in do_init
    do_lock(
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/core.py", line 1070, in do_lock
    lockfile = project._lockfile(categories=lockfile_categories)
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/project.py", line 581, in _lockfile
    plette.Pipfile.load(pf), categories=categories
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/vendor/plette/pipfiles.py", line 59, in load
    return cls(data)
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/vendor/plette/models/base.py", line 49, in __init__
    self.validate(data)
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/vendor/plette/pipfiles.py", line 43, in validate
    klass.validate(data[key])
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/vendor/plette/models/base.py", line 81, in validate
    return validate(cls, data)
  File "/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv/vendor/plette/models/base.py", line 38, in validate
    raise ValidationError(data, v)
pipenv.vendor.plette.models.base.ValidationError: {'python_version': '3.6', 'python_full_version': '3.6.7'}
python_full_version: 'python_version' must not be present with 'python_full_version'
python_version: 'python_full_version' must not be present with 'python_version'</details>

### Steps to replicate

`mkdir newProject`
`cd newProject`
`pyenv install 3.6.7`
`pyenv local 3.6.7`
`pipenv install --python 3.6.7`
ERRORS out when attempting to create the Pipfile.lock

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.10.9'`

Pipenv location: `'/home/victor/.local/pipx/venvs/pipenv/lib/python3.8/site-packages/pipenv'`

Python location: `'/home/victor/.local/pipx/venvs/pipenv/bin/python'`

OS Name: `'posix'`

User pip version: `'22.2.2'`

user Python installations found:

  - `3.8.10`: `/usr/bin/python3.8`
  - `3.8.10`: `/usr/bin/python3`
  - `3.8.10`: `/bin/python3.8`
  - `3.8.10`: `/bin/python3`
  - `3.6.8`: `/home/victor/.pyenv/versions/3.6.8/bin/python3`
  - `3.6.7`: `/home/victor/.pyenv/versions/3.6.7/bin/python3`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`
  - `2.7.18`: `/bin/python2`
  - `2.7.18`: `/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.8.10',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.10.102.1-microsoft-standard-WSL2',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Wed Mar 2 00:30:59 UTC 2022',
 'python_full_version': '3.8.10',
 'python_version': '3.8',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `PYENV_SHELL`
  - `WSL_DISTRO_NAME`
  - `WT_SESSION`
  - `NAME`
  - `PWD`
  - `LOGNAME`
  - `MOTD_SHOWN`
  - `HOME`
  - `LANG`
  - `WSL_INTEROP`
  - `LS_COLORS`
  - `WAYLAND_DISPLAY`
  - `LESSCLOSE`
  - `TERM`
  - `LESSOPEN`
  - `USER`
  - `DISPLAY`
  - `SHLVL`
  - `input_file`
  - `XDG_RUNTIME_DIR`
  - `PYENV_ROOT`
  - `WSLENV`
  - `XDG_DATA_DIRS`
  - `PATH`
  - `HOSTTYPE`
  - `PULSE_SERVER`
  - `WT_PROFILE_ID`
  - `OLDPWD`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/victor/.local/bin:/home/victor/bin:/home/victor/.pyenv/shims:/home/victor/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Python310/Scripts/:/mnt/c/Python310/:/mnt/c/Program Files (x86)/Razer Chroma SDK/bin:/mnt/c/Program Files/Razer Chroma SDK/bin:/mnt/c/Program Files/Oculus/Support/oculus-runtime:/mnt/c/Python39/Scripts/:/mnt/c/Python39/:/mnt/c/Program Files (x86)/Razer/ChromaBroadcast/bin:/mnt/c/Program Files/Razer/ChromaBroadcast/bin:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Users/Victor/AppData/Local/Microsoft/WindowsApps:/mnt/c/Program Files/Git/cmd:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Users/Victor/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Amazon/AWSCLIV2/:/mnt/c/Program Files/PuTTY/:/mnt/c/Program Files/nodejs/:/mnt/c/Program Files/PostgreSQL/14/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/Program Files/Microsoft SQL Server/150/Tools/Binn/:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/:/mnt/c/Program Files/MySQL/MySQL Shell 8.0/bin/:/mnt/c/Ruby30-x64/bin:/mnt/c/Users/Victor/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files/heroku/bin:/mnt/c/Users/Victor/AppData/Roaming/npm/node_modules/yarn/bin:/mnt/c/Program Files (x86)/BrowserStackLocal/:/mnt/c/Program Files/Multipass/bin:/mnt/c/Users/Victor/AppData/Roaming/npm:/mnt/c/sqllite3:/mnt/c/Users/Victor/.dotnet/tools:/mnt/c/Users/Victor/AppData/Local/Programs/Hyper/resources/bin:/snap/bin:/home/victor/.local/bin:/home/victor/.local/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/home/victor/NewProject`

---------------------------

Contents of `Pipfile` ('/home/victor/NewProject/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.6"
python_full_version = "3.6.7"

```

</details>

**Comment by oz123** [comment]
We no longer support Python3.6.
