### ISSUE TITLE
Wrong path detection , got OSError: [WinError 123]

### ISSUE THREAD

**Issue by eromoe** [pypa/pipenv#5423]
Error detail :
```
E:\MY_WORK\notebooks\modin_exercises>pipenv install
Traceback (most recent call last):
  File "C:\Users\ufo\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ufo\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ufo\anaconda3\Scripts\pipenv.exe\__main__.py", line 7, in <module>
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\vendor\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\cli\options.py", line 57, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\vendor\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\vendor\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\vendor\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\vendor\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\vendor\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\vendor\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\cli\command.py", line 236, in install
    do_install(
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\core.py", line 2076, in do_install
    ensure_project(
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\core.py", line 529, in ensure_project
    ensure_virtualenv(
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\core.py", line 450, in ensure_virtualenv
    python = ensure_python(project, three=three, python=python)
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\core.py", line 339, in ensure_python
    path_to_python = find_a_system_python(python)
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\core.py", line 305, in find_a_system_python
    return next(iter(finder.find_all_python_versions()), None)
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 307, in find_all_python_versions
    python_version_dict = getattr(self.system_path, "python_version_dict", {})
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 115, in system_path
    self._system_path = self.create_system_path()
  File "C:\Users\ufo\anaconda3\lib\site-packages\pipenv\vendor\pythonfinder\pythonfinder.py", line 77, in create_system_path
    return pyfinder_path.SystemPath.create(
  File "C:\Users\ufo\anaconda3\Lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 680, in create
    {
  File "C:\Users\ufo\anaconda3\Lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 685, in <dictcomp>
    if exists_and_is_accessible(p)
  File "C:\Users\ufo\anaconda3\Lib\site-packages\pipenv\vendor\pythonfinder\models\path.py", line 68, in exists_and_is_accessible
    return path.exists()
  File "C:\Users\ufo\anaconda3\lib\pathlib.py", line 1400, in exists
    self.stat()
  File "C:\Users\ufo\anaconda3\lib\pathlib.py", line 1197, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'E:\\MY_WORK\\notebooks\\modin_exercises\\#C:\\Users\\ufo\\anaconda3\\Library\\mingw-w64\\bin'
```

After some research, I found it cause by environment variable : 
![image](https://user-images.githubusercontent.com/3938751/196837082-c329a859-625f-495d-9e11-6807825a1f1a.png)

I comment this line,  but recognize by pipenv , this is wrong behaviour.

**Comment by oz123** [comment]
As @frostming said above, your system has an environment variable called:

```
#C:\\Users\\ufo\\anaconda3\\Library\\mingw-w64\\bin'
```
Remove this completely and the issue should be solved.

**Comment by eromoe** [comment]
I just wanted to express pipenv should not affect by this .

**Comment by oz123** [comment]
Why do you think pipenv should handle wrong usage of environment variables? There is a limit where software should break. This is definitely such a case.
If you used an ORM would you expect it to correct your wrong SQL?
Eventually, errors should stop the execution of a program.
