### ISSUE TITLE
Local Modules Not in PATH

### ISSUE THREAD

**Issue by MattG-Everworks** [pypa/pipenv#5442]
### Issue description

I am using the python launcher for dev with pipenv on Windows. The specific command is "py -m pipenv run python \<myprogram\>" where myprogram is structured as a directory with an \_\_init\_\_.py, \_\_main\_\_.py, and some modules. This method of calling the program was working at one point in time, but after installing git bash I am no long able to use the command. It seems the directory is no longer in the venv PATH.

Basic Project Structure:
```
- myproject
   L myprogram
     L __init__.py
     L __main__.py
     L module1.py
     L module2.py
   L Pipfile
   L Pipfile.lock
```

### Expected result

I expect the project directory to be in the path.

### Actual result

I get the following error.

```
Loading .env environment variables...
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\OneDrive - Everworks\Desktop\My Files\code\python\PycharmProjects\ExcelTagTool\exceltagtool\__main__.py", line 13, in <module>
    from exceltagtool import exceltools as et, plctools as pt
ModuleNotFoundError: No module named 'exceltagtool'
```

If I add "PYTHONPATH=${py -m pipenv --which};" to the .env file, everything works as expected.

### Steps to replicate

Run py -m pipenv run python <myprogram> with the stucture outlined above on Windows after installing Git Bash. I'm uncertain if this issue will be reproducible.

-------------------------------------------------------------------------------

```json
{
    "_meta": {
        "hash": {
            "sha256": "73600e3ab1aed617b935be01694e48907caf631f01519f952c31ba75feb4acb9"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.10"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "pycomm3": {
            "hashes": [
                "sha256:4698d979f27829135b7bbd53a435ce84142301d4fbdda61334c74c70bd027592",
                "sha256:cb6f41c49269e5ba7dd9c5ded319b8f9964a26c04246a52f2ebd906af04f3c1a"
            ],
            "index": "pypi",
            "version": "==1.2.10"
        },
        "pywin32": {
            "hashes": [
                "sha256:25746d841201fd9f96b648a248f731c1dec851c9a08b8e33da8b56148e4c65cc",
                "sha256:30c53d6ce44c12a316a06c153ea74152d3b1342610f1b99d40ba2795e5af0269",
                "sha256:3c7bacf5e24298c86314f03fa20e16558a4e4138fc34615d7de4070c23e65af3",
                "sha256:4f32145913a2447736dad62495199a8e280a77a0ca662daa2332acf849f0be48",
                "sha256:7ffa0c0fa4ae4077e8b8aa73800540ef8c24530057768c3ac57c609f99a14fd4",
                "sha256:94037b5259701988954931333aafd39cf897e990852115656b014ce72e052e96",
                "sha256:bb2ea2aa81e96eee6a6b79d87e1d1648d3f8b87f9a64499e0b92b30d141e76df",
                "sha256:be253e7b14bc601718f014d2832e4c18a5b023cbe72db826da63df76b77507a1",
                "sha256:cbbe34dad39bdbaa2889a424d28752f1b4971939b14b1bb48cbf0182a3bcfc43",
                "sha256:d24a3382f013b21aa24a5cfbfad5a2cd9926610c0affde3e8ab5b3d7dbcf4ac9",
                "sha256:d3ee45adff48e0551d1aa60d2ec066fec006083b791f5c3527c40cd8aefac71f",
                "sha256:de9827c23321dcf43d2f288f09f3b6d772fee11e809015bdae9e69fe13213988",
                "sha256:ead865a2e179b30fb717831f73cf4373401fc62fbc3455a0889a7ddac848f83e",
                "sha256:f64c0377cf01b61bd5e76c25e1480ca8ab3b73f0c4add50538d332afdf8f69c5"
            ],
            "index": "pypi",
            "version": "==304"
        },
        "wmi": {
            "hashes": [
                "sha256:1d6b085e5c445141c475476000b661f60fff1aaa19f76bf82b7abb92e0ff4942",
                "sha256:b6a6be5711b1b6c8d55bda7a8befd75c48c12b770b9d227d31c1737dbf0d40a6"
            ],
            "index": "pypi",
            "version": "==1.5.1"
        }
    },
    "develop": {}
}

```

**Comment by MattG-Everworks** [comment]
It turns out that this issue was caused by improper imports. The confusing thing is that it worked at one point in time, and now that I understand the issue, I have no idea why it ever did work.
