### ISSUE TITLE
Unable to uninstall django-moneyfield using pipenv uninstall

### ISSUE THREAD

**Issue by Jake-Mulhern** [pypa/pipenv#5514]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

Describe the issue briefly here.

I installed the package 'django-moneyfield' using the following command
```
$ pipenv install django-moneyfield
```

I then tried to uninstall the package using 
```
$ pipenv uninstall django-moneyfield
```

and received this error:
AttributeError: 'NoneType' object has no attribute 'key'

I did try to exit out of the shell and then enter the pipenv shell again but got the same results.

### Expected result

I expected the package to be uninstalled successfully.

### Actual result

Uninstalling django-moneyfield...
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/cli/options.py", line 56, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/vendor/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pipenv/cli/command.py", line 268, in uninstall
    retcode = do_uninstall(
  File "/usr/local/lib/python3.9/site-packages/pipenv/core.py", line 2373, in do_uninstall
    with project.environment.activated():
  File "/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/pipenv/environment.py", line 987, in activated
    if extra_dist not in self.get_working_set():
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 626, in __contains__
    return self.by_key.get(dist.key) == dist
AttributeError: 'NoneType' object has no attribute 'key'

### Steps to replicate

1. Install django-moneyfield
$ pipenv install django-moneyfield

2. Uninstall django-moneyfield
$ pipenv uninstall django-moneyfield

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.5.2'`

Pipenv location: `'/usr/local/lib/python3.9/site-packages/pipenv'`

Python location: `'/usr/local/opt/python@3.9/bin/python3.9'`

Python installations found:

  - `3.10.8`: `/Users/jacobmulhern/.local/share/virtualenvs/undriveable-backend-vC8dl01Q/bin/python3`
  - `3.10.8`: `/Users/jacobmulhern/.local/share/virtualenvs/undriveable-backend-vC8dl01Q/bin/python`
  - `3.10.8`: `/Users/jacobmulhern/.local/share/virtualenvs/undriveable-backend-vC8dl01Q/bin/python3`
  - `3.10.8`: `/Users/jacobmulhern/.local/share/virtualenvs/undriveable-backend-vC8dl01Q/bin/python`
  - `3.10.8`: `/usr/local/bin/python3`
  - `3.10.8`: `/usr/local/bin/python`
  - `3.10.4`: `/Users/jacobmulhern/.pyenv/versions/3.10.4/bin/python3`
  - `3.9.15`: `/usr/local/bin/python3.9`
  - `3.8.9`: `/usr/bin/python3`
  - `3.7.9`: `/Users/jacobmulhern/.pyenv/versions/3.7.9/bin/python3`
  - `3.6.15`: `/Users/jacobmulhern/.pyenv/versions/3.6.15/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.15',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '21.4.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT '
                     '2022; root:xnu-8020.101.4~15/RELEASE_X86_64',
 'python_full_version': '3.9.15',
 'python_version': '3.9',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `__CFBundleIdentifier`
  - `TMPDIR`
  - `XPC_FLAGS`
  - `LaunchInstanceID`
  - `TERM`
  - `SSH_AUTH_SOCK`
  - `SECURITYSESSIONID`
  - `XPC_SERVICE_NAME`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `SHELL`
  - `HOME`
  - `LOGNAME`
  - `USER`
  - `PATH`
  - `SHLVL`
  - `PWD`
  - `OLDPWD`
  - `ANDROID_HOME`
  - `PYENV_ROOT`
  - `PYENV_SHELL`
  - `PYENV_VIRTUALENV_INIT`
  - `LDFLAGS`
  - `CPPFLAGS`
  - `PKG_CONFIG_PATH`
  - `__CF_USER_TEXT_ENCODING`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `SECRET_KEY`
  - `DEBUG`
  - `ALLOWED_HOSTS`
  - `POSTGRES_NAME`
  - `POSTGRES_USER`
  - `POSTGRES_PASSWORD`
  - `POSTGRES_HOST`
  - `POSTGRES_PORT`
  - `PIPENV_ACTIVE`
  - `VIRTUAL_ENV`
  - `PS1`
  - `LANG`
  - `_`
  - `PIP_SHIMS_BASE_MODULE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/Users/jacobmulhern/.local/share/virtualenvs/undriveable-backend-vC8dl01Q/bin:/usr/local/sbin:/usr/local/opt/openssl@3/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/jacobmulhern/.pyenv/shims:/usr/local/bin:/Users/jacobmulhern/.pyenv/bin:/Users/jacobmulhern/Library/Android/sdk/platform-tools:/usr/local/sbin:/usr/local/opt/openssl@3/bin:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/usr/local/bin:/Users/jacobmulhern/.pyenv/bin:/Users/jacobmulhern/.pyenv/bin:/Users/jacobmulhern/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/jacobmulhern/Library/Android/sdk/platform-tools`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/jacobmulhern/Bixly/Undriveable/undriveable-backend`
  - `VIRTUAL_ENV`: `/Users/jacobmulhern/.local/share/virtualenvs/undriveable-backend-vC8dl01Q`

---------------------------

Contents of `Pipfile` ('/Users/jacobmulhern/Bixly/Undriveable/undriveable-backend/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "*"
django-environ = "*"
djangorestframework = "*"
psycopg2 = "*"
django-moneyfield = "*"

[dev-packages]

[requires]
python_version = "3.10"

```

Contents of `Pipfile.lock` ('/Users/jacobmulhern/Bixly/Undriveable/undriveable-backend/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "52f7ad1bfe426ce882da628495efecd48d9010ad932df11c5f881c610f2ad68c"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.10"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "asgiref": {
            "hashes": [
                "sha256:1d2880b792ae8757289136f1db2b7b99100ce959b2aa57fd69dab783d05afac4",
                "sha256:4a29362a6acebe09bf1d6640db38c1dc3d9217c68e6f9f6204d72667fc19a424"
            ],
            "markers": "python_version >= '3.7'",
            "version": "==3.5.2"
        },
        "django": {
            "hashes": [
                "sha256:678bbfc8604eb246ed54e2063f0765f13b321a50526bdc8cb1f943eda7fa31f1",
                "sha256:6b1de6886cae14c7c44d188f580f8ba8da05750f544c80ae5ad43375ab293cd5"
            ],
            "index": "pypi",
            "version": "==4.1.3"
        },
        "django-environ": {
            "hashes": [
                "sha256:bff5381533056328c9ac02f71790bd5bf1cea81b1beeb648f28b81c9e83e0a21",
                "sha256:f21a5ef8cc603da1870bbf9a09b7e5577ab5f6da451b843dbcc721a7bca6b3d9"
            ],
            "index": "pypi",
            "version": "==0.9.0"
        },
        "django-moneyfield": {
            "hashes": [
                "sha256:72f129f573adc5d05a05cfbc4ba7b46fc76320dac510f6b4731ac243e76db484"
            ],
            "index": "pypi",
            "version": "==0.2.1"
        },
        "djangorestframework": {
            "hashes": [
                "sha256:579a333e6256b09489cbe0a067e66abe55c6595d8926be6b99423786334350c8",
                "sha256:eb63f58c9f218e1a7d064d17a70751f528ed4e1d35547fdade9aaf4cd103fd08"
            ],
            "index": "pypi",
            "version": "==3.14.0"
        },
        "psycopg2": {
            "hashes": [
                "sha256:093e3894d2d3c592ab0945d9eba9d139c139664dcf83a1c440b8a7aa9bb21955",
                "sha256:190d51e8c1b25a47484e52a79638a8182451d6f6dff99f26ad9bd81e5359a0fa",
                "sha256:1a5c7d7d577e0eabfcf15eb87d1e19314c8c4f0e722a301f98e0e3a65e238b4e",
                "sha256:1e5a38aa85bd660c53947bd28aeaafb6a97d70423606f1ccb044a03a1203fe4a",
                "sha256:322fd5fca0b1113677089d4ebd5222c964b1760e361f151cbb2706c4912112c5",
                "sha256:4cb9936316d88bfab614666eb9e32995e794ed0f8f6b3b718666c22819c1d7ee",
                "sha256:920bf418000dd17669d2904472efeab2b20546efd0548139618f8fa305d1d7ad",
                "sha256:922cc5f0b98a5f2b1ff481f5551b95cd04580fd6f0c72d9b22e6c0145a4840e0",
                "sha256:a5246d2e683a972e2187a8714b5c2cf8156c064629f9a9b1a873c1730d9e245a",
                "sha256:b9ac1b0d8ecc49e05e4e182694f418d27f3aedcfca854ebd6c05bb1cffa10d6d",
                "sha256:d3ef67e630b0de0779c42912fe2cbae3805ebaba30cda27fea2a3de650a9414f",
                "sha256:f5b6320dbc3cf6cfb9f25308286f9f7ab464e65cfb105b64cc9c52831748ced2",
                "sha256:fc04dd5189b90d825509caa510f20d1d504761e78b8dfb95a0ede180f71d50e5"
            ],
            "index": "pypi",
            "version": "==2.9.5"
        },
        "pytz": {
            "hashes": [
                "sha256:222439474e9c98fced559f1709d89e6c9cbf8d79c794ff3eb9f8800064291427",
                "sha256:e89512406b793ca39f5971bc999cc538ce125c0e51c27941bef4568b460095e2"
            ],
            "version": "==2022.6"
        },
        "sqlparse": {
            "hashes": [
                "sha256:0323c0ec29cd52bceabc1b4d9d579e311f3e4961b98d174201d5622a23b85e34",
                "sha256:69ca804846bb114d2ec380e4360a8a340db83f0ccf3afceeb1404df028f57268"
            ],
            "markers": "python_version >= '3.5'",
            "version": "==0.4.3"
        }
    },
    "develop": {}
}

```
</details>

**Comment by matteius** [comment]
@Jake-Mulhern I was unable to reproduce this issue:

```
matteius@matteius-VirtualBox:~/pipenv-triage$ mkdir pipenv-5514
matteius@matteius-VirtualBox:~/pipenv-triage$ cd pipenv-5514
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5514$ pipenv install django-moneyfield
Creating a virtualenv for this project...
Pipfile: /home/matteius/pipenv-triage/pipenv-5514/Pipfile
Using /home/matteius/.pyenv/versions/3.11.0/bin/python3 (3.11.0) to create virtualenv...
⠦ Creating virtual environment...created virtual environment CPython3.11.0.final.0-64 in 336ms
  creator Venv(dest=/home/matteius/.virtualenvs/pipenv-5514-UqHbiLlo, clear=False, no_vcs_ignore=False, global=False, describe=CPython3Posix)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/matteius/.local/share/virtualenv)
    added seed packages: pip==22.3.1, setuptools==65.5.1, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /home/matteius/.virtualenvs/pipenv-5514-UqHbiLlo
Creating a Pipfile for this project...
Installing django-moneyfield...
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Locking [dev-packages] dependencies...
Updated Pipfile.lock (821232339058045c4fa12b6ce9e0ef4eb3177621b2d92b5fa0396eb3a5add537)!
Installing dependencies from Pipfile.lock (add537)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5514$ cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django-moneyfield = "*"

[dev-packages]

[requires]
python_version = "3.11"
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5514$ cat Pipfile.lock 
{
    "_meta": {
        "hash": {
            "sha256": "821232339058045c4fa12b6ce9e0ef4eb3177621b2d92b5fa0396eb3a5add537"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.11"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "django-moneyfield": {
            "hashes": [
                "sha256:72f129f573adc5d05a05cfbc4ba7b46fc76320dac510f6b4731ac243e76db484"
            ],
            "index": "pypi",
            "version": "==0.2.1"
        }
    },
    "develop": {}
}
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5514$ pipenv uninstall django-moneyfield
Removing django-moneyfield from Pipfile.lock...
Removed django-moneyfield from Pipfile category packages
Uninstalling django-moneyfield...
Found existing installation: django-moneyfield 0.2.1
Uninstalling django-moneyfield-0.2.1:
  Successfully uninstalled django-moneyfield-0.2.1

Locking [packages] dependencies...
Locking [dev-packages] dependencies...
Updated Pipfile.lock (ed6d5d614626ae28e274e453164affb26694755170ccab3aa5866f093d51d3e4)!
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5514$ cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]

[dev-packages]

[requires]
python_version = "3.11"
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5514$ cat Pipfile.lock 
{
    "_meta": {
        "hash": {
            "sha256": "ed6d5d614626ae28e274e453164affb26694755170ccab3aa5866f093d51d3e4"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.11"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {},
    "develop": {}
}
matteius@matteius-VirtualBox:~/pipenv-triage/pipenv-5514$ 
```

**Comment by matteius** [comment]
@Jake-Mulhern You are on `pipenv==2022.5.2` -- please try the latest release.
