### ISSUE TITLE
AttributeError: 'WindowsPath' object has no attribute 'expanduser'

### ISSUE THREAD

**Issue by oklsw** [pypa/pipenv#5521]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 18, in <module>
    from IPython.core.application import (
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\__init__.py", line 56, in <module>
    from .terminal.embed import embed
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\terminal\embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 35, in <module>
    from .debugger import TerminalPdb, Pdb
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\terminal\debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\completer.py", line 146, in <module>
    import jedi
  File "C:\ProgramData\Anaconda3\lib\site-packages\jedi\__init__.py", line 32, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, preload_module
  File "C:\ProgramData\Anaconda3\lib\site-packages\jedi\api\__init__.py", line 13, in <module>
    import parso
  File "C:\ProgramData\Anaconda3\lib\site-packages\parso\__init__.py", line 42, in <module>
    from parso.grammar import Grammar, load_grammar
  File "C:\ProgramData\Anaconda3\lib\site-packages\parso\grammar.py", line 13, in <module>
    from parso.cache import parser_cache, load_module, try_to_save_module
  File "C:\ProgramData\Anaconda3\lib\site-packages\parso\cache.py", line 76, in <module>
    _default_cache_path = _get_default_cache_path()
  File "C:\ProgramData\Anaconda3\lib\site-packages\parso\cache.py", line 73, in _get_default_cache_path
    return dir_.expanduser()
AttributeError: 'WindowsPath' object has no attribute 'expanduser'
![gooey](https://user-images.githubusercontent.com/37338815/205490719-983db01e-6611-433a-b777-84a811d66e31.jpg)
[](url)

**Comment by matteius** [comment]
I am not sure if pipenv is compatible with Anaconda.

**Comment by oklsw** [comment]
> I am not sure if pipenv is compatible with Anaconda.

@matteius Many thinks! I can run it with Spyder.

**Comment by matteius** [comment]
Sorry @oklsw -- I didn't quite understand -- but in your original stack trace the error is happening in a package outside of pipenv:

```
File "C:\ProgramData\Anaconda3\lib\site-packages\parso\cache.py", line 73, in get_default_cache_path
return dir.expanduser()
AttributeError: 'WindowsPath' object has no attribute 'expanduser'
```

**Comment by matteius** [comment]
@oklsw Did you ever get anywhere with this?

**Comment by matteius** [comment]
I reworked pythonfinder in a major way and would like if you could recheck this issue with `pipenv==2023.5.19` @oklsw
