### ISSUE TITLE
The error from pipenv isn't clear about the which dependency is causing the parsing error.  

### ISSUE THREAD

**Issue by rahul-narkhede** [pypa/pipenv#5568]
Following statck trace was received while creating a piplock file.  The error doesn't show what dependencies are causing the error

```
Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/pkg_resources/__init__.py", line 3021, in _dep_map
      return self.__dep_map
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
      raise AttributeError(attr)
  AttributeError: _DistInfoDistribution__dep_map
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/packaging/requirements.py", line 102, in __init__
      req = REQUIREMENT.parseString(requirement_string)
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/pyparsing.py", line 1955, in parseString
      raise exc
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/pyparsing.py", line 3814, in parseImpl
      raise ParseException(instring, loc, self.errmsg, self)
  pipenv.patched.notpip._vendor.pyparsing.ParseException: Expected stringEnd, found ','  (at char 23), (line:1, col:24)
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/pkg_resources/__init__.py", line 3101, in __init__
      super(Requirement, self).__init__(requirement_string)
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/packaging/requirements.py", line 104, in __init__
      raise InvalidRequirement(
  pipenv.patched.notpip._vendor.packaging.requirements.InvalidRequirement: Parse error at "','": Expected stringEnd
  During handling of the above exception, another exception occurred:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/pipenv/resolver.py", line 766, in <module>
      main()
    File "/usr/local/lib/python3.7/site-packages/pipenv/resolver.py", line 760, in main
      _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
    File "/usr/local/lib/python3.7/site-packages/pipenv/resolver.py", line 743, in _main
      resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
    File "/usr/local/lib/python3.7/site-packages/pipenv/resolver.py", line 704, in resolve_packages
      results, resolver = resolve(
    File "/usr/local/lib/python3.7/site-packages/pipenv/resolver.py", line 685, in resolve
      return resolve_deps(
    File "/usr/local/lib/python3.7/site-packages/pipenv/utils.py", line 1377, in resolve_deps
      results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
    File "/usr/local/lib/python3.7/site-packages/pipenv/utils.py", line 1106, in actually_resolve_deps
      resolver.resolve()
    File "/usr/local/lib/python3.7/site-packages/pipenv/utils.py", line 882, in resolve
      results = resolver.resolve(self.constraints, check_supported_wheels=False)
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
      result = self._result = resolver.resolve(
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 472, in resolve
      state = resolution.resolve(requirements, max_rounds=max_rounds)
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 366, in resolve
      failure_causes = self._attempt_to_pin_criterion(name)
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 212, in _attempt_to_pin_criterion
      criteria = self._get_updated_criteria(candidate)
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/resolvelib/resolvers.py", line 202, in _get_updated_criteria
      for requirement in self._p.get_dependencies(candidate=candidate):
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/provider.py", line 197, in get_dependencies
      return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/provider.py", line 197, in <listcomp>
      return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolution/resolvelib/candidates.py", line 250, in iter_dependencies
      requires = self.dist.requires() if with_requires else ()
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/pkg_resources/__init__.py", line 2736, in requires
      dm = self._dep_map
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/pkg_resources/__init__.py", line 3023, in _dep_map
      self.__dep_map = self._compute_dependencies()
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/pkg_resources/__init__.py", line 3033, in _compute_dependencies
      reqs.extend(parse_requirements(req))
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/pkg_resources/__init__.py", line 3094, in parse_requirements
      yield Requirement(line)
    File "/usr/local/lib/python3.7/site-packages/pipenv/patched/notpip/_vendor/pkg_resources/__init__.py", line 3103, in __init__
      raise RequirementParseError(str(e))
  pipenv.patched.notpip._vendor.pkg_resources.RequirementParseError: Parse error at "','": Expected stringEnd
  ```

**Comment by matteius** [comment]
Have you tried running with --verbose?

**Comment by matteius** [comment]
You are running an incredibly old version of `pipenv` because `patched/notpip` was renamed to `patched/pip` a long time ago.
