### ISSUE TITLE
Unable to add dependecy with version construct

### ISSUE THREAD

**Issue by glensc** [pypa/pipenv#5569]
### Issue description

I want to add something to Pipfile so that pipenv requirements would generate a line:

```
backports.cached-property==1.0.2; python_version <= '3.7'
```

how can I do that?

I tried:

```
[packages]
appdirs = "==1.4.4"
attrs = "==22.2.0"
"backports.cached-property" = "==1.0.2; python_version <= '3.7'"
```

But pipenv lock resulted error:

```
pipenv.patched.pip._vendor.packaging.specifiers.InvalidSpecifier: Invalid specifier: '==1.0.2; python_version <= '3.7''
```

<details>

```
$ pipenv --version
pipenv, version 2022.12.19

$ pipenv lock
Loading .env environment variables...
Locking [packages] dependencies...
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/packaging/specifiers.py", line 634, in __init__
    parsed.add(Specifier(specifier))
               ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/packaging/specifiers.py", line 98, in __init__
    raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
pipenv.patched.pip._vendor.packaging.specifiers.InvalidSpecifier: Invalid specifier: '==1.0.2; python_version <= '3.7''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/bin/pipenv", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/cli/options.py", line 57, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/cli/command.py", line 340, in lock
    do_lock(
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/core.py", line 1190, in do_lock
    venv_resolve_deps(
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 1035, in venv_resolve_deps
    deps = convert_deps_to_pip(deps, project, include_index=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/utils/dependencies.py", line 283, in convert_deps_to_pip
    new_dep = Requirement.from_pipfile(dep_name, dep)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 2761, in from_pipfile
    r.req.specifier = SpecifierSet(_pipfile["version"])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/packaging/specifiers.py", line 636, in __init__
    parsed.add(LegacySpecifier(specifier))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/packaging/specifiers.py", line 253, in __init__
    super().__init__(spec, prereleases)
  File "/opt/homebrew/Cellar/pipenv/2022.12.19/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/packaging/specifiers.py", line 98, in __init__
    raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
pipenv.patched.pip._vendor.packaging.specifiers.InvalidSpecifier: Invalid specifier: '==1.0.2; python_version <= '3.7''

$
```

### Expected result

Describe what you expected.

### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on macOS, run the following:

    $ pipenv --support | pbcopy

If you're on Windows, run the following:

    > pipenv --support | clip

If you're on Linux, run the following:

    $ pipenv --support | xclip

**Comment by oz123** [comment]
You need to use a dict notation. Pipfile is a toml file.
Please see here
https://github.com/sarugaku/plette/tree/master/examples

**Comment by glensc** [comment]
Okay, thanks!

```diff
index d8c9d31a..e7565253 100644
--- a/Pipfile
+++ b/Pipfile
@@ -8,7 +8,7 @@ verify_ssl = true
 [packages]
 appdirs = "==1.4.4"
 attrs = "==22.2.0"
-"backports.cached-property" = "==1.0.2"
+"backports.cached-property" = {version="==1.0.2", python_version="<='3.7'"}
 certifi = "==2022.12.7"
 charset-normalizer = "==3.0.1"
 click = "==8.1.3"
```

```
➜ pipenv lock
Loading .env environment variables...
Locking [packages] dependencies...
⠹ Resolving dependencies...Warning: backports.cached-property==1.0.2 ; python_version <= '3.7' doesn't match your environment, its dependencies won't be resolved.
Locking [dev-packages] dependencies...
Updated Pipfile.lock (fe0ad06f8c96044a83ee3f81adb53ce096463cb9fc91f9f9dc94e57af4d9cb1d)!
```

```
➜ pipenv requirements | sed -e 's/ ;/;/g' | grep backports.cached-property
Loading .env environment variables...
backports.cached-property==1.0.2; python_version <= '3.7'
```

you may add it to your examples there. 

ps:


🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)

NOTE: edit your post and fix it with a permalink!

PS: gitlab has a bug and you need to reload a page before `y` works.

**Comment by glensc** [comment]
still a question how do I describe "and"?

```json
            "markers": "python_version >= '3.7' and python_version < '4'",
```

**Comment by glensc** [comment]
```toml
pfzy = {version="==0.3.4", python_version=">='3.7' and <'4.0'"}
```

```
    raise InvalidMarker(
pipenv.patched.pip._vendor.packaging.markers.InvalidMarker: Invalid marker: "python_version >='3.7' and <'4.0'", parse error at "and <'4."
```

----

```toml
pfzy = {version="==0.3.4", python_version=">='3.7'", python_version="<'4.0'"}
```

```
    raise TomlDecodeError(str(err), original, pos)
pipenv.vendor.toml.decoder.TomlDecodeError: Duplicate keys! (line 20 column 1 char 466)
````

----

I'm actually confused, where those `python_version` come in first place? some of them are added automatically if I just `pipenv install <package>`

**Comment by oz123** [comment]
> still a question how do I describe "and"?
> 
> ```json
>             "markers": "python_version >= '3.7' and python_version < '4'",
> ```

Legitimate question. I don't know yet. We'll have to figure this in plette and or requirementslib.
Can you re-open this issue in the Plette repo?

Thanks for the idea of adding your example. I will consider this.

**Comment by glensc** [comment]
I realized I don't need the upper bound and other "and" clauses, so I just set ">=" for them:
- https://github.com/Taxel/PlexTraktSync/pull/1368

but ideas how they ended in first place in my Pipfile.lock and why should I declare them in Pipfile? I'm declaring them now in pipfile because dependabot loses them, not stable updating my Pipfile.lock:
- https://github.com/dependabot/dependabot-core/issues/6091

**Comment by glensc** [comment]
Issue created:
- https://github.com/sarugaku/plette/issues/38

**Comment by matteius** [comment]
@glensc Its in the docs:  https://pipenv.pypa.io/en/latest/advanced/#specifying-basically-anything

Have you tried something like this and it doesn't work?

```
unittest2 = {version = ">=1.0,<3.0", markers="python_version < '2.7.9' or (python_version >= '3.0' and python_version < '3.4')"}
```

**Comment by glensc** [comment]
@matteius ok, thanks:
- https://github.com/Taxel/PlexTraktSync/commit/82e714bc2284dae6a0889f0fcff5ef199fe2e47e

@oz123: ps: edit [your post](https://github.com/pypa/pipenv/issues/5569#issuecomment-1383077919) and fix it with a permalink! instructions bottom of this post: https://github.com/pypa/pipenv/issues/5569#issuecomment-1383112872
