### ISSUE TITLE
I can't use pipenv after upgrading my Linux Mint to the latest version (Vera).

### ISSUE THREAD

**Issue by madyanes** [pypa/pipenv#5609]
```
$ pipenv 
Traceback (most recent call last):
  File "/home/madyan/.local/bin/pipenv", line 5, in <module>
    from pipenv import cli
ModuleNotFoundError: No module named 'pipenv'

```

I've tried to reinstall pipenv with pipx but it shows error:
```
$ pipx install --force pipenv
Installing to existing venv 'pipenv'
Fatal error from pip prevented installation. Full pip output in file:
    /home/madyan/.local/pipx/logs/cmd_2023-02-13_06.46.12_pip_errors.log

⚠️  Not removing existing venv /home/madyan/.local/pipx/venvs/pipenv because it was not created in this session
Error installing pipenv.

$ pipx list
venvs are in /home/madyan/.local/pipx/venvs
apps are exposed on your $PATH at /home/madyan/.local/bin
   package pipenv 2022.12.19, installed using Python 3.8.10
    - pipenv
    - pipenv-resolver
```

Tried using pip, but it doesn't seem to work:
```
$ pip install pipenv         
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pipenv in /usr/local/lib/python3.10/dist-packages (2023.2.4)
Requirement already satisfied: setuptools>=36.2.1 in /usr/lib/python3/dist-packages (from pipenv) (59.6.0)
Requirement already satisfied: virtualenv in /usr/local/lib/python3.10/dist-packages (from pipenv) (20.19.0)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /usr/local/lib/python3.10/dist-packages (from pipenv) (0.5.7)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from pipenv) (2020.6.20)
Requirement already satisfied: platformdirs<4,>=2.4 in /usr/local/lib/python3.10/dist-packages (from virtualenv->pipenv) (3.0.0)
Requirement already satisfied: distlib<1,>=0.3.6 in /usr/local/lib/python3.10/dist-packages (from virtualenv->pipenv) (0.3.6)
Requirement already satisfied: filelock<4,>=3.4.1 in /usr/lib/python3/dist-packages (from virtualenv->pipenv) (3.6.0)

$ pipenv
Traceback (most recent call last):
  File "/home/madyan/.local/bin/pipenv", line 5, in <module>
    from pipenv import cli
ModuleNotFoundError: No module named 'pipenv'
```

I need a help please. Thank you in advance.

**Comment by madyanes** [comment]
It's fixed.

I uninstalled the pipenv and the pipx using pip. And reinstall them. 

[Reference: uninstall pipx](https://github.com/pypa/pipx/issues/278#issuecomment-554679349)
