### ISSUE TITLE
pipenv is confused by virtual environment folders from different platforms

### ISSUE THREAD

**Issue by rwb27** [pypa/pipenv#5630]
### Issue description

My project folder contains virtual environment folders (`.venv` and `.venv_wsl`) for both Windows and Linux (mostly using Windows Subsystem Linux). I am managing these manually, and activating each before running `pipenv`. On Windows, `pipenv` crashes when looking for package metadata because the virtual environment that doesn't match my current platform is searched, rather than being ignored.

### Expected result

All virtual environments are ignored.

### Actual result

`pipenv` crashes with the following traceback:
```
Traceback (most recent call last):
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\Scripts\pipenv.exe\__main__.py", line 7, in <module>
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\cli\options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\cli\command.py", line 696, in sync
    categories=state.installstate.categories,
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\core.py", line 3202, in do_sync
    categories=categories,
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\core.py", line 1372, in do_init
    categories=categories,
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\core.py", line 869, in do_install_dependencies
    lockfile.get_requirements(dev=dev, only=dev_only, categories=[category])
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\requirementslib\models\lockfile.py", line 284, in get_requirements
    yield Requirement.from_pipfile(k, v)
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 2750, in from_pipfile
    r = FileRequirement.from_pipfile(name, pipfile)
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 1834, in from_pipfile
    arg_dict["parsed_line"] = Line(line, extras=extras)
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 171, in __init__    self.parse()
    self.parse_name()
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 1028, in parse_name
    name = self._parse_name_from_path()
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 991, in _parse_name_from_path
    metadata = get_metadata(self.path)
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\requirementslib\models\setup_info.py", line 740, in get_metadata
    dist = get_distinfo_dist(path, pkg_name=pkg_name)
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\requirementslib\models\setup_info.py", line 709, in get_distinfo_dist
    dist_dir = next(iter(find_distinfo(path, pkg_name=pkg_name)), None)
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\requirementslib\models\setup_info.py", line 702, in find_distinfo
    for dist_dir in dist_dirs:
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\requirementslib\models\setup_info.py", line 693, in <genexpr> 
    dist_dir
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\requirementslib\models\setup_info.py", line 665, in iter_metadata
    with contextlib.closing(ScandirCloser(p)) as path_iterator:
  File "c:\users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\lib\site-packages\pipenv\vendor\requirementslib\models\setup_info.py", line 625, in __init__  
    self.iterator = scandir(path)
OSError: [WinError 1920] The file cannot be accessed by the system: 'C:/local/repos/openflexure-microscope-server\\.venv_wsl\\lib64'
```

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

Create a WSL virtual environment in a particular project folder:
```
$ git clone https://gitlab.com/openflexure/openflexure-microscope-server.git
$ cd openflexure-microscope-server/
$ python -m venv .venv_wsl
$ source .venv_wsl/bin/activate
$ python -m pip install --upgrade pip pipenv wheel
$ pipenv sync
```
Create an equivalent Windows virtual environment:
```
> python -m venv .venv
> .venv/Scripts/activate
> python -m pip install --upgrade pip pipenv wheel
> pipenv sync
```

This should be sufficient to produce the crash that I see, I think. The `Pipfile` is in the repository I mention, though I don't think it is the problem.

### Cause and work-around

I believe the problem is in the way that `requirementslib` searches for package metadata: it excludes virtual environments, but only ones that look like virtual environments for the current system (Windows/others).  So, on Windows it still attempts to search the WSL virtual environment for packages, which is where it gets stuck. `requirementslib` is vendorised into `pipenv`, and so I fixed the problem by editing `pipenv\vendor\requirementslib\models\setup_info.py`, amending `_is_venv_dir(path)` to return `True` for **any** virtual environment, regardless of the current platform. The revised function is now:
```python
def _is_venv_dir(path):
    # type: (AnyStr) -> bool
    return (
        # The first two lines are appropriate for Windows
        os.path.isfile(os.path.join(path, "Scripts/python.exe")) 
        or os.path.isfile(os.path.join(path, "Scripts/activate"))
        # Other platforms should have these files in a virtual environment
        or os.path.isfile(os.path.join(path, "bin/python")) 
        or os.path.isfile(os.path.join(path, "bin/activate"))
    )
```
I don't know if it's more appropriate to raise/suggest this here or upstream, but I thought it was worth mentioning here as it's baked in to pipenv.

I have no idea if this changes behaviour that will have unintended consequences elsewhere - but what I can say is that it's fixed my problem for now.

-------------------------------------------------------------------------------
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2023.2.18'`

Pipenv location: `'c:\\users\\[my_username]\\.pyenv\\pyenv-win\\versions\\3.7.9\\lib\\site-packages\\pipenv'`

Python location: `'c:\\users\\[my_username]\\.pyenv\\pyenv-win\\versions\\3.7.9\\python.exe'`

OS Name: `'nt'`

User pip version: `'23.0.1'`

user Python installations found:

  - `3.11.0`: `C:\Python311\python.exe`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.9',
 'os_name': 'nt',
 'platform_machine': 'AMD64',
 'platform_python_implementation': 'CPython',
 'platform_release': '10',
 'platform_system': 'Windows',
 'platform_version': '10.0.19041',
 'python_full_version': '3.7.9',
 'python_version': '3.7',
 'sys_platform': 'win32'}
```

System environment variables:

  - `ALLUSERSPROFILE`
  - `APPDATA`
  - `BINDIR`
  - `CHOCOLATEYINSTALL`
  - `CHOCOLATEYLASTPATHUPDATE`
  - `CHROME_CRASHPAD_PIPE_NAME`
  - `CMDLINE`
  - `COMMANDS`
  - `COMMONPROGRAMFILES`
  - `COMMONPROGRAMFILES(X86)`
  - `COMMONPROGRAMW6432`
  - `COMPUTERNAME`
  - `COMSPEC`
  - `DRIVERDATA`
  - `EXTRAPATHS`
  - `FPS_BROWSER_APP_PROFILE_STRING`
  - `FPS_BROWSER_USER_PROFILE_STRING`
  - `HOMEDRIVE`
  - `HOMEPATH`
  - `HTTP_PROXY`
  - `LOCALAPPDATA`
  - `LOGONSERVER`
  - `NUMBER_OF_PROCESSORS`
  - `ONEDRIVE`
  - `ONEDRIVECOMMERCIAL`
  - `ONEDRIVECONSUMER`
  - `ORIGINAL_XDG_CURRENT_DESKTOP`
  - `OS`
  - `PATH`
  - `PATHEXT`
  - `PROCESSOR_ARCHITECTURE`
  - `PROCESSOR_IDENTIFIER`
  - `PROCESSOR_LEVEL`
  - `PROCESSOR_REVISION`
  - `PROGRAMDATA`
  - `PROGRAMFILES`
  - `PROGRAMFILES(X86)`
  - `PROGRAMW6432`
  - `PROMPT`
  - `PSMODULEPATH`
  - `PUBLIC`
  - `PYENV`
  - `PYENV_HOME`
  - `PYENV_ROOT`
  - `PYTHON_SHIMS`
  - `SESSIONNAME`
  - `SKIP`
  - `SYSTEMDRIVE`
  - `SYSTEMROOT`
  - `TEMP`
  - `TMP`
  - `USERDNSDOMAIN`
  - `USERDOMAIN`
  - `USERDOMAIN_ROAMINGPROFILE`
  - `USERNAME`
  - `USERPROFILE`
  - `WINDIR`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `LANG`
  - `COLORTERM`
  - `GIT_ASKPASS`
  - `VSCODE_GIT_ASKPASS_NODE`
  - `VSCODE_GIT_ASKPASS_EXTRA_ARGS`
  - `VSCODE_GIT_ASKPASS_MAIN`
  - `VSCODE_GIT_IPC_HANDLE`
  - `VSCODE_INJECTION`
  - `_PATH`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv?specific environment variables:

Debug?specific environment variables:

  - `PATH`: `C:\Users\[my_username]\.pyenv\pyenv-win\versions\3.7.9;C:\Users\[my_username]\.pyenv\pyenv-win\versions\3.7.9\Scripts;C:\Users\[my_username]\AppData\Roaming\Python\Python37\Scripts;C:\Users\[my_username]\.pyenv\pyenv-win\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Python311\Scripts\;C:\Python311\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\OpenSCAD\;C:\Program Files\Docker\Docker\resources\bin;C:\Users\[my_username]\AppData\Local\Microsoft\WindowsApps;C:\Users\[my_username]\AppData\Local\Programs\Microsoft VS Code\bin;`
  - `LANG`: `en_US.UTF-8`

---------------------------

Contents of `Pipfile` ('C:\\local\\repos\\openflexure-microscope-server\\Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://www.piwheels.org/simple"
verify_ssl = true
name = "piwheels"

[requires]
python_version = '3.7'

[packages]
openflexure-microscope-server = {editable = true, path = "."}

[dev-packages]
openflexure-microscope-server = {editable = true, path = ".", extras = ["dev"]}

```

Contents of `Pipfile.lock` ('C:\\local\\repos\\openflexure-microscope-server\\Pipfile.lock') not provided as it made the issue too long.

```
</details>

**Comment by matteius** [comment]
Thanks for your detailed analysis!  I will look into it soon more after we release the next version.  Feel free to open a requirementslib PR in the meantime to see if the test runner still passes and we can examine it further from there.

**Comment by matteius** [comment]
@rwb27 Been hard at work in this space, could you help me check:
1.) Still an issue with the upgrades to pythonfinder?  `pipenv==2023.5.19`
2.) Still an issue with the future upgrades to requirementslib?, this branch:  https://github.com/pypa/pipenv/pull/5679

**Comment by rwb27** [comment]
I'm delighted to say this issue doesn't reappear with `pipenv==2023.5.19`, however I'm afraid I now can't reproduce it with `pipenv==2023.2.18` either. 

The machine in question got rebuilt so I was following the recipe given in my original issue.  This has me wondering whether perhaps there is some interaction between `pyenv-win` and everything else that wasn't helping (I tried to reproduce it using a manually installed Python 3.7, rather than going via pyenv). I'll have another poke around when I can, but for now I can only apologies that I don't seem to be able to reproduce my own bug!
