### ISSUE TITLE
`pipenv install` errors out with `ModuleNotFoundError: No module named 'distutils.cmd'` even though it is present on the system

### ISSUE THREAD

**Issue by marekdedic** [pypa/pipenv#5674]
Hi,
while running `pipenv install`, I get a long list of errors, but I think the most important one is the following few lines:

```
[pipenv.exceptions.InstallError]: Traceback (most recent call last):
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/patched/pip/__pip-runner__.py", line 50, in <module>
[pipenv.exceptions.InstallError]:     runpy.run_module("pip", run_name="__main__", alter_sys=True)
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3.9/runpy.py", line 225, in run_module
[pipenv.exceptions.InstallError]:     return _run_module_code(code, init_globals, run_name, mod_spec)
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
[pipenv.exceptions.InstallError]:     _run_code(code, mod_globals, init_globals,
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
[pipenv.exceptions.InstallError]:     exec(code, run_globals)
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/patched/pip/__main__.py", line 35, in <module>
[pipenv.exceptions.InstallError]:     spec.loader.exec_module(pipenv)
[pipenv.exceptions.InstallError]:   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[pipenv.exceptions.InstallError]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/__init__.py", line 63, in <module>
[pipenv.exceptions.InstallError]:     from .cli import cli
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/cli/__init__.py", line 1, in <module>
[pipenv.exceptions.InstallError]:     from .command import cli  # noqa
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/cli/command.py", line 7, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.cli.options import (
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/cli/options.py", line 3, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.project import Project
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/project.py", line 19, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.environment import Environment
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/environment.py", line 17, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.patched.pip._internal.commands.install import InstallCommand
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/patched/pip/_internal/commands/__init__.py", line 9, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.patched.pip._internal.cli.base_command import Command
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/patched/pip/_internal/cli/base_command.py", line 15, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.patched.pip._internal.cli import cmdoptions
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/patched/pip/_internal/cli/cmdoptions.py", line 24, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.patched.pip._internal.cli.parser import ConfigOptionParser
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/patched/pip/_internal/cli/parser.py", line 12, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.patched.pip._internal.configuration import Configuration, ConfigurationError
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/patched/pip/_internal/configuration.py", line 26, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.patched.pip._internal.utils.logging import getLogger
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/patched/pip/_internal/utils/logging.py", line 29, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.patched.pip._internal.utils.misc import ensure_dir
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/patched/pip/_internal/utils/misc.py", line 42, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.patched.pip._internal.locations import get_major_minor_version
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/patched/pip/_internal/locations/__init__.py", line 67, in <module>
[pipenv.exceptions.InstallError]:     from . import _distutils
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/patched/pip/_internal/locations/_distutils.py", line 20, in <module>
[pipenv.exceptions.InstallError]:     from distutils.cmd import Command as DistutilsCommand
[pipenv.exceptions.InstallError]: ModuleNotFoundError: No module named 'distutils.cmd'
```

I have searched for the common causes of this and I can say the following:
- I have `python3-distutils` and `python3-apt` installed, I also tried reinstalling them
- I can import the `distutils` module from my system python:
  ```
  ❯ python3
  Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
  Type "help", "copyright", "credits" or "license" for more information.
  >>> from distutils.cmd import Command
  >>>
  ```
- I can also import the `distutils` module from `pipenv shell`:
  ```
  ❯ python
  Python 3.9.13 (main, Jun  8 2022, 09:45:57)
  [GCC 11.3.0] on linux
  Type "help", "copyright", "credits" or "license" for more information.
  >>> from distutils.cmd import Command
  >>>
  ```

So.. What gives? The module is obviously there, but somehow pipenv cannot find it

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting.

If you're on Linux, run the following:

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.12.19'`

Pipenv location: `'/usr/lib/python3/dist-packages/pipenv'`

Python location: `'/usr/bin/python3'`

OS Name: `'posix'`

User pip version: `'22.3.1'`

user Python installations found:

  - `3.11.2`: `/usr/bin/python3`
  - `3.11.2`: `/bin/python3`
  - `3.9.13`: `/usr/bin/python3.9`
  - `3.9.13`: `/bin/python3.9`
  - `3.8.5`: `/opt/miniconda3/bin/python3`
  - `3.8.5`: `/opt/miniconda3/bin/python3.8`
  - `3.8.5`: `/opt/miniconda3/bin/python`
  - `2.7.18`: `/usr/bin/python2`
  - `2.7.18`: `/usr/bin/python2.7`
  - `2.7.18`: `/bin/python2`
  - `2.7.18`: `/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.11.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '6.1.0-7-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT_DYNAMIC Debian 6.1.20-2 (2023-04-08)',
 'python_full_version': '3.11.2',
 'python_version': '3.11',
 'sys_platform': 'linux'}
```

System environment variables:

  - `ALACRITTY_LOG`
  - `ALACRITTY_SOCKET`
  - `ALACRITTY_WINDOW_ID`
  - `ANDROID_HOME`
  - `COLORTERM`
  - `CONDA_DEFAULT_ENV`
  - `CONDA_EXE`
  - `CONDA_PREFIX`
  - `CONDA_PROMPT_MODIFIER`
  - `CONDA_PYTHON_EXE`
  - `CONDA_SHLVL`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `DESKTOP_SESSION`
  - `DISPLAY`
  - `EDITOR`
  - `GDMSESSION`
  - `GDM_LANG`
  - `GIO_LAUNCHED_DESKTOP_FILE`
  - `GIO_LAUNCHED_DESKTOP_FILE_PID`
  - `GJS_DEBUG_OUTPUT`
  - `GJS_DEBUG_TOPICS`
  - `GNOME_DESKTOP_SESSION_ID`
  - `GNOME_SETUP_DISPLAY`
  - `GTK_MODULES`
  - `HOME`
  - `INVOCATION_ID`
  - `JOURNAL_STREAM`
  - `JULIA_NUM_THREADS`
  - `LANG`
  - `LANGUAGE`
  - `LC_MEASUREMENT`
  - `LC_MONETARY`
  - `LC_NUMERIC`
  - `LC_PAPER`
  - `LC_TIME`
  - `LESS`
  - `LOGNAME`
  - `LSCOLORS`
  - `LS_COLORS`
  - `MANAGERPID`
  - `MOZ_ENABLE_WAYLAND`
  - `OLDPWD`
  - `P9K_TTY`
  - `PAGER`
  - `PATH`
  - `POWERLINE_COMMAND`
  - `PWD`
  - `QTWEBENGINE_DICTIONARIES_PATH`
  - `QT_ACCESSIBILITY`
  - `QT_IM_MODULE`
  - `SESSION_MANAGER`
  - `SHELL`
  - `SHLVL`
  - `SKIM_CTRL_T_COMMAND`
  - `SKIM_DEFAULT_COMMAND`
  - `SSH_AGENT_LAUNCHER`
  - `SSH_AUTH_SOCK`
  - `SYSTEMD_EXEC_PID`
  - `TERM`
  - `TERM_PROGRAM`
  - `TERM_PROGRAM_VERSION`
  - `TMUX`
  - `TMUX_PANE`
  - `TMUX_PLUGIN_MANAGER_PATH`
  - `USER`
  - `USERNAME`
  - `VISUAL`
  - `WAYLAND_DISPLAY`
  - `WINDOWID`
  - `XAUTHORITY`
  - `XDG_CURRENT_DESKTOP`
  - `XDG_MENU_PREFIX`
  - `XDG_RUNTIME_DIR`
  - `XDG_SESSION_CLASS`
  - `XDG_SESSION_DESKTOP`
  - `XDG_SESSION_TYPE`
  - `XMODIFIERS`
  - `ZSH`
  - `_`
  - `_CE_CONDA`
  - `_CE_M`
  - `_P9K_SSH_TTY`
  - `_P9K_TTY`
  - `is_vim`
  - `P9K_SSH`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/user/.local/bin:/opt/miniconda3/bin:/opt/miniconda3/condabin:/home/user/.local/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `SHELL`: `/bin/zsh`
  - `EDITOR`: `nvim`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/user/project`

---------------------------

Contents of `Pipfile` ('/home/user/project/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[[source]]
name = "redacted"
url = "redacted"
verify_ssl = true

[dev-packages]
notebook = "== 6.4.12"
jupyterhub = "== 1.5.0"
jupyterlab = "== 3.3.2"
dask-labextension = "== 5.2.0"
bokeh = "== 2.4.3"
ipywidgets = "== 7.7.0"
# Research
matplotlib = "*"
scikit-learn = "*"
scipy = "*"
cryptography = ">=38.0.3"

[packages]
## DASK
kubernetes = "== 17.17.0"
dask = { extras = ["complete", "dataframe"], version = "== 2022.09.2" }
dask-kubernetes = "== 2022.9.0"
distributed = "== 2022.09.2"
click = "== 8.0.2"
# Research
aiohttp = ">=3.7.4"
fastparquet = "*"
python-snappy = "*"
pandas = "1.5.0"
pyarrow = "*"
pyathena = "*"
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
s3fs = "*"
smart_open = "*"
numpy = "*"
hypothesis = "*"
threatqsdk = { version = "*", index = "cognitive-intelligence" }
vt-py = "==0.17.3"
tldextract = "*"
aiofiles = "*"
pytest-asyncio = "*"

[requires]
python_version = "3.9"
#TODO: doens't work with jupyterhub

[pipenv]
allow_prereleases = false

```

Contents of `Pipfile.lock` ('/home/user/project/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "d743e6571b658ebc0baf48d5cc01fe2170bd3f490330ab917bec86b7c763e859"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.9"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            },
            {
                "name": "redacted",
                "url": "redacted",
                "verify_ssl": true
            }
        ]
    },
    "default": {
	}
}

```
</details>

**Comment by matteius** [comment]
@marekdedic I am not sure as I have not seen this issue before, but noting you are on `2022.12.19` -- could you try upgrading to `2023.4.29` and see if the issue persists?

**Comment by marekdedic** [comment]
Nope, the issue is still the same even with that version of pipenv. In the meantime, I somehow got it to work once (had to install `libsnappy-dev` along the way), but I cannot recreate it again :(

**Comment by matteius** [comment]
Is it possible you have an old version of pipenv somewhere on the path and its getting confused when running the subprocesses?

**Comment by matteius** [comment]
Also would be worth having you try the new release of pipenv that was just cut, but make sure you `pip uninstall pipenv --yes` multiple times until it is clearly not on the path anymore, just in case.

**Comment by bdwilson** [comment]
same issue here:

# pipenv --support
<details><summary>$ pipenv --support</summary>

Pipenv version: `'2023.5.19'`

Pipenv location: `'/usr/local/lib/python3.10/dist-packages/pipenv'`

Python location: `'/usr/bin/python3'`

OS Name: `'posix'`

User pip version: `'23.1.2'`

user Python installations found:


PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.6',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.15.0-71-generic',
 'platform_system': 'Linux',
 'platform_version': '#78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023',
 'python_full_version': '3.10.6',
 'python_version': '3.10',
 'sys_platform': 'linux'}
```

System environment variables:

  - `SHELL`
  - `SUDO_GID`
  - `PIPENV_ACTIVE`
  - `SUDO_COMMAND`
  - `SUDO_USER`
  - `PWD`
  - `LOGNAME`
  - `PIP_PYTHON_PATH`
  - `HOME`
  - `LANG`
  - `LS_COLORS`
  - `VIRTUAL_ENV`
  - `LC_TERMINAL`
  - `LESSCLOSE`
  - `TERM`
  - `LESSOPEN`
  - `USER`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `LC_TERMINAL_VERSION`
  - `SHLVL`
  - `PYTHONDONTWRITEBYTECODE`
  - `PS1`
  - `PATH`
  - `SUDO_UID`
  - `MAIL`
  - `_`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

 - `PIPENV_ACTIVE`: `1`

Debug–specific environment variables:

  - `PATH`: `/root/.local/share/virtualenvs/bulk-tasmota-configuration-m6np3S30/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/wilson/code/bulk-tasmota-configuration`
  - `VIRTUAL_ENV`: `/root/.local/share/virtualenvs/bulk-tasmota-configuration-m6np3S30`


---------------------------

Contents of `Pipfile` ('/home/wilson/code/bulk-tasmota-configuration/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
click = "*"
requests = "*"
json5 = "*"

[requires]
python_version = "3.8"

```


Contents of `Pipfile.lock` ('/home/wilson/code/bulk-tasmota-configuration/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "c61669a9ce743977a1086ea43786f01c4a80be0479cec3697de13cbf8c492d50"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.8"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "certifi": {
            "hashes": [
                "sha256:84c85a9078b11105f04f3036a9482ae10e4621616db313fe045dd24743a0820d",
                "sha256:fe86415d55e84719d75f8b69414f6438ac3547d2078ab91b67e779ef69378412"
            ],
            "markers": "python_version >= '3.6'",
            "version": "==2022.6.15"
        },
        "charset-normalizer": {
            "hashes": [
                "sha256:5189b6f22b01957427f35b6a08d9a0bc45b46d3788ef5a92e978433c7a35f8a5",
                "sha256:575e708016ff3a5e3681541cb9d79312c416835686d054a23accb873b254f413"
            ],
            "markers": "python_version >= '3.6'",
            "version": "==2.1.0"
        },
        "click": {
            "hashes": [
                "sha256:7682dc8afb30297001674575ea00d1814d808d6a36af415a82bd481d37ba7b8e",
                "sha256:bb4d8133cb15a609f44e8213d9b391b0809795062913b383c62be0ee95b1db48"
            ],
            "index": "pypi",
            "version": "==8.1.3"
        },
        "idna": {
            "hashes": [
                "sha256:84d9dd047ffa80596e0f246e2eab0b391788b0503584e8945f2368256d2735ff",
                "sha256:9d643ff0a55b762d5cdb124b8eaa99c66322e2157b69160bc32796e824360e6d"
            ],
            "markers": "python_version >= '3.5'",
            "version": "==3.3"
        },
        "json5": {
            "hashes": [
                "sha256:1ff8351ee2ae80fd89d64210d9522db7e157516a7b12c72089ded6964527283f",
                "sha256:2ace77117c068c5f1f23f97e530a0d49bc09a46039521b6daa74aa39524e02a2"
            ],
            "index": "pypi",
            "version": "==0.9.9"
        },
        "requests": {
            "hashes": [
                "sha256:7c5599b102feddaa661c826c56ab4fee28bfd17f5abca1ebbe3e7f19d7c97983",
                "sha256:8fefa2a1a1365bf5520aac41836fbee479da67864514bdb821f31ce07ce65349"
            ],
            "index": "pypi",
            "version": "==2.28.1"
        },
        "urllib3": {
            "hashes": [
                "sha256:c33ccba33c819596124764c23a97d25f32b28433ba0dedeb77d873a38722c9bc",
                "sha256:ea6e8fb210b19d950fab93b60c9009226c63a28808bc8386e05301e25883ac0a"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4, 3.5' and python_version < '4'",
            "version": "==1.26.11"
        }
    },
    "develop": {}
}

```
</details>

Pipfile:
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
click = "*"
requests = "*"
json5 = "*"

[requires]
python_version = "3.8"

**Comment by matteius** [comment]
What version of setuptools do you have installed?

**Comment by marekdedic** [comment]
System python:
```py
>>> setuptools.__version__
'67.7.2'
```

pipenv shell:
```py
>>> setuptools.__version__
'66.1.1'
```

**Comment by matteius** [comment]
Could this be rechecked with `2023.6.12` -- I have a hunch that the sys.path hacks I removed could have been causing this as well.

**Comment by marekdedic** [comment]
Still the same with `2023.6.18` :(

**Comment by CNDW** [comment]
I had a similar issue with `v2023.6.18` and `v2023.6.12` both failing while `v2023.6.11` worked. It may be unrelated to your issue but I eventually tracked it down to another pipenv install in my environment. The removal of the `sys.path` manipulation in 1cc03eaa3b13114fca0d84fcad25148f71f413ff exposes pipenv to issues with module resolution confusion. 

I'm suspecting that `pipenv` is importing a module from a different install which is resulting in the downstream errors - this snippet in particular

```
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
[pipenv.exceptions.InstallError]:     exec(code, run_globals)
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3/dist-packages/pipenv/patched/pip/__main__.py", line 35, in <module>
[pipenv.exceptions.InstallError]:     spec.loader.exec_module(pipenv)
```
there looks like there could be 2 different venvs involved

```
/usr/lib/python3.9
```
and
```
/usr/lib/python3
```

In my case, I had a global `pipenv` install in my `python 3.11` and another install in `python 3.7` - running `pipenv` from a `python 3.7` venv was using the install from the `python 3.11` but resolving internal pipenv modules from the `python 3.7` install

**Comment by marekdedic** [comment]
Umm, @matteius why was this closed without any comment or resolution?

**Comment by matteius** [comment]
@marekdedic Are you claiming this is still an issue for you on `2023.9.1`?

**Comment by marekdedic** [comment]
@matteius Yes, I do:

```shell
$ pipenv install
Installing dependencies from Pipfile.lock (2f3ef0)...
[pipenv.exceptions.InstallError]: Traceback (most recent call last):
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/patched/pip/__pip-runner__.py", line 50, in <module>
[pipenv.exceptions.InstallError]:     runpy.run_module("pip", run_name="__main__", alter_sys=True)
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3.9/runpy.py", line 225, in run_module
[pipenv.exceptions.InstallError]:     return _run_module_code(code, init_globals, run_name, mod_spec)
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
[pipenv.exceptions.InstallError]:     _run_code(code, mod_globals, init_globals,
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
[pipenv.exceptions.InstallError]:     exec(code, run_globals)
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/patched/pip/__main__.py", line 28, in <module>
[pipenv.exceptions.InstallError]:     spec.loader.exec_module(pipenv)
[pipenv.exceptions.InstallError]:   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[pipenv.exceptions.InstallError]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/__init__.py", line 40, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.cli import cli  # noqa
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/cli/__init__.py", line 1, in <module>
[pipenv.exceptions.InstallError]:     from .command import cli  # noqa
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/cli/command.py", line 4, in <module>
[pipenv.exceptions.InstallError]:     from pipenv import environments
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/environments.py", line 8, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.utils.fileutils import normalize_drive
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/utils/fileutils.py", line 15, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.patched.pip._internal.locations import USER_CACHE_DIR
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/patched/pip/_internal/locations/__init__.py", line 66, in <module>
[pipenv.exceptions.InstallError]:     from . import _distutils
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/patched/pip/_internal/locations/_distutils.py", line 20, in <module>
[pipenv.exceptions.InstallError]:     from distutils.cmd import Command as DistutilsCommand
[pipenv.exceptions.InstallError]: ModuleNotFoundError: No module named 'distutils.cmd'
ERROR: Couldn't install package: {}
 Package installation failed...
/usr/lib/python3.11/subprocess.py:1127: ResourceWarning: subprocess 153315 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=4 encoding='utf-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=7 encoding='utf-8'>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

```shell
$ pipenv --version
pipenv, version 2023.9.8
```

**Comment by matteius** [comment]
@marekdedic Can you try setting env var `_PIP_USE_SYSCONFIG = false` -- I am not sure why this is happening for you, I haven't see this issue and had assumed what Travis was saying about a prior patch that we added back to ensure latest installed pipenv is in the sys path.

**Comment by marekdedic** [comment]
Doesn't help :(

```shell
$ export _PIP_USE_SYSCONFIG=false
$ pipenv install
Installing dependencies from Pipfile.lock (2f3ef0)...
[pipenv.exceptions.InstallError]: Traceback (most recent call last):
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/patched/pip/__pip-runner__.py", line 50, in <module>
[pipenv.exceptions.InstallError]:     runpy.run_module("pip", run_name="__main__", alter_sys=True)
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3.9/runpy.py", line 225, in run_module
[pipenv.exceptions.InstallError]:     return _run_module_code(code, init_globals, run_name, mod_spec)
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
[pipenv.exceptions.InstallError]:     _run_code(code, mod_globals, init_globals,
[pipenv.exceptions.InstallError]:   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
[pipenv.exceptions.InstallError]:     exec(code, run_globals)
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/patched/pip/__main__.py", line 28, in <module>
[pipenv.exceptions.InstallError]:     spec.loader.exec_module(pipenv)
[pipenv.exceptions.InstallError]:   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[pipenv.exceptions.InstallError]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/__init__.py", line 40, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.cli import cli  # noqa
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/cli/__init__.py", line 1, in <module>
[pipenv.exceptions.InstallError]:     from .command import cli  # noqa
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/cli/command.py", line 4, in <module>
[pipenv.exceptions.InstallError]:     from pipenv import environments
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/environments.py", line 8, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.utils.fileutils import normalize_drive
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/utils/fileutils.py", line 15, in <module>
[pipenv.exceptions.InstallError]:     from pipenv.patched.pip._internal.locations import USER_CACHE_DIR
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/patched/pip/_internal/locations/__init__.py", line 66, in <module>
[pipenv.exceptions.InstallError]:     from . import _distutils
[pipenv.exceptions.InstallError]:   File "/home/user/.local/lib/python3.11/site-packages/pipenv/patched/pip/_internal/locations/_distutils.py", line 20, in <module>
[pipenv.exceptions.InstallError]:     from distutils.cmd import Command as DistutilsCommand
[pipenv.exceptions.InstallError]: ModuleNotFoundError: No module named 'distutils.cmd'
ERROR: Couldn't install package: {}
 Package installation failed...
/usr/lib/python3.11/subprocess.py:1127: ResourceWarning: subprocess 311396 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=4 encoding='utf-8'>
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=7 encoding='utf-8'>
```

**Comment by bsridatta** [comment]
Having exactly the same issue, can anyone look into this?

**Comment by jjstrydom** [comment]
I had 3.11 as my version where pipenv was installed, and 3.12 for my virtual environment for the project
I could fix it with:
`pip install setuptools` executed within the 3.12 shell

**Comment by matteius** [comment]
I would appreciate any help checking if `2024.3.0` resolved this issue.

**Comment by MPatersonSoftware** [comment]
I'm getting this issue in `2024.4.1`

```
$ pipenv install
Installing dependencies from Pipfile.lock (caf478)...
Traceback (most recent call last):
  File "/home/markp/.local/lib/python3.12/site-packages/pipenv/patched/pip/__pip-runner__.py", line 50, in 
<module>
    runpy.run_module("pip", run_name="__main__", alter_sys=True)
  File "/usr/lib/python3.9/runpy.py", line 225, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/markp/.local/lib/python3.12/site-packages/pipenv/patched/pip/__main__.py", line 29, in <module>
    spec.loader.exec_module(pipenv)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/markp/.local/lib/python3.12/site-packages/pipenv/__init__.py", line 30, in <module>
    from pipenv.cli import cli  # noqa
  File "/home/markp/.local/lib/python3.12/site-packages/pipenv/cli/__init__.py", line 1, in <module>
    from .command import cli  # noqa
  File "/home/markp/.local/lib/python3.12/site-packages/pipenv/cli/command.py", line 4, in <module>
    from pipenv import environments
  File "/home/markp/.local/lib/python3.12/site-packages/pipenv/environments.py", line 8, in <module>
    from pipenv.utils.fileutils import normalize_drive
  File "/home/markp/.local/lib/python3.12/site-packages/pipenv/utils/fileutils.py", line 16, in <module>
    from pipenv.patched.pip._internal.locations import USER_CACHE_DIR
  File "/home/markp/.local/lib/python3.12/site-packages/pipenv/patched/pip/_internal/locations/__init__.py", 
line 66, in <module>
    from . import _distutils
  File "/home/markp/.local/lib/python3.12/site-packages/pipenv/patched/pip/_internal/locations/_distutils.py",
line 20, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'
ERROR: Couldn't install package: {}
 Package installation failed...
```

This is run from within a 3.9 shell tb seems to be refering to my system python3.12 version. Much like [CNDW's.](https://github.com/pypa/pipenv/issues/5674#issuecomment-1607883823) 

I did run `pip3 install --break-system-packages setuptools` for my system version hoping this would resolve the issue but it doesn't seem to help.
