### ISSUE TITLE
Trying to install project on M2 Mac fails with `Pep 517 Error`

### ISSUE THREAD

**Issue by FabianClemenz** [pypa/pipenv#5796]
### Issue description

We have a Project which is been developed on Ubuntu and MacOS Systems (Ventura 13.4.1 - Intel Mac). It is also deployed on an Ubuntu server via Docker. I recently switched to a new M2 Mac and tried to install the env as always (`pipenv sync --dev`) but it fails with following Error.

I installed `pyenv` through homebrew and installed pipenv for the specified python version (`3.10.12`) in the project.
pipenv version `2023.7.11`

### Expected result

I can run `pipenv sync --dev` and use my environment

### Actual result

```
ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of setuptools.build_meta in pyproject.toml
Traceback (most recent call last):
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/cli/command.py", line 671, in sync
    retcode = do_sync(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/routines/install.py", line 353, in do_sync
    do_init(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/routines/install.py", line 777, in do_init
    do_install_dependencies(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/routines/install.py", line 455, in do_install_dependencies
    batch_install(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/routines/install.py", line 596, in batch_install
    batch_install_iteration(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/routines/install.py", line 538, in batch_install_iteration
    _cleanup_procs(project, procs, failed_deps_queue, retry=retry)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/routines/install.py", line 651, in _cleanup_procs
    dep.use_pep517 = True
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/requirementslib/models/common.py", line 18, in __setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
ValueError: "Requirement" object has no field "use_pep517"
```

### Steps to replicate

1. Switching to the directory 
2. running `pipenv sync --dev`

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2023.7.11'`

Pipenv location: `'/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv'`

Python location: `'/Users/fabianclemenz/.pyenv/versions/3.10.12/bin/python3.10'`

OS Name: `'posix'`

User pip version: `'23.2'`

user Python installations found:

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.12',
 'os_name': 'posix',
 'platform_machine': 'arm64',
 'platform_python_implementation': 'CPython',
 'platform_release': '22.5.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT '
                     '2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020',
 'python_full_version': '3.10.12',
 'python_version': '3.10',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `NVM_INC`
  - `ZNT_CONFIG_DIR`
  - `LDFLAGS`
  - `MANPATH`
  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `NVM_CD_FLAGS`
  - `_P9K_TTY`
  - `PIPENV_VERBOSITY`
  - `TERM`
  - `SHELL`
  - `CPPFLAGS`
  - `PIPENV_VENV_IN_PROJECT`
  - `HOMEBREW_REPOSITORY`
  - `TMPDIR`
  - `TERM_PROGRAM_VERSION`
  - `ZNT_REPO_DIR`
  - `TERM_SESSION_ID`
  - `PYENV_VERSION`
  - `LC_ALL`
  - `ZSH`
  - `NVM_DIR`
  - `USER`
  - `LS_COLORS`
  - `COMMAND_MODE`
  - `PYCURL_SSL_LIBRARY`
  - `pipfile_dir`
  - `CPATH`
  - `SSH_AUTH_SOCK`
  - `PYENV_DIR`
  - `__CF_USER_TEXT_ENCODING`
  - `PYENV_VIRTUALENV_INIT`
  - `PAGER`
  - `LSCOLORS`
  - `PATH`
  - `__CFBundleIdentifier`
  - `PWD`
  - `EDITOR`
  - `P9K_SSH`
  - `LANG`
  - `P9K_TTY`
  - `ITERM_PROFILE`
  - `PYENV_HOOK_PATH`
  - `XPC_FLAGS`
  - `XPC_SERVICE_NAME`
  - `PYENV_SHELL`
  - `SHLVL`
  - `HOME`
  - `COLORFGBG`
  - `LC_TERMINAL_VERSION`
  - `HOMEBREW_PREFIX`
  - `ITERM_SESSION_ID`
  - `LESS`
  - `LOGNAME`
  - `LC_CTYPE`
  - `PKG_CONFIG_PATH`
  - `NVM_BIN`
  - `INFOPATH`
  - `HOMEBREW_CELLAR`
  - `_P9K_SSH_TTY`
  - `LC_TERMINAL`
  - `COLORTERM`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_DISABLE_PIP_VERSION_CHECK`

Pipenv–specific environment variables:

 - `PIPENV_VERBOSITY`: `-1`
 - `PIPENV_VENV_IN_PROJECT`: `enabled`

---------------------------

Contents of `Pipfile` ('/Users/fabianclemenz/dev/work/bastuck/backend/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "*"
django-environ = "*"
celery = "*"
django-celery-beat = "*"
django-redis = "*"
google-cloud-vision = "*"
psycopg2-binary = "*"
django-constance = {extras = ["database"], version = "*"}
django-ninja = "*"
pandas = "*"
django-extensions = "*"
gunicorn = "*"
psycopg2 = "*"
fabric = "*"
django-ninja-jwt = {extras = ["crypto"], version = "*"}
termcolor = "*"
django-jazzmin = "*"
filetype = "*"
django-ninja-extra = "*"
pillow = "*"
django-storages = "*"
boto3 = "*"
sentry-sdk = "*"
json-log-formatter = "*"
django-import-export = "*"
django-cleanup = "*"
pydantic = {extras = ["email"], version = "*"}
numpy = "*"
django-ninja-passwordreset = "*"
django-cors-headers = "*"
pytest-xdist = "*"

[dev-packages]
pipenv = "*"
pytest-django = "*"
pytest-cov = "*"
pre-commit = "*"
flake8 = "*"
autopep8 = "*"
black = "*"
isort = "*"
invoke = "*"
pygraphviz = "*"
ipython = "*"
factory-boy = "*"
pytest-env = "*"
pytest = "*"
pytest-mock = "*"
django-webtest = "*"
mock = "*"
awscli-local = "*"
awscli = "*"

[requires]
python_version = "3.10"

```
</details>

**Comment by FabianClemenz** [comment]
When I try to do lock again I get this output:

```Traceback (most recent call last):
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 709, in resolve
    results = resolver.resolve(self.constraints, check_supported_wheels=False)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/candidates.py", line 157, in __init__
    self.dist = self._prepare()
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/operations/prepare.py", line 631, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/distributions/sdist.py", line 48, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/distributions/sdist.py", line 118, in _install_build_reqs
    build_reqs = self._get_build_requires_wheel()
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/distributions/sdist.py", line 95, in _get_build_requires_wheel
    return backend.get_requires_for_build_wheel()
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/utils/misc.py", line 692, in get_requires_for_build_wheel
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_impl.py", line 166, in get_requires_for_build_wheel
    return self._call_hook('get_requires_for_build_wheel', {
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/utils/subprocess.py", line 252, in runner
    call_subprocess(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/patched/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pipenv.patched.pip._internal.exceptions.InstallationSubprocessError: Getting requirements to build wheel exited with 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 1082, in venv_resolve_deps
    results = resolve_packages(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/resolver.py", line 654, in resolve_packages
    results, resolver = resolve(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/resolver.py", line 634, in resolve
    return resolve_deps(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 1134, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 969, in actually_resolve_deps
    resolver.resolve()
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 711, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: Getting requirements to build wheel exited with 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/cli/command.py", line 364, in lock
    do_lock(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/routines/lock.py", line 65, in do_lock
    venv_resolve_deps(
  File "/Users/fabianclemenz/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 1100, in venv_resolve_deps
    raise RuntimeError("There was a problem with locking.")
RuntimeError: There was a problem with locking.
```

**Comment by FabianClemenz** [comment]
Resolved it - the first error was within `psycopg2` package - which needed underlying `postgresql` installation, the second one was with `pygraphviz` which I am currently resolving
