### ISSUE TITLE
pipenv install cannot use --categories option along with --editable

### ISSUE THREAD

**Issue by expfun** [pypa/pipenv#5800]
pipenv install cannot use --categories option along with --editable

### Expected result

Describe what you expected.

### Actual result
```shell
pipenv install -e --categories detection ./akina/detection/livoxdetection/
```
Following error occurred:

Installing initially failed dependencies...
Traceback (most recent call last):
  File "/home/js/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/cli/command.py", line 233, in install
    do_install(
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/routines/install.py", line 170, in do_install
    do_init(
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/routines/install.py", line 777, in do_init
    do_install_dependencies(
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/routines/install.py", line 455, in do_install_dependencies
    batch_install(
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/routines/install.py", line 596, in batch_install
    batch_install_iteration(
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/routines/install.py", line 538, in batch_install_iteration
    _cleanup_procs(project, procs, failed_deps_queue, retry=retry)
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/routines/install.py", line 651, in _cleanup_procs
    dep.use_pep517 = True
  File "/home/js/.local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/common.py", line 18, in __setattr__
    raise ValueError(f'"{self.__class__.__name__}" object has no field "{name}"')
ValueError: "Requirement" object has no field "use_pep517"

**Comment by expfun** [comment]
pipenv install -e ./akina/detection/livoxdetection/ --categories detection ./akina/detection/livoxdetection/ works
