### ISSUE TITLE
Some dependencies using the sys_platform marker can not be resolved since version "2023.8.19"

### ISSUE THREAD

**Issue by LiveNL** [pypa/pipenv#5938]
### Issue description
(Some) dependencies that use the `sys_platform` marker, could not be resolved during an install. 
This issue exists in all versions after version "2023.7.23" and appears on systems other than the system that is mentioned in the marker (note, the output is from 2023.9.8, but as said, the issue exists since `[v2023.8.19](https://github.com/pypa/pipenv/releases/tag/v2023.8.19)` onwards)

### Expected result
Expected would be that the install would resolve itself, without issues. That is, to not stop/fail on dependencies with a system marker other than the current system.

### Actual result
`pipenv install` now results in: 
```
ERROR: No matching distribution found for python-magic-bin==0.4.14
```

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

**1) Minimal Pipfile to reproduce:**
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
python-magic-bin    = {version = "==0.4.14", sys_platform = "== 'win32'"}

[requires]
python_version = "3.11.0"
```

**2) run pipenv install**
```
pipenv install  --verbose
```

<details>
    <summary><b> 3) output of pipenv install  --verbose</b></summary>

### Output:
```shell
Pipfile.lock (8da0f5) out of date, updating to (499099)...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting()
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('python-magic-bin==0.4.14'),
None)
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement
python-magic-bin==0.4.14 (from versions: none)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 397,
in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 174,
in _add_to_criteria
    raise RequirementsConflicted(criterion)
pipenv.patched.pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('python-magic-bin==0.4.14')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/resolver.py",
line 92, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 546,
in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 399,
in resolve
    raise ResolutionImpossible(e.criterion.information)
pipenv.patched.pip._vendor.resolvelib.resolvers.ResolutionImpossible:
[RequirementInformation(requirement=SpecifierRequirement('python-magic-bin==0.4.14'), parent=None)]
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 445, in resolve
    results = resolver.resolve(constraints, check_supported_wheels=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/resolver.py",
line 101, in resolve
    raise error from e
pipenv.patched.pip._internal.exceptions.DistributionNotFound: No matching distribution found for python-magic-bin==0.4.14
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/resolver.py", line 675, in <module>
    main()
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/resolver.py", line 661, in main
    _main(
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/resolver.py", line 645, in _main
    resolve_packages(
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/resolver.py", line 612, in resolve_packages
    results, resolver = resolve(
                        ^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/resolver.py", line 592, in resolve
    return resolve_deps(
           ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 897, in resolve_deps
    results, hashes, internal_resolver = actually_resolve_deps(
                                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 670, in actually_resolve_deps
    resolver.resolve()
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 447, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: [31m[1mERROR[0m: [33mNo matching distribution found for python-magic-bin==0.4.14[0m
✘ Locking Failed!
⠧ Locking...
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/bin/pipenv", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/cli/command.py", line 209, in install
    do_install(
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/routines/install.py", line 164, in do_install
    do_init(
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/routines/install.py", line 648, in do_init
    do_lock(
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/routines/lock.py", line 65, in do_lock
    venv_resolve_deps(
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 838, in venv_resolve_deps
    c = resolve(cmd, st, project=project)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pipenv/2023.9.8/libexec/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 707, in resolve
    raise RuntimeError("Failed to lock Pipfile.lock!")
RuntimeError: Failed to lock Pipfile.lock!
```
</details> 

**Note**: looking at the other issues, I found some overlap in this issue: https://github.com/pypa/pipenv/issues/5884 . I also (successfully) tried the 'strange' solution that was given there. That is: specifying the marker, as actual marker instead of as `sys_platform` attribute. This however probably isn't the desired solution, so I'm happy to hear any other options!

**Comment by matteius** [comment]
Well its a bit of a pickle, the short of it is:  dropping requirementslib had some side effects and broke how sys_platform was working; I then made a different patch of it which is truly a behavior change to fold those sys_platform and os_name markers. 
 
The way its working in the latest versions is if you want to skip resolving that dependency on a specific platform, it would need to be added as markers as the sys_platform will try to resolve it and sub dependencies, but will then fold those sys_platform and os_name specs into the sub-dependencies.   This works well for published wheels and things that don't need to build and sdist, but it is problematic for things that do need to build an sdist but cannot on a deferent system where they were simply skipped entirely before.

**Comment by LiveNL** [comment]
Thanks for the clarification. We'll move `sys_platform` to markers then, as also shown in the example [Pipfile](https://github.com/pypa/pipenv/blob/cdf41def30b4300357d1e927c31a21371bc50779/docs/pipfile.md?plain=1#L24)
