### ISSUE TITLE
Possible regression when installing dependencies from a secondary source private registry

### ISSUE THREAD

**Issue by gbottari** [pypa/pipenv#5945]
### Issue description

The latest version of Pipenv (v2023.9.8) fails to resolve dependencies from a private registry. However, a previous version (v2023.7.9) works fine.

### Expected result

A happy `✔ Success!` message.

### Actual result

<details>
<summary>Error Output</summary>
<pre>
Building requirements...
Resolving dependencies...
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting()
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('private_package==0.47.2'), None)
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement private_package==0.47.2 (from 
versions: none)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 174, in _add_to_criteria
    raise RequirementsConflicted(criterion)
pipenv.patched.pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('private_package==0.47.2')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/usr/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 399, in resolve
    raise ResolutionImpossible(e.criterion.information)
pipenv.patched.pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('private_package==0.47.2'), 
parent=None)]
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 445, in resolve
    results = resolver.resolve(constraints, check_supported_wheels=False)
  File "/usr/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/resolver.py", line 101, in resolve
    raise error from e
pipenv.patched.pip._internal.exceptions.DistributionNotFound: No matching distribution found for private_package==0.47.2
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pipenv/resolver.py", line 675, in <module>
    main()
  File "/usr/lib/python3.11/site-packages/pipenv/resolver.py", line 661, in main
    _main(
  File "/usr/lib/python3.11/site-packages/pipenv/resolver.py", line 645, in _main
    resolve_packages(
  File "/usr/lib/python3.11/site-packages/pipenv/resolver.py", line 612, in resolve_packages
    results, resolver = resolve(
  File "/usr/lib/python3.11/site-packages/pipenv/resolver.py", line 592, in resolve
    return resolve_deps(
  File "/usr/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 897, in resolve_deps
    results, hashes, internal_resolver = actually_resolve_deps(
  File "/usr/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 670, in actually_resolve_deps
    resolver.resolve()
  File "/usr/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 447, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: [31m[1mERROR[0m: [33mNo matching distribution found for private_package==0.47.2[0m
✘ Locking Failed!
</pre>
</details>

### Steps to replicate

Here is a Pipfile that looks like the one I'm using:

```pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url =  "https://VssSessionToken:<token>@pkgs.dev.azure.com/<account>/<project>/_packaging/<feed>/pypi/simple/"
verify_ssl = true
name = "azure"

[packages]
private_package = {version = "==0.47.2", index = "azure"}
```

Using pipenv v2023.7.9 the output of `pipenv lock` is: `✔ Success!` 

However, when using pipenv v2023.9.8: `pipenv lock --verbose` gives the error output above.

---

Issues that might be related:
- https://github.com/pypa/pipenv/issues/5767
- https://github.com/pypa/pipenv/issues/5932

**Comment by matteius** [comment]
Possibly it needs to be named `private-package` -- I've done testing at least of a number of private registries (not azure yet) and haven't seen this issue yet.

**Comment by gbottari** [comment]
@matteius Thanks for the suggestion, but renaming it to `private-package` and it didn't work.

Since you think that other private registries work, I can try setting up a testing one within Azure to help reproduce.
