### ISSUE TITLE
pipenv 2023.10.3 ParseException with dependency name containing square brackets

### ISSUE THREAD

**Issue by command-tab** [pypa/pipenv#5962]
### Issue description

When running `pipenv lock` or `pipenv install --dev`, pipenv 2023.10.3 throws a ParseException and fails with a RuntimeError when the Pipfile contains a dependency with square brackets in its name, e.g. `'dramatiq[redis, watch]' = "==1.14.2"` (as shown in [dramatiq's documentation](https://dramatiq.io/installation.html)). This issue does not occur in the previous 2023.9.8 release.

### Expected result

I expected pipenv to successfully resolve dependencies and create/update the lockfile.

### Actual result

pipenv fails to parse the dependency and throws an exception.

### Steps to replicate

1. Create a new pipenv virtualenv with the default Pipfile. Then add one dependency containing square brackets, resulting in a Pipfile like this:

    ```toml
    [[source]]
    url = "https://pypi.python.org/simple"
    verify_ssl = true
    name = "pypi"
    
    [packages]
    'dramatiq[redis, watch]' = "==1.14.2"
    
    [dev-packages]
    
    [requires]
    python_version = "3.11"
    python_full_version = "3.11.5"
    ```
2. Run `pipenv lock` or `pipenv install --dev`
3. Exception is thrown:

   ```
   $ pipenv lock
    Locking [packages] dependencies...
    Building requirements...
    Resolving dependencies...
    Locking Failed!
    ⠸ Locking...False
    Traceback (most recent call last):
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/packaging/requirements.py", line 102, in __init__
        req = REQUIREMENT.parseString(requirement_string)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/pyparsing/util.py", line 256, in _inner
        return fn(self, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/pyparsing/core.py", line 1190, in parse_string
        raise exc.with_traceback(None)
    pipenv.patched.pip._vendor.pyparsing.exceptions.ParseException: Expected string_end, found ']'  (at char 5), (line:1, col:6)
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/patched/pip/_internal/req/constructors.py", line 341, in _parse_req_string
        req = get_requirement(req_as_string)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/patched/pip/_internal/utils/packaging.py", line 45, in get_requirement
        return Requirement(req_string)
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/packaging/requirements.py", line 104, in __init__
        raise InvalidRequirement(
    pipenv.patched.pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'], drama'": Expected string_end
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/resolver.py", line 675, in <module>
        main()
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/resolver.py", line 661, in main
        _main(
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/resolver.py", line 645, in _main
        resolve_packages(
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/resolver.py", line 612, in resolve_packages
        results, resolver = resolve(
                            ^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/resolver.py", line 592, in resolve
        return resolve_deps(
               ^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 892, in resolve_deps
        results, hashes, internal_resolver = actually_resolve_deps(
                                             ^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 654, in actually_resolve_deps
        resolver = Resolver.create(
                   ^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 204, in create
        install_req, _ = expansive_install_req_from_line(dep, expand_env=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/utils/dependencies.py", line 987, in expansive_install_req_from_line
        parts = parse_req_from_line(pip_line, line_source)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/patched/pip/_internal/req/constructors.py", line 369, in parse_req_from_line
        req: Optional[Requirement] = _parse_req_string(req_as_string)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/patched/pip/_internal/req/constructors.py", line 355, in _parse_req_string
        raise InstallationError(msg)
    pipenv.patched.pip._internal.exceptions.InstallationError: Invalid requirement: 'watch], dramatiq[redis, watch]==1.14.2'
    
    Traceback (most recent call last):
      File "/Users/callen/.pyenv/versions/3.11.3/bin/pipenv", line 8, in <module>
        sys.exit(cli())
                 ^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1130, in __call__
        return self.main(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/cli/options.py", line 58, in main
        return super().main(*args, **kwargs, windows_expand_args=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1055, in main
        rv = self.invoke(ctx)
             ^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1657, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1404, in invoke
        return ctx.invoke(self.callback, **ctx.params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
        return __callback(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
        return ctx.invoke(f, obj, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 760, in invoke
        return __callback(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 26, in new_func
        return f(get_current_context(), *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/cli/command.py", line 340, in lock
        do_lock(
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/routines/lock.py", line 65, in do_lock
        venv_resolve_deps(
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 833, in venv_resolve_deps
        c = resolve(cmd, st, project=project)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/callen/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 702, in resolve
        raise RuntimeError("Failed to lock Pipfile.lock!")
    RuntimeError: Failed to lock Pipfile.lock!
   ```

### Version Information

* macOS Sonoma 14.0 (23A344)
* Python 3.11.3 via pyenv
* pip 23.2.1
* pipenv 2023.10.3

Thank you ❤️

**Comment by matteius** [comment]
@command-tab Those extras should be defined under the extras key, so for your example the Pipfile entry should be:
`dramatiq = {version = "==1.14.2", extras = ["redis", "watch"]}` where the key is the package name.   I believe this is the entry you would get if you ran `pipenv install dramatiq[redis, watch]`

**Comment by command-tab** [comment]
TIL about the `extras` key! That does indeed work in the Pipfile, as does `pipenv install 'dramatiq[rabbitmq, watch]'`. I've been specifying this incorrectly for quite some time, and only just now got bit by it. Thanks!
