### ISSUE TITLE
python.exe: No module named poetry

### ISSUE THREAD

**Issue by ghusrcm** [pypa/pipenv#5976]
### Issue description
When following the steps described at https://www.youtube.com/watch?v=YSGqfT0mlWA, 

### Expected result
Welcome to  Auto-GPT

### Actual result
The system cannot find the file specified.
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\AutoGPT-agbenchmark-v0.0.10\AutoGPT-agbenchmark-v0.0.10\autogpts\autogpt\scripts\check_requirements.py", line 11, in <module>
    from poetry.factory import Factory
ModuleNotFoundError: No module named 'poetry'
ECHO is off.
C:\Users\Administrator\AppData\Local\Programs\Python\Python312\python.exe: No module named poetry
ECHO is off.
Finished installing packages Starting AutoGPT...
ECHO is off.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Administrator\Downloads\AutoGPT-agbenchmark-v0.0.10\AutoGPT-agbenchmark-v0.0.10\autogpts\autogpt\autogpt\__main__.py", line 2, in <module>
    import autogpt.app.cli
  File "C:\Users\Administrator\Downloads\AutoGPT-agbenchmark-v0.0.10\AutoGPT-agbenchmark-v0.0.10\autogpts\autogpt\autogpt\app\__init__.py", line 1, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
Press any key to continue . . .

### Steps to replicate
1) Downloaded the latest release.
2) Renamed .env.template to just .env
3) Opened run.bat

**Comment by matteius** [comment]
I do not understand this issue report.
