### ISSUE TITLE
Error messages when attempting to install package that isn't found aren't informative

### ISSUE THREAD

**Issue by JohnAtl** [pypa/pipenv#5995]
### Issue description

When one attempts to install a package that isn't found, the errors printed are 64 lines long(!). This can be especially troublesome for new users.

### Expected result

A message such as:
Package 'fake-package' was not found

### Actual result

❯ pipenv install fake-package
Installing fake-package...
Resolving fake-package...
Added fake-package to Pipfile's [packages] ...
✔ Installation Succeeded
Pipfile.lock (3bac23) out of date, updating to (682f89)...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
⠏ Locking...False
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not find a version that satisfies the requirement fake-package (from versions: none)
[ResolutionFailure]:   File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/resolver.py", line 645, in _main
[ResolutionFailure]:       resolve_packages(
[ResolutionFailure]:   File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/resolver.py", line 612, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/resolver.py", line 592, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 908, in resolve_deps
[ResolutionFailure]:       results, hashes, internal_resolver = actually_resolve_deps(
[ResolutionFailure]:   File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 681, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 442, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv run pip install <requirement_name> to bypass this mechanism, then run $ pipenv graph to inspect the versions actually installed in the virtualenv.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: No matching distribution found for fake-package

Traceback (most recent call last):
  File "/home/john/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/cli/command.py", line 209, in install
    do_install(
  File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/routines/install.py", line 297, in do_install
    raise e
  File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/routines/install.py", line 281, in do_install
    do_init(
  File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/routines/install.py", line 648, in do_init
    do_lock(
  File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/routines/lock.py", line 65, in do_lock
    venv_resolve_deps(
  File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 849, in venv_resolve_deps
    c = resolve(cmd, st, project=project)
  File "/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv/utils/resolver.py", line 718, in resolve
    raise RuntimeError("Failed to lock Pipfile.lock!")
RuntimeError: Failed to lock Pipfile.lock!

### Steps to replicate

pipenv install fake-package

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2023.10.24'`

Pipenv location: `'/home/john/.local/pipx/venvs/pipenv/lib/python3.10/site-packages/pipenv'`

Python location: `'/home/john/.local/pipx/venvs/pipenv/bin/python'`

OS Name: `'posix'`

User pip version: `'23.3.1'`

user Python installations found:

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.10',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '6.1.0-13-amd64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29)',
 'python_full_version': '3.10.10',
 'python_version': '3.10',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LANG`
  - `USER`
  - `LOGNAME`
  - `HOME`
  - `PATH`
  - `SHELL`
  - `TERM`
  - `DISPLAY`
  - `XDG_SESSION_ID`
  - `XDG_RUNTIME_DIR`
  - `DBUS_SESSION_BUS_ADDRESS`
  - `XDG_SESSION_TYPE`
  - `XDG_SESSION_CLASS`
  - `MOTD_SHOWN`
  - `XLA_FLAGS`
  - `SSH_CLIENT`
  - `SSH_CONNECTION`
  - `SSH_TTY`
  - `SHLVL`
  - `PWD`
  - `OLDPWD`
  - `rvm_path`
  - `rvm_prefix`
  - `rvm_bin_path`
  - `rvm_version`
  - `ATUIN_SESSION`
  - `ATUIN_HISTORY`
  - `XDG_DATA_DIRS`
  - `CONDA_EXE`
  - `_CE_M`
  - `_CE_CONDA`
  - `CONDA_PYTHON_EXE`
  - `CONDA_SHLVL`
  - `CONDA_PREFIX`
  - `CONDA_DEFAULT_ENV`
  - `CONDA_PROMPT_MODIFIER`
  - `LD_LIBRARY_PATH`
  - `STARSHIP_SHELL`
  - `STARSHIP_SESSION_KEY`
  - `iam`
  - `CONDA_HOME`
  - `GEM_HOME`
  - `ATUIN_HISTORY_ID`
  - `_`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/home/john/.local/bin:/home/john/.local/apps:/home/john/gems/bin:/home/john/miniconda3/bin:/home/john/miniconda3/bin:/home/john/miniconda3/condabin:/home/john/.config/emacs/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/usr/local/rvm/bin`
  - `SHELL`: `/usr/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/home/john`

---------------------------

</details>

**Comment by matteius** [comment]
Do you find the output of `--verbose` to be any more helpful?
