### ISSUE TITLE
Resolution Failure Poor Error Message or Bug

### ISSUE THREAD

**Issue by jamesstidard** [pypa/pipenv#6004]
### Issue description

I'm trying to `pipenv upgrade -v --index my-index my-package==1.0.50`, but I get a ResolutionFailure that says:

```console
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Cannot install my-package==1.0.50 because these package versions have conflicting dependencies.
INFO:pipenv.patched.pip._internal.resolution.resolvelib.factory:
The conflict is caused by:
    The user requested my-package==1.0.50
    The user requested (constraint) my-package==1.0.50
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

I've inspected the versions required in the `setup.py` of `my-package` and compared them to the versions of the same dependancies within my projects `Pipfile` and `Pipfile.lock`. As far as I can see, there should be no conflict.

### Expected result

I would maybe expect a better error, like the ones that appears in these docs: https://pip.pypa.io/en/latest/topics/dependency-resolution/#understanding-your-error-message, but the message I get makes me think that maybe it's a bug, or a misconfiguration.

These updates have worked in the past with `pipenv update --keep-outdated my-package==x.y.z`. I dont believe much has changed to the two projects since `--keep-outdated` was removed.

### Actual result

```
$ pipenv upgrade -v --index my-pypi my-package==1.0.50
Loading .env environment variables...
Building requirements...
Resolving dependencies...
INFO:pipenv.patched.pip._internal.network.session:adding trusted host: 'my.pypi.local' (from line 3 of 
/var/folders/5v/x8dcvr4n2wl0dlq2pxd35y2w0000gn/T/pipenv-76z845wd-requirements/pipenv-zivt4uts-constraints.txt)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting()
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('my-package==1.0.50'), None)
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Cannot install my-package==1.0.50 because these package versions have conflicting dependencies.
INFO:pipenv.patched.pip._internal.resolution.resolvelib.factory:
The conflict is caused by:
    The user requested my-package==1.0.50
    The user requested (constraint) my-package==1.0.50
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
Traceback (most recent call last):
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 174, in _add_to_criteria
    raise RequirementsConflicted(criterion)
pipenv.patched.pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('my-package==1.0.50')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 399, in resolve
    raise ResolutionImpossible(e.criterion.information)
pipenv.patched.pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('my-package==1.0.50'), parent=None)]
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 440, in resolve
    results = resolver.resolve(constraints, check_supported_wheels=False)
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/resolver.py", line 104, in resolve
    raise error from e
pipenv.patched.pip._internal.exceptions.DistributionNotFound: ResolutionImpossible: for help visit 
https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/resolver.py", line 675, in <module>
    main()
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/resolver.py", line 661, in main
    _main(
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/resolver.py", line 645, in _main
    resolve_packages(
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/resolver.py", line 612, in resolve_packages
    results, resolver = resolve(
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/resolver.py", line 592, in resolve
    return resolve_deps(
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 908, in resolve_deps
    results, hashes, internal_resolver = actually_resolve_deps(
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 681, in actually_resolve_deps
    resolver.resolve()
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 442, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: [31m[1mERROR[0m: [33mResolutionImpossible: for help visit 
https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts[0m
✘ Locking Failed!
⠦ Locking...
Traceback (most recent call last):
  File "/Users/james/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/cli/options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/cli/command.py", line 251, in upgrade
    upgrade(
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/routines/update.py", line 156, in upgrade
    upgrade_lock_data = venv_resolve_deps(
                        ^^^^^^^^^^^^^^^^^^
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 849, in venv_resolve_deps
    c = resolve(cmd, st, project=project)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/.local/pipx/venvs/pipenv/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 718, in resolve
    raise RuntimeError("Failed to lock Pipfile.lock!")
RuntimeError: Failed to lock Pipfile.lock!
```

**Comment by matteius** [comment]
Could be related to something else I observed recently with packages that have a dash in Pipfile -- have you tired installing `my_package`.

**Comment by matteius** [comment]
@jamesstidard Try adding `PIPENV_RESOLVER_PARENT_PYTHON = 1` to your .env or environment and running with `--verbose`  that will invoke the resolver in the same parent process as pipenv which sometimes makes it easier to spot something in the logging.   Let me know if this helps ...

**Comment by jamesstidard** [comment]
@thomas-oaknorth unfortunately not, I'm sorry to say I've actually started migrating to poetry in hopes of better errors, though maybe it'll be the same, if both pipenv and poetry are built on pip.

**Comment by matteius** [comment]
poetry is not built on pip from what I understand, it uses its own resolver and mechanisms.
