### ISSUE TITLE
TypeError: argument of type 'Integer' is not iterable

### ISSUE THREAD

**Issue by bitjerry** [pypa/pipenv#6040]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

Check the [diagnose documentation](https://pipenv.pypa.io/en/latest/diagnose/) for common issues before posting! We may close your issue if it is very similar to one of them. Please be considerate, or be on your way.

Make sure to mention your debugging experience if the documented solution failed.

### Issue description

Describe the issue briefly here.

### Expected result

Describe what you expected.

### Actual result

```
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting()
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('bs4')
, None)
INFO:pipenv.patched.pip._internal.operations.prepare:Collecting bs4 (from -r
C:\Users\Mr.lin\AppData\Local\Temp\pipenv-catp1jiz-requirements\pipenv-5x0aop2d-constraints.txt (line 4))
INFO:pipenv.patched.pip._internal.operations.prepare:Using cached bs4-0.0.1-py3-none-any.whl
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('argpa
rse'), None)
INFO:pipenv.patched.pip._internal.operations.prepare:Collecting argparse (from -r
C:\Users\Mr.lin\AppData\Local\Temp\pipenv-catp1jiz-requirements\pipenv-5x0aop2d-constraints.txt (line 2))
INFO:pipenv.patched.pip._internal.network.download:Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('path'
), None)
INFO:pipenv.patched.pip._internal.operations.prepare:Collecting path (from -r
C:\Users\Mr.lin\AppData\Local\Temp\pipenv-catp1jiz-requirements\pipenv-5x0aop2d-constraints.txt (line 3))
INFO:pipenv.patched.pip._internal.operations.prepare:Obtaining dependency information for path from
https://files.pythonhosted.org/packages/9c/b1/bd656b3187552080182d3d30f2ac4dd5a239fd0ae3ef773602b8882d4644/path-16.9.0-p
y3-none-any.whl.metadata
INFO:pipenv.patched.pip._internal.network.download:Using cached path-16.9.0-py3-none-any.whl.metadata (6.7 kB)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('async
io'), None)
INFO:pipenv.patched.pip._internal.operations.prepare:Collecting asyncio (from -r
C:\Users\Mr.lin\AppData\Local\Temp\pipenv-catp1jiz-requirements\pipenv-5x0aop2d-constraints.txt (line 5))
INFO:pipenv.patched.pip._internal.network.download:Using cached asyncio-3.4.3-py3-none-any.whl (101 kB)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting_round(0)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('beaut
ifulsoup4'),
LinkCandidate('file:///C:/Users/Mr.lin/AppData/Local/pipenv/pipenv/Cache/wheels/d4/c8/5b/b5be9c20e5e4503d04a6eac8a3cd5c2
393505c29f02bea0960/bs4-0.0.1-py3-none-any.whl'))
INFO:pipenv.patched.pip._internal.operations.prepare:Collecting beautifulsoup4 (from bs4->-r
C:\Users\Mr.lin\AppData\Local\Temp\pipenv-catp1jiz-requirements\pipenv-5x0aop2d-constraints.txt (line 4))
INFO:pipenv.patched.pip._internal.network.download:Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.pinning(LinkCandidate('file:///C:/Users/Mr.lin
/AppData/Local/pipenv/pipenv/Cache/wheels/d4/c8/5b/b5be9c20e5e4503d04a6eac8a3cd5c2393505c29f02bea0960/bs4-0.0.1-py3-none
-any.whl'))
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.ending_round(0, state)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting_round(1)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.pinning(LinkCandidate('https://files.pythonhos
ted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
(from https://pypi.org/simple/argparse/)'))
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.ending_round(1, state)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting_round(2)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.pinning(LinkCandidate('https://files.pythonhos
ted.org/packages/9c/b1/bd656b3187552080182d3d30f2ac4dd5a239fd0ae3ef773602b8882d4644/path-16.9.0-py3-none-any.whl (from
https://pypi.org/simple/path/) (requires-python:>=3.8)'))
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.ending_round(2, state)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting_round(3)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.pinning(LinkCandidate('https://files.pythonhos
ted.org/packages/22/74/07679c5b9f98a7cb0fc147b1ef1cc1853bc07a4eb9cb5731e24732c5f773/asyncio-3.4.3-py3-none-any.whl (from
https://pypi.org/simple/asyncio/)'))
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.ending_round(3, state)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting_round(4)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.adding_requirement(SpecifierRequirement('soups
ieve>1.2'),
LinkCandidate('https://files.pythonhosted.org/packages/57/f4/a69c20ee4f660081a7dedb1ac57f29be9378e04edfcb90c526b923d4beb
c/beautifulsoup4-4.12.2-py3-none-any.whl (from https://pypi.org/simple/beautifulsoup4/) (requires-python:>=3.6.0)'))
INFO:pipenv.patched.pip._internal.operations.prepare:Collecting soupsieve>1.2 (from beautifulsoup4->bs4->-r
C:\Users\Mr.lin\AppData\Local\Temp\pipenv-catp1jiz-requirements\pipenv-5x0aop2d-constraints.txt (line 4))
INFO:pipenv.patched.pip._internal.operations.prepare:Obtaining dependency information for soupsieve>1.2 from
https://files.pythonhosted.org/packages/4c/f3/038b302fdfbe3be7da016777069f26ceefe11a681055ea1f7817546508e3/soupsieve-2.5
-py3-none-any.whl.metadata
INFO:pipenv.patched.pip._internal.network.download:Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.pinning(LinkCandidate('https://files.pythonhos
ted.org/packages/57/f4/a69c20ee4f660081a7dedb1ac57f29be9378e04edfcb90c526b923d4bebc/beautifulsoup4-4.12.2-py3-none-any.w
hl (from https://pypi.org/simple/beautifulsoup4/) (requires-python:>=3.6.0)'))
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.ending_round(4, state)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting_round(5)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.pinning(LinkCandidate('https://files.pythonhos
ted.org/packages/4c/f3/038b302fdfbe3be7da016777069f26ceefe11a681055ea1f7817546508e3/soupsieve-2.5-py3-none-any.whl (from
https://pypi.org/simple/soupsieve/) (requires-python:>=3.8)'))
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.ending_round(5, state)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting_round(6)
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.ending(State(mapping=OrderedDict([('bs4',
LinkCandidate('file:///C:/Users/Mr.lin/AppData/Local/pipenv/pipenv/Cache/wheels/d4/c8/5b/b5be9c20e5e4503d04a6eac8a3cd5c2
393505c29f02bea0960/bs4-0.0.1-py3-none-any.whl')), ('argparse',
LinkCandidate('https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2
f/argparse-1.4.0-py2.py3-none-any.whl (from https://pypi.org/simple/argparse/)')), ('path',
LinkCandidate('https://files.pythonhosted.org/packages/9c/b1/bd656b3187552080182d3d30f2ac4dd5a239fd0ae3ef773602b8882d464
4/path-16.9.0-py3-none-any.whl (from https://pypi.org/simple/path/) (requires-python:>=3.8)')), ('asyncio',
LinkCandidate('https://files.pythonhosted.org/packages/22/74/07679c5b9f98a7cb0fc147b1ef1cc1853bc07a4eb9cb5731e24732c5f77
3/asyncio-3.4.3-py3-none-any.whl (from https://pypi.org/simple/asyncio/)')), ('beautifulsoup4',
LinkCandidate('https://files.pythonhosted.org/packages/57/f4/a69c20ee4f660081a7dedb1ac57f29be9378e04edfcb90c526b923d4beb
c/beautifulsoup4-4.12.2-py3-none-any.whl (from https://pypi.org/simple/beautifulsoup4/) (requires-python:>=3.6.0)')),
('soupsieve',
LinkCandidate('https://files.pythonhosted.org/packages/4c/f3/038b302fdfbe3be7da016777069f26ceefe11a681055ea1f7817546508e
3/soupsieve-2.5-py3-none-any.whl (from https://pypi.org/simple/soupsieve/) (requires-python:>=3.8)'))]),
criteria={'bs4': Criterion((SpecifierRequirement('bs4'), via=None)), 'argparse':
Criterion((SpecifierRequirement('argparse'), via=None)), 'path': Criterion((SpecifierRequirement('path'), via=None)),
'asyncio': Criterion((SpecifierRequirement('asyncio'), via=None)), 'beautifulsoup4':
Criterion((SpecifierRequirement('beautifulsoup4'),
via=LinkCandidate('file:///C:/Users/Mr.lin/AppData/Local/pipenv/pipenv/Cache/wheels/d4/c8/5b/b5be9c20e5e4503d04a6eac8a3c
d5c2393505c29f02bea0960/bs4-0.0.1-py3-none-any.whl'))), 'soupsieve': Criterion((SpecifierRequirement('soupsieve>1.2'),
via=LinkCandidate('https://files.pythonhosted.org/packages/57/f4/a69c20ee4f660081a7dedb1ac57f29be9378e04edfcb90c526b923d
4bebc/beautifulsoup4-4.12.2-py3-none-any.whl (from https://pypi.org/simple/beautifulsoup4/)
(requires-python:>=3.6.0)')))}, backtrack_causes=[]))
INFO:pipenv.patched.pip._internal.network.download:Using cached path-16.9.0-py3-none-any.whl (24 kB)
INFO:pipenv.patched.pip._internal.network.download:Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
[=== ] Locking...
Success!
Locking [dev-packages] dependencies...
Locking [global] dependencies...
Building requirements...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\null\python\Scripts\pipenv.exe\__main__.py", line 7, in <module>
    # when invoked as python -m pip <command>
                 ^^^^^
  File "C:\null\python\Lib\site-packages\pipenv\vendor\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\null\python\Lib\site-packages\pipenv\cli\options.py", line 58, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\null\python\Lib\site-packages\pipenv\vendor\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\null\python\Lib\site-packages\pipenv\vendor\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\null\python\Lib\site-packages\pipenv\vendor\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\null\python\Lib\site-packages\pipenv\vendor\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\null\python\Lib\site-packages\pipenv\vendor\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\null\python\Lib\site-packages\pipenv\vendor\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\null\python\Lib\site-packages\pipenv\cli\command.py", line 209, in install
    do_install(
  File "C:\null\python\Lib\site-packages\pipenv\routines\install.py", line 164, in do_install
    do_init(
  File "C:\null\python\Lib\site-packages\pipenv\routines\install.py", line 672, in do_init
    do_lock(
  File "C:\null\python\Lib\site-packages\pipenv\routines\lock.py", line 65, in do_lock
    venv_resolve_deps(
  File "C:\null\python\Lib\site-packages\pipenv\utils\resolver.py", line 782, in venv_resolve_deps
    deps = convert_deps_to_pip(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\null\python\Lib\site-packages\pipenv\utils\dependencies.py", line 474, in convert_deps_to_pip
    req = dependency_as_pip_install_line(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\null\python\Lib\site-packages\pipenv\utils\dependencies.py", line 389, in dependency_as_pip_install_line
    vcs = next(iter([vcs for vcs in VCS_LIST if vcs in dep]), None)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\null\python\Lib\site-packages\pipenv\utils\dependencies.py", line 389, in <listcomp>
    vcs = next(iter([vcs for vcs in VCS_LIST if vcs in dep]), None)
                                                ^^^^^^^^^^
TypeError: argument of type 'Integer' is not iterable
```

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

-------------------------------------------------------------------------------

`pipenv install --verbose`

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[global]
timeout = 3600

[packages]
bs4 = "*"
path = "*"
asyncio = "*"
argparse = "*"

[dev-packages]

[requires]
python_version = "3.11"
python_full_version = "3.11.5"

```

</details>

**Comment by matteius** [comment]
The issue here stems from the [global] group which is being interpreted as a package category.   Its not one of the standard reserved group names as far as as I know -- do you have documentation about it?

**Comment by bitjerry** [comment]
> The issue here stems from the [global] group which is being interpreted as a package category. Its not one of the standard reserved group names as far as as I know -- do you have documentation about it?

This is a configuration option of pip, I thought pipenv also had such parameters. Sorry, it was my mistake.

**Comment by matteius** [comment]
@bitjerry I think it is possible to set those pip env vars and have them take effect in a .env file but not from the global section.
