### ISSUE TITLE
Can't install it on python3.12 with pipx

### ISSUE THREAD

**Issue by Harry-Jing** [pypa/pipenv#6110]
### Issue description

Can't install it on python3.12

### Steps to replicate
```cli
 ❯❯ pipx install pdm
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\Harry\.local\pipx\logs\cmd_2024-03-12_05.59.26_pip_errors.log

Some possibly relevant errors from pip install:
    AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

Error installing pdm.
```

Windows 11
Python3.12
pipx 1.4.3

cmd_2024-03-12_05.59.26_pip_errors.log
```
PIP STDOUT
----------

PIP STDERR
----------
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Harry\.local\pipx\shared\Lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\Harry\.local\pipx\shared\Lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Harry\.local\pipx\shared\Lib\site-packages\pip\_internal\commands\install.py", line 345, in run
    session = self.get_default_session(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Harry\.local\pipx\shared\Lib\site-packages\pip\_internal\cli\req_command.py", line 98, in get_default_session
    self._session = self.enter_context(self._build_session(options))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Harry\.local\pipx\shared\Lib\site-packages\pip\_internal\cli\req_command.py", line 125, in _build_session
    session = PipSession(
              ^^^^^^^^^^^
  File "C:\Users\Harry\.local\pipx\shared\Lib\site-packages\pip\_internal\network\session.py", line 343, in __init__
    self.headers["User-Agent"] = user_agent()
                                 ^^^^^^^^^^^^
  File "C:\Users\Harry\.local\pipx\shared\Lib\site-packages\pip\_internal\network\session.py", line 175, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Harry\.local\pipx\shared\Lib\site-packages\pip\_internal\metadata\importlib\_envs.py", line 188, in get_distribution
    return next(matches, None)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Harry\.local\pipx\shared\Lib\site-packages\pip\_internal\metadata\importlib\_envs.py", line 183, in <genexpr>
    matches = (
              ^
  File "C:\Users\Harry\.local\pipx\shared\Lib\site-packages\pip\_internal\metadata\base.py", line 612, in iter_all_distributions
    for dist in self._iter_distributions():
  File "C:\Users\Harry\.local\pipx\shared\Lib\site-packages\pip\_internal\metadata\importlib\_envs.py", line 176, in _iter_distributions
    for dist in finder.find_eggs(location):
  File "C:\Users\Harry\.local\pipx\shared\Lib\site-packages\pip\_internal\metadata\importlib\_envs.py", line 144, in find_eggs
    yield from self._find_eggs_in_dir(location)
  File "C:\Users\Harry\.local\pipx\shared\Lib\site-packages\pip\_internal\metadata\importlib\_envs.py", line 111, in _find_eggs_in_dir
    from pip._vendor.pkg_resources import find_distributions
  File "C:\Users\Harry\.local\pipx\shared\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2164, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

**Comment by cclauss** [comment]
Is this issue opened on the wrong repo?  Perhaps I am missing something but the issue seems to be about `pipx` and `pdm` and I do not see `pipenv` mentioned at all.

**Comment by matteius** [comment]
Just checking in here @Harry-Jing -- I wonder the same thing as @cclauss -- I am going to close this for now since the output clearly shows trying to install `pdm`.
