### ISSUE TITLE
get-pipenv.py fails with Python 3.12

### ISSUE THREAD

**Issue by RyPeck** [pypa/pipenv#6259]
### Issue description

`get-pipenv.py` fails using Python 3.12.

### Expected result

Script would succeed and pipenv would be installed.

### Actual result

```
root@1e0ce8402c0c:/# curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2110k  100 2110k    0     0  5534k      0 --:--:-- --:--:-- --:--:-- 5539k
Traceback (most recent call last):
  File "<stdin>", line 27131, in <module>
  File "<stdin>", line 189, in main
  File "<stdin>", line 164, in bootstrap
  File "<stdin>", line 145, in monkeypatch_for_cert
  File "/tmp/tmpee3o3rj4/pip.zip/pip/_internal/commands/__init__.py", line 9, in <module>
  File "/tmp/tmpee3o3rj4/pip.zip/pip/_internal/cli/base_command.py", line 13, in <module>
  File "/tmp/tmpee3o3rj4/pip.zip/pip/_internal/cli/cmdoptions.py", line 23, in <module>
  File "/tmp/tmpee3o3rj4/pip.zip/pip/_internal/cli/parser.py", line 12, in <module>
  File "/tmp/tmpee3o3rj4/pip.zip/pip/_internal/configuration.py", line 20, in <module>
  File "/tmp/tmpee3o3rj4/pip.zip/pip/_internal/exceptions.py", line 7, in <module>
  File "/tmp/tmpee3o3rj4/pip.zip/pip/_vendor/pkg_resources/__init__.py", line 2164, in <module>
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
root@1e0ce8402c0c:/# python -V
Python 3.12.6
```

### Steps to replicate

With Python 3.12 - run `curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python`.

Can use a Docker container - 

```
% docker run --rm -ti --entrypoint /bin/bash python:3.12 
root@ba8788ce9041:/# curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
...snip...
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```
-------------------------------------------------------------------------------

bash: pipenv: command not found

**Comment by oz123** [comment]
@RyPeck Can you please verify that the script works for you in the PR?

**Comment by RyPeck** [comment]
@oz123 worked for me! Thanks.

**Comment by oz123** [comment]
Thank you for providing feedback! @RyPeck
