### ISSUE TITLE
pipenv does not use or not working with python 3.7

### ISSUE THREAD

**Issue by MKisil** [pypa/pipenv#6265]
### Issue description

When I execute the following command in venv with python 3.7 (with any library): `pipenv install django`
I get the following error: `RuntimeError: Failed to lock Pipfile.lock!`

### Expected result

I expect to create a virtual environment with python 3.7, install the library, and create Pipfile.lock

### Actual result

Here are full traceback with all commands:

```
PS D:\test> pipenv --venv
No virtualenv has been created for this projectD:\test yet!
Aborted!
PS D:\test> pipenv shell --python 3.7
Creating a virtualenv for this project
Pipfile: D:\test\Pipfile
Using C:/Users/mihaj/AppData/Local/Programs/Python/Python37/python.exe3.7.0 to create virtualenv...
[    ] Creating virtual environment...created virtual environment CPython3.7.0.final.0-64 in 479ms
  creator CPython3Windows(dest=C:\Users\mihaj\.virtualenvs\test-0PsIO9xF, clear=False, no_vcs_ignore=False,
global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy,
app_data_dir=C:\Users\mihaj\AppData\Local\pypa\virtualenv)
    added seed packages: pip==24.0, setuptools==68.0.0, wheel==0.42.0
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Successfully created virtual environment!
Virtualenv location: C:\Users\mihaj\.virtualenvs\test-0PsIO9xF
Launching subshell in virtual environment...
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS D:\test> pipenv --version
pipenv, version 2024.1.0
PS D:\test> python -V
Python 3.7.0
PS D:\test> pipenv install django --verbose
Installing django...
Resolving django...
Added django to Pipfile's [packages] ...
Installation Succeeded
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
Traceback (most recent call last):
  File "C:/Users/mihaj/AppData/Local/Programs/Python/Python312/Lib/site-packages/pipenv/resolver.py", line 6, in
<module>
    from functools import cached_property
ImportError: cannot import name 'cached_property' from 'functools'
(C:\Users\mihaj\AppData\Local\Programs\Python\Python37\lib\functools.py)
Locking Failed!
[    ] Locking packages...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Scripts\pipenv.exe\__main__.py", line 7, in <module>
    # when invoked as python -m pip <command>
                 ^^^^^
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipenv\vendor\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipenv\cli\options.py", line 52, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipenv\vendor\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipenv\vendor\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipenv\vendor\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipenv\vendor\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipenv\vendor\click\decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipenv\vendor\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipenv\cli\command.py", line 207, in install
    do_install(
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipenv\routines\install.py", line 234, in do_install
    raise e
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipenv\routines\install.py", line 209, in do_install
    do_init(
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipenv\routines\install.py", line 649, in do_init
    do_lock(
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipenv\routines\lock.py", line 67, in do_lock
    venv_resolve_deps(
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipenv\utils\resolver.py", line 859, in venv_resolve_deps
    c = resolve(cmd, st, project=project)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mihaj\AppData\Local\Programs\Python\Python312\Lib\site-packages\pipenv\utils\resolver.py", line 723, in resolve
    raise RuntimeError("Failed to lock Pipfile.lock!")
RuntimeError: Failed to lock Pipfile.lock!
```

### Steps to replicate

`pipenv shell --python 3.7`
`pipenv install django --verbose`

-------------------------------------------------------------------------------

```
PS D:\test> pipenv --support | clip
PS D:\test>
```

**Comment by oz123** [comment]
Matt already answered it. We can't support EOL versions of Python. Our hands are full anyway.
