### ISSUE TITLE
pipenv lock failing

### ISSUE THREAD

**Issue by cchristous** [pypa/pipenv#6274]
### Issue description

Hi,

I am seeing an issue when running `pipenv lock`. See the logs below.

<details><summary>Logs</summary>

```
Command failed: pipenv lock
Creating a virtualenv for this project
Pipfile: 
/tmp/renovate/repos/github/redacted-org/redacted-repo-name/Pipfile
Using /opt/containerbase/tools/python/3.11.10/bin/python3.11.10 to create 
virtualenv...
created virtual environment CPython3.11.10.final.0-64 in 421ms
  creator 
CPython3Posix(dest=/tmp/renovate/cache/others/virtualenvs/assume-codeartifact-wr
iter-gSKShA4x, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, 
wheel=bundle, via=copy, app_data_dir=/tmp/tmpk43ln2ux)
    added seed packages: pip==24.2, setuptools==75.1.0, wheel==0.44.0
  activators 
BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator
,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /tmp/renovate/cache/others/virtualenvs/redacted-repo-name-gSKShA4x
Locking [packages] dependencies...
False
<console width=80 None>
Traceback (most recent call last):
  File "/opt/containerbase/tools/pipenv/2024.1.0/3.11.10/bin/pipenv", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/containerbase/tools/pipenv/2024.1.0/3.11.10/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pipenv/2024.1.0/3.11.10/lib/python3.11/site-packages/pipenv/cli/options.py", line 52, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pipenv/2024.1.0/3.11.10/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pipenv/2024.1.0/3.11.10/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pipenv/2024.1.0/3.11.10/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pipenv/2024.1.0/3.11.10/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pipenv/2024.1.0/3.11.10/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pipenv/2024.1.0/3.11.10/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pipenv/2024.1.0/3.11.10/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pipenv/2024.1.0/3.11.10/lib/python3.11/site-packages/pipenv/cli/command.py", line 342, in lock
    do_lock(
  File "/opt/containerbase/tools/pipenv/2024.1.0/3.11.10/lib/python3.11/site-packages/pipenv/routines/lock.py", line 67, in do_lock
    venv_resolve_deps(
  File "/opt/containerbase/tools/pipenv/2024.1.0/3.11.10/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 859, in venv_resolve_deps
    c = resolve(cmd, st, project=project)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/containerbase/tools/pipenv/2024.1.0/3.11.10/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 723, in resolve
    raise RuntimeError("Failed to lock Pipfile.lock!")
RuntimeError: Failed to lock Pipfile.lock!

```
</details>

It's not clear to me why this is failing. It started failing within the last week or so. I thought this was related to the new 2024.1.0 version, but I was able to reproduce with 2024.0.3.

This relates to https://github.com/renovatebot/renovate/discussions/31860.

Any idea what is going on here or a good way to debug?

I can reproduce locally with renovatebot, but I can't reproduce locally on the repos using my laptop's configuration.

### Expected result

I expected the Pipfile.lock to be updated with the latest versions.

### Actual result

The command failed with an unclear message.

I don't believe I can run this with the --verbose option.

### Steps to replicate

I can't provide steps to replicate unfortunately because this runs inside self hosted renovatebot.

**Comment by cchristous** [comment]
I was able to get this working.

The stdout was getting logged elsewhere, so it wasn't easy to see what was going wrong.

<details><summary>stdout Logs</summary>
```
Building requirements...
Resolving dependencies...
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.starting()
INFO:pipenv.patched.pip._internal.resolution.resolvelib.reporter:Reporter.adding
_requirement(SpecifierRequirement('cryptography==37.0.4'), None)
CRITICAL:pipenv.patched.pip._internal.resolution.resolvelib.factory:Could not 
find a version that satisfies the requirement cryptography==37.0.4 (from 
versions: none)
Traceback (most recent call last):
  File 
\"/opt/containerbase/tools/pipenv/2024.0.3/3.11.10/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py\", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File 
\"/opt/containerbase/tools/pipenv/2024.0.3/3.11.10/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py\", line 174, in 
_add_to_criteria
    raise RequirementsConflicted(criterion)
pipenv.patched.pip._vendor.resolvelib.resolvers.RequirementsConflicted: 
Requirements conflict: SpecifierRequirement('cryptography==37.0.4')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File 
\"/opt/containerbase/tools/pipenv/2024.0.3/3.11.10/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/resolver.py\", line 95, in 
resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File 
\"/opt/containerbase/tools/pipenv/2024.0.3/3.11.10/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py\", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File 
\"/opt/containerbase/tools/pipenv/2024.0.3/3.11.10/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py\", line 399, in resolve
    raise ResolutionImpossible(e.criterion.information)
pipenv.patched.pip._vendor.resolvelib.resolvers.ResolutionImpossible: 
[RequirementInformation(requirement=SpecifierRequirement('cryptography==37.0.4')
, parent=None)]
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File 
\"/opt/containerbase/tools/pipenv/2024.0.3/3.11.10/lib/python3.11/site-packages/pipenv/utils/resolver.py\", line 443, in resolve
    results = resolver.resolve(constraints, check_supported_wheels=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File 
\"/opt/containerbase/tools/pipenv/2024.0.3/3.11.10/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/resolver.py\", line 104, in 
resolve
    raise error from e
pipenv.patched.pip._internal.exceptions.DistributionNotFound: No matching 
distribution found for cryptography==37.0.4
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File 
\"/opt/containerbase/tools/pipenv/2024.0.3/3.11.10/lib/python3.11/site-packages/pipenv/resolver.py\", line 671, in <module>
    main()
  File 
\"/opt/containerbase/tools/pipenv/2024.0.3/3.11.10/lib/python3.11/site-packages/pipenv/resolver.py\", line 657, in main
    _main(
  File 
\"/opt/containerbase/tools/pipenv/2024.0.3/3.11.10/lib/python3.11/site-packages/pipenv/resolver.py\", line 641, in _main
    resolve_packages(
  File 
\"/opt/containerbase/tools/pipenv/2024.0.3/3.11.10/lib/python3.11/site-packages/pipenv/resolver.py\", line 608, in resolve_packages
    results, resolver = resolve(
                        ^^^^^^^^
  File 
\"/opt/containerbase/tools/pipenv/2024.0.3/3.11.10/lib/python3.11/site-packages/pipenv/resolver.py\", line 588, in resolve
    return resolve_deps(
           ^^^^^^^^^^^^^
  File 
\"/opt/containerbase/tools/pipenv/2024.0.3/3.11.10/lib/python3.11/site-packages/pipenv/utils/resolver.py\", line 920, in resolve_deps
    results, hashes, internal_resolver = actually_resolve_deps(
                                         ^^^^^^^^^^^^^^^^^^^^^^
  File 
\"/opt/containerbase/tools/pipenv/2024.0.3/3.11.10/lib/python3.11/site-packages/pipenv/utils/resolver.py\", line 687, in actually_resolve_deps
    resolver.resolve()
  File 
\"/opt/containerbase/tools/pipenv/2024.0.3/3.11.10/lib/python3.11/site-packages/pipenv/utils/resolver.py\", line 445, in resolve
    raise ResolutionFailure(message=str(e))
pipenv.exceptions.ResolutionFailure: ERROR: \u001b[33mNo matching distribution found 
for cryptography==37.0.4\u001b[0m
✘ Locking Failed!
```
</details>

It turned out that the auth token wasn't set in the expected environment variable. Setting the variable made things work.
