### ISSUE TITLE
pipenv 2024.3.0 fails with "location not created nor specified" error in python3.12 docker image

### ISSUE THREAD

**Issue by asmisha** [pypa/pipenv#6295]
### Issue description

After updating to 2024.3.0 the docker image stopped building in one of my projects:

```
FROM python:3.12 as base

RUN pip install pipenv
RUN pipenv install --system
```

```
 > [base 8/8] RUN pip debug && pipenv --version && pipenv install --system:
0.502 WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
0.502 pip version: pip 24.2 from /usr/local/lib/python3.12/site-packages/pip (python 3.12)
0.503 sys.version: 3.12.7 (main, Oct 19 2024, 04:14:06) [GCC 12.2.0]
0.503 sys.executable: /usr/local/bin/python3.12
0.504 sys.getdefaultencoding: utf-8
0.504 sys.getfilesystemencoding: utf-8
0.505 locale.getpreferredencoding: UTF-8
0.505 sys.platform: linux
0.505 sys.implementation:
0.506   name: cpython
0.506 'cert' config value: Not specified
0.507 REQUESTS_CA_BUNDLE: None
0.507 CURL_CA_BUNDLE: None
0.509 pip._vendor.certifi.where(): /usr/local/lib/python3.12/site-packages/pip/_vendor/certifi/cacert.pem
0.509 pip._vendor.DEBUNDLED: False
0.509 vendored library versions:
0.611   CacheControl==0.14.0
0.611   distlib==0.3.8
0.615   distro==1.9.0
0.615   msgpack==1.0.8
0.616   packaging==24.1
0.616   platformdirs==4.2.2
0.617   pyproject-hooks==1.0.0
0.617   requests==2.32.3
0.618   certifi==2024.07.04
0.618   idna==3.7
0.618   urllib3==1.26.18
0.636   rich==13.7.1 (Unable to locate actual module version, using vendor.txt specified version)
0.636   pygments==2.18.0
0.637   typing_extensions==4.12.2 (Unable to locate actual module version, using vendor.txt specified version)
0.640   resolvelib==1.0.1
0.640   setuptools==70.3.0 (Unable to locate actual module version, using vendor.txt specified version)
0.655   tomli==2.0.1
0.656   truststore==0.9.1
0.662 Compatible tags: 987
0.662   cp312-cp312-manylinux_2_36_x86_64
0.662   cp312-cp312-manylinux_2_35_x86_64
0.663   cp312-cp312-manylinux_2_34_x86_64
0.663   cp312-cp312-manylinux_2_33_x86_64
0.663   cp312-cp312-manylinux_2_32_x86_64
0.664   cp312-cp312-manylinux_2_31_x86_64
0.664   cp312-cp312-manylinux_2_30_x86_64
0.664   cp312-cp312-manylinux_2_29_x86_64
0.665   cp312-cp312-manylinux_2_28_x86_64
0.666   cp312-cp312-manylinux_2_27_x86_64
0.666   ...
0.666   [First 10 tags shown. Pass --verbose to show all.]
1.203 pipenv, version 2024.3.0
1.752 Traceback (most recent call last):
1.752   File "/usr/local/bin/pipenv", line 8, in <module>
1.753     sys.exit(cli())
1.753              ^^^^^
1.753   File "/usr/local/lib/python3.12/site-packages/pipenv/vendor/click/core.py", line 1157, in __call__
1.754     return self.main(*args, **kwargs)
1.754            ^^^^^^^^^^^^^^^^^^^^^^^^^^
1.754   File "/usr/local/lib/python3.12/site-packages/pipenv/cli/options.py", line 52, in main
1.754     return super().main(*args, **kwargs, windows_expand_args=False)
1.754            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.754   File "/usr/local/lib/python3.12/site-packages/pipenv/vendor/click/core.py", line 1078, in main
1.754     rv = self.invoke(ctx)
1.754          ^^^^^^^^^^^^^^^^
1.754   File "/usr/local/lib/python3.12/site-packages/pipenv/vendor/click/core.py", line 1688, in invoke
1.755     return _process_result(sub_ctx.command.invoke(sub_ctx))
1.755                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.755   File "/usr/local/lib/python3.12/site-packages/pipenv/vendor/click/core.py", line 1434, in invoke
1.755     return ctx.invoke(self.callback, **ctx.params)
1.755            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.755   File "/usr/local/lib/python3.12/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
1.755     return __callback(*args, **kwargs)
1.755            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.755   File "/usr/local/lib/python3.12/site-packages/pipenv/vendor/click/decorators.py", line 92, in new_func
1.756     return ctx.invoke(f, obj, *args, **kwargs)
1.756            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.756   File "/usr/local/lib/python3.12/site-packages/pipenv/vendor/click/core.py", line 783, in invoke
1.756     return __callback(*args, **kwargs)
1.756            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.756   File "/usr/local/lib/python3.12/site-packages/pipenv/cli/command.py", line 207, in install
1.756     do_install(
1.756   File "/usr/local/lib/python3.12/site-packages/pipenv/routines/install.py", line 309, in do_install
1.757     new_packages, _ = handle_new_packages(
1.757                       ^^^^^^^^^^^^^^^^^^^^
1.757   File "/usr/local/lib/python3.12/site-packages/pipenv/routines/install.py", line 114, in handle_new_packages
1.757     do_update(
1.757   File "/usr/local/lib/python3.12/site-packages/pipenv/routines/update.py", line 51, in do_update
1.757     ensure_project(
1.757   File "/usr/local/lib/python3.12/site-packages/pipenv/utils/project.py", line 96, in ensure_project
1.757     os.environ["PIP_PYTHON_PATH"] = project.python(system=system)
1.757                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.757   File "/usr/local/lib/python3.12/site-packages/pipenv/project.py", line 1418, in python
1.757     return project_python(self, system=system)
1.757            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.757   File "/usr/local/lib/python3.12/site-packages/pipenv/utils/shell.py", line 408, in project_python
1.758     python = project._which("python")
1.758              ^^^^^^^^^^^^^^^^^^^^^^^^
1.758   File "/usr/local/lib/python3.12/site-packages/pipenv/project.py", line 1427, in _which
1.758     raise RuntimeError("location not created nor specified")
1.758 RuntimeError: location not created nor specified
```

### Steps to replicate

Here is the repo that reproduces the error. https://github.com/asmisha/pipenv-install-fail-demo

**Comment by kidris-apolitical** [comment]
I am experiencing the same issue. Pinning the version to `2024.1.0` did the trick.

```Dockerfile
FROM python:3.11

...

# install dependencies
RUN python3 -m pip install -U pip && pip install pipenv==2024.1.0
```

**Comment by matteius** [comment]
Huh, we have a single test of `--syststem` flag but it also has `--deploy` -- I wonder if `pipenv install --system --deploy` would work as-is?   I'll have to look into this more, but probably won't have time today.

**Comment by asmisha** [comment]
> Huh, we have a single test of `--syststem` flag but it also has `--deploy` -- I wonder if `pipenv install --system --deploy` would work as-is? I'll have to look into this more, but probably won't have time today.

I confirm it works with `--deploy` flag and fails without it.

**Comment by matteius** [comment]
X-Post;  I just opened https://github.com/pypa/pipenv/pull/6297 -- if you could give it a whirl that would help validate it.  I also added a test.

**Comment by cristiancastano852** [comment]
The same problem with python 3.8 (python:3.8-slim)

**Comment by matteius** [comment]
2024.3.1 has been released
