### ISSUE TITLE
After installing packages: pip._vendor.requests.exceptions.SSLError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by prcastro** [pypa/pipenv#854]
After creating a Python 3 environment, I runned the following command to install some packages:

```
$ pipenv install numpy pandas scipy scikit-learn

Installing numpy…
Collecting numpy
  Using cached numpy-1.13.3-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy
Successfully installed numpy-1.13.3

Adding numpy to Pipfile's [packages]…
Installing pandas…
Collecting pandas
  Using cached pandas-0.20.3-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: pytz>=2011k in /home/paulo/.local/share/virtualenvs/datalab-JssD66kq/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: numpy>=1.7.0 in /home/paulo/.local/share/virtualenvs/datalab-JssD66kq/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: python-dateutil>=2 in /home/paulo/.local/share/virtualenvs/datalab-JssD66kq/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: six>=1.5 in /home/paulo/.local/share/virtualenvs/datalab-JssD66kq/lib/python3.6/site-packages (from python-dateutil>=2->pandas)
Installing collected packages: pandas
Successfully installed pandas-0.20.3

Adding pandas to Pipfile's [packages]…
Installing scipy…
Collecting scipy
  Using cached scipy-0.19.1-cp36-cp36m-manylinux1_x86_64.whl
Requirement already satisfied: numpy>=1.8.2 in /home/paulo/.local/share/virtualenvs/datalab-JssD66kq/lib/python3.6/site-packages (from scipy)
Installing collected packages: scipy
Successfully installed scipy-0.19.1

Adding scipy to Pipfile's [packages]…
Installing scikit-learn…
Collecting scikit-learn
  Using cached scikit_learn-0.19.0-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: scikit-learn
Successfully installed scikit-learn-0.19.0

Adding scikit-learn to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 295, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 297, in ssl_wrap_socket
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.2.6', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/cli.py", line 1852, in install
    do_lock(system=system, pre=pre)
  File "/usr/lib/python3.6/site-packages/pipenv/cli.py", line 1083, in do_lock
    pre=pre
  File "/usr/lib/python3.6/site-packages/pipenv/utils.py", line 421, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 101, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 199, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 293, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 171, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 625, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/lib/python3.6/site-packages/pipenv/patched/pip/_vendor/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [Errno 2] No such file or directory
```

Using pipenv v8.2.6

**Comment by joaorafaelm** [comment]
Do you have `certifi` installed?

**Comment by prcastro** [comment]
Installing `certifi` solved the issue. Do you know what happened? Why wasn't certifi installed as a dependency (I installed pipenv from pip)?

**Comment by ncoghlan** [comment]
Reopening as I just ran into the same problem on Debian 9, and it isn't clear to me yet why:

1. The dependency isn't declared at the `pipenv` level; and
2. Running `python3 -m pip install --user certifi` fixed the problem, but `sudo apt-get install python3-certifi` didn't

**Comment by uranusjr** [comment]
I’m guessing it’s probably because them pem files are missing in the manifest, and therefore not vendor-ed correctly.

**Comment by kennethreitz** [comment]
We need to update our MANIFEST.in file :)

**Comment by egorsmkv** [comment]
I have a similar problem. I update the ``certifi`` package on my system and it is solve the problem:

```
sudo pip3 install -U certifi
```

**Comment by firebase007** [comment]
requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 75, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 65, in main
    clear=do_clear,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/resolver.py", line 57, in resolve
    verbose=verbose,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/../pipenv/utils.py", line 452, in resolve_deps
    'https://pypi.org/pypi/{0}/json'.format(name), timeout=10
  File "/usr/local/lib/python2.7/dist-packages/pipenv/../pipenv/vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/../pipenv/vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/../pipenv/vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/../pipenv/vendor/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 2] No such file or directory

/usr/local/lib/python2.7/dist-packages/pipenv/utils.py:1186: ResourceWarning: Implicitly cleaning up TemporaryDirectory '/tmp/pipenv-7ysuw_-requirements'>
  warnings.warn(warn_message, ResourceWarning)``

**Comment by kennethreitz** [comment]
you may be missing the 'certifi' dependency

**Comment by voondo** [comment]
Same issue here. The workaround did not help. 
FYI I just ran : `pipenv install ansible` in an empty pipenv directory.

**Comment by techalchemy** [comment]
`pip install certifi`

If that doesn't help, provide actual debug info or open a new issue

**Comment by Deepakpratap** [comment]
**Hi I am using Manjaro Linux....when i am trying to run pip install certifi...getting below error.**

Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    load_entry_point('pip==10.0.1', 'console_scripts', 'pip3')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/usr/lib/python3.6/site-packages/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/usr/lib/python3.6/site-packages/pip/_internal/index.py", line 20, in <module>
    from pip._vendor.requests.exceptions import SSLError
ModuleNotFoundError: No module named 'pip._vendor.requests.exceptions'
